### ISSUE TITLE
update igb drivers and e1000e

### ISSUE THREAD

**Issue by brammittendorff** [ntop/PF_RING#10]
please update the igb and e1000e drivers there are some issues on debian. i updated them here:
https://github.com/brammittendorff/PF_RING/tree/master/drivers/DNA

**Comment by cardigliano** [comment]
Hi Bram
please send a merge request to the dev branch

Alfredo

**Comment by brammittendorff** [comment]
I will try to test and update all DNA drives, i will create a new merge request for you in this weekend.
