### ISSUE TITLE
i40e_zc not reporting stats to kernel

### ISSUE THREAD

**Issue by jnicholls** [ntop/PF_RING#101]
I'm running the i40e_zc driver on kernel 4.4.12.  Capturing is going well, everything is working as expected.  However, the driver doesn't appear to be reporting stats to the kernel; no rx packets or bytes are being reported from the interface e.g. by checking `ifconfig <interface>`, `ethtool -S <interface>` or view ongoing rates via `sar -n DEV 1`.  Nothing is coming from the /sys stats.

This is latest 6.4.0-stable.

**Comment by jnicholls** [comment]
@cardigliano @lucaderi Can I get some feedback on this issue please?  It's still present in the latest 6.4.0 stable builds. Thanks.

**Comment by cardigliano** [comment]
@jnicholls we are looking into this to see how to fix it, since ZC is a kernel-bypass technology the userspace library is reading card counters (which are clear-on-read) causing this.

**Comment by jnicholls** [comment]
Thanks @cardigliano, appreciate it.  This seems like a new issue because the ixgbe drivers work as expected, albeit they report stats every other second.  Is this clear-on-read a fundamental difference in the i40e driver or chipset?

**Comment by RichardEdell** [comment]
On Stack 1, I see one form of interface counters changing, while the ZC driver is loaded.

[iron@sensor-1 ~]$ date ; ethtool -S em1 | egrep '(port.rx_bytes|port.rx_size|port.rx_unicast|port.rx_multicast|port.rx_broadcast)' ; sleep 1 ; date ; ethtool -S em1 | egrep '(port.rx_bytes|port.rx_size|port.rx_unicast|port.rx_multicast|port.rx_broadcast)'
Tue Jun 14 15:35:04 UTC 2016
     port.rx_bytes: 139453894540
     port.rx_unicast: 167957752
     port.rx_multicast: 37878
     port.rx_broadcast: 356298
     port.rx_size_64: 1742436
     port.rx_size_127: 29826925
     port.rx_size_255: 31301954
     port.rx_size_511: 14413803
     port.rx_size_1023: 6986203
     port.rx_size_1522: 84080608
     port.rx_size_big: 0
Tue Jun 14 15:35:05 UTC 2016
     port.rx_bytes: 139472085978
     port.rx_unicast: 167978015
     port.rx_multicast: 37879
     port.rx_broadcast: 356302
     port.rx_size_64: 1742531
     port.rx_size_127: 29831066
     port.rx_size_255: 31305939
     port.rx_size_511: 14414070
     port.rx_size_1023: 6986761
     port.rx_size_1522: 84091829
     port.rx_size_big: 0

**Comment by jnicholls** [comment]
@RichardEdell yeah good call, port stats are updated even when the queue stats are not.

**Comment by cardigliano** [comment]
There is a patch for this on latest code.
