### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ntop/PF_RING#106]
Would you like to add more error handling for return values from functions like the following?
- [pthread_rwlock_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_init.html) ⇒ [main](https://github.com/ntop/PF_RING/blob/4361586fc4b85ca57ac2e1811aecd353bfc0edda/userland/examples/pfdump.c#L192)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [pfring_open](https://github.com/ntop/PF_RING/blob/e33c6289c16acf4a0da624365c591023ad1ea836/userland/lib/pfring.c#L131)

**Comment by cardigliano** [comment]
We will asap, thank you for reporting. If you want to send pull requests they are welcome.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for your software?
