### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [ntop/PF_RING#107]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first) in [the function "pfring_open"](https://github.com/ntop/PF_RING/blob/e33c6289c16acf4a0da624365c591023ad1ea836/userland/lib/pfring.c#L209).

**Comment by cardigliano** [comment]
Code is more clear with the NULL check. Thank you for reporting anyway.
