### ISSUE TITLE
problem with pf_ring ixgbe drivers on updated debian 8 and updated linux-headers

### ISSUE THREAD

**Issue by brammittendorff** [ntop/PF_RING#11]
uname -r
3.16.0-4-amd64

cat /etc/issue
Debian GNU/Linux 8

/home/bram/PF_RING-6.0.3/drivers/DNA/ixgbe-3.21.2-DNA/src/ixgbe_main.c: At top level:
/home/bram/PF_RING-6.0.3/drivers/DNA/ixgbe-3.21.2-DNA/src/ixgbe_main.c:9353:2: error: unknown field ândo_set_vf_tx_rateâ specified in initializer
  .ndo_set_vf_tx_rate = ixgbe_ndo_set_vf_bw,
  ^

This happens even when i try PF_RING-6.1.1
http://www.nmon.net/packages/ubuntu/14.04/all/ixgbe-dna/

- email me for ssh root at bram@nerd.host

**Comment by lmangani** [comment]
Bram,

Could you retest and let us know if this is still an issue? Thanks!

**Comment by brammittendorff** [comment]
I will tomorrow, i'll give you an update tomorrow!

**Comment by cardigliano** [comment]
Fixed with ixgbe-4.1.2
