### ISSUE TITLE
pf-ring module failed to build on 4.4 LTS kernel

### ISSUE THREAD

**Issue by ikle** [ntop/PF_RING#112]
Locked variants of sk_attach_filer/sk_detach_filter introduced in mainline kernel v4.5 and absent in v4.4. Applied patch tested with Linux 4.4.6 and 6.4.1-stable branch.
[0001-kernel-pf_ring-fix-build-for-4.4.x-kernel.patch.txt](https://github.com/ntop/PF_RING/files/356707/0001-kernel-pf_ring-fix-build-for-4.4.x-kernel.patch.txt)

**Comment by cardigliano** [comment]
Looking at http://lxr.linux.no/linux+v4.5/+search it seems sk_attach_filer is not defined in v4.4,
do you have a standard kernel or Ubuntu LTS? Please provide uname -a

**Comment by ikle** [comment]
I cross compile with mainline 4.4.6 + some minor changes in Wi-Fi stack in OpenEmbedded environment, thus output of uname cannot help you.

https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/include/linux/filter.h?id=refs/tags/v4.4.6#n448 — sk_attach_filter defined at least from 4.4.1 to 4.4.14 (last), locked variant __sk_detach_filter seems to be introduced in 4.4.8 (thus my patch is sligtly wrong).

**Comment by cardigliano** [comment]
Ok, fixed in 9a75714d32dee69b92376b0d7942ca59dcd217a4
Thank you
