### ISSUE TITLE
i40e kernel panic

### ISSUE THREAD

**Issue by protraf-josiah** [ntop/PF_RING#118]
I am able to reproduce a kernel panic using the i40e-1.5.18-zc drivers.
When I have a PF_RING application running using an interface (in this case eth2)
If I run tcpdump on this interface at the same time, then exit tcpdump it will consistently cause a kernel panic. The logs indicate this happens when tcpdump tries to leave promiscuous mode.
From what I can see, the device resets when promiscuous mode is toggled which causes PF_RING to raise an error since the device is in use.

This is the kernel log of when it had happened:
[http://hastebin.com/hibonigira.md](http://hastebin.com/hibonigira.md)

After this happens, the system hard-locks and requires physically rebooted.

**Comment by cardigliano** [comment]
It seems to be due to a card reset (on this card model, setting the promisc leads to a card reset),
it should be handled by avoiding handling promisc state changes when the card is in use, I will
check it.
Are you running the application in ZC mode ("zc:" prefix) for reproducing the issue?

**Comment by protraf-josiah** [comment]
Yes, the application is running in ZC mode. The driver enabling 2 RSS queues on that port also if it helps.

**Comment by dreadiscool** [comment]
Can confirm that this was an issue, I was able to replicate this

**Comment by cardigliano** [comment]
I am not able to reproduce this in our lab, reopen if it is still reproducible with latest code.
