### ISSUE TITLE
youtube pattern do not match traffic

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/PF_RING#12]
I am ddwrt user and some time ago ddwrt developers drop using l7 filters and started using nDPI with iptables (for marking-matching traffic for QoS and Access Restriction purposes). I am not developer nor the network guru. Just simple SOHO user with very basic understanding of routers.
ddwrt has big community and now we have problem because some nDPI protocols (filters) do not work. ddwrt devs says it is not ddwrt problem.  Youtube, Steam do not work... my finfings about this problem are here in bug report on ddwrt TRAC http://svn.dd-wrt.com/ticket/4117#comment:7
If I can provide more informations I would be happy, just to solve this issue. Thx for your work on nDPI it is already great!

**Comment by lucaderi** [comment]
@Mile-Lile Can you please open this bug in nDPI and not on PF_RING ? I.e. https://github.com/ntop/nDPI/issues
