### ISSUE TITLE
using pfcount recv 64byts ,the pps are 961k, is there have any way to improve pps?

### ISSUE THREAD

**Issue by huangh901218** [ntop/PF_RING#120]

**Comment by cardigliano** [comment]
What is the ingress rate and the drivers you are using? Please provide some output from pfcount.

**Comment by huangh901218** [comment]
![Uploading IMG_7109.JPG…]()

**Comment by huangh901218** [comment]
![Uploading IMG_7109
![Uploading IMG_7109.JPG…]()
.JPG…]()

**Comment by huangh901218** [comment]
the driver is e1000e 
![img_7109](https://cloud.githubusercontent.com/assets/20471137/17234068/d32dd75a-5567-11e6-8916-fdedc3389b1f.JPG)

**Comment by cardigliano** [comment]
It seems there is no packet loss at pf_ring level, please note taht most of the e1000e card are not able to do line-rate (14.88Mpps) due to hw limitations.
