### ISSUE TITLE
on centos 6.8 zc ixgbe drivers cannot be loaded

### ISSUE THREAD

**Issue by lucadistefano** [ntop/PF_RING#121]
with kernel 2.6.32-642.3.1 of centos 6.8 ixgbe_zc cannot be loaded
same driver version using kernel 2.6.32-504.16.2 works fine

**Comment by cardigliano** [comment]
It works for me on the same kernel, how did you load the driver? Did you compile it form source or from DKMS packages? Please make sure DKMS did rebuilt/reinstall the module. Thank you.

# uname -a

Linux CentOS_Dev 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lucadistefano** [comment]
![image](https://cloud.githubusercontent.com/assets/1080723/17473096/e7bd9568-5d4e-11e6-894f-14cbd45fcfaf.png)
![image](https://cloud.githubusercontent.com/assets/1080723/17479012/1a243c20-5d70-11e6-9804-054aa27d63e5.png)
![image](https://cloud.githubusercontent.com/assets/1080723/17479015/2774609e-5d70-11e6-927e-d9733de91b3c.png)

the machina have 32GB memory, 2 10G nics configured with zc and a zc cluster.
hugepages configured 4096

seems happens only on 6.7->6.8 upgraded systems
the customer is blocked.
thanks

**Comment by cardigliano** [comment]
Did you upgrade pf_ring and drivers from an older release? Please try removing all packages nad cleaning up the environment from all pf_ring.ko/ixgbe_zc.ko (use updatedb && locate to find all occurrence), then reinstall everything. This to make sure dkms recompile/reinstall all the .ko modules.

**Comment by lucadistefano** [comment]
removed all pf_ring.ko and *_zc.ko reinstalled packages.
some configurations and scripts have changed name pf_ring <-> pfring, hugepages configuration changed.
after reconfiguration has worked but when stopping cluster we get kernel panic again:

![image](https://cloud.githubusercontent.com/assets/1080723/17483007/909a4fa2-5d84-11e6-9d9d-b8fedc7651e7.png)

**Comment by lucadistefano** [comment]
other screenshot:
![image](https://cloud.githubusercontent.com/assets/1080723/17510580/d810ad86-5e1f-11e6-9a26-f90674585554.png)

**Comment by cardigliano** [comment]
@lucadistefano we added some safety check and recompiled the binaries for centos, please update again and let us know. Thank you.

**Comment by lucadistefano** [comment]
can you please list the package version ?
this fix the cluster problem?

**Comment by cardigliano** [comment]
Latest package available, not sure it fixes your issue, we are trying to figure out the source of the problem.

**Comment by cardigliano** [comment]
Please also provide the full configuration (command line/configuration file).
