### ISSUE TITLE
Deadlock inside pfring_mod_set_bpf_filter

### ISSUE THREAD

**Issue by lsimard** [ntop/PF_RING#125]
To reproduce the deadlock the ring must be reentrant (PF_RING_REENTRANT)

The write lock is done at the beginning of pfring_mod_set_bpf_filter

```
if(unlikely(ring->reentrant))
    pthread_rwlock_wrlock(&ring->rx_lock);
```

If the setsockopt fails and returns -1, the function pfring_mod_remove_bpf_filter is then called

```
rc = setsockopt(ring->fd, 0, SO_ATTACH_FILTER, &fcode, sizeof(fcode));

  pcap_freecode(&filter);

  if(rc == -1)
    pfring_mod_remove_bpf_filter(ring);
```

First thing function pfring_mod_remove_bpf_filter does is a write lock on the rx_lock

**Comment by cardigliano** [comment]
Fixed, thank you for reporting.
