### ISSUE TITLE
zcount can't receive packet once stop zsend

### ISSUE THREAD

**Issue by Davehou** [ntop/PF_RING#126]
I use PF stable version 6.4.1, "PF_RING ZC license 6.4.1.160615", and then use e1000e driver. I also use ./load_driver.sh to load PF ring driver and e1000e ZC driver to host. The host system is CentOS 7.1.1503 (linux kernel version: 3.10.0-229).

After load driver, and then use two commands "zsend" && "zconut" at the same time. Once stop "zsend" command, zcount can't receive any packets. About the detailed log, please refer to the below.

[root@localhost examples_zc]# ./zsend -i zc:enp0s25 -c 1 -g 0 -b 8 -l 60
###### 
# ERROR: You do not seem to have a valid PF_RING ZC license 6.4.1.160615 for enp0s25 [Intel 1 Gbit e1000e family]
# ERROR: Please get one at http://shop.ntop.org/.
###### 
# We're now working in demo mode with packet capture and
# transmission limited to 5 minutes
###### 
###### 
# ERROR: You do not seem to have a valid PF_RING ZC license 6.4.1.160615 for enp0s25 [Intel 1 Gbit e1000e family]
# ERROR: Please get one at http://shop.ntop.org/.
###### 

Sending packets to zc:enp0s25
# Estimated CPU freq: 3192516000 Hz
# Absolute Stats: 811'489 pkts – 68'165'076 bytes
# 

Absolute Stats: 1'719'421 pkts – 144'431'364 bytes
# Actual Stats: 907'853.01 pps – 0.61 Gbps [76266288 bytes / 1.0 sec]

…………………………………………….
…………………………………………….
…………………………………………….
# ^CLeaving…

Absolute Stats: 5'236'710 pkts – 439'883'640 bytes
# Actual Stats: 577'629.07 pps – 0.39 Gbps [3668952 bytes / 0.1 sec]
# 

Absolute Stats: 5'236'711 pkts – 439'883'724 bytes
# Actual Stats: 11'904.76 pps – 0.01 Gbps [84 bytes / 0.0 sec]
# [root@localhost examples_zc]# ./zcount -i enp0s25
# Absolute Stats: 1'110'934 pkts (0 drops) – 97'762'192 bytes
# 

Absolute Stats: 2'121'242 pkts (0 drops) – 186'669'296 bytes
# Actual Stats: 1'010'192.83 pps (0.00 drops) – 0.71 Gbps

…………………………………………….
…………………………………………….
# 

Absolute Stats: 9'851'796 pkts (0 drops) – 866'958'048 bytes
# Actual Stats: 0.00 pps (0.00 drops) – 0.00 Gbps
# 

Absolute Stats: 9'851'796 pkts (0 drops) – 866'958'048 bytes
# Actual Stats: 0.00 pps (0.00 drops) – 0.00 Gbps
# 

Absolute Stats: 9'851'796 pkts (0 drops) – 866'958'048 bytes
# Actual Stats: 0.00 pps (0.00 drops) – 0.00 Gbps

**Comment by lucaderi** [comment]
Hello, you are sending packets with zsend over zc:enp0s25. As long as this happens the enp0s25 is detached from the kernel (kernel-bypass) and thus all packets are injected down the link. I see that you have activated zcount in non-kernel bypass mode (you have used -i enp0s25 instead of -i zc:enp0s25) over the same interface and I am not sure I understand what you want to achieve. Please explain but I have the feeling that count should be activated on a different network interface
