### ISSUE TITLE
zbalance Segfault while integrating nDPI functionality

### ISSUE THREAD

**Issue by mmanoj** [ntop/PF_RING#130]
Dear  @Skryabind 

as per our previous discussion ref: https://github.com/ntop/nDPI/issues/223 
I'm integrating nDPI functionality to PF_RING zbalance example, while run it I'm getting segfault core dump. However unable to get much details with gdb. My code block is as below.

if(pfring_zc_recv_pkt(outzq[id], &b, wait_for_packet) > 0) {

u_char *packet = pfring_zc_pkt_buff_data(b, outzq[id]);

struct pfring_pkthdr *header;

memset(&header, 0, sizeof(header));

header->len = b->len; // seg fault causing this line as per the trace.

header->caplen = b->len;

memset((void*)&header->extended_hdr.parsed_pkt, 0, sizeof(struct pkt_parsing_info));

pfring_parse_pkt((u_char_)packet, (struct pfring_pkthdr_)header, 4, 1, 1);

 u_int16_t thread_id = _((u_int16_t_)id);
 /\* allocate an exact size buffer to check overflows */
  uint8_t *packet_checked = malloc(header->caplen);
  memcpy(packet_checked, packet, header->caplen);
  printf("\n---------before process packet-------\n");
  ndpi_workflow_process_packet(ndpi_thread_info[thread_id].workflow, header, packet_checked);

Please advice, I can send full code if you can mention the email.

**Comment by mmanoj** [comment]
Note: I'm using PF_RING only no ZC

**Comment by cardigliano** [comment]
header is a pointer, please declare it as:
struct pfring_pkthdr header;

**Comment by mmanoj** [comment]
@cardigliano Thank you for the clarification, however I'm getting following error and warning. Your advice is great help.

zbalance.c: In function ‘consumer_thread’:
zbalance.c:232:43: error: cannot convert to a pointer type
 pfring_parse_pkt((u_char_)packet, (struct pfring_pkthdr_)header, 4, 1, 1);
                                           ^
zbalance.c:241:70: warning: passing argument 2 of ‘ndpi_workflow_process_packet’ from incompatible pointer type [-Wincompatible-pointer-types]
   ndpi_workflow_process_packet(ndpi_thread_info[thread_id].workflow, &header, packet_checked);
                                                                      ^
In file included from zbalance.c:47:0:
/opt/pf_ring/nDPI/example/ndpi_util.h:129:6: note: expected ‘const struct pcap_pkthdr *’ but argument is of type ‘struct pfring_pkthdr *’
 void ndpi_workflow_process_packet (struct ndpi_workflow \* workflow,

**Comment by mmanoj** [comment]
@Skryabind  can you guide me linking steps with ndpi and pf_ring. I done below steps in makefile but still getting below error:

Makefile:
NDPI=/opt/pf_ring/nDPI/src/include
NDPI2=/opt/pf_ring/nDPI/example
INCLUDE    = -I${PFRINGDIR} -I${PFRING_KERNEL} -I${PCAPDIR} -I${NDPI} -I${NDPI2} `../lib/pfring_config --include` 

#

# User and System libraries

#
LIBS       = ${LIBPFRING} `../lib/pfring_config --libs` ../libpcap/libpcap.a -lpthread @SYSLIBS@ /opt/pf_ring/nDPI/lib/libndpi.la

#

# C compiler and flags

#
CC         = ${CROSS_COMPILE}gcc
CFLAGS     = -O2 -Wall @CFLAGS@ ${INCLUDE}

%.o: %.c zutils.c ndpi_util.c

#     ${CC} ${CFLAGS} -c $< -o $@

error: zbalance.o: In function `consumer_thread':
zbalance.c:(.text+0x34b): undefined reference to`ndpi_workflow_process_packet'
collect2: error: ld returned 1 exit status
Makefile:58: recipe for target 'zbalance' failed
make: **\* [zbalance] Error 1
