### ISSUE TITLE
zbalance Segfault while integrating nDPI

### ISSUE THREAD

**Issue by mmanoj** [ntop/PF_RING#131]
with reference to issue #130 
@cardigliano  I update as advice and successfully compiled. However I'm getting segfault inside ndpi_workflow_process_packet.

Please guide as this will help many people.
## My code : zbalance.c

void\* consumer_thread(void\* _id) {
  long id = (long) _id;

  pfring_zc_pkt_buff *b = buffers[id];

  bind2core(bind_core[id]);

  while(!consumers_stats[id].do_shutdown) {

```
if(pfring_zc_recv_pkt(outzq[id], &b, wait_for_packet) > 0) {
```

u_char *packet = pfring_zc_pkt_buff_data(b, outzq[id]);
struct pfring_pkthdr header;
memset(&header, 0, sizeof(header));

header.len = b->len;

header.caplen = b->len;

memset((void*)&header.extended_hdr.parsed_pkt, 0, sizeof(struct pkt_parsing_info));

pfring_parse_pkt((u_char_)packet, (struct pfring_pkthdr_)&header, 4, 1, 1);

 u_int16_t thread_id = _((u_int16_t_)id);

//CALLING nDPI
 ndpi_workflow_process_packet(ndpi_thread_info[thread_id].workflow, (struct pcap_pkthdr*)&header, packet);

}
# }

Make file:
# 

PFRING_KERNEL=../../kernel
NDPI=/opt/pf_ring/nDPI/src/include
NDPI2=/opt/pf_ring/nDPI/example
INCLUDE    = -I${PFRINGDIR} -I${PFRING_KERNEL} -I${PCAPDIR} -I${NDPI} -I${NDPI2} `../lib/pfring_config --include`
# 
# User and System libraries
# 

LIBS       = ${LIBPFRING} ${LIBPCAP} `../lib/pfring_config --libs` ../libpcap/libpcap.a /opt/pf_ring/nDPI/lib/libndpi.a -lpthread  -lrt 
# 
# C compiler and flags
# 

CC         = ${CROSS_COMPILE}gcc
CFLAGS     = -O2 -Wall  ${INCLUDE}

%.o: %.c %.h zutils.c ndpi_util.c ndpi_util.h
    ${CC} ${CFLAGS} -c $< -o $@
# ndpi_util.o:ndpi_util.c ndpi_util.h

```
#${CC} ${CFLAGS} -c $< -o $@
```

zbalance: zbalance.o ndpi_util.o ${LIBPFRING} Makefile
#     ${CC} ${CFLAGS} zbalance.o ndpi_util.o ${LIBS} -o $@

Error:
Thread 3 "zbalance" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee583700 (LWP 6674)]
0x00000000004055d0 in ndpi_workflow_process_packet ()

@Skryabind I follow same instructions as provided previous thread https://github.com/ntop/nDPI/issues/223

Your advice great help to resolve the issue and integrate ndpi functionality with PF_RING. Looking way forward to resolve this.

**Comment by cardigliano** [comment]
@mmanoj, we do not have enough information to help you (for instance we do not see where ndpi_thread_info is initialised). Please also note this is related to nDPI, not to pf_ring, thus this is not the right place. Actually this is even not an issue as it seems the application you are developing is not calling ndpi_workflow_process_packet correctly, if you need development support please drop us an email.

**Comment by mmanoj** [comment]
@cardigliano  Thanks for the feedback, I will check to figure it out. This is my research project, not for commercial. So I have to develop for testing. If I fix I will update you.
