### ISSUE TITLE
 i40e-zc drivers: load is not distributed between all cores

### ISSUE THREAD

**Issue by AlexeyRN** [ntop/PF_RING#133]
Hello!
I have 40Gbit network using i40e-zc drivers. But when I use zsend i get only 13Gbit because zsend uses only one core, who load increase to 100%. How can I distribute load between all cores to achieve 40Gbit?

```
# ./zsend -i zc:eth7
=========================
Absolute Stats: 251'538'863 pkts - 21'129'264'492 bytes
Actual Stats: 19'362'324.31 pps - 13.01 Gbps [1626604392 bytes / 1.0 sec]
=========================
```

**Comment by cardigliano** [comment]
@AlexeyRN you can enable RSS and run a traffic generator per TX queue (i.e. zsend -i zc:eth7@<i> -g <i>)

**Comment by AlexeyRN** [comment]
Where and how can I enable RSS?
Thank you!

**Comment by cardigliano** [comment]
ethtool -L eth7 combined 4
where 4 is the number of RSS queues

**Comment by AlexeyRN** [comment]
Thank you!
