### ISSUE TITLE
ZC ixgbe driver, does not work on ubuntu 14.04

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/PF_RING#135]
Hi there.
every thing is OK except the ZC ixgbe driver.

saeid@correlator:~$ grep Hugepagesize /proc/meminfo
Hugepagesize:       2048 kB

hugepage config:
saeid@correlator:~$ sysctl -a | grep huge
sysctl: permission denied on key 'fs.protected_hardlinks'
sysctl: permission denied on key 'fs.protected_symlinks'
sysctl: permission denied on key 'kernel.cad_pid'
sysctl: permission denied on key 'kernel.usermodehelper.bset'
sysctl: permission denied on key 'kernel.usermodehelper.inheritable'
sysctl: permission denied on key 'net.ipv4.tcp_fastopen_key'
sysctl: permission denied on key 'net.ipv6.conf.all.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.default.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.em1.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.em2.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.lo.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.p4p1.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.p4p2.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.p4p3.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.p4p4.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.p6p1.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.p6p2.stable_secret'
vm.hugepages_treat_as_movable = 0
vm.hugetlb_shm_group = 0
vm.nr_hugepages = 1024
vm.nr_hugepages_mempolicy = 1024
vm.nr_overcommit_hugepages = 0

pf_ring.ko is loaded.
saeid@correlator:~$ lsmod | grep pf_ring
pf_ring               712704  4

root@correlator:/home/saeid/PF_RING/drivers/intel/ixgbe/ixgbe-4.1.5-zc/src# mount | grep huge
nodev on /mnt/huge type hugetlbfs (rw,pagesize=1GB)
nodev on /mnt/huge type hugetlbfs (rw)
nodev on /mnt/huge type hugetlbfs (rw)

my NIC is Intel® 82599 10 Gigabit Ethernet Controller:
saeid@correlator:~$ ethtool -i p6p1
driver: ixgbe
version: 4.1.5
firmware-version: 0x80000597, 1.180.0
bus-info: 0000:27:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

os version:  
saeid@correlator:~$uname -a
Linux correlator 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

when trying to load driver:
root@correlator:/PF_RING/drivers/intel/ixgbe/ixgbe-4.1.5-zc/src# ./load_driver.sh
rmmod: ERROR: Module pf_ring is in use
insmod: ERROR: could not insert module ../../../../../kernel/pf_ring.ko: File exists
irqbalance: no process found
Configuring p6p1
# IFACE CORE MASK -> FILE

p6p1 0 1 -> /proc/irq/54/smp_affinity
Configuring p6p2
# IFACE CORE MASK -> FILE

p6p2 0 1 -> /proc/irq/57/smp_affinity

---

root@correlator:/PF_RING/drivers/intel/ixgbe/ixgbe-4.1.5-zc/src# zcount -i p6p1                         pfring_zc_create_cluster error [No buffer space available] Please check that pf_ring.ko is loaded and hugetlb fs is mounted

I have no idea why ZC ixgbe driver does not works? UBUNTU 14.04

**Comment by cardigliano** [comment]
Hi @mr-mohsen 
zc does not support 1gb hugepages, please try unmounting all your hugetlbfs and remounting it with 2mb hugepages (please note you have "nodev on /mnt/huge type hugetlbfs (rw,pagesize=1GB)")

**Comment by nickwallen** [comment]
Does ZC still not support 1GB huge pages?  

If I need 1GB pages for another use case, Is it possible to have both 2MB and 1GB THPs in use at the same time?

**Comment by cardigliano** [comment]
ZC supports 2MB only, you can enable 1G pages and use 2 different mountpoints
