### ISSUE TITLE
ixgbe losing traffic

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#139]
I have a cluster with 6 ixgbe rx_only interfaces and balancer to distribute the traffic to 24 threads (by count of cores). 
I monitor pps counters from network cards and also processed packets in my application. I see that app processes maximum 3Mpps, so after that limit packets became loose. 

![graph_image](https://cloud.githubusercontent.com/assets/4038319/18988250/310dd97c-871f-11e6-81e3-787522ecc6f6.png)
In the graph the yellow area is the total pps given from all 6 interfaces counters, black line is the total counter of packets of all my threads.
I count packets pretty simple:

```
if (pfring_zc_recv_pkt(outzq[id], &b, 1) > 0 ) {
   row_pkt_count[thread_id]++;
   ...
```

So I sure there were no bugs in packet counting. Also I always check if the queues are full, but it's not.
So I have that driver receives a packet but not give it to the process. 
Where might be a problem? Buffers, slots, or something else?

I tried to change active_wait in balancer, and also wait_for_packet in pfring_zc_recv_pkt - no result.
Load of every cores is no more than 70% in time of losing traffic. _ethtool -S eth*_ shows no errors.

**Comment by cardigliano** [comment]
@Skryabind what is the load on the zbalance core when loosing packets? Where do you read loss counters? Could you provide some output from zbalance stats?

**Comment by Skryabind** [comment]
@cardigliano I just see mismatch between incoming traffic and processing traffic. Interface counters shows no errors, no drops. I'll try to run zbalance, but this server is in production, so I need to plan this step.

**Comment by cardigliano** [comment]
@Skryabind I thought you were using zbalance_ipc, now I got you are using your own balancer, no need to tun zbalance. I guess you have a balancer thread (ZC worker?) distributing the traffic, could you provide the cpu load where that thread is running, and ingress (interfaces) and egress queues (balancer-to-threads) stats?

**Comment by Skryabind** [comment]
Yes, I have a balancer distributing the traffic, I define it like that:

```
    zw = pfring_zc_run_balancer(
            inzq,
            outzq,
            watch_interfaces_count,
            num_threads,
            wsp,
            round_robin_bursts_policy,
            NULL /* idle callback */,
            NULL,
            (void *) ((long) num_threads),
            !wait_for_packet,
            -1
    );
```

I tried to change wait_for_packet to 1 and to 0.
I don't know which core uses balancer, but all cores are not overloaded:

```
top - 21:45:13 up 93 days, 12:59,  4 users,  load average: 9,58, 9,03, 8,73
Tasks: 281 total,   1 running, 280 sleeping,   0 stopped,   0 zombie
%Cpu0  : 41,5 us,  0,3 sy,  0,0 ni, 58,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu1  : 41,6 us,  0,7 sy,  0,0 ni, 57,8 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu2  : 35,8 us,  1,0 sy,  0,0 ni, 63,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu3  : 40,4 us,  0,7 sy,  0,0 ni, 58,9 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu4  : 43,6 us,  0,7 sy,  0,0 ni, 55,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu5  : 42,0 us,  0,7 sy,  0,0 ni, 57,3 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu6  : 35,3 us,  0,7 sy,  0,0 ni, 64,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu7  : 43,7 us,  0,7 sy,  0,0 ni, 55,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu8  : 24,5 us,  0,3 sy,  0,0 ni, 75,2 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu9  : 45,3 us,  0,0 sy,  0,0 ni, 54,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu10 : 29,3 us,  0,7 sy,  0,0 ni, 70,0 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu11 : 41,9 us,  1,0 sy,  0,0 ni, 57,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu12 : 26,2 us,  0,3 sy,  0,0 ni, 73,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu13 : 34,7 us,  0,7 sy,  0,0 ni, 64,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu14 : 24,7 us,  0,7 sy,  0,0 ni, 74,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu15 : 31,3 us,  1,0 sy,  0,0 ni, 67,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu16 : 27,2 us,  0,3 sy,  0,0 ni, 72,5 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu17 : 34,0 us,  0,7 sy,  0,0 ni, 65,3 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu18 : 27,4 us,  0,3 sy,  0,0 ni, 72,3 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu19 : 28,9 us,  0,7 sy,  0,0 ni, 70,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu20 : 23,6 us,  0,3 sy,  0,0 ni, 76,0 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu21 : 35,9 us,  0,7 sy,  0,0 ni, 63,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu22 : 25,1 us,  0,3 sy,  0,0 ni, 74,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu23 : 33,6 us,  0,7 sy,  0,0 ni, 65,8 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem:  66001344 total, 44438224 used, 21563120 free,   147580 buffers
KiB Swap: 11869180 total,  1049820 used, 10819360 free.  1123904 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 89006 root      20   0 18,141g 8,635g   6332 S 844,5 13,7   2601:40 dsf2
```

How I can get egress queues (balancer-to-threads) stats? I know only one way - is the self-made counters in the code. This counters you can see in the graph above - black line is total (summed) count of incoming packets on all threads. Yellow area is the total incoming packets count on interfaces (getting from system counters)

Additional info:
I open interfaces like that:
`inzq[i] = pfring_zc_open_device(zc, watch_interfaces[i], rx_only, 0);`
And read the traffic:
`if (pfring_zc_recv_pkt(outzq[id], &b, wait)>0)`
I tried to set 'wait' to 1 and 0.

**Comment by cardigliano** [comment]
Please print/draw recv and drop stats using pfring_zc_stats() on all inzq[] and outzq[].
As of the top output, I guess it wasn't at the time the black line didn't match the yellow area.

**Comment by Skryabind** [comment]
Oh, I didn't know about this function, it's my fault. Please give my a time to insert this in my code and collect a statistic.

**Comment by Skryabind** [comment]
Hello! Here is all counters.
First, counters of inzq (6 incoming interfaces):

```
in_balancer_in_0    recv: 1948798762    sent: 0 drop: 21800609
in_balancer_in_1    recv: 529024631     sent: 0 drop: 3096944
in_balancer_in_2    recv: 2556778872    sent: 0 drop: 542852524
in_balancer_in_3    recv: 2344578829    sent: 0 drop: 3643734989
in_balancer_in_4    recv: 3869098520    sent: 0 drop: 513533481
in_balancer_in_5    recv: 2417834028    sent: 0 drop: 3816516130
```

Second, counters of outzq:

```
in_balancer_out_0   recv: 242906393     sent: 242906393     drop: 5028462
in_balancer_out_1   recv: 3156589292    sent: 3156589298    drop: 1807626
in_balancer_out_2   recv: 3803752704    sent: 3803752718    drop: 698412
in_balancer_out_3   recv: 2337036214    sent: 2337036214    drop: 669381
in_balancer_out_4   recv: 3311741865    sent: 3311741865    drop: 1135492
in_balancer_out_5   recv: 731817172     sent: 731817175     drop: 1282974
in_balancer_out_6   recv: 2549141646    sent: 2549141650    drop: 860848
in_balancer_out_7   recv: 1355481469    sent: 1355481469    drop: 4108314
in_balancer_out_8   recv: 3700237677    sent: 3700237683    drop: 2293395
in_balancer_out_9   recv: 49825658      sent: 49825667      drop: 1561026
in_balancer_out_10  recv: 3720155044    sent: 3720155044    drop: 2023785
in_balancer_out_11  recv: 3107100924    sent: 3107100929    drop: 1330914
in_balancer_out_12  recv: 379843101     sent: 379843118     drop: 1759392
in_balancer_out_13  recv: 4120472833    sent: 4120472850    drop: 2054099
in_balancer_out_14  recv: 590616679     sent: 590616680     drop: 257612
in_balancer_out_15  recv: 551710456     sent: 551710457     drop: 842588
in_balancer_out_16  recv: 1506182179    sent: 1506182181    drop: 1963857
in_balancer_out_17  recv: 3050941029    sent: 3050941038    drop: 638716
in_balancer_out_18  recv: 3858934334    sent: 3858934338    drop: 172646
in_balancer_out_19  recv: 2756190649    sent: 2756190652    drop: 1382141
in_balancer_out_20  recv: 400553753     sent: 400553758     drop: 435753
in_balancer_out_21  recv: 3517402464    sent: 3517402466    drop: 420147
in_balancer_out_22  recv: 3385427031    sent: 3385427033    drop: 1069508
in_balancer_out_23  recv: 99094016      sent: 99094017      drop: 3882052
```

Total recv of inzq: 13666113642, total Drops: 8541534677
Total sent of outzq: 52283154693, total recv: 52283154582 total drops: 37679140
I thought that counters will be equal, but it's dramatically different (13666113642 vs 52283154693).
Drops had been increased in time when the black line didn't match the yellow area.

**Comment by cardigliano** [comment]
@Skryabind it seems you have drops both at traffic distribution and processing (consumer threads), so it seems the problem is that the system in general has too much work to do and cannot keep up with ingress rate. A first step in order to improve performance and decouple packet distribution and processing is using core affinity (this does not solve memory bandwidth issues anyway): please dedicate a physical core to the distribution thread setting core affinity, and the same for processing threads. After that please provide me the top output and in/out stats when the system is loosing traffic.

**Comment by Skryabind** [comment]
@cardigliano thanks for that, I've dedicated the distribution thread to distinct core, now this core is 100% user load, but this is because I turned on the active wait mode. This evening I'll see the counters in both active and passive wait mode.

**Comment by Skryabind** [comment]
Hi, @cardigliano , I'm happy because my problem is resolved! I did as you said (I dedicated distribution thread in separate core) and now I have zero drops, all works fine, thanks!
![graph_image](https://cloud.githubusercontent.com/assets/4038319/19851874/e1f1dc64-9f81-11e6-980a-5307c34083d8.png)
Currently, 4.5M packets is near to limit for one distribution thread (distribution uses almost 100% of one core)

**Comment by cardigliano** [comment]
Great!
