### ISSUE TITLE
would you please to supply a pure Go userland lib for pf_ring?

### ISSUE THREAD

**Issue by wheelcomplex** [ntop/PF_RING#14]
Dear Luca,

There is a CGO binding for pf_ring(https://godoc.org/github.com/google/gopacket/pfring), because huge overhead( CGO call vs Go call ~= 500x) to call from Go to C functions by CGO, the binding package is no for high speed packet programming.

BTW: CGO overhead test code:  http://play.golang.org/p/GXTwp6Ybot

Best regard,

**Comment by cardigliano** [comment]
Hi 
sorry but there is no plan to add native Go support to pf_ring at the moment.

Best Regards
Alfredo

**Comment by lucaderi** [comment]
@wheelcomplex We don't use Go so we lack the knowledge to carry on this task. However if you need our help to implement it (from the C side I mean) we can definitively assist you.
