### ISSUE TITLE
Different reported packet rates in cento

### ISSUE THREAD

**Issue by JeremyAshton-shopify** [ntop/PF_RING#140]
As discussed on ntop-misc mailing list:

Here is the deal.  If I configure zbalance_ipc listen on 4x interfaces
and then map those queues to dummy interfaces; Cento shows the
bandwidth 100x more than reality.  i.e. it shows 27.91Gbps whereas it
is actually ~279 Mbit/s.

pfcount on dummy0 interface:
`$ sudo pfcount -i dummy0 -c 100`

```
=========================
Absolute Stats: [152'733 pkts total][0 pkts dropped][0.0% dropped]
[152'733 pkts rcvd][108'744'822 bytes rcvd][50'907.23 pkt/sec][289.96 Mbit/sec]
=========================
Actual Stats: [41'132 pkts rcvd][1'000.05 ms][41'129.73 pps][0.25 Gbps]
=========================

=========================
Absolute Stats: [189'340 pkts total][0 pkts dropped][0.0% dropped]
[189'340 pkts rcvd][134'926'703 bytes rcvd][47'331.02 pkt/sec][269.83 Mbit/sec]
=========================
Actual Stats: [36'607 pkts rcvd][1'000.11 ms][36'602.82 pps][0.21 Gbps]
=========================
```

cento on dummy0 interface (should be 1/4 of total bandwidth):
`$ sudo /usr/local/bin/zbalance_ipc -i zc:<int1>,zc:<int2>,zc:<int3>,zc:<int4> -c10 -n4 -m1 -g0 -u /mnt/hugepages/ -r 0:dummy0 -r 1:dummy1 -r 2:dummy2 -r 3:dummy3`
`$ sudo cento -i dummy0`
03/Oct/2016 16:58:26 [NetworkInterface.cpp:990] [dummy0] [12'458'091 pps/27.91 Gbps][29'412/0/0/512'000 act/exp/drop/max flows][0/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 16:58:27 [NetworkInterface.cpp:990] [dummy0] [12'447'559 pps/27.88 Gbps][29'412/0/0/512'000 act/exp/drop/max flows][0/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 16:58:28 [NetworkInterface.cpp:990] [dummy0] [12'753'627 pps/28.57 Gbps][29'412/0/0/512'000 act/exp/drop/max flows][0/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 16:58:29 [NetworkInterface.cpp:990] [dummy0] [12'385'380 pps/27.74 Gbps][29'412/0/0/512'000 act/exp/drop/max flows][0/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 16:58:30 [NetworkInterface.cpp:990] [dummy0] [12’261'717 pps/27.47 Gbps][29'412/0/0/512'000 act/exp/drop/max flows][0/0 RX/TX pkt drops][0 TX pps]

cento on raw interface with zc:
`$ sudo cento -i zc:<int1> -i zc:<int2> -i zc:<int3> -i zc:<int4> -g 1,2,3,4 -C 100 -H`
03/Oct/2016 17:23:21 [NetworkInterface.cpp:990] [zc:<int1>] [34'636 pps/0.23 Gbps][12'454/0/0/512'000 act/exp/drop/max flows][150'083/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 17:23:21 [NetworkInterface.cpp:990] [zc:<int2>] [16'778 pps/0.14 Gbps][5'815/0/0/512'000 act/exp/drop/max flows][38'765/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 17:23:21 [NetworkInterface.cpp:990] [zc:<int3>] [93'670 pps/0.47 Gbps][31'722/0/0/512'000 act/exp/drop/max flows][128'497/0 RX/TX pkt drops][0 TX pps]
03/Oct/2016 17:23:21 [NetworkInterface.cpp:990] [zc:<int4>] [67 pps/0.00 Gbps][160/0/0/512'000 act/exp/drop/max flows][0/0 RX/TX pkt drops][0 TX pps]

**Comment by cardigliano** [comment]
@JeremyAshton-shopify as I said on the ML, this seems to be related to a name clash in cento:
“dummy” is a special device name used in cento for generating synthetic traffic in order to simulate 
a capture interface with high speed, please try renaming the interface (before running balance/cento) with:
ip link set dummy0 name myname0
In any case we will somehow change this in order to avoid simular issues in future.
