### ISSUE TITLE
Segfault on Centos 7.2 with i40e

### ISSUE THREAD

**Issue by jemcek** [ntop/PF_RING#144]
Hi, 

I have a fresh install of PF_RING on Centos 7.2 using the nightly build rpm packages.
-PFRING_ZC v.6.5.0.161006
- driver i40e_zc

Starting the pfsend, pfcount or zcount,  the apps crash immediately:

[root@kobila ~]# pfsend -i zc:ens1f0
Sending packets on zc:ens1f0
Segmentation fault
[root@kobila ~]# zcount -i zc:ens1f0
Segmentation fault

[root@kobila ~]# tail /var/log/messages
 kernel: pfsend[10252]: segfault at 0 ip 00007f423e449a78 sp 00007ffca5df1748 error 4 in libc-2.17.so[7f423e317000+1b7000]
kernel: zcount[10381]: segfault at 0 ip 00007f7252a6ca78 sp 00007fff61b02528 error 4 in libc-2.17.so[7f725293a000+1b7000]

[root@kobila pf_ring]# grep PF_RING /var/log/messages
Oct 20 14:20:00 kobila kernel: [PF_RING] Welcome to PF_RING 6.5.0 ($Revision: dev:919561fd3c69aa665051a721d7f972f60f344da0$)#012(C) 2004-16 ntop.org
Oct 20 14:20:00 kobila kernel: [PF_RING] registered /proc/net/pf_ring/
Oct 20 14:20:00 kobila kernel: [PF_RING] Min # ring slots 4096
Oct 20 14:20:00 kobila kernel: [PF_RING] Slot version     16
Oct 20 14:20:00 kobila kernel: [PF_RING] Capture TX       Yes [RX+TX]
Oct 20 14:20:00 kobila kernel: [PF_RING] IP Defragment    No
Oct 20 14:20:00 kobila kernel: [PF_RING] Initialized correctly
Oct 20 14:20:03 kobila pf_ring: Starting PF_RING module: tx unmodified, ignoring
Oct 20 14:20:03 kobila kernel: [PF_RING-ZC] i40e_up_complete: attach ens1f0 [pf start=2432696320 len=8388608][cache_line_size=128][MSIX enabled]
Oct 20 14:20:05 kobila kernel: [PF_RING-ZC] i40e_up_complete: attach ens1f1 [pf start=2424307712 len=8388608][cache_line_size=128][MSIX enabled]
Regards, Miha

**Comment by JeremyAshton-shopify** [comment]
also segfaults on ubuntu:

```
$ sudo /usr/local/bin/zbalance_ipc -i zc:<redacted> -c 100 -n 2 -m 2

Oct 20 20:09:01 <redacted> kernel: [  399.025425] zbalance_ipc[11106]: segfault at 0 ip 00007ff9d6966d63 sp 00007ffee6c02fc8 error 4 in libc-2.19.so[7ff9d68e0000+1ba000]
Oct 20 20:09:01 <redacted> kernel: [  399.025425] zbalance_ipc[11106]: segfault at 0 ip 00007ff9d6966d63 sp 00007ffee6c02fc8 error 4 in libc-2.19.so[7ff9d68e0000+1ba000]

$ sudo /usr/local/bin/zbalance_ipc -i zc:<redacted> -c 100 -n 1 -m 1
Oct 20 20:09:30 <redacted> kernel: [  428.785586] zbalance_ipc[11547]: segfault at 0 ip 00007f162d9f0d63 sp 00007fffae330f08 error 4 in libc-2.19.so[7f162d96a000+1ba000]
Oct 20 20:09:30 <redacted> kernel: [  428.785586] zbalance_ipc[11547]: segfault at 0 ip 00007f162d9f0d63 sp 00007fffae330f08 error 4 in libc-2.19.so[7f162d96a000+1ba000]

$ uname -r
3.19.0-73-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:  Ubuntu
Description:  Ubuntu 14.04.5 LTS
Release:  14.04
Codename:  trusty

$ dkms status
e1000e-zc, 3.2.7.1.932, 3.19.0-73-generic, x86_64: installed
fm10k-zc, 0.20.1.932, 3.19.0-73-generic, x86_64: installed
i40e-zc, 1.5.18.932, 3.19.0-73-generic, x86_64: installed
igb-zc, 5.3.3.5.932, 3.19.0-73-generic, x86_64: installed
ixgbe-zc, 4.1.5.932, 3.19.0-73-generic, x86_64: installed
pfring, 6.5.0, 3.19.0-73-generic, x86_64: installed
sysdig, 0.8.0, 3.16.0-77-generic, x86_64: installed
sysdig, 0.8.0, 3.19.0-71-generic, x86_64: installed
sysdig, 0.8.0, 3.19.0-73-generic, x86_64: installed

$ cat /proc/net/pf_ring/info
PF_RING Version          : 6.5.0 (dev:919561fd3c69aa665051a721d7f972f60f344da0)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
```

**Comment by cardigliano** [comment]
Hi guys
it seems you updated in the middle of a big change to the dev repo (https://github.com/ntop/PF_RING/commit/919561fd3c69aa665051a721d7f972f60f344da0)
Please update again and everything should work. BTW: please also make sure the new pf_ring.ko gets loaded before running applications, as some data structure changed and everything needs to be in sync.

**Comment by jemcek** [comment]
I can confirm it works after the update.
