### ISSUE TITLE
pfcount - problem in QinQ vlan header decoding

### ISSUE THREAD

**Issue by jemcek** [ntop/PF_RING#145]
With double tagged packets the pfcount verbose output (-v 1 or -v 2) is wrong. Only inner vlan header is decoded.

[root@kobila ~]# pfcount -i zc:ens1f0  -v 2
Using PF_RING v.6.5.0

02:00:00.000000000 [RX][if_index=0][00:19:E2:B8:3F:C4 -> A8:9D:21:68:77:C0] [vlan 50] [IPv4][93.103.1.87:0 -> 193.2.253.130:0] [l3_proto=50][hash=3408400516][tos=0][tcp_seq_num=0] [caplen=126][len=126][eth_offset=0][l3_offset=22][l4_offset=42][payload_offset=42]
A8 9D 21 68 77 C0 00 19 E2 B8 3F C4 81 00 04 52 81 00 00 32 08 00 45 00 00 68 3C 5A 00 00 3E 32 22 C7 5D 67 01 57 C1 02 FD 82 74 97 3A 6A 00 00 97 92 FF 2F D0 01 02 03 03 04 3E D1 10 58 2A 74 A8 2F 4F DD 5E DC 9D 62 15 68 D1 72 03 8E E0 2E B3 95 AC 18 5F 35 68 B3 B0 61 7D 5B 75 C1 5D D2 85 5E D7 57 CA 2C 90 86 B1 08 9A 1C A9 3E 5C 92 75 A7 0E 58 ED E9 0F 12 45 FD 2B E4 5D 6D

Inner vlan header is decoded (81 00 00 32) while the outer is missing (81 00 04 52) in the verbose output. 

Similar tcpdump output:

[root@kobila ~]# tcpdump -n -i ens1f0 -e 
08:23:13.866983 a8:9d:21:68:77:c0 > 2c:21:72:f1:67:f2, ethertype 802.1Q (0x8100), length 1514: vlan 2106, p 0, ethertype 802.1Q, vlan 50, p 0, ethertype IPv4, 212.235.206.147.ltp-deepspace > 193.77.158.143.50974: Flags [.], seq 1933226031:1933227483, ack 3121704434, win 3456, length 1452

**Comment by cardigliano** [comment]
Inner VLAN was used as VLAN in packet decoding, with commit https://github.com/ntop/PF_RING/commit/75d190bb0cca9884731938b04373b11252784545 first VLAN is used, and also QinQ VLAN is added to metadata (and printed in pfcount)
