### ISSUE TITLE
[pf_ring] whitelist the interfaces that are configured by /etc/init.d/pf_ring

### ISSUE THREAD

**Issue by JeremyAshton-shopify** [ntop/PF_RING#147]
The startup script for pf_ring configures all interfaces except the one with the default route.  This should not happen.  For instance, we use bonded interfaces.  So, pf_ring opts to configure the underlying interface based on packet capture.  Instead of blacklisting the interface with the default route one should whitelist which interfaces should be configured.  pf_ring should not be so greedy.  ;)

**Comment by cardigliano** [comment]
IMHO a whitelist-based approach requires too much effort from the users, and also breaks backward compatibility. What we can add is a blacklist using a configuration file.

**Comment by srinathman** [comment]
I suggest a balanced approach.  Like this we can introduce a white list feature and keep backward compatibility

Create /etc/sysconfig/pf_ring with a variable "INTERFACES_WHITELIST" commented by default.
`#INTERFACES_WHITELIST="eth4 eth5"`

Change this line in the init script

`INTERFACES="$(cat /proc/net/dev | grep ':' | cut -d ':' -f 1|grep -v 'lo' | tr '\n' ' '| sed 's/  / /g')"`

with the following:

```
if [ "${INTERFACES_WHITELIST}" != "" ]; then
     INTERFACES="$INTERFACES_WHITELIST"
else
     INTERFACES="$(cat /proc/net/dev | grep ':' | cut -d ':' -f 1|grep -v 'lo' | tr '\n' ' '| sed 's/  / /g')"
fi
```

and finally, add this line somewhere at the top of the init script:

```
# pull in sysconfig settings
[ -f /etc/sysconfig/pf_ring ] && . /etc/sysconfig/pf_ring
```

**Comment by cardigliano** [comment]
@srinathman your approach is nice, however it solves a different problem, it does not prevent the script from loading the ZC driver for the non-whitelisted interfaces, it just prevents the script from configuring them. I think we should add both checks. As of the sysconfig file, I would add it to /etc/pf_ring that's where we have all configurations (actually the sysconfig folder is system dependent).

**Comment by cardigliano** [comment]
Commit 1f76cdb996309ce58221c79573daf05903e0d117 should handle both cases, you can create a configuration file /etc/pf_ring/interfaces.conf like in the example below:

MANAGEMENT_INTERFACES="eth0 eth1"
CAPTURE_INTERFACES="eth2 eth3 eth4 eth5"
