### ISSUE TITLE
DAG support within PF_RING packages

### ISSUE THREAD

**Issue by johnatspark1** [ntop/PF_RING#148]
While it is possible to compile PF_RING to support the Endace DAG interface/driver, it is not yet available in the PF_RING package.

**Comment by lucaderi** [comment]
@johnatspark1 We have included DAG inside the PF_RING packages. We need to further test the code and implement TX (so far only RX is enabled) but you can start testing it in the meantime.

**Comment by johnatspark1** [comment]
I would be happy to test.  Please let me know how/where to find/install those packages.  Robert Cotter @ Endace is also willing to test.

**Comment by cardigliano** [comment]
Please use dev packaget (aka nightly builds) available at http://packages.ntop.org

**Comment by johnatspark1** [comment]
nprobe still not seeing the dag card....
Is there a way to query what interface PF_RING sees?

[root@localhost ~]# nprobe -n 172.25.32.67:2055 -i dag0
07/Nov/2016 09:49:39 [nprobe.c:3434] ERROR: Invalid nProbe license (/etc/nprobe.license) [Missing license file]
07/Nov/2016 09:49:39 [nprobe.c:3441] ERROR: *****************************************************
07/Nov/2016 09:49:39 [nprobe.c:3442] ERROR: *\*                                                 **
07/Nov/2016 09:49:39 [nprobe.c:3443] ERROR: *\*  Switching to DEMO MODE (missing valid license) **
07/Nov/2016 09:49:39 [nprobe.c:3444] ERROR: *\*                                                 **
07/Nov/2016 09:49:39 [nprobe.c:3445] ERROR: *\*  Purchase your nProbe license at                **
07/Nov/2016 09:49:39 [nprobe.c:3446] ERROR: *\*       https://shop.ntop.org/                    **
07/Nov/2016 09:49:39 [nprobe.c:3447] ERROR: *\*                                                 **
07/Nov/2016 09:49:39 [nprobe.c:3448] ERROR: *****************************************************
07/Nov/2016 09:49:39 [nprobe.c:7404] ERROR: ***************************************************************
07/Nov/2016 09:49:39 [nprobe.c:7405] ERROR: \* NOTE: This is a DEMO version limited to 25000 flows export.  *
07/Nov/2016 09:49:39 [nprobe.c:7406] ERROR: ***************************************************************
07/Nov/2016 09:49:39 [nprobe.c:4961] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
07/Nov/2016 09:49:39 [nprobe.c:4964] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
07/Nov/2016 09:49:39 [nprobe.c:5064] Welcome to nProbe v.7.5.161106 ($Revision: 5466 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
07/Nov/2016 09:49:39 [nprobe.c:5074] Running on CentOS Linux release 7.2.1511 (Core)
07/Nov/2016 09:49:39 [nprobe.c:5085] [LICENSE] nProbe SystemId: 12FBFEEB00000749
07/Nov/2016 09:49:39 [nprobe.c:7422] Welcome to nProbe v.7.5.161106 for x86_64-unknown-linux-gnu
07/Nov/2016 09:49:39 [plugin.c:1051] 0 plugin(s) enabled
07/Nov/2016 09:49:39 [nprobe.c:6943] Non IPv4/v6 traffic is discarded according to the template
07/Nov/2016 09:49:39 [util.c:432] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
07/Nov/2016 09:49:39 [util.c:443] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
07/Nov/2016 09:49:39 [nprobe.c:5617] Using packet capture length 128
07/Nov/2016 09:49:39 [util.c:4401] ERROR: Cannot get hw addr for dag0
07/Nov/2016 09:49:40 [nprobe.c:5670] ERROR: Unable to open interface dag0.
07/Nov/2016 09:49:40 [nprobe.c:7523] ERROR: Unable to open interface dag0 (dag0: No such device exists (SIOCGIFHWADDR: No such device))
07/Nov/2016 09:49:40 [nprobe.c:7525] ERROR: Try using -i none if you do not want capture from a NIC

**Comment by cardigliano** [comment]
@johnatspark1 please note 1. you should use dag:0 as interface name, 2. nprobe is using standard libpcap as capture engine. Please try first of all with pfcount -i dag:0

**Comment by johnatspark1** [comment]
Getting stats from pfcount and when I run nprobe with "-i dag:0" it seems to work.
The issue I have now is when I try to run a second instance of nprobe using "-i dag:0" it gives the following errors:
07/Nov/2016 13:28:04 [util.c:4401] ERROR: Cannot get hw addr for 0
Error attaching to stream 0: is it already attached to another application?
07/Nov/2016 13:28:04 [nprobe.c:5670] ERROR: Unable to open interface dag:0.
07/Nov/2016 13:28:04 [nprobe.c:7523] ERROR: Unable to open interface dag:0 (dag:0: No such device exists (SIOCGIFHWADDR: No such device))

it does not have an issue running multiple instances using another interface. (like "-i ens4")

Here is ultimately what I'm trying to run:
nprobe -E "0:1" -f "!tcp" -a -n 10.65.24.57:2055 -i dag:0 -u 1 -Q 2 -t 60 -d 15 -V 10 -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %L4_DST_PORT %L4_SRC_PORT %IN_BYTES %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %PROTOCOL %IPV4_SRC_MASK %IPV4_DST_MASK %IN_SRC_MAC %OUT_DST_MAC" -G

nprobe -E "0:2" -f "tcp and not(port 80)" -a -n 10.65.24.57:2055 -i dag:0 -u 1 -Q 2 -t 60 -d 15 -V 10 -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %L4_DST_PORT %L4_SRC_PORT %IN_BYTES %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %PROTOCOL %IPV4_SRC_MASK %IPV4_DST_MASK %IN_SRC_MAC %OUT_DST_MAC %TCP_FLAGS %CLIENT_NW_DELAY_MS %SERVER_NW_DELAY_MS %APPL_LATENCY_MS" -G

nprobe -E "0:3" -f "tcp and port 80" -a -n 10.65.24.57:2055 -i dag:0 -u 1 -Q 2 -t 60 -d 15 -V 10 -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %L4_DST_PORT %L4_SRC_PORT %IN_BYTES %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %PROTOCOL %IPV4_SRC_MASK %IPV4_DST_MASK %IN_SRC_MAC %OUT_DST_MAC %TCP_FLAGS %CLIENT_NW_DELAY_MS %SERVER_NW_DELAY_MS %APPL_LATENCY_MS %HTTP_URL %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME" -G

**Comment by sfd** [comment]
DAG cards only support one application using each stream at a time, regardless of the API used. You will not be able to use both pfcount and nprobe on dag0:0 at the same time.

Separate applications can be run on different streams simultaneously, e.g. dag0:0 and dag0:2, however the user must configure traffic steering to the streams.

**Comment by cardigliano** [comment]
Please note that you should use the pf_ring notation which is module:port@stream (stream support has just been added, please update), for example: dag:0@0 (in case of DAG we also support as exception the notation dag:0:0 to avoid user mistakes)

**Comment by sfd** [comment]
I assume -i dag:dag0:0 would also work, as you use dag_parse_name()?

**Comment by cardigliano** [comment]
Correct
