### ISSUE TITLE
PF_RING DKMS not performed when the kernel is updated

### ISSUE THREAD

**Issue by lucaderi** [ntop/PF_RING#154]
When the Linux kernel is updated, the PF_RING kernel module is not recompiled and thus the kernel module does not load at the next boot with the new kernel

Nov  6 09:02:18 luca-pc kernel: [   24.527036] pf_ring: module verification failed: signature and/or required key missing - tainting kernel
Nov  6 09:02:18 luca-pc kernel: [   24.527059] pf_ring: disagrees about version of symbol skb_copy_bits
Nov  6 09:02:18 luca-pc kernel: [   24.527060] pf_ring: Unknown symbol skb_copy_bits (err -22)
Nov  6 09:02:18 luca-pc kernel: [   24.527065] pf_ring: disagrees about version of symbol skb_put
Nov  6 09:02:18 luca-pc kernel: [   24.527066] pf_ring: Unknown symbol skb_put (err -22)
Nov  6 09:02:18 luca-pc kernel: [   24.527069] pf_ring: disagrees about version of symbol dev_queue_xmit
Nov  6 09:02:18 luca-pc kernel: [   24.527070] pf_ring: Unknown symbol dev_queue_xmit (err -22)
Nov  6 09:02:18 luca-pc kernel: [   24.527074] pf_ring: disagrees about version of symbol sock_wmalloc
Nov  6 09:02:18 luca-pc kernel: [   24.527075] pf_ring: Unknown symbol sock_wmalloc (err -22)
Nov  6 09:02:18 luca-pc kernel: [   24.527078] pf_ring: disagrees about version of symbol __sk_attach_filter
Nov  6 09:02:18 luca-pc kernel: [   24.527079] pf_ring: Unknown symbol __sk_attach_filter (err -22)
Nov  6 09:02:18 luca-pc kernel: [   24.527081] pf_ring: disagrees about version of symbol dev_add_pack
Nov  6 09:02:18 luca-pc kernel: [   24.527082] pf_ring: Unknown symbol dev_add_pack (err -22)

**Comment by novaksam** [comment]
Having this issue too; here's a gist from a compilation failure for DKMS
https://gist.github.com/novaksam/adab3090dc3e69380be2e1574546406b

**Comment by novaksam** [comment]
I think the i40e driver needs to get updated to 1.5.25; I was able to compile that on the latest centOS7, but not a base 1.5.18

**Comment by cardigliano** [comment]
All the drivers should compile now on centos 7, fixes are available on github dev or from packages in 1h.

**Comment by cardigliano** [comment]
Fixed
