### ISSUE TITLE
pf_ring zc stop capturing packet after a while

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/PF_RING#157]
Hi.
I am using  PF_RING 6.5.0. and using the following piece of my code to capture packets :
```
    void runZCConnection() {
        long int i = 0;
        for (;;) {
            if (likely(pfring_zc_recv_pkt(zqc, &buffer_connection, _wait_for_packet) >= 0)) {
                u_char *pkt_data = pfring_zc_pkt_buff_data(buffer_connection, zqc);
                std::string payload(pkt_data + _ConnectionHeaderSize, pkt_data + _snapLengthConnection);
                _Connection_buffer[i] = payload;
                _Connection_Number++;
                i = (i + 1) % _Max_Element_Connection_buffer;
                continue;
            }
            break;
        }
        LOG_INFO("***************************************************************************");
        LOG_INFO("***********************Stop Capturing Connections**************************");
        LOG_INFO("***************************************************************************");
    }
```
my NIC is:

> root@ubuntu:/u02/ng4/m2# ethtool -i ens1f0
> driver: ixgbe
> version: 4.1.5
> firmware-version: 0x80000597, 1.349.0
> expansion-rom-version:
> bus-info: 0000:04:00.0
> supports-statistics: yes
> supports-test: yes
> supports-eeprom-access: yes
> supports-register-dump: yes
> supports-priv-flags: no

I regesterd my licences yesterday and after that, the PF_RING ZC does not work correctly. My program works correctly when capturing packets on none zc mode:
zbalance_ipc -i ens1f0     -c 44 -n 2 -m 2 -a -g 19 --------- works fine for a long time
zbalance_ipc -i zc:ens1f0 -c 44 -n 2 -m 2 -a -g 19 ------ works fine for a while (e.g. 20 min)

after a while running zbalance_ipc in zc mode, zbalance_ipc  stops capturing packets and my application captures nothing as well. 
what is wrong with that? How can I fix it?

OS: Linux ubuntu 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
root@ubuntu:#  grep Hugepagesize /proc/meminfo
Hugepagesize:       2048 kB
```

```
root@ubuntu:# sysctl -a | grep huge
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.ens1f0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
vm.hugepages_treat_as_movable = 0
vm.hugetlb_shm_group = 0
vm.nr_hugepages = 1024
vm.nr_hugepages_mempolicy = 1024
vm.nr_overcommit_hugepages = 0

```
pf_ring.ko is loaded.
```
root@ubuntu:# lsmod 
Module                  Size  Used by
ixgbe                 294912  0
pf_ring              1224704  20

```

> root@ubuntu:# mount | grep huge
> cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
> hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
> hugetlb on /run/lxcfs/controllers/hugetlb type cgroup (rw,relatime,hugetlb)
> nodev on /mnt/huge type hugetlbfs (rw,relatime)

trying to load driver:

> root@ubuntu:~/PF_RING/drivers/intel/ixgbe/ixgbe-4.1.5-zc/src# ./load_driver.sh
> irqbalance: no process found
> Configuring ens4f0
> IFACE CORE MASK -> FILE
> =======================
> ens4f0 0 1 -> /proc/irq/94/smp_affinity
> Configuring ens4f1
> IFACE CORE MASK -> FILE
> =======================
> ens4f1 0 1 -> /proc/irq/97/smp_affinity
> Configuring ens1f0
> IFACE CORE MASK -> FILE
> =======================
> ens1f0 0 1 -> /proc/irq/88/smp_affinity
> Configuring ens1f1
> IFACE CORE MASK -> FILE
> =======================
> ens1f1 0 1 -> /proc/irq/91/smp_affinity
> Warning: 512 hugepages available, 1024 requested

dmesg output on loading driver:
> [Wed Nov 16 09:44:29 2016] [PF_RING] registered /proc/net/pf_ring/
> [Wed Nov 16 09:44:29 2016] NET: Registered protocol family 27
> [Wed Nov 16 09:44:29 2016] [PF_RING] Min # ring slots 4096
> [Wed Nov 16 09:44:29 2016] [PF_RING] Slot version     16
> [Wed Nov 16 09:44:29 2016] [PF_RING] Capture TX       Yes [RX+TX]
> [Wed Nov 16 09:44:29 2016] [PF_RING] IP Defragment    No
> [Wed Nov 16 09:44:29 2016] [PF_RING] Initialized correctly
> [Wed Nov 16 09:44:29 2016] Intel(R) 10 Gigabit PCI Express Network Driver - version 4.1.5
> [Wed Nov 16 09:44:29 2016] Copyright (c) 1999-2015 Intel Corporation.
> [Wed Nov 16 09:44:29 2016] ixgbe: Receive-Side Scaling (RSS) set to 1
> [Wed Nov 16 09:44:29 2016] ixgbe: 0000:04:00.0: ixgbe_check_options: FCoE Offload feature enabled
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0: PCI Express bandwidth of 32GT/s available
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0: (Speed:5.0GT/s, Width: x8, Encoding Loss:20%)
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0 eth0: MAC: 2, PHY: 17, SFP+: 12, PBA No: G43260-007
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0: 00:
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0 eth0: Enabled Features: RxQ: 1 TxQ: 1
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0 eth0: Intel(R) 10 Gigabit Network Connection
> [Wed Nov 16 09:44:29 2016] ixgbe: Receive-Side Scaling (RSS) set to 1
> [Wed Nov 16 09:44:29 2016] ixgbe: 0000:04:00.1: ixgbe_check_options: FCoE Offload feature enabled
> [Wed Nov 16 09:44:29 2016] ixgbe 0000:04:00.0 ens1f0: renamed from eth0
> [Wed Nov 16 09:44:30 2016] ixgbe 0000:04:00.0: registered PHC device on ens1f0
> [Wed Nov 16 09:44:30 2016] IPv6: ADDRCONF(NETDEV_UP): ens1f0: link is not ready
> [Wed Nov 16 09:44:30 2016] ixgbe 0000:04:00.0 ens1f0: detected SFP+: 12
> [Wed Nov 16 09:44:30 2016] ixgbe 0000:04:00.0 ens1f0: NIC Link is Up 1 Gbps, Flow Control: RX/TX
> [Wed Nov 16 09:44:30 2016] IPv6: ADDRCONF(NETDEV_CHANGE): ens1f0: link becomes ready

**Comment by cardigliano** [comment]
@mr-mohsen a few questions:
1. are you using latest code from git?
2. what happens if you replace your application with pfcount?
3. could you provide some output when zbalance_ipc stops receiving traffic? Please run it with -p

**Comment by rezaeimh7** [comment]
1- Yes, I am.
2-  hmm, I have no idea. What is the advantage??
3-
21/Nov/2016 10:14:15 [zbalance_ipc.c:151] =========================
21/Nov/2016 10:14:15 [zbalance_ipc.c:152] Absolute Stats: Recv 3'112'225'740 pkts (2'254 drops) - Forwarded 3'112'225'740 pkts (0 drops)
21/Nov/2016 10:14:15 [zbalance_ipc.c:224] Actual Stats: Recv 0.00 pps (0.00 drops) - Forwarded 0.00 pps (0.00 drops)

4- Thank You

**Comment by cardigliano** [comment]
2. I want to make sure that there is no ring corruption on the application side

**Comment by rezaeimh7** [comment]
Hi again.
replacing My App with pfcount and zcount seems works fine. You have right @cardigliano. may be there is  ring corruption.

i have two applications and each of them must capture the same amounts of packets. i use zbalance_ipc as follow to meet my requirements:

```
// Named Session queues
zbalance_ipc -i zc:ens1f0 -c 44 -n 2 -m 2 -a -g 19  
// Named Connection queues
zbalance_ipc -i zc:ens1f1 -c 99 -n 2 -m 2 -a -g 18
```

on My applications side, i use these part of code for capturing packets from 2 queues of the above clusters:

```
//Globals
pfring_zc_queue *zqc, *zqs;
pfring_zc_buffer_pool *zpc, *zps;
pfring_zc_pkt_buff *buffer_connection, *buffer_session;

//Intitializing
        zqc = pfring_zc_ipc_attach_queue(_connection_cluster_id, _queue_id, rx_only);
        if (zqc == NULL) {
            fprintf(stderr, "pfring_zc_ipc_attach_queue error [%s] Please check that cluster %d is running\n",
                    strerror(errno), _connection_cluster_id);
            stopZC();
        }
        zpc = pfring_zc_ipc_attach_buffer_pool(_connection_cluster_id, _queue_id);
        if (zpc == NULL) {
            fprintf(stderr, "pfring_zc_ipc_attach_buffer_pool error [%s] Please check that cluster %d is running\n",
                    strerror(errno), _connection_cluster_id);
            stopZC();
        }
        buffer_connection = pfring_zc_get_packet_handle_from_pool(zpc);
        if (buffer_connection == NULL) {
            fprintf(stderr, "pfring_zc_get_packet_handle_from_pool error\n");
            stopZC();
        }

        //session_handler
        zqs = pfring_zc_ipc_attach_queue(_session_cluster_id, _queue_id, rx_only);
        if (zqs == NULL) {
            fprintf(stderr, "pfring_zc_ipc_attach_queue error [%s] Please check that cluster %d is running\n",
                    strerror(errno), _session_cluster_id);
            stopZC();
        }
        zps = pfring_zc_ipc_attach_buffer_pool(_session_cluster_id, _queue_id);
        if (zps == NULL) {
            fprintf(stderr, "pfring_zc_ipc_attach_buffer_pool error [%s] Please check that cluster %d is running\n",
                    strerror(errno), _session_cluster_id);
            stopZC();
        }
        buffer_session = pfring_zc_get_packet_handle_from_pool(zps);
        if (buffer_session == NULL) {
            fprintf(stderr, "pfring_zc_get_packet_handle_from_pool error\n");
            stopZC();
        }//ZCWrapper       

```

And finally capture packets with the following functions ( as said earlier)

```
    void runZCConnection() {
        long int i = 0;
        for (;;) {
            if (unlikely(pfring_zc_recv_pkt(zqc, &buffer_connection, _wait_for_packet) < 0)) {
                break;
            }
            u_char *pkt_data = pfring_zc_pkt_buff_data(buffer_connection, zqc);
            std::string payload(pkt_data + _ConnectionHeaderSize, pkt_data + _snapLengthConnection);
            try {
                _Connection_buffer[i] =payload;
            } catch (...) {
                LOG_INFO("Packet= %s", payload.c_str());
                continue;
            }
            _Connection_Number++;
            i = (i + 1) % _Max_Element_Connection_buffer;
        }
    }

```
```
    void runZCSession() {
        long int c = 0;
        for (;;) {
            if (unlikely(pfring_zc_recv_pkt(zqs, &buffer_session, _wait_for_packet) < 0)) {
                break;
            }
            u_char *pkt_data = pfring_zc_pkt_buff_data(buffer_session, zqs);
            std::string payload (pkt_data + _SessionHeaderSize, pkt_data + _snapLengthSession);
            try {
                _Session_buffer[c] = payload;

            } catch (...) {
                LOG_INFO("Packet rejected on runZCSession: %s", payload.c_str());
                continue;
            }
            _Session_Number++;
            c = (c + 1) % _Max_Element_Session_buffer;
        }
    }//packet consumer

```
Everything is OK but for some minutes (e.g. less than 20 m). then zbbalance_ipc stops working and receives no packets.
Can you Tell me what is wrong with My code?

**Comment by rezaeimh7** [comment]
@cardigliano , @lucaderi  Can you help me to solve my problem?

**Comment by cardigliano** [comment]
@mr-mohsen this code looks fine, however I do not have visibility of what else your application is doing, what I can tell you is to pay attention to avoid mixing buffers between the two clusters.

**Comment by rezaeimh7** [comment]
@cardigliano  how should i set  ixgbe RSS for my both Applications? is there any relation between my problem and RSS setting??

**Comment by cardigliano** [comment]
@mr-mohsen when using zbalance_ipc for traffic distribution RSS should be set to single queue (RSS=1,1). However there should be no relation between RSS and socket corruption, but again, I cannot be sure as I do not know what your application is doing exactly.

**Comment by rezaeimh7** [comment]
@cardigliano i'm sorry for late response.
My application capture packets from 2 clusters and save them on 2 separate buffers. then i do some operations on the buffers and save the results elsewhere.
There is no relation between the functions which capture packets and rest of my application functions. each one works separately.

**Comment by rezaeimh7** [comment]
@cardigliano  waiting for your help  :-)

**Comment by cardigliano** [comment]
@mr-mohsen as I said, if there is a ring corruption, it's somehow caused by your code (you said zcount on the same system is working), I cannot say more with the info I have. If you need development support, please send us a direct email with the details and we will arrange it.
