### ISSUE TITLE
parsed_header_len not in pf_ring.h anymore?

### ISSUE THREAD

**Issue by mgkallit** [ntop/PF_RING#158]
Hi all,

We are noticing that 

u_int16_t parsed_header_len; /* Extra parsing data before packet */

is not defined anymore in kernel/linux/pf_ring.h at the latest PF_RING-dev branch.

It is still there though under PF_RING-6.4.1.-stable.

Our monitoring application needs that information to parse the packet. Is that an intentional change and shall we adopt our application accordingly?

Many thanks,

MK

**Comment by cardigliano** [comment]
@mgkallit parsed_header_len was used by kernel plugins, we removed support for that in dev as it was deprecated, what are you doing exactly with parsed_header_len?

**Comment by mgkallit** [comment]
We were using it to parse the packets, as adjusted from a previous PF_RING example, namely userland/examples/pfcount_aggregator.c. E.g.,

    memcpy(&ehdr, p+h->extended_hdr.parsed_header_len, sizeof(struct ether_header));
    eth_type = ntohs(ehdr.ether_type);

**Comment by cardigliano** [comment]
Please take a look at:

https://github.com/ntop/PF_RING/blob/dev/userland/lib/pfring_utils.c#L602

Note that extended_hdr.parsed_header_len was not really needed for parsing packets.

Alfredo

**Comment by mgkallit** [comment]
Thanks, we can adjust accordingly!
