### ISSUE TITLE
No dna0

### ISSUE THREAD

**Issue by daz3dz** [ntop/PF_RING#159]
I have checked that pf_ring is in fact running but I do not have a dn0 adapter. This program I want to use is supposed to switch to pf_ring once it detects dna0, but it's not working. I've checked with lsmod; it shows that pf_ring is running. I've checked my network adapters and there is no dna0. How do I get pf_ring to create dna0?

**Comment by cardigliano** [comment]
@daz3dz dna is deprecated, the new generation intel-based kernel-bypass drivers is ZC (http://www.ntop.org/products/packet-capture/pf_ring/pf_ring-zc-zero-copy/), please read https://github.com/ntop/PF_RING/blob/dev/doc/README.apt_rpm_packages for configuring it.
