### ISSUE TITLE
ixgbe-zc RSS maps packets in the same TCP connection to dierent NIC queues

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#163]
RSS  maps the IP packets in the same TCP connection to dierent NIC queues depending on the direction of the packets.

I have try the following Modify in ixgbe_zc driver source: 

http://webcache.googleusercontent.com/search?q=cache:vB6JhS0AJCUJ:youfu.xyz/2014/12/07/ixgbe-rss/+&cd=3&hl=zh-CN&ct=clnk&gl=jp

http://www.ndsl.kaist.edu/~kyoungsoo/papers/TR-symRSS.pdf

the follow is my change:
http://61.48.51.134/2.png

and I also can't get packets in the same TCP connection from same NIC queues. 
I download this driver https://github.com/majek/ixgbe and do the same Modify, I can get packets in the same TCP connection from same NIC queues.

have you change some code with RSS ?

**Comment by cardigliano** [comment]
RSS is already symmetric with PF_RING (by default when using the ZC API, or with the PF_RING_ZC_SYMMETRIC_RSS flag when using the standard PF_RING API)

Alfredo

**Comment by laoyang103** [comment]
OK thanks a lot, I get the result is use /PF_RING-xxx/userlan/tcpdump, it use PF_RING API and not set PF_RING_ZC_SYMMETRIC_RSS flag.
