### ISSUE TITLE
Kernel Panic on starting cento-bridge

### ISSUE THREAD

**Issue by izzie88** [ntop/PF_RING#165]
when i startup cento-bridge, there was a kernel panic,
on checking the sys logs i found this,

Dec 11 01:40:59 NTOP-DPI kernel: [ 1501.095490] ixgbe 0000:10:00.0 eth0: changing MTU from 1500 to 9000
Dec 11 01:40:59 NTOP-DPI kernel: [ 1501.175704] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
Dec 11 01:41:00 NTOP-DPI kernel: [ 1501.361994] ixgbe 0000:10:00.0 eth0: detected SFP+: 5
Dec 11 01:41:00 NTOP-DPI kernel: [ 1501.501813] ixgbe 0000:10:00.0 eth0: NIC Link is Up 10 Gbps, Flow Control: RX
Dec 11 01:41:03 NTOP-DPI kernel: [ 1504.300391] ixgbe 0000:10:00.1 eth2: changing MTU from 1500 to 9000
Dec 11 01:41:03 NTOP-DPI kernel: [ 1504.379543] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
Dec 11 01:41:03 NTOP-DPI kernel: [ 1504.562487] ixgbe 0000:10:00.1 eth2: detected SFP+: 6
Dec 11 01:41:03 NTOP-DPI kernel: [ 1504.701659] ixgbe 0000:10:00.1 eth2: NIC Link is Up 10 Gbps, Flow Control: RX
Dec 11 01:46:34 NTOP-DPI ZC[4373]: error unlink'ing /mnt/huge/pfring_zc_11: Permission denied
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.100172] BUG: unable to handle kernel paging request at 000000000007b800
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.115819] IP: [<ffffffff810cabce>] native_queued_spin_lock_slowpath+0xfe/0x170
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.131945] PGD 0 
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.147227] Oops: 0002 [#1] SMP 
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.162631] Modules linked in: ixgbe_zc(OE) vxlan ip6_udp_tunnel udp_tunnel pf_ring(OE) configfs uio ipmi_ssif intel_powerclamp coretemp kvm_intel kvm ipmi_devintf gpio_ich irqbypass crct10dif_pclmul crc32_pclmul input_leds aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd serio_raw cdc_ether usbnet mii ioatdma 8250_fintek shpchp ipmi_si ipmi_msghandler i7core_edac mac_hid edac_core lpc_ich i5500_temp lp parport autofs4 igb dca hid_generic ptp usbhid pps_core hid pata_acpi megaraid_sas i2c_algo_bit fjes [last unloaded: ip6_udp_tunnel]
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.246019] CPU: 2 PID: 4374 Comm: cento-bridge Tainted: G           OE   4.4.0-45-generic #66-Ubuntu
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.262621] Hardware name: IBM IBM System x 3620 M3 -[737642G]-/69Y1101, BIOS -[HSE119AUS-1.08]- 09/22/2011
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.280361] task: ffff8802724db200 ti: ffff880227d8c000 task.ti: ffff880227d8c000
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.298476] RIP: 0010:[<ffffffff810cabce>]  [<ffffffff810cabce>] native_queued_spin_lock_slowpath+0xfe/0x170
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.317604] RSP: 0018:ffff880227d8fb68  EFLAGS: 00010206
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.337122] RAX: 00000000000027f5 RBX: ffff88046f5b94c0 RCX: 000000000007b800
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.357364] RDX: ffff880277a97840 RSI: 00000000000c0000 RDI: ffff88046f5b94c4
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.378057] RBP: ffff880227d8fb68 R08: 0000000000000101 R09: ffffffffc04b0198
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.398783] R10: ffffea00090277c0 R11: 0000000000000000 R12: ffff88046f5b94c4
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.419784] R13: ffff880471c8e400 R14: ffff8800356534b8 R15: ffff880035653000
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.441468] FS:  0000000000000000(0000) GS:ffff880277a80000(0000) knlGS:0000000000000000
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.463694] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.485806] CR2: 000000000007b800 CR3: 0000000001e0a000 CR4: 00000000000006e0
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.508768] Stack:
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.531545]  ffff880227d8fb88 ffffffff810cc1a0 ffff88046f5b9000 ffff880035653000
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.555395]  ffff880227d8fb98 ffffffff8183151e ffff880227d8fbb8 ffffffffc04a5079
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.579720]  0000000000000000 ffff880035653000 ffff880227d8fc00 ffffffffc04b01e1
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.603964] Call Trace:
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.628422]  [<ffffffff810cc1a0>] queued_write_lock_slowpath+0x80/0x90
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.653450]  [<ffffffff8183151e>] _raw_write_lock+0x1e/0x20
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.679184]  [<ffffffffc04a5079>] pfring_release_zc_dev+0x39/0x1c0 [pf_ring]
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.705294]  [<ffffffffc04b01e1>] ring_release+0x4c1/0x750 [pf_ring]
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.731842]  [<ffffffff8170856f>] sock_release+0x1f/0x80
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.758133]  [<ffffffff817085e2>] sock_close+0x12/0x20
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.784381]  [<ffffffff8120f594>] __fput+0xe4/0x220
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.811171]  [<ffffffff8120f70e>] ____fput+0xe/0x10
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.837753]  [<ffffffff8109ed41>] task_work_run+0x81/0xa0
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.864646]  [<ffffffff81083e51>] do_exit+0x2e1/0xb00
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.891563]  [<ffffffff810846f3>] do_group_exit+0x43/0xb0
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.918532]  [<ffffffff810908c2>] get_signal+0x292/0x600
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.946325]  [<ffffffff8102e537>] do_signal+0x37/0x6f0
Dec 11 01:46:36 NTOP-DPI kernel: [ 1836.973891]  [<ffffffff810f5aac>] ? ktime_get+0x3c/0xb0
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.001526]  [<ffffffff810f02d6>] ? hrtimer_nanosleep+0x106/0x210
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.029531]  [<ffffffff810ef140>] ? __hrtimer_init+0x90/0x90
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.057724]  [<ffffffff8100320c>] exit_to_usermode_loop+0x8c/0xd0
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.086017]  [<ffffffff81003c6e>] syscall_return_slowpath+0x4e/0x60
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.114970]  [<ffffffff81831a10>] int_ret_from_sys_call+0x25/0x8f
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.143786] Code: 87 47 02 c1 e0 10 85 c0 74 38 48 89 c1 c1 e8 12 48 c1 e9 0c 83 e8 01 83 e1 30 48 98 48 81 c1 40 78 01 00 48 03 0c c5 c0 56 f3 81 <48> 89 11 8b 42 08 85 c0 75 0d f3 90 8b 42 08 85 c0 74 f7 eb 02 
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.205503] RIP  [<ffffffff810cabce>] native_queued_spin_lock_slowpath+0xfe/0x170
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.235610]  RSP <ffff880227d8fb68>
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.265095] CR2: 000000000007b800
Dec 11 01:46:36 NTOP-DPI kernel: [ 1837.295379] ---[ end trace 68b299d8bec2a969 ]---

**Comment by markabey** [comment]
Was this fixed? If so, when?

**Comment by lucaderi** [comment]
When Alfredo closed the issue. Do you still experience this issue?

**Comment by markabey** [comment]
I have an older version running from Sept 2016, but I cant see which commit
is a fix for it around those dates.
