### ISSUE TITLE
How to set HW filter for zbalance_ipc?

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/PF_RING#169]
Hi.
After searching and googling for 1 hour, i don't understand what really a HW filtering would be and how do i set HW filter for zbalance_ipc?
Is it possible to set HW filtering to zbalance_ipc?

If YES, Can you provide an example? 
Is that only available for ZC supported  NICs?

Many Thanks

**Comment by cardigliano** [comment]
@mr-mohsen take a look at the example in zcount:
https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zcount.c#L361
Please note not all cards are supported, hw rules are supported for instance by some ixgbe-based cards such as 82599. For other cards we provide hw filtering support through standard bpf, please take a look at https://github.com/ntop/PF_RING/blob/dev/userland/nbpf/README.fm10k.md for instance.
