### ISSUE TITLE
PF_RING rpm package does not handle upgrade

### ISSUE THREAD

**Issue by lucaderi** [ntop/PF_RING#170]
On CentOS 6 (and probably also 7, everything works on Ubuntu) when PF_RING is upgraded with applications running (e.g. ntopng), the installation seems to complete successfully but it is not like that as
- the pf_ring module is not unloaded
- as of the above, the pf_ring dkms is not compiled
- applications are not stopped/restarted

After the upgrade, it is tricky to restart the apps as the DKMS compilation must be forced, and applications do not restart until that happens.

**Comment by cardigliano** [comment]
This has been fixed.
