### ISSUE TITLE
Can each thread or process get all packets from the same NIC use ZC API

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#171]
I want to both analysis and dump heavy traffic use ZC API, it must use two threads one is analysis another is dump. So two threads must receivd all traffic. How can I finish it?

the best solution for me is two process listen the same NIC

**Comment by cardigliano** [comment]
You can do that using zbalance_ipc (in case of multiple processes) or writing your application based on zbalance code (in case you want a single multithreaded application).
Please take a look at the examples at https://github.com/ntop/PF_RING/tree/dev/userland/examples_zc

Alfredo

**Comment by laoyang103** [comment]
very thank you Alfredo, I will use one zbalance_ipc  and two zcount_ipc to analysis and dump traffic. By the way will zbalance_ipc  use double CPU and memory compared to only capture NIC with zcount ?

**Comment by cardigliano** [comment]
Sure, zbalance_ipc requires one more core for forwarding traffic.

Alfredo
