### ISSUE TITLE
How can I get packet timestamp nanosecond level

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#172]
I have try the follow in zbalance_ipc
1. add flag PF_RING_ZC_DEVICE_HW_TIMESTAMP in pfring_zc_open_device (zbalance_ipc.c: 564)
2. set args as -i zc:p18p1 -c 99 -m 3 -n 3 -S 9 -R 30

I break at fo_multiapp_gtp_distribution_func and see follow

_Breakpoint 1, fo_multiapp_gtp_distribution_func (pkt_handle=0x7fffef400040, in_queue=0x67b4c0, user=0x3)
    at zbalance_ipc.c:370
370	  int32_t i, offset = 0, app_instance, consumers_mask = 0, hash;
(gdb) p pkt_handle->ts 
$6 = {tv_sec = 0, tv_nsec = 0}_

I have read this [http://www.ntop.org/pf_ring/remote-nsec-timestamps-using-pf_ring-and-cpacket-devices/](url)  and can not get http://www.ntop.org/cpacket_ts.tgz with 404 not found

**Comment by cardigliano** [comment]
What is your card model?

Alfredo

**Comment by laoyang103** [comment]
Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

**Comment by cardigliano** [comment]
Please note this card does not support hw timestamping in hw, you should use sw timestamp (please take a look at zbalance_ipc -S)
