### ISSUE TITLE
Balancer worker core overloading

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#173]
```
pfring_zc_worker* pfring_zc_run_balancer(
    pfring_zc_queue *in_queues[],
    pfring_zc_queue * 	out_queues[],
    u_int32_t 	num_in_queues,
    u_int32_t 	num_out_queues,
    pfring_zc_buffer_pool *working_set_pool,
    pfring_zc_recv_policy recv_policy,
    pfring_zc_idle_callback callback,
    pfring_zc_distribution_func func,
    void *user_data,
    u_int32_t active_wait,
    int32_t core_id_affinity 
)
```	

Balancer bound to some core (set core_id_affinity).
On high traffic load balancer use all 100% core to which it was bound.
Traffic starts to be lost.

Any ideas how to fix this problem?

I suggested create several balancers.
But I not shure.
Supposing 
num_in_queues = 6
num_out_queues = 10

Run first balancer
```
pfring_zc_run_balancer1(
    in_queues[1],
    out_queues,
    num_in_queues == 3,
    num_out_queues == 10,
    working_set_pool[1],
    round_robin_bursts_policy,
    NULL,
    NULL,
    (void *) ((long) num_out_queues == 10),
    0,
    1
);
```

Run second balancer
```
pfring_zc_run_balancer1(
    in_queues[2],
    out_queues,
    num_in_queues == 3,
    num_out_queues == 10,
    working_set_pool[2],
    round_robin_bursts_policy,
    NULL,
    NULL,
    (void *) ((long) num_out_queues == 10),
    0,
    2
);
```

It's let avoids traffic lost because of one core overloading.
But different balancers have the same the egress queues handles array (out_queues).
This will cause problems?
What happens when both balancers try enqueue pointer to the packet to the same queue at the same time?!
PF_RING ZC have some synchronization for such a case?

**Comment by cardigliano** [comment]
This is expected, handling many ingress and egress queues requires many cpu cycles.
Using several balancers to parallelise packet capture/distribution is the way to go, however sending to the same queues is not supported as queues are single-producer, thus you should send to different queues and aggregate from those queues on the consumer.

**Comment by andyarus** [comment]
What do you mean by "aggregate from those queues on the consumer"?
pfring_zc_recv_pkt(out_queues[1], pkt_handle, wait_for_incoming_packet);
pfring_zc_recv_pkt(out_queues[2], pkt_handle, wait_for_incoming_packet);
this?
But I use separate consumer thread for specific out_queues[] and I get issue with packet order? If one thread processing packet for the same flow faster then other and sends it sooner than should

**Comment by cardigliano** [comment]
Correct, something like that, 
you have to pay attention to packet order (however the same applies if you use the same queues with some synchronisation) 
an option is using timestamps, it’s annoying but other mechanisms such as locks are more expensive..

Alfredo

**Comment by andyarus** [comment]
Thanks!
May you are suggest other solutions for core overloading issue when use only one balancer?
I get traffic from many interfaces.
For every out_queues[] I run consumer thread that processing packet and then sends it to the destination. All work good with one balancer, but on high load I lose traffic.
If create more balancers I get issue with packet order when send them.
And when I processing packet me important traffic flow, I calculate some statistics for flows and make some other actions. Big issue when packet for the same flow recorded to different out_queues. It's create problem how processing the same flow in different threads. When using one balancer packets for the same flow recorded to the same out_queue thats was fine.

**Comment by cardigliano** [comment]
@andyarus if you're concerned about same flows coming from different interfaces, thus from different zbalance threads, the same could happen at the interface level, with the zbalance thread reading from multiple interfaces. However what you say can be avoided, keeping the order at flow level, using another setup: RSS with 2 queues per interface, and 2 zbalance threads, the first thread reading from all interfaces queue 0, the second thread reading from all interfaces queue 1 (RSS distributes the traffic using a 4-tuple hash)

**Comment by andyarus** [comment]
Thanks! This solve problem!
But my mistake was that I bind second balancer to odd core and this slow down work and was packet loss.
Now we bind both balancers to even cores and all work fine!

More details:
https://github.com/ntop/PF_RING/issues/181
