### ISSUE TITLE
I want to deal with zero copy data with multiThread Program

### ISSUE THREAD

**Issue by solaris888** [ntop/PF_RING#174]
I want to use multiThread program to deal with zero copy data,
but I don't want to copy data  to every Thread ,whether I can use multiThread program to deal with one data

 I create a virtual network card in ubuntu ,Whether I can use multiThread program  get zero copy date from virtual network card?
Do you have  another way ?

**Comment by cardigliano** [comment]
Please take a look at this sample multithreaded application https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance.c
If this is not what you are looking for, please provide more details.
