### ISSUE TITLE
PF_RING ZC: igb on 6.4 causes soft lockup on network restart

### ISSUE THREAD

**Issue by ahchengrui** [ntop/PF_RING#175]
centos 6.6 x64
version pfring6.4 stable 
I install the pfring in the machine
then run ./zcount zc:eth2
I can get the packet captured 
Then I run 
service network restart
the zcount cannot get any packet any more

then I try to kill the pid, it cannot work

and then I get the kernel log:
BUG:SOFT LOCKUP - cpu#0 stuck for 67s! [zcount:2703]

Anyone can have a try, just run the zcount or other prog and then restart the network, the problem will be reproduced!

**Comment by cardigliano** [comment]
@ahchengrui what is the driver/card model?

**Comment by ahchengrui** [comment]
@cardigliano The card is Intel I210(igb)

**Comment by cardigliano** [comment]
This is related to https://github.com/ntop/PF_RING/issues/288
