### ISSUE TITLE
Can ZC API or driver filter repeat packet

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#177]
I received traffic repeat more than once, I want to keep only one traffic.
I know one packet's unique ID is ip.Identification in IP layer, I want to use this to filter repeat packet, is that right?
Is ZC already have this function?

**Comment by cardigliano** [comment]
@laoyang103 ZC does not support this as it requires to keep some state, you should do this at application level.

**Comment by laoyang103** [comment]
OK thank you very much.
