### ISSUE TITLE
pfring_zc_stats how it works for device queue in RX mode

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#179]
recv++ when to the network card(NIC) came a new packet?
But when drop++?
If some NIC memory full and new packet has come but not memory to save him hence packet will be dropped.
Or pf_ring remaded driver for NIC counting devise queue size. If so, then when queue size increases and when decreases?
I have packets loss problem and I try figure out why this happen.
1. Because balancer worker can not get in time process all incoming packets when it reaches 100% load core. Or 100% load core it's result of packets loss on NIC? How balancer worker function work? When this func start increase core load? When incoming traffic increase. But when 80%, 90%, 99%, 100? It depends on the value of pause in balancer func? When more traffic, less pause, more core load? When NIC start loss packets, pause equal 0 and therefore core load equal 100%?
2. Problem in NIC. When to the NIC comes a lot of traffic. Say 8Gbit/s. NIC memory overflow. Packets loss begin, balancer worker function work without pause then core load == 100%.
When on NIC comes less traffic, say 4Gbit/s, NIC memory not full and everything works as it should be.

How to solve packets loss problem? Use more NIC's, to distribute incoming traffic so that there was no overflow one memory card? Use more balancer workers to speed up processing device queue. Or something else?
How it's work?

**Comment by cardigliano** [comment]
@andyarus if your balancer thread reaches 100% cpu load and you have packet loss, the problem is that your cpu is not fast enough for handling all the traffic you have using a single core.
Please provide:
- cpu model
- traffic rate (pps)
- zbalance_ipc command line (or describe the distribution function you are using if you wrote your custom distribution function)

**Comment by andyarus** [comment]
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
4.5 Mpps
default distribution function ( void * 	user_data == (void *) ((long) num_threads_balancer[i])

1 balancer > 4.5 Mpps packet loss (1 core 100%)
2 balancers > 4 Mpps packet loss (1 core 100%, 2 core ~60%)
4 balancers > 3 Mpps packet loss (no one core reach 100% load)

```
pfring_zc_worker* pfring_zc_run_balancer	(	pfring_zc_queue * 	in_queues[],
pfring_zc_queue * 	out_queues[],
u_int32_t 	num_in_queues,
u_int32_t 	num_out_queues,
pfring_zc_buffer_pool * 	working_set_pool,
pfring_zc_recv_policy 	recv_policy,
pfring_zc_idle_callback 	callback,
pfring_zc_distribution_func 	func,
void * 	user_data,
u_int32_t 	active_wait,
int32_t 	core_id_affinity 
)
```	

Please help undestand, how device queue size changes (pfring_zc_queue * in_queues[]).
When it is increased, when decreased?
When this queue full, pfring zc drop packets, pfring_zc_stat increase drop value?
How it's work?

**Comment by cardigliano** [comment]
Could you run "zbalance_ipc -i ethX -n 1 -m 1 -p" and provide some output?
Please provide also:
- ethtool -g eth1
- cat /proc/net/pf_ring/dev/ethX/info

**Comment by andyarus** [comment]
**./zbalance_ipc -i eth13 -n 1 -m 1 -p**
```
24/Jan/2017 10:56:15 [zbalance_ipc.c:683] Starting balancer with 1 consumer queues..
24/Jan/2017 10:56:15 [zbalance_ipc.c:693] Run your application instances as follows:
24/Jan/2017 10:56:15 [zbalance_ipc.c:698]     pfcount -i zc:99@0
24/Jan/2017 10:56:16 [zbalance_ipc.c:151] =========================
24/Jan/2017 10:56:16 [zbalance_ipc.c:152] Absolute Stats: Recv 569'791 pkts (0 drops) - Forwarded 8'190 pkts (561'601 drops)
24/Jan/2017 10:56:16 [zbalance_ipc.c:191]                 eth13 RX 569823 pkts Dropped 0 pkts (0.0 %)
24/Jan/2017 10:56:16 [zbalance_ipc.c:205]                 Q 0 RX 0 pkts Dropped 561633 pkts (0.0 %)
24/Jan/2017 10:56:16 [zbalance_ipc.c:234] =========================
24/Jan/2017 10:56:17 [zbalance_ipc.c:151] =========================
24/Jan/2017 10:56:17 [zbalance_ipc.c:152] Absolute Stats: Recv 1'130'958 pkts (0 drops) - Forwarded 8'190 pkts (1'122'768 drops)
24/Jan/2017 10:56:17 [zbalance_ipc.c:191]                 eth13 RX 1131000 pkts Dropped 0 pkts (0.0 %)
24/Jan/2017 10:56:17 [zbalance_ipc.c:205]                 Q 0 RX 0 pkts Dropped 1122810 pkts (0.0 %)
24/Jan/2017 10:56:17 [zbalance_ipc.c:224] Actual Stats: Recv 561'078.34 pps (0.00 drops) - Forwarded 0.00 pps (561'078.34 drops)
24/Jan/2017 10:56:17 [zbalance_ipc.c:234] =========================
24/Jan/2017 10:56:18 [zbalance_ipc.c:151] =========================
24/Jan/2017 10:56:18 [zbalance_ipc.c:152] Absolute Stats: Recv 1'681'533 pkts (0 drops) - Forwarded 8'190 pkts (1'673'343 drops)
24/Jan/2017 10:56:18 [zbalance_ipc.c:191]                 eth13 RX 1681533 pkts Dropped 0 pkts (0.0 %)
24/Jan/2017 10:56:18 [zbalance_ipc.c:205]                 Q 0 RX 0 pkts Dropped 1673359 pkts (0.0 %)
24/Jan/2017 10:56:18 [zbalance_ipc.c:224] Actual Stats: Recv 550'491.32 pps (0.00 drops) - Forwarded 0.00 pps (550'491.32 drops)
24/Jan/2017 10:56:18 [zbalance_ipc.c:234] =========================
24/Jan/2017 10:56:19 [zbalance_ipc.c:151] =========================
24/Jan/2017 10:56:19 [zbalance_ipc.c:152] Absolute Stats: Recv 2'230'791 pkts (0 drops) - Forwarded 8'190 pkts (2'222'601 drops)
24/Jan/2017 10:56:19 [zbalance_ipc.c:191]                 eth13 RX 2230813 pkts Dropped 0 pkts (0.0 %)
24/Jan/2017 10:56:19 [zbalance_ipc.c:205]                 Q 0 RX 0 pkts Dropped 2222635 pkts (0.0 %)
24/Jan/2017 10:56:19 [zbalance_ipc.c:224] Actual Stats: Recv 549'162.44 pps (0.00 drops) - Forwarded 0.00 pps (549'162.44 drops)
24/Jan/2017 10:56:19 [zbalance_ipc.c:234] =========================
...
24/Jan/2017 10:56:29 [zbalance_ipc.c:151] =========================
24/Jan/2017 10:56:29 [zbalance_ipc.c:152] Absolute Stats: Recv 7'774'502 pkts (0 drops) - Forwarded 8'190 pkts (7'766'310 drops)
24/Jan/2017 10:56:29 [zbalance_ipc.c:191]                 eth13 RX 7774529 pkts Dropped 0 pkts (0.0 %)
24/Jan/2017 10:56:29 [zbalance_ipc.c:205]                 Q 0 RX 0 pkts Dropped 7766377 pkts (0.0 %)
24/Jan/2017 10:56:29 [zbalance_ipc.c:224] Actual Stats: Recv 559'108.46 pps (0.00 drops) - Forwarded 0.00 pps (559'106.46 drops)
24/Jan/2017 10:56:29 [zbalance_ipc.c:234] =========================
```
**ethtool -g eth13**
```
Ring parameters for eth13:
Pre-set maximums:
RX:        32768
RX Mini:    0
RX Jumbo:    0
TX:        32768
Current hardware settings:
RX:        32768
RX Mini:    0
RX Jumbo:    0
TX:        32768
```
**cat /proc/net/pf_ring/dev/eth13/info**
```
Name:              eth13
Index:             23
Address:           00:E0:ED:2E:B0:2F
Polling Mode:      NAPI/ZC
Type:              Ethernet
Family:            Intel ixgbe 82599
Max # TX Queues:   4

Used RX Queues: 4
Num RX Slots:      32768
Num TX Slots:      32768
```

**Comment by cardigliano** [comment]
@andyarus it seems that zbalance_ipc is able to capture all the traffic, there is no drop at card level. If you have packet loss in your application, it is probably due to the processing time.
However, please also note you are not using a ZC driver, you should add the zc: prefix. In this case you should disable RSS, otherwise you capture from the first queue only (zc:eth13 == zc:eth13@0)
