### ISSUE TITLE
Under Centos 7 and Fedora 21:  undefined reference to `pcap_lex'

### ISSUE THREAD

**Issue by ivanfig** [ntop/PF_RING#18]
[idf@node2 examples]$ make
gcc  -march=corei7 -mtune=corei7  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../../kernel/plugins -I../lib -I../libpcap -Ithird-party  -D HAVE_ZERO -D ENABLE_BPF -D HAVE_LIBNUMA -O2  pfcount.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a    -lpthread  -lrt   -lnuma -lrt -o pfcount
../libpcap/libpcap.a(grammar.o): In function `pcap_parse':
/mnt/gluster/Downloads/PF_RING/userland/libpcap/y.tab.c:2183: undefined reference to `pcap_lex'
collect2: error: ld returned 1 exit status
make: *** [pfcount] Error 1
[idf@node2 examples]$

**Comment by lucaderi** [comment]
@ivanfig Did you install bison/lex prior to compile libpcap?

**Comment by ivanfig** [comment]
[idf@node2 PF_RING]$ sudo yum install flex
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.cc.columbia.edu
 * epel: mirror.cogentco.com
 * extras: mirror.es.its.nyu.edu
 * updates: mirror.trouble-free.net
Package flex-2.5.37-3.el7.x86_64 already installed and latest version
Nothing to do
[idf@node2 PF_RING]$ sudo yum install bison
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.cc.columbia.edu
 * epel: mirror.cogentco.com
 * extras: mirror.es.its.nyu.edu
 * updates: mirror.trouble-free.net
Package bison-2.7-4.el7.x86_64 already installed and latest version
Nothing to do
[idf@node2 PF_RING]$

**Comment by ivanfig** [comment]
I got it work. Not sure what I was doing wrong. I removed it and git'ed again and it seems to build fine this time.
