### ISSUE TITLE
How to programmatically forward packets to some queues using tools under userland/example_zc directory

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/PF_RING#182]
Hi everyone

My first requirement is to capture packets from some interfaces, so Afaik this can be done by almost all tools under example_zc directory. 

The second requirement is need to extract some information (an IP) from each packet payload and the third requirement is to forward packets to some desired queues based on what the extracted IP is?

Which tools can help me? Ho do i do this?

**Comment by cardigliano** [comment]
Please take a look at https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance_ipc.c
there are a few distribution functions, some of them are based on IP

**Comment by rezaeimh7** [comment]
@cardigliano thanks for your reply but i should provide some more descriptions about what i mean.

I can capture packets from one or more network interfaces and put them on one or more queues.
Every packet i capture has a format like this

> [---------header----------][-------------------------payload-------------------]
> ---------header----------  userr_ID a b c d e ...... { An IP Address } ........... x y z

The IP address in the above example is one of our local IPs provided for our users which connect to our servers. Each user has its own IP and as the above example implies the IP address is located on packet payload. So we should capture each packet and extract the IP Address of the user.

suppose our internal IP range is 

> 100.0.0.0-100.127.255.255.

Until now, i capture and send the packets to one queue. On the other side there is an application that reads the packet from the queue and handles them.

I need to divide the IP range to 4 separated IP ranges as follows:

> 100.0.0.0-100.31.255.255.
> 100.32.0.0-100.63.255.255.
> 100.64.0.0-100.95.255.255.
> 100.96.0.0-100.127.255.255.

So the number of my applications which handle the packets will be increased to 4 respectively.
I want to create 4 queues for my applications and send the packets to the application which its IP range contains the IP address of the packet.

If i want to be honest, i have no idea how to do this with the tools under example_zc directory?

**Comment by cardigliano** [comment]
In essence you need to extend zbalance_ipc.c with a custom distribution function, if you need development support please send us a direct email.

**Comment by mr-mohsen** [comment]
@cardigliano  thanks again.
I am using some server for zones and also using one server as load balancer that receives all packets from zones servers.
I can change our network topology in the way that we receive packets from multiple server instead of one. As you know each server has it's own IP and the IP address is appeared in the header of every packet transmitted by the server.

So, if i could separate the packets by its source IP, how current tools can help me to distribute packets across multiple applications?

**Comment by rezaeimh7** [comment]
@cardigliano thanks again for your reply.
Now, I am trying to extend zbalacnce_ipc to distribute packets across multiple applications by the source IP of the packet.

All of the packets have identical format. you can see a couple of the Packets as follows

> 
> root@saeid-P85-D3:/home/saeid# tcpdump -i enp5s1 -A -nnvvXS
> 
> 18:56:04.501543 IP (tos 0x0, ttl 128, id 11828, offset 0, flags [none], proto 
> UDP (17), length 218)
>     192.168.2.201.50788 > 192.168.2.19.10330: [udp sum ok] UDP, length 190
> 0x0000:  4500 00da 2e34 0000 8011 85b2 c0a8 02c9  E....4..........
> 0x0010:  c0a8 0213 c664 285a 00c6 e61e 3c31 343e  .....d(Z....<14>
> 0x0020:  4665 6220 3230 2031 383a 3536 3a30 3220  Feb.20.18:56:02.
> 0x0030:  5254 5f46 4c4f 573a 2052 545f 464c 4f57  RT_FLOW:.RT_FLOW
> 0x0040:  5f53 4553 5349 4f4e 5f43 5245 4154 453a  _SESSION_CREATE:
> 0x0050:  2073 6573 7369 6f6e 2063 7265 6174 6564  .session.created
> 0x0060:  2031 302e 312e 342e 3230 382f 3131 3833  .10.1.4.208/1183
> 0x0070:  342d 3e31 302e 312e 342e 3232 392f 3131  4->10.1.4.229/11
> 0x0080:  3833 3620 6a75 6e6f 732d 6874 7470 7320  836.junos-https.
> 0x0090:  3130 2e31 2e31 312e 3134 372f 3131 3833  10.1.11.147/1183
> 0x00a0:  372d 3e31 302e 312e 342e 3232 392f 3131  7->10.1.4.229/11
> 0x00b0:  3833 3620 736f 7572 6365 2072 756c 6520  836.source.rule.
> 0x00c0:  3920 4e2f 4120 4e2f 4120 3120 5443 505f  9.N/A.N/A.1.TCP_
> 0x00d0:  4150 505f 4143 4345 5353                 APP_ACCESS
> 
> 18:56:04.501546 IP (tos 0x0, ttl 128, id 11829, offset 0, flags [none], proto 
> UDP (17), length 219)
>     192.168.2.201.50788 > 192.168.2.19.10330: [udp sum ok] UDP, length 191
> 0x0000:  4500 00db 2e35 0000 8011 85b0 c0a8 02c9  E....5..........
> 0x0010:  c0a8 0213 c664 285a 00c7 3989 3c31 343e  .....d(Z..9.<14>
> 0x0020:  4665 6220 3230 2031 383a 3536 3a30 3220  Feb.20.18:56:02.
> 0x0030:  5254 5f46 4c4f 573a 2052 545f 464c 4f57  RT_FLOW:.RT_FLOW
> 0x0040:  5f53 4553 5349 4f4e 5f43 5245 4154 453a  _SESSION_CREATE:
> 0x0050:  2073 6573 7369 6f6e 2063 7265 6174 6564  .session.created
> 0x0060:  2031 302e 312e 3139 2e31 3733 2f31 3736  .10.1.19.173/176
> 0x0070:  3830 2d3e 3130 2e31 2e37 2e32 3333 2f31  80->10.1.7.233/1
> 0x0080:  3736 3832 206a 756e 6f73 2d68 7474 7073  7682.junos-https
> 0x0090:  2031 302e 312e 3130 2e32 3232 2f31 3736  .10.1.10.222/176
> 0x00a0:  3833 2d3e 3130 2e31 2e37 2e32 3333 2f31  83->10.1.7.233/1
> 0x00b0:  3736 3832 2073 6f75 7263 6520 7275 6c65  7682.source.rule
> 0x00c0:  2039 204e 2f41 204e 2f41 2031 2054 4350  .9.N/A.N/A.1.TCP
> 0x00d0:  5f41 5050 5f41 4343 4553 53              _APP_ACCESS
> 
> 18:56:04.501549 IP (tos 0x0, ttl 128, id 11830, offset 0, flags [none], proto 
> UDP (17), length 217)
>     192.168.2.201.50788 > 192.168.2.19.10330: [udp sum ok] UDP, length 189
> 0x0000:  4500 00d9 2e36 0000 8011 85b1 c0a8 02c9  E....6..........
> 0x0010:  c0a8 0213 c664 285a 00c5 b056 3c31 343e  .....d(Z...V<14>
> 0x0020:  4665 6220 3230 2031 383a 3536 3a30 3220  Feb.20.18:56:02.
> 0x0030:  5254 5f46 4c4f 573a 2052 545f 464c 4f57  RT_FLOW:.RT_FLOW
> 0x0040:  5f53 4553 5349 4f4e 5f43 5245 4154 453a  _SESSION_CREATE:
> 0x0050:  2073 6573 7369 6f6e 2063 7265 6174 6564  .session.created
> 0x0060:  2031 302e 312e 3136 2e31 3734 2f31 3737  .10.1.16.174/177
> 0x0070:  3936 2d3e 3130 2e31 2e38 2e36 322f 3137  96->10.1.8.62/17
> 0x0080:  3739 3820 6a75 6e6f 732d 6874 7470 7320  798.junos-https.
> 0x0090:  3130 2e31 2e31 302e 3134 312f 3137 3739  10.1.10.141/1779
> 0x00a0:  392d 3e31 302e 312e 382e 3632 2f31 3737  9->10.1.8.62/177
> 0x00b0:  3938 2073 6f75 7263 6520 7275 6c65 2039  98.source.rule.9
> 0x00c0:  204e 2f41 204e 2f41 2031 2054 4350 5f41  .N/A.N/A.1.TCP_A
> 0x00d0:  5050 5f41 4343 4553 53                   PP_ACCESS

How do i get source IP from UDP packets using pf_ring zc APIs?

**Comment by cardigliano** [comment]
Please take a look at pfring_print_pkt() in https://github.com/ntop/PF_RING/blob/dev/userland/lib/pfring_utils.c#L703
which is using pfring_parse_pkt() for parsing the packet.
