### ISSUE TITLE
pf_ring error

### ISSUE THREAD

**Issue by izzie88** [ntop/PF_RING#184]
Hi,

Please when I start cento-bridge, i get this error and cento-bridge refuses to start, what doest it mean, how can i solve it?

28/Feb/2017 13:44:55 [cento.cpp:981] Built on Ubuntu 16.04.1 LTS
28/Feb/2017 13:44:55 [cento.cpp:982] Available CPU Cores: 16
28/Feb/2017 13:44:55 [cento.cpp:983] Max flow duration set to 120 sec (-t)
28/Feb/2017 13:44:55 [cento.cpp:984] Max flow idleness set to 30 sec (-d)
28/Feb/2017 13:44:55 [cento.cpp:985] Flow hash size set to 512000 buckets (-w)
28/Feb/2017 13:44:55 [cento.cpp:986] Hashes will have up to 1024000 buckets (-W)
28/Feb/2017 13:44:55 [cento.cpp:989] WARNING: No flow export defined (missing -5/-9 parameters)
28/Feb/2017 13:44:55 [cento.cpp:990] WARNING: Flows are just harvested after they are expired
28/Feb/2017 13:44:58 [cento.cpp:1171] Initialized global ZC cluster 10
28/Feb/2017 13:45:00 [ZCInterface.cpp:51] ERROR: pfring_zc_open_device(zc:eth0, TX) error [Device or resource busy]

**Comment by cardigliano** [comment]
Hi
is there any other application using zc:eth0?
Could you also provide the command line you are using for running cento?

Alfredo

**Comment by izzie88** [comment]
#!/bin/bash
echo 4096 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages \
&& mount -t hugetlbfs nodev /mnt/huge \
&& service cento stop \
&& cento-bridge -i zc:eth0,zc:eth2 --zmq tcp://127.0.0.1:5556 --bridge-conf bridge-policy --dpi-level 2 \

**Comment by cardigliano** [comment]
@izzie88 any message in dmesg regarding that?
