### ISSUE TITLE
pcap_send does not get called from inside a zero copy application

### ISSUE THREAD

**Issue by akiskourtis** [ntop/PF_RING#185]
So I am calling the pcap_send from inside the zbounce, to send the packets to another interface outside the ring. 
#1 very bizarre behaviour I noticed is in the latest PF_RING version, the pcap_send is somehow ignored. The same exact code ran from inside a older-version PF_RING directory works.

#2 another very strange thing, the kernel module loaded is the one from the newest version.

I couldn't find any commit related to that?

Is this behaviour expected?

Thank you

Best Regards

**Comment by cardigliano** [comment]
What do you mean with ignored in 1? Are you sending on an interface which is in use by ZC perhaps?
Please provide more details about what you are doing and the behaviour you see

**Comment by akiskourtis** [comment]
Ok so basically we are at the zbounce.c

`if (init_direction(&dir[0], device1, device2) < 0) 
	return -1;

	if (bidirectional)
	if (init_direction(&dir[1], device2, device1) < 0) 
``
We insert the eth0 and eth1 to the ring

at the void *packet_consumer_thread

before we send the packet using the pfring_zc_send_pkt(i->outzq, &i->tmpbuff, flush_packet)

I do a packet send with pcap at the fp = eth2

pcap_sendpacket(fp, packet, tot_len) != 0)

So right there the pcap_send is called but somehow no packet is sent to the interface.
And this is happening to the latest pfring version directory.

**Comment by cardigliano** [comment]
Please update to latest dev code and let me know, there is a fix for this.
