### ISSUE TITLE
raspberry pi 3 compile

### ISSUE THREAD

**Issue by akefallonitis** [ntop/PF_RING#186]
I cannot compile pf_ring on rpi 3 output:

pi@raspberrypi:~/PF_RING/kernel $ sudo make
make -C /lib/modules/4.4.34-v7+/build SUBDIRS=/home/pi/PF_RING/kernel EXTRA_CFLAGS='-I/home/pi/PF_RING/kernel -DGIT_REV="\"dev:f79389b6b5f541b17896cb7521cc3c08bf45ba98\""' modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.34-v7+'
  CC [M]  /home/pi/PF_RING/kernel/pf_ring.o
/home/pi/PF_RING/kernel/pf_ring.c: In function ‘copy_data_to_ring’:
/home/pi/PF_RING/kernel/pf_ring.c:2782:67: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘u_int32_t’ [-Wformat=]
    skb->len, hdr->caplen - (sizeof(struct ethhdr) + sizeof(struct eth_vlan_hdr)));
                                                                   ^
  Building modules, stage 2.
  MODPOST 1 modules
WARNING: "sk_detach_filter" [/home/pi/PF_RING/kernel/pf_ring.ko] undefined!
WARNING: "sk_attach_filter" [/home/pi/PF_RING/kernel/pf_ring.ko] undefined!
  CC      /home/pi/PF_RING/kernel/pf_ring.mod.o
  LD [M]  /home/pi/PF_RING/kernel/pf_ring.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.4.34-v7+'

pi@raspberrypi:~/PF_RING/kernel $ sudo insmod ./pf_ring.ko
insmod: ERROR: could not insert module ./pf_ring.ko: Unknown symbol in module

dmesg pf_ring: Unknown symbol sk_detach_filter (err 0)

Thanks in advanced for any help

**Comment by cardigliano** [comment]
Latest raspberry kernel is untested atm, we will port it asap. Thank you for reporting.

**Comment by akefallonitis** [comment]
Thank you very much for you answer i was going to try older rasbian version...Any timeline?

**Comment by akefallonitis** [comment]
Any progress ? thanks again

**Comment by cardigliano** [comment]
There is a patch for this on the dev branch. Please update and let us know.
