### ISSUE TITLE
Stack injection

### ISSUE THREAD

**Issue by coelho** [ntop/PF_RING#19]
I've been trying PF_RING ZC the last few days and have the issue where stack injection does not seem to work.

```
git: 1f0bbaee4602a867cd27e8c7b4d32bcd57247346
driver: ixgbe-3.22.3-zc
distro: debian 8 jessie
uname -a: Linux dev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```
I've also tried this on Ubuntu 12.04 and Ubuntu 14.04.

I installed using roughly:
```
git clone https://github.com/ntop/PF_RING.git
cd PF_RING/
make
cd drivers/ZC/intel/ixgbe/ixgbe-3.22.3-zc/src
make
./load_driver.sh
```

I first tried the zbounce example to emulate a normal Linux stack which did not seem to work:
```
zbounce -i zc:eth0 -o stack:eth0 -c 1 -b
```

And then I wanted to see if the stack:eth0 interface was actually working so I tried:
```
zsend -i stack:eth0 -p 50000 -c 1
```
I had bmon open at the time to look at the bandwidth usage on the interface and I did not see any traffic increase at all. I thought it was PF_RING ZC so I tried to no avail:
```
pfsend -i stack:eth0 -p 50000
```

The zc:devX seems to work and the just devX seems to work as well. It's just stack:devX that isn't working.

I'm not sure if I'm doing something wrong, misunderstanding, or this is an actual bug.

EDIT: I also tried 6.0.3 stable and that did not work either.

**Comment by cardigliano** [comment]
Please try with tcpdump or pfcount, probably bmon is reading stats from the interface, while the "stack:" module is injecting packets directly to the stack.

**Comment by coelho** [comment]
This issue looks resolved to me now that I've tested again.

Thanks!
