### ISSUE TITLE
pf_ring packet drops

### ISSUE THREAD

**Issue by mgregr** [ntop/PF_RING#190]
Hello,
  I would like to understand, why pf_ring reports packet drops and how to find what caused the drops and how to mitigate the issue. The current situation:

CentOS7, Intel(R) Xeon(R) CPU X3450  @ 2.67GHz, 8GB RAM
Ethernet: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+
i40e driver

```
PF_RING Version          : 6.4.1 (6.4.1-stable:bcd1c4349fe95066d36a4957c31abeead8c3937e)
Total rings              : 1
Standard (non ZC) Options
Ring slots               : 65534
Slot version             : 16
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
```

I am running nprobe with the following config:
`nprobe -n x.x.x.x:9998 -i enp1s0f0 -V 9 -b 1 -w 522288 `

However, pf_ring stats reports some drops:
```
Duration: 0:00:21:03:683
Bytes:    682078656560
Packets:  647668124
Dropped:  161556589
```
The traffic is around 5Gbps, so I don't think that should be an issue for nprobe or pf_ring.  The stats from nprobe says, that everything is ok.
`Flow drop stats:   [0 bytes/0 pkts][0 flows]`

The drops are not continual - e.g., right now, 20 minutes later, I have the same number of drops and the traffic remains the same as well ~ 4-5 Gbits.
```
Duration: 0:00:37:02:812
Bytes:    1250955672128
Packets:  1182275927
Dropped:  161556589
```
Is there something I am missing or an idea how to debug the problem?
Thanks

**Comment by cardigliano** [comment]
Hi @igregr, packet loss using nProbe on standard drivers at 5 Gbit could be normal, this depends on several factors including: 1. traffic rate, 2. plugins enabled, 3. hardware, etc. Please run a simple application such as pfcount on the same interface, and check what is the traffic rate and if there is any drop.

**Comment by mgregr** [comment]
Hi @cardigliano , pfcount seems to be ok so far. What do you recommend then to achieve a wired speed without drops? I tried zc driver, but with zc, I am receiving large number of drops even with simple zcount (I tried zcount with and without `-a` but no difference).

**Comment by cardigliano** [comment]
You are dropping traffic with ZC  even using pfcount probably because you loaded multiple RSS queues but you are capturing from the first one only (with ZC drivers zc:eth1 means zc:eth1@0). Please try setting RSS=1,1

Alfredo

**Comment by mgregr** [comment]
Thank you for the info @cardigliano, but unfortunately this is not the case.
```
# cat /etc/pf_ring/zc/i40e/i40e.conf 
RSS=1,1
```
But I see the drops with this config an zc as well. :(

```
# zcount -i zc:enp1s0f0 -a
=========================
Absolute Stats: 5'469'956 pkts (1'461 drops) - 6'057'093'607 bytes
Actual Stats: 532'571.33 pps (450.92 drops) - 4.69 Gbps
=========================
```

**Comment by cardigliano** [comment]
Please provide the output of:
cat /proc/net/pf_ring/dev/enp1s0f0/info

Alfredo

**Comment by mgregr** [comment]
```
Name:              enp1s0f0
Index:             38
Address:           68:05:CA:34:89:C0
Polling Mode:      NAPI/ZC
Type:              Ethernet
Family:            Intel i40e
Max # TX Queues:   1
# Used RX Queues:  1
Num RX Slots:      4096
Num TX Slots:      4096
```

**Comment by cardigliano** [comment]
@igregr could you test the dev package (v.6.5) to check if there is some difference? We reworked the i40e support and want to check if it depends on the library.

**Comment by mgregr** [comment]
I tried to update the pfring. Right now I have:

```
# cat /proc/net/pf_ring/info 
PF_RING Version          : 6.5.0 (dev:549a80dd3dbbaf3422ff5ce36920fa9c2f2149e9)
Total rings              : 0
Standard (non ZC) Options
Ring slots               : 65534
Slot version             : 16
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
```
```
# cat /proc/net/pf_ring/dev/enp1s0f0/info 
Name:         enp1s0f0
Index:        6
Address:      68:05:CA:34:89:C0
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    1
RX Queues:    1
Num RX Slots: 4096
Num TX Slots: 4096
```
I see much higher number of drops than on the stable version (the numbers are same with or without `-a` flag).

```
# pfcount -i zc:enp1s0f0
=========================
Absolute Stats: [7'228'066 pkts total][6'802 pkts dropped][0.1% dropped]
[7'221'264 pkts rcvd][7'793'350'054 bytes rcvd][750'402.77 pkt/sec][6'478.81 Mbit/sec]
=========================
```

The pfring without the zc mode seems to be quite stable and I do not see drops with simple pfcount. 

```
# pfcount -i enp1s0f0
=========================
Absolute Stats: [60'309'124 pkts total][0 pkts dropped][0.0% dropped]
[60'309'124 pkts rcvd][65'797'512'001 bytes rcvd][687'383.42 pkt/sec][5'999.50 Mbit/sec]
========================= 
```
This was with the following version of i40e driver and firmware:
```
# ethtool -i enp1s0f0
driver: i40e
version: 1.5.18
firmware-version: 4.53 0x80001dca 0.0.0
```
I tried to update the i40e driver and firmware to the latest version:
```
driver: i40e
version: 1.6.42
firmware-version: 5.05 0x800028a6 1.1568.0
```
The pfring with the standard i40e seems to be quite stable and I do not see drops with simple pfcount. However, if I try zc (which loads older driver version: 1.5.18), I still see drops. Thus, the i40e-zc driver seems to be broken.

**Comment by cardigliano** [comment]
@igregr this looks really weird, any chance to let us ssh into this system?

**Comment by surj08** [comment]
Heyo I see this is only a month old and I seem to be having the same issue only with ntopng instead. I thought maybe it was ntop at first but, finally troubleshot it down to pf_ring. Pfcount doesn't seem have this problem (0% drop). This is a completely clean reinstall except ntop. I reinstalled because had some package issues I cleaned up but, thought they might be the cause still. I did not have this issue with ntop prior to updates run last friday which was before the reinstall. Last updates to this box before that were probably ~3 months ago (before the reinstall)

Please let me know if I can help with any other information

Thank you!

```
[root@ntop ~]# cat /proc/net/pf_ring/info
PF_RING Version          : 6.5.0 (dev:da66eb563994aeaf7f8c305efe0f0fee635402d9)
Total rings              : 1

Standard (non ZC) Options
Ring slots               : 65536
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
```
```
[root@ntop ntopng]# cat /proc/net/pf_ring/14852-eno33557248.146
Bound Device(s)    : eno33557248
Active             : 1
Breed              : Standard
Appl. Name         : ntopng
Slot Version       : 16 [6.5.0]
Min Num Slots      : 4098
Bucket Len         : 1514
Slot Len           : 1720 [bucket+header]
Tot Memory         : 7057408
Tot Packets        : 26961807
Tot Pkt Lost       : 15451523      Just found this little guy.....
Tot Insert         : 11510284
Tot Read           : 11500651
Insert Offset      : 5373344
Remove Offset      : 5678272
Num Free Slots     : 0
```

```
eno33557248: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether 00:50:56:9c:f0:4c  txqueuelen 1000  (Ethernet)
        RX packets 5590448  bytes 3101883121 (2.8 GiB)
        RX errors 0  dropped 130234  overruns 0  frame 0
        TX packets 12  bytes 2016 (1.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
 Absolute Stats: [328'891 pkts total][0 pkts dropped][0.0% dropped]
 [328'891 pkts rcvd][213'294'980 bytes rcvd][9'212.91 pkt/sec][47.80 Mbit/sec]
 =========================
 Actual Stats: [8'974 pkts rcvd][693.96 ms][12'931.58 pps][0.07 Gbps]

```

```
VMware VM Version 11
CentOS 7: 3.10.0-514.16.1.el7.x86_64
8 GB Ram
4 vCPU
top - 14:55:13 up  2:28,  1 user,  load average: 1.35, 1.44, 1.60
Tasks: 110 total,   1 running, 109 sleeping,   0 stopped,   0 zombie
%Cpu(s): 50.5 us,  1.4 sy,  0.0 ni, 46.3 id,  0.0 wa,  0.0 hi,  1.8 si,  0.0 st
KiB Mem :  8010812 total,  5178344 free,  1115340 used,  1717128 buff/cache
KiB Swap:  5242876 total,  5242876 free,        0 used.  6563612 avail Mem
```

```
Reinstall:
Yum update
Yum install open-vm-tools nano  epel-release wget
cd /etc/yum.repos.d/
 wget http://packages.ntop.org/centos/ntop.repo -O ntop.repo
yum install redis hiredis
Yum install ntopng
```

```
Ntopng TCP Packet Analysis:
Retransmissions 27k
Out of Order 263k
Lost 41k
```

**Comment by cardigliano** [comment]
@surj08 what I see from your logs is that pfcount is not loosing traffic, while pf_ring is reporting packet loss when running ntopng. This means that ntopng is the bottleneck and it is not related with this specific issue.
Please open an issue in ntopng, and report the traffic rate, cpu model, any any useful detail about the configuration. Thank you.

**Comment by surj08** [comment]
Thank you I will do that! I wasn't positive what the issue was and was
about to open one there untill I saw this. Thanks again for your time and
sorry to muck up your thread
