### ISSUE TITLE
Error compiling on Kernel 4.10.2 -> pf_ring.c: In function 'set_skb_time':

### ISSUE THREAD

**Issue by paolss** [ntop/PF_RING#192]
cd kernel; make
make[1]: Entering directory '/usr/src/PF_RING/kernel'
make -C /lib/modules/4.10.2/build SUBDIRS=/usr/src/PF_RING/kernel EXTRA_CFLAGS='-I/usr/src/PF_RING/kernel -DGIT_REV="\"dev:eb39458666af3348228150ca6d980d56bea036f7\""' modules
make[2]: Entering directory '/usr/src/linux-4.10.2'
  CC [M]  /usr/src/PF_RING/kernel/pf_ring.o
/usr/src/PF_RING/kernel/pf_ring.c: In function 'set_skb_time':
/usr/src/PF_RING/kernel/pf_ring.c:2659:17: error: request for member 'tv64' in something not a structure or union
   if(skb->tstamp.tv64 == 0)
                 ^
/usr/src/PF_RING/kernel/pf_ring.c: In function 'buffer_ring_handler':
/usr/src/PF_RING/kernel/pf_ring.c:4090:13: error: request for member 'tv64' in something not a structure or union
   skb.tstamp.tv64 = 0;
             ^
make[3]: *** [scripts/Makefile.build:301: /usr/src/PF_RING/kernel/pf_ring.o] Error 1
make[2]: *** [Makefile:1490: _module_/usr/src/PF_RING/kernel] Error 2
make[2]: Leaving directory '/usr/src/linux-4.10.2'
make[1]: *** [Makefile:48: all] Error 2
make[1]: Leaving directory '/usr/src/PF_RING/kernel'
make: *** [Makefile:2: all] Error 2

BR
Pawel

**Comment by cardigliano** [comment]
Hi @paolss, what OS/version is this? Thank you.

**Comment by paolss** [comment]
Gentoo Linux

**Comment by cardigliano** [comment]
Fixed on latest dev code.
