### ISSUE TITLE
Help with zbalance_ipc and a distribution function based on BPF...

### ISSUE THREAD

**Issue by gianogli** [ntop/PF_RING#196]
As suggested in https://github.com/ntop/ntopng/issues/1105 we would like to implement a new "custom" distribution function, into the zbalance_ipc code, to properly balance the traffic in our environment.
This new distribution function should be based on some BPF filter rules. An example of these rules could be:
```
output_queue_1: net 192.168.1.0/24 or net 192.168.2.0/24
output_queue_2: host 192.168.3.1 or host 192.168.3.2
output_queue_3: net 192.168.3.0/24 and not (host 192.168.3.1 or host 192.168.3.2)
output_queue_4: net 192.168.4.0/24
```
All the rules will be based only on src/dst IP and on src/dst network.

To do that I've to create a new function like `ip_distribution_func`, called in instance `my_custom_bpf_distribution_func`, I've to extract the source and the destination IP from the current packet, and I've to evaluate the BPF filter with the least performance impact.

Could you help me with these last 2 points?
I just need a little example on how quickly evaluate a BPF rule (for instance `net 192.168.3.0/24 and not (host 192.168.3.1 or host 192.168.3.2)`) starting from `pkt_handle` and  `in_queue` pointers.

Thanks...

**Comment by cardigliano** [comment]
In order to evaluate bpf in userspace please take a look at the bpf support in libpfring:

https://github.com/ntop/PF_RING/blob/dev/userland/lib/pfring_utils.c#L837
https://github.com/ntop/PF_RING/blob/dev/userland/lib/pfring.c#L520

**Comment by gianogli** [comment]
Hi, I need a little help to complete my custom function.
I wrote some lines of code just to understand which pf_ring functions and data structure I need to implement it. I know that this code is horrible to see but it is just a little test to implement a (more or less) working code. I will improve it in a second time. 
The code is:
```
int32_t ip_custom_distribution_func(pfring_zc_pkt_buff *pkt_handle, pfring_zc_queue *in_queue, void *user) {
  //long num_out_queues = (long) user;
  struct pfring_bpf_program *filter1;
  struct pfring_bpf_program *filter2;
  struct pfring_bpf_program *filter3;
  struct pfring_bpf_program *filter4;
  
  filter1 = calloc(1, sizeof(struct pfring_bpf_program *));
  filter2 = calloc(1, sizeof(struct pfring_bpf_program *));
  filter3 = calloc(1, sizeof(struct pfring_bpf_program *));
  filter4 = calloc(1, sizeof(struct pfring_bpf_program *));
  
  char sfilter1[] = "net 192.168.1.0/24";
  char sfilter2[] = "net 192.168.2.0/24";
  char sfilter3[] = "net 192.168.3.0/24";
  char sfilter4[] = "net 192.168.4.0/24";
  
  pfring_parse_bpf_filter(sfilter1, 65535, filter1);
  pfring_parse_bpf_filter(sfilter2, 65535, filter2);
  pfring_parse_bpf_filter(sfilter3, 65535, filter3);
  pfring_parse_bpf_filter(sfilter4, MAX_CAPLEN, filter4);

  if (bpf_filter(filter1.bpf_insn, pfring_zc_pkt_buff_data(pkt_handle, in_queue), X, Y)) return 1;
  if (bpf_filter(filter2.bpf_insn, pfring_zc_pkt_buff_data(pkt_handle, in_queue), X, Y)) return 2;
  if (bpf_filter(filter3.bpf_insn, pfring_zc_pkt_buff_data(pkt_handle, in_queue), X, Y)) return 3;
  if (bpf_filter(filter4.bpf_insn, pfring_zc_pkt_buff_data(pkt_handle, in_queue), X, Y)) return 4;

  return 5;
}
```
In this case we have 1 input and 5 output queues. 

My questions are:
1) Are the used pf_ring functions and data structures the correct one?
2) Into the `bpf_filter()` function, how can I calculate the correct `X` and `Y` values for the current packet? Have I to use `pfring_parse_pkt()`?

Thanks

**Comment by cardigliano** [comment]
You can use pkt_handle->len for both X and Y. Code looks fine (besides the fact that you should create the filters once externally)

**Comment by gianogli** [comment]
I've just finished to implement it!
Here you can find the patch file: [zbalance_ipc_bpf_patch.txt](https://github.com/ntop/PF_RING/files/961551/zbalance_ipc_bpf_patch.txt)

It's working fine and I think that it could be a useful feature for the zbalance_ipc software.

Now we have a new "BPF" mode "-m 5" and a new parameter "-F" to insert the BPF filters.

Ex.
```
# zbalance_ipc -i zc:0@0 -c1 -n3 -m5 -F"net 192.168.1.0/24","net 192.168.2.0/24"
27/Apr/2017 13:39:03 [zbalance_ipc.c:975] Starting balancer with 3 consumer queues..
27/Apr/2017 13:39:03 [zbalance_ipc.c:980]       BPF(Q 0) => net 192.168.1.0/24
27/Apr/2017 13:39:03 [zbalance_ipc.c:980]       BPF(Q 1) => net 192.168.2.0/24
27/Apr/2017 13:39:03 [zbalance_ipc.c:982]       BPF(Q 2) => All the packets that aren't been matched by the previous BPF filters
27/Apr/2017 13:39:03 [zbalance_ipc.c:994] Run your application instances as follows:
27/Apr/2017 13:39:03 [zbalance_ipc.c:999]       pfcount -i zc:1@0
27/Apr/2017 13:39:03 [zbalance_ipc.c:999]       pfcount -i zc:1@1
27/Apr/2017 13:39:03 [zbalance_ipc.c:999]       pfcount -i zc:1@2
27/Apr/2017 13:39:04 [zbalance_ipc.c:247] =========================
```
Do you think to add it into the "dev" branch in the future?

Thanks for your suggestions and your help. :-)

**Comment by cardigliano** [comment]
Great, thank you for the patch. Yes, it affects performance, but it's useful for sure. We will discuss whether to merge it or add support for bpf in the queue itself, which would simplify the app code.
