### ISSUE TITLE
PFRING clustering mechanism is not working as expected

### ISSUE THREAD

**Issue by gautamch13** [ntop/PF_RING#197]
PFRING clustering mechanism is not working as expected for GTP traffic when there are inner and outer IP layer present in the same packet. Eth->IP1->UDP->GTP->IP2->TCP->..

Work around of this is added into dev package and verified working fine.
Can you please help to know when this change will be released?

**Comment by cardigliano** [comment]
@gautamch13 a new stable will be released this week

**Comment by gautamch13** [comment]
Thank you for an update !
