### ISSUE TITLE
the ethernet driver issue

### ISSUE THREAD

**Issue by Tingting-He** [ntop/PF_RING#198]
my computer ethernet device is Intel Corporation 82545EM Gigabit Ethernet Controller,use the command ethtool -i ens33 | grep driver,it appear e1000.But the ZC driver not includes the e1000 driver.I insmod the e1000e driver,it appears the problem: insmod: ERROR: could not insert module e1000e.ko: Unknown symbol in module.
Intel Corporation 82545EM Gigabit Ethernet Controller is not support the ZC?

**Comment by cardigliano** [comment]
e1000 is not supported, sorry
