### ISSUE TITLE
Troubles running p0f v3 with PF_RING

### ISSUE THREAD

**Issue by bak1an** [ntop/PF_RING#20]
Hi.

I'm trying to get p0f v3 (http://lcamtuf.coredump.cx/p0f3/) running with PF_RING.

I'm using stock centos 7 x86_64 kernel (3.10.0-229.7.2.el7.x86_64) with PF_RING installed from packages found at http://www.nmon.net/packages/rpm7/x86_64/PF_RING/.

Upon starting I can see PF_RING module getting loaded:
```
[    8.644538] [PF_RING] Welcome to PF_RING 6.1.1 ($Revision: :$)
(C) 2004-14 ntop.org
[    8.644571] [PF_RING] registered /proc/net/pf_ring/
[    8.644576] NET: Registered protocol family 27
[    8.644587] [PF_RING] Min # ring slots 4096
[    8.644591] [PF_RING] Slot version     16
[    8.644596] [PF_RING] Capture TX       Yes [RX+TX]
[    8.644600] [PF_RING] IP Defragment    No
[    8.644603] [PF_RING] Initialized correctly
```

Examples from https://github.com/ntop/PF_RING/tree/dev/userland/examples work just fine. But when I start p0f it just hangs up whole PC. Nothing helps but hard reset.

I've tried to use lockup watchdog (with `softlockup_panic=1` parameter) - but no luck. Machine just hangs and that's it.

Is it possible that this is a bug in PF_RING code?

**Comment by cardigliano** [comment]
Hi Anton
since this does not happen with the sample applications provided with PF_RING,
it is hard to say if it is due to PF_RING or not. Do you have any trace?

Alfredo

**Comment by bak1an** [comment]
Hi Alfredo,

Unfortunately I don't have anything like a stacktrace for this. As I
mentioned machine just hangs up and the only thing you can do with it is
hard reset. And there are no logs afterwards.

The strange thing is that p0f is just a pcap application, how could it
cause a lockup like this?
One more interesting detail is that when I link p0f against centos stock
libpcap and run it without PF_RING it works just fine.

I'm now going to try adding some extra debug prints into p0f to see where
exactly it hangs up.
Perhaps setting a network kernel logging might also give us some more info
about what is going on there.

I will come back here as soon as I have more info.

Thanks!

**Comment by bak1an** [comment]
Hi Alfredo,

It's been a long time but I've finally managed to pull some data for you.

So here are the key facts I have:

- I'm trying to run http://lcamtuf.coredump.cx/p0f3/. It's a regular libpcap based application/library. There are some performance hacks but my guess that this should not lead to kernel panics.

- To install PF_RING I do following steps:
  * install compilers, kernel headers, etc
  * remove stock distro libpcap in case it's there
  * clone `dev` branch from https://github.com/ntop/PF_RING
  * `cd kernel ; make ; make install`
  * `cd userland/lib ; ./configure ; make ; make install`
  * `cd userland/libpcap ; ./configure ; make ; make install`
  * `modprobe pf_ring`

- When I run examples from PF_RING after above steps they work just fine.

- p0f + centos 7 (pf_ring module **NOT** loaded) **works** 

- p0f + centos 7 + PF_RING **hangs up**

- p0f + **debian 7** + PF_RING **works fine** (sic! install steps are the same as above, just used other distro)

- Hung up centos 7 machine is not responsive at all. Only hard reset helps.

- Here is what I was able to get using netconsole - https://gist.github.com/bak1an/a9e826c069f6075c0dc4 (`modprobe netconsole ; modprobe pf_ring ; ./p0f`) 

- I've tried adding prints to p0f itself. It seems to hang up at random places, 3-4 secs after start. There is poll loop (https://github.com/p0f/p0f/blob/master/p0f.c#L773) in most cases it hangs up after about 5 iterations.

That is all I have. Does this make any sense? Can I get some more info?

Thanks!

**Comment by bak1an** [comment]
`cat /proc/sys/net/core/bpf_jit_enable` gives me `0` on both debian and centos.

**Comment by cardigliano** [comment]
Please check this bug is still alive on latest code, we fixed bpf-related crashes (on bpf free) some time ago.

**Comment by bak1an** [comment]
@cardigliano it works now, thanks!
