### ISSUE TITLE
hash_pkt does not hash based on MAC addresses in case of non-IP packets

### ISSUE THREAD

**Issue by zambo99** [ntop/PF_RING#200]
While capturing traffic with lots of non-IP packets (PROFINET) we noticed that only one of the sniffing CPU cores was active, while all the other ones were almost inactive.

A quick look into the implementation of hash_pkt seems to confirm that packet hashing does not use source and destination MAC addresses when the traffic is non-IP.

Would it be possible to extend the implementation to also use MAC addresses for non-IP packets, so that it is possible to split the load into multiple cores?

**Comment by zambo99** [comment]
Would you at least consider merging the code I could provide if I make a pull request?

**Comment by cardigliano** [comment]
Hi @zambo99, sorry we have a lot of high priority tasks atm, I didn't have a change to look at this yet. If you send a pull request I will be happy to review and merge it.

**Comment by JuMeBe** [comment]
Hello, @cardigliano et al.
When do you think you can merge our pull request #231? Is there anything we can do to speed it up?
Thanks.

**Comment by cardigliano** [comment]
@JuMeBe there is something to fix in that pull request, please read my comments inline with the code

**Comment by JuMeBe** [comment]
@cardigliano I haven't found your comments anywhere. Can you send me a link or something?

**Comment by cardigliano** [comment]
Please see https://github.com/ntop/PF_RING/pull/231

> Please avoid moving an enum as it would break binary applications, causing the wrong cluster type to be selected.

In essence please do not change the order of preexisting enums.

**Comment by JuMeBe** [comment]
Definitely. Fixed and committed: please see  [commits](https://github.com/ntop/PF_RING/pull/231/commits) at #231.

**Comment by cardigliano** [comment]
Merged https://github.com/ntop/PF_RING/pull/231

**Comment by JuMeBe** [comment]
@cardigliano @lucaderi Do you guys have an estimate for when can we expect a new ntop release with the additions from this issue?
Thanks.

**Comment by cardigliano** [comment]
@JuMeBe this has been merged on Jul 18, if you install latest software you should already be able to use it. What do you mean with "ntop", do you mean ntopng?

**Comment by JuMeBe** [comment]
@cardigliano Yes, sorry, I think that's what I meant (I was only focused in PF_RING library).

I know it was merged, but we would rather use a tagged release which includes those additions (if a release can be expected within a reasonable time).
