### ISSUE TITLE
A general question

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#205]
I've a few more questions that I hope you can help with.

Objective
=========
send a packet and bounce it for and indefinite amount of time.

My system has an dual port NIC card (10G)
I have wired them as follows:

eth0,tx ----------> eth1,rx
eth0,rx <---------- eth1,tx

so, this way I can generate and transmit some traffic via eth0,tx. 
when eth1,rx recieves traffic, it will send it back to eth0,rx via eth1,tx

Configuration
=============
in order to achieve the above senario: 
1. I've created one cluster
2. I've created two Tx queues, one per device (two device queue for each port)
3. I've cretaed two Rx queues, one per device
4. I've cretaed two load-balancers (one per Tx queue), one for each device (two worker threads one per Rx queues). 
5. I've created two sets of three out-queues (consumer queues). Each out-queue is serviced by one consumer thread. Total of six consumer threads

configuration summary: two sets of Rx,Tx,loadbalancer/one worker threads, and three consumer threads.

Testing 
=======
When I activated one set of configuration (for example: eth0: {Rx,Tx,loadbalancer/one worker threads, and three consumer threads} and use either zsend/zbalance, I see the packets are either sent or received in both senarios. 

Question
========
Once I activated both sets I don't see any packets, event though the send command is reporting sending packets. 

Is this because in PF_RING cluster you can't do loop back as I'm doing?

Any help would be greatly appreciated.

P.S. I can't get tcpdump working (any idea).

Thank you, 
Steven

**Comment by cardigliano** [comment]
@szarea how are you sending packets when activating both sets? (tx of both interfaces is in use by your application)

**Comment by cardigliano** [comment]
Closed for inactivity, please reopen in case.
