### ISSUE TITLE
YUM error while trying to update "pfing" on centos 7.3.1611

### ISSUE THREAD

**Issue by ghost** [ntop/PF_RING#207]
Hello.

Running "yum update" on centos 7 and getting the error below. Just happened like yesterday. Any suggestions or what am I doing wrong or a way around? Thank you.

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

    base: mirror.keystealth.org
    epel: mirror.hmc.edu
    extras: repos-tx.psychz.net
    updates: mirror.scalabledns.com
    Resolving Dependencies
    --> Running transaction check
    ---> Package pfring.x86_64 0:6.6.0-1201 will be updated
    --> Processing Dependency: pfring = 6.6.0-1201 for package: ntopng-2.4.170428-1311.x86_64
    --> Processing Dependency: pfring = 6.6.0-1201 for package: n2disk-2.8.170428-4800.x86_64
    --> Processing Dependency: pfring = 6.6.0-1201 for package: cento-1.2.170428-93.x86_64
    --> Processing Dependency: pfring = 6.6.0-1201 for package: nprobe-7.4.170428-5335.x86_64
    ---> Package pfring.x86_64 0:6.6.0-1204 will be an update
    ---> Package pfring-dkms.noarch 0:6.6.0-1201 will be updated
    ---> Package pfring-dkms.noarch 0:6.6.0-1204 will be an update
    --> Finished Dependency Resolution
    Error: Package: ntopng-2.4.170428-1311.x86_64 (@ntop)
    Requires: pfring = 6.6.0-1201
    Removing: pfring-6.6.0-1201.x86_64 (@ntop)
    pfring = 6.6.0-1201
    Updated By: pfring-6.6.0-1204.x86_64 (ntop)
    pfring = 6.6.0-1204
    Error: Package: n2disk-2.8.170428-4800.x86_64 (@ntop)
    Requires: pfring = 6.6.0-1201
    Removing: pfring-6.6.0-1201.x86_64 (@ntop)
    pfring = 6.6.0-1201
    Updated By: pfring-6.6.0-1204.x86_64 (ntop)
    pfring = 6.6.0-1204
    Error: Package: nprobe-7.4.170428-5335.x86_64 (@ntop)
    Requires: pfring = 6.6.0-1201
    Removing: pfring-6.6.0-1201.x86_64 (@ntop)
    pfring = 6.6.0-1201
    Updated By: pfring-6.6.0-1204.x86_64 (ntop)
    pfring = 6.6.0-1204
    Error: Package: cento-1.2.170428-93.x86_64 (@ntop)
    Requires: pfring = 6.6.0-1201
    Removing: pfring-6.6.0-1201.x86_64 (@ntop)
    pfring = 6.6.0-1201
    Updated By: pfring-6.6.0-1204.x86_64 (ntop)
    pfring = 6.6.0-1204
    You could try using --skip-broken to work around the problem
    You could try running: rpm -Va --nofiles --nodigest

**Comment by cardigliano** [comment]
@jozatan it seems it is working for me, could you try updating again or removing/reinstalling the packages?

# yum list installed | grep "pfring\|n2disk"
n2disk.x86_64                        2.8.170428-4800                @ntop       
pfring.x86_64                        6.6.0-1204                     @ntop       
pfring-dkms.noarch                   6.6.0-1204                     @ntop-noarch
pfring-drivers-zc-dkms.noarch        1.2-0                          @ntop-noarch

**Comment by ghost** [comment]
Thank you

Updating it definitely didn't work as you can see form the log below but your suggestion removing/reinstalling it, did it.

Let me know if it is not appropriate to post such long logs. I'm trying only to help someone else if has that issue in the future.

[root@moon ~]# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.sonic.net
 * epel: mirror.hmc.edu
 * extras: denver.gaminghost.co
 * updates: centos.mirror.ndchost.com
Resolving Dependencies
--> Running transaction check
---> Package pfring.x86_64 0:6.6.0-1201 will be updated
--> Processing Dependency: pfring = 6.6.0-1201 for package: ntopng-2.4.170428-1311.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: n2disk-2.8.170428-4800.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: cento-1.2.170428-93.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: nprobe-7.4.170428-5335.x86_64
---> Package pfring.x86_64 0:6.6.0-1204 will be an update
---> Package pfring-dkms.noarch 0:6.6.0-1201 will be updated
---> Package pfring-dkms.noarch 0:6.6.0-1204 will be an update
--> Finished Dependency Resolution
Error: Package: ntopng-2.4.170428-1311.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
Error: Package: n2disk-2.8.170428-4800.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
Error: Package: nprobe-7.4.170428-5335.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
Error: Package: cento-1.2.170428-93.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@moon ~]# yum list installed | grep -E "pfring|n2disk"
n2disk.x86_64                        2.8.170428-4800                @ntop
pfring.x86_64                        6.6.0-1201                     @ntop
pfring-dkms.noarch                   6.6.0-1201                     @ntop-noarch
[root@moon ~]# yum erase pfring pfring-dkms
Loaded plugins: fastestmirror
Resolving Dependencies
--> Running transaction check
---> Package pfring.x86_64 0:6.6.0-1201 will be erased
--> Processing Dependency: pfring = 6.6.0-1201 for package: ntopng-2.4.170428-1311.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: n2disk-2.8.170428-4800.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: cento-1.2.170428-93.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: nprobe-7.4.170428-5335.x86_64
---> Package pfring-dkms.noarch 0:6.6.0-1201 will be erased
--> Running transaction check
---> Package cento.x86_64 0:1.2.170428-93 will be erased
---> Package n2disk.x86_64 0:2.8.170428-4800 will be erased
---> Package nprobe.x86_64 0:7.4.170428-5335 will be erased
---> Package ntopng.x86_64 0:2.4.170428-1311 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch         Version                Repository          Size
================================================================================
Removing:
 pfring            x86_64       6.6.0-1201             @ntop               10 M
 pfring-dkms       noarch       6.6.0-1201             @ntop-noarch       302 k
Removing for dependencies:
 cento             x86_64       1.2.170428-93          @ntop              3.7 M
 n2disk            x86_64       2.8.170428-4800        @ntop              4.9 M
 nprobe            x86_64       7.4.170428-5335        @ntop              8.1 M
 ntopng            x86_64       2.4.170428-1311        @ntop               65 M

Transaction Summary
================================================================================
Remove  2 Packages (+4 Dependent packages)

Installed size: 92 M
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : ntopng-2.4.170428-1311.x86_64                                1/6
Removing /usr/local/bin/ntopng link
  Erasing    : cento-1.2.170428-93.x86_64                                   2/6
  Erasing    : nprobe-7.4.170428-5335.x86_64                                3/6
Configuration directory /etc/n2disk does not exist: quitting...
  Erasing    : n2disk-2.8.170428-4800.x86_64                                4/6
Stopping pf_ring (via systemctl):  [  OK  ]
  Erasing    : pfring-6.6.0-1201.x86_64                                     5/6

Uninstall of pfring module (version 6.6.0) beginning:
Error! There are no instances of module: pfring
6.6.0 located in the DKMS tree.
  Erasing    : pfring-dkms-6.6.0-1201.noarch                                6/6
  Verifying  : pfring-6.6.0-1201.x86_64                                     1/6
  Verifying  : n2disk-2.8.170428-4800.x86_64                                2/6
  Verifying  : nprobe-7.4.170428-5335.x86_64                                3/6
  Verifying  : cento-1.2.170428-93.x86_64                                   4/6
  Verifying  : ntopng-2.4.170428-1311.x86_64                                5/6
  Verifying  : pfring-dkms-6.6.0-1201.noarch                                6/6

Removed:
  pfring.x86_64 0:6.6.0-1201           pfring-dkms.noarch 0:6.6.0-1201

Dependency Removed:
  cento.x86_64 0:1.2.170428-93           n2disk.x86_64 0:2.8.170428-4800
  nprobe.x86_64 0:7.4.170428-5335        ntopng.x86_64 0:2.4.170428-1311

Complete!
[root@moon ~]# yum erase zeromq3
Loaded plugins: fastestmirror
No Match for argument: zeromq3
No Packages marked for removal
[root@moon ~]# yum clean all
Loaded plugins: fastestmirror
Cleaning repos: base epel extras ntop ntop-noarch updates
Cleaning up everything
Cleaning up list of fastest mirrors
[root@moon ~]# yum update
Loaded plugins: fastestmirror
base                                                     | 3.6 kB     00:00
epel/x86_64/metalink                                     |  14 kB     00:00
epel                                                     | 4.3 kB     00:00
extras                                                   | 3.4 kB     00:00
ntop                                                     | 2.9 kB     00:00
ntop-noarch                                              | 2.9 kB     00:00
updates                                                  | 3.4 kB     00:00
(1/9): base/7/x86_64/group_gz                              | 155 kB   00:00
(2/9): epel/x86_64/group_gz                                | 170 kB   00:00
(3/9): extras/7/x86_64/primary_db                          | 151 kB   00:00
(4/9): ntop/7/x86_64/primary_db                            | 5.5 kB   00:00
(5/9): epel/x86_64/primary_db                              | 4.7 MB   00:00
(6/9): ntop-noarch/7/primary_db                            | 3.8 kB   00:00
(7/9): epel/x86_64/updateinfo                              | 788 kB   00:01
(8/9): updates/7/x86_64/primary_db                         | 4.8 MB   00:00
(9/9): base/7/x86_64/primary_db                            | 5.6 MB   00:02
Determining fastest mirrors
 * base: mirrors.cat.pdx.edu
 * epel: mirror.hmc.edu
 * extras: centos.mirror.ndchost.com
 * updates: mirror.chpc.utah.edu
No packages marked for update
[root@moon ~]# yum install pfring n2disk nprobe ntopng ntopng-data cento
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.pdx.edu
 * epel: mirror.hmc.edu
 * extras: centos.mirror.ndchost.com
 * updates: mirror.chpc.utah.edu
Package ntopng-data-2.4.170428-1311.noarch already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package cento.x86_64 0:1.2.170428-93 will be installed
---> Package n2disk.x86_64 0:2.8.170428-4800 will be installed
---> Package nprobe.x86_64 0:7.4.170428-5335 will be installed
---> Package ntopng.x86_64 0:2.4.170428-1311 will be installed
---> Package pfring.x86_64 0:6.6.0-1204 will be installed
--> Processing Dependency: pfring-dkms = 6.6.0 for package: pfring-6.6.0-1204.x86_64
--> Running transaction check
---> Package pfring-dkms.noarch 0:6.6.0-1204 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch         Version                 Repository         Size
================================================================================
Installing:
 cento             x86_64       1.2.170428-93           ntop              614 k
 n2disk            x86_64       2.8.170428-4800         ntop              919 k
 nprobe            x86_64       7.4.170428-5335         ntop              1.6 M
 ntopng            x86_64       2.4.170428-1311         ntop               28 M
 pfring            x86_64       6.6.0-1204              ntop              1.2 M
Installing for dependencies:
 pfring-dkms       noarch       6.6.0-1204              ntop-noarch        69 k

Transaction Summary
================================================================================
Install  5 Packages (+1 Dependent package)

Total download size: 32 M
Installed size: 92 M
Is this ok [y/d/N]: y
Downloading packages:
(1/6): cento-1.2.170428-93.x86_64.rpm                      | 614 kB   00:02
(2/6): n2disk-2.8.170428-4800.x86_64.rpm                   | 919 kB   00:02
(3/6): nprobe-7.4.170428-5335.x86_64.rpm                   | 1.6 MB   00:00
(4/6): pfring-6.6.0-1204.x86_64.rpm                        | 1.2 MB   00:00
(5/6): pfring-dkms-6.6.0-1204.noarch.rpm                   |  69 kB   00:00
(6/6): ntopng-2.4.170428-1311.x86_64.rpm                   |  28 MB   00:04
--------------------------------------------------------------------------------
Total                                              4.3 MB/s |  32 MB  00:07
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : pfring-dkms-6.6.0-1204.noarch                                1/6
WARNING: /usr/lib64/dkms/common.postinst does not exist.
Loading new pfring-6.6.0 DKMS files...
Building for 3.10.0-514.16.1.el7.x86_64
Building initial module for 3.10.0-514.16.1.el7.x86_64
Done.

pf_ring:
Running module version sanity check.

Good news! Module version 6.6.0 for pf_ring.ko
exactly matches what is already found in kernel 3.10.0-514.16.1.el7.x86_64.
DKMS will not replace this module.
You may override by specifying --force.
Adding any weak-modules
depmod: ERROR: fstatat(4, pf_ring.ko): No such file or directory

depmod...

DKMS: install completed.
  Installing : pfring-6.6.0-1204.x86_64                                     2/6
Starting pf_ring (via systemctl):  Job for pf_ring.service failed because the control process exited with error code. See "systemctl status pf_ring.service" and "journalctl -xe" for details.
[FAILED]
warning: %post(pfring-6.6.0-1204.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package pfring-6.6.0-1204.x86_64
  Installing : n2disk-2.8.170428-4800.x86_64                                3/6
Configuration directory /etc/n2disk does not exist: quitting...
  Installing : nprobe-7.4.170428-5335.x86_64                                4/6
  Installing : cento-1.2.170428-93.x86_64                                   5/6
Created symlink from /etc/systemd/system/multi-user.target.wants/cento.service to /etc/systemd/system/cento.service.
  Installing : ntopng-2.4.170428-1311.x86_64                                6/6
Setting up redis auto startup
Note: Forwarding request to 'systemctl enable redis.service'.
Creating link under /usr/local/bin
  Verifying  : pfring-6.6.0-1204.x86_64                                     1/6
  Verifying  : n2disk-2.8.170428-4800.x86_64                                2/6
  Verifying  : nprobe-7.4.170428-5335.x86_64                                3/6
  Verifying  : cento-1.2.170428-93.x86_64                                   4/6
  Verifying  : pfring-dkms-6.6.0-1204.noarch                                5/6
  Verifying  : ntopng-2.4.170428-1311.x86_64                                6/6

Installed:
  cento.x86_64 0:1.2.170428-93           n2disk.x86_64 0:2.8.170428-4800
  nprobe.x86_64 0:7.4.170428-5335        ntopng.x86_64 0:2.4.170428-1311
  pfring.x86_64 0:6.6.0-1204

Dependency Installed:
  pfring-dkms.noarch 0:6.6.0-1204

Complete!
[root@moon ~]# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.pdx.edu
 * epel: mirror.hmc.edu
 * extras: centos.mirror.ndchost.com
 * updates: mirror.chpc.utah.edu
No packages marked for update
[root@moon ~]# yum list installed | grep -E "pfring|n2disk"
n2disk.x86_64                        2.8.170428-4800                @ntop
pfring.x86_64                        6.6.0-1204                     @ntop
pfring-dkms.noarch                   6.6.0-1204                     @ntop-noarch
[root@moon ~]#

**Comment by cardigliano** [comment]
@jozatan thank you, we will check the update process
