### ISSUE TITLE
Change request in "/etc/init.d/pf_ring"

### ISSUE THREAD

**Issue by gianogli** [ntop/PF_RING#208]
Hi,
I think that there is an issue into this init file when someone want configure his server to avoid the pf_ring loading during the server boot.
The function `init_config()`, in fact, is always executed during each boot and, as you can see: 
```
init_config() {
        if [ ! -d "${PF_RING_CONFIG_DIR}" ]; then
                mkdir ${PF_RING_CONFIG_DIR}
        fi
        if [ ! -f "${PF_RING_CONFIG_DIR}/pf_ring.conf" ]; then
                touch "${PF_RING_CONFIG_DIR}/pf_ring.conf"
        fi
        if [ ! -f "${PF_RING_CONFIG_DIR}/pf_ring.start" ]; then
                touch "${PF_RING_CONFIG_DIR}/pf_ring.start"
        fi
        for F in ${DRIVERS_FLAVOR[@]} ; do
                for D in ${DKMS_DRIVERS[@]} ; do
                        if [ ! -d ${PF_RING_CONFIG_DIR}/${F}/${D} ]; then
                                mkdir -p ${PF_RING_CONFIG_DIR}/${F}/${D}
                        fi
                done
        done
}
```
the file `pf_ring.start` is always created even if someone voluntarily delete it (or rename it to `pf_ring.stop`).
Could you implement in all your init scripts the use of the `*.stop` files (`ntopng.stop`, `pf_ring.stop`) to avoid the loading of your software?
Thanks...

**Comment by cardigliano** [comment]
I changed the script to avoid rewriting the configuration if /etc/pf_ring has been already configured, checking the pf_ring.conf presence
