### ISSUE TITLE
How do you enable BPF filtering

### ISSUE THREAD

**Issue by yuyi2017yuyi** [ntop/PF_RING#209]
[root@localhost eth2]# cat info
Name:         eth2
Index:        108
Address:      68:91:D0:60:89:8C
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    4
RX Queues:    4
Num RX Slots: 4096
Num TX Slots: 4096

[root@localhost pf_ring]# cat 6215-eth2.3443
Bound Device(s)    : 
Active             : 1
Breed              : ZC
Appl. Name         : pfring-zc-0-zc:eth2@0
Socket Mode        : RX only
Capture Direction  : RX only
Sampling Rate      : 1
IP Defragment      : No
BPF Filtering      : Disabled                               
Sw Filt Hash Rules : 0
Sw Filt WC Rules   : 0
Hw Filt Rules      : 0
Sw Filt Hash Match : 0
Sw Filt Hash Miss  : 0
Poll Pkt Watermark : 128
Num Poll Calls     : 0
Channel Id         : 0
Num RX Slots       : 4096

QUESTION:
                   **how to set  BPF Filtering   from  Disabled   to Enabled ?**   I have download the last PF_RING version and try as following:

cd <PF_RING>/userland/lib 
./configure --enable-bpf 
make

but it had not changed, thank for you help!!

**Comment by cardigliano** [comment]
@yuyi2017yuyi BPF filters are evaluated in userspace when using ZC (which is a kernel bypass technology), that line is actually misleading, as it reports the status of BPF inside the kernel. I will remove it in case of ZC.
