### ISSUE TITLE
Question about clusters

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#21]
Hello. I need to read a traffic from set of ingress interfaces, process it, and send it to egress set of interfaces. Please tell me, must I create 2 clusters (for ingress and for egress interfaces), or I need to use one common cluster and include all interfaces to this single cluster? Do you have an example for this issue?

**Comment by cardigliano** [comment]
Please have a look at zreplicator.c and zbounce.c under userland/examples_zc.

**Comment by Skryabind** [comment]
@cardigliano thank you, I look at zreplicator.c, zbounce.c and zbalance.c also, and for total understanding have a question. Please, tell, is it a correct alghoritm?
 To read a traffic from incoming N-interfaces and send them to other M-interfaces (with using some threads), I need to open all that devices in one cluster (by pfring_zc_open_device with rx_only/tx_only respectively) and create a two workers (pfring_zc_run_balancer) for incoming and outgoing traffic. When processing a traffic in different threads I will read a traffic from incoming queues and  send it to outgoing queues. Is it correct?
Thank you.

**Comment by cardigliano** [comment]
Correct, please note that you cannot share the same queues with different workers (queues are single producer / single consumer).
