### ISSUE TITLE
Interface stops receiving packets

### ISSUE THREAD

**Issue by jordanca** [ntop/PF_RING#210]
Hi, I have an issue where a NIC card seemingly locks up after some time. All 4 interfaces on this card can not receive any packets. Only a reboot causes the interfaces to start working again only then to lockup again after some time (roughly 1 hour).  There are no logs or errors that I can see.

Current Setup
Centos 6.9 (2.6.32-696.1.1.el6.x86_64)
PF_RING 6.6.0 stable (not using the ZC drivers)
Using tcpdump 4.9.0 to capture incoming packets
4 x intel x710 i40e (4 x 10gb interfaces per card)

The other 3 cards are not having this issue. 

Are you able to help me try and diagnose the issue before I label it a hardware issue.  I can capture packets on each interface on this card fine without issue. Just stops capturing after a time with the only fix for now...a reboot.

Let me know what info I can provide.

Thanks,
Jordan

**Comment by cardigliano** [comment]
Hi @jordanca, this looks like an hw or driver issue, please double check removing pf_ring and capturing with vanilla tcpdump. Thank you

**Comment by jordanca** [comment]
Thanks for your advice cardigliano......turns out it was an issue with the firmware version of the x710. Have since updated an no longer seeing the issues.

Cheers,
Jordan
