### ISSUE TITLE
driver issue

### ISSUE THREAD

**Issue by Ransetsu** [ntop/PF_RING#211]
are the drivers only for zc or can they be used with vanilla? Because when I load the pf_ring compiled e1000e driver onto my on board network interface (which uses the regular e1000e driver), all packets get dropped at the interface

steps taken as root:
rmmod e1000e
insmod /lib/modules/kernel-version/kernel/net/pf_ring/pf_ring.ko transparent_mode=2
insmod /PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000e.ko
/PF_RING/userland/tcpdump/tcpdump -i eth0 -G 120 -w rotate_%Y%m%d%H%M%S

tcpdump captures nothing and pfcount doesnt see any traffic and when i stop tcpdump it gives me zeros for captured and dropped. The kernel module does work without the driver and i do see traffic that way. The only problem is at 1gbps traffic the file size starts out okay at ~14gb per every 2 minutes but will drop to about 9gb over time. Yet, with the standard version of tcpdump and no pf_ring we see a consistent 12gb file size. Not sure what is going on.

**Comment by cardigliano** [comment]
@Ransetsu our ZC drivers are also able to work as standard drivers, what you are seeing is strange, it needs to be debugged somehow. Any change to provide (ssh?) access to this machine?
