### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by ExxonLIVE** [ntop/PF_RING#216]
Hi, 

i was using the installation guide provided on [NTOP->Get Started->Download](http://www.ntop.org/get-started/download/). 

Step 1 and 2 worked perfectly. But the "make" command does not work:
```
pi@raspberrypi:~/PF_RING/kernel $ make
make -C /lib/modules/4.9.24-v7+/build SUBDIRS=/home/pi/PF_RING/kernel EXTRA_CFLAGS='-I/home/pi/PF_RING/kernel -DGIT_REV="\"dev:08d0f2542680b9d9399c6910f3decadf92c5b43c\""' modules
make[1]: *** /lib/modules/4.9.24-v7+/build: Datei oder Verzeichnis nicht gefunden.  Schluss.
Makefile:48: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm using a Raspberry Pi 3 and have no special Linux skills. I was running all commands as root and pi. Both did not work.

In advance: Thank you for your help and may the force be with you.

**Comment by cardigliano** [comment]
Hi
you are getting the error because you need to install kernel headers in order to compile PF_RING.

Alfredo

**Comment by ExxonLIVE** [comment]
Hi,

thank you for your help.

How do i install the kernel headers?

**Comment by cardigliano** [comment]
Please search on google how to install kernel headers on raspberry based on your kernel version (I am sorry we are not able to support you with this)
