### ISSUE TITLE
transparent_mode=2 replacement?

### ISSUE THREAD

**Issue by Manouchehri** [ntop/PF_RING#217]
Since `transparent_mode` is now deprecated, is there another easy solution to completely block the Linux kernel from accessing certain ZC devices/ports?

I'm implementing a transparent bridge, and trying to avoid any traffic from the PF_RING box from accidentally being sent out.

**Comment by cardigliano** [comment]
@Manouchehri when you open an interface in ZC mode, it gets detached from the kernel (no packet from the kernel can reach the adapter). However, if there is no active ZC socket on the interface, then it works as a standard interface. If the latter is a problem for you, the only option is to patch the driver to add a new option for preventing the card from speaking with the kernel at all.
