### ISSUE TITLE
TX Queue is full; PF_Rring fails to transmit packets from multiple threads. The transmit buffer is overflowed.

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#220]
Hi,
I would greatly appreciate if you could help me to resolve this issue.

Problem Summary Definition:
TX Queue is full; PF_Rring fails to transmit packets from multiple threads. The transmit buffer is overflowed.

System Configuration:
I am using two dual port Intel 10 gig cards (Eth8, Eth9, Eth10, and Eth11)
Eth8 is connected to Eth10 and Eth9 is connected to Eth11 (Eth8 <--> Eth10, Eth9<--> eth11) 

My Application opens Eth8 for both RX & TX and opens Eth9 for RX as follows:
::pfring_zc_open_device(clusterHandle, “zc:eth8”, rx_only)
::pfring_zc_open_device(clusterHandle, “zc:eth8”, tx_only)
::pfring_zc_open_device(clusterHandle, “zc:eth9”, tx_only)

Application opens a consumer queue per consumer threads as follows: 
::pfring_zc_create_queue(clusterHandle, MaxQueueLen)

Application is configured with four consumer threads and one worker thread.
The worker thread receives ingress packets from Eth10 (using zsend application) as follows:
::pfring_zc_recv_pkt(thePfringRxInQueue, thePfringRxPktBuf, theRxActiveWaity)

The ingress packets are distributed in round-robin fashion to consumers’ threads. Each consumer thread processes its own ingress packets and retransmitted them to Eth11 as follows:
sentBytes = ::pfring_zc_send_pkt(thePfringTxOutQueue,
               &thePfringRxPktBuf[pktBufIndex],
                thePsdConsumerThreadInfo->theFlushPacket);

Detail Definition:

Application handles 10 gig bits/s in line rate with four consumer threads, but when it tries to transmit the ingress packets out via TX-queue, Tx queue fails. ::pfring_zc_queue_is_full() returns one(1).
However, if I use one thread as a consumer thread it works fine. However, one thread handles only a quarter of transmitted data (2.5 gig). 
I reluctantly introduce usleep and got mixed results. For example:
usleep(<100) won’t make any difference.
usleep (>1000) with ::pfring_zc_sync_queue(zq, tx_only) with two consumer threads, I get packets transmitted with disaster performance.

Hardware configurations:
CPUs & Cores
=====
Process Frequency 2.4 GHZ
L1 cache RAM 896 K
L2 cache RAM 3584 K
L3 vache RAM 35840 K
CPU1 version Intel Xeon E5-2680 v4 @ 2.4 GHZ
CPU2 version Intel Xeon E5-2680 v4 @ 2.4 GHZ
14 cores per CPU, 
total cores 28

PCI Slots
=======
Slot1 PCI-E 3.0 X8
Slot2 PCI-E 3.0 X8
Slot3 PCI-E 3.0 X16
Slot4 PCI-E 2.0 X8
Slot5 PCI-E 3.0 X16
Slot6 PCI-E 3.0 X8

Network Cards
============
IXGBE — Two Dual-port Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

Memory
=======
8 & 32 GB DIMMS of DDR4  with speed of 2400 MHZ 
Total memory 262144
Memory Speed 2400

load_driver.sh:

#!/bin/bash
FAMILY=ixgbe
# Remove old modules (if loaded)
rmmod ixgbe
rmmod pf_ring

insmod ../../../../../kernel/pf_ring.ko enable_ip_defrag=1 min_num_slots=8192 quick_mode=1 enable_tx_capture=0
# Required by ixgbe
modprobe ptp
modprobe vxlan
modprobe dca

MAX_NUM_RX_SLOTS=65535

# Select the CPU of the NUMA node where per-adapter memory will be allocated
insmod ./ixgbe.ko RSS=1,1,1,1 numa_cpu_affinity=0,0,14,15

sleep 1

killall irqbalance

INTERFACES=$(cat /proc/net/dev|grep ':'|grep -v 'lo'|grep -v 'sit'|awk -F":" '{print $1}'|tr -d ' ')
for IF in $INTERFACES ; do
        TOCONFIG=$(ethtool -i $IF|grep $FAMILY|wc -l)
        if [ "$TOCONFIG" -eq 1 ]; then
                printf "Configuring %s\n" "$IF"
                ifconfig $IF up
                sleep 1
                bash ../scripts/set_irq_affinity $IF

                # Max number of RX slots
                ethtool -G $IF rx $MAX_NUM_RX_SLOTS

                # Max number of TX slots
                ethtool -G $IF tx $MAX_NUM_RX_SLOTS

                # Disabling VLAN stripping
                ethtool -K $IF rxvlan off

                # Disabling Flow Control (actually it should be automatically disabled by the driver)
                #ethtool -A $IF autoneg off
                ethtool -A $IF rx off
                ethtool -A $IF tx off
fi
done

HUGEPAGES_NUM=2048
HUGEPAGES_PATH=/dev/hugepages
sync && echo 3 > /proc/sys/vm/drop_caches
echo $HUGEPAGES_NUM > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
if [ `cat /proc/mounts | grep hugetlbfs | grep $HUGEPAGES_PATH | wc -l` -eq 0 ]; then
        if [ ! -d $HUGEPAGES_PATH ]; then
                mkdir $HUGEPAGES_PATH
        fi
        mount -t hugetlbfs nodev $HUGEPAGES_PATH
fi
HUGEPAGES_AVAIL_1=$(grep HugePages_Total /sys/devices/system/node/node0/meminfo | cut -d ':' -f 2|sed 's/ //g')
HUGEPAGES_AVAIL_2=$(grep HugePages_Total /sys/devices/system/node/node1/meminfo | cut -d ':' -f 2|sed 's/ //g')
HUGEPAGES_AVAIL=`expr $HUGEPAGES_AVAIL_1 + $HUGEPAGES_AVAIL_2`
if [ $HUGEPAGES_AVAIL -ne $HUGEPAGES_NUM ]; then
        printf "Warning: %s hugepages available, %s requested\n" "$HUGEPAGES_AVAIL" "$HUGEPAGES_NUM"
fi

Thank you,
Steven

**Comment by cardigliano** [comment]
Is thePfringTxOutQueue (eth11) shared between all threads?

**Comment by szarea** [comment]
yes, thePfringTxoutQueue(Eth9) is shared among all the consumer threads.

**Comment by szarea** [comment]
Let me simplify the scenario, one TX queue(zq) is shared among four consumer threads.
Each consumer thread has its own pfring_zc_pkt_buff buffer. Each consumer thread perform the following instruction in a tight loop:

   pktBufIndex = pktCnt & (MAX_OUTPUT_BUFFS-1);
   u_char *buffer = pfring_zc_pkt_buff_data(buffers[pktBufIndex], zq);
   buffers[pktBufIndex]->len = 60;
   forge_udp_packet(buffer, pktCnt++);
   sentBytes = ::pfring_zc_send_pkt(zq,
              &buffers[pktBufIndex],
               thePsdConsumerThreadInfo->theFlushPacket);

**Comment by cardigliano** [comment]
Plesae note pfring_zc_send_pkt() on the same queue is not permitted, as queues (including devices) are single-producer/single-consuer to avoid locks. An option is loading the interface with multiple RSS queues, one per thread, transmitting on a different TX queue per thread (thread 0 on zc:ethX@0, thread 1 on zc:ethX@1, and so on)

**Comment by szarea** [comment]
Thank you for your response.  I'm using one nick card for reading(eth8) and another nick card for writing(eth9).
so if I understood you correctly, I need to configure the writer nick(eth9) with RSS 4 and and open a four tx-queues. I will give shut right now. Again thank you for feedback.

**Comment by cardigliano** [comment]
Correct
