### ISSUE TITLE
Does PF_RING support interface "lo"?

### ISSUE THREAD

**Issue by shang-wang** [ntop/PF_RING#221]
Hi all:

I'm using PF_RING to do the packet capturing, but found out that it doesn't work for `lo` interface. I'm trying this on virtual machine with ubuntu 14.04, compiled `pfcount` and run, here's the output:
```
vagrant@ubuntu-1404:~/PF_RING/userland/examples [13:15:10][dev] $ sudo ./pfcount -i lo
pfring_open error [No such device] (pf_ring not loaded or interface lo is down ?)
vagrant@ubuntu-1404:~/PF_RING/userland/examples [13:15:31][dev] $ sudo ./pfcount -i eth0
Using PF_RING v.6.7.0
Capturing from eth0 [mac: 08:00:27:AD:41:5D][if_index: 2][speed: 1000Mb/s]
# Device RX channels: 1
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/2852-eth0.16
=========================
Absolute Stats: [1 pkts total][0 pkts dropped][0.0% dropped]
[1 pkts rcvd][84 bytes rcvd]
=========================
...
```
It clearly shows that the interface `lo` is not recognized while `eth0` works fine. What am I missing? Thanks!

**Comment by cardigliano** [comment]
@shang-wang loopback was not supported by PF_RING as we usually capture network traffic, now I enabled loopback capture in latest dev code, please check it.

**Comment by zinid** [comment]
Just for the record, it doesn't work for me, `dmesg` reports:
```
[ 3115.277339] [PF_RING] bind: lo dev index not found
```
Tested with `dev` branch (14f62e0edb2b54cd614ab9d1f6467ccb8c6c9c32).

**Comment by zinid** [comment]
If anyone is interested, as a workaround I use `dummy` interface instead of `lo`, which seems to be working:
```
# ip link add dummy0 type dummy
# ip link set dev dummy0 up
```

**Comment by cardigliano** [comment]
What version are you using?

**Comment by zinid** [comment]
PF_RING version is 14f62e0edb2b54cd614ab9d1f6467ccb8c6c9c32
Linux kernel version is `5.4.0-2-amd64 #1 SMP Debian 5.4.8-1 (2020-01-05) x86_64`

**Comment by cardigliano** [comment]
Same version is working for me, I will test it with the same kernel.
