### ISSUE TITLE
pfring_zc fails with capture tx

### ISSUE THREAD

**Issue by splitice** [ntop/PF_RING#224]
We attempted to upgrade our ipstats software (https://github.com/splitice/ipstats/blob/master/ipstats.cpp) to pfring_zc.

On the testing hardware intel i210 with igb_zc driver we attempted to test the new version. Although we are using the zc module we have not *yet* got a licence.

The device is opened with the PF_RING_ZC_DEVICE_CAPTURE_TX flag and yet the tx side is not captured.

```
        for (int i = 0; i < ndev; i++){
                inzq[i] = pfring_zc_open_device(zc, dev[i], rx_only, PF_RING_ZC_DEVICE_CAPTURE_TX);

                if (inzq[i] == NULL) {
                  fprintf(stderr, "failed to create in queue\n");
                  return;
                }

                get_mac(dev[i], macs + (i * 6));
        }

        if(ndev != 1){
        /*      zq = pfring_zc_create_queue(zc, 1024);
                pfring_zc_run_balancer(inzq, &zq, ndev, 1, NULL, round_robin_bursts_policy, false, 0);*/
        }else{
                zq = inzq[0];
        }

        while (running){
                if((n = pfring_zc_recv_pkt_burst(zq, buffers, BURST_LEN, 1)) > 0) {
                  for (int i = 0; i < n; i++) {
                        u_char *pkt_data = pfring_zc_pkt_buff_data(buffers[i], zq);
                        ethernet_handler(pkt_data, is_incomming(macs, ndev, pkt_data));
                  }
                }
        }
```

The RX side is captured fine.

**Comment by cardigliano** [comment]
@splitice what is the interface name in dev[i] ?

**Comment by splitice** [comment]
zc:eth0

**Comment by cardigliano** [comment]
@splitice please note you cannot capture TX on a ZC interface (when using the zc: prefix) as kernel is detached (ZC is a kernel-bypass technology and the application takes full control over the card)
