### ISSUE TITLE
Userpace BPF in ZC

### ISSUE THREAD

**Issue by cardigliano** [ntop/PF_RING#225]
pfring_zc_set_bpf_filter on dev queues generates hw rules when supported by the underlying hw, otherwise it just does nothing. It should use userspace BPF instead as fallback. The same should happen for SPSC queues.

**Comment by cardigliano** [comment]
Update: BPF support for SPSC queues has been added.

**Comment by liuchuang** [comment]
It doesn't work in my environmental test（linux-2.6.32-696,pfring6.6.0,ixgbe zc ,82599EB）。
I added the api: pfring_zc_set_bpf_filter(inzqs[i],"host 1.2.3.4") in example_zc/zbalance_ipc.c,but it can't filter any package。did I miss any steps?

**Comment by cardigliano** [comment]
Could you check with latest stable or dev?

**Comment by liuchuang** [comment]
cannot work in pfring7.0.0-stable and dev too。

**Comment by liuchuang** [comment]
thx,add the pfring_zc_set_bpf_filter in example_zc/zcount_ipc.c,it works。
can I use this api in example_zc/zbalance_ipc.c(input queue:inzqs) ?
or how to use this api in old type interface(pfring_open) like pfcount -i zc:1@1 ?

**Comment by cardigliano** [comment]
Please note you should set the filter in the consumer application, you can use both the ZC API or the standard API, both have functions to set the BPF.
