### ISSUE TITLE
pf-ring license does  not work after update

### ISSUE THREAD

**Issue by izzie88** [ntop/PF_RING#226]
Hello,
Please after my update the pf_ring license does not work anymore.
pf ring is loaded
and license says its ok

root@NTOP-DPI:~# zcount -i eth0 -C 
License Ok
root@NTOP-DPI:~# zcount -i eth0 -M
0 No expiration
root@NTOP-DPI:~# zcount -i eth2 -C 
License Ok
root@NTOP-DPI:~# zcount -i eth2 -M
0 No expiration
root@NTOP

root@NTOP-DPI:~# lsmod | grep ring
pf_ring              1236992  2

Name:         eth0
Index:        7
Address:      90:E2:BA:9F:35:20
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 32768
Num TX Slots: 32768
Name:         eth2
Index:        8
Address:      90:E2:BA:9F:35:21
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 32768
Num TX Slots: 32768

**Comment by izzie88** [comment]
Even though i have a valid license i still get the logs below.

#########################################################################
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC license 6.7.0.170613 for eth0 [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC license 6.7.0.170613 for eth2 [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################

**Comment by cardigliano** [comment]
Please use the zc: prefix when checking license (non zc interface does not require a license)
zcount -i zc:eth0 -C
