### ISSUE TITLE
Large number of dropped packets by PF_RING after upgrade from 6.0.3 to 6.6.0

### ISSUE THREAD

**Issue by pavel-odintsov** [ntop/PF_RING#229]
Hello, guys!

I'm working on an ability to use your latest code together with FNM open source because our customers ask us to do it because they usually have your commercial licenses and do not want to use outdated code 👍 

I just replaced PF_RING 6.0.3 by 6.6.0 and it does not work at all. My test machine is Debian 9 with 4.9 kernel but I got reports that other versions also does not work: https://github.com/pavel-odintsov/fastnetmon/issues/601

My traffic rate is extremely small. I just downloaded 1Gb file with DogotalOcean VPS.

Right now I'm playing with PF_RING non-zc and our code is extremely simple and clear: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/pfring_plugin/pfring_collector.cpp#L692 

Also, I noticed a huge number of dropped packets in same time and probably PF_RING drops everything at this moment.

```
Packets received:       591
Packets dropped:        13326
Packets dropped:        2254.8 %
```

And I use this code to extract these counters:
```
if (pfring_stats(pf_ring_descr, &pfring_status_data) >= 0) {
            char stats_buffer[256];
            double packets_dropped_percent = 0;

            if (pfring_status_data.recv > 0) {
                packets_dropped_percent = (double)pfring_status_data.drop / pfring_status_data.recv * 100;
            }

            sprintf(stats_buffer, "Packets received:\t%lu\n"
                                  "Packets dropped:\t%lu\n"
                                  "Packets dropped:\t%.1f %%\n",
                    (long unsigned int)pfring_status_data.recv,
                    (long unsigned int)pfring_status_data.drop, packets_dropped_percent);
            output_buffer << stats_buffer;
        } else {
            logger << log4cpp::Priority::ERROR << "Can't get PF_RING stats";
        }
```

Could you help me? Probably, some small constant or additional function call required but now I stuck and have no idea what I should change. 

Thank you so much!

**Comment by cardigliano** [comment]
Hi @pavel-odintsov, please provide:
1. cat /proc/net/pf_ring/info
2. cat /proc/net/pf_ring/dev/ethX/info
3. ethtool -i ethX
4. the actual dev and flags parameters passed to pfring_open()
5. some stats using pfcount -i ethX

**Comment by pavel-odintsov** [comment]
Thanks for the fast response! And sorry about bothering your at weekends :)

It was my fault. I used PF_RING 6.0.3 library and PF_RING 6.6.0 kernel module. Now it works really cool:
```
FastNetMon 1.1.3 master git-94f4947e87753b8be193ca54d17dac24cac599fb Pavel Odintsov: stableit.ru
IPs ordered by: packets
Incoming traffic          1363 pps    138 mbps      0 flows
138.68.110.77             1363 pps    138 mbps      0 flows

Outgoing traffic          1092 pps      0 mbps      0 flows
138.68.110.77             1092 pps      0 mbps      0 flows

Internal traffic             0 pps      0 mbps

Other traffic                0 pps      0 mbps

Screen updated in:              0 sec 438 microseconds
Traffic calculated in:          0 sec 71 microseconds
Total amount of IPv6 packets related to our own network: 0
Not processed packets: 0 pps
Packets received:       77316
Packets dropped:        0
Packets dropped:        0.0 %
```
