### ISSUE TITLE
installing pf-ring on Mac OS X

### ISSUE THREAD

**Issue by Drewshg312** [ntop/PF_RING#23]
I'm trying to install pf-ring on mac os x yosemite 10.10.4. Doing what's written here: http://www.ntop.org/get-started/download/
so:

    git clone https://github.com/ntop/PF_RING.git
    cd PF_RING/kernel

so far so good, bu when doing "make" getting this:

    $ make
    make -C /lib/modules/14.4.0/build SUBDIRS=/usr/local/src/PF_RING/kernel EXTRA_CFLAGS='-I/usr/local/src/PF_RING/kernel -DGIT_REV="\"dev:b2a8f8a93b226e74428424e91a2ea3bd3148123d\""' modules
    make[1]: *** /lib/modules/14.4.0/build: No such file or directory.  Stop.
    Makefile:38: recipe for target 'all' failed
    make: *** [all] Error 2

Maybe some dependencies absent?
What's the problem and how to solve it? Please help!
Thank you!

**Comment by cardigliano** [comment]
PF_RING runs on linux only.

**Comment by Drewshg312** [comment]
than probably you don't need /usr/local/src/PF_RING/userland/libpcap-1.6.2-ring/README.macosx and all related stuff...  Am I wrong?

**Comment by cardigliano** [comment]
Correct, they are files from the original libpcap.

**Comment by Drewshg312** [comment]
Too bad(
