### ISSUE TITLE
No matter how I configure the interfaces I'm not able to send more than 26 Gbps per interface and receive almost 24 Gbps. The driver is dropping 2 Gbps.

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#230]
Hi

Background Info:
================
My goal is to generate 40 Gbps traffic from an interface and receive 40 Gbps data from another interface.
eth20 ------------->eth21 
          40 Gbps

Eth20 is binded to numa zero and eth21 is binded to numa 1 

Issue Summary
=============
No matter how I configure the interfaces I'm not able to send more than 26 Gbps per interface and receive almost 24 Gbps. The driver is dropping 2 Gbps.

Issue Detail
============  
I have observed the following scenarios:

Scenario One:
============
RSS set 1 for both eth20 & eth21
Max throughput for zsend is 15 Gbps and zcount is capable of handling 15 Gbps (minor drops).

Scenario Two:
============
RSS set to 2 for Eth20 and RSS is to 1 for Eth21
Max throughput for zsend@0 and zsend@1 is 26 Gbps and zcount can handle only 23 Gbps and drops the rest.

Scenario Three:
==============
RSS set to 2 for both eth20 & eth21
Max throughput for zsend@0 and zsend@1 is 26 Gbps and zcount@0 & zcout@1 can handle only 23 Gbps and drops the rest.

From this point it does not matter how I configure the RSS, I get the same result
I even tried with RSS set to 14 for both eth20 & eth21 I got the same result.

Note: Intel has provided a new version of their 40 gig driver (version 2.0.23). Does PF_Ring support it?
 

Any help is greatly appreciated.

Steven  

Topology
========
back to back, Eth20 generates traffic via zsend and Eth21 receives traffic via zcount

PF_RING Info
============
[root@localhost examples_zc]# cat /proc/net/pf_ring/info
PF_RING Version          : 6.7.0 (dev:9273fe2299ba50670a736b052e3377c527eb4752)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 8192
Slot version             : 16
Capture TX               : No [RX only]
IP Defragment            : Yes
Socket Mode              : Quick
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
[root@localhost examples_zc]# cat /proc/net/pf_ring/dev/eth20/info 
Name:         eth20
Index:        22
Address:      68:05:CA:2E:74:C8
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    14
RX Queues:    14
Num RX Slots: 4096
Num TX Slots: 4096
[root@localhost examples_zc]# cat /proc/net/pf_ring/dev/eth21/info
Name:         eth21
Index:        24
Address:      68:05:CA:30:67:68
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    14
RX Queues:    14
Num RX Slots: 4096
Num TX Slots: 4096
[root@localhost examples_zc]# cat /proc/net/pf_ring/dev/eth22/info
Name:         eth22
Index:        25
Address:      68:05:CA:30:67:69
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    1
RX Queues:    1
Num RX Slots: 4096
Num TX Slots: 4096
[root@localhost examples_zc]# cat /proc/net/pf_ring/dev/eth23/info
Name:         eth23
Index:        23
Address:      68:05:CA:2E:74:C9
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    1
RX Queues:    1
Num RX Slots: 4096
Num TX Slots: 4096

Hardware Spec
===============
CPUs & Cores
=============
Process Frequency 2.4 GHZ
L1 cache RAM 896 K
L2 cache RAM 3584 K
L3 vache RAM 35840 K
CPU1 version Intel Xeon E5-2680 v4 @ 2.4 GHZ
CPU2 version Intel Xeon E5-2680 v4 @ 2.4 GHZ
14 cores per CPU, 
total cores 28

PCI Slots (using X16 & X8 PCI SLOT)
==========
Slot1 PCI-E 3.0 X8
Slot2 PCI-E 3.0 X8
Slot3 PCI-E 3.0 X16
Slot4 PCI-E 2.0 X8
Slot5 PCI-E 3.0 X16
Slot6 PCI-E 3.0 X8

Network Cards
============
i40e — Two Dual-port Intel Corporation
Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 01)
Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 01)

Memory
=======
8 & 32 GB DIMMS of DDR4  with speed of 2400 MHZ 
Total memory 262144
Memory Speed 2400

Driver Info
==============
[root@localhost examples_zc]# ethtool --driver eth20
driver: i40e
version: 1.5.18
firmware-version: 4.24 0x800013fc 0.0.0
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

Interface Info
==============
[root@localhost src]# ethtool eth21
Settings for eth21:
        Supported ports: [ FIBRE ]
        Supported link modes:   40000baseCR4/Full 
        Supported pause frame use: Symmetric
        Supports auto-negotiation: Yes
        Advertised link modes:  40000baseCR4/Full 
        Advertised pause frame use: No
        Advertised auto-negotiation: Yes
        Speed: 40000Mb/s
        Duplex: Full
        Port: Direct Attach Copper
        PHYAD: 0
        Transceiver: external
        Auto-negotiation: on
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x0000000f (15)
                               drv probe link timer
        Link detected: yes
[root@localhost src]# ethtool eth22
Settings for eth22:
        Supported ports: [ FIBRE ]
        Supported link modes:   40000baseCR4/Full
        Supported pause frame use: Symmetric
        Supports auto-negotiation: Yes
        Advertised link modes:  40000baseCR4/Full
        Advertised pause frame use: No
        Advertised auto-negotiation: Yes
        Speed: 40000Mb/s
        Duplex: Full
        Port: Direct Attach Copper
        PHYAD: 0
        Transceiver: external
        Auto-negotiation: on
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x0000000f (15)
                               drv probe link timer
        Link detected: yes

numa binding
============
[root@localhost examples_zc]# cat /sys/class/net/eth20/device/numa_node
0
[root@localhost examples_zc]# cat /sys/class/net/eth21/device/numa_node
1
[root@localhost examples_zc]# cat /sys/class/net/eth22/device/numa_node
1
[root@localhost examples_zc]# cat /sys/class/net/eth23/device/numa_node
0

load_drive.sh
=============
#!/bin/bash

FAMILY=i40e

#service udev start

# Remove old modules (if loaded)
rmmod i40e
rmmod pf_ring

# We assume that you have compiled PF_RING
insmod ../../../../../kernel/pf_ring.ko enable_ip_defrag=1 min_num_slots=8192 quick_mode=1 enable_tx_capture=0

# Required by i40e
modprobe ptp
modprobe vxlan
modprobe configfs

# Load the driver
insmod ./i40e.ko

# Enable debugging
#find /sys/kernel/debug/i40e/ -name command -exec sh -c 'echo  "msg_enable 16" > {}' {} ';'

# Disable multiqueue
#find /sys/kernel/debug/i40e/ -name command -exec sh -c 'echo  "set rss_size 1" > {}' {} ';'

sleep 1

MAX_NUM_RX_SLOTS=4096
#MAX_NUM_RX_SLOTS=65535

killall irqbalance 

INTERFACES=$(cat /proc/net/dev|grep ':'|grep -v 'lo'|grep -v 'sit'|awk -F":" '{print $1}'|tr -d ' ')
for IF in $INTERFACES ; do
        echo "interface:[$IF] is being processed"
        TOCONFIG=$(ethtool -i $IF|grep $FAMILY|wc -l)
        echo "Family_type:[$FAMILY] was found:[$TOCONFIG]"
        if [ "$TOCONFIG" -eq 1 ]; then
                printf "Configuring %s\n" "$IF"
                if [[ $IF = eth20 ]] || [[ $IF == eth21 ]] ; then
                   # Set number of RSS queues to four 
                   echo "Setting number of RSS queue to FOUR"
                   ethtool -L $IF combined 14
                else
                   # Set number of RSS queues
                   echo "Setting number of RSS queue to ONE"
                   ethtool -L $IF combined 1
                fi

                # Max number of RX slots
                ethtool -G $IF rx $MAX_NUM_RX_SLOTS

                # Max number of TX slots
                ethtool -G $IF tx $MAX_NUM_RX_SLOTS

                # Disabling offloads
                ethtool -K $IF sg off tso off gso off gro off > /dev/null 2>&1

                # Disabling VLAN stripping
                ethtool -K $IF rxvlan off

                # Flow Control automatically disabled by the driver (no need to use the following commands)
                #ethtool -A $IF autoneg off
                #ethtool -A $IF rx off
                #ethtool -A $IF tx off
                #ethtool -s $IF speed 40000

                # Enable n-tuple hw filters
                #ethtool -K $IF ntuple on

                ifconfig $IF up
                sleep 1
                bash ../scripts/set_irq_affinity $IF
        fi
done

HUGEPAGES_NUM=20480
HUGEPAGES_PATH=/dev/hugepages
sync && echo 3 > /proc/sys/vm/drop_caches
echo $HUGEPAGES_NUM > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
if [ `cat /proc/mounts | grep hugetlbfs | grep $HUGEPAGES_PATH | wc -l` -eq 0 ]; then
        if [ ! -d $HUGEPAGES_PATH ]; then
                mkdir $HUGEPAGES_PATH
        fi
        mount -t hugetlbfs nodev $HUGEPAGES_PATH
fi
HUGEPAGES_AVAIL_1=$(grep HugePages_Total /sys/devices/system/node/node0/meminfo | cut -d ':' -f 2|sed 's/ //g')
HUGEPAGES_AVAIL_2=$(grep HugePages_Total /sys/devices/system/node/node1/meminfo | cut -d ':' -f 2|sed 's/ //g')
HUGEPAGES_AVAIL=`expr $HUGEPAGES_AVAIL_1 + $HUGEPAGES_AVAIL_2`
if [ $HUGEPAGES_AVAIL -ne $HUGEPAGES_NUM ]; then
        printf "Warning: %s hugepages available, %s requested\n" "$HUGEPAGES_AVAIL" "$HUGEPAGES_NUM"
fi

commands:
=========
./zsend -c 0 -g 0 -l 60 -i zc:eth20@0
./zsend -c 1 -g 1 -l 60 -i zc:eth20@1
./zsend -c 2 -g 2 -l 60 -i zc:eth20@2
./zsend -c 3 -g 3 -l 60 -i zc:eth20@3
./zsend -c 4 -g 4 -l 60 -i zc:eth20@4
./zsend -c 5 -g 5 -l 60 -i zc:eth20@5
./zsend -c 6 -g 6 -l 60 -i zc:eth20@6
./zsend -c 7 -g 7 -l 60 -i zc:eth20@7
./zsend -c 8 -g 8 -l 60 -i zc:eth20@8
./zsend -c 9 -g 9 -l 60 -i zc:eth20@9
./zsend -c 10 -g 10 -l 60 -i zc:eth20@10
./zsend -c 11 -g 11 -l 60 -i zc:eth20@11
./zsend -c 12 -g 12 -l 60 -i zc:eth20@12
./zsend -c 13 -g 13 -l 60 -i zc:eth20@13
./zcount -c 14 -g 14 -i zc:eth21@0
./zcount -c 15 -g 15 -i zc:eth21@1
./zcount -c 16 -g 16 -i zc:eth21@2
./zcount -c 17 -g 17 -i zc:eth21@3
./zcount -c 18 -g 18 -i zc:eth21@4
./zcount -c 19 -g 19 -i zc:eth21@5
./zcount -c 20 -g 20 -i zc:eth21@6
./zcount -c 21 -g 21 -i zc:eth21@7
./zcount -c 22 -g 22 -i zc:eth21@8
./zcount -c 23 -g 23 -i zc:eth21@9
./zcount -c 24 -g 24 -i zc:eth21@10
./zcount -c 25 -g 25 -i zc:eth21@11
./zcount -c 26 -g 26 -i zc:eth21@12
./zcount -c 27 -g 27 -i zc:eth21@13
[

TOP
====
25679 root      20   0  164m 1848  948 S  9.6  0.0   0:22.42 zsend
25681 root      20   0  164m 1844  948 S  9.6  0.0   0:22.07 zsend
25683 root      20   0  164m 1844  948 S  9.6  0.0   0:21.91 zsend
25685 root      20   0  164m 1844  948 S  9.6  0.0   0:21.71 zsend
25689 root      20   0  164m 1844  948 S  9.6  0.0   0:21.48 zsend
25694 root      20   0  164m 1844  948 S  9.6  0.0   0:21.14 zsend
25673 root      20   0  164m 1844  948 S  9.3  0.0   0:22.62 zsend
25677 root      20   0  164m 1848  952 S  9.3  0.0   0:22.62 zsend
25686 root      20   0  164m 1844  948 S  9.3  0.0   0:21.59 zsend
25690 root      20   0  164m 1848  948 S  9.3  0.0   0:18.10 zsend
25692 root      20   0  164m 1848  948 S  9.3  0.0   0:21.26 zsend
25644 root      20   0  164m 1832  944 S  8.6  0.0   0:19.42 zcount
25656 root      20   0  164m 1836  944 S  8.6  0.0   0:19.88 zcount
25666 root      20   0  164m 1836  944 S  8.6  0.0   0:19.36 zcount
25668 root      20   0  164m 1836  944 S  8.6  0.0   0:20.11 zcount
25670 root      20   0  164m 1836  944 S  8.6  0.0   0:20.20 zcount
25646 root      20   0  164m 1836  944 S  8.3  0.0   0:19.45 zcount
25658 root      20   0  164m 1836  944 S  8.3  0.0   0:19.89 zcount
25660 root      20   0  164m 1836  944 S  8.3  0.0   0:19.26 zcount
25662 root      20   0  164m 1836  944 S  8.3  0.0   0:19.26 zcount
25637 root      20   0  164m 1824  936 S  8.0  0.0   0:19.34 zcount
25639 root      20   0  164m 1836  944 S  8.0  0.0   0:19.19 zcount
25640 root      20   0  164m 1836  944 S  8.0  0.0   0:18.78 zcount
25642 root      20   0  164m 1836  944 S  8.0  0.0   0:18.82 zcount
25664 root      20   0  164m 1836  944 S  8.0  0.0   0:19.37 zcount
25676 root      20   0  164m 1844  948 S  6.6  0.0   0:15.42 zsend
25697 root      20   0  164m 1844  948 S  6.3  0.0   0:18.08 zsend

**Comment by cardigliano** [comment]
Hi @szarea, it could be you reached the memory bandwidth limit, as you are moving 50 Gbit with many transactions (60-byte packets).
1. please provide the output of lstopo
2. please try running zsend with -l 1500 in order to see if you are able to move more data over the bus
3. please provide some output from zsend and zcount to check all the stats

**Comment by szarea** [comment]
Than you for your reply, please let me know if you need more info.

output from  "running zsend with -l 1500"
=============================
Scenario One: RSS is set to one for both ingress and egress interfaces
--------------
./zsend -c 1 -g 1 -l 1500 -i zc:eth23
=========================
Absolute Stats: 43'176'788 pkts - 65'801'424'912 bytes
Actual Stats: 24'390.24 pps - 0.30 Gbps [1524 bytes / 0.0 sec]
=========================

./zcount -c 14 -g 14 -i zc:eth22
=========================
Absolute Stats: 26'156'856 pkts (0 drops) - 39'863'048'544 bytes
Actual Stats: 0.00 pps (0.00 drops) - 0.00 Gbps
=========================

Scenario Two: RSS is set to two for both ingress and egress interfaces
--------------

./zsend -c 0 -g 0 -l 1500 -i zc:eth20@0
=========================
Absolute Stats: 67'232'847 pkts - 102'462'858'828 bytes
Actual Stats: 1'640'312.83 pps - 20.00 Gbps [2499884256 bytes / 1.0 sec]
=========================

./zsend -c 1 -g 1 -l 1500 -i zc:eth20@1
=========================
Absolute Stats: 64'018'687 pkts - 97'564'478'988 bytes
Actual Stats: 1'640'231.91 pps - 20.00 Gbps [2499768432 bytes / 1.0 sec]
=========================

./zcount -c 14 -g 14 -i zc:eth21@0
=========================
Absolute Stats: 26'247'616 pkts (6'666'096 drops) - 40'001'366'784 bytes
Actual Stats: 1'640'295.04 pps (0.00 drops) - 20.00 Gbps
=========================


./zcount -c 15 -g 15 -i zc:eth21@1
=========================
Absolute Stats: 26'246'728 pkts (0 drops) - 40'000'013'472 bytes
Actual Stats: 1'640'385.75 pps (0.00 drops) - 20.00 Gbps
=========================

lstopo output
==========
Machine (256GB total)
  NUMANode L#0 (P#0 128GB)
    Package L#0 + L3 L#0 (35MB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
      L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
      L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
      L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
      L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
      L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
      L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
      L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#7)
      L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8 + PU L#8 (P#8)
      L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9 + PU L#9 (P#9)
      L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10 + PU L#10 (P#10)
      L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11 + PU L#11 (P#11)
      L2 L#12 (256KB) + L1d L#12 (32KB) + L1i L#12 (32KB) + Core L#12 + PU L#12 (P#12)
      L2 L#13 (256KB) + L1d L#13 (32KB) + L1i L#13 (32KB) + Core L#13 + PU L#13 (P#13)
    HostBridge L#0
      PCIBridge
        PCI 8086:1583
          Net L#0 "eth20"
        PCI 8086:1583
          Net L#1 "eth23"
      PCIBridge
        PCI 8086:1521
          Net L#2 "eth0"
        PCI 8086:1521
          Net L#3 "eth1"
      PCIBridge
        PCI 8086:1521
          Net L#4 "eth2"
        PCI 8086:1521
          Net L#5 "eth3"
      PCI 8086:8d62
      PCIBridge
        PCIBridge
          PCI 1a03:2000
      PCI 8086:8d02
        Block L#6 "sda"
  NUMANode L#1 (P#1 128GB)
    Package L#1 + L3 L#1 (35MB)
      L2 L#14 (256KB) + L1d L#14 (32KB) + L1i L#14 (32KB) + Core L#14 + PU L#14 (P#14)
      L2 L#15 (256KB) + L1d L#15 (32KB) + L1i L#15 (32KB) + Core L#15 + PU L#15 (P#15)
      L2 L#16 (256KB) + L1d L#16 (32KB) + L1i L#16 (32KB) + Core L#16 + PU L#16 (P#16)
      L2 L#17 (256KB) + L1d L#17 (32KB) + L1i L#17 (32KB) + Core L#17 + PU L#17 (P#17)
      L2 L#18 (256KB) + L1d L#18 (32KB) + L1i L#18 (32KB) + Core L#18 + PU L#18 (P#18)
      L2 L#19 (256KB) + L1d L#19 (32KB) + L1i L#19 (32KB) + Core L#19 + PU L#19 (P#19)
      L2 L#20 (256KB) + L1d L#20 (32KB) + L1i L#20 (32KB) + Core L#20 + PU L#20 (P#20)
      L2 L#21 (256KB) + L1d L#21 (32KB) + L1i L#21 (32KB) + Core L#21 + PU L#21 (P#21)
      L2 L#22 (256KB) + L1d L#22 (32KB) + L1i L#22 (32KB) + Core L#22 + PU L#22 (P#22)
      L2 L#23 (256KB) + L1d L#23 (32KB) + L1i L#23 (32KB) + Core L#23 + PU L#23 (P#23)
      L2 L#24 (256KB) + L1d L#24 (32KB) + L1i L#24 (32KB) + Core L#24 + PU L#24 (P#24)
      L2 L#25 (256KB) + L1d L#25 (32KB) + L1i L#25 (32KB) + Core L#25 + PU L#25 (P#25)
      L2 L#26 (256KB) + L1d L#26 (32KB) + L1i L#26 (32KB) + Core L#26 + PU L#26 (P#26)
      L2 L#27 (256KB) + L1d L#27 (32KB) + L1i L#27 (32KB) + Core L#27 + PU L#27 (P#27)
    HostBridge L#6
      PCIBridge
        PCI 8086:1583
          Net L#7 "eth21"
        PCI 8086:1583
          Net L#8 "eth22"

**Comment by cardigliano** [comment]
> From this point it does not matter how I configure the RSS, I get the same result
> I even tried with RSS set to 14 for both eth20 & eth21 I got the same result.

I guess you ran 14 zsend, binding them to different cpu cores each, and it's like running 2 zsend. If this is the case it seems you hit an hw limit with the memory bandwidth or bus transactions. 
I see you are able to do 40Gbps with big packets: please note that with 60-byte packets you have much more (per-packet) overhead with respect to 1500-byte packets, at the same Gbps.
In addition to this, the small ring size of the XL710 (4096 slots) does not help. However that's not the main problem as you should've seen an improvement with RSS > 2.

**Comment by cardigliano** [comment]
Closing this, please reopen if necessary
