### ISSUE TITLE
Version: 2.0.26 - Intel® Network Adapter Driver for PCIe* 40 Gigabit Ethernet 

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#234]
what is the plan to upgrade ZC support for most recent release of i40e driver (Version: 2.0.26) ?
How much work will be for me do the upgrade with you help?
Thank you,
Steven

**Comment by cardigliano** [comment]
@szarea why do you need this version? Compilation issues or bug fixes?

**Comment by szarea** [comment]
Thank you for getting back to me.
Mainly for bug fixes, and firmware upgrades, intel tools such as proadmin (i.e. ./qcu64e).

**Comment by cardigliano** [comment]
Got it, there was no plan to upgrade it as it's working with all LTS kernels,
however we can upgrade it asap as it makes sense to move to a newer version
in this case.

**Comment by szarea** [comment]
again many thanks, let me know if I can be any help.

**Comment by szarea** [comment]
do you have any ET for it ?

**Comment by cardigliano** [comment]
Let us add this to the roadmap and see the ETA, I guess we can push this for early/mid July

**Comment by szarea** [comment]
thank you very much.

**Comment by mgregr** [comment]
+1 for this update

**Comment by cardigliano** [comment]
2.0.26 is on github, we are testing it

**Comment by cardigliano** [comment]
2.0.26 passed preliminary tests, please report any issue. Closing this issue.
