### ISSUE TITLE
pf-ring 6.6.0 performance issue 

### ISSUE THREAD

**Issue by sergico** [ntop/PF_RING#235]
I'm testing the PF_RING driver 6.6.0 on a system with:
OS: GNU/Linux Voyage 0.10.0 (Debian Jessy based distro) 
Kernel: 4.4.26 vanilla
NIC: Intel Corporation Device 15ac
NIC driver: ixgbe 5.0.4 compiled from sources 

I'm loading pf_ring with the following option: min_num_slots=65536

I'm running a 10Gb test vs such a system with a simple app that sends udp packets (1500 byte) 
Using tcpdump we capture on average ~6.4 milion packets 

I copied the pf_ring.ko driver and the libpcap disributed with the pf_ring .deb package 
Please note: I did compile the pf_ring driver on another host running the same kernel version (I do not have dev tools on the target system, and cannot install them)

Loaded the pf_ring module using the script load_driver.sh (dca is loaded, hugepages configured, etc)

Using the env variable LD_LIBRARY_PATH I'm running tcpdump linking the pf-ring aware libpcap (libpcap.so.1.7.4) Surprisingly I'm getting worst performances: ~5 milions packets

I verified that the correct library (pcap) is loaded checking the /proc/net/pf_ring filesystem (I see the newly created file <tcpdump_pid>-eth7.4 

Could you please help me understand what I'm doing wrong?

Best Regards
Sergio

**Comment by cardigliano** [comment]
Hi @sergico 
we need to check at what level packet loss occurs,
please run pfcount, generate the traffic, and post the output of:
- ethtool -S eth7
- cat /proc/net/pf_ring/*eth7*

**Comment by sergico** [comment]
Hi @cardigliano 

just run the following test:

- source host sends 10mil/1500B udp packets to target host where I installed the pf_ring driver
- target host is running  
`# ./pfcount -i eth7 -f udp and port 12345`

[ethtool.eth7.txt](https://github.com/ntop/PF_RING/files/1139370/ethtool.eth7.txt)

Cannot find the file: /proc/net/pf_ring/eth7 though

```
# cat /proc/net/pf_ring/dev/eth7/info 
Name:         eth7
Index:        16
Address:      0C:C4:7A:97:EC:A9
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    1
RX Queues:    1
```
Couple of questions:
- Do you also need the output of the pfcount tool? (shall I redirect to file the stdout/stderr?)
- is it correct that the libpcap distributed with pfring does not use libpfring.so?
```
# ldd ./libpcap.so.1.7.4
	linux-vdso.so.1 (0x00007fffdc799000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbb864c5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbb862bd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbb860b8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbb85d0d000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c5b221c000)
```
- This is the output of  ```cat /proc/net/pf_ring/27506-eth7.7 ```
```
Bound Device(s)    : eth7
Active             : 1
Breed              : Standard
Appl. Name         : pfcount
Socket Mode        : RX only
Capture Direction  : RX+TX
Sampling Rate      : 1
IP Defragment      : No
BPF Filtering      : Enabled
Sw Filt Hash Rules : 0
Sw Filt WC Rules   : 0
Hw Filt Rules      : 0
Sw Filt Hash Match : 0
Sw Filt Hash Miss  : 0
Poll Pkt Watermark : 128
Num Poll Calls     : 82959
Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
Slot Version       : 16 [6.6.0]
Min Num Slots      : 65558
Bucket Len         : 128
Slot Len           : 184 [bucket+header]
Tot Memory         : 12070912
Tot Packets        : 5921263
Tot Pkt Lost       : 0
Tot Insert         : 5921263
Tot Read           : 5921262
Insert Offset      : 3867664
Remove Offset      : 3867480
Num Free Slots     : 65557
Reflect: Fwd Ok    : 0
Reflect: Fwd Errors: 0
```
while pfcount is running but after the udp traffic has terminated
Hope this might help understanding what is not working/whether my setup is wrong

Thanks
Sergio

**Comment by cardigliano** [comment]
2017-07-11 17:29 GMT+02:00 Sergio Borghese <notifications@github.com>:

**Comment by cardigliano** [comment]
Hi Sergio
yes please redirect to file or just cut&paste a few lines from pfcount

Alfredo

2017-07-11 17:41 GMT+02:00 Alfredo Cardigliano <
alfredo.cardigliano@gmail.com>:

**Comment by sergico** [comment]
Hi Alfredo,

please find attached the pfcount and ethtool output:
[pfcount.out.txt](https://github.com/ntop/PF_RING/files/1139461/pfcount.out.txt)
[ethtool.eth7.txt](https://github.com/ntop/PF_RING/files/1139462/ethtool.eth7.txt)

```
cat /proc/net/pf_ring/27611-eth7.8 
Bound Device(s)    : eth7
Active             : 1
Breed              : Standard
Appl. Name         : pfcount
Socket Mode        : RX only
Capture Direction  : RX+TX
Sampling Rate      : 1
IP Defragment      : No
BPF Filtering      : Enabled
Sw Filt Hash Rules : 0
Sw Filt WC Rules   : 0
Hw Filt Rules      : 0
Sw Filt Hash Match : 0
Sw Filt Hash Miss  : 0
Poll Pkt Watermark : 128
Num Poll Calls     : 82487
Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
Slot Version       : 16 [6.6.0]
Min Num Slots      : 65558
Bucket Len         : 128
Slot Len           : 184 [bucket+header]
Tot Memory         : 12070912
Tot Packets        : 5926009
Tot Pkt Lost       : 0
Tot Insert         : 5926009
Tot Read           : 5926009
Insert Offset      : 4742896
Remove Offset      : 4742896
Num Free Slots     : 65558
Reflect: Fwd Ok    : 0
Reflect: Fwd Errors: 0
```

**Comment by cardigliano** [comment]
It seems there is no packet loss at pf_ring level:

> Tot Pkt Lost       : 0

However the card itself is missing something as you can see from ethtool:

> rx_missed_errors: 22637793

Please try enabling RSS to see if it improves.
