### ISSUE TITLE
pfring_open error: centos6.9

### ISSUE THREAD

**Issue by xswvfr** [ntop/PF_RING#236]
hi
used centos6.9 kernel 2.6.32-696.3.2.el6.x86_64 not working

 lsmod |grep pf_ring
pf_ring               691797  0 

cat /proc/net/pf_ring/info
PF_RING Version          : 6.0.3 ($Revision: 已导出 $)
Total rings              : 0

Standard (non DNA/ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

modinfo pf_ring
filename:       /lib/modules/2.6.32-696.3.2.el6.x86_64/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
description:    Packet capture acceleration and analysis
author:         Luca Deri <deri@ntop.org>
license:        GPL
srcversion:     B1E5D96084CEA8960B3D5FA
depends:        
vermagic:       2.6.32-696.3.2.el6.x86_64 SMP mod_unload modversions 
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           transparent_mode:(deprecated) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)

but kernel 2.6.32-696.1.1.el6.x86_64 . is working

**Comment by xswvfr** [comment]
error msg "
pfring_open error: No such device (pf_ring not loaded or perhaps you use quick mode and have already a socket bound to br0, eth0
2017-07-07 11:40:37,968 [ERROR] PF_RING initilization failed, exit from programm

**Comment by cardigliano** [comment]
please run pfcount -i eth0 and report the output

**Comment by xswvfr** [comment]
hi

`pfcount -i eth0
Using PF_RING v.6.0.3
Capturing from eth0 [mac: 84:2B:2B:0D:05:62][if_index: 2][speed: 1000Mb/s]
# Device RX channels: 8
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/15677-eth0.4
=========================
Absolute Stats: [1'153 pkts total][0 pkts dropped][0.0% dropped]
[1'153 pkts rcvd][195'018 bytes rcvd]
=========================

=========================
Absolute Stats: [2'559 pkts total][0 pkts dropped][0.0% dropped]
[2'559 pkts rcvd][427'520 bytes rcvd][2'558.71 pkt/sec][3.42 Mbit/sec]
=========================
Actual Stats: [1'406 pkts rcvd][1'000.11 ms][1'405.84 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [3'764 pkts total][0 pkts dropped][0.0% dropped]
[3'764 pkts rcvd][646'897 bytes rcvd][1'881.81 pkt/sec][2.59 Mbit/sec]
=========================
Actual Stats: [1'205 pkts rcvd][1'000.08 ms][1'204.90 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [5'278 pkts total][0 pkts dropped][0.0% dropped]
[5'278 pkts rcvd][950'858 bytes rcvd][1'759.17 pkt/sec][2.54 Mbit/sec]
=========================
Actual Stats: [1'514 pkts rcvd][1'000.07 ms][1'513.89 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [7'994 pkts total][0 pkts dropped][0.0% dropped]
[7'994 pkts rcvd][2'215'442 bytes rcvd][1'998.27 pkt/sec][4.43 Mbit/sec]
=========================
Actual Stats: [2'716 pkts rcvd][1'000.19 ms][2'715.48 pps][0.01 Gbps]
=========================

=========================
Absolute Stats: [9'550 pkts total][0 pkts dropped][0.0% dropped]
[9'550 pkts rcvd][2'642'431 bytes rcvd][1'909.79 pkt/sec][4.23 Mbit/sec]
=========================
Actual Stats: [1'556 pkts rcvd][1'000.08 ms][1'555.87 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [10'703 pkts total][0 pkts dropped][0.0% dropped]
[10'703 pkts rcvd][2'937'926 bytes rcvd][1'783.64 pkt/sec][3.92 Mbit/sec]
=========================
Actual Stats: [1'153 pkts rcvd][1'000.08 ms][1'152.90 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [12'095 pkts total][0 pkts dropped][0.0% dropped]
[12'095 pkts rcvd][3'306'299 bytes rcvd][1'727.68 pkt/sec][3.78 Mbit/sec]
=========================
Actual Stats: [1'392 pkts rcvd][1'000.09 ms][1'391.87 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [16'653 pkts total][0 pkts dropped][0.0% dropped]
[16'653 pkts rcvd][6'168'384 bytes rcvd][2'081.41 pkt/sec][6.17 Mbit/sec]
=========================
Actual Stats: [4'558 pkts rcvd][1'000.08 ms][4'557.63 pps][0.02 Gbps]
=========================

=========================
Absolute Stats: [18'120 pkts total][0 pkts dropped][0.0% dropped]
[18'120 pkts rcvd][6'635'406 bytes rcvd][2'013.13 pkt/sec][5.90 Mbit/sec]
=========================
Actual Stats: [1'467 pkts rcvd][1'000.09 ms][1'466.85 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [19'879 pkts total][0 pkts dropped][0.0% dropped]
[19'879 pkts rcvd][7'284'776 bytes rcvd][1'987.70 pkt/sec][5.83 Mbit/sec]
=========================
Actual Stats: [1'759 pkts rcvd][1'000.08 ms][1'758.84 pps][0.01 Gbps]
=========================

=========================
Absolute Stats: [22'249 pkts total][0 pkts dropped][0.0% dropped]
[22'249 pkts rcvd][8'446'207 bytes rcvd][2'022.43 pkt/sec][6.14 Mbit/sec]
=========================
Actual Stats: [2'370 pkts rcvd][1'000.09 ms][2'369.78 pps][0.01 Gbps]
=========================

=========================
Absolute Stats: [24'325 pkts total][0 pkts dropped][0.0% dropped]
[24'325 pkts rcvd][9'239'360 bytes rcvd][2'026.88 pkt/sec][6.16 Mbit/sec]
=========================
Actual Stats: [2'076 pkts rcvd][1'000.11 ms][2'075.75 pps][0.01 Gbps]
=========================

=========================
Absolute Stats: [26'259 pkts total][0 pkts dropped][0.0% dropped]
[26'259 pkts rcvd][10'013'186 bytes rcvd][2'019.71 pkt/sec][6.16 Mbit/sec]
=========================
Actual Stats: [1'934 pkts rcvd][1'000.13 ms][1'933.74 pps][0.01 Gbps]
=========================

=========================
Absolute Stats: [27'904 pkts total][0 pkts dropped][0.0% dropped]
[27'904 pkts rcvd][10'499'885 bytes rcvd][1'992.94 pkt/sec][6.00 Mbit/sec]
=========================
Actual Stats: [1'645 pkts rcvd][1'000.09 ms][1'644.84 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [29'695 pkts total][0 pkts dropped][0.0% dropped]
[29'695 pkts rcvd][11'087'421 bytes rcvd][1'979.46 pkt/sec][5.91 Mbit/sec]
=========================
Actual Stats: [1'791 pkts rcvd][1'000.08 ms][1'790.84 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [31'074 pkts total][0 pkts dropped][0.0% dropped]
[31'074 pkts rcvd][11'393'033 bytes rcvd][1'941.93 pkt/sec][5.70 Mbit/sec]
=========================
Actual Stats: [1'379 pkts rcvd][1'000.10 ms][1'378.86 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [32'383 pkts total][0 pkts dropped][0.0% dropped]
[32'383 pkts rcvd][11'600'501 bytes rcvd][1'904.69 pkt/sec][5.46 Mbit/sec]
=========================
Actual Stats: [1'309 pkts rcvd][1'000.08 ms][1'308.88 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [33'747 pkts total][0 pkts dropped][0.0% dropped]
[33'747 pkts rcvd][11'851'203 bytes rcvd][1'874.64 pkt/sec][5.27 Mbit/sec]
=========================
Actual Stats: [1'364 pkts rcvd][1'000.09 ms][1'363.87 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [34'806 pkts total][0 pkts dropped][0.0% dropped]
[34'806 pkts rcvd][12'048'513 bytes rcvd][1'831.71 pkt/sec][5.07 Mbit/sec]
=========================
Actual Stats: [1'059 pkts rcvd][1'000.07 ms][1'058.91 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [37'811 pkts total][0 pkts dropped][0.0% dropped]
[37'811 pkts rcvd][13'601'981 bytes rcvd][1'890.36 pkt/sec][5.44 Mbit/sec]
=========================
Actual Stats: [3'005 pkts rcvd][1'000.08 ms][3'004.75 pps][0.01 Gbps]
=========================`

**Comment by cardigliano** [comment]
@fyhqycom it seems pf_ring is loaded, what did you try to run? I can read "br0, eth0", could you send me the exact command?

**Comment by xswvfr** [comment]
hi
it's fastnetmon run 
https://github.com/pavel-odintsov/fastnetmon

thanks

**Comment by cardigliano** [comment]
Are you able to reproduce the issue with pfcount? (using the same interfaces)

**Comment by pavel-odintsov** [comment]
Hi, guys!

It's worth to mention that pf_Ring fails in this case before receiving any packets, here (inside pf_ring_main_loop): https://github.com/pavel-odintsov/fastnetmon/blob/master/src/pfring_plugin/pfring_collector.cpp#L289

**Comment by cardigliano** [comment]
Thank you @pavel-odintsov 
However I will wait for the pfcount command line, in order to check the exact input provided to pfring_open

**Comment by cardigliano** [comment]
©losed for inactivity, please reopen in case
