### ISSUE TITLE
The buffer before sending (receiving) is equal to the buffer after sending (receiving)

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#238]
```
threadN:
    pfring_zc_buffer_pool *buf_pool = pfring_zc_create_buffer_pool(zc_cluster, pool_len);
    pfring_zc_pkt_buff *buffer = pfring_zc_get_packet_handle_from_pool(buf_pool);
```

I try figure out why buffer before 
```

pfring_zc_pkt_buff *buffer_previous = buffer;

if (pfring_zc_recv_pkt(RSS_queue_RX[thread_id], &buffer, 1) > 0) {
	...
}

...

pfring_zc_pkt_buff *buffer_previous = buffer;

if ((rc = pfring_zc_send_pkt(RSS_queue_TX[thread_id], &buffer, 1)) < 0) {
   ...
}

```
is equal to the buffer after

```
if (buffer_previous == buffer) {
    syslog(LOG_CRIT, "WTF?");
}

```
Under what conditions is it possible?
What mistake could I have made that it happened?

I open 16 RSS queues for two ports
I think I allocate enough buffers for that queues

But when I create buffer pool it's possible that 

`pfring_zc_create_buffer_pool(zc_cluster, pool_len);`

return part the same buffers in other threads? If buffers in the cluster will not be enough?
Left less than pool_len.

I actively
get
`pfring_zc_get_packet_handle_from_pool`
and release
`pfring_zc_release_packet_handle_to_pool`

within one thread and also release buffer from different thread to buffer pool created in other thread
but I do not think that the error in this...

Any advice?

**Comment by cardigliano** [comment]
> Under what conditions is it possible?

It happens when recv or send is not successful.

> release buffer from different thread to buffer pool created in other thread

You should avoid using the same pool from multiple threads as pool's code is not thread safe (you need external locking in case, but I recommend you using different pools).

**Comment by andyarus** [comment]
What if

```
pfring_zc_pkt_buff *buffer_previous = buffer;
if (pfring_zc_recv_pkt(RSS_queue_RX[thread_id], &buffer, 1) > 0) {
    ...
    if (buffer_previous == buffer) {
        syslog(LOG_CRIT, "WTF?");
    }
   ...
}
```

```
pfring_zc_pkt_buff *buffer_previous = buffer;
if ((rc = pfring_zc_send_pkt(RSS_queue_TX[thread_id], &buffer, 1)) < 0) {
    ...
    if (buffer_previous == buffer) {
        syslog(LOG_CRIT, "WTF?");
    }
   ...
}
```

recv or send don't return error
and buffers equal anyway.

It's possible only if I add the same buffer in TX queue
i.e. send the same buffer repeatedly?
`if ((rc = pfring_zc_send_pkt(RSS_queue_TX[thread_id], &buffer, 1)) < 0) {`

> You should avoid using the same pool from multiple threads as pool's code is not thread safe (you need external locking in case, but I recommend you using different pools).
I use locks (pthread_mutex_t). I use own pool per thread, but now It turns out that packet can be processed in different thread.

Question about RSS queues.
It's ok that I use 16 RSS queues per interface?
```
RSS_queue_RX[thread_id] = pfring_zc_open_device(zc, interface_name, rx_only, 0);
RSS_queue_TX[thread_id] = pfring_zc_open_device(zc, interface_name, tx_only, 0);
```
and then recv and send from and to this queues without any locks. it's thread safe?

Just for now I run app and get rare error (several errors every few minutes) in some threads when try send
rc:-1
item->pkt->len:1418
errsv:0
strerror:Success
I run 16 RX threads and 16 TX threads for the same cores (1 RX and 1 TX per core: HyperThreading enabled).
And pfring_zc_stats() show that
for one thread (one direction) I get small growth drop packets after sending (11 for hour work)
for two threads (other direction) 
thread13: 85 pkts drop
thread14: 8 pkts drop
for all other threads I don't see drops.
But sometimes I see problem with equal beffore before recv or send and after

Obviously, I'm doing something wrong, but how do I detect a problem.

**Comment by andyarus** [comment]
Thanks for the help!
> pool's code is not thread safe

Exactly!

I use mutex only for
`pfring_zc_release_packet_handle_to_pool`
Buf not for
`pfring_zc_get_packet_handle_from_pool`

I add mutex and seems now all work well
