### ISSUE TITLE
pfring_zc_stats drops

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#239]
pfring_zc_stats show drops on device interface queue (RX and TX)
NIC 10 Gbps
Now traffic 3 Gbps (RX and TX approximately equal) and I see drops
Why it's can happen?
Too slowly I take packets from the RX queue?
I'm sending packets to the TX queue too fast?

pfring_zc_stats function is thread safe?
I can often call it and recv/send packets from/to queues for which I call it?

**Comment by andyarus** [comment]
Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection

Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz

**sudo cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor**
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance
performance

**dmidecode -t memory**
Size: 4096 MB
Type: DDR3
Speed: 1066 MHz
Rank: 1
Configured Clock Speed: 1066 MHz

**numastat -cm**

Per-node system memory usage (in MBs):
                 Node 0 Node 1 Total
                 ------ ------ -----
MemTotal           7977   8078 16056
MemFree             833    570  1403
MemUsed            7144   7508 14652
Active             1760   1496  3256
Inactive           1095    820  1915
Active(anon)        983    885  1868
Inactive(anon)      372    182   554
Active(file)        777    611  1388
Inactive(file)      723    639  1361
Unevictable           0      0     0
Mlocked               0      0     0
Dirty                25     66    90
Writeback             0      0     0
FilePages          1606   1498  3104
Mapped               28     16    44
AnonPages          1250    826  2077
Shmem               104    240   344
KernelStack           3      2     5
PageTables            7      5    12
NFS_Unstable          0      0     0
Bounce                0      0     0
WritebackTmp          0      0     0
Slab                107     78   185
SReclaimable         78     50   128
SUnreclaim           30     27    57
AnonHugePages         0      0     0
HugePages_Total    4096   4096  8192
HugePages_Free     3956      0  3956
HugePages_Surp        0      0     0


This is possible because the memory is too slow?

**Comment by andyarus** [comment]
![filter2_](https://user-images.githubusercontent.com/6764259/28414786-97b690be-6d66-11e7-9be2-dbc6501ae34f.png)

**Comment by andyarus** [comment]
To which NUMA NODE the card (eth6 eth7 eth8 eth9) is binded?
```
yaav@prefilter2:/src/DSF/build$ sudo cat /sys/bus/pci/devices/`sudo ethtool -i eth6 | grep bus-info | cut -d ' ' -f 2`/numa_node
-1
yaav@prefilter2:/src/DSF/build$ sudo cat /sys/bus/pci/devices/`sudo ethtool -i eth7 | grep bus-info | cut -d ' ' -f 2`/numa_node
-1
yaav@prefilter2:/src/DSF/build$ sudo cat /sys/bus/pci/devices/`sudo ethtool -i eth8 | grep bus-info | cut -d ' ' -f 2`/numa_node
-1
yaav@prefilter2:/src/DSF/build$ sudo cat /sys/bus/pci/devices/`sudo ethtool -i eth9 | grep bus-info | cut -d ' ' -f 2`/numa_node
-1
```

**Comment by cardigliano** [comment]
@andyarus what is the traffic rate you are able to handle with pfcount (RX) and pfsend (TX)? I need this to figure out whether the bottleneck is on the capture side or on the application side.
As of the numa topology, it seems everything is on the second CPU, however please provide the ascii output from lstopo which is more readable.

**Comment by andyarus** [comment]
```
Machine (16GB total)
  NUMANode L#0 (P#0 7977MB) + Socket L#0 + L3 L#0 (15MB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#12)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#1)
      PU L#3 (P#13)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#2)
      PU L#5 (P#14)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#3)
      PU L#7 (P#15)
    L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
      PU L#8 (P#4)
      PU L#9 (P#16)
    L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
      PU L#10 (P#5)
      PU L#11 (P#17)
  NUMANode L#1 (P#1 8078MB) + Socket L#1 + L3 L#1 (15MB)
    L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
      PU L#12 (P#6)
      PU L#13 (P#18)
    L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
      PU L#14 (P#7)
      PU L#15 (P#19)
    L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8
      PU L#16 (P#8)
      PU L#17 (P#20)
    L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9
      PU L#18 (P#9)
      PU L#19 (P#21)
    L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10
      PU L#20 (P#10)
      PU L#21 (P#22)
    L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11
      PU L#22 (P#11)
      PU L#23 (P#23)
  HostBridge L#0
    PCIBridge
      PCI 8086:1d6b
    PCIBridge
      PCI 8086:1521
        Net L#0 "eth0"
      PCI 8086:1521
        Net L#1 "eth1"
    PCIBridge
      PCI 102b:0532
    PCI 8086:1d02
      Block L#2 "sda"
  HostBridge L#4
    PCIBridge
      PCIBridge
        PCIBridge
          PCI 8086:10fb
            Net L#3 "eth6"
          PCI 8086:10fb
            Net L#4 "eth7"
        PCIBridge
          PCI 8086:10fb
            Net L#5 "eth8"
          PCI 8086:10fb
            Net L#6 "eth9"
```

> what is the traffic rate you are able to handle with pfcount (RX) and pfsend (TX)? I need this to figure out whether the bottleneck is on the capture side or on the application side.

It's production server and I can't make test on them right now.
I'll try to figure out how to do it and if I can, I provide the information you need

Can you please explain how drops increase?

```
pfring_zc_worker* pfring_zc_run_balancer	(
    pfring_zc_queue * 	in_queues[],
    pfring_zc_queue * 	out_queues[],
    u_int32_t 	num_in_queues,
    u_int32_t 	num_out_queues,
    pfring_zc_buffer_pool * 	working_set_pool,
    round_robin_bursts_policy,
    NULL,
    NULL,
    (void *) ((long) num_out_queues),
    0,
    int32_t 	core_id_affinity 
)	

pfring_zc_stat zc_stats;
pfring_zc_stats(in_queues[queue_index], &zc_stats);
```

Why **zc_stats.drop** value can increase?
Balancer too slowly takes out buffers from this queue than they come on the queue of the interface?

Or out_queues[queue_index] queue if full and when balancer try append new buffer to this queue, he see than  it full and make ++zc_stats.drop? Thus, I just need quickly take packets from the queue or increase the size of this queue and then there will not be drops?

**Comment by andyarus** [comment]
**ethtool -g eth6**
```
Ring parameters for eth6:
Pre-set maximums:
RX:		32768
RX Mini:	0
RX Jumbo:	0
TX:		32768
Current hardware settings:
RX:		32768
RX Mini:	0
RX Jumbo:	0
TX:		32768
```
```
queue_len = 32768;
out_queues[queue_index] = pfring_zc_create_queue(zc, queue_len);
```

**Comment by andyarus** [comment]
```
queue_len = 32768;
out_queues[queue_index] = pfring_zc_create_queue(zc, queue_len);
```

**Comment by cardigliano** [comment]
If zc_stats.drop increases on in_queues, that means the balancer cannot keep up with the ingress traffic. This can happen due to many factors, including:
1. the distribution function does too much work, thus it doesn't have enough cpu cycles to keep up with the packet rate
2. cpu affinity is wrong and traffic goes through the QPI (which adds latency, besides reducing the memory bandwidth)
