### ISSUE TITLE
Interrupts balancing in multi-NIC schema

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#24]
I try a zc cluster with tho network cards: one with ixgbe driver and one with e1000e. I receive a traffic from 10G interface and send them into 3 1G interfaces. I balance user load by cores, but system interrupts still in first core:

    %Cpu0  : 46,3 us,  0,3 sy,  0,0 ni,  0,0 id,  0,0 wa,  0,0 hi, 53,3 si,  0,0 st
    %Cpu1  : 66,4 us,  3,5 sy,  0,0 ni, 30,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
    %Cpu2  : 65,2 us,  5,1 sy,  0,0 ni, 29,7 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
    %Cpu3  : 65,8 us,  3,8 sy,  0,0 ni, 30,5 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st

Is a way to balance a system interrupts by cores too?

**Comment by cardigliano** [comment]
Please note ZC should not use IRQs, how did you open the device?
Anyway, you can balance interrupts via /proc or using PF_RING/drivers/*/intel/ixgbe/ixgbe-*/scripts/set_irq_affinity

**Comment by Skryabind** [comment]
I open one zc cluster, add all interfaces to it and create 8 queues - 4 for receiving and 4 for sending traffic. (4 - is the number of cores). 10G interface open rx_only, 1G interfaces opens tx_only.
I think this interrupts occurs when transfer packet from one nic to other.
I balance interrupts via /proc, thanks for it:

     %Cpu0  : 75,7 us,  1,4 sy,  0,0 ni,  1,4 id,  0,0 wa,  0,0 hi, 21,6 si,  0,0 st
     %Cpu1  : 74,0 us,  1,3 sy,  0,0 ni,  0,3 id,  0,0 wa,  0,0 hi, 24,3 si,  0,0 st
     %Cpu2  : 78,0 us,  1,3 sy,  0,0 ni,  0,3 id,  0,0 wa,  0,0 hi, 20,3 si,  0,0 st
     %Cpu3  : 75,0 us,  1,0 sy,  0,0 ni,  0,3 id,  0,0 wa,  0,0 hi, 23,7 si,  0,0 st
How do you think, is any way to decrease interrupts number in my case?

**Comment by cardigliano** [comment]
Hi
please check in /proc/interrupts which lines have growing numbers and let me know,
please also provide:
- interface names for the interfaces you are using,
- content of /proc/net/pf_ring/dev/ethX/info for the interfaces above,
- cat /proc/net/pfring/<sockets> while running the application.

Thank you
Alfredo

**Comment by Skryabind** [comment]
@cardigliano, please give me a time for tomorrow.

**Comment by Skryabind** [comment]
I decrease an interrupts, and now they are about 6-8%:

    %Cpu0  : 83,4 us,  1,0 sy,  0,0 ni,  8,1 id,  0,0 wa,  0,0 hi,  7,5 si,  0,0 st
    %Cpu1  : 82,4 us,  1,7 sy,  0,0 ni,  8,1 id,  0,0 wa,  0,0 hi,  7,8 si,  0,0 st
    %Cpu2  : 83,9 us,  1,0 sy,  0,0 ni,  8,0 id,  0,0 wa,  0,0 hi,  7,0 si,  0,0 st
    %Cpu3  : 87,3 us,  1,3 sy,  0,0 ni, 11,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st

My current /proc/interrupts:

    # cat /proc/interrupts | grep -e eth -e CPU
              CPU0       CPU1       CPU2       CPU3
    68:          1          0          0          0   PCI-MSI-edge      eth5
    69:         70          0      14741          0   PCI-MSI-edge      eth5-rx-0
    70:         43          0          0      10025   PCI-MSI-edge      eth5-rx-1
    71:       4281          0          0          0   PCI-MSI-edge      eth5-rx-2
    72:         22       9845          0          0   PCI-MSI-edge      eth5-rx-3
    73:         12          0       2982          0   PCI-MSI-edge      eth5-tx-0
    74:         29          0          0       3073   PCI-MSI-edge      eth5-tx-1
    75:       1431          0          0          0   PCI-MSI-edge      eth5-tx-2
    76:         16       5196          0          0   PCI-MSI-edge      eth5-tx-3
    77:       1234          0          0          0   PCI-MSI-edge      eth9
    79:       1264          0          0          0   PCI-MSI-edge      eth2-TxRx-0
    80:          2          0          0          0   PCI-MSI-edge      eth2
    81:       1242          0          0          0   PCI-MSI-edge      eth3-TxRx-0
    82:          0          0          0          0   PCI-MSI-edge      eth3
    83:   38803199          0          0          0   PCI-MSI-edge      eth6
    84:    9473940   28814175     207401          0   PCI-MSI-edge      eth11
    94:    9438578          0   27935883          0   PCI-MSI-edge      eth10

Interfaces: 
eth2 - 10G, receive traffic only
eth6, eth10, eth11 - 1G, send traffic only

    # cat /proc/net/pf_ring/dev/eth2/info
    Name:              eth2
    Index:             10
    Address:           00:E0:ED:50:2E:9C
    Polling Mode:      NAPI/ZC
    Type:              Ethernet
    Family:            Intel ixgbe 82599
    Max # TX Queues:   1
    # Used RX Queues:  1
    Num RX Slots:      32768
    Num TX Slots:      32768

    # cat /proc/net/pf_ring/dev/eth6/info
    Name:              eth6
    Index:             13
    Address:           00:1B:21:91:77:40
    Polling Mode:      NAPI/ZC
    Type:              Ethernet
    Family:            Intel e1000e
    Max # TX Queues:   1
    # Used RX Queues:  1
    Num RX Slots:      0
    Num TX Slots:      4096

    # cat /proc/net/pf_ring/dev/eth10/info
    Name:              eth10
    Index:             15
    Address:           00:1B:21:91:77:42
    Polling Mode:      NAPI/ZC
    Type:              Ethernet
    Family:            Intel e1000e
    Max # TX Queues:   1
    # Used RX Queues:  1
    Num RX Slots:      0
    Num TX Slots:      4096

    # cat /proc/net/pf_ring/dev/eth11/info
    Name:              eth11
    Index:             14
    Address:           00:1B:21:91:77:43
    Polling Mode:      NAPI/ZC
    Type:              Ethernet
    Family:            Intel e1000e
    Max # TX Queues:   1
    # Used RX Queues:  1
    Num RX Slots:      0
    Num TX Slots:      4096

Sockets:

    # cat  /proc/net/pf_ring/1212-eth2.5
    Bound Device(s)    :
    Active             : 1
    Breed              : ZC
    Appl. Name         : pfring-zc-1-zc:eth2
    Socket Mode        : RX only
    Capture Direction  : RX only
    Sampling Rate      : 1
    IP Defragment      : No
    BPF Filtering      : Disabled
    # Sw Filt. Rules   : 0
    # Hw Filt. Rules   : 0
    Poll Pkt Watermark : 128
    Num Poll Calls     : 0
    Channel Id         : 0
    Num RX Slots       : 32768
    Tot Memory         : 1048576 bytes

    # cat  /proc/net/pf_ring/1212-none.4
    Bound Device(s)    :
    Active             : 0
    Breed              : Standard
    Appl. Name         : pfring-zc-cluster-1
    Socket Mode        : RX+TX
    Capture Direction  : RX+TX
    Sampling Rate      : 1
    IP Defragment      : No
    BPF Filtering      : Disabled
    # Sw Filt. Rules   : 0
    # Hw Filt. Rules   : 0
    Poll Pkt Watermark : 128
    Num Poll Calls     : 0

    # cat  /proc/net/pf_ring/1212-eth6.6
    Bound Device(s)    :
    Active             : 1
    Breed              : ZC
    Appl. Name         : pfring-zc-1-zc:eth6
    Socket Mode        : TX only
    Channel Id         : 0
    Num TX Slots       : 4096
    Tot Memory         : 65536 bytes

    # cat  /proc/net/pf_ring/1212-eth6.7
    Bound Device(s)    : eth6
    Active             : 1
    Breed              : Standard
    Appl. Name         : <unknown>
    Socket Mode        : RX only
    Capture Direction  : RX+TX
    Sampling Rate      : 1
    IP Defragment      : No
    BPF Filtering      : Disabled
    # Sw Filt. Rules   : 0
    # Hw Filt. Rules   : 0
    Poll Pkt Watermark : 128
    Num Poll Calls     : 0
    Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
    Cluster Id         : 0
    Slot Version       : 16 [6.1.1]
    Min Num Slots      : 4098
    Bucket Len         : 1600
    Slot Len           : 1640 [bucket+header]
    Tot Memory         : 6729728
    Tot Packets        : 0
    Tot Pkt Lost       : 0

    # cat  /proc/net/pf_ring/1212-eth10.8
    Bound Device(s)    :
    Active             : 1
    Breed              : ZC
    Appl. Name         : pfring-zc-1-zc:eth10
    Socket Mode        : TX only
    Channel Id         : 0
    Num TX Slots       : 4096
    Tot Memory         : 65536 bytes

    # cat  /proc/net/pf_ring/1212-eth10.9
    Bound Device(s)    : eth10
    Active             : 1
    Breed              : Standard
    Appl. Name         : <unknown>
    Socket Mode        : RX only
    Capture Direction  : RX+TX
    Sampling Rate      : 1
    IP Defragment      : No
    BPF Filtering      : Disabled
    # Sw Filt. Rules   : 0
    # Hw Filt. Rules   : 0
    Poll Pkt Watermark : 128
    Num Poll Calls     : 0
    Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
    Cluster Id         : 0
    Slot Version       : 16 [6.1.1]
    Min Num Slots      : 4098
    Bucket Len         : 1600
    Slot Len           : 1640 [bucket+header]
    Tot Memory         : 6729728
    Tot Packets        : 1730
    Tot Pkt Lost       : 0
    Tot Insert         : 1730
    Tot Read           : 0
    Insert Offset      : 179920
    Remove Offset      : 0
    Num Free Slots     : 2368
    Reflect: Fwd Ok    : 0
    Reflect: Fwd Errors: 0

    # cat  /proc/net/pf_ring/1212-eth11.10
    Bound Device(s)    :
    Active             : 1
    Breed              : ZC
    Appl. Name         : pfring-zc-1-zc:eth11
    Socket Mode        : TX only
    Channel Id         : 0
    Num TX Slots       : 4096
    Tot Memory         : 65536 bytes

    # cat  /proc/net/pf_ring/1212-eth11.11
    Bound Device(s)    : eth11
    Active             : 1
    Breed              : Standard
    Appl. Name         : <unknown>
    Socket Mode        : RX only
    Capture Direction  : RX+TX
    Sampling Rate      : 1
    IP Defragment      : No
    BPF Filtering      : Disabled
    # Sw Filt. Rules   : 0
    # Hw Filt. Rules   : 0
    Poll Pkt Watermark : 128
    Num Poll Calls     : 0
    Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
    Cluster Id         : 0
    Slot Version       : 16 [6.1.1]
    Min Num Slots      : 4098
    Bucket Len         : 1600
    Slot Len           : 1640 [bucket+header]
    Tot Memory         : 6729728
    Tot Packets        : 1759
    Tot Pkt Lost       : 0
    Tot Insert         : 1759
    Tot Read           : 0
    Insert Offset      : 182936
    Remove Offset      : 0
    Num Free Slots     : 2339
    Reflect: Fwd Ok    : 0
    Reflect: Fwd Errors: 0

**Comment by Skryabind** [comment]
This is strange that in 1Gb interfaces opens 2 sockets - ZC and standard. Please wait, after some minutes I give you some interests information

**Comment by Skryabind** [comment]
So, I think that interrupts - is a feature (probably a bug) in e1000e driver.
I create a testbed: mirroring about 100Mbps into 1G port (e1000e driver) and run zcount.
First, I run it without zc:

    # ./zcount -i eth9 -c 1
    =========================
    Absolute Stats: 19'310 pkts (0 drops) - 12'396'418 bytes
    =========================
    
    =========================
    Absolute Stats: 38'949 pkts (0 drops) - 23'726'838 bytes
    Actual Stats: 19'637.27 pps (0.00 drops) - 0.09 Gbps
    =========================
    
    =========================
    Absolute Stats: 56'599 pkts (0 drops) - 34'457'941 bytes
    Actual Stats: 17'647.47 pps (0.00 drops) - 0.09 Gbps
    =========================
    
    ^CLeaving...

You can see correct values - 0.09Gbps
Interrupts is about 0.07%:
 
    %Cpu0  :  0,0 us,  0,0 sy,  0,0 ni, 99,3 id,  0,0 wa,  0,0 hi,  0,7 si,  0,0 st

Second, I run zcount with zc:
    # ./zcount -i zc:eth9 -c 1
    =========================
    Absolute Stats: 17'439 pkts (0 drops) - 1'533'264 bytes
    =========================
    
    =========================
    Absolute Stats: 35'186 pkts (0 drops) - 3'094'101 bytes
    Actual Stats: 17'742.75 pps (0.00 drops) - 0.01 Gbps
    =========================
    
    =========================
    Absolute Stats: 70'802 pkts (0 drops) - 6'225'928 bytes
    Actual Stats: 17'865.96 pps (0.00 drops) - 0.01 Gbps
    =========================
    
    ^CLeaving...

You can see that traffic is only 0.01Gps, and interrupts about 0.4%:

    %Cpu0  :  0,4 us,  0,4 sy,  0,0 ni, 98,9 id,  0,0 wa,  0,0 hi,  0,4 si,  0,0 st

Also, there are two sockets opened:

    # ls /proc/net/pf_ring/
    1457-eth9.45  1457-eth9.46  1457-none.44  dev  info  plugins_info  stats


Next, I mirror a traffic in 10G interface (ixgbe) in the same server.
When I run zcount, there are only one socket on interface:

    # ls /proc/net/pf_ring/
    1642-eth2.3  1642-none.2  dev  info  plugins_info  stats

And system interrupts are zero. (traffic about 6Gbps)

Also I show another server with igb driver, and in such server there one socket in interface too.

**Comment by cardigliano** [comment]
@Skryabind, it is expected for e1000e to open 2 sockets, one for rx and one for tx.
As of interrupts, I do not see the problem now, is it solved?

**Comment by Skryabind** [comment]
In zcount interface opens as rx_only, so second socket is excess.
Interrupts still exists when working with e1000e driver (and only with e1000e!). But they are not huge, so if you think that this is normal, lets close the issue. As of problem with reading traffic by zcount (in my previous message), I will open new issue.
