### ISSUE TITLE
Can filter packet where capture from zbalance_ipc like bpf

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#240]
I want to filter packet from zbalance_ipc, because zcount_ipc can not filter packets it must implement filter in    zbalance_ipc.
my filter is simple, it very like BPF, can I implement it in zcount_ipc

**Comment by cardigliano** [comment]
You can implement filtering either in zbalance_ipc (in the distribution function) or in zcount_ipc using latest dev code (please see https://github.com/ntop/PF_RING/blob/dev/userland/lib/pfring_zc.h#L286)

**Comment by gianogli** [comment]
@laoyang103 I think that my little patch could help you.
[zbalance_ipc_bpf_patch.txt](https://github.com/ntop/PF_RING/files/1162651/zbalance_ipc_bpf_patch.txt)
Take a look here: https://github.com/ntop/PF_RING/issues/196
Bye bye... ;-)

**Comment by laoyang103** [comment]
@cardigliano thanks for you reply, I will use pfring_zc_set_bpf_filter in zbalance_ipc. 
@gianogli thanks for your patch, but I think you'd better use pfring_zc_set_bpf_filter when init queues, not in distribution function, it will affects performance smaller.

**Comment by laoyang103** [comment]
@cardigliano I have use pfring_zc_set_bpf_filter in zfanout_ipc and zcount_ipc, but its all return -1.
zcount_ipc:
  zq = pfring_zc_ipc_attach_queue(cluster_id, queue_id, rx_only);
  printf("ffffffffffffffffff: %d", pfring_zc_set_bpf_filter(zq, "host 192.168.1.12"));
zfanout_ipc 
   for (i = 0; i < num_slaves; i++) {
    outzq[i] = pfring_zc_create_queue(zc, queue_len);
    printf("ffffffffffffffffff: %d", pfring_zc_set_bpf_filter(outzq[i], "host 192.168.1.12"));
  }

**Comment by laoyang103** [comment]
@cardigliano could you show a example whether in zbalance_ipc or zcount_ipc use pfring_zc_set_bpf_filter

**Comment by cardigliano** [comment]
Here you go, this is working for me. Are you using latest dev code?

https://github.com/ntop/PF_RING/commit/ccd5f58507f14dd556641d1fc072f896e5b132da#diff-ec66ebd58333f0d5b22aa5fdc9538894

**Comment by laoyang103** [comment]
OK, I have try it and work fine
