### ISSUE TITLE
yum install pfring fails.

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/PF_RING#241]
Dear:
Since the update today I am experiencing problems with the pf_ring module perform the suggested steps but I continue with problems.

Ã¢ pf_ring.service - Start/stop pfring service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since vie 2017-07-21 15:00:40 -05; 4s ago
  Process: 13508 ExecStart=/etc/init.d/pf_ring start (code=exited, status=99)

jul 21 15:00:40 server systemd[1]: Starting Start/stop pfring service...
jul 21 15:00:40 server pf_ring[13508]: Starting PF_RING module: PF_RING already loaded. Exiting[FALLÃ]
jul 21 15:00:40 server systemd[1]: pf_ring.service: control process exited, code=exited status=99
jul 21 15:00:40 server systemd[1]: Failed to start Start/stop pfring service.
jul 21 15:00:40 server systemd[1]: Unit pf_ring.service entered failed state.
jul 21 15:00:40 server systemd[1]: pf_ring.service failed.

And at the start of the kernel:
[   11.813709] pf_ring: loading out-of-tree module taints kernel.
[   11.814120] pf_ring: module verification failed: signature and/or required key missing - tainting kernel
[   11.815078] [PF_RING] Welcome to PF_RING 6.6.0 ($Revision: 6.6.0-stable:e76633df3f18028e81acb5bdf0db69c189359ef7$)
(C) 2004-16 ntop.org
[   11.815103] [PF_RING] registered /proc/net/pf_ring/
[   11.815106] NET: Registered protocol family 27
[   11.815146] [PF_RING] Min # ring slots 4096
[   11.815149] [PF_RING] Slot version     16
[   11.815151] [PF_RING] Capture TX       Yes [RX+TX]
[   11.815153] [PF_RING] IP Defragment    No
[   11.815155] [PF_RING] Initialized correctly

uname -a:
Linux server 3.10.0-514.26.1.el7.x86_64 #1 SMP Thu Jun 29 16:05:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Any idea how I can solve this problem?
Attentive to comments.

Greetings.

**Comment by cardigliano** [comment]
> pf_ring.service - Start/stop pfring service
> Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled; vendor preset: disabled)
> Active: failed (Result: exit-code) since vie 2017-07-21 15:00:40 -05; 4s ago
> Process: 13508 ExecStart=/etc/init.d/pf_ring start (code=exited, status=99)
> 
> jul 21 15:00:40 server systemd[1]: Starting Start/stop pfring service...
> jul 21 15:00:40 server pf_ring[13508]: Starting PF_RING module: PF_RING already loaded. Exiting[FALLÃ]
> jul 21 15:00:40 server systemd[1]: pf_ring.service: control process exited, code=exited status=99
> jul 21 15:00:40 server systemd[1]: Failed to start Start/stop pfring service.
> jul 21 15:00:40 server systemd[1]: Unit pf_ring.service entered failed state.
> jul 21 15:00:40 server systemd[1]: pf_ring.service failed.

Could you provide the commands you ran? I tried to reproduce it using latest stable on Centos 7 and I do not get the same trace..

**Comment by cfrancis2b** [comment]
Cardigliano:

Solvent the problem. Uninstall pfring restart the machine and reinstall.
At that moment he got up without any problems.

But now every time ntopng is updated the error occurs, only re-performing the procedure described above installs the package.

Greetings.

**Comment by cardigliano** [comment]
We made some change to the package, please reopen if you reproduce it again on the next update.

**Comment by cfrancis2b** [comment]
So far only works if I uninstall the package, reboot the server and install.
With:
Centos 7
pfring 6.7.0
ntopng 3.1.170913-3220

The same error was presented in a Fedora 26 but here if I could uninstall the pfring of the module with "modprobe -r", after that I installed the new version.

**Comment by 001101** [comment]
same here

**Comment by jmcastellote** [comment]
I think I have the same issue on Fedora 27.

After installing ntopng (`dnf install ntopng`) and its dependencies (I can see pfring, pfring-dkms, dkms...), I see that service start has failed (on the install output).

Then when checking the service status or trying to start it with systemd, I get:

```
-- Subject: Unit pf_ring.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit pf_ring.service has begun starting up.
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Starting PF_RING module: modprobe: FATAL: Module pf_ring not found in directory /lib/modules/4.14.3-300.fc27.x86_
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Uninstalling old pfring version
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Error! The module pfring 7.0.0 is not currently installed.
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: This module is not currently ACTIVE for kernel 4.14.3-300.fc27.x86_64 (x86_64).
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Error! There is no instance of pfring 7.0.0
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: for kernel 4.14.3-300.fc27.x86_64 (x86_64) located in the DKMS tree.
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Compiling new pfring driver
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Error! echo
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Your kernel headers for kernel 4.14.3-300.fc27.x86_64 cannot be found at
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: /lib/modules/4.14.3-300.fc27.x86_64/build or /lib/modules/4.14.3-300.fc27.x86_64/source.
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Installing new pfring driver
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Error! echo
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Your kernel headers for kernel 4.14.3-300.fc27.x86_64 cannot be found at
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: /lib/modules/4.14.3-300.fc27.x86_64/build or /lib/modules/4.14.3-300.fc27.x86_64/source.
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: modprobe: FATAL: Module pf_ring not found in directory /lib/modules/4.14.3-300.fc27.x86_64
dic 13 17:01:27 iraklis.nubelibre.com pf_ring[11801]: Unable to load PF_RING. Exiting[FALLÓ]
dic 13 17:01:27 iraklis.nubelibre.com systemd[1]: pf_ring.service: Control process exited, code=exited status=99
dic 13 17:01:27 iraklis.nubelibre.com systemd[1]: Failed to start Start/stop pfring service.
-- Subject: Unit pf_ring.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit pf_ring.service has failed.
-- 
-- The result is failed.
```

I've tried mentioned workaround by uninstalling, rebooting and installing, but no luck.

**Comment by jmcastellote** [comment]
Hi again,

Seems it is fixed now on my side.

On my case, kernel-devel was missing so the new pfring module couldn't get loaded (I probably should have realized about this before).
Installing it fixes the issue. 

Should kernel-devel be a dependency of ntopng?

Now, for fedora 27, ntopng will then complaint about many missing libraries. They are all already there under /usr/lib64 but with newer name.

So after creating softlinks for all the libraries claimed by ntopng, it now runs like a charm.
i.e.: `ln -s /usr/lib64/libhiredis.so.0.13 /usr/lib64/libhiredis.so.0.12`

Btw, NTOPNG is a really awesome tool!!

**Comment by cardigliano** [comment]
We reworked the packages including the dependency tree, please let us know if you still have issues

**Comment by jmcastellote** [comment]
Many thanks @cardigliano. It worked for me first time right after retrying.

**Comment by cardigliano** [comment]
Thank you. Please reopen in case.

**Comment by 001101** [comment]
After I removed the kernel module by hand and reinstalling the new version it works on CentOS 7, thanks!
