### ISSUE TITLE
zbalance_ipc option to drop privileges documented but not implemented

### ISSUE THREAD

**Issue by desbma** [ntop/PF_RING#247]
Somewhat related to #245: `zbalance_ipc` and `zbalance_DC_ipc` both [document a `-D <username>    Drop privileges` command line option](https://github.com/ntop/PF_RING/blob/b6f37779d568890abc1815838e5434e850e8593e/userland/examples_zc/zbalance_ipc.c#L374), however that option is not handled in the code.

**Comment by cardigliano** [comment]
Fixed with cdec0f4dec066d6b279487671ef29874072ae395

**Comment by desbma** [comment]
Thanks
