### ISSUE TITLE
/etc/init.d/cluster does not parse the zbalance_ipc pid file

### ISSUE THREAD

**Issue by bherrin2** [ntop/PF_RING#250]
the included cluster script found in package/etc/init.d/cluster wants to parse /etc/cluster/cluster-##.conf and looks for -P=/path/to/pidfile.pid this does not work as zbalance_ipc will not parse the parameter in this format. Rather zbalance_ipc wants the format -P /path/to/pidfile.pid

I was able to work around this by modifying these lines:
PID_FILE=$(cat /etc/cluster/cluster-${CLUSTER_ID}.conf | grep '\-P='|cut -d '=' -f 2)
to 
PID_FILE=$(cat /etc/cluster/cluster-${CLUSTER_ID}.conf | grep '\-P\ '|cut -d ' ' -f 2)

and placing the pid param at the begining of the .conf

**Comment by bherrin2** [comment]
also had to modify:
$CLUSTER_MASTER_BINARY /etc/cluster/cluster-${CLUSTER_ID}.conf >> /var/log/cluster/cluster-${CLUSTER_ID}.log 2>&1 &
to
$CLUSTER_MASTER_BINARY $( cat /etc/cluster/cluster-${CLUSTER_ID}.conf) >> /var/log/cluster/cluster-${CLUSTER_ID}.log 2>&1 &

**Comment by cardigliano** [comment]
@bherrin2 actually zbalance_ipc is supposed to use '=' as you can see at https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zutils.c#L326
Did you try using '=' to assign option values in the configuration file?

**Comment by bherrin2** [comment]
yes, the problem is that zbalance_ipc when run from the cli will not parse the -P=
so this:
zbalance_ipc -i zc:enp5s0f0 -c 99 -n 5 -m 1 -g 0 -d -P=/run/pf_ring.pid
will not create the pid file, but this
zbalance_ipc -i zc:enp5s0f0 -c 99 -n 5 -m 1 -g 0 -d -P /run/pf_ring.pid
will create the pid file

**Comment by cardigliano** [comment]
@bherrin2 not sure I got the problem sorry, when you use /etc/init.d/cluster zbalance_ipc reads a configuration file, not command line

**Comment by bherrin2** [comment]
@cardigliano I could not find any documentation on the config file format, but the script itself is just executing the cli command and appending the content of /etc/cluster/cluster-##.conf

In my case cluster-99.conf contains the cli paramters:
root@r610:/run# cat /etc/cluster/cluster-99.conf
-P /run/zbalance99.pid -i zc:enp5s0f0 -c 99 -n 5 -m 1 -g 0 -d

**Comment by cardigliano** [comment]
Please use something like this:

```
# cat /etc/cluster/cluster-99.conf
-P=/run/zbalance99.pid
-i=zc:enp5s0f0
-c=99
-n=5
-m=1
-g=0
-d
```

**Comment by bherrin2** [comment]
OK will try that, some documentation on the config file syntax would be nice for us non developers :)

**Comment by cardigliano** [comment]
Sure sorry, that script is usually used by our nBox gui, that generates the configuration file, we will add some documentation!

**Comment by bherrin2** [comment]
using the above format for cluster-99.conf and reverting to the original cluster script DOES work, I had an extra space after an '='

Thank you for your assistance @cardigliano
