### ISSUE TITLE
pfring_is_pkt_available issue

### ISSUE THREAD

**Issue by rajeshkalluri009** [ntop/PF_RING#251]
I have written an application to capture packets on ubuntu 14.04 and able to successfully capture all packets receiving on eth0. 
Now, i installed ubuntu mint on raspberry pi3 board and installed pf_ring from git. I followed same instructions as i did on a desktop.
But, at this api "pfring_is_pkt_available" always it is showing no packets available. I cross checked with wireshark, i have sufficient incoming data on eth0. 
Have i did any installation mistakes/ any other things i need to do when i am running an application on raspberry pi3 board and operating system ubuntu mint.

Please some body help in this regard.

Thanks ...

**Comment by cardigliano** [comment]
@rajeshkalluri009, Ubuntu mint on raspberry pi3 is untested sorry, we will try to run some test asap

**Comment by rajeshkalluri009** [comment]
@cardigliano Thanks for reply, actually it is ubuntu mate not ubuntu mint ... sorry for typo ... 

what operating system you recommend for pi3 to use pf_ring, please suggest.

**Comment by cardigliano** [comment]
We use it on raspbian (kernel 4.9.35-v7+) and it seems to work smoothly.

**Comment by rajeshkalluri009** [comment]
[pf_ring_queries.pdf](https://github.com/ntop/PF_RING/files/1284528/pf_ring_queries.pdf)
@cardigliano I installed raspbian operating system on pi3 board, but problem remain same. Attaching detailed log here for reference. I could capture out going packets but not incoming packets.

Please suggest ...

**Comment by cardigliano** [comment]
@rajeshkalluri009 we pushed a patch to fix this, please update to latest code and let us know if it's working for you.

**Comment by rajeshkalluri009** [comment]
@cardigliano Thanks, it's working. Will update if any other issues in capturing packets.
