### ISSUE TITLE
pfring_zc_stats.drop reports non-zero for first RSS rx queue only

### ISSUE THREAD

**Issue by mattipee** [ntop/PF_RING#253]
Evaluating PFRING ZC 6.6.0, I have 4 queues configured and if I exceed the rate at which a capture thread can receive packets from any one of the queues, the drop stat is only non-zero for the first queue (eg zc:em1@0), regardless the queue on which the packet should have been received. The total number of packets reported dropped appears to be correct (ie same as ifconfig/ethtool).

Is this a bug, or can this level of detail simply not be obtained from the driver?

**Comment by cardigliano** [comment]
@mattipee there is a similar limitation on some card, as some hw counter is per interface and not per queue. What is the card model you are using?

**Comment by mattipee** [comment]
@cardigliano Currently Intel X710, yet to test X520.

**Comment by cardigliano** [comment]
X710 has per-port drop counters, that's why you see all drops on queue 0

**Comment by mattipee** [comment]
Thank you for confirming that. Can you comment on the X520?

**Comment by cardigliano** [comment]
X520 has counters per queue

**Comment by mattipee** [comment]
Thanks.
