### ISSUE TITLE
PF_RING zc send packet not equals recv packets

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#255]
I use PF_RING-6.4.1 
both send and recv NIC is:

> root@localhost:/usr/local/PF_RING-6.4.1/userland/tcpdump# ethtool -i p6p1
driver: e1000e
version: 3.2.7.1-NAPI
firmware-version: 2.1-3
bus-info: 0000:09:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

the send and recv command is 

> zsend -i zc:p6p1 -r 0.5 -n 5000000 -c 22 -f 30/1467105919
> zcount -i zc:p6p1 -c 33

the send result is:

> =========================
Absolute Stats: 5'000'000 pkts - 1'155'564'164 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 0.0 sec]
=========================

the recv result is:

> =========================
Absolute Stats: 4'981'054 pkts (0 drops) - 1'131'235'600 bytes
Actual Stats: 0.00 pps (0.00 drops) - 0.00 Gbps
=========================

**Comment by cardigliano** [comment]
@laoyang103 could you try without -f?

**Comment by laoyang103** [comment]
@cardigliano 

send:
> =========================
Absolute Stats: 5'000'000 pkts - 420'000'000 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 0.0 sec]
=========================

recv:
> =========================
Absolute Stats: [channel=0][4977372 pkts rcvd][0 pkts dropped]
Total Pkts=4977372/Dropped=0.0 %
4977372 pkts - 418099248 bytes [241117.0 pkt/sec - 162.03 Mbit/sec]
=========================
Actual Stats: [channel=0][0 pkts][641.2 ms][0.0 pkt/sec]
=========================
Aggregate stats (all channels): [0.0 pkt/sec][162.03 Mbit/sec][0 pkts dropped]
=========================

**Comment by cardigliano** [comment]
@laoyang103 please describe the testbed, are you cross connecting two ports directly on two machines?
I see the same interface name in pfsend and pfcount.
Btw, please move to latest stable if possible (6.6)

**Comment by laoyang103** [comment]
@cardigliano Yes, I use two machines, the NIC in two machines have the same name p6p1, I will test the laset version

I have reboot two machines and all is OK, but i also want to know why.
Is it because boot too long time?

send NIC:

>=========================
Absolute Stats: 5'000'000 pkts - 1'155'564'164 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 0.0 sec]
=========================
root@PTCS-OS:~# ifconfig p6p1
p6p1      Link encap:Ethernet  HWaddr 14:dd:a9:4d:d3:02  
          inet6 addr: fe80::16dd:a9ff:fe4d:d302/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5000006 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1055562968 (1.0 GB)
          Interrupt:18 Memory:dc500000-dc520000 

recv NIC:

> =========================
Absolute Stats: 5'000'000 pkts (0 drops) - 1'135'564'164 bytes
Actual Stats: 0.00 pps (0.00 drops) - 0.00 Gbps
=========================
root@localhost:~# ifconfig p6p1
p6p1      Link encap:Ethernet  HWaddr 38:2c:4a:c7:d2:b4  
          inet6 addr: fe80::3a2c:4aff:fec7:d2b4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5000000 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1055551432 (1.0 GB)  TX bytes:680 (680.0 B)
          Interrupt:17 Memory:fb600000-fb620000

**Comment by laoyang103** [comment]
@cardigliano 
By the way, I only use pf_ring not zc, get the same result.
ifconfig result is right, but applaction miss a little packets.
I have load the "drivers/intel/igb/igb-5.3.3.5-zc/" driver on recv machine.
I try not use pf_ring also miss a little packets, I feel pf_ring doesn't work

driver use when recv packets
> root@localhost:/opt/PF_RING-6.6.0/drivers/intel/igb/igb-5.3.3.5-zc/src# lsmod | grep igb
igb                   200704  0 
ptp                    20480  1 igb
root@localhost:/opt/PF_RING-6.6.0/drivers/intel/igb/igb-5.3.3.5-zc/src# lsmod | grep pf
pf_ring              1236992  4 

send NIC:

> [root@localhost ~]# ethtool -i enp4s0
driver: e1000e
version: 3.2.6-k
firmware-version: 2.1-3
expansion-rom-version: 
bus-info: 0000:04:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

recv NIC

> root@localhost:/opt/PF_RING-6.6.0/drivers/intel/igb/igb-5.3.3.5-zc/src# ethtool -i eth3
driver: igb
version: 5.3.3.5
firmware-version: 1.59, 0x800008f8, 1.791.0
bus-info: 0000:0a:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

pf_ring:

> root@localhost:/opt/PF_RING-6.6.0/drivers/intel/igb/igb-5.3.3.5-zc/src# cat /proc/net/pf_ring/info 
PF_RING Version          : 6.6.0 (unknown)
Total rings              : 0
Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

eth3:

> root@localhost:/opt/PF_RING-6.6.0/drivers/intel/igb/igb-5.3.3.5-zc/src# cat /proc/net/pf_ring/dev/eth3/info 
Name:         eth3
Index:        8
Address:      2C:53:4A:00:26:27
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel igb 82580/i350 HW TS
TX Queues:    1
RX Queues:    1
Num RX Slots: 4096
Num TX Slots: 4096

send command

> [root@localhost ~]# tcpreplay -i enp4s0 --mbps=50 /root/data.pcap 
Actual: 267718 packets (98432555 bytes) sent in 15.74 seconds
Rated: 6249999.5 Bps, 49.99 Mbps, 16998.82 pps
Flows: 21103 flows, 1339.94 fps, 267717 flow packets, 1 non-flow
Statistics for network device: enp4s0
	Successful packets:        267718
	Failed packets:            0
	Truncated packets:         0
	Retried packets (ENOBUFS): 0
	Retried packets (EAGAIN):  0

recv stat
> =========================
Absolute Stats: [267'711 pkts total][0 pkts dropped][0.0% dropped]
[267'711 pkts rcvd][104'857'213 bytes rcvd][10'938.69 pkt/sec][34.28 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][472.05 ms][0.00 pps][0.00 Gbps]
=========================

**Comment by cardigliano** [comment]
Please use ZC for your tests, as with standard drivers you should look in different places for packet loss (card, kernel..)
Please also avoid using a pcap with mixed traffic, please generate synthetic traffic with pfsend.

**Comment by laoyang103** [comment]
@cardigliano 
use pfsend send 1000000 packets with a pacp file
>root@ubuntu:~# tcpdump -i p5p1 -w a.pcap -B 655360 -s 10000
tcpdump: WARNING: p5p1: no IPv4 address assigned
tcpdump: listening on p5p1, link-type EN10MB (Ethernet), capture size 10000 bytes
^C999724 packets captured
999724 packets received by filter
0 packets dropped by kernel

I have look card with ifconfig, it has no packet lost. 
I use tcpdump know kernel has no packet lost. 
how can I look packet lost and any other?

I have try use pfsend generate synthetic traffic, no packet lost. 
But I want to know why have packet lost with a pcap?

**Comment by cardigliano** [comment]
Are you able to check the delta between sent and received traffic, to see which packets are getting lost, in case they are special packets (e.g. bigger than mtu)?

**Comment by laoyang103** [comment]
yes I have diff send and recv packets, it seem the lost are the same packets in every test, its length is less than mtu.
I copy the recvived packets to send, also have a little lost.
if packets length more than mtu ifconfig will show the lost, but ifconfig show packets is equals send packets in every test

**Comment by laoyang103** [comment]
@cardigliano

I also test Ubuntu 14.04.3 without PF_RING, the result is same to use it, I feel PF_RING doesn't.work.
I can give you ssh both send and recv machine

**Comment by cardigliano** [comment]
@laoyang103 could you provide the "diff" packets?

**Comment by laoyang103** [comment]
@cardigliano 

mybe my lost, I only insert pf_ring.ko use standard PF_RING.
Dose I have to run drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/load_driver.sh to use standard PF_RING?

**Comment by cardigliano** [comment]
@laoyang103 to capture in standard mode you can use both vanilla drivers and our drivers (opening the interface without the "zc:" prefix)

**Comment by laoyang103** [comment]
@cardigliano 
But, I use PF_RING NIC drivers(e1000e) has Vary with not use.
when use has no packet lost, if not send:1000000 recv: 999530

**Comment by cardigliano** [comment]
Please keep using our drivers then, we do not have control over the vanilla drivers, it could be they are old or not optimised.

**Comment by laoyang103** [comment]
@cardigliano 
OK, thanks a lot !!!

**Comment by laoyang103** [comment]
@cardigliano 
Sorry, I just use drivers/intel/igb driver test, also have packet lost.
open #255

**Comment by laoyang103** [comment]
opened #255
