### ISSUE TITLE
update libpcap to the latest version

### ISSUE THREAD

**Issue by tianchao-haohan** [ntop/PF_RING#256]
There exists memory leak in libpcap-1.7.4 and the memory leak has been fixed in the latest version. Is that possible to update the customized libpcap to the latest version?

**Comment by cardigliano** [comment]
@tianchao-haohan we will upgrade both libpcap and tcpdump asap, thank you for reporting

**Comment by cardigliano** [comment]
https://github.com/ntop/PF_RING/commit/b726ec3fd3ec0259b746a7fab20d69d495085b29

**Comment by lucaderi** [comment]
@cardigliano Please also update tcpdump and not just libpcap

**Comment by cardigliano** [comment]
In progress.. :-)

**Comment by cardigliano** [comment]
https://github.com/ntop/PF_RING/commit/96f5f0e517f9239efbee52c3b1dd320a6d9e9d07
