### ISSUE TITLE
i40e: ethtool command failed

### ISSUE THREAD

**Issue by yuyi2017yuyi** [ntop/PF_RING#259]
I want to set the flow by using eththool command,for example:
1,ethtool -N ens2f1 flow-type tcp4 src-ip  192.168.1.212 m 0.0.255.255  dst-ip 0.0.0.0 m 0.0.255.255 action 1
2,ethtool -N ens2f1 flow-type tcp4 src-ip  0.0.0.0 m 0.0.255.255  dst-ip 192.168.1.212 m 0.0.255.255 action 1
the result is :
Total 2 rules
Filter: 7422
	Rule Type: TCP over IPv4
	Src IP addr: 0.0.0.0 mask: 255.255.255.255
	Dest IP addr: 192.168.1.212 mask: 255.255.255.255
	TOS: 0x0 mask: 0xff
	Src port: 0 mask: 0xffff
	Dest port: 0 mask: 0xffff
	Action: Direct to queue 1

Filter: 7423
	Rule Type: TCP over IPv4
	Src IP addr: 192.168.1.212 mask: 255.255.255.255
	Dest IP addr: 0.0.0.0 mask: 255.255.255.255
	TOS: 0x0 mask: 0xff
	Src port: 0 mask: 0xffff
	Dest port: 0 mask: 0xffff
	Action: Direct to queue 1

**# after I update i40e driver for pfring_zc,the second command is failed**
ethtool -N ens2f1 flow-type tcp4 src-ip  0.0.0.0 m 0.0.255.255  dst-ip 192.168.1.212 m 0.0.255.255 action 1
**rmgr: Cannot insert RX class rule: Operation not supported**

My environment is the following:

1. PF_Ring ZC 6.5.0 
2. Linux kernel 3.10.0-327.el7.x86_64 (from CentOS Linux release 7.2.1511 (Core) )
3. 4 x 10GbE Intel XL710 NICs

how to solve this problem? Thank you !

**Comment by cardigliano** [comment]
@yuyi2017yuyi please double check that the same behaviour occurs with latest code from the dev branch (6.7) and i40e-zc 2.x. Thank you.

**Comment by yuyi2017yuyi** [comment]
@cardigliano ,Thank your reply.I had try to compile the latest code from the dev branch (6.7) and i40e-2.0.26-zc,but the ethtool command failed again as before 
**rmgr: Cannot insert RX class rule: Operation not supported**
what can I do for this ? Thank you .

**Comment by acloudiator** [comment]
Got the same problem! Did anyone found any fix for it? Thanks!

**Comment by cardigliano** [comment]
Using the current i40e-2.3.6-zc driver distributed with pf_ring I am able to add rules, however some of the parameters like "m 0.0.255.255" seems to be not supported by the Intel driver. This is working for me for instance:
ethtool -N $IF flow-type tcp4 src-ip 192.168.1.212 action 0
Please remember to enable ntuple support with:
ethtool -K $IF ntuple on
Please confirm this is working for you.

**Comment by yarick** [comment]
```
root@u2090:/scripts/zc# ethtool --config-ntuple ens4 flow-type tcp4 dst-ip  192.104.182.209 dst-port 80 action -1
Added rule with ID 8186
```
BUT
```
root@u2090:/scripts/zc# ethtool --config-ntuple ens4 flow-type tcp4 dst-ip  192.104.182.209 dst-port 80 src-ip 192.104.182.224  action -1
rmgr: Cannot insert RX class rule: Invalid argument
```

**Comment by cardigliano** [comment]
@yarick what card model is this?
On ixgbe cards for instance you cannot mix rules with different set of fields (i.e. different mask).
It could be this is a similar case.

**Comment by yarick** [comment]
```
04:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
```
@cardigliano - is the most efficient way to direct flow for a given
1) SRC ADDR
2) DST ADDR
3) DST PORT
?

**Comment by cardigliano** [comment]
On 82599 you can set hw rules with <SRC ADDR, DST ADDR, *, DST PORT>, however you cannot mix rules with different masks like <SRC ADDR, DST ADDR, *, DST PORT> and <SRC ADDR, DST ADDR, *, *>
