### ISSUE TITLE
Ubuntu 16.04 pf_ring zc install

### ISSUE THREAD

**Issue by dwissm1** [ntop/PF_RING#263]
Have been trying to install the e1000e PF_RING ZC drivers to use with BRO.
Using an Intel NUC i3 (NUC6i3SYH) --  Has a Intel I219V Gigabit Ethernet LAN adapter and figured it would work?  (e1000e zc driver)

Ubuntu 16.04.3 LTS
$uname -r
4.10.0-35-generic

Trying to install the e1000e drivers:
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o' failed
make[2]: *** [/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o] Error 1
Makefile:1524: recipe for target '_module_/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src' failed
make[1]: *** [_module_/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-35-generic'
Makefile:259: recipe for target 'default' failed
make: *** [default] Error 2

Appreciate any help you can provide.

**Comment by cardigliano** [comment]
@dwissm1, our Ubuntu 16.04.3 LTS system has kernel 4.4.0-96, how did you install 4.10.0-35?

**Comment by dwissm1** [comment]
Upgraded with apt during patching.  Is that kernel supported or do I need to regress back?

Thanks for your reply.

**Comment by cardigliano** [comment]
@dwissm1 if it's a default kernel in ubuntu lts we need to patch the drivers to support it, however an apt upgrade does not install it on my machine, thus I need to understand how you installed it.

**Comment by dwissm1** [comment]
Sorry for the delay... 
I did a complete reinstall of Ubuntu just to make sure it wasn't something I did.
No patching, no apt-get update/upgrade.  Vanilla install of Ubuntu Desktop 16.04.3 and this is the kernel I got.


uname -a

Linux brobuntu 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Installed from a USB drive, downloaded from Ubuntu site. 


## NOTES:


/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c: In function ‘e1000e_cyclecounter_read’:
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5253:2: error: unknown type name ‘cycle_t’
  cycle_t systim, systim_next;
  ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5265:13: error: ‘cycle_t’ undeclared (first use in this function)
   systim = (cycle_t)systimel_1;
             ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5265:13: note: each undeclared identifier is reported only once for each function it appears in
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5265:21: error: expected ‘;’ before ‘systimel_1’
   systim = (cycle_t)systimel_1;
                     ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5266:22: error: expected ‘;’ before ‘systimeh’
   systim |= (cycle_t)systimeh << 32;
                      ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5270:21: error: expected ‘;’ before ‘systimel_2’
   systim = (cycle_t)systimel_2;
                     ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5271:22: error: expected ‘;’ before ‘systimeh’
   systim |= (cycle_t)systimeh << 32;
                      ^
In file included from /home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:48:0:
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:688:19: error: expected ‘;’ before ‘__er32’
 #define er32(reg) __er32(hw, E1000_##reg)
                   ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5285:27: note: in expansion of macro ‘er32’
    systim_next = (cycle_t)er32(SYSTIML);
                           ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/e1000.h:688:19: error: expected ‘;’ before ‘__er32’
 #define er32(reg) __er32(hw, E1000_##reg)
                   ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5286:28: note: in expansion of macro ‘er32’
    systim_next |= (cycle_t)er32(SYSTIMH) << 32;
                            ^
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c: In function ‘e1000_sw_init’:
/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:5338:20: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
   adapter->cc.read = e1000e_cyclecounter_read;
                    ^
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o' failed
make[5]: *** [/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o] Error 1
Makefile:1524: recipe for target '_module_/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src' failed
make[4]: *** [_module_/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src] Error 2
make[4]: Leaving directory '/usr/src/linux-headers-4.10.0-35-generic'
Makefile:259: recipe for target 'default' failed
make[3]: *** [default] Error 2
make[3]: Leaving directory '/home/user/install/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src'
Makefile:10: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/user/install/PF_RING/drivers/intel'
Makefile:3: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user/install/PF_RING/drivers'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cardigliano** [comment]
@dwissm1 please install Ubuntu LTS, not the Desktop version

**Comment by dwissm1** [comment]
So it looks like regardless of what version of Ubuntu 16.04.3 you get that kernel.  The older versions of LTS 16.04.1 and 2 use the older kernel.  Is it possible to recompile for the latest LTS?

**Comment by cardigliano** [comment]
Ubuntu Server LTS 16.04.3 comes with 4.4.0, Ubuntu Desktop comes with 4.10.0 (which is not yet supported)
