### ISSUE TITLE
No more than more than 32 egress queues in zbalance_ipc and packet drop in queues >24

### ISSUE THREAD

**Issue by radoslawc** [ntop/PF_RING#264]
Hi!
What's limiting factor in zbalance_ipc to have more than 32 egress queues? 
I mean this message:
[zbalance_ipc.c:673] ERROR: Misconfiguration detected: you cannot use more than 32 egress queues in fan-out or multi-app mode
happening with either -n 40 and -n 20,20 for example.

Secondly seems like queues > 24 are dropping packets for no apparent reason:

29/Sep/2017 10:08:45 [zbalance_ipc.c:213] =========================
29/Sep/2017 10:08:45 [zbalance_ipc.c:214] Absolute Stats: Recv 15'779'608 pkts (174'042 drops) - Forwarded 14'594'632 pkts (16'964'585 drops)
29/Sep/2017 10:08:45 [zbalance_ipc.c:253]                 zc:enp5s0f0 RX 15779641 pkts Dropped 174042 pkts (1.1 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 0 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 1 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 2 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 3 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 4 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 5 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 6 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 7 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 8 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 9 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 10 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 11 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 12 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 13 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 14 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 15 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 16 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 17 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 18 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 19 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 20 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 21 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 22 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 23 RX 0 pkts Dropped 0 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 24 RX 0 pkts Dropped 582114 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 25 RX 0 pkts Dropped 606976 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:267]                 Q 26 RX 0 pkts Dropped 15775648 pkts (0.0 %)
29/Sep/2017 10:08:45 [zbalance_ipc.c:286] Actual Stats: Recv 538'358.19 pps (0.00 drops) - Forwarded 498'149.66 pps (578'567.71 drops)
29/Sep/2017 10:08:45 [zbalance_ipc.c:296] =========================

This is pf_ring:
6.6.0-stable:518c91207f2f0a2df003178d69cf705e912003a7 (Thu Sep 28 11:04:58 2017 +0200)

ubuntu xenial server, kernel 4.4.0-96-generic #119-Ubuntu SMP

Best regards
Rado

**Comment by cardigliano** [comment]
@radoslawc in case of fan-out the 32-queues limit is due to the API (we use a 32-bit mask), we can enlarge it to 64 if needed (we usually discourage using too many queues). 
-n 40 is supposed to work, what are you passing to -m?

**Comment by radoslawc** [comment]
Thank you for swift response. You're absolutely right -n 40 works. Sorry for that.
Anyways, my idea was to make 20 workers for bro and 20 threads in suricata like this:
99@0 - 99@19 for bro
99@20 - 99@40 for suricata
with zbalance_ipc -i zc:enp5s0f0 -c 99 -n 20,20 -m 1 -p -g 1

**Comment by cardigliano** [comment]
Latest dev code now supports up to 64 consumers.
