### ISSUE TITLE
i40e Version: 2.2.4

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#265]
what is your plan for upgrading Inter I40e driver to the most recent version: 2.2.4?
Let me know if I can be any help
Thank you,
Steven

**Comment by cardigliano** [comment]
@szarea where did you find i40e 2.2.4? It seems latest stable is 2.1.26 https://sourceforge.net/projects/e1000/files/i40e%20stable/

**Comment by szarea** [comment]
Hi,

Please see:
https://downloadcenter.intel.com/download/24411/Intel-Network-Adapter-Driver-for-PCIe-40-Gigabit-Ethernet-Network-Connections-Under-Linux- <https://downloadcenter.intel.com/download/24411/Intel-Network-Adapter-Driver-for-PCIe-40-Gigabit-Ethernet-Network-Connections-Under-Linux->

Thank you,
Steven

**Comment by cardigliano** [comment]
For some reason they didn't update i40e on sourceforge, thank you for reporting, instead of updating to 2.1.26 we will go for 2.2.4.

**Comment by cardigliano** [comment]
i40e zc 2.2.4 is available (currently under testing)
