### ISSUE TITLE
pf_ring_zc_stat needs behavioral modification

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#266]
pfring_zc_stats (pfring_zc_queue *queue, pfring_zc_stat *stats) return value of zero for stats.sent if and only if it is transmitted from the same application.

For example, If my application reads 100 packet from zq1, the zq1's stats.recv provides right value.  However, if my application, tries to transmit the same packs from zq2, the zq2's stats.recv and state.sent are both zero.  

do not you think that state.sent's vale for zq2 should be 100 too.

**Comment by szarea** [comment]
how can I reset the stats?

**Comment by szarea** [comment]
https://downloadcenter.intel.com/download/24411/Intel-Network-Adapter-Driver-for-PCIe-40-Gigabit-Ethernet-Network-Connections-Under-Linux-

**Comment by cardigliano** [comment]
@szarea what do you mean with "if and only if it is transmitted from the same application"?
And what do you mean with "reset the stats", do you want to restart counting from 0 at some point?

**Comment by cardigliano** [comment]
Closed for inactivity, please reopen in case
