### ISSUE TITLE
ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration

### ISSUE THREAD

**Issue by ghost** [ntop/PF_RING#267]
OS: Red Hat Server 7.4

Closely related to: https://github.com/ntop/PF_RING/issues/135

I saw the comment: "zc does not support 1gb hugepages, please try unmounting all your hugetlbfs and remounting it with 2mb hugepages (please note you have "nodev on /mnt/huge type hugetlbfs (rw,pagesize=1GB)")"

On Red Hat, it seems according to [this](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7-Beta/html/Performance_Tuning_Guide/sect-Red_Hat_Enterprise_Linux-Performance_Tuning_Guide-Memory-Configuring-huge-pages.html) that the total size of the huge pages is controlled by using the number. Since the size is 2Mib, I set it to 1 page based on the thread [here](https://github.com/ntop/PF_RING/issues/135). I did this by doing the following:

`sysctl -w vm.nr_hugepages=1
echo "vm.nr_hugepages=1" >> /etc/sysctl.conf

Verified with: grep Huge /proc/meminfo
AnonHugePages:    137216 kB
HugePages_Total:       1
HugePages_Free:        1
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB`

However, when I run:

`zbalance_ipc -i zc:ens15f0 -c 99 -n 8 -m 1 -g 8
08/Oct/2017 22:13:58 [zbalance_ipc.c:723] ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration`

I still receive the error. I'm trying to set up bro according to [this ](https://github.com/ntop/PF_RING/blob/dev/doc/README.bro.md) tutorial.

Any ideas?

# **Update:**

I recompiled zbalance with print statements to get a better idea of what is going on and it seems that there is no hugepages mount point:

[root@sensor1 examples_zc]# ./zbalance_ipc -i zc:ens15f0 -c 99 -n 1
cluster_id is 99
buffer_len is 1536
metadata_len is 0
tot_num_buffers is 40984
numa_node_id is 4294967295
hugepages mount point is
08/Oct/2017 23:17:37 [zbalance_ipc.c:762] ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration

## Update 2
Went digging through the source. Evidently setting it to NULL has it autodetect:
* @param hugepages_mountpoint The HugeTLB mountpoint (NULL for auto-detection) for memory allocation.

## Update 3
I tried manually specifying the hugepages mountpoint in the code

This got me:

optarg is /dev/hugepages/
cluster_id is 99
buffer_len is 1536
metadata_len is 0
tot_num_buffers is 40984
numa_node_id is 4294967295
hugepages mount point is /dev/hugepages
Press enter to continue...

08/Oct/2017 23:48:58 [zbalance_ipc.c:768] ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration

Right back to where I started.

## Update 4

I went rolling through the code with GDB and it seems that pfring_open is returning null and subsequently I'm getting 1536 return. See this image
![screen1](https://user-images.githubusercontent.com/1595564/31325669-5110926e-ac85-11e7-9c2b-86e0a9227b56.PNG)
.

**Comment by cardigliano** [comment]
@grantcurell 2MB hugepages (1 page x 2MB per page) is not enough, please set vm.nr_hugepages to something like 512 at least

**Comment by ghost** [comment]
I found the issue. By default, Red Hat seems to have no huge pages. Based on your response, I hopped on my other server which had an identical configuration to the one I used above, but I had not manipulated the hugepage settings whatsoever. See the attached [hugepages.txt](https://github.com/ntop/PF_RING/files/1368383/hugepages.txt). It fails and on further inspection, there are no huge pages. Due to the comments in the other thread and not having any idea what any of this meant when I first encountered the problem, I assumed my pages were too large when in fact they didn't exist. An easy problem to fix once you know what you're looking at, but I was completely lost as a novice hahaha. The fix action is:

`sysctl -w vm.nr_hugepages=512`
`echo "vm.nr_hugepages=512" >> /etc/sysctl.conf`

To make the program friendlier to the uninitiated, suggest following patch:

Lines: 751-755 of zbalance_ipc.c
  if (zc == NULL) {
    trace(TRACE_ERROR, "pfring_zc_create_cluster error [%s] Please check your hugetlb configuration\n",
            strerror(errno));
    return -1;
  }

change to:

  if (zc == NULL) {
    if (errno == 105) {
      trace(TRACE_ERROR, "pfring_zc_create_cluster error [%s]\n",
              strerror(errno));
      printf("Insufficient hugepage memory. Try increasing your hugepage size or count.\n");
    } else {
      trace(TRACE_ERROR, "pfring_zc_create_cluster error [%s] Please check your hugetlb configuration\n",
              strerror(errno));
    }
    return -1;
  }

Or something with less of a magic number, but that makes it clearer what is going on.

**Comment by cardigliano** [comment]
Message added as suggested (please send a pull request next time :-) Thank you.

**Comment by ghost** [comment]
No problem!

**Comment by lijk8890** [comment]
mount -t hugetlbfs nodev /mnt/huge
sysctl -w vm.nr_hugepages=2048
