### ISSUE TITLE
PFRing w/Bro: fatal error: problem with interface zc:<interface> (pcap_error: SIOCGIFHWADDR: No such device (pcap_activate))

### ISSUE THREAD

**Issue by ghost** [ntop/PF_RING#268]
I am using:
[The Bro PFRing Read Me](https://github.com/ntop/PF_RING/blob/dev/doc/README.bro.md)
[Best practices for using Bro IDS with PF_RING ZC. Reliably.](http://www.ntop.org/pf_ring/best-practices-for-using-bro_ids-with-pf_ring-zc-reliably/)

I have confirmed bro recognizes the zc drivers because I can collect on zc:ens15f0.

## Currently Trying

Right now I am trying to do the second configuration where you create a series of dummy interfaces. I have run:

modprobe dummy numdummies=4
ifconfig dummy0 up
ifconfig dummy1 up
ifconfig dummy2 up
ifconfig dummy3 up
zbalance_ipc -i zc:ens15f0 -n 4 -m 1 -c 2 -r 0:dummy0 -r 1:dummy1 -r 2:dummy2 -r 3:dummy3

My current configuration for node.cfg is: [current_configuration.txt](https://github.com/ntop/PF_RING/files/1369116/current_configuration.txt)

However, when I run deploy in broctl I receive the following:

> ==== stderr.log
> fatal error: problem with interface zc:dummy3 (pcap_error: SIOCGIFHWADDR: No such device (pcap_activate))
>
> ==== stdout.log
> max memory size         (kbytes, -m) unlimited
> data seg size           (kbytes, -d) unlimited
> virtual memory          (kbytes, -v) unlimited
> core file size          (blocks, -c) unlimited
>
> ==== .cmdline
> -i zc:dummy3 -U .status -p broctl -p broctl-live -p local -p worker-4-3 local.bro broctl base/frameworks/cluster local-worker.bro broctl/auto
>
> ==== .env_vars
> PATH=/opt/bro/bin:/opt/bro/share/broctl/scripts:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
> BROPATH=/opt/bro/spool/installed-scripts-do-not-touch/site::/opt/bro/spool/installed-scripts-do-not-touch/auto:/opt/bro/share/bro:/opt/bro/share/bro/policy:/opt/bro/share/bro/site
> CLUSTER_NODE=worker-4-3

## Also Tried

I first tried tying bro directly to zbalance_ipc with node.cfg of: 
[old_config.txt](https://github.com/ntop/PF_RING/files/1369131/old_config.txt)

`zbalance_ipc -i zc:ens15f0 -c 99 -n 8 -m 1 -g 8`

Edit: For clarification, you get the same error it just says it couldn't find zc:99.

**Comment by cardigliano** [comment]
Please use just "dummy3" in place of "zc:dummy3" as dummy interfaces are not ZC interface.

**Comment by ghost** [comment]
Will try momentarily, but what about the section "Also Tried"? I would need zc in front of the 99 would I not? If so, shouldn't bro have found that?

**Comment by cardigliano** [comment]
Please check if "pfcount -i zc:99@0" is working

**Comment by ghost** [comment]
Confirmed, dropping the zc off of the interface worked.

---------------------------

In response to what is directly above: No, I gave that a shot earlier as well, but no dice. I have reproduced the problem. See the below.

Tried with
[worker-1]
type=worker
host=localhost
interface=zc:99
lb_method=pf_ring
lb_procs=4
pin_cpus=0,1,2,3

and

[worker-1]
type=worker
host=localhost
interface=zc:99@0
lb_method=pf_ring
lb_procs=4
pin_cpus=0,1,2,3

respectively. Output of broctl diag is below.

[output.txt](https://github.com/ntop/PF_RING/files/1369276/output.txt)

**Comment by ghost** [comment]
Wait, I'm bad. You asked for pfcount. One moment.

Edit: Yes, pfcount works as expected:

Note: `pfcount -i zc:99` also works.

[root@sensor1 ~]<POUND> pfcount -i zc:99@0
Using PF_RING v.6.6.0
Capturing from zc:99@0 [mac: unknown][if_index: -1][speed: 0Mb/s]
<POUND> Device RX channels: 1
<POUND> Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/12818-none.66

Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd]



Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]

Actual Stats: [0 pkts rcvd][1'000.03 ms][0.00 pps][0.00 Gbps]



Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]

Actual Stats: [0 pkts rcvd][1'000.02 ms][0.00 pps][0.00 Gbps]


^CLeaving...

Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]

Actual Stats: [0 pkts rcvd][368.87 ms][0.00 pps][0.00 Gbps]
