### ISSUE TITLE
How to interpret zbalance_ipc - High Packet Drop Rate?

### ISSUE THREAD

**Issue by ghost** [ntop/PF_RING#269]
I have a 100% noob question. How do you interpret zbalance_ipc's output? I'm trying to figure out how much of the total traffic I'm actually capturing.

09/Oct/2017 13:20:54 [zbalance_ipc.c:214] Absolute Stats: Recv 69'317'744 pkts (387'529'076 drops) - Forwarded 69'317'739 pkts (0 drops)
09/Oct/2017 13:20:54 [zbalance_ipc.c:286] Actual Stats: Recv 119'385.80 pps (1'056'214.34 drops) - Forwarded 119'384.80 pps (0.00 drops)

I'm giving this shot on a server and I want to confirm my understanding of zbalance_ipc.

The above is saying the following:

- zbalance_ipc received 69'317'744 packets total and dropped 387'529'076 in the receive queue. (That seems really really bad?)
- It forwarded 69,317,739 to bro and none of those were dropped.
- zbalance is currently receiving 119,385 packets per second and is dropping 1,056,214.34 per second? Is that millions? That also seems really really bad.
- On the forwarding side it is forwarding 119,384.80 as in thousands? With no drops?

Thanks in advance.

**Comment by cardigliano** [comment]
Everything is correct. 1'056'214.34 is 1 million, and 119'384.80 is 119 thousands. 
As of the performance and drops, could you provide the configuration you are using? (at least the command line)

**Comment by ghost** [comment]
For that one I tried [node.cfg-old.txt](https://github.com/ntop/PF_RING/files/1370333/node.cfg-old.txt)

with `zbalance_ipc -i zc:ens15f0 -n 4 -m 1 -c 2 -r 0:dummy0 -r 1:dummy1 -r 2:dummy2 -r 3:dummy3`

--------------------------------------------------

I then wrote the following dummy code: [dummy_code.txt](https://github.com/ntop/PF_RING/files/1370337/dummy_code.txt)

which generated a zbalance_ipc command which would run as 32 workers with 32 queues.

This is what the node config looks like. [node.cfg-new.txt](https://github.com/ntop/PF_RING/files/1370344/node.cfg-new.txt)

Unfortunately, the performance was still quite bad.
zbalance statistics: [performance.txt](https://github.com/ntop/PF_RING/files/1370352/performance.txt)

What I was sending: [pfsend_output.txt](https://github.com/ntop/PF_RING/files/1370354/pfsend_output.txt)

This was a pcap I downloaded from [here](https://download.netresec.com/pcap/maccdc-2011/maccdc2011_00013_20110312202724.pcap.gz).

Edit: What really caught my eye was the massive discrepancy between what was being sent and what was being received. While the sender side was pushing out millions of packets per second, the receiver side only saw a tiny fraction of that.

**Comment by cardigliano** [comment]
Please provide cat /proc/net/pf_ring/dev/ens15f0/info

**Comment by ghost** [comment]
[root@sensor1 ~]# cat /proc/net/pf_ring/dev/ens15f0/info
Name:         ens15f0
Index:        15
Address:      90:E2:BA:A6:63:10
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    32
RX Queues:    32
Num RX Slots: 8192
Num TX Slots: 8192

**Comment by ghost** [comment]
Update:

I spun things up without running Bro and saw that there is a surprisingly high drop rate before I start Bro.
![drop_before_bro](https://user-images.githubusercontent.com/1595564/31417104-20d3eb22-adf3-11e7-9d64-dab7482ab26f.PNG)

It looks like I'm losing 5-10% of the traffic before it even hits bro.

## More Information

I dropped the speed to 1 Gb/s and something weird is going on. zbalance_ipc goes from seeing about what I expect it to see as far as I can tell to far less than it should. It's reporting that it only is seeing a fraction of the traffic I know is being sent to it.

![packet_count_discrepency](https://user-images.githubusercontent.com/1595564/31417659-a65744ee-adf6-11e7-8c3c-117b422c5720.PNG)

Is this an issue with how the information is displayed or is this valid?

I also ran it with pfcount - it looks like I'm losing about 1/4 packets at 10Gb/s.
![pfcount](https://user-images.githubusercontent.com/1595564/31418221-6a5e86b0-adfa-11e7-9382-0e1604eeb625.PNG)

**Comment by cardigliano** [comment]
@grantcurell please note the driver is configured with 32 RSS queues, but zbalance_ipc is capturing from the first queue only. This explains why you see little traffic out of the overall traffic you are sending. Please Change the driver configuration to load 1 RSS queue per interface. 
Please read:
https://github.com/ntop/PF_RING/blob/dev/doc/README.RSS.md
https://github.com/ntop/PF_RING/blob/dev/doc/README.apt_rpm_packages.md
After doing this fix, let us know what performance do you get.

**Comment by ghost** [comment]
@cardigliano: How do you know which number corresponds to which interface?

`insmod ixgbe.ko RSS=0,0,0,0`

On my box I have a riser card with two GBICs in it. Would:

`modprobe ixgbe_zc RSS=0,0`

correspond to put as many RSS queues as possible on each interface? Said another way, is this how it works?

First 0 in RSS=0,0 corresponds to ens15f0
Second 0 in RSS=0,0 corresponds to ens15f1

I tried `modprobe ixgbe_zc RSS=0,0,0,0` just for giggles and the performance was the same, but I suspect there is more to it. That said, my Google-fu is coming up empty on how this stuff works so it's difficult to figure out how to proceed.

The other command I'm trying to figure out is:

`ethtool --set-channels <if> combined 1`

What does combined 1 mean? I tried ethtool --set-channels <if> combined 32, but that just got kicked back at me with no information as to why:

[root@sensor1 ~]# ethtool --set-channels ens15f0 combined 32
combined unmodified, ignoring
no channel parameters changed, aborting
current values: tx 0 rx 0 other 1 combined 32

I tried looking at the man page, but all it said was:

--set-channels
Changes the numbers of channels of the specified network device.

which to a novice is basically useless because if I knew exactly what a channel was, I wouldn't have to look it up in the first place :-p.

--------------------------------------------------------------------------

Edit: For clarification, if I have already installed the package, I don't need to do anything from [this page](https://github.com/ntop/PF_RING/blob/dev/doc/README.apt_rpm_packages.md) unless I want to configure all of this on startup - correct?

**Comment by cardigliano** [comment]
Please use:
modprobe ixgbe_zc RSS=1,1,1,1

**Comment by ghost** [comment]
@cardigliano 

I ran `modprobe ixgbe_zc RSS=1,1,1,1` and then `pfcount -i zc:ens15f0 -n 32`

Performance worsened substantially:

![pfcount](https://user-images.githubusercontent.com/1595564/31440880-0484b2bc-ae57-11e7-85fa-48b3d51a0aaf.PNG)

Edit: I saw the section regarding naming convention, but I don't fully understand the implications. Does this mean pfcount needs to be called with a series of interface queues? Or is it still called with interface zc:ens15f0

**Comment by cardigliano** [comment]
Can I see /proc/net/pf_ring/dev/ens15f0/info now?
Please also provide the pfcount command line

**Comment by ghost** [comment]
@cardigliano 

Name:         ens15f0
Index:        33
Address:      90:E2:BA:A6:63:10
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 8192
Num TX Slots: 8192

**Comment by cardigliano** [comment]
The driver is configured with 8K slots, maximum is 32K. Please note our init.d or load_driver.sh script by default  configures the driver with 32K slots, it's recommended to use the scripts (also for other settings):

ethtool -G $IF rx 32768
ethtool -G $IF tx 32768

**Comment by ghost** [comment]
Following up on what we worked on together, it unfortunately still has a very high packet drop rate. Performance below:

`zbalance_ipc -i zc:ens15f0 -c 99 -n 32 -m 1 -g 1`

![performance](https://user-images.githubusercontent.com/1595564/31447087-ba36dc20-ae66-11e7-89f6-f97bc196f38a.PNG)

Copy of node.cfg

[node.cfg.txt](https://github.com/ntop/PF_RING/files/1375957/node.cfg.txt)

To start up I ran

`/etc/init.d/pf_ring start`

**Comment by cardigliano** [comment]
Packet loss depends on time spent by zbalance_ipc for forwarding to dummy interfaces, as discussed by email, closing this issue
