### ISSUE TITLE
PF_RING ZC have params to set queue size between zc NIC and zc Applcation

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#272]
Hi, I want to know have params to set queue size between zc NIC and zc Applcation.
like param in zbalance_ipc to set queue size between zbalance_ipc and zcount_ipc.
-q <size>        Number of slots in each consumer queue (default: 8192)
-b <size>        Number of buffers in each consumer pool (default: 16)

**Comment by cardigliano** [comment]
You can tune that using the RSS queue size in the driver configuration

**Comment by laoyang103** [comment]
@cardigliano 

I can not find param as you say, the follow is igb driver all param, could you tell me?

> Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x         
root@iPilot-APM:~# modinfo /usr/local/driver/igb.ko         
filename:       /usr/local/driver/igb.ko                    
version:        5.3.3.5                                     
license:        GPL                                         
description:    Intel(R) Gigabit Ethernet Network Driver    
author:         Intel Corporation, <e1000-devel@lists.source
forge.net>                                                  
srcversion:     BB8C2D706848890338E51A1                     
alias:          pci:v00008086d000010D6sv*sd*bc*sc*i*        
alias:          pci:v00008086d000010A9sv*sd*bc*sc*i*        
alias:          pci:v00008086d000010A7sv*sd*bc*sc*i*        
alias:          pci:v00008086d000010E8sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001526sv*sd*bc*sc*i*        
alias:          pci:v00008086d0000150Dsv*sd*bc*sc*i*        
alias:          pci:v00008086d000010E7sv*sd*bc*sc*i*        
alias:          pci:v00008086d000010E6sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001518sv*sd*bc*sc*i*        
alias:          pci:v00008086d0000150Asv*sd*bc*sc*i*        
alias:          pci:v00008086d000010C9sv*sd*bc*sc*i*        
alias:          pci:v00008086d00000440sv*sd*bc*sc*i*        
alias:          pci:v00008086d0000043Csv*sd*bc*sc*i*        
alias:          pci:v00008086d0000043Asv*sd*bc*sc*i*        
alias:          pci:v00008086d00000438sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001516sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001511sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001510sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001527sv*sd*bc*sc*i*        
alias:          pci:v00008086d0000150Fsv*sd*bc*sc*i*        
alias:          pci:v00008086d0000150Esv*sd*bc*sc*i*        
alias:          pci:v00008086d00001524sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001523sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001522sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001521sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001539sv*sd*bc*sc*i*        
alias:          pci:v00008086d0000157Csv*sd*bc*sc*i*        
alias:          pci:v00008086d0000157Bsv*sd*bc*sc*i*        
alias:          pci:v00008086d00001538sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001537sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001536sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001533sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001F45sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001F41sv*sd*bc*sc*i*        
alias:          pci:v00008086d00001F40sv*sd*bc*sc*i*        
depends:        ptp                                         
vermagic:       3.19.0-25-generic SMP mod_unload modversions
                                                            
parm:           InterruptThrottleRate:Maximum interrupts per
 second, per vector, (max 100000), default 3=adaptive (array
 of int)                                                    
parm:           IntMode:Change Interrupt Mode (0=Legacy, 1=M
SI, 2=MSI-X), default 2 (array of int)                      
parm:           Node:set the starting node to allocate memor
y on, default -1 (array of int)                             
parm:           LLIPort:Low Latency Interrupt TCP Port (0-65
535), default 0=off (array of int)                          
parm:           LLIPush:Low Latency Interrupt on TCP Push fl
ag (0,1), default 0=off (array of int)                      
parm:           LLISize:Low Latency Interrupt on Packet Size
 (0-1500), default 0=off (array of int)                     
parm:           RSS:Number of Receive-Side Scaling Descripto
r Queues (0-8), default 1, 0=number of cpus (array of int)  
parm:           VMDQ:Number of Virtual Machine Device Queues
: 0-1 = disable, 2-8 enable, default 0 (array of int)       
parm:           max_vfs:Number of Virtual Functions: 0 = dis
able, 1-7 enable, default 0 (array of int)                  
parm:           MDD:Malicious Driver Detection (0/1), defaul
t 1 = enabled. Only available when max_vfs is greater than 0
 (array of int)                                             
parm:           QueuePairs:Enable Tx/Rx queue pairs for inte
rrupt handling (0,1), default 1=on (array of int)           
parm:           EEE:Enable/disable on parts that support the
 feature (array of int)                                     
parm:           DMAC:Disable or set latency for DMA Coalesci
ng ((0=off, 1000-10000(msec), 250, 500 (usec)) (array of int
)                                                           
parm:           LRO:Large Receive Offload (0,1), default 0=o
ff (array of int)                                           
parm:           enable_debug:Set to 1 to enable debug tracin
g into the syslog (uint)                                    
parm:           debug:Debug level (0=none, ..., 16=all) (int
)                                                           
root@iPilot-APM:~# modinfo /usr/local/driver/igb.ko | grep s
ize                                                         
root@iPilot-APM:~# modinfo /usr/local/driver/ixgbe.ko | grep
 size

**Comment by cardigliano** [comment]
The option name is RSS, please read:
https://github.com/ntop/PF_RING/blob/dev/doc/README.apt_rpm_packages.md
https://github.com/ntop/PF_RING/blob/dev/doc/README.RSS.md

**Comment by laoyang103** [comment]
@cardigliano 

I have read your link about RSS, before this I set 2 queues to recv.
I use ethtool to adjusting the size of the RX queue, but nic have the max size of rx queue 

> oot@iPilot-APM:~# ethtool -g em2                           
Ring parameters for em2:                                    
Pre-set maximums:                                           
RX:             4096                                        
RX Mini:        0                                           
RX Jumbo:       0                                           
TX:             4096                                        
Current hardware settings:                                  
RX:             4096                                        
RX Mini:        0                                           
RX Jumbo:       0                                           
TX:             4096

> 
you see I have set 4096 the rx queue size, but it have packet lost too.
next I set more rx queues for recv, but it not expand queue size.
 how can I set more than max rx queue size

**Comment by cardigliano** [comment]
@laoyang103, 4096 is the max queue size for igb cards,
if you have drops it's likely it depends on the application, could you provide some output from zbalance_ipc?

**Comment by laoyang103** [comment]
@cardigliano 

> 15/Oct/2017 15:35:36 [ipmipc.c:204]                 zc:p1p2@
0 RX 43725318 pkts Dropped 124833 pkts (0.3 %)              
15/Oct/2017 15:35:36 [ipmipc.c:204]                 zc:p1p2@
1 RX 43982121 pkts Dropped 32228 pkts (0.1 %)               
15/Oct/2017 15:35:36 [ipmipc.c:218]                 Q 0 RX 8
5459456 pkts Dropped 177353 pkts (0.2 %)                    
15/Oct/2017 15:35:36 [ipmipc.c:218]                 Q 1 RX 8
5637008 pkts Dropped 0 pkts (0.0 %)                         
15/Oct/2017 15:35:36 [ipmipc.c:218]                 Q 2 RX 5
1510879 pkts Dropped 34060776 pkts (39.8 %)                 
15/Oct/2017 15:35:36 [ipmipc.c:218]                 Q 3 RX 0
 pkts Dropped 0 pkts (0.0 %)                                
15/Oct/2017 15:35:36 [ipmipc.c:237] Actual Stats: Recv 2'727
'058.93 pps (0.00 drops) - Forwarded 7'122'097.19 pps (867'0
40.46 drops)

as you see I set 2 recv queue, p1p1 is inter 82599 10Gbit NIC
drop packet is between NIC and zbalance_ipc, I think I need set more recv queue

**Comment by cardigliano** [comment]
As you can see drops are on "Forwarded", that means the consumer cannot keep up with ingress rate.

**Comment by laoyang103** [comment]
@cardigliano 

see below

> 15/Oct/2017 15:35:36 [ipmipc.c:204] zc:p1p2@0 RX 43725318 pkts Dropped 124833 pkts (0.3 %)
15/Oct/2017 15:35:36 [ipmipc.c:204] zc:p1p2@1 RX 43982121 pkts Dropped 32228 pkts (0.1 %)

**Comment by cardigliano** [comment]
Please avoid using RSS with zbalance_ipc, as it just adds more work for aggregation in zbalance_ipc

**Comment by laoyang103** [comment]
@cardigliano 

Thank you for your reminding
