### ISSUE TITLE
PF_RING & RT Linux kernel

### ISSUE THREAD

**Issue by hsirk6** [ntop/PF_RING#275]
Hello,
I am experimenting with RT Kernels. I am interested in Centos patched kernel 3.10.0-514.6.1.rt56.429.el7.x86_64.But the PF_RING kernel code fails to compile.

Does PF_RING support linux RT kernel?
Thanks
Krishnan

**Comment by cardigliano** [comment]
Hi @hsirk6, pf_ring has not been tested on RT kernel, happy to help you fixing compilation issues though. Please share the errors you get.

**Comment by hsirk6** [comment]
Hi @cardigliano, Thanks for the quick response and clarification. Below is the error I see.

/lib/modules/3.10.0-514.6.1.rt56.429.el7.x86_64/build SUBDIRS=/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel EXTRA_CFLAGS='-I/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel -DGIT_REV="\"  s_2_1:395a9259c7653fbe47a67114cb153d97de2e3f66\""' modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-514.6.1.rt56.430.el7.x86_64'
  CC [M]  /var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.o
In file included from include/linux/spinlock_types.h:20:0,
                 from include/linux/spinlock.h:81,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from /var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.c:78:
/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.c: In function ‘init_ring_readers’:
include/linux/rwlock_types_rt.h:27:2: error: expected expression before ‘{’ token
  { .lock = __RT_MUTEX_INITIALIZER_SAVE_STATE(name.lock), \
  ^
/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.c:293:5: note: in expansion of macro ‘__RW_LOCK_UNLOCKED’
     __RW_LOCK_UNLOCKED(ring_mgmt_lock)
     ^
/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.c: In function ‘init_lockless_list’:
include/linux/rwlock_types_rt.h:27:2: error: expected expression before ‘{’ token
  { .lock = __RT_MUTEX_INITIALIZER_SAVE_STATE(name.lock), \
  ^
/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.c:452:5: note: in expansion of macro ‘__RW_LOCK_UNLOCKED’
     __RW_LOCK_UNLOCKED(l->list_lock)
     ^
make[3]: *** [/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel/pf_ring.o] Error 1
make[2]: *** [_module_/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel] Error 2
make[2]: Leaving directory `/usr/src/kernels/3.10.0-514.6.1.rt56.430.el7.x86_64'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/var/nfsshare//workspace//external/pfring/pfring-6.7.0/kernel'
make: *** [all] Error 2

**Comment by sangorrin** [comment]
Hi, I could reproduce the same problem.
It seems you are using __RW_LOCK_UNLOCKED for dynamic initialization, and you should be using rwlock_init instead (https://www.kernel.org/doc/Documentation/locking/spinlocks.txt).

[0001-pf_ring-use-rwlock_init-for-dynamic-initialization.patch.txt](https://github.com/ntop/PF_RING/files/1761184/0001-pf_ring-use-rwlock_init-for-dynamic-initialization.patch.txt)

**Comment by cardigliano** [comment]
@sangorrin you are right, I just pushed a fix. 
@hsirk6 please test latest dev code and let us know if it works for you.
Thank you.
