### ISSUE TITLE
vlan filtering doesn't work on live capture

### ISSUE THREAD

**Issue by gaardiolor** [ntop/PF_RING#276]
Hello, 

I'm using pf_ring v6.4.0-766-g7f0b5c5 on RHEL6 running a kernel from elrepo, kernel-ml-4.13.9-1.el6.elrepo.x86_64 . Compiled PF_RING , insmodded the module, all fine. Next I compiled libpcap and tcpdump, also went fine. 

Now I'm using tcpdump on a trunk port, by which I mean that I'm receiving packets containing 802.1Q vlan tags. I can see those tags running 
`tcpdump -nei <int>`
 so I'm sure I'm running on a trunk port. Now when I run tcpdump without any filters and dump the pcap to disk, afterwards I can filter the pcap on a vlan tag, example: 
`tcpdump -ner <pcap> vlan 1000`
 I only get the packets of vlan 1000 . 

This doesn't work when running a live capture however. 
`tcpdump -nei <int> vlan 1000`
doesn't show any packets. The 'normal' tcpdump version, not using the PF_RING kernel module, does show packets.

This was a known bug in earlier versions of both kernel 2.x and libpcap, did it somehow got reintroduced to PF_RING ? Also see https://github.com/ntop/PF_RING/issues/89 . Apparently it was fixed before, but now it's broken again ? I've tested with tcpdumps compiled against both libpcap-1.7.4 and libpcap-1.8.1, same result.

**Comment by cardigliano** [comment]
@gaardiolor we made some fixes to bpf filters with libpcap some time ago, could you try with latest PF_RING to see if you are still able to reproduce it? Thank you

**Comment by gaardiolor** [comment]
Thanks for the quick reply! Didn't realize the default branch pointed to an old version. Just cloned the 7.0.0-stable branch, same problem unfortunately.

Steps:
```
rmmod pf_ring.ko # old version
git clone -b 7.0.0-stable https://github.com/ntop/PF_RING.git
cd PF_RING/kernel
make
make install
insmod pf_ring.ko

cd ../userland/lib
./configure
make
make install

cd ../libpcap-1.8.1
./configure
make

cd ../tcpdump
./configure # it finds pcap in ../libpcap-1.8.1/libpcap.a
make
```
After that, the newly compiled tcpdump can't filter on vlan (tags) on a live capture. After dumping to disk (using -w ) it works. So it's the same behaviour as the old version.

**Comment by cardigliano** [comment]
@gaardiolor it seems there is an issue with vlan filtering on some kernels as you discovered, as a temporary workaround you can set the PCAP_PF_RING_USERSPACE_BPF env var to enable userspace bpf (this is supported on latest stable and dev code)

**Comment by gaardiolor** [comment]
@cardigliano Great it works, thanks! Any idea about the impact on performance ?

**Comment by gaardiolor** [comment]
Just tested on stock kernel of RHEL6 ( 2.6.32-696.1.1.el6.x86_64 ) and RHEL7 ( 3.10.0-514.16.1.el7.x86_64 ), same problem. Workaround works on those systems as well. 

Could be related to https://bugzilla.redhat.com/show_bug.cgi?id=1264316

**Comment by cardigliano** [comment]
It could have some impact as all traffic is moved from kernel to userspace, what is your traffic rate?

**Comment by gaardiolor** [comment]
About 200k pps at the moment. Still have 0 dropped packets with the workaround enabled, while the stock tcpdump drops about 2k packets per second.. so apparently not all benefit of PF_RING is lost when using this workaround.

Any idea when a permanent fix could be implemented (rough estimate; will it take days/weeks/months/years) ?

**Comment by cardigliano** [comment]
You should be able to move to userspace up to 2-3Mpps  (depending on your system), when BPF evaluation has some overhead, not sure what is the max rate you should be able to handle (it also depends on filter complexity). We will work on this asap, hopefully it will take a few days, however it depends on the root cause (we can write some workaround to make it work inside the kernel, but better to write a final patch)

**Comment by cardigliano** [comment]
https://github.com/ntop/PF_RING/commit/7e6b0529a1759770f31477be926bd2530e6bc523 fixes this, PCAP_PF_RING_USERSPACE_BPF is no longer needed as workaround
