### ISSUE TITLE
Kernel Panic when BPF is in use on RHEL7.1 

### ISSUE THREAD

**Issue by chjohnst** [ntop/PF_RING#28]
[  257.126292] [PF_RING] Welcome to PF_RING 6.1.1 ($Revision: dev:c294956bff608bbdddd2a00810ad37f538df6dea$)
(C) 2004-14 ntop.org
[  257.126304] [PF_RING] registered /proc/net/pf_ring/
[  257.126305] NET: Registered protocol family 27
[  257.126314] [PF_RING] Min # ring slots 4096
[  257.126314] [PF_RING] Slot version     16
[  257.126315] [PF_RING] Capture TX       Yes [RX+TX]
[  257.126316] [PF_RING] IP Defragment    No
[  257.126316] [PF_RING] Initialized correctly
[  257.140850] device p1p1 entered promiscuous mode
[  257.151117] BUG: unable to handle kernel NULL pointer dereference at 000000000000000e
[  257.151152] IP: [<ffffffff811c8681>] file_free_rcu+0x11/0x40
[  257.151178] PGD 0
[  257.151188] Oops: 0002 [#1] SMP
[  257.151202] Modules linked in: pf_ring(OF) 8021q garp stp mrp llc ext4 mbcache jbd2 intel_powerclamp coretemp iTCO_wdt iTCO_vendor_support dcdbas ipmi_devintf intel_rapl kvm_intel kvm crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel aesni_intel lrw gf128mul glue_helper ablk_helper cryptd pcspkr sb_edac edac_core lpc_ich mei_me mfd_core mei shpchp ipmi_si wmi ipmi_msghandler acpi_power_meter binfmt_misc xfs libcrc32c sd_mod crc_t10dif crct10dif_common mgag200 syscopyarea sysfillrect sysimgblt drm_kms_helper ttm igb ixgbe drm mdio i2c_algo_bit ptp i2c_core pps_core megaraid_sas dca dm_mirror dm_region_hash dm_log dm_mod
[  257.151448] CPU: 1 PID: 0 Comm: swapper/1 Tainted: GF          O--------------   3.10.0-229.el7.x86_64 #1
[  257.151476] Hardware name: Dell Inc. PowerEdge R730xd/0599V5, BIOS 1.2.10 03/09/2015
[  257.151499] task: ffff8810287316c0 ti: ffff881028758000 task.ti: ffff881028758000
[  257.151521] RIP: 0010:[<ffffffff811c8681>]  [<ffffffff811c8681>] file_free_rcu+0x11/0x40
[  257.151547] RSP: 0018:ffff88203ec036f0  EFLAGS: 00010286
[  257.151563] RAX: ffff881ff5a13800 RBX: ffff88201ed16d00 RCX: 0000000000000000
[  257.151584] RDX: 000000000000000e RSI: ffff881ff5a13820 RDI: 000000000000000e
[  257.151604] RBP: ffff88203ec036f8 R08: 000000000000000e R09: 0000000000000002
[  257.151625] R10: 0000000000000001 R11: ffff88201ed16d00 R12: 000000000000000e
[  257.151645] R13: 000000000000002e R14: ffff881ff2c6e1ce R15: ffff8820225b0800
[  257.151666] FS:  0000000000000000(0000) GS:ffff88203ec00000(0000) knlGS:0000000000000000
[  257.151689] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  257.151706] CR2: 000000000000000e CR3: 000000000190a000 CR4: 00000000001407e0
[  257.151727] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  257.151747] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
[  257.151768] Stack:
[  257.151776]  ffff88201ed16d00 ffff88203ec03740 ffffffffa063ece2 ffff88203ec03740
[  257.151805]  ffffffff810a2494 ffff8820225b0800 ffff88203ec03b50 000000000000000e
[  257.151836]  ffff88201ed16d00 ffff88203ec037b0 ffff88203ec03a20 ffffffffa063f13e
[  257.151868] Call Trace:
[  257.151878]  <IRQ>
[  257.151886]
[  257.151897]  [<ffffffffa063ece2>] bpf_filter_skb+0x52/0xe0 [pf_ring]
[  257.151917]  [<ffffffff810a2494>] ? __wake_up+0x44/0x50
[  257.151936]  [<ffffffffa063f13e>] add_skb_to_ring.isra.42+0x3ce/0x10e0 [pf_ring]
[  257.151959]  [<ffffffffa063b281>] ? parse_raw_pkt.part.27+0x6a1/0xa60 [pf_ring]
[  257.151983]  [<ffffffff813b0001>] ? serial8250_unregister_port+0x21/0xa0
[  257.152005]  [<ffffffffa0640b6f>] skb_ring_handler+0xd1f/0x1eb0 [pf_ring]
[  257.152030]  [<ffffffff813b7084>] ? credit_entropy_bits.part.12+0x164/0x1c0
[  257.152052]  [<ffffffff813b8854>] ? add_interrupt_randomness+0x184/0x1b0
[  257.152073]  [<ffffffff813b8720>] ? add_interrupt_randomness+0x50/0x1b0
[  257.152095]  [<ffffffffa0641d05>] ? packet_rcv+0x5/0x90 [pf_ring]
[  257.152115]  [<ffffffff813b8720>] ? add_interrupt_randomness+0x50/0x1b0
[  257.152138]  [<ffffffff810c8abd>] ? __getnstimeofday+0xd/0xd0
[  257.152158]  [<ffffffffa0641d51>] packet_rcv+0x51/0x90 [pf_ring]
[  257.152827]  [<ffffffff814fc220>] __netif_receive_skb_core+0x380/0x870
[  257.153483]  [<ffffffff814fc728>] __netif_receive_skb+0x18/0x60
[  257.154137]  [<ffffffff814fc7b0>] netif_receive_skb+0x40/0xd0
[  257.154790]  [<ffffffff814fd2c0>] napi_gro_receive+0x80/0xb0
[  257.155432]  [<ffffffffa00ffe2c>] ixgbe_clean_rx_irq+0x7ac/0xb30 [ixgbe]
[  257.156062]  [<ffffffffa010107b>] ixgbe_poll+0x4bb/0x930 [ixgbe]
[  257.156688]  [<ffffffff812ddb10>] ? timerqueue_add+0x60/0xb0
[  257.157316]  [<ffffffff8109ad65>] ? enqueue_hrtimer+0x25/0x80
[  257.157927]  [<ffffffff814fcb72>] net_rx_action+0x152/0x240
[  257.158521]  [<ffffffff81077bf7>] __do_softirq+0xf7/0x290
[  257.159097]  [<ffffffff8161635c>] call_softirq+0x1c/0x30
[  257.159651]  [<ffffffff81015de5>] do_softirq+0x55/0x90
[  257.160182]  [<ffffffff81077f95>] irq_exit+0x115/0x120
[  257.160694]  [<ffffffff81616ef8>] do_IRQ+0x58/0xf0
[  257.161194]  [<ffffffff8160c0ed>] common_interrupt+0x6d/0x6d
[  257.161679]  <EOI>
[  257.161686]
[  257.162159]  [<ffffffff814aa6e2>] ? cpuidle_enter_state+0x52/0xc0
[  257.162634]  [<ffffffff814aa6d8>] ? cpuidle_enter_state+0x48/0xc0
[  257.163100]  [<ffffffff814aa815>] cpuidle_idle_call+0xc5/0x200
[  257.163560]  [<ffffffff8101d21e>] arch_cpu_idle+0xe/0x30
[  257.164019]  [<ffffffff810c6955>] cpu_startup_entry+0xf5/0x290
[  257.164481]  [<ffffffff810423ca>] start_secondary+0x1ba/0x230
[  257.164936] Code: c6 70 86 1c 81 e8 b0 b4 f4 ff 5b 5d c3 66 66 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 48 89 e5 53 48 89 fb 48 8b 7f 70 <f0> ff 0f 0f 94 c2 84 d2 74 05 e8 f0 59 ed ff 48 8b 3d 89 01 86
[  257.165984] RIP  [<ffffffff811c8681>] file_free_rcu+0x11/0x40
[  257.166472]  RSP <ffff88203ec036f0>
[  257.166947] CR2: 000000000000000e

**Comment by cardigliano** [comment]
Fixed, please update from dev

**Comment by lmangani** [comment]
Closing as resolved, re-open if needed.
