### ISSUE TITLE
PF_RING and netmap clash over ax25_ptr - causing a kernel OOPS

### ISSUE THREAD

**Issue by oc-ja** [ntop/PF_RING#280]
Hello,

while playing around with different raw packet frameworks, I came across a bug, which caused a kernel OOPS for me (see [here](https://github.com/luigirizzo/netmap/issues/389)).
It turns out, that PF_RING and netmap use the same `ax25_ptr` pointer on net_device. Obviously leading to all sorts of problems in both directions.

I think it would be a good idea to add a check around [here](https://github.com/ntop/PF_RING/blob/dev/kernel/pf_ring.c#L7864), if the pointer looks in use, like you already do at unregistering:
```
      hook = (struct pfring_hooks *) dev->pfring_ptr;
      if(hook && (hook->magic == PF_RING)) {
	remove_device_from_ring_list(dev);
	dev->pfring_ptr = NULL;
      }
```

Thank you!

**Comment by cardigliano** [comment]
This should fix it https://github.com/ntop/PF_RING/commit/7ff4a49da1787fb514e2b91d7074626843bee923
