### ISSUE TITLE
kernel panic in ubuntu 14.04 

### ISSUE THREAD

**Issue by JeremyAshton-shopify** [ntop/PF_RING#281]
It would appear we are still seeing the problem as reported in: https://github.com/ntop/PF_RING/issues/277

Console output from module insertion:
 * Starting NTP server ntpd                                              [ OK ]
 * Starting MD monitoring service mdadm --monitor                        [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
 * Stopping configure network device                                     [ OK ]
 * Stopping configure network device security                            [ OK ]
[   31.627842] BUG: unable to handle kernel [   31.628839] i40e 0000:02:00.0 cap0: renamed from eth2

[   31.637025] NULL pointer dereference at 0000000000000058
[   31.643123] IP: [<ffffffffc05c9676>] i40e_vsi_reset_stats+0x196/0x410 [i40e_zc]
[   31.650771] PGD 0
[   31.653092] Oops: 0002 [#1] SMP
[   31.656623] Modules linked in: i40e_zc(OE+) configfs uio pf_ring(OE) 8021q garp mrp stp llc bonding ipmi_ssif intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ast ablk_helper cryptd ttm drm_kms_helper drm i2c_algo_bit fb_sys_fops syscopyarea input_leds sysfillrect joydev sysimgblt sb_edac edac_core mei_me mei shpchp ioatdma lpc_ich wmi ipmi_si 8250_fintek ipmi_msghandler acpi_power_meter mac_hid xfs lp parport raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor ixgbe dca vxlan ip6_udp_tunnel udp_tunnel ses enclosure raid6_pq hid_generic libcrc32c usbhid raid1 hid raid0 ahci ptp multipath libahci megaraid_sas mdio pps_core linear fjes [last unloaded: i40e]
[   31.732265] CPU: 8 PID: 3616 Comm: modprobe Tainted: G           OE   4.4.0-97-generic #120~14.04.1-Ubuntu
[   31.742348] Hardware name: Supermicro SSG-6048R-E1CR36H/X10DRH-iT, BIOS 1.1 05/15/2015
[   31.750703] task: ffff883f614fc600 ti: ffff883f63a34000 task.ti: ffff883f63a34000
[   31.758637] RIP: 0010:[<ffffffffc05c9676>]  [<ffffffffc05c9676>] i40e_vsi_reset_stats+0x196/0x410 [i40e_zc]
[   31.768882] RSP: 0018:ffff883f63a377c8  EFLAGS: 00010206
[   31.774684] RAX: 0000000000000002 RBX: ffff887f62cec000 RCX: 0000000000000000
[   31.782315] RDX: ffff887f632c6000 RSI: 0000000000000003 RDI: ffff887f6327acc0
[   31.789960] RBP: ffff883f63a377c8 R08: 0000000000000001 R09: 0000000000000098
[   31.797615] R10: 0000000000000001 R11: 0000000000000014 R12: ffff887f62cec000
[   31.805275] R13: ffff887f632c6000 R14: ffff887f62cec000 R15: ffff887f632c6220
[   31.812947] FS:  00007f2c68e3b740(0000) GS:ffff883f7fc00000(0000) knlGS:0000000000000000
[   31.821594] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   31.827909] CR2: 0000000000000058 CR3: 0000003f62112000 CR4: 00000000001406e0
[   31.835778] Stack:
[   31.838564]  ffff883f63a37858 ffffffffc05d1a50 0000000062cec008 ffff883f63a377f4
[   31.846826]  ffff000000000001 bc7ac40cffffffff ffff887f6547909c ffff883f63a37858
[   31.855112]  ffffffffc05e0d04 0000000002052003 0000000000000000 0000000000010001
[   31.863412] Call Trace:
[   31.866709]  [<ffffffffc05d1a50>] i40e_vsi_setup+0x500/0x890 [i40e_zc]
[   31.874104]  [<ffffffffc05e0d04>] ? i40e_aq_set_switch_config+0x84/0xb0 [i40e_zc]
[   31.882465]  [<ffffffffc05d25c1>] i40e_setup_pf_switch+0x481/0x580 [i40e_zc]
[   31.890404]  [<ffffffffc05d5b9d>] i40e_probe.part.86+0xd8d/0x1930 [i40e_zc]
[   31.898271]  [<ffffffff810d59a7>] ? irq_to_desc+0x17/0x20
[   31.904584]  [<ffffffff813e500d>] ? radix_tree_lookup+0xd/0x10
[   31.911335]  [<ffffffff810d59a7>] ? irq_to_desc+0x17/0x20
[   31.917664]  [<ffffffff810d95fe>] ? irq_get_irq_data+0xe/0x20
[   31.924341]  [<ffffffff81055710>] ? mp_map_pin_to_irq+0xb0/0x310
[   31.931293]  [<ffffffff81055f71>] ? mp_map_gsi_to_irq+0xa1/0xc0
[   31.938160]  [<ffffffff8104d490>] ? acpi_register_gsi_ioapic+0xb0/0x150
[   31.945734]  [<ffffffff816e435a>] ? pci_conf1_read+0xba/0x100
[   31.952443]  [<ffffffff816e7a33>] ? raw_pci_read+0x23/0x40
[   31.958903]  [<ffffffff81424f9e>] ? pci_bus_read_config_word+0x7e/0x90
[   31.966413]  [<ffffffff8142d112>] ? do_pci_enable_device+0xc2/0xf0
[   31.973592]  [<ffffffffc05d675e>] i40e_probe+0x1e/0x30 [i40e_zc]
[   31.980601]  [<ffffffff8142fc35>] local_pci_probe+0x45/0xa0
[   31.987161]  [<ffffffff814310e1>] pci_device_probe+0xe1/0x130
[   31.993883]  [<ffffffff8153d79b>] driver_probe_device+0x21b/0x470
[   32.000948]  [<ffffffff8153da75>] __driver_attach+0x85/0x90
[   32.007480]  [<ffffffff8153d9f0>] ? driver_probe_device+0x470/0x470
[   32.014693]  [<ffffffff8153b63d>] bus_for_each_dev+0x5d/0x90
[   32.021308]  [<ffffffff8153d12e>] driver_attach+0x1e/0x20
[   32.027640]  [<ffffffff8153cc90>] bus_add_driver+0x1d0/0x290
[   32.034214]  [<ffffffffc041f228>] ? trace_event_define_fields_i40e_xmit_template+0x96/0x96 [i40e_zc]
[   32.044244]  [<ffffffff8153e470>] driver_register+0x60/0xe0
[   32.050692]  [<ffffffff8142f5ec>] __pci_register_driver+0x4c/0x50
[   32.057650]  [<ffffffffc041f2d1>] i40e_init_module+0xa9/0xdd8 [i40e_zc]
[   32.065101]  [<ffffffff8100213d>] do_one_initcall+0xcd/0x1f0
[   32.071576]  [<ffffffff811dfb9d>] ? kmem_cache_alloc_trace+0x1ad/0x220
[   32.078909]  [<ffffffff81184354>] ? do_init_module+0x27/0x1d2
[   32.085439]  [<ffffffff8118438d>] do_init_module+0x60/0x1d2
[   32.091791]  [<ffffffff81104344>] load_module+0x1424/0x1b10
[   32.098111]  [<ffffffff81100b30>] ? __symbol_put+0x40/0x40
[   32.104337]  [<ffffffff81207d31>] ? kernel_read+0x41/0x60
[   32.110463]  [<ffffffff81104bfe>] SYSC_finit_module+0x7e/0xa0
[   32.116929]  [<ffffffff81104c3e>] SyS_finit_module+0xe/0x10
[   32.123224]  [<ffffffff8180f4f6>] entry_SYSCALL_64_fastpath+0x16/0x75
[   32.130378] Code: 39 00 0f 84 cf 00 00 00 66 83 ba d6 0c 00 00 00 0f 84 c1 00 00 00 31 f6 eb 07 48 8b 8a 80 0c 00 00 48 63 c6 83 c6 01 48 8b 0c c1 <48> c7 41 58 00 00 00 00 48 c7 41 60 00 00 00 00 48 8b 8a 80 0c
[   32.151786] RIP  [<ffffffffc05c9676>] i40e_vsi_reset_stats+0x196/0x410 [i40e_zc]
[   32.159948]  RSP <ffff883f63a377c8>
[   32.164185] CR2: 0000000000000058
[   32.168255] ---[ end trace a5a9020776b42ac6 ]---
/etc/rc2.d/S30pf_ring: line 220:  3616 Killed                  /sbin/modprobe ${1}_${2} ${DRV_PARAM}
Error loading driver i40e-zc
Uninstalling old i40e-zc version
[   32.206193] systemd-udevd[3431]: renamed network interface eth2 to cap0
 * Starting configure network device security                            [ OK ]
 * Starting configure network device                                     [ OK ]
[   35.515483] systemd-hostnamed[4158]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!
Compiling new i40e-zc driver
Installing new i40e-zc driver

**Comment by cardigliano** [comment]
Reopened https://github.com/ntop/PF_RING/issues/277 (closing this)
