### ISSUE TITLE
Error Installing pfring-7.0.0-1535.x86_64                    

### ISSUE THREAD

**Issue by flaviopace** [ntop/PF_RING#282]
Installazione     : pfring-7.0.0-1535.x86_64                                                                                                              3/7
Starting pf_ring (via systemctl):  Job for **pf_ring.service failed** because the control process exited with error code. See "systemctl status pf_ring.service" and "journalctl -xe" for details.

Where : systemctl status pf_ring.service
● pf_ring.service - Start/stop pfring service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since sab 2017-11-04 14:46:52 UTC; 1min 36s ago

nov 04 14:46:52 pf_ring[3708]: /lib/modules/4.10.17-3-pve/build or /lib/modules/4.10.17-3-pve/source.
nov 04 14:46:52 pf_ring[3708]: **Installing new pfring driver**
nov 04 14:46:52 pf_ring[3708]: Error! echo
nov 04 14:46:52 pf_ring[3708]: Your kernel headers for kernel 4.10.17-3-pve cannot be found at
nov 04 14:46:52 pf_ring[3708]: /lib/modules/4.10.17-3-pve/build or /lib/modules/4.10.17-3-pve/source.
nov 04 14:46:52  pf_ring[3708]: Unable to load PF_RING. Exiting[FAILED]
nov 04 14:46:52  systemd[1]: pf_ring.service: control process exited, code=exited status=99
nov 04 14:46:52  systemd[1]: Failed to start Start/stop pfring service.
nov 04 14:46:52  systemd[1]: Unit pf_ring.service entered failed state.
nov 04 14:46:52 systemd[1]: pf_ring.service failed.

Installed:
  cento.x86_64 0:1.2.171102-97  n2disk.x86_64 0:2.8.171102-4825  nprobe.x86_64 0:8.0.171102-5797  ntopng.x86_64 0:3.0.171102-2920  pfring.x86_64 0:7.0.0-1535

Dependency installed:
  pfring-dkms.noarch 0:7.0.0-1535                                                  redis.x86_64 0:3.2.10-2.el7

I'm trying to install ntopng  on my CentOS Linux release 7.4.1708 following instruction palce here: 
http://packages.ntop.org/centos-stable/

Can you help me to better understand root cause ?

**Comment by cardigliano** [comment]
@flaviopace you get this error because pf_ring is not able to find kernel headers, it seems you are running a non standard kernel, please try installing kernel headers or use a plain centos installation

**Comment by flaviopace** [comment]
@cardigliano thanks for your response. Yes I do not have a standard kernel:
uname -a
Linux 4.10.17-3-pve #1 SMP PVE 4.10.17-23 (Tue, 19 Sep 2017 09:43:50 +0200) x86_64 x86_64 x86_64 GNU/Linux

but I already had installed the kernel-headers-3.10.0-693.5.2.el7.x86_64 on my **VPS**

Do you have other ideas ?

**Comment by cardigliano** [comment]
@flaviopace you need kernel headers for the kernel you are running (4.10.17-3-pve)

**Comment by flaviopace** [comment]
@cardigliano you are right. My VPS Kernel version and kernel headers are different. 
I will compile it by myself. Thanks
