### ISSUE TITLE
zbalance_ipc and zcount only drop RSS 0 stream packets

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#283]
Hi, I use PF_RING 6.4.1 in Ubuntu 14.04.3
NIC:
>  Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

set two recv stream with: 
> ethtool -L p3p1 combined 2

set max recv ring buf:
> root@localhost:~# ethtool -g p3p1
> Ring parameters for p3p1:
> Pre-set maximums:
> RX:		32768
> RX Mini:	0
> RX Jumbo:	0
> TX:		32768
> Current hardware settings:
> RX:		32768
> RX Mini:	0
> RX Jumbo:	0
> TX:		32768

start zbalance_ipc with:
> zbalance_ipc -i zc:p3p1@0,zc:p3p1@1 -c 98 -n 4 -q 131072 -b 1024 -m 2 -g 0 -p

the follow log show only drop packet recv from zc:p3p1@0, also test "zcount -i zc:p3p1@0" drop and "zcount -i zc:p3p1@1" not drop
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:195] ClusterId:         98
> TotQueues:         4
> Applications:      1
> App0Queues:        4
> Duration:          0:00:01:40:001
> Packets:           125105032
> Forwarded:         524280
> Processed:         0
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:205]                 zc:p3p1@0 RX 62709405 pkts Dropped 2261840 pkts (3.5 %)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:205]                 zc:p3p1@1 RX 62395627 pkts Dropped 0 pkts (0.0 %)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:219]                 Q 0 RX 0 pkts Dropped 124973986 pkts (0.0 %)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:219]                 Q 1 RX 0 pkts Dropped 124974009 pkts (0.0 %)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:219]                 Q 2 RX 0 pkts Dropped 124974009 pkts (0.0 %)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:219]                 Q 3 RX 0 pkts Dropped 124974009 pkts (0.0 %)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:238] Actual Stats: Recv 1'116'621.37 pps (35'873.11 drops) - Forwarded 0.00 pps (4'466'485.49 drops)
> 06/Nov/2017 12:06:43 [zbalance_ipc.c:248] =========================

**Comment by cardigliano** [comment]
@laoyang103 please configure a single RSS queue when using zbalance_ipc, as you usually get worse performance capturing and aggregating traffic from multiple queues rather than just capturing from a single queue.

**Comment by laoyang103** [comment]
@cardigliano 
the same result, please note I use zcount only capture zc:p3p1@0 and also drop packets

> 06/Nov/2017 16:13:22 [ipmipc.c:195] ClusterId:         98
> TotQueues:         4
> Applications:      1
> App0Queues:        4
> Duration:          0:00:00:10:000
> Packets:           22862264
> Forwarded:         524280
> Processed:         0
> 06/Nov/2017 16:13:22 [ipmipc.c:205]                 zc:p3p1 RX 22862384 pkts Dropped 188619 pkts (0.8 %)
> 06/Nov/2017 16:13:22 [ipmipc.c:219]                 Q 0 RX 0 pkts Dropped 22731314 pkts (0.0 %)
> 06/Nov/2017 16:13:22 [ipmipc.c:219]                 Q 1 RX 0 pkts Dropped 22731314 pkts (0.0 %)
> 06/Nov/2017 16:13:22 [ipmipc.c:219]                 Q 2 RX 0 pkts Dropped 22731314 pkts (0.0 %)
> 06/Nov/2017 16:13:22 [ipmipc.c:219]                 Q 3 RX 0 pkts Dropped 22731356 pkts (0.0 %)
> 06/Nov/2017 16:13:22 [ipmipc.c:238] Actual Stats: Recv 1'145'397.88 pps (7'047.97 drops) - Forwarded 0.00 pps (4'581'591.53 drops)
> 06/Nov/2017 16:13:22 [ipmipc.c:248] =========================

**Comment by cardigliano** [comment]
Please provide some output from zcount

**Comment by laoyang103** [comment]
@cardigliano 

> root@localhost:/usr/local/driver# zcount -i zc:p3p1 -c 98
> =========================
> Absolute Stats: 1'132'089 pkts (20'910 drops) - 253'421'405 bytes
> =========================
> 
> =========================
> Absolute Stats: 2'284'722 pkts (20'910 drops) - 522'361'390 bytes
> Actual Stats: 1'152'511.98 pps (0.00 drops) - 2.15 Gbps
> =========================
> 
> =========================
> Absolute Stats: 3'427'708 pkts (30'079 drops) - 784'759'588 bytes
> Actual Stats: 1'142'802.00 pps (9'167.52 drops) - 2.10 Gbps
> =========================
> 
> =========================
> Absolute Stats: 4'557'326 pkts (53'520 drops) - 1'040'312'956 bytes
> Actual Stats: 1'129'512.95 pps (23'438.82 drops) - 2.04 Gbps
> =========================
> 
> =========================
> Absolute Stats: 5'708'124 pkts (55'015 drops) - 1'302'451'832 bytes
> Actual Stats: 1'150'700.19 pps (1'494.87 drops) - 2.10 Gbps
> =========================
> 
> ^CLeaving...
> =========================
> Absolute Stats: 6'691'897 pkts (56'163 drops) - 1'531'694'591 bytes
> Actual Stats: 1'147'590.37 pps (1'339.16 drops) - 2.14 Gbps
> =========================
> 
> =========================
> Absolute Stats: 6'691'897 pkts (56'163 drops) - 1'531'694'591 bytes
> Actual Stats: 0.00 pps (0.00 drops) - 0.00 Gbps
> =========================

**Comment by cardigliano** [comment]
@laoyang103 please set the zcount affinity (with -g 1 for instance) and make sure there is no other process running on the same core, it's strange zcount is loosing traffic at that rate.
Btw, what is the cpu model? Please also provide ram informations (installed modules and speed)

**Comment by laoyang103** [comment]
@cardigliano 

I have set  zcount affinity with -g 1, also lost packet. I make sure no other process running on the same core. the packet lossing rate also less than %1
BTW, I want to know how to reopen a issue.

CPU:

> processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
stepping	: 3
microcode	: 0x1d
cpu MHz		: 1199.296
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bugs		:
bogomips	: 6784.69
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

TOP:

> top - 14:26:11 up 20:34,  7 users,  load average: 0.21, 1.22, 3.07
Tasks: 172 total,   2 running, 170 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni, 94.2 id,  0.0 wa,  0.0 hi,  5.8 si,  0.0 st
%Cpu1  :  0.0 us,  1.0 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  1.0 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  1.0 us,  0.0 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  2.0 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  1.0 us,  1.0 sy,  0.0 ni, 98.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.0 us,  1.0 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  32672364 total, 31138464 used,  1533900 free,   166704 buffers
KiB Swap: 62498812 total,        4 used, 62498808 free. 21484592 cached Mem

Memory:

> root@iPilot-APM:~# dmidecode|grep "System Information" -A9|egrep  "Manufacturer|Product|Serial"
	Manufacturer: Intel Corporation
	Product Name: S1200RP
	Serial Number: ............
root@iPilot-APM:~# dmidecode|grep -A5 "Memory Device"|grep Size|grep -v Range
	Size: 8192 MB
	Size: 8192 MB
	Size: 8192 MB
	Size: 8192 MB
root@iPilot-APM:~# dmidecode|grep -A16 "Memory Device"|grep 'Speed'
	Speed: 1600 MHz
	Speed: 1600 MHz
	Speed: 1600 MHz
	Speed: 1600 MHz
root@iPilot-APM:~# dmidecode -t memory
Handle 0x0042, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: Single-bit ECC
	Maximum Capacity: 32 GB
	Error Information Handle: Not Provided
	Number Of Devices: 4
Handle 0x0044, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x0042
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: 8192 MB
	Form Factor: DIMM
	Set: None
	Locator: ChannelA-DIMM1
	Bank Locator: BANK 1
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1600 MHz
	Manufacturer: Samsung
	Serial Number: 21463317
	Asset Tag: 9876543210
	Part Number: M391B1G73QH0-YK0  
	Rank: 2
	Configured Clock Speed: 1600 MHz

**Comment by laoyang103** [comment]
reopening

**Comment by laoyang103** [comment]
#reopening

**Comment by laoyang103** [comment]
@cardigliano 
I misoperation closed this issue, please have a see

**Comment by cardigliano** [comment]
@laoyang103 you hw configuration looks good, could you try adding also -a to zcount?

**Comment by laoyang103** [comment]
@cardigliano 

also drop less than %1 with -a.
I can provide ssh remote operation this machine, send to your email.

**Comment by cardigliano** [comment]
@laoyang103 please send the output of top (press 1) or htop while zcount is running

**Comment by laoyang103** [comment]
@cardigliano 

ipmcnt -i zc:p3p1 -a -g 1

> Tasks: 164 total,   1 running, 163 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.7 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.3 us,  0.0 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.3 us,  0.3 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  32672364 total, 29638892 used,  3033472 free,   288652 buffers
KiB Swap: 62499836 total,        4 used, 62499832 free. 20266496 cached Mem
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                             
14745 root      20   0  150540   4892   1900 S 100.1  0.0   0:33.84 ipmcnt                                              
 1017 daemon    20   0  516604  10876   7868 S   0.3  0.0   2:03.89 CodeMeterLin                                        
 1671 root      20   0 16.616g 0.987g  10984 S   0.3  3.2 150:00.63 java                                                
 4818 root      20   0       0      0      0 S   0.3  0.0   0:06.84 kworker/0:0      

zcount print
> =========================
Absolute Stats: 165'091'184 pkts (185'725 drops) - 37'872'117'134 bytes
Actual Stats: 1'141'106.55 pps (6'478.52 drops) - 2.04 Gbps
=========================

**Comment by cardigliano** [comment]
It's strange you are getting those performance with a 82599, please also provide "dmesg | grep PCIe"

**Comment by laoyang103** [comment]
@cardigliano 

> root@iPilot-APM:/data/kpi# dmesg | grep PCIe
[    0.209990] ACPI FADT declares the system doesn't support PCIe ASPM, so disable it
[    2.821891] igb 0000:02:00.0: eth0: (PCIe:5.0Gb/s:Width x4) 2c:53:4a:00:26:26
[    2.967386] igb 0000:02:00.1: eth1: (PCIe:5.0Gb/s:Width x4) 2c:53:4a:00:26:27
[    3.047690] igb 0000:05:00.0: eth2: (PCIe:2.5Gb/s:Width x1) 00:1e:67:fc:ed:4b
[    3.126009] igb 0000:06:00.0: eth3: (PCIe:2.5Gb/s:Width x1) 00:1e:67:fc:ed:4c
[   10.695371] igb 0000:02:00.0: eth0: (PCIe:5.0GT/s:Width x4) 
[   10.799378] igb 0000:02:00.1: eth0: (PCIe:5.0GT/s:Width x4) 
[   10.892743] igb 0000:05:00.0: eth0: (PCIe:2.5GT/s:Width x1) 
[   11.739632] igb 0000:06:00.0: eth0: (PCIe:2.5GT/s:Width x1)

**Comment by cardigliano** [comment]
I do not see the p3p1 interface, it should be an ixgbe (82599)

**Comment by laoyang103** [comment]
@cardigliano 

this is dmesg | grep ixgbe output. dmesg | grep PCIe really can not see ixgbe

> root@iPilot-APM:/data/kpi# dmesg | grep ixgbe
[    2.812275] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver - version 4.0.1-k
[    3.317895] ixgbe: Copyright (c) 1999-2014 Intel Corporation.
[    3.595409] ixgbe 0000:07:00.0: Multiqueue Enabled: Rx Queue count = 8, Tx Queue count = 8
[    3.604836] ixgbe 0000:07:00.0: PCI Express bandwidth of 4GT/s available
[    3.613859] ixgbe 0000:07:00.0: (Speed:5.0GT/s, Width: x1, Encoding Loss:20%)
[    3.622626] ixgbe 0000:07:00.0: This is not sufficient for optimal performance of this card.
[    3.631513] ixgbe 0000:07:00.0: For optimal performance, at least 20GT/s of bandwidth is required.
[    3.640484] ixgbe 0000:07:00.0: A slot with more lanes and/or higher speed is suggested.
[    3.649615] ixgbe 0000:07:00.0: MAC: 2, PHY: 18, SFP+: 5, PBA No: Unknown
[    3.658665] ixgbe 0000:07:00.0: 90:e2:ba:90:1c:e4
[    3.679835] ixgbe 0000:07:00.0: Intel(R) 10 Gigabit Network Connection
[    3.867574] ixgbe 0000:07:00.1: Multiqueue Enabled: Rx Queue count = 8, Tx Queue count = 8
[    3.876993] ixgbe 0000:07:00.1: PCI Express bandwidth of 4GT/s available
[    3.886220] ixgbe 0000:07:00.1: (Speed:5.0GT/s, Width: x1, Encoding Loss:20%)
[    3.895469] ixgbe 0000:07:00.1: This is not sufficient for optimal performance of this card.
[    3.904830] ixgbe 0000:07:00.1: For optimal performance, at least 20GT/s of bandwidth is required.
[    3.914300] ixgbe 0000:07:00.1: A slot with more lanes and/or higher speed is suggested.
[    3.923906] ixgbe 0000:07:00.1: MAC: 2, PHY: 18, SFP+: 6, PBA No: Unknown
[    3.933306] ixgbe 0000:07:00.1: 90:e2:ba:90:1c:e5
[    3.944180] ixgbe 0000:07:00.1: Intel(R) 10 Gigabit Network Connection
[    3.956531] ixgbe 0000:07:00.0 p3p1: renamed from eth0
[    3.994149] ixgbe 0000:07:00.1 p3p2: renamed from eth1
[   10.230816] ixgbe 0000:07:00.1: complete
[   10.254812] ixgbe 0000:07:00.0: complete
[   11.789129] ixgbe: Receive-Side Scaling (RSS) set to 1
[   11.789130] ixgbe: 0000:07:00.0: ixgbe_check_options: FCoE Offload feature enabled
[   11.927798] ixgbe 0000:07:00.0: FCoE offload feature is not available. Disabling FCoE offload feature
[   11.952903] ixgbe 0000:07:00.0: PCI Express bandwidth of 4GT/s available
[   11.952905] ixgbe 0000:07:00.0: (Speed:5.0GT/s, Width: x1, Encoding Loss:20%)
[   11.952906] ixgbe 0000:07:00.0: This is not sufficient for optimal performance of this card.
[   11.952907] ixgbe 0000:07:00.0: For optimal performance, at least 20GT/s of bandwidth is required.
[   11.952908] ixgbe 0000:07:00.0: A slot with more lanes and/or higher speed is suggested.
[   11.953026] ixgbe 0000:07:00.0 eth0: MAC: 2, PHY: 18, SFP+: 5, PBA No: Unknown
[   11.953027] ixgbe 0000:07:00.0: 90:e2:ba:90:1c:e4
[   11.953029] ixgbe 0000:07:00.0 eth0: Enabled Features: RxQ: 1 TxQ: 1 LRO 
[   11.953060] ixgbe 0000:07:00.0 eth0: Intel(R) 10 Gigabit Network Connection
[   11.953202] ixgbe: Receive-Side Scaling (RSS) set to 1
[   11.953204] ixgbe: 0000:07:00.1: ixgbe_check_options: FCoE Offload feature enabled
[   11.955320] ixgbe 0000:07:00.0 p3p1: renamed from eth0
[   12.107860] ixgbe 0000:07:00.1: FCoE offload feature is not available. Disabling FCoE offload feature
[   12.133150] ixgbe 0000:07:00.1: PCI Express bandwidth of 4GT/s available
[   12.133152] ixgbe 0000:07:00.1: (Speed:5.0GT/s, Width: x1, Encoding Loss:20%)
[   12.133153] ixgbe 0000:07:00.1: This is not sufficient for optimal performance of this card.
[   12.133154] ixgbe 0000:07:00.1: For optimal performance, at least 20GT/s of bandwidth is required.
[   12.133154] ixgbe 0000:07:00.1: A slot with more lanes and/or higher speed is suggested.
[   12.133273] ixgbe 0000:07:00.1 eth0: MAC: 2, PHY: 18, SFP+: 6, PBA No: Unknown
[   12.133274] ixgbe 0000:07:00.1: 90:e2:ba:90:1c:e5
[   12.133275] ixgbe 0000:07:00.1 eth0: Enabled Features: RxQ: 1 TxQ: 1 LRO 
[   12.133307] ixgbe 0000:07:00.1 eth0: Intel(R) 10 Gigabit Network Connection
[   12.134486] ixgbe 0000:07:00.1 p3p2: renamed from eth0
[   13.195328] ixgbe 0000:07:00.0: registered PHC device on p3p1
[   13.364376] ixgbe 0000:07:00.0 p3p1: detected SFP+: 5
[   13.824262] ixgbe 0000:07:00.0 p3p1: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[   15.139596] ixgbe 0000:07:00.1: registered PHC device on p3p2
[   15.193233] ixgbe 0000:07:00.0 p3p1: detected SFP+: 5
[   15.444974] ixgbe 0000:07:00.0 p3p1: NIC Link is Up 10 Gbps, Flow Control: RX
[   15.507510] ixgbe 0000:07:00.1 p3p2: detected SFP+: 6
[   17.896589] ixgbe 0000:07:00.1 p3p2: detected SFP+: 6

**Comment by cardigliano** [comment]
This is why you are getting bad performance, you are using a x1 PCIe slot, please move the card to another slot with more PCIe lanes:
[ 3.876993] ixgbe 0000:07:00.1: PCI Express bandwidth of 4GT/s available
[ 3.886220] ixgbe 0000:07:00.1: (Speed:5.0GT/s, Width: x1, Encoding Loss:20%)

**Comment by laoyang103** [comment]
OK, Thank you very much. I will try it
