### ISSUE TITLE
e1000e zc driver drop packet

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#284]
HI, Cardigliano 

I use PF_RING 6.4.1 with Intel Corporation 82574L Gigabit Network Connection NIC, driver is e1000e.

> root@PTCS-OS:~# ethtool -i p6p1
driver: e1000e
version: 3.2.7.1-NAPI
firmware-version: 2.1-3
bus-info: 0000:09:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

first I use the follow command, and no packet drop. but I see ksoftirqd/0 in top, and it use cpu %20-%30, why  can see it in top?

> ./zbalance_ipc -i zc:p6p1 -m 2 -n 3 -q 65530 -b 1600 -g 0 -S 1 -p
./zcount_ipc -i 0 -c 98 -g 2
./zcount_ipc -i 1 -c 98 -g 3
./zcount_ipc -i 2 -c 98 -g 4

second I run my application replace zcount_ipc, I see have packet lost also less than %1 and ksoftirqd/0 use cpu %40-%60.

> 10/Nov/2017 17:38:19 [ipmipc.c:196] ClusterId:         98
TotQueues:         3
Applications:      1
App0Queues:        3
Duration:          0:00:21:00:040
Packets:           261294201
Forwarded:         532300209
Processed:         532300205
10/Nov/2017 17:38:19 [ipmipc.c:206]                 zc:p6p1 RX 261294201 pkts Dropped 1278954 pkts (0.5 %)
10/Nov/2017 17:38:19 [ipmipc.c:220]                 Q 0 RX 260849353 pkts Dropped 444848 pkts (0.2 %)
10/Nov/2017 17:38:19 [ipmipc.c:220]                 Q 1 RX 260647157 pkts Dropped 647044 pkts (0.2 %)
10/Nov/2017 17:38:19 [ipmipc.c:220]                 Q 2 RX 10803699 pkts Dropped 0 pkts (0.0 %)
10/Nov/2017 17:38:19 [ipmipc.c:239] Actual Stats: Recv 206'883.49 pps (0.00 drops) - Forwarded 423'525.00 pps (0.00 drops)
10/Nov/2017 17:38:19 [ipmipc.c:249] =========================

I know the causes of packet loss packet is replace zcount_ip with my application, but use igb zc driver have no packet lost and no ksoftirqd/0 in top. so I think packet loss is related to network card and application process performance.

At this time zbalance_ipc cpu use %60, in igb zc only use %10.
igb machine CPU: 

> Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz

e1000e machine CPU:

> Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz

How can I solve it, adjust some parameters in driver or zbalance_ipc?

**Comment by cardigliano** [comment]
@laoyang103, e1000e interfaces are usually slower than igb (in our tests we've seen they are not able to do 1.48Mpps even with ZC drivers), they have a different architecture, with less buffering power. This can also explain the cpu load.

**Comment by laoyang103** [comment]
@cardigliano.
can I adjust some parameters to improve performance, for example zbalance_ipc -q and -b, but this two param seem does not work for improve performance

**Comment by cardigliano** [comment]
@laoyang103 if the bottleneck is on the capture side, increasing the application queue length does improve the performance

**Comment by laoyang103** [comment]
@cardigliano OK, thanks for your help, my bottleneck is on the application side.
