### ISSUE TITLE
Having trouble with using PF_RING ZC under Hyper-V

### ISSUE THREAD

**Issue by mrnerdhair** [ntop/PF_RING#285]
I've been struggling for a few days trying to get the igb-zc driver to handle an i350 card exposed to a Hyper-V VM using PCI passthrough (of the Physical Function, not to be confused with SR-IOV, where you pass through a Virtual Function and have to use the igbvf driver instead).

However, whenever I `rmmod igb` and `modprobe igb-zc`, I get a kernel oops and it no worky.

Any ideas?

> Nov 10 16:18:15 sd-sriov kernel: Intel(R) Gigabit Ethernet Network Driver - version 5.3.3.5
> Nov 10 16:18:15 sd-sriov kernel: Copyright (c) 2007-2015 Intel Corporation.
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: can't derive routing for PCI INT A
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: PCI INT A: no GSI
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: added PHC on eth1
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: Intel(R) Gigabit Ethernet Network Connection
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: eth1: (PCIe:5.0GT/s:Width x4)
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0 eth1: MAC: e0:4f:43:07:44:f0
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: eth1: PBA No: 106900-000
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: LRO is disabled
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0: Using MSI-X interrupts. 1 rx queue(s), 1 tx queue(s)
> Nov 10 16:18:15 sd-sriov kernel: igb 4ffd:00:00.0 hvpci13: renamed from eth1
> Nov 10 16:18:15 sd-sriov systemd[1]: Started ifup for hvpci13.
> Nov 10 16:18:15 sd-sriov systemd[1]: Found device I350 Gigabit Network Connection.
> Nov 10 16:18:16 sd-sriov kernel: BUG: unable to handle kernel NULL pointer dereference at 0000000000000020
> Nov 10 16:18:16 sd-sriov kernel: IP: [<ffffffffc0093ee9>] skb_ring_handler+0x99/0x1f80 [pf_ring]
> Nov 10 16:18:16 sd-sriov kernel: PGD 86399067 PUD 345e7067 PMD 0
> Nov 10 16:18:16 sd-sriov kernel: Oops: 0000 [#1] SMP
> Nov 10 16:18:16 sd-sriov kernel: Modules linked in: igb_zc(OE) ip6table_filter ip6_tables xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack iptable_filter ip_tables x_tables ptp pps_core dca i2c_algo_bit crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd serio_raw pci_hyperv hyperv_fb hv_balloon joydev mac_hid igbvf pf_ring(OE) autofs4 hid_generic hid_hyperv hv_storvsc hv_netvsc scsi_transport_fc hid hv_utils hyperv_keyboard hv_vmbus [last unloaded: igb]
> Nov 10 16:18:16 sd-sriov kernel: CPU: 5 PID: 2008 Comm: ip Tainted: G           OE   4.4.0-81-generic #104-Ubuntu
> Nov 10 16:18:16 sd-sriov kernel: Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
> Nov 10 16:18:16 sd-sriov kernel: task: ffff88008623aa00 ti: ffff880033c1c000 task.ti: ffff880033c1c000
> Nov 10 16:18:16 sd-sriov kernel: RIP: 0010:[<ffffffffc0093ee9>]  [<ffffffffc0093ee9>] skb_ring_handler+0x99/0x1f80 [pf_ring]
> Nov 10 16:18:16 sd-sriov kernel: RSP: 0018:ffff880033c1f428  EFLAGS: 00010202
> Nov 10 16:18:16 sd-sriov kernel: RAX: 0000000000000008 RBX: 0000000033c1f6c8 RCX: ffff880007b18000
> Nov 10 16:18:16 sd-sriov kernel: RDX: ffff880033c1f6e0 RSI: 0000000000000000 RDI: 0000000000000000
> Nov 10 16:18:16 sd-sriov kernel: RBP: ffff880033c1f640 R08: ffff880007b10000 R09: 00000000f9080000
> Nov 10 16:18:16 sd-sriov kernel: R10: 0000000007b10000 R11: ffff880086071f50 R12: 0000000033c1f6e0
> Nov 10 16:18:16 sd-sriov kernel: R13: 0000000000000000 R14: ffff880270004b01 R15: 0000000000000001
> Nov 10 16:18:16 sd-sriov kernel: FS:  00007f55d9115700(0000) GS:ffff880279b40000(0000) knlGS:0000000000000000
> Nov 10 16:18:16 sd-sriov kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> Nov 10 16:18:16 sd-sriov kernel: CR2: 0000000000000020 CR3: 00000000f7409000 CR4: 00000000003406e0
> Nov 10 16:18:16 sd-sriov kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
> Nov 10 16:18:16 sd-sriov kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
> Nov 10 16:18:16 sd-sriov kernel: Stack:
> Nov 10 16:18:16 sd-sriov kernel:  ffff880033c1f4f0 0000000000000046 ffff880287ffb6c0 00000000ffffffff
> Nov 10 16:18:16 sd-sriov kernel:  0000000079b4dc40 ffff88026fb70000 0000000002080020 ffff880287ffb6f0
> Nov 10 16:18:16 sd-sriov kernel:  ffff880279407700 ffff880279400e00 ffff880287ffb6c0 ffff880000000000
> Nov 10 16:18:16 sd-sriov kernel: Call Trace:
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff811991e9>] ? __alloc_pages_nodemask+0x159/0x2a0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8172685a>] ? __build_skb+0x2a/0xe0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc016325a>] ? _hv_pcifront_read_config+0xda/0x160 [pci_hyperv]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc01634f9>] ? hv_pcifront_read_config+0x59/0x70 [pci_hyperv]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc028d578>] igb_configure+0x608/0x7c0 [igb_zc]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc0282dd0>] ? ring_is_not_empty+0xc0/0xc0 [igb_zc]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc0285c00>] ? igb_clean_rx_ring+0xf0/0xf0 [igb_zc]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc028d7d9>] __igb_open+0xa9/0x5d0 [igb_zc]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffffc028de60>] igb_open+0x10/0x20 [igb_zc]
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81738ad8>] __dev_open+0xc8/0x140
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81738ded>] __dev_change_flags+0x9d/0x160
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81738ed9>] dev_change_flags+0x29/0x70
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81747823>] do_setlink+0x633/0xb80
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff811afe6c>] ? zone_statistics+0x7c/0xa0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff811991e9>] ? __alloc_pages_nodemask+0x159/0x2a0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81425de2>] ? nla_parse+0x32/0x100
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8174845a>] rtnl_newlink+0x5aa/0x8a0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff811991e9>] ? __alloc_pages_nodemask+0x159/0x2a0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81348200>] ? security_capset+0x80/0x80
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8108a8e8>] ? ns_capable_common+0x68/0x80
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8108a913>] ? ns_capable+0x13/0x20
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81746ad6>] rtnetlink_rcv_msg+0xe6/0x230
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff817216b7>] ? __alloc_skb+0x87/0x1f0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff817469f0>] ? rtnetlink_rcv+0x30/0x30
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81769764>] netlink_rcv_skb+0xa4/0xc0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff817469e8>] rtnetlink_rcv+0x28/0x30
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8176913a>] netlink_unicast+0x18a/0x240
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff817694eb>] netlink_sendmsg+0x2fb/0x3a0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8139fe21>] ? aa_sock_msg_perm+0x61/0x150
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81718ae8>] sock_sendmsg+0x38/0x50
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81719591>] ___sys_sendmsg+0x281/0x290
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81202c5b>] ? mem_cgroup_try_charge+0x6b/0x1e0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff8119ffd7>] ? lru_cache_add_active_or_unevictable+0x27/0xa0
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff811c1e93>] ? handle_mm_fault+0xcf3/0x1850
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81226b0e>] ? dput+0x1ee/0x220
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81211250>] ? __fput+0x190/0x220
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81719ee1>] __sys_sendmsg+0x51/0x90
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81719f32>] SyS_sendmsg+0x12/0x20
> Nov 10 16:18:16 sd-sriov kernel:  [<ffffffff81840a72>] entry_SYSCALL_64_fastpath+0x16/0x71
> Nov 10 16:18:16 sd-sriov kernel: Code: dd 01 00 00 84 d2 49 89 fd 41 89 d4 41 0f 95 c7 84 db 45 89 c2 41 0f 95 c6 45 84 ff 0f 84 e7 01 00 00 45 84 f6 0f 84 de 01 00 00 <48> 8b 47 20 0f b7 80 36 02 00 00 89 84 24 08 01 00 00 80 3d 6e
> Nov 10 16:18:16 sd-sriov kernel: RIP  [<ffffffffc0093ee9>] skb_ring_handler+0x99/0x1f80 [pf_ring]
> Nov 10 16:18:16 sd-sriov kernel:  RSP <ffff880033c1f428>
> Nov 10 16:18:16 sd-sriov kernel: CR2: 0000000000000020
> Nov 10 16:18:16 sd-sriov kernel: ---[ end trace 6670ee594f1f24c0 ]---

**Comment by cardigliano** [comment]
@reidrankin this seems to be due to a failure allocating memory for skbuffs, did you try increasing the physical memory available for this vm?

**Comment by mrnerdhair** [comment]
The VM has several GB of free memory at the time of failure, but it is
using Dynamic Memory, and I can imagine a conflict there.

I'll try switching that off (and throwing a few more GB to the VM for good
measure) on Monday and let you know what happens.

**Comment by cardigliano** [comment]
Any update on this?
