### ISSUE TITLE
pfring_zc_send_pkt error (rarely)

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#289]
http://www.silicom-usa.com/pr/server-adapters/networking-bypass-adapters/10-gigabit-ethernet-bypass-networking-server-adapters/pe310g4bpi9-bypass-adapter/
http://www.silicom-usa.com/pr/server-adapters/networking-bypass-adapters/10-gigabit-ethernet-bypass-networking-server-adapters/pe210g2bpi9-ethernet-bypass/

sudo modinfo pf_ring && sudo cat /proc/net/pf_ring/info

filename:       /lib/modules/3.16.0-4-amd64/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
depends:        
vermagic:       3.16.0-4-amd64 SMP mod_unload modversions 
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           transparent_mode:(deprecated) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)
PF_RING Version          : 6.4.1 (6.4.1-stable:db7bbc5160303d6f3a1985248455ac03a0a3298d)
Total rings              : 45

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

We use this NIC's on different servers. Problem the same
Some times, not always

turn on bypass (bpctl_util all set_bypass on)
Restart app with changes
turn off bypass (bpctl_util all set_bypass off)

Traffic go, all ok

After some time, I see debug messages in log

if ((rc = pfring_zc_send_pkt(queue[rss_queue_id], &pkt->buffer, 1)) < 0) {
	// message to syslog
}

app processing billions packets, but I see very rarely and very small count of these errors
and only for specific RSS queues

on NIC with 2 ports
We use 11 RSS queues (max possible 16)
Opened every queue for sending in both directions (RX and TX)

If these errors begins, then it's not stopped.
Some time I see log messages that pfring_zc_send_pkt fail.

It's very bad.

What I do?
I several times

turn on bypass (bpctl_util all set_bypass on)
Restart app with changes
turn off bypass (bpctl_util all set_bypass off)

and pray that I don't see errors
If errors don't started in first hour after bypass off then all ok and and they will not appear

Why it's happen?

**Comment by cardigliano** [comment]
@andyarus do you have multiple threads sharing the same interface/queue perhaps?
If I got it, once you see the first error, then you are not able to send any packet on that queue until you restart the application, it sounds like a queue corruption. This could happen in case of concurrent accesses to the queue.

**Comment by andyarus** [comment]
I create separate queues for threads
Every thread recv/send from/to own queue.
Also I use yet one thread for pushing packets from my queues, but there I use mutexes.
Seems I make protection...

When errors beginning.
Suppose thread processing 1 Gbps, and I don't see so much errrors. Only severals in time period. Suppose one error in 10 minutes. Or other time period, not static.

**Comment by cardigliano** [comment]
@andyarus in essence you are seeing sporadic errors at 1G, how many at a higher rate? I thought you were no longer able to send after the first error, but it seems this is not the case right? Can it be that the link (or the flow control) cannot send the packet and keep up with the transmission rate? 
Do you think this is related to #293 from what you see?

**Comment by andyarus** [comment]
//in essence you are seeing sporadic errors at 1G, how many at a higher rate?
Not much if compare with the total number of transmitted packets.
// I thought you were no longer able to send after the first error, but it seems this is not the case right?
Yep, packets are still being transmitted. But sometimes I can see PF RING send error in my debug to syslog. Rarely

//Can it be that the link (or the flow control) cannot send the packet and keep up with the transmission rate?
How I can find out it?..
If I reload PF RING drivers, and try again start app then likely all be ok. But if I get errors I try restart while errors stopped. 

//Do you think this is related to #293 from what you see?
Maybe some same problem in drivers...
But in #https://github.com/ntop/PF_RING/issues/293 NIC ports on **bypass on** state. Traffic just bypassed

**Comment by cardigliano** [comment]
This is an ixgbe interface with a 10G link right? 
Are you opening the interface in ZC mode ("zc:" prefix) or standard mode? 
Please provide ethtool -g ethX

**Comment by andyarus** [comment]
Yes,
ixgbe 10G
zc:eth11

```
ethtool -g eth11
Ring parameters for eth11:
Pre-set maximums:
RX:		32768
RX Mini:	0
RX Jumbo:	0
TX:		32768
Current hardware settings:
RX:		32768
RX Mini:	0
RX Jumbo:	0
TX:		32768
```

**Comment by andyarus** [comment]
Now, every restart, I reloaded pf ring aware driver for NIC
and seems all ok, I don't see errors
Thanks!
