### ISSUE TITLE
Lost traffic in ZC mode (e1000e)

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#29]
I use e1000e driver. Incoming traffic on interface is about 100Mbps.
First, run zcount without zc:

    # ./zcount -c1 -i eth9
    ....
    =========================
    Absolute Stats: 43'038 pkts (0 drops) - 25'622'234 bytes
    Actual Stats: 20'646.93 pps (0.00 drops) - 0.10 Gbps
    =========================

Looks ok.
Next, run zcount in zc mode:
    
    # ./zcount -c1 -i zc:eth9
    ....
    =========================
    Absolute Stats: 43'335 pkts (0 drops) - 3'810'350 bytes
    Actual Stats: 22'122.77 pps (0.00 drops) - 0.02 Gbps
    =========================

In second case there are only 0.02Gbps, although real incoming traffic stay 100Mbps.
PPS in both cases are equals. So, I think that in zc mode driver parse packets incorrect.

Additional info:

    # ethtool -i eth9
    driver: e1000e
    version: 3.0.4.1-NAPI
    firmware-version: 5.10-2
    bus-info: 0000:07:00.0
    supports-statistics: yes
    supports-test: yes
    supports-eeprom-access: yes
    supports-register-dump: yes
    supports-priv-flags: no

    # cat /proc/net/pf_ring/info
    PF_RING Version          : 6.1.1 (dev:66b9ee499e33298f638a1117bc5ef806167bbe5a)
    Total rings              : 0
    
    Standard (non DNA/ZC) Options
    Ring slots               : 4096
    Slot version             : 16
    Capture TX               : Yes [RX+TX]
    IP Defragment            : No
    Socket Mode              : Standard
    Total plugins            : 0
    Cluster Fragment Queue   : 0
    Cluster Fragment Discard : 0

**Comment by Skryabind** [comment]
When run zcount in verbose mode, I see that caplen in all packets are always 64:

    [1438685121.854049309] [08:19:A6:CD:1D:C0 -> 00:22:B0:18:88:01] [vlan 3100] [IPv4][87.245.194.82:80 -> 85.12.217.70:51381] [l3_proto=TCP][hash=2902683839][tos=0][tcp_seq_num=3682633067] [caplen=64][len=64][parsed_header_len=0][eth_offset=0][l3_offset=18][l4_offset=38][payload_offset=58]

**Comment by cardigliano** [comment]
Hi
please check latest code from git dev.

Alfredo

**Comment by Skryabind** [comment]
It works now. Thanks!
