### ISSUE TITLE
Intel® Xeon® Scalable Processors

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#290]
PF RING ok with
Intel® Xeon® Gold 6130 Processor
?
Seems 6 memory channels better.
And memory speed 2666 Mhz

Now we choose between

**Intel® Xeon® Gold 6130 Processor (16 cores)**
https://ark.intel.com/products/120492/Intel-Xeon-Gold-6130-Processor-22M-Cache-2_10-GHz
and
**Intel® Xeon® Processor E5-2683 v4**
https://ark.intel.com/products/91766/Intel-Xeon-Processor-E5-2683-v4-40M-Cache-2_10-GHz

What better for packet processing with PF RING?

**Comment by cardigliano** [comment]
@andyarus, looking at those models you selected, the xeon gold looks better,
we are in the phase of running tests on those cpus, we will update you as soon
as we have some interesting number about E5 vs Gold
