### ISSUE TITLE
zbalance_ipc No buffer space available

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#291]
@cardigliano I use zbalance_ipc get [No buffer space available] error, my Huge pages free is 3538, why No buffer space available?
I have diff with a ok machine, see HugePages_Rsvd, there is a world of difference between the two.

OK machine Huge pages

> root@iPilot-APM:~# cat /proc/meminfo | grep Huge
AnonHugePages:   1570816 kB
HugePages_Total:    2300
HugePages_Free:     1126
HugePages_Rsvd:      152
HugePages_Surp:        0
Hugepagesize:       2048 kB

My command

> root@iPilot-APM:/usr/local/var# ipmipc -i zc:p4p1,zc:p4p2 -c 98 -n 3 -m 2
15v/2017 17:10:25 [ipmipc.c:685] ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration

Problem machine memory info

> RORO-PC
root@iPilot-APM:/usr/local/var# cat /proc/meminfo
MemTotal:       131628752 kB
MemFree:        122310308 kB
MemAvailable:   122249164 kB
Buffers:           15392 kB
Cached:            64024 kB
SwapCached:            0 kB
Active:           428468 kB
Inactive:          29168 kB
Active(anon):     378212 kB
Inactive(anon):     1264 kB
Active(file):      50256 kB
Inactive(file):    27904 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      62499836 kB
SwapFree:       62499836 kB
Dirty:              1044 kB
Writeback:             0 kB
AnonPages:        378236 kB
Mapped:            50472 kB
Shmem:              1276 kB
Slab:              96288 kB
SReclaimable:      24780 kB
SUnreclaim:        71508 kB
KernelStack:       10512 kB
PageTables:         6088 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    124119908 kB
Committed_AS:    1081508 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      507096 kB
VmallocChunk:   34291074652 kB
HardwareCorrupted:     0 kB
AnonHugePages:     98304 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:    4096
HugePages_Free:     3545
HugePages_Rsvd:     2736
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      178048 kB
DirectMap2M:     8847360 kB
DirectMap1G:    126877696 kB

my NICs

> root@iPilot-APM:/usr/local/var# ethtool -i p4p1
driver: igb
version: 5.3.3.5
firmware-version: 1.63, 0x800009fa
bus-info: 0000:81:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
root@iPilot-APM:/usr/local/var# ethtool -i p4p2
driver: igb
version: 5.3.3.5
firmware-version: 1.63, 0x800009fa
bus-info: 0000:81:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
root@iPilot-APM:/usr/local/var#

**Comment by cardigliano** [comment]
Please provide df, cat /proc/mounts, ls /dev/hugepages

**Comment by laoyang103** [comment]
@cardigliano sorry this machine has reboot and is OK now, I will provide when it happen.

this is now OK status you need:
df
> root@iPilot-APM:/data/kpi# df  
Filesystem      1K-blocks       Used  Available Use% Mounted on
/dev/sda1       480486104    1814384  454241336   1% /
none                    4          0          4   0% /sys/fs/cgroup
udev             16405472          4   16405468   1% /dev
tmpfs             3283244        896    3282348   1% /run
none                 5120          0       5120   0% /run/lock
none             16416212          4   16416208   1% /run/shm
none               102400          0     102400   0% /run/user
/dev/sdb1      5425529784 4056737700 1095338260  79% /data/dsas
/dev/sdb2      4037071240    1088732 3830888008   1% /data/kpi
/dev/sdb3      4032409256  147622552 3679929004   4% /var
/dev/sda3       418635512      74416  397272600   1% /data/dumpfiles

cat /proc/mounts

> root@iPilot-APM:/data/kpi# cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=16405472k,nr_inodes=4101368,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=3283244k,mode=755 0 0
/dev/disk/by-uuid/5222768c-a38c-420e-8c80-5414d0a54526 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /sys/fs/cgroup tmpfs rw,relatime,size=4k,mode=755 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
none /sys/kernel/security securityfs rw,relatime 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
none /run/shm tmpfs rw,nosuid,nodev,relatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755 0 0
none /sys/fs/pstore pstore rw,relatime 0 0
/dev/sdb1 /data/dsas ext4 rw,relatime,data=ordered 0 0
/dev/sdb2 /data/kpi ext4 rw,relatime,data=ordered 0 0
/dev/sdb3 /var ext4 rw,relatime,data=ordered 0 0
/dev/sda3 /data/dumpfiles ext4 rw,relatime,data=ordered 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,name=systemd 0 0
nodev /mnt/huge hugetlbfs rw,relatime 0 0

ls /dev/hugepages
> root@iPilot-APM:/data/kpi#  ls /dev/hugepages
ls: cannot access /dev/hugepages: No such file or directory

**Comment by laoyang103** [comment]
Hello @cardigliano 
 I use zbalance_ipc captrue three NIC, every NIC use ethtool -L $nic combined 2, then start 2 zbalance_ipc, but get [No buffer space available] error when start more than 4 zbalance_ipc, my Huge pages free is 14336

see follow:

> root@iPilot-XPM:/usr/local/var# df
Filesystem       1K-blocks     Used   Available Use% Mounted on
/dev/sda1       1441727828  7082812  1361386456   1% /
none                     4        0           4   0% /sys/fs/cgroup
udev              65823740        4    65823736   1% /dev
tmpfs             13166900     1760    13165140   1% /run
none                  5120        0        5120   0% /run/lock
none              65834484        0    65834484   0% /run/shm
none                102400        0      102400   0% /run/user
/dev/sdb4       3865427336    71996  3668979804   1% /data/dumpfiles
/dev/sdb3       3844823352   113300  3649381172   1% /data/kpi
/dev/sdb2      58360406256   174532 55430527840   1% /var
/dev/sdb1      97267384088 35127396 92349427816   1% /data/dsas

> root@iPilot-XPM:/usr/local/var# cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=65823740k,nr_inodes=16455935,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=13166900k,mode=755 0 0
/dev/disk/by-uuid/98f94bc8-bee7-42e1-953b-7eebf3f9d748 / ext4 rw,relatime,errors=remount-ro,stripe=64,data=ordered 0 0
none /sys/fs/cgroup tmpfs rw,relatime,size=4k,mode=755 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
none /sys/kernel/security securityfs rw,relatime 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
none /run/shm tmpfs rw,nosuid,nodev,relatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755 0 0
none /sys/fs/pstore pstore rw,relatime 0 0
/dev/sdb4 /data/dumpfiles ext4 rw,relatime,stripe=64,data=ordered 0 0
/dev/sdb3 /data/kpi ext4 rw,relatime,stripe=64,data=ordered 0 0
/dev/sdb2 /var ext4 rw,relatime,stripe=64,data=ordered 0 0
/dev/sdb1 /data/dsas ext4 rw,relatime,stripe=64,data=ordered 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,name=systemd 0 0
none /dev/hugepages hugetlbfs rw,relatime 0 0

> root@iPilot-XPM:/usr/local/var#  ls /dev/hugepages
pfring_zc_93  pfring_zc_94  pfring_zc_95  pfring_zc_96


> root@iPilot-XPM:/usr/local/var# ps aux | grep ipm
root      1081  0.0  0.0      0     0 ?        SN   18:10   0:00 [kipmi0]
root      3212  104  0.0 1089024 9048 ?        Sl   18:12   1:12 ipc -i zc:p4p1@0 -D 1 -c 93 -n 2 -m 5 -g 0 -S 1 -p
root      3280  105  0.0 1089024 9188 ?        Sl   18:12   1:07 ipc -i zc:p4p1@1 -D 1 -c 94 -n 2 -m 5 -g 4 -S 5 -p
root      3297  105  0.0 1089024 9096 ?        Sl   18:12   1:03 pc -i zc:p20p1@0 -D 6 -c 95 -n 2 -m 5 -g 8 -S 9 -p
root      3353  105  0.0 1089024 9188 ?        Sl   18:12   0:59 ipc -i zc:p20p1@1 -D 6 -c 96 -n 2 -m 5 -g 12 -S 13 -p
root      3774  0.0  0.0  12784  2072 pts/0    S+   18:13   0:00 grep --color=auto ipm


> root@iPilot-XPM:/usr/local/var# ipc -i zc:p3p1@0 -D 4 -c 97 -n 2 -m 2 -g 16 -S 17 -p
21/Aug/2020 18:13:20 [src/ipc.c:607] ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration

**Comment by cardigliano** [comment]
please monitor hugepages utilization with "cat /proc/meminfo | grep Huge" after running each zbalance_ipc instance

**Comment by laoyang103** [comment]
also have 15360 after 4 ipc started. no app

> root@iPilot-XPM:~# cat /proc/meminfo |grep Huge                    
AnonHugePages:   2551808 kB                                        
HugePages_Total:   16384                                           
HugePages_Free:    15360                                           
HugePages_Rsvd:        0                                           
HugePages_Surp:        0                                           
Hugepagesize:       2048 kB                                        
root@iPilot-XPM:~#

**Comment by cardigliano** [comment]
@laoyang103 please provide ifconfig listing all the interfaces you are using

**Comment by laoyang103** [comment]
> root@iPilot-XPM:~# ifconfig p3p1                                   
p3p1      Link encap:Ethernet  HWaddr f8:f2:1e:82:55:54            
          inet6 addr: fe80::faf2:1eff:fe82:5554/64 Scope:Link      
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:
1                                                                  
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0      
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0     
          collisions:0 txqueuelen:1000                             
          RX bytes:2424 (2.4 KB)  TX bytes:680 (680.0 B)           
          Memory:bd080000-bd100000

> root@iPilot-XPM:~# ifconfig p4p1                                   
p4p1      Link encap:Ethernet  HWaddr f8:f2:1e:82:57:b8            
          inet6 addr: fe80::faf2:1eff:fe82:57b8/64 Scope:Link      
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:
1                                                                  
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0      
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0     
          collisions:0 txqueuelen:1000                             
          RX bytes:2424 (2.4 KB)  TX bytes:680 (680.0 B)           
          Memory:bc080000-bc100000                                 
                                                                   

> root@iPilot-XPM:~# ifconfig p20p1                                  
p20p1     Link encap:Ethernet  HWaddr f8:f2:1e:82:71:ac            
          inet6 addr: fe80::faf2:1eff:fe82:71ac/64 Scope:Link      
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:
1                                                                  
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0      
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0     
          collisions:0 txqueuelen:1000                             
          RX bytes:2424 (2.4 KB)  TX bytes:680 (680.0 B)           
          Memory:eea80000-eeb00000

**Comment by cardigliano** [comment]
It looks fine. Do you see any error in dmesg?

**Comment by cardigliano** [comment]
Please also try adding -E to zbalance_ipc for debug info

**Comment by laoyang103** [comment]
dmesg say follow

> [ 7892.861440] [PF_RING] pfring_select_zc_dev:5892 p3p1@1 mapping f
ailed or not a ZC device                                           
[ 7996.969610] [PF_RING] pfring_select_zc_dev:5892 p4p1@1 mapping f
ailed or not a ZC device                                           
[ 7997.072961] [PF_RING] pfring_select_zc_dev:5892 p4p1@1 mapping f
ailed or not a ZC device                                           
[ 7998.635647] [PF_RING] pfring_select_zc_dev:5892 p4p1@1 mapping f
ailed or not a ZC device                                           
[ 8004.983468] [PF_RING] pfring_select_zc_dev:5892 p20p1@1 mapping 
failed or not a ZC device                                          
[ 8005.085248] [PF_RING] pfring_select_zc_dev:5892 p20p1@1 mapping 
failed or not a ZC device                                          
[ 8006.654678] [PF_RING] pfring_select_zc_dev:5892 p20p1@1 mapping 
failed or not a ZC device                                          
[ 8012.997673] [PF_RING] pfring_select_zc_dev:5892 p3p1@1 mapping f
ailed or not a ZC device                                           
[ 8013.101531] [PF_RING] pfring_select_zc_dev:5892 p3p1@1 mapping f
ailed or not a ZC device                                           
[ 8117.211549] [PF_RING] pfring_select_zc_dev:5892 p4p1@1 mapping f
ailed or not a ZC device                                           
[ 8117.313068] [PF_RING] pfring_select_zc_dev:5892 p4p1@1 mapping f
ailed or not a ZC device                                           
root@iPilot-XPM:~#

**Comment by laoyang103** [comment]
Hi @cardigliano , I use PF_RING 7.3.0 in ubuntu 14.04.3

I have test with follow:

> ipc -i zc:p20p1 -D 1 -c 93 -n 2,2 -m 4 -q 65536 -b 1024 -g 0 -S 1 -p  2>&1 >> /data/kpi//ipc93.log &
comm -i zc:93@0 -D 1 -n 2 -s  2>&1 >> /data/kpi//comm930.log &
comm -i zc:93@1 -D 1 -n 3 -s  2>&1 >> /data/kpi//comm931.log &
dsas -i zc:93@2 -D 1 -n 4 -s  2>&1 >> /data/kpi//dsas932.log &
dsas -i zc:93@3 -D 1 -n 5 -s  2>&1 >> /data/kpi//dsas933.log &
ipc -i zc:p3p1 -D 4 -c 94 -n 2,2 -m 4 -q 65536 -b 1024 -g 8 -S 9 -p  2>&1 >> /data/kpi//ipc94.log &
comm -i zc:94@0 -D 4 -n 10 -s  2>&1 >> /data/kpi//comm940.log &
comm -i zc:94@1 -D 4 -n 11 -s  2>&1 >> /data/kpi//comm941.log &
dsas -i zc:94@2 -D 4 -n 12 -s  2>&1 >> /data/kpi//dsas942.log &
dsas -i zc:94@3 -D 4 -n 13 -s  2>&1 >> /data/kpi//dsas943.log &
ipc -i zc:p4p1 -D 6 -c 95 -n 2,2 -m 4 -q 65536 -b 1024 -g 16 -S 17 -p  2>&1 >> /data/api//ipc95.log &
24/Aug/2020 12:21:42 [src/ipc.c:607] ERROR: pfring_zc_create_cluster error [No buffer space available] Please check your hugetlb configuration
comm -i zc:95@0 -D 6 -n 18 -s  2>&1 >> /data/kpi//comm950.log &
comm -i zc:95@1 -D 6 -n 19 -s  2>&1 >> /data/kpi//comm951.log &
dsas -i zc:95@2 -D 6 -n 20 -s  2>&1 >> /data/kpi//dsas952.log &
dsas -i zc:95@3 -D 6 -n 21 -s  2>&1 >> /data/kpi//dsas953.log &

HugePages_Total is 16384, first ipc(zc:p4p1)  start surplus 15360, second start surplus 14336, last start with error, nothing found in dmesg

**Comment by cardigliano** [comment]
@laoyang103 please use pf_ring 7.7 (dev) or 7.6 (stable) as I am unable to support you with 7.3

**Comment by laoyang103** [comment]
Hi @cardigliano  final I compile PF_RING-7.6.0-stable on ubuntu 14.04.3, got follow:

> root@iPilot-XPM:~# ipc -i zc:p21p1@0 -D 2 -c 92 -n 2 -m 2 -q 65536 -b 1024 -g 18 -S 19 -p -E
[PF_RING-ZC][DEBUG] 165896 1536-byte (1600-byte) buffers requested
[PF_RING-ZC][DEBUG] 342807296 bytes approximated memory required
[PF_RING-ZC][DEBUG] 7864 2097152-byte pages available at /dev/hugepages
[PF_RING-ZC][DEBUG] 164 2097152-byte pages requested (cluster id = 92)
[PF_RING-ZC][DEBUG] 164 2097152-byte pages allocated with va = 0x7fc46d800000 pa = [ - ]
25/Aug/2020 12:37:26 [zbalance_ipc.c:954] ERROR: pfring_zc_create_cluster error [No buffer space available]
25/Aug/2020 12:37:26 [zbalance_ipc.c:957] ERROR: Insufficient hugepage memory, please try increasing your hugepage count

then I change -g and -S to core 40 and 41, it work

> root@iPilot-XPM:~# ipmipc -i zc:p21p1@1 -D 2 -c 92 -n 2 -m 2 -q 65536 -b 1024 -g 40 -S 41 -p -E
[PF_RING-ZC][DEBUG] 165896 1536-byte (1600-byte) buffers requested
[PF_RING-ZC][DEBUG] 342807296 bytes approximated memory required
[PF_RING-ZC][DEBUG] 7864 2097152-byte pages available at /dev/hugepages
[PF_RING-ZC][DEBUG] 164 2097152-byte pages requested (cluster id = 92)
[PF_RING-ZC][DEBUG] 164 2097152-byte pages allocated with va = 0x7f599ae00000 pa = [ 53785657344, 53783560192, 53789851648, 53787754496, 53794045952, 53791948800, 53798240256, 53796143104, 53802434560, 53800337408, 53806628864, 53804531712, 53810823168, 53808726016, 53815017472, 53812920320, 53819211776, 53817114624, 53823406080, 53821308928, 53827600384, 53825503232, 53831794688, 53829697536, 53835988992, 53833891840, 53840183296, 53838086144, 53844377600, 53842280448, 53848571904, 53846474752, 53852766208, 53850669056, 53856960512, 53854863360, 53861154816, 53859057664, 53865349120, 53863251968, 53869543424, 53867446272, 53873737728, 53871640576, 53877932032, 53875834880, 53882126336, 53880029184, 53886320640, 53884223488, 53890514944, 53888417792, 53894709248, 53892612096, 53898903552, 53896806400, 53903097856, 53901000704, 53907292160, 53905195008, 53911486464, 53909389312, 53915680768, 53913583616, 53919875072, 53917777920, 53924069376, 53921972224, 53928263680, 53926166528, 53932457984, 53930360832, 53936652288, 53934555136, 53940846592, 53938749440, 53945040896, 53942943744, 53949235200, 53947138048, 53953429504, 53951332352, 53957623808, 53955526656, 53961818112, 53959720960, 53966012416, 53963915264, 53970206720, 53968109568, 53974401024, 53972303872, 53978595328, 53976498176, 53982789632, 53980692480, 53986983936, 53984886784, 53991178240, 53989081088, 53995372544, 53993275392, 53999566848, 53997469696, 54003761152, 54001664000, 54007955456, 54005858304, 54012149760, 54010052608, 54016344064, 54014246912, 54020538368, 54018441216, 54024732672, 54022635520, 54028926976, 54026829824, 54033121280, 54031024128, 54037315584, 54035218432, 54041509888, 54039412736, 54045704192, 54043607040, 54049898496, 54047801344, 54054092800, 54051995648, 54058287104, 54056189952, 54062481408, 54060384256, 54066675712, 54064578560, 54070870016, 54068772864, 54075064320, 54072967168, 54079258624, 54077161472, 54083452928, 54081355776, 54087647232, 54085550080, 54091841536, 54089744384, 54096035840, 54093938688, 54100230144, 54098132992, 54104424448, 54102327296, 54108618752, 54106521600, 54112813056, 54110715904, 54117007360, 54114910208, 54121201664, 54119104512, 54125395968, 54123298816 ]
[PF_RING-ZC][DEBUG] Initialising memory segment
[PF_RING-ZC][DEBUG] Memory allocation completed successfully
WARNING: your system lacks of pthread_setaffinity_np() (not core binding)
25/Aug/2020 12:49:24 [zbalance_ipc.c:1136] Starting balancer with 2 consumer queues..
25/Aug/2020 12:49:24 [zbalance_ipc.c:1146] Run your application instances as follows:
25/Aug/2020 12:49:24 [zbalance_ipc.c:1151] 	pfcount -i zc:92@0
25/Aug/2020 12:49:24 [zbalance_ipc.c:1151] 	pfcount -i zc:92@1
user changed to nobody
25/Aug/2020 12:49:24 [zbalance_ipc.c:1237] User changed to 2
25/Aug/2020 12:49:25 [zbalance_ipc.c:268] =========================

**Comment by cardigliano** [comment]
Great, so I assume everything is working now. Thank you for the update.

**Comment by laoyang103** [comment]
@cardigliano Thanks for your reply, but my question is bind core 18 19, this seem pa is an empty array

> va = 0x7fc46d800000 pa = [ - ] 

and why bind 40 41 pa not empty?

**Comment by cardigliano** [comment]
I think it depends on the CPU you are using, hugepages are allocated per CPU. Please provide the output of "lstopo"

**Comment by laoyang103** [comment]
Thans for your reply, follow is ls topo output:

> root@iPilot-XPM:~# lstopo 
Machine (126GB)
  NUMANode L#0 (P#0 63GB)
    Socket L#0 + L3 L#0 (22MB)
      L2 L#0 (1024KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#32)
      L2 L#1 (1024KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
        PU L#2 (P#1)
        PU L#3 (P#33)
      L2 L#2 (1024KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
        PU L#4 (P#2)
        PU L#5 (P#34)
      L2 L#3 (1024KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
        PU L#6 (P#3)
        PU L#7 (P#35)
      L2 L#4 (1024KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
        PU L#8 (P#4)
        PU L#9 (P#36)
      L2 L#5 (1024KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
        PU L#10 (P#5)
        PU L#11 (P#37)
      L2 L#6 (1024KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
        PU L#12 (P#6)
        PU L#13 (P#38)
      L2 L#7 (1024KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
        PU L#14 (P#7)
        PU L#15 (P#39)
      L2 L#8 (1024KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8
        PU L#16 (P#8)
        PU L#17 (P#40)
      L2 L#9 (1024KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9
        PU L#18 (P#9)
        PU L#19 (P#41)
      L2 L#10 (1024KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10
        PU L#20 (P#10)
        PU L#21 (P#42)
      L2 L#11 (1024KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11
        PU L#22 (P#11)
        PU L#23 (P#43)
      L2 L#12 (1024KB) + L1d L#12 (32KB) + L1i L#12 (32KB) + Core L#12
        PU L#24 (P#12)
        PU L#25 (P#44)
      L2 L#13 (1024KB) + L1d L#13 (32KB) + L1i L#13 (32KB) + Core L#13
        PU L#26 (P#13)
        PU L#27 (P#45)
      L2 L#14 (1024KB) + L1d L#14 (32KB) + L1i L#14 (32KB) + Core L#14
        PU L#28 (P#14)
        PU L#29 (P#46)
      L2 L#15 (1024KB) + L1d L#15 (32KB) + L1i L#15 (32KB) + Core L#15
        PU L#30 (P#15)
        PU L#31 (P#47)
    HostBridge L#0
      PCI 8086:a1d2
      PCI 8086:a182
      PCIBridge
        PCIBridge
          PCI 1a03:2000
            GPU L#0 "card0"
            GPU L#1 "controlD64"
    HostBridge L#3
      PCIBridge
        PCI 1000:005d
          Block L#2 "sda"
          Block L#3 "sdb"
    HostBridge L#5
      PCIBridge
        PCIBridge
          PCIBridge
            PCI 8086:37d1
              Net L#4 "p8p1"
            PCI 8086:37d1
              Net L#5 "p8p2"
            PCI 8086:37d1
              Net L#6 "p8p3"
            PCI 8086:37d1
              Net L#7 "p8p4"
    HostBridge L#9
      PCIBridge
        PCI 8086:10fb
          Net L#8 "p4p1"
        PCI 8086:10fb
          Net L#9 "p4p2"
      PCIBridge
        PCI 8086:10fb
          Net L#10 "p3p1"
        PCI 8086:10fb
          Net L#11 "p3p2"
  NUMANode L#1 (P#1 63GB)
    Socket L#1 + L3 L#1 (22MB)
      L2 L#16 (1024KB) + L1d L#16 (32KB) + L1i L#16 (32KB) + Core L#16
        PU L#32 (P#16)
        PU L#33 (P#48)
      L2 L#17 (1024KB) + L1d L#17 (32KB) + L1i L#17 (32KB) + Core L#17
        PU L#34 (P#17)
        PU L#35 (P#49)
      L2 L#18 (1024KB) + L1d L#18 (32KB) + L1i L#18 (32KB) + Core L#18
        PU L#36 (P#18)
        PU L#37 (P#50)
      L2 L#19 (1024KB) + L1d L#19 (32KB) + L1i L#19 (32KB) + Core L#19
        PU L#38 (P#19)
        PU L#39 (P#51)
      L2 L#20 (1024KB) + L1d L#20 (32KB) + L1i L#20 (32KB) + Core L#20
        PU L#40 (P#20)
        PU L#41 (P#52)
      L2 L#21 (1024KB) + L1d L#21 (32KB) + L1i L#21 (32KB) + Core L#21
        PU L#42 (P#21)
        PU L#43 (P#53)
      L2 L#22 (1024KB) + L1d L#22 (32KB) + L1i L#22 (32KB) + Core L#22
        PU L#44 (P#22)
        PU L#45 (P#54)
      L2 L#23 (1024KB) + L1d L#23 (32KB) + L1i L#23 (32KB) + Core L#23
        PU L#46 (P#23)
        PU L#47 (P#55)
      L2 L#24 (1024KB) + L1d L#24 (32KB) + L1i L#24 (32KB) + Core L#24
        PU L#48 (P#24)
        PU L#49 (P#56)
      L2 L#25 (1024KB) + L1d L#25 (32KB) + L1i L#25 (32KB) + Core L#25
        PU L#50 (P#25)
        PU L#51 (P#57)
      L2 L#26 (1024KB) + L1d L#26 (32KB) + L1i L#26 (32KB) + Core L#26
        PU L#52 (P#26)
        PU L#53 (P#58)
      L2 L#27 (1024KB) + L1d L#27 (32KB) + L1i L#27 (32KB) + Core L#27
        PU L#54 (P#27)
        PU L#55 (P#59)
      L2 L#28 (1024KB) + L1d L#28 (32KB) + L1i L#28 (32KB) + Core L#28
        PU L#56 (P#28)
        PU L#57 (P#60)
      L2 L#29 (1024KB) + L1d L#29 (32KB) + L1i L#29 (32KB) + Core L#29
        PU L#58 (P#29)
        PU L#59 (P#61)
      L2 L#30 (1024KB) + L1d L#30 (32KB) + L1i L#30 (32KB) + Core L#30
        PU L#60 (P#30)
        PU L#61 (P#62)
      L2 L#31 (1024KB) + L1d L#31 (32KB) + L1i L#31 (32KB) + Core L#31
        PU L#62 (P#31)
        PU L#63 (P#63)
    HostBridge L#12
      PCIBridge
        PCI 8086:10fb
          Net L#12 "p21p1"
        PCI 8086:10fb
          Net L#13 "p21p2"
      PCIBridge
        PCI 8086:10fb
          Net L#14 "p20p1"
        PCI 8086:10fb
          Net L#15 "p20p2"

**Comment by cardigliano** [comment]
That confirms you have 2 different CPUs and 18/19 and 40/41 are on two different CPUs. You can control hugepages allocation on each CPU, please read https://www.ntop.org/guides/pf_ring/hugepages.html

**Comment by laoyang103** [comment]
OK, thank you very much, I got lotopo and hugepages allocation on each CPU new knowledge
