### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by KjellKod** [ntop/PF_RING#30]
It would be sweet if the documentation can be updated to point to this github location instead of svn. 
It is strictly not an issue for the github code but I'm putting it up here since they are intertwined 
(API description and the actual API)

Example: http://www.ntop.org/pf_ring/learning-the-pf_ring-api/

**Comment by lucaderi** [comment]
Hi, can you please send us a merge requests with the fixes you want to make?

**Comment by KjellKod** [comment]
I tried to convey that on the URL mentioned the documentation should point to github but it points to svn instead so links in the URL page above is broken.

I.e its your site that needs to fix broken links and not he GitHub.

I hadn't signed up for the mailing list at the time I posted this issue. If I had I would have posted it there instead.

Since you have read it I think the message was delivered and I'm OK with this being closed.

**Comment by lmangani** [comment]
Documentation being updated. Thanks for your report! Closing.
