### ISSUE TITLE
Test PF_RING ZC at e1000e

### ISSUE THREAD

**Issue by WhorfC** [ntop/PF_RING#301]
Hi:
    System：Censos7.1
    I'm run ./zcount -i zc:enp1s0
Tip: We're now working in demo mode with packet capture and transmission limited to 5 minutes.
But after 10 seconds, cannot get packet.

As follows:
    =========================
Absolute Stats: 874'119 pkts (0 drops) - 92'656'614 bytes
=========================

=========================
Absolute Stats: 1'954'011 pkts (0 drops) - 207'125'166 bytes
Actual Stats: 1'079'791.57 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 3'036'618 pkts (0 drops) - 321'881'508 bytes
Actual Stats: 1'080'897.02 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 4'118'156 pkts (0 drops) - 436'524'536 bytes
Actual Stats: 1'081'353.08 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 5'200'813 pkts (0 drops) - 551'286'178 bytes
Actual Stats: 1'082'514.10 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 6'281'196 pkts (0 drops) - 665'806'754 bytes
Actual Stats: 1'080'136.72 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 7'362'890 pkts (0 drops) - 780'466'296 bytes
Actual Stats: 1'081'554.47 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 8'443'577 pkts (0 drops) - 895'019'096 bytes
Actual Stats: 1'080'599.47 pps (0.00 drops) - 0.92 Gbps
=========================

=========================
Absolute Stats: 8'647'787 pkts (0 drops) - 916'665'334 bytes
Actual Stats: 204'189.58 pps (0.00 drops) - 0.17 Gbps
=========================

=========================
Absolute Stats: 8'647'788 pkts (0 drops) - 916'665'418 bytes
Actual Stats: 1.00 pps (0.00 drops) - 0.00 Gbps
=========================

=========================
Absolute Stats: 8'647'789 pkts (0 drops) - 916'665'502 bytes
Actual Stats: 1.00 pps (0.00 drops) - 0.00 Gbps
=========================

=========================
Absolute Stats: 8'647'790 pkts (0 drops) - 916'665'586 bytes
Actual Stats: 1.00 pps (0.00 drops) - 0.00 Gbps
=========================

=========================
Absolute Stats: 8'647'791 pkts (0 drops) - 916'665'670 bytes
Actual Stats: 1.00 pps (0.00 drops) - 0.00 Gbps

It's the same test many times.

**Comment by cardigliano** [comment]
@WhorfC what pf_ring version are you using? Please provide cat /proc/net/pf_ring/info and ethtool -i enp1s0

**Comment by WhorfC** [comment]
PF_RING Version          : 7.0.0 (unknown)
Total rings              : 0
Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0


driver: e1000e
version: 3.2.7.1-NAPI
firmware-version: 5.133-1
bus-info: 0000:01:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no


01:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)

**Comment by cardigliano** [comment]
@WhorfC, I was not able to reproduce it, more debugging is needed on your side if possible,
please run ./pfcount -i zc:enp1s0 -v 1 and provide some output when it stops receiving traffic (I see it receives 1 pps)

**Comment by cardigliano** [comment]
Closed for inactivity, please reopen in case
