### ISSUE TITLE
Possible typo in ../drivers/intel/i40e/i40e-2.3.6-zc/src/i40e/Makefile

### ISSUE THREAD

**Issue by akadoorie** [ntop/PF_RING#303]
Maybe ?= should be := in the following line:
https://github.com/ntop/PF_RING/blob/dev/drivers/intel/i40e/i40e-2.3.6-zc/src/i40e/Makefile#L77

**Comment by cardigliano** [comment]
?= sets INSTALL_MOD_DIR only if it's not set
