### ISSUE TITLE
balancer vs lacp

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#304]
4 ports on nic (port1 - port2, port3 - port4)
traffic go through all ports in out
now I use RSS queues for distributing packets between cpu cores
I tried use balancers (pfring_zc_run_balancer)
When I enable first pair of ports (port1 - port2 bypass off)
traffic go
Then i try enable other pair (port3 - port4 bypass off)
and traffic "died"
I guess because of balancer distribute packets between all ports, but for success work **LACP (Link Aggregation Control Protocol)** service packets of this protocol must be transmitted between only one pair of ports?
Packet (service packet for LACP) come to port1, and I can only send this packet from port1 (back) ot from port2 (in other direction). If I send this packet from port3 or from port4 I lost aggregation and traffic "died". It's correct?
How I can handle this problem? Using PF RING balancer I can get information about from where the packet was received (what's port)?

**Comment by cardigliano** [comment]
The distribution function you specify in pfring_zc_run_balancer() ha an pfring_zc_queue *in_queue parameter which is the ingress port for the packet.

**Comment by andyarus** [comment]
```
typedef int32_t(* pfring_zc_distribution_func)(pfring_zc_pkt_buff *pkt_handle, pfring_zc_queue *in_queue, void *user)

The distribution function prototype.

Parameters
pkt_handle | The received buffer handle.
in_queue | The ingress queues handle from which the packet arrived.
user | The pointer to the user data.
Returns
The egress queue index (or a negative value to drop the packet) in case of balancing, the egress queues bit-mask in case of fan-out.
```

and what option I have
check for every packet?
```
if (in_queue == in_queue_port0) {
}
```
and what I can do?
If I have this pointer (to port queue) when get packet from out_queue (pfring_zc_recv_pkt), I could  parse packet and then if it's `lacp` packet, I could send him to right port and not lose aggregation.

**Comment by cardigliano** [comment]
Yes you should check for every packet something like in_queue == in_queue_port0
