### ISSUE TITLE
modprobe pf_ring  (6.0.3) in CentOS7.2 fail. 

### ISSUE THREAD

**Issue by moonshineBoy** [ntop/PF_RING#306]
```
[root@localhost kernel]# modprobe pf_ring 
modprobe: ERROR: could not insert 'pf_ring': Unknown symbol in module, or unknown parameter (see dmesg)
```

How to solve this issue, friend?

**Comment by cardigliano** [comment]
Please run dmesg and provide the output
BTW please note PF_RING 6.0 is quite old, please consider moving to latest stable.

**Comment by cardigliano** [comment]
Closed for inactivity, please reopen in case
