### ISSUE TITLE
pfring_open eth0 error [Address family not supported by protocol]

### ISSUE THREAD

**Issue by hom7** [ntop/PF_RING#308]
hi, how to deal with this error?

**Comment by cardigliano** [comment]
Please provide:
cat /proc/net/pf_ring/info
cat /proc/net/pf_ring/dev/eth0/info

**Comment by hom7** [comment]
server:ubuntu 14.04.05 x64

 lsmod |grep pf
pf_ring              1241088  0 

cat /proc/net/pf_ring/info
PF_RING Version          : 7.1.0 (dev:de6f27ff53e926765faa78c35ce8ea02da01f63f)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

cat /proc/net/pf_ring/dev/eth0/info
Name:         eth0
Index:        2
Address:      00:0C:29:C3:06:40
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    1
RX Queues:    1

now error: pfring_set_channel_id() failed: -1

**Comment by cardigliano** [comment]
What application are you using? Please try running pfcount -i eth0

**Comment by hom7** [comment]
The server did not find this command. 
I entered the installation package implementation

cd PF_RING/userland/examples

PF_RING/userland/examples# ./pcount -i eth0
Capturing from eth0
=========================
Absolute Stats: [0 pkts rcvd][0 pkts dropped]
Total Pkts=0/Dropped=0.0 %
0 pkts [0.0 pkt/sec] - 0 bytes [0.00 Mbit/sec]
=========================
=========================
Absolute Stats: [2 pkts rcvd][0 pkts dropped]
Total Pkts=2/Dropped=0.0 %
2 pkts [4.0 pkt/sec] - 342 bytes [0.01 Mbit/sec]
=========================
Actual Stats: 2 pkts [1001.1 ms][2.00 pkt/sec]
=========================
=========================
Absolute Stats: [4 pkts rcvd][0 pkts dropped]
Total Pkts=4/Dropped=0.0 %
4 pkts [2.7 pkt/sec] - 764 bytes [0.00 Mbit/sec]
=========================
Actual Stats: 2 pkts [1001.2 ms][2.00 pkt/sec]
=========================
=========================
Absolute Stats: [6 pkts rcvd][0 pkts dropped]
Total Pkts=6/Dropped=0.0 %
6 pkts [2.4 pkt/sec] - 1186 bytes [0.00 Mbit/sec]
=========================
Actual Stats: 2 pkts [1000.8 ms][2.00 pkt/sec]
=========================
=========================
Absolute Stats: [9 pkts rcvd][0 pkts dropped]
Total Pkts=9/Dropped=0.0 %
9 pkts [2.6 pkt/sec] - 1668 bytes [0.00 Mbit/sec]
=========================
Actual Stats: 3 pkts [1001.1 ms][3.00 pkt/sec]

**Comment by cardigliano** [comment]
Ok so pfcount is working, it seems you are passing some wrong parameter to pfring_set_channel_id()

**Comment by hom7** [comment]
OK，Then I am under my own inspection, thank you very much
