### ISSUE TITLE
build system problems

### ISSUE THREAD

**Issue by wmyrda** [ntop/PF_RING#312]
Hi,
I created installation script for RF_RING in Gentoo https://bugs.gentoo.org/645542 found following problems during installation:
1) Program does not have option to compile library without static library
2) Makefile.in has harcoded /lib directory during install. Gentoo is true multilib distro and disallows install directly into lib direcory https://wiki.gentoo.org/wiki/Multilib. 
3) Libray symlink is required for suricata, but is not created 

First issue is partially fixed by the patch in the reported bug as it changes build system not to install static library. Choosing static library no to compile made shared library fail during compile

Second issue has been fixed by changing Makefile.in entries. For both fixes see https://645542.bugs.gentoo.org/attachment.cgi?id=516316

Third issue is fixed by the install script https://645542.bugs.gentoo.org/attachment.cgi?id=516520 with entry of libpfring.so /usr/$(get_libdir)/libpfring.so.1 but it would be good idea to reflect that in source as well

**Comment by cardigliano** [comment]
Hi
that’s great, thank you for forking on that, please read my comments below.

Alfredo

> On 25 Jan 2018, at 11:19, wmyrda <notifications@github.com> wrote:
> 
> Hi,
> I created installation script for RF_RING in Gentoo https://bugs.gentoo.org/645542 <https://bugs.gentoo.org/645542> found following problems during installation:
> 
> Program does not have option to compile library without static library
What about running make install-shared ? Of running make install is the only option?
> Makefile.in has harcoded /lib directory during install. Gentoo is true multilib distro and disallows install directly into lib direcory https://wiki.gentoo.org/wiki/Multilib <https://wiki.gentoo.org/wiki/Multilib>.
Where @libdir@ comes from?

**Comment by wmyrda** [comment]
> What about running make install-shared ? Of running make install is the only option?

Installing works fine and yes running "make install-shared" does the job of installing just shared library. What I was after is that at configure time one should be able to disable creation of static library to save this few cpu cycles. I did it manually in Makefile.in and compilation of just the shared library failed. It is nothing essential, but it was first time I encountered similar problem hence the report. Removing install-shared was just a way I picked to install shared only, but You are right I could as well just use install-shared.

> Where @libdir@ comes from?

I am not the programmer to know how autotools work, but for me @libdir@ is whey for the system to process default libdir by the configure script. Only thing what Gentoo does is requiring every instance of /lib to be configurable for multilib so several versions of the system may be installed at the same time (eg. AMD64 & x86) therefore plain /lib is forbidden hence the use of --libdir=/usr/$(get_libdir) at configure. Some installation scripts use it several times to have more than one directory used for that purpose.

**Comment by cardigliano** [comment]
@wmyrda, please check latest code and let us know if it works for you.

**Comment by wmyrda** [comment]
libdir is not set properly without the need for any patch. Thanks!

I now use install-shared - so no patch is needed there either

/usr/lib64/libpfring.so.1 link  still is not installed just library itself /usr/lib64/libpfring.so

so 2 out of 3 ;)

**Comment by cardigliano** [comment]
> On 27 Jan 2018, at 14:19, wmyrda <notifications@github.com> wrote:
> 
> libdir is not set properly without the need for any patch. Thanks!
> 
I guess "not" is "now"
> I now use install-shared - so no patch is needed there either
> 
Ok
> /usr/lib64/libpfring.so.1 link still is not installed just library itself /usr/lib64/libpfring.so
> 
Do you mean libpfring.so.7.0.0 ?
> so 2 out of 3 ;)
> 
:-)

Alfredo

**Comment by wmyrda** [comment]
> I guess "not" is "now"

yes You are right. I meant  "Now"

> Do you mean libpfring.so.7.0.0 ?

I am not sure why suricata looks for .1 instead of real library number, but it could that it finds no number present therefore it expects it to be "1". Libraries on the other hand usually install symlinks to the real library version number. If proper is to have libpfring.so.7.0.0 than it could follow example of other like libvpx which has following:

/usr/lib64/libvpx.so -> libvpx.so.4.1.0*
/usr/lib64/libvpx.so.4 -> libvpx.so.4.1.0*
/usr/lib64/libvpx.so.4.1 -> libvpx.so.4.1.0*
/usr/lib64/libvpx.so.4.1.0*

**Comment by cardigliano** [comment]
Please check latest dev code and let us know, I added symlinks with the version.

**Comment by wmyrda** [comment]
If that change https://github.com/ntop/PF_RING/commit/635af1a2ef964c4aa8e96067ca82d8591734afd0 was to bring symlinks to the library than I must say did not get any. Besides after that change includes by default didn't install in /usr/include but in /include which is probably not something that one would want

**Comment by cardigliano** [comment]
@wmyrda that patch was not intended to bring symlinks, I ported symlinks to dev too, and fixed the prefix. Please update and let me know if everything works now.

**Comment by wmyrda** [comment]
Includes installed properly. Links got created too

-rwxr-xr-x 1 root root 490456 02-13 09:42 /usr/lib64/libpfring.so*
lrwxrwxrwx 1 root root     24 02-13 09:42 /usr/lib64/libpfring.so.7 -> //usr/lib64/libpfring.so*
lrwxrwxrwx 1 root root     24 02-13 09:42 /usr/lib64/libpfring.so.7.1.0 -> //usr/lib64/libpfring.so*

, but build system says following:

 * QA Notice: Found an absolute symlink in a library directory:
 *            usr/lib64/libpfring.so.7 -> /tmp/portage/net-libs/pf_ring-7.0.3/image//usr/lib64/libpfring.so
 *            It should be a relative symlink if in the same directory
 *            or a linker script if it crosses the /usr boundary.

 * QA Notice: Found an absolute symlink in a library directory:
 *            usr/lib64/libpfring.so.7.1.0 -> /tmp/portage/net-libs/pf_ring-7.0.3/image//usr/lib64/libpfring.so
 *            It should be a relative symlink if in the same directory
 *            or a linker script if it crosses the /usr boundary.

This seems what we should be after
-rwxr-xr-x 1 root root 490456 02-13 09:42 /usr/lib64/libpfring.so*
lrwxrwxrwx 1 root root     12 02-13 09:46 /usr/lib64/libpfring.so.7 -> libpfring.so*
lrwxrwxrwx 1 root root     12 02-13 09:46 /usr/lib64/libpfring.so.7.1.0 -> libpfring.so*

PS I rebuilded suricata and for some reason it is still looking for /usr/lib64/libpfring.so.1 I am not sure why, but it might be something on part of their build system.

**Comment by cardigliano** [comment]
Here you go https://github.com/ntop/PF_RING/commit/d475ba4a9b0e2570bd3f8bf758c36067d3d9f778

**Comment by wmyrda** [comment]
That was fast :) Working fine now! Issue may be marked as fixed.
