### ISSUE TITLE
PF_RING fails to compile on ARM

### ISSUE THREAD

**Issue by Pigi-102** [ntop/PF_RING#319]
I'm trying to compile PF_RING on a raspberry 3 and is failing with this message:
make -C /lib/modules/4.9.5-v7-arm/build SUBDIRS=/root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src modules
make[1]: Entering directory '/usr/src/linux-4.10.0next20170224'
  CC [M]  /root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o
/root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8345:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ndo_get_stats64 = e1000e_get_stats64,
                     ^
/root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8345:21: note: (near initialization for âe1000e_netdev_ops.ndo_get_stats64â)
/root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.c:8372:2: error: #endif without #if
 #endif /* HAVE_NET_DEVICE_OPS */
  ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:295: /root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src/netdev.o] Error 1
make[1]: *** [Makefile:1494: _module_/root/ntopng/PF_RING/drivers/intel/e1000e/e1000e-3.2.7.1-zc/src] Error 2
make[1]: Leaving directory '/usr/src/linux-4.10.0next20170224'
make: *** [Makefile:259: default] Error 2

Actually my setup is : 
Hardware raspberry pi3
Distro   Slackware for arm 14.2 
Output from uname -a: Linux  4.9.5-v7-arm #1 SMP Wed Jan 25 22:34:57 GMT 2017 armv7l BCM2835 GNU/Linux
gcc -v output:
Reading specs from /usr/lib/gcc/arm-slackware-linux-gnueabi/5.4.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/arm-slackware-linux-gnueabi/5.4.0/lto-wrapper
Target: arm-slackware-linux-gnueabi
Configured with: ../gcc-5.4.0/configure --with-march=armv7-a --with-float=hard --disable-werror --prefix=/usr --mandir=/usr/man --infodir=/usr/info --libdir=/usr/lib --enable-bootstrap --enable-checking=release --with-system-zlib --disable-libunwind-exceptions --with-python-dir=/lib/python2.7/site-packages --enable-libstdcxx-dual-abi --with-default-libstdcxx-abi=gcc4-compatible --enable-shared --enable-languages=ada,c,c++,fortran,go,java,objc,lto --enable-objc-gc --enable-threads=posix --enable-__cxa_atexit --enable-libssp --enable-lto --with-gnu-ld --verbose --enable-java-home --with-java-home=/usr/lib/jvm/jre --with-jvm-root-dir=/usr/lib/jvm --with-jvm-jar-dir=/usr/lib/jvm/jvm-exports --with-arch-directory= --with-antlr-jar=/root/slackware64-current/source/d/gcc/antlr-runtime-3.4.jar --enable-java-awt=gtk --disable-gtktest --disable-install-libiberty --host=arm-slackware-linux-gnueabi --build=arm-slackware-linux-gnueabi --target=arm-slackware-linux-gnueabi
Thread model: posix
gcc version 5.4.0 (GCC) 

2017-10-20 PF_RING 7.0
This is what is into the first lines of Changelog file.

The environment come from a git pull made today.

Is there any workaround to this ?

Thanks

Pigi-102

**Comment by Pigi-102** [comment]
I forgot:
2017-10-20 PF_RING 7.0
This is what is into the first leins of Changelog file.
The environment cose fron a git pull made today.
Thanks

Pigi-102

**Comment by cardigliano** [comment]
@Pigi-102 do you really need to compile the e1000e driver on raspberry?

**Comment by Pigi-102** [comment]
@cardigliano  absolutelly not, but following the instruction to compile there is no information on how to avoid the compilation.

I will try to modify the Makefile to see if I can avoid it .

**Comment by Pigi-102** [comment]
After removed the driver from makefile It built correctly.
Unfortunally there is another problem, but I will open a new issue for it.
Thanks a lot.

**Comment by jonbackhaus** [comment]
@Pigi-102 -- can you provide some additional detail on how you got PF_RING to compile on ARM? I'm trying to compile for the ODROID XU4 (ARMv7) inside an Ubuntu Docker container and having a hell of a time getting things running. Any help you can provide would be greatly appreciated. Thank you!!

**Comment by Pigi-102** [comment]
@jonbackhaus The fix, in my case, has been to remove the "cd intel; make " in the PF_RING/drivers Makefile

Nothinkg more than this
HTH

**Comment by jonbackhaus** [comment]
@Pigi-102 Thanks for that. On @cardigliano 's recommendation, I pulled the latest `dev` branch and rebuilt successfully. Oddly, it's not allowing me to install the `pf_ring.ko` module but we'll cross that bridge...
