### ISSUE TITLE
Machine crashes with ZC i40e driver v1.5.18

### ISSUE THREAD

**Issue by RaD-Andrew** [ntop/PF_RING#321]
Dear All,

This initial post is a fact-finding mission to determine what's needed from us (e.g. dmesg output) to progress a machine instability issue.

I should stress that the machine crashes outlined here have been observed using the PF_RING zc example apps (e.g. zcount et al), as well as via our own application.

**BACKGROUND**

For some time now we have been successfully using PF_RING v6.4.1 in production, with 82599-based NICs and PF_RING's ixgbe driver.  The underlying OS is RHEL 6.9 on all machines, and we capture in zero-copy mode (e.g. from zc:eth0).

We have some new machines, still running RHEL 6.9, but with X710-based NICs, and we're having machine stability problems with PF_RING's i40e driver.  More on our observations shortly.

I'm aware that v2.x of this driver (as ships with PF_RING 7.0.0) has been flagged as problematic by Alfredo.  v6.4.1 and 6.6.0 of PF_RING appear to have the same i40e driver version, and we have indeed observed machine crashes with both these versions of PF_RING.  For now, until advised otherwise, we're persisting with v6.4.1.

**OBSERVATIONS**

The init procedure is the familiar:-
  *   pfring_zc_create_cluster()
  *   pfring_zc_create_buffer_pool()
  *   pfring_zc_open_device()
  *   pfring_zc_create_queue()
  *   pfring_zc_run_balancer()

Either at some point during this process. or packets start to arrive, I'm not sure which yet, the machine will crash and reboot.

I'm unclear of the precise pattern to yield instability, as sometimes we start out app and all is well, and sometimes the machine dies.  I'm working on gathering more info for you.

Once in an unstable state, it appears as if instability can survive a machine reboot.  So a machine has just come back up, I've performed an i40e 'load_driver.sh', started our app, and the machine has died again.  I have asked our IT Ops people to power-cycle the machine (it is geographically remote from me), and I'm expecting a load_driver/app start cycle to succeed.

Any and all comments welcome.
Regards,
A.

**Comment by cardigliano** [comment]
Hi @RaD-Andrew 
Are you able to receive any packet before the crash? Does it crash as soon as a packet is received?
Are you able to check that the same happens with PF_RING 7.0 or dev, using i40e v.2.3.6 ?
Do you have any trace of the crash? I understand that the machine instantly reboots, so I guess you have no trace.
Thank you

**Comment by RaD-Andrew** [comment]
Hi Alfredo,

I'll check all of these things and will come back to you.
Regards,
A.

**Comment by RaD-Andrew** [comment]
Hi again Alfredo,

**With PF-RING v6.4.1 and i40e v1.5.18 in play**

The machine crash happens after pfring_zc_open_device(), but before pfring_zc_create_queue().

I currently don't have additional tracing - any particular requests?


**With PF-RING-dev and i40e v2.3.6 in play**

I have started and stopped our app several times, and all seems well with reliability and packet reception.

What is your roadmap/timeline for the dev branch making it to a release?

Regards,
A.

**Comment by cardigliano** [comment]
@RaD-Andrew what about PF_RING 7.0 stable?

**Comment by RaD-Andrew** [comment]
With PF_RING-7.0.0-stable.zip (currently showing as 31 commits ahead of the 7.0.0 release), and i40e v2.3.6 as shipped in the 7.0.0-stable ZIP, all seems to work nicely.

The i40e v2.2.4 as to be avoided if I understand correctly.

Do you know when the 7.0.0-stable branch will make it to a release?

A.

**Comment by cardigliano** [comment]
If you use our stable repository at http://packages.ntop.org you already get 7.0 with latest fixes

**Comment by RaD-Andrew** [comment]
OK - thanks for your help Alfredo.

If all seems well after a couple of days, I'll mark this issue as closed.
A.

**Comment by RaD-Andrew** [comment]
After a "tidy up" of the machine (i.e. removal of anything PF_RING related *other* than PF_RING-7.0.0-stable, our application builds but won't start:-

error while loading shared libraries: libpfring.so.1: cannot open shared object file: No such file or directory

libpfring.so and libpfring.a have been built, and are in PF_RING-7.0.0-stable/userland/lib.

C_INCLUDE_PATH, LIBRARY_PATH and LD_LIBRARY_PATH all look correct.

Puzzled, and continuing to investigate, but suggestions welcome.

A.

**Comment by RaD-Andrew** [comment]
Correction:-

libpfring.so. and libpfring.a have been built

(i.e. not so.1, but this appears to be the same behaviour as a 6.4.1 build).

A.

**Comment by RaD-Andrew** [comment]
**Some clarification:-**

Within the PF_RING code base, we do a 'make' but *never* a 'make install'.  For a 6.4.1 install we'd export these environment vars:-

export C_INCLUDE_PATH=/root/PF_RING-6.4.1/userland/lib:/root/PF_RING-6.4.1/userland/libpcap:/root/PF_RING-6.4.1/kernel/
export LIBRARY_PATH=/root/PF_RING-6.4.1/userland/lib:/root/PF_RING-6.4.1/userland/libpcap:/usr/local/lib/
export LD_LIBRARY_PATH=$LIBRARY_PATH

This has worked well thus far.

For a 7.0.0 or 7.0.0-stable build, this approach yields the shared library error.

Continuing to investigate...
A.

**Comment by RaD-Andrew** [comment]
I did a manual:-
ln -s libpfring.so libpfring.so.1
in
/root/PF_RING-7.0.0-stable/userland/lib
to fix the shared lib problem.

Assuming one more successful over-night run, I'l mark this thread as closed tomorrow am.
A.
