### ISSUE TITLE
pfring_zc_pkt_buff len

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#329]
Which fields are included in the value pfring_zc_pkt_buff length?

https://en.wikipedia.org/wiki/Ethernet_frame

**802.3 Ethernet packet and frame structure:**
Preamble 7 octets
Start of frame delimiter 1 octet

L2:
MAC destination 6 octets
MAC source 6 octets
802.1Q tag (optional) (4 octets)
Ethertype (Ethernet II) or length (IEEE 802.3) 2 octets
L3+:
Payload 46‑1500 octets

Frame check sequence (32‑bit CRC) 4 octets
Interpacket gap 12 octets

pfring_zc_pkt_buff length =
L2 (macs, vlan (optional), etherType) + (L3+) + Frame check sequence (32‑bit CRC)
It's correct?

I want get value
Payload 46‑1500 octets

How right way to calculate this?

**Comment by cardigliano** [comment]
pfring_zc_pkt_buff length include octets from the L2 header to the end of the payload (maximum length is 1514 + vlan on a standard MTU of 1500 bytes)

**Comment by andyarus** [comment]
Thanks!
