### ISSUE TITLE
Suricata compilation issues with pf_ring

### ISSUE THREAD

**Issue by dspransy** [ntop/PF_RING#33]
I'm attempting to compile Suricata on RHEL7 with pf_ring (stable, 6.1.1 rpm) support (for use with ZC), but I'm getting the following error at compile time:

 
./configure --prefix=/usr --sysconfdir=/etc --enable-pfring --with-libpfring-includes=/usr/local/include --with-libpfring-libraries=/usr/local/lib --with-libnspr-includes=/usr/include/nspr4/ --with-libnspr-libraries=/usr/lib64/ --with-libcap_ng-libraries=/usr/lib64/
...
checking for pfring_open in -lpfring... no
checking for pfring_stats in -lpfring... no

   ERROR! --enable-pfring was passed but the library was not found or version is >4, go get it
 
   from http://www.ntop.org/PF_RING.html

I found reference to this issue somewhere else and they suggested adding the following before running ./configure: "LIBS="-lrt -lnuma"

Adding that statement allows configure to get past the pf_ring check, but appears to cause other library checks to fail later on.

**Comment by cardigliano** [comment]
What are the "other library checks" failing?
