### ISSUE TITLE
pf_ring.c has a static minimum and maximum packet size

### ISSUE THREAD

**Issue by ddosDev** [ntop/PF_RING#331]
Within pf_ring.c it seems like there is a hardcoded max MTU. The minimum isn't very important because packets will always either be this size or larger (at least I'm pretty sure).

`#define RING_MIN_SLOT_SIZE    (60+sizeof(struct pfring_pkthdr))`
`#define RING_MAX_SLOT_SIZE    (1514+sizeof(struct pfring_pkthdr))`

What action does pf_ring take when a received packet exceeds this MTU size? It seems like packets above them don't even get received in pf_ring (from various tests).

Can you clear this up? Is there any way to increase that MTU size to be able to receive oversized UDP packets? This is especially important when using pf_ring in an IDS setup to analyze reflected DDoS traffic. DNS, NTP, memcached all send oversized UDP packets and I'd like to be able to pick them up and analyze them.

Thanks for your time and expect a prompt response.

**Comment by cardigliano** [comment]
@ddosDev RING_MAX_SLOT_SIZE is not really used, pf_ring works for me with jumbo frames, what card/drivers are you using?

**Comment by ddosDev** [comment]
i40e with an Intel x710 NIC.

**Comment by cardigliano** [comment]
What PF_RING version are you using? Are you using ZC?

**Comment by ddosDev** [comment]
PFRING_ZC v.7.1.0.180109

Yes, ZC is really the only solution that has fit my needs perfectly so far. I think the issue is with how other networks in the route may split oversized packets into fragments of MTU size. I have yet to work with jumbo frames but I do look forward to it.

**Comment by cardigliano** [comment]
Can we close this issue then?
