### ISSUE TITLE
PF_RING ZC lost vlan layer in packet

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#333]
Hi, I use PF_RING 6.4.1(also test last version PF_RING 7.0), send one packet with vlan layer, but I recv packet has no vlan layer and zc set ethernet type as IP(0x0800)

this is send packet:
0000   00 0a 49 b6 f9 83 58 6a b1 cc 2d 7d **81 00** 04 92
0010   08 00 45 00 00 28 00 00 40 00 3f 06 03 3c ac 12
0020   00 52 ac 12 e0 1d 1b 59 9c 9d 00 00 00 00 a2 82
0030   61 1f 50 14 00 00 bb a3 00 00 00 00 00 00 00 00

this is recv packet:
0000   00 0a 49 b6 f9 83 58 6a b1 cc 2d 7d **08 00** 45 00
0010   00 28 00 00 40 00 3f 06 03 3c ac 12 00 52 ac 12
0020   e0 1d 1b 59 9c 9d 00 00 00 00 a2 82 61 1f 50 14
0030   00 00 bb a3 00 00 00 00 00 00 00 00

**Comment by cardigliano** [comment]
Please disable vlan stripping offload using ethtool (our init script should do that for you https://github.com/ntop/PF_RING/blob/6.4.1-stable/package/etc/init.d/pf_ring#L173)

**Comment by laoyang103** [comment]
@cardigliano Thank you, I will try
