### ISSUE TITLE
pf_ring license stop working when interfaces are renamed

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#335]
once I rename the following interfaces from:
ens15f0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 68:05:ca:2e:74:c8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens15f1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 68:05:ca:2e:74:c9  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens5f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 68:05:ca:30:67:68  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens5f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 68:05:ca:30:67:69  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

TO:
psdeth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 68:05:ca:2e:74:c8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

psdeth1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 68:05:ca:2e:74:c9  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

psdeth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::9002:e074:e473:4753  prefixlen 64  scopeid 0x20<link>
        ether 68:05:ca:30:67:68  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 528 (528.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

psdeth3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::f1cb:c1a9:59cb:6ecf  prefixlen 64  scopeid 0x20<link>
        ether 68:05:ca:30:67:69  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 876 (876.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

the licensing is stop working.

I amgetting the following errors:
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC license 7.1.0.180326 for psdeth2 [Intel 10/40 Gbit i40e family]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC license 7.1.0.180326 for psdeth3 [Intel 10/40 Gbit i40e family]
# ERROR: Please get one at http://shop.ntop.org/.

Moving the order of loading pf_ring.ko, i40e.ko, and rename_ifs.sh is not solving my issue. However it causes different issues, such as pf_ring won't recognize the interfaces.

Thank you

**Comment by cardigliano** [comment]
@szarea the interface name should not affect the license, please provide the content of /etc/pf_ring/6805CA306768

**Comment by szarea** [comment]
[szarea@psd1 ~]$ cat /etc/pf_ring/6805CA306768
23ADFD7AD03C0A0844682913F465EAF81538352898A2671B94
[szarea@psd1 ~]$

**Comment by szarea** [comment]
any updates???

**Comment by cardigliano** [comment]
@szarea the license seems to be valid for that interface and works for me, we need to debug this a little bit. Please provide the output of "pfcount -L -v 1"

**Comment by szarea** [comment]
Before renaming interfaces
=====================
[root@psd1 ~]# /tmp/pfcount -L -v 1
Name	SystemName	Module	MAC	BusID	NumaNode	Status	License
lo	lo	pf_ring	00:00:00:00:00:00	0000:00:00.0	-1	Up	NotFound
eno1	eno1	pf_ring	0C:C4:7A:86:51:F8	0000:03:00.0	0	Up	NotFound
eno2	eno2	pf_ring	0C:C4:7A:86:51:F9	0000:03:00.1	0	Up	NotFound
eno3	eno3	pf_ring	0C:C4:7A:86:51:FA	0000:04:00.0	0	Up	NotFound
eno4	eno4	pf_ring	0C:C4:7A:86:51:FB	0000:04:00.1	0	Up	NotFound
virbr0	virbr0	pf_ring	52:54:00:7F:1F:12	0000:00:00.0	-1	Up	NotFound
virbr0-nic	virbr0-nic	pf_ring	52:54:00:7F:1F:12	0000:00:00.0	-1	Down	NotFound
zc:ens15f0	ens15f0	pf_ring-zc	68:05:CA:2E:74:C8	0000:02:00.0	0	Up	Valid
zc:ens15f1	ens15f1	pf_ring-zc	68:05:CA:2E:74:C9	0000:02:00.1	0	Up	Valid
zc:ens5f0	ens5f0	pf_ring-zc	68:05:CA:30:67:68	0000:81:00.0	1	Up	Valid
zc:ens5f1	ens5f1	pf_ring-zc	68:05:CA:30:67:69	0000:81:00.1	1	Up	Valid
Segmentation fault (core dumped)


After renaming Interfaces
===================
[root@psd1 ~]# /tmp/pfcount -L -v 1
Name	SystemName	Module	MAC	BusID	NumaNode	Status	License
lo	lo	pf_ring	00:00:00:00:00:00	0000:00:00.0	-1	Up	NotFound
eno1	eno1	pf_ring	0C:C4:7A:86:51:F8	0000:03:00.0	0	Up	NotFound
eno2	eno2	pf_ring	0C:C4:7A:86:51:F9	0000:03:00.1	0	Up	NotFound
eno3	eno3	pf_ring	0C:C4:7A:86:51:FA	0000:04:00.0	0	Up	NotFound
eno4	eno4	pf_ring	0C:C4:7A:86:51:FB	0000:04:00.1	0	Up	NotFound
virbr0	virbr0	pf_ring	52:54:00:7F:1F:12	0000:00:00.0	-1	Up	NotFound
virbr0-nic	virbr0-nic	pf_ring	52:54:00:7F:1F:12	0000:00:00.0	-1	Down	NotFound
zc:psdeth0	psdeth0	pf_ring-zc	68:05:CA:2E:74:C8	0000:02:00.0	0	Up	Valid
zc:psdeth1	psdeth1	pf_ring-zc	68:05:CA:2E:74:C9	0000:02:00.1	0	Up	Valid
zc:psdeth2	psdeth2	pf_ring-zc	68:05:CA:30:67:68	0000:81:00.0	1	Up	Valid
zc:psdeth3	psdeth3	pf_ring-zc	68:05:CA:30:67:69	0000:81:00.1	1	Up	Valid
Segmentation fault (core dumped)

**Comment by szarea** [comment]
please ignore this issue and close it. it was a user error. sorry.
