### ISSUE TITLE
zcount_ipc unable to connect inside of KVM guest

### ISSUE THREAD

**Issue by phantium** [ntop/PF_RING#336]
Hi,

I have both uio and uio_ivshmem loaded, while uio_ivshmem throws "module verification failed: signature and/or required key missing - tainting kernel", should that affect creating /dev/uioX devices?

```
# ls /dev/uio*
ls: cannot access '/dev/uio*': No such file or directory
```

I believe the above is the reason why zcount_ipc is failing to run, resulting in:
```
# zcount_ipc -i 0 -c 99 -u
pfring_zc_ipc_attach_queue error [No such file or directory] Please check that cluster 99 is running
```

I have the KVM host running the following:
```
# zbalance_ipc -i ens1f1 -c 99 -n 2 -m 0 -Q /var/run/qemu-server/100.vnc

```
This appears to be working as intended.

Any ideas on what I could do to resolve this issue?

Thanks in advance!

Phantium

**Comment by cardigliano** [comment]
@phantium did you follow the guide at http://www.ntop.org/guides/pf_ring/vm_support/kvm_zc.html ?
What OS are you running?
The "module verification failed" message can be ignored.

**Comment by phantium** [comment]
@cardigliano Running Ubuntu 16.04 in the VM and the host is the latest proxmox with Debian squeeze, yes I did follow the guide.

**Comment by cardigliano** [comment]
I see that you are passing "/var/run/qemu-server/100.vnc", it does not look like a QMP control socket, please use "-chardev socket,path=/tmp/qmp0,server,nowait,id=qmp0 -mon chardev=qmp0,mode=control" as described in the guide and pass /tmp/qmp0

**Comment by phantium** [comment]
Ahh, I see that now. Thanks, I made a mistake there and did do it correctly before.
/var/run/qemu-server/100.qmp is the right control socket, however it seems to throw:

09/Apr/2018 15:34:22 [zbalance_ipc.c:975] ERROR: pfring_zc_vm_register(/var/run/qemu-server/100.qmp) error

I was happy it was finally working, however it really is not.

/usr/bin/kvm -id 100 -chardev socket,id=qmp,path=/var/run/qemu-server/100.qmp,server,nowait -mon chardev=qmp,mode=control is what is shown as the process.

**Comment by phantium** [comment]
We eventually resolved it by moving the network card into the VM, where it works properly. On the host, it seems to be a daunting task to get it working.

**Comment by cardigliano** [comment]
This has been tested with an Ubuntu 16 Cloud image as guest, running it using 
the utility scripts available at: 
https://github.com/ntop/PF_RING/tree/dev/userland/examples_zc/kvm/host
Please note that the uio module has been updated and it is available at:
https://github.com/ntop/PF_RING/tree/dev/userland/examples_zc/kvm/guest
