### ISSUE TITLE
insmod fails on Ubuntu xenial

### ISSUE THREAD

**Issue by yarick** [ntop/PF_RING#339]
Compiled pf_ring.ko on Ubuntu xenial
Failure

```
insmod  pf_ring.ko 
insmod: ERROR: could not insert module pf_ring.ko: Invalid module format
modprobe pf_ring -v
insmod /lib/modules/4.4.0-121-generic/kernel/net/pf_ring/pf_ring.ko 
modprobe: ERROR: could not insert 'pf_ring': Exec format error
```

Subsequenty compiled from 7-stable and dev branches - same issue.

Has somebody tested this on kernel version 4.4.0-121 ?

```
 kernel: [  987.765622] pf_ring: version magic '4.4.0-121-generic SMP mod_unload modversions ' should be '4.4.0-121-generic SMP mod_unload modversions retpoline '
```

### GCC Test
gcc-5  - fail (default)
gcc-6 - fail
gcc-7 - not tested

**Comment by cardigliano** [comment]
Hi @yarick latest pf_ring dev code from github compiles and loads smoothly on my Ubuntu 16 with kernel 4.4.0-121-generic, did you compile it on the same box?

**Comment by superyarick** [comment]
It compiles now.  Thank you for all the awesome work you guys are doing.

Now,  I am seeing an error with missing header file, when compiling intel ixgbe driver.
Could be related to this commit - 

```
39c39
< #include "../../../../../kernel/linux/pf_ring.h"
---
> #include "pf_ring.h"
2096c2096
```

This issue with pf_ring compile is resolved.  Let me know if you want me to open/fix a separate issue/commit for the include in ixgbe ZC driver.

**Comment by cardigliano** [comment]
Please try with cd PF_RING/drivers/intel/; make

**Comment by superyarick** [comment]
Thanks!   That worked.  I can copy the kernel module manually. 
OR
```
cd /usr/src/PF_RING/drivers/intel/ixgbe/ixgbe-5.0.4-zc/src; make install
```
Just wondering if regular users are running some other install script.

**Comment by cardigliano** [comment]
@superyarick we provide packages at http://packages.ntop.org, and you can use init.d/systemctl as explained at http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html
