### ISSUE TITLE
Time across pfring_send,sendto and pfring_zc_send_pkt

### ISSUE THREAD

**Issue by AnkitAggarwalPEC** [ntop/PF_RING#341]
Hi 
I'm currently calculating the time across the pfring _send and pfring_zc_send_pkt with flush set to be 1.
However the timing seems to be came to around 2 to 3 micros which is same as of linux sendto call. 

As the ZC is bypassing the kernel it should be somewhat less than 2 micros. Please let me know what I can do reduce this number.

**Comment by cardigliano** [comment]
@AnkitAggarwalPEC a few questions:
1. are you opening the interface with the "zc:" prefix?
2. does "micros" mean "usec"?
3. how did you measure this time?
Thank you

**Comment by AnkitAggarwalPEC** [comment]
@cardigliano 
>>does "micros" mean "usec"? 
Yes
>>how did you measure this time?
``` 
clock_gettime(CLOCK_REALTIME ,&startTime);
pfring_zc_send_pkt(zq, &buffers[buffer_id], 1);
clock_gettime(CLOCK_REALTIME ,&endTime);
```
Can you please tell me what is your latency numbers for this function call?

**Comment by cardigliano** [comment]
@AnkitAggarwalPEC that measures just the time for the call, it does not measure the actual time the packet is transmitted on the wire..

**Comment by AnkitAggarwalPEC** [comment]
@cardigliano Can you please tell me how to measure that time? Also I have set the flush parameter as 1 which will flush the data from the nic to the wire. 

My aim of this exercise is to compare the time across the linux sendto call and pfring_zc_send_pk call.
Please let me know how can I do this

**Comment by AnkitAggarwalPEC** [comment]
@cardigliano Any update?

**Comment by cardigliano** [comment]
In order to get an accurate result you need some appliance able to run latency (RTT) tests checking the packet timestamp on the wire (e.g. spirent can run RFC2544 and similar tests). PF_RING also comes with a tool (https://github.com/ntop/PF_RING/blob/dev/userland/examples/pflatency.c) that can be used on another appliance (with ZC to get accurate results) to measure the RTT, however it does not make much sense to use PF_RING to measure PF_RING :-)

**Comment by AnkitAggarwalPEC** [comment]
>> are you opening the interface with the "zc:" prefix?

I used with the zc: prefix just now. I can see the new time around ```pfring_zc_send_pkt``` around in 500 Nanoes. Is that acceptable number compared to the 2 micros earlier.

**Comment by cardigliano** [comment]
I see, however that just gives you an indication of the function call overhead, if you are interested in the real transmission latency you need an external tool. Please also consider that clock_gettime itself has takes some cpu cicle.

**Comment by AnkitAggarwalPEC** [comment]
@cardigliano Can you please provide me the zpflatency like pflatency?

**Comment by cardigliano** [comment]
There is no zpflatency, you can use pflatency using a "zc:" interface

**Comment by AnkitAggarwalPEC** [comment]
@cardigliano Thanks for the previous help

@cardigliano Is there any TCP Stack implemented for the PF_RING? I'm trying to use the PF_RING for my tcp packet sending application. I'm trying to handle TCP Packet resend if the TCP Packet fail to transmit and other feature of packet reordering which is provided in the linux TCP Stack

**Comment by cardigliano** [comment]
We do not provide a TCP stack, however it would be interesting to integrate it with userspace TCP stacks.
