### ISSUE TITLE
Measuring packet traversal time from Hardware(NIC) to Application Time

### ISSUE THREAD

**Issue by AnkitAggarwalPEC** [ntop/PF_RING#342]
Hi

I'm trying to measure the time time difference i.e how much it take to transfer the packet from the NIC to Application time in this case the ``pfcount.c``

I modified the code in function ``print_packet`` as below
```struct timespec x;                                                                                                                                  
   clock_gettimg(CLOCK_REALTIME ,&x);                                                                                                                           
   if(h->extended_hdr.timestamp_ns) {                                                                                                                 
     s = ((h->extended_hdr.timestamp_ns / 1000000000) + thiszone) % 86400;                                                                            
     usec = (h->extended_hdr.timestamp_ns / 1000) % 1000000;                                                                                          
     nsec = h->extended_hdr.timestamp_ns % 1000;                                                                                                      
   } else {                                                                                                                                           
     usec = h->ts.tv_usec;                                                                                                                            
   }
printf("Time to reach User Space=%d" , x.tv_nsec - (usec * 1000 + nsec));
```                                                                                                           

And this is how I'm running this:
``` ./pfcount -i stack:lo -g 1 -s ```
I'm seeing some random time ranging from in 58 to 500 usec which seems to absurd.

Please let me know how can I obtain the correct hardware to application time.

**Comment by cardigliano** [comment]
@AnkitAggarwalPEC please note that the packet timestamp may be not computed in hw depending on the adapter you are using. If you are using an Intel adapter it is computed in software in kernel space (standard drivers) or in userspace (ZC drivers)

**Comment by AnkitAggarwalPEC** [comment]
@cardigliano If the nic have the capability to generate the HW timestamp. Will the ZC Driver still compute the timestamp in the userspace?

**Comment by cardigliano** [comment]
Sorry for late reply, if you have a card supporting hw timestamping, you can measure the time from the nic to the application, however that also assumes that there is no time shift between the card time and the system time.
