### ISSUE TITLE
How can I use i40e and X710 Adapter send 40Gbps traffic ?

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#346]
Hi, I have two X710 Adapter as follow:

> root@localhost:~# lspci | grep Eth
03:00.0 Ethernet controller: Intel Corporation Ethernet 10G 2P X710 Adapter (rev 01)
03:00.1 Ethernet controller: Intel Corporation Ethernet 10G 2P X710 Adapter (rev 01)
06:00.0 Ethernet controller: Intel Corporation Ethernet 10G 2P X710 Adapter (rev 01)
06:00.1 Ethernet controller: Intel Corporation Ethernet 10G 2P X710 Adapter (rev 01)
0a:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection
0b:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection

pci slot is:

> root@localhost:~# dmesg | grep i40e | grep PCI
[    2.648412] i40e 0000:03:00.0: PCI-Express: Speed 8.0GT/s Width x8
[    3.168208] i40e 0000:03:00.1: PCI-Express: Speed 8.0GT/s Width x8
[    3.736218] i40e 0000:06:00.0: PCI-Express: Speed 8.0GT/s Width x8
[    4.244205] i40e 0000:06:00.1: PCI-Express: Speed 8.0GT/s Width x8

cpu is 

> root@localhost:~# cat /proc/cpuinfo | grep CPU
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
model name	: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz

I have enough cpu and memory to use，how can I send and recv 40Gbps traffic?

**Comment by cardigliano** [comment]
@laoyang103 did you install the i40e-zc driver and ran performance tests with pfcount/pfsend? What kind of application do you need to run on this system?

**Comment by laoyang103** [comment]
@cardigliano yes i install i40e-zc driver, run performance tests with zcount and zsend? I only test 10Gbps result, maybe the "Intel Corporation Ethernet 10G 2P X710 Adapter (rev 01)" can only get 10Gbps result.

I have see another issue https://github.com/ntop/PF_RING/issues/230, I see he use "Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 01)".

**Comment by cardigliano** [comment]
X710 is a 10G card, XL710 is 40G

**Comment by laoyang103** [comment]
@cardigliano Thank you for your reply
