### ISSUE TITLE
PF_Ring support for CAN data

### ISSUE THREAD

**Issue by magantiakhilchandra** [ntop/PF_RING#348]
Trying to capture CAN bus data using PF ring. Found a header file with a CAN structure in it.
[https://github.com/ntop/PF_RING/blob/dev/userland/libpcap-1.8.1/pcap/can_socketcan.h](url)

It doesn't open the CAN device to capture the data? Or am I missing some functions? 

Regards.

**Comment by cardigliano** [comment]
@magantiakhilchandra that header file is from libpcap, PF_RING does not have native support for CAN bus

**Comment by magantiakhilchandra** [comment]
Oh okay, thanks for the confirmation. @cardigliano
