### ISSUE TITLE
pfring_zc_open_device with  PF_RING_ZC_IPONLY_RSS |PF_RING_ZC_SYMMETRIC_RSS  flag?

### ISSUE THREAD

**Issue by yuyi2017yuyi** [ntop/PF_RING#349]
I  use funcation pfring_zc_open_device with the   PF_RING_ZC_IPONLY_RSS |PF_RING_ZC_SYMMETRIC_RSS flag  ,but I cann't get the  all  symmetric packets from same NIC queues   on src/dst IP only.How to get the expected result? Thanks a lot!

**Comment by cardigliano** [comment]
@yuyi2017yuyi what is you card model?
It would be also useful to check the traffic you have, could you provide a pcap perhaps? (you can send it to cardigliano@ntop.org)

**Comment by yuyi2017yuyi** [comment]
@cardigliano ,my card is ixgbe(02:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)).The email  containing  pcap file has been sent. Please check the attachment,thanks .

**Comment by cardigliano** [comment]
@yuyi2017yuyi, please note that there is no flag PF_RING_ZC_SYMMETRIC_RSS (we have the asymmetric flag PF_RING_ZC_DEVICE_ASYMMETRIC_RSS, but you should not use it), and PF_RING_ZC_IPONLY_RSS  is actually PF_RING_ZC_DEVICE_IPONLY_RSS.
This said, it seems that running pfring_zc_open_device(zc, device, rx_only, PF_RING_ZC_DEVICE_IPONLY_RSS) works for me with your pcap, everything goes to the same queue.

**Comment by yuyi2017yuyi** [comment]
@cardigliano ,I have used  pfring_zc_open_device(zc, device, rx_only, PF_RING_ZC_DEVICE_IPONLY_RSS) ,it works well ,Thank you very much!
