### ISSUE TITLE
ZC mode will stuck the server

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#351]
Ip netns exec 153 cat /proc/net/pf_ring/dev/eth3/info | grep ZC will show
Polling Mode: ZC/NAP

Sorry for the error. I tpye it wrongly. the above is eth3. so eth3 (data channle) is ZC. not eth1 (control channle with 1Gb/s) .
I first run ip netnes exec 151 iperf -s on another server. there will be two phenomenons:
1. I run  ip netns exec 153 pfcount -i zc:eth3 first, and it will run corrently with 0 packets captured. then I run ip netnes exec 153 iperf -c 192.168.0.151, still 0 pkts captured. 
2 I run  ip netnes exec 153 iperf -c 192.168.0.151 first, and then run ip netns exec 153 pfcount -i zc:eth3 . then server with interface 153 will be stuck, I need to reboot it. another server is fine.

Sorry for the misleading of last answer. i type the interface wrongly.

Thanks a lot.

**Comment by FOSquare** [comment]
In my last question. you said that:"
please note that you cannot run ZC on a management interface, as it disconnects the interface from the system (it is a kernel-bypass technology)"

eth3 is not management interface. I am using eth0 as management interface, while eth3 is used as data interface. 
by chance if you mean the management interface is eth3, and ZC:eth3 will disconnect eth3 from system. then how can we use the pf_ring with zc?
Thanks a lot...

**Comment by cardigliano** [comment]
@FOSquare what do you mean with data interface? Do you have any ip configured on eth3? I guess iperf traffic will go through eth3, you cannot use ZC to capture traffic generated or directed to the same machine (through the linux stack).

**Comment by FOSquare** [comment]
I have 1Gb/s ethernet interface eth0 acted as control channle (For ssh connection from outside network). And 10Gb/s interfaces eth3 and eth4 acted as data channel (conneciton between servers in the network).
I have two servers aether and themis. Their data interface are connected by a 10Gb/s switch.
aether with eth3 (192.168.0.151) and eth4 (192.168.0.152) .
themis with eth3 (192.168.0.153) and eth4 (192.168.0.154) .
I am using iperf -s on eth3 of aether (151). and iperf -c on eth3 (153) of themis for the experiment. The traffic are exchanged between those two servers. they are not on the same machine. Do i explain it clear? Thank a lot.

**Comment by cardigliano** [comment]
@FOSquare if I understand themis is also the machine where you are capturing traffic, as I said you cannot run ZC on an interface which is being used by the linux stack (as you are sending traffic using iperf on that interface). ZC is a kernel-bypass technology, it detached the interface from the linux stack when capturing traffic.

**Comment by FOSquare** [comment]
Yes, sorry for the mis-understanding your meaning before. 
Then I will test the caputring with real applicaitons. If I deploy an media-downloading application on those two servers. aether is acted as the server with media data such as films, while themis is the client that want to fetch films from aether. I should be able to capture the pkts tranmissted between those two interfaces, right? If yes, we can close this issue. 
Apologize again for misunderstanding your meaning due to my poor knowledge on the protocol stack. Thanks again.

**Comment by cardigliano** [comment]
@FOSquare a client application on themis would use the linux stack anyway, you cannot use it in combination with ZC for the same reason.
