### ISSUE TITLE
Wrong RING version: kernel is 16, libpfring was compiled with 17

### ISSUE THREAD

**Issue by bml0aGlu** [ntop/PF_RING#352]
[PF_RING] Wrong RING version: kernel is 16, libpfring was compiled with 17
pfring_open error [No such device] (pf_ring not loaded or interface eno49 is down ?)

**Comment by bml0aGlu** [comment]
cat /proc/net/pf_ring/info 
PF_RING Version          : 7.0.0 (7.0.0-stable:96e916d6f2e3017cff1c8f0d44657b946030d6ce)
Total rings              : 10

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

**Comment by cardigliano** [comment]
@gnithinreddy80 this happens when you have the pf_ring kernel module from the stable loaded, and you use an application from the nigtly builds (or compiled with pf_ring dev). Please make sure everything is in sync.

**Comment by ronygut** [comment]
Got [PF_RING] Wrong RING version: kernel is 20, libpfring was compiled with 21
What needs to be recompiled in order to fix this error?

**Comment by cardigliano** [comment]
Please update the kernel module (pfring-dkms) and make sure it is reloaded (restart the service or reboot the machine)

**Comment by ronygut** [comment]
I'm not using pfring-dkms.
I'm building from source to test the PF_RING FT.
I'm running the ftflow_pcap from examples_ft using static linking of nDPI and pfring

**Comment by ronygut** [comment]
I rebuild the pf_ring.ko and loaded it and it works fine now.
Thanks!
