### ISSUE TITLE
kernel panic 

### ISSUE THREAD

**Issue by jppo** [ntop/PF_RING#353]
Hello,

I get some kernel panics with PF_RING, the machine freeze sometimes during start, sometimes after minutes or even while stopping with panic messages, sometimes the system remain active
[syslog.txt](https://github.com/ntop/PF_RING/files/2086967/syslog.txt)

, another time the machine freeze while stopping.
I enclose the last syslog with 2 problems.

Regards

JP P

**Comment by cardigliano** [comment]
Hi @jppo, what pf_ring version are you using?
Could you provide more details about the configuration? (e.g. what drivers are you using? are you running a native host or containers or virtual machine, any other detail that can be useful).
Thank you

**Comment by jppo** [comment]
Hello, 

The machine runs a Debian 9 Stretch up to date. 
CPU : i3-3220 CPU @ 3.30GHz 
RAM : 16Go 
Disks : 2 * 2To RAID 1 
Kernel : 4.16.6 
EThernet controlers : 
RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06) 
RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 09) 

PF_RING version : 7.1.0 (extracted from pf_ring.ko with "strings")

**Comment by jppo** [comment]
Hello, 

The machine runs a Debian 9 Stretch up to date, no emulator, bare metal system.
CPU    : i3-3220 CPU @ 3.30GHz 
RAM    : 16Go 
Disks  : 2 * 2To RAID 1 
Kernel : 4.16.6 
EThernet controlers : 
1) RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06) 
2) RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 09) 

PF_RING version : 7.1.0 (extracted from pf_ring.ko with "strings") 

If you want other informations ... i can get it.

Regards

JP Pozzi

**Comment by cardigliano** [comment]
@jppo are you running containers, like docker or others? I see some log about namespaces, and I want to try to reproduce this issue using a similar system configuration. Thank you.

Jun  9 14:46:41 kmail kernel: [   17.965504] [PF_RING] Init network namespace         (ptrval)
Jun  9 14:46:41 kmail kernel: [   17.965509] [PF_RING] registered /proc/net/pf_ring/
Jun  9 14:46:41 kmail kernel: [   19.748363] [PF_RING] Init network namespace         (ptrval)
Jun  9 14:46:41 kmail kernel: [   19.748366] [PF_RING] registered /proc/net/pf_ring/

**Comment by jppo** [comment]
Hello, 

Yes that machine is often running KVM systems, but I didn't use them since some weeks as they are now running on another system. 
That other system is similar (but core I5) and SSD disks running a 4.14.43 kernel with PF_RING, Ntopng and Suricata, but I didn't see any kind of kernel crash. 
On the "culprit" system Suricata and NtopNG are also running since ages. 

Regards 

JP Pozzi

**Comment by cardigliano** [comment]
@jppo I added more debug info, could you update the kernel module (pfring-dkms) and provide us the dmesg output again? Thank you.

**Comment by cardigliano** [comment]
This seems to be related to https://github.com/ntop/PF_RING/issues/318, please follow up on that thread, providing some more trace based on latest code with more debug info. Thank you.

**Comment by jppo** [comment]
Hello,

I get the last pf_ring version (pfring_7.1.0-1989) and install it on
the machine with its kernel 4.16.6.
The boot was OK, without any messages ... the machine runs, I will
watch from time to time for log messages.

Regards

Jppo

**Comment by cardigliano** [comment]
Ok thank you, please write updates on issue #318 if any
