### ISSUE TITLE
Inter-VM with ZC questions

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#354]
I found this in the userGuide.
“PF_RING ZC (Zero Copy) is a flexible packet processing framework that allows you to achieve 1/10 Gbit
line-rate packet processing (both RX and TX) at any packet size. It implements zero-copy operations
including patterns for inter-process and inter-VM (KVM) communications.”

So inter-process and inter-VM will not have linux stack invoking, is it? 
if it is the case, Why I can not run two docker containers on two servers? I think inter-VM should be the same as inter-containers.

More general. I do not find a detailed guide for how to deploy the VMs for using the zc driver.  Since zc mode can caputre at around 9.5 Gb/s, there should be pkts on the NIC. Where is the pkts comeing from? Or Why VM will work in zc mode?

A last question, if I want to only record the transmission time, destinaiton and pkt length of the packet, rather than the whole pkt. Can I achieve by zc mode? If not, can I achieve that by write some codes which invokes some functions of pf_ring?

Thanks a lot.

**Comment by cardigliano** [comment]
> So inter-process and inter-VM will not have linux stack invoking, is it?

Correct, in that case ZC uses shared memory.

> if it is the case, Why I can not run two docker containers on two servers? I think inter-VM should be the same as inter-containers.

What do you mean with "run two docker containers on two servers"? Please describe the use case and the traffic path.

> I do not find a detailed guide for how to deploy the VMs for using the zc driver.

We have some guide (e.g. https://github.com/ntop/PF_RING/blob/dev/doc/vm/virsh_hostdev.rst), but again, please describe the use case in order to understand what you are trying to do and provide detailed info.

>  if I want to only record the transmission time, destinaiton and pkt length of the packet, rather than the whole pkt

What do you mean with record? What is the application here? Are you forwarding traffic? Please provide more details as this is too generic.

**Comment by FOSquare** [comment]
1.  I want to build a small home-made Data Center network with around 20 serves (each server has dual NICs).
2.  I want to run Data Center applications such as media-streaming, web-searching and so on in my network.  For easy deploying, I want to install docker on each server. then I just depoly container on the docker (The contanier acts as application). 
(So there may be the case that I deploly the "media-streaming server" with dataset on one node, and "media-straming client" on another node). You told me that it will not work last time. Is there a method to make it works? I think docker is also a kind of virulizaiton. can the zc driver also use the shared memory in this case?
3.  I would like to collect the traces of the applications running in the netwrok on each server, and get the traffic shape of our network traffic. I don't need to get the full packet. the transmission time. packet length and destination are enough for modeling the traffic shape. In other word, I do not care about the payload of the pkt, only care about the header and the transmission time.

4 if ZC driver does not wrok. I know I can use pf_ring for storing the pkts, but pf_ring can not work at 10Gb/s. it start loss pkts at aroud 5Gb/s. Can I just use pf_ring to sample the pkt and then to store the sampling pkts for the modeling of the traffic shape? such as every 100 pkts, i just caputre one pkt and store it. or every 1us, I capture one pkt and store it. Here I also mean I only need to store the transmission time, pkt length and pkt destination. I do not need pkt payload at all. But if I can get the pkt payload also. it is also fine. 

How far can I go with pf_ring and pf_ring with drivers?

Thanks a lot.

**Comment by FOSquare** [comment]
When i use pf_ring for just caputring:
./pfcount -i eth5 
I could see at 1Gb/s, no pkt loss.
However, when I use it for both capturing and storing
./pfcount -i eth5 -o /storage/test1
at bandwidht of 900Mb/s, I could see more than 80% pkts loss.

Is it the case? anyway to avoid the pkt loss for pkt storage? 
Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare please note pfcount is not optimized for dumping traffic, having packet loss with pfcount -o event at 1 Gbit could be normal, please consider using n2disk for that..

**Comment by FOSquare** [comment]
about my last question, do you have any comments? Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare sorry what is the last question?

**Comment by FOSquare** [comment]
This is the background. 
1. I want to build a small home-made Data Center network with around 20 serves (each server has dual NICs).

2. I want to run Data Center applications such as media-streaming, web-searching and so on in my network. For easy deploying, I want to install docker on each server. then I just depoly container on the docker (The contanier acts as application).
(So there may be the case that I deploly the "media-streaming server" with dataset on one node, and "media-straming client" on another node). You told me that it will not work last time. Is there a method to make pf_ring with zc driver works? I think docker is also a kind of virulizaiton. can the zc driver also use the shared memory in this case? 

3 I would like to collect the traces of the applications running in the network on each server, and get the traffic shape of our network traffic. I don't need to get the full packet. the transmission time. packet length and destination are enough for modeling the traffic shape. In other word, I do not care about the payload of the pkt, only care about the header and the transmission time. can pf_ring zc capture the traffic of real applicaitons? It's said that it only works with inter-process and inter-VM, then does it means it can not work with real applications?

4 if ZC driver does not work. I know I can use pf_ring for storing the pkts, but pf_ring can not work at 10Gb/s. it start loss pkts at aroud 5Gb/s. As you already said, it is not optimized for dumping traffic. So can I just use pf_ring to sample the pkt and then to store the sampling pkts for the modeling of the traffic shape? such as every 100 pkts, i just caputre one pkt and store it. or every 1us, I capture one pkt and store it. Here I also mean I only need to store the transmission time, pkt length and pkt destination. I do not need pkt payload at all. But if I can get the pkt payload also. it is also fine.

How far can I go with pf_ring and pf_ring with zc drivers?

Thanks a lot.

And also I post the issues with n2disk under n2disk folder. please also kindly check it when you have time. Thanks again.

**Comment by cardigliano** [comment]
ZC cannot work as it capture traffic directly from the card, detaching it from the operating system, this means that it cannot be used from your streaming application and packet capture at the same time (this regardless of VM or containers). This means that you should use standard pf_ring or capture traffic from another server using a span port or a tap.
As of the data to store, if you want to record metadata (time, len, destination) instead of raw data, you need a custom application for doing that. In other words, PF_RING is just a capture framework, then you need a raw traffic recorder (n2disk) for full rate capture, or a custom application dumping the informations you need.
