### ISSUE TITLE
How do I Verify ZC drivers installation

### ISSUE THREAD

**Issue by bml0aGlu** [ntop/PF_RING#355]
I want to use pf ring with zc drivers for masscan. From masscan documentation "When Masscan detects that an adapter is named something like zc:enp1s0 instead of something like enp1s0, it'll automatically switch to PF_RING ZC mode."

**Comment by cardigliano** [comment]
@gnithinreddy80 I am not familiar with massscan, however according to what you said configuring ZC should be enough, please read http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html
