### ISSUE TITLE
Error in running insmod command

### ISSUE THREAD

**Issue by FahadMaqbool** [ntop/PF_RING#359]
Error in running insmod command

I am not sure what is causing this issue. any help?

root@fahad-OptiPlex-7040:/home/fahad/PF_RING/kernel# insmod pf_ring.ko min_num_slots=8192 enable_tx_capture=0 quick_mode=1
insmod: ERROR: could not insert module pf_ring.ko: File exists

**Comment by cardigliano** [comment]
It seems that pf_ring is already loaded, please check it with lsmod | grep pf_ring

**Comment by FahadMaqbool** [comment]
Thanks.
