### ISSUE TITLE
Compilation issues with PF_RING DNA drivers

### ISSUE THREAD

**Issue by lucaderi** [ntop/PF_RING#36]
With the latest CentOS 6.x kernel, none of the DNA drivers compile anymore.

**Comment by lucaderi** [comment]
> uname -a
Linux centos6.ntop.org 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cardigliano** [comment]
All DNA drivers have been updated (working on latest CentOS 6)
