### ISSUE TITLE
The user scenario of pf_ring zc

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#360]
I felt I was clear last time. But when I think more. I still have confusion. You told me that 
"ZC is meant to be used for monitoring traffic from a network, not from the host itself (which is a special case, and it does not require Zero-Copy capture as the standard driver is able to handle that, as it's the same traffic iperf is generating)"

I read from the guidebook, which are all talking pf-ring and pf_ring zc with NIC on server side. not on switch. Then what do yo mean by "monitoring traffic from a network ,not from the host itself". I think it is used on the host.

Could you kindly provide me with a typical user scenario with a little bit more detail to help me to understand the correct using of pf_ring zc? I know inter-process and inter-KVM use shared memory, zc works under those two cases. 

Thanks a lot. I check the issues of other guys. I find only I was confused with this issue. Sorry for that.

**Comment by cardigliano** [comment]
@FOSquare I did not mean that ZC should run on the switch (you can definitely run it on a standard machine), I meant that it should be used to capture traffic from a span port of a switch, or from a tap, or in general to capture traffic from the link, generated by other hosts. In your case traffic is generated by the same host where ZC is running, and this is not possible as ZC is a kernel-bypass technology.
