### ISSUE TITLE
Problem with pfring-dkms update on debian jessie.

### ISSUE THREAD

**Issue by raa0x0** [ntop/PF_RING#361]
When I try to update packages,  I always get the following errors:
```
E: Failed to fetch http://packages.ntop.org/apt-stable/jessie/all/./pfring-dkms_7.2.0_all.deb  Size mismatch
```
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie
```

**Comment by cardigliano** [comment]
@raa0x0 it works for me, same configuration (stable packages on Debian Jessie), please try again with apt-get update

**Comment by raa0x0** [comment]
@cardigliano Fact, the problem was this broken package was still kept on our cache server, manual package removal from cache fixed problem!
