### ISSUE TITLE
Comparison between pf_ring zc and netmap

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#362]
Both solutions are based on ring buffer and kernel by pass technologies. Do you have few words highlight the differences? netmap can also not be used for networking while caputring due to the kernel by pass, right?
Thanks a lot.

**Comment by cardigliano** [comment]
AFAIK what you said is correct, netmap takes over the interface while capturing, same as zc. They are a bit different as ZC fully works in userspace, while netmap uses a combination of kernel driver and userspace code, however the linux stack should be detached from the interface in any case.
