### ISSUE TITLE
Cannot build the kernel resources in NVIDIA TX1 

### ISSUE THREAD

**Issue by ginsongsong** [ntop/PF_RING#367]
Hi all,

I had met the problem in installation the PF_RING of kernel folder.
My linux kernel is 3.10.96-tegra, it's higher than 2.6.11. 
Is it a problem that nvidia changed some important kernel features which are the PF_ring needs it?  

root@tegra-ubuntu:/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel# make
make -C /lib/modules/3.10.96-tegra/build SUBDIRS=/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel EXTRA_CFLAGS='-I/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel -DGIT_REV="\"dkms-revision:62b704725f65b9f5234f6978d153a8be59e885ca\""' modules
make[1]: Entering directory '/usr/src/linux-headers-3.10.96-tegra'
  CC [M]  /media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel/pf_ring.o
scripts/basic/fixdep: 1: scripts/basic/fixdep: Syntax error: "(" unexpected
scripts/Makefile.build:314: recipe for target '/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel/pf_ring.o' failed
make[2]: *** [/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel/pf_ring.o] Error 2
Makefile:1237: recipe for target '_module_/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel' failed
make[1]: *** [_module_/media/ubuntu/DATA/NetCheck/PF_RING_revision/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.10.96-tegra'

**Comment by cardigliano** [comment]
@ginsongsong it seems that your kernel has some issue with the linux headers scripts, not directly related to pf_ring. Unfortunately we are not able to help you as this is not a supported kernel..
