### ISSUE TITLE
Trying to link tshark with libpcap aware of pf_ring library

### ISSUE THREAD

**Issue by alvarospunk** [ntop/PF_RING#368]
I am not really sure if this is or not an issue, but I'm trying to link the tshark binary with the libpcap aware pf_ring and the results are very bad, it drops a lot of packets!

I do it by exporting in LD_PRELOAD the path of libpcap aware library (in this case ~/PF_RING/userland/libpcap/libpcap.so.1.8.1).

I don't have any other shared libpcap library and it's dropping a lot of packets

**Comment by cardigliano** [comment]
Hi @alvarospunk, what do you mean with "a lot of packets"? Could you provide some number about your traffic rate and the packet loss? Please note that tshark has some overhead, thus please also run some performance check with pfcount.

**Comment by alvarospunk** [comment]
Yes, sorry, I should have been more specific

In a 60 seconds capture, I obtain 3872 packets and drop 325
I've attempted this 20 times and there's always around 10% packet loss

Nevertheless, if I capture with tcpdump compiled by ntop I never have packet loss

**Comment by alvarospunk** [comment]
Is the shared library located in libpcap folder the one who's pf_ring awareness, or the other one located in libpcap-1.8.1 folder? Maybe I confused them and linked with the non-aware libpcap and that's just the problem

**Comment by cardigliano** [comment]
The libpcap folder is linking to libpcap-1.8.1. However your traffic rate seems to be low, you should not loose traffic in any condition. Could you provide "cat /proc/net/pf_ring/<socket>" while capturing traffic?

**Comment by alvarospunk** [comment]
Here it is

cat /proc/net/pf_ring/dev/enp3s0/info 
Name:         enp3s0
Index:        4
Address:      68:05:CA:2E:F4:85
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel e1000e
TX Queues:    1
RX Queues:    1
Num RX Slots: 0
Num TX Slots: 4096

**Comment by alvarospunk** [comment]
cat /proc/net/pf_ring/info 
PF_RING Version          : 7.2.0 (7.2.0-stable:68eb78aa6f72b736e60f949c0e6b964681095449)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

**Comment by cardigliano** [comment]
You should find another file in the same folder, containing the pid of the application in the file name, and socket informations as content (if you do not have such file, you are not capturing with pfring)

**Comment by alvarospunk** [comment]
Do you mean this?

cat /proc/net/pf_ring/15436-enp3s0.383 
Bound Device(s)    : enp3s0
Active                 : 1
Breed                  : Standard
Appl. Name             : <unknown>
Socket Mode            : RX+TX
Capture Direction      : RX+TX
Sampling Rate          : 1
IP Defragment          : No
BPF Filtering          : Disabled
Sw Filt Hash Rules     : 0
Sw Filt WC Rules       : 0
Sw Filt Hash Match     : 0
Sw Filt Hash Miss      : 0
Hw Filt Rules          : 0
Poll Pkt Watermark     : 1
Num Poll Calls         : 696208
Poll Watermark Timeout : 0
Channel Id Mask        : 0xFFFFFFFFFFFFFFFF
VLAN Id                : 65535
Slot Version           : 17 [7.2.0]
Min Num Slots          : 4096
Bucket Len             : 65535
Slot Len               : 65584 [bucket+header]
Tot Memory             : 268644352
Tot Packets            : 399584
Tot Pkt Lost           : 25294
Tot Insert             : 399584
Tot Read               : 399584
Insert Offset          : 162512616
Remove Offset          : 162512616
Num Free Slots         : 4096
TX: Send Ok            : 0
TX: Send Errors        : 0
Reflect: Fwd Ok        : 0
Reflect: Fwd Errors    : 0

**Comment by cardigliano** [comment]
Yes, it seems that the application does not capture the traffic fast enough, please try increasing the ring size with the min_num_slots parameter (when loading pf_ring.ko) to handle bursts, the default value is 4096, try with a higher value like 65536

**Comment by alvarospunk** [comment]
Ok, thank you very much, I'll try now with 65536 slots
That's the number of slots of the circular buffer, I guess

**Comment by alvarospunk** [comment]
In 2 hours I post results

**Comment by alvarospunk** [comment]
Wow, I set the slots to 65536 and I've being now capturing with no packet loss at all.
Then I increased transfer rate and it's capturing in 60 seconds 100% of 40000 packets.
It seems now it's all working with the new conf

Thank you very much!!! I guess you can close the issue
