### ISSUE TITLE
Can't build example_zc in NVIDIA TX2 with intel X540-T2

### ISSUE THREAD

**Issue by obligingxx** [ntop/PF_RING#369]
I want to install PF_RING-7.0.0 in NVIDIA TX2 with intel X540-T2.
Install according to userGuide, but when I into example_zc folder do make it show 
make: Nothing to be done for 'all'.
Example folder can make successful , I need to use zero-copy example and function so how do I modify the Makefile or another ways ?
My linux kernel is 4.4.38-tegra and my OS is Ubuntu 16.04 LTS.

**Comment by cardigliano** [comment]
You can get the "Nothing to be done" message in 2 cases: 
1. when applications have already been compiled (you should see the executables)
2. when the ZC library has not been detected for your arch, please run:
 PF_RING/userland$ ./configure
and check for this line:
checking PF_RING ZC support... yes

**Comment by obligingxx** [comment]
Hi, thanks for your reply, I can't see checking PF_RING ZC support... yes when ./configure and in example_zc folder have no any *.o file or execution file , is that ZC does not support arm-based system whether use intel NIC card ?

**Comment by cardigliano** [comment]
@obligingxx ZC supports x86 only, sorry I didn't realize you are running the NVIDIA TX2 arch.
