### ISSUE TITLE
PF_RING-7, compiling this module，“make” error

### ISSUE THREAD

**Issue by hom7** [ntop/PF_RING#370]
my server
=========
Linux p2p-tw-2 4.13.0-1019-gcp #23-Ubuntu SMP Thu May 31 16:13:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
===============

![aaaaaa](https://user-images.githubusercontent.com/15682396/42371700-d21d5760-8142-11e8-93c2-ddf9347790cf.png)

**Comment by cardigliano** [comment]
Hi @hom7, please note that only Ubuntu LTS official kernels are supported,
however we do our best supporting all kernels, and I recommend you checking
latest code from github (not sure about what version you are running)

**Comment by hom7** [comment]
my server :Ubuntu 16.04.4 LTS

**Comment by cardigliano** [comment]
@hom7 it seems that you are running a non official kernel by Google Cloud

**Comment by hom7** [comment]
Google cloud kernel does not support?

**Comment by cardigliano** [comment]
@hom7 as I said we do our best to support all kernels, however we do not officially support it as we do not have it in our lab. Please check latest dev code from github and report the errors you get in case, we will try to support it.

**Comment by hom7** [comment]
Ok, I am looking at it, thank you.

**Comment by hom7** [comment]
Does pf_ring have a command to view traffic?

**Comment by cardigliano** [comment]
Do you mean a tool for dumping traffic stats on an interface like packets and bytes? You can use pfcount -i <interface>

**Comment by hom7** [comment]
These modules are used, but aren't sure if they work, is there any effective way to confirm the use?
![12222133](https://user-images.githubusercontent.com/15682396/42547501-10126744-84f5-11e8-9cfe-a2b532f1c6f8.png)

**Comment by cardigliano** [comment]
Do you want to check if this application is using pf_ring for capturing traffic? When an application is running on pf_ring, a new file per socket is created under /proc/net/pf_ring/

**Comment by hom7** [comment]
Are you referring to this? Looks like my application pf_ring doesn't work.


![ttttt](https://user-images.githubusercontent.com/15682396/42556680-f1c45412-851e-11e8-9e9a-0764eb94e602.png)

**Comment by cardigliano** [comment]
Are you able to capture traffic with pfcount on the same interface?

**Comment by hom7** [comment]
Ok, I understand, thank you very much.
