### ISSUE TITLE
pfcount with bpf reports drops upon traffic bursts

### ISSUE THREAD

**Issue by BilldePing** [ntop/PF_RING#372]
While using PF_RING 6.4 I've encountered packet drops whilst using pfcount on a zc enabled x520 intel ixgbe nic receiving less than 1Gbps of traffic on average.

Using pfcount I see on average 100 packets that meet the filtering conditions.
Every once in a while though, a burst of 10k packets that meets the bpf conditions arrives and I see that pfcount is experiencing 90% drops from that burst.

**Comment by cardigliano** [comment]
Hi @BilldePing, please avoid sending the same issue here and on the ml, 
btw this is the right place for issues. 
Filtering happens in userspace after that the packet has been captured in the 
standard ZC way. It seems that you have bursts that the bpf engine is not able 
to handle (10k packets is just what is passing the filter), please check the total 
traffic before bpf to see what is the peak rate.
Please also update to latest stable (7.2) as we no longer support 6.4.
