### ISSUE TITLE
PF-ring driver is queuing income packets up to 4 packets prior to releasing them to application. #371

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#374]
This is continuation of issue #371 (I don't how to reopen the issue).

Thank you for the patch. I have been testing the patch since your last posting.

Patch fix some issue bout the problem still exits.
You can create the problem with two interfaces.
/tmp/zcount -c 2 -g 14 -i zc:psdeth3
/tmp/zsend -c 1 -g 20 -i zc:psdeth3 -p 1 -l 125
/tmp/zcount -c 4 -g 16 -i zc:psdeth2
/tmp/zsend -c 3 -g 22 -i zc:psdeth2 -p 1 -l 125
Everything look great if you run the following set of commands separately
Command set one
/tmp/zsend -c 3 -g 22 -i zc:psdeth2 -p 1 -l 125
/tmp/zcount -c 2 -g 14 -i zc:psdeth3
command set Two
/tmp/zsend -c 1 -g 20 -i zc:psdeth3 -p 1 -l 125
/tmp/zcount -c 4 -g 16 -i zc:psdeth2

However, as soon as you try to run them all together then you see the same issue in one the pairs:
/tmp/zcount -c 2 -g 14 -i zc:psdeth3
/tmp/zsend -c 1 -g 20 -i zc:psdeth3 -p 1 -l 125
/tmp/zcount -c 4 -g 16 -i zc:psdeth2
/tmp/zsend -c 3 -g 22 -i zc:psdeth2 -p 1 -l 125

I also see another issue which may be related to the above issue.
PSD application creates One Cluster for both interfaces and opens four devices using pfring_zc_open_device().

The issue I see is that when I’ll start polling driver for read both interfaces. Packets arrive in batch.
I have a tight loop which polls the driver for both interfaces via pfring_zc_recv_pkt and after receiving a packet that packet gets forward to other interface via pfring_zc_send_pkt().

The packest arrive from one interface and they leave from another interface.
For example a packet arrive from psdeth0 and leaves the application from psdeth1.
                         pfring_zc_recv_pkt()
Psdeth0 ---------------------------------> Driver
              <-------------------------------- Packet
                      prfring_zc_send_pkt()
Psdeth1 -------------------------------> Driver

1532208960 INFO syslog : devName:[zc:psdeth0@0], devIndex:[0]. Queue_Id:[1048576], Interface_Index:[16], Queue_is_device:[Yes], Queue_Info.buffer_len:[2048], Queue_Info.metadata_len:[40] Queue_Speed:[10000]

1532208961 INFO syslog : devName:[zc:psdeth0@0], devIndex:[0]. Queue_Id:[1048576], Interface_Index:[16], Queue_is_device:[Yes], Queue_Info.buffer_len:[2048], Queue_Info.metadata_len:[40] Queue_Speed:[10000]

1532208962 INFO syslog : devName:[zc:psdeth1@0], devIndex:[0]. Queue_Id:[1114112], Interface_Index:[17], Queue_is_device:[Yes], Queue_Info.buffer_len:[2048], Queue_Info.metadata_len:[40] Queue_Speed:[10000]

1532208963 INFO syslog : devName:[zc:psdeth1@0], devIndex:[0]. Queue_Id:[1114112], Interface_Index:[17], Queue_is_device:[Yes], Queue_Info.buffer_len:[2048], Queue_Info.metadata_len:[40] Queue_Speed:[10000]

See the attached file for more info:
![pfing](https://user-images.githubusercontent.com/3901825/43040617-9aac5e4a-8cfd-11e8-9493-e551b1a508e1.jpg)

**Comment by cardigliano** [comment]
I reopened #371, please keep posting there. Closing this. Thank you.
