### ISSUE TITLE
Capture from all queues of an interface at the same time?

### ISSUE THREAD

**Issue by alvarospunk** [ntop/PF_RING#375]
1) If I created 1 queue per core (6) per each interface, how can I capture from all interfaces at the same time?

tcpdump -i zc:eth0 will capture from queue 0, and I'd like to capture from all queues

2) Another question, when I load pf_ring module, I can set number of ring slots to 65534, but when I load zerocopy driver (sudo ./load_driver), it returns to be 4096. How could I manage to set it again to 65534?

Thanks

**Comment by cardigliano** [comment]
1. If you want to use tcpdump, you need to use an application able to aggregate from multiple interfaces and forward aggregated traffic to tcpdump. Example:
zbalance_ipc -i zc:eth0@0,zc:eth1@0 -n 1 -c 99
tcpdump -i zc:99@0
2. the number of slots you set for pf_ring applies to the kernel buffer which is used in case of standard drivers, with ZC the number of slots is limited by the card RX ring, which is 4096 or 32768 depending on the card model (we already set the maximum when using our scripts).

**Comment by alvarospunk** [comment]
Thank you very much
