### ISSUE TITLE
Add API call for packet slicing

### ISSUE THREAD

**Issue by lucaderi** [ntop/PF_RING#38]
Modern accelerated NICs include a feature called packet slicing. Even though commodity NICs do not support it, it is necessary to add support for slicing so that PF_RING-based apps can benefit from it. The API call should take (at least) a parameter that specifies at what level slicing will take place (L3, L4....)

**Comment by cardigliano** [comment]
new API pfring_set_packet_slicing
https://github.com/ntop/PF_RING/commit/b11ab48198d6b7b873c3e7673d48fc4c04cac045
