### ISSUE TITLE
pfring_set_tx_watermark() failed [rc=-7]

### ISSUE THREAD

**Issue by xyzheng0706** [ntop/PF_RING#381]
download  the PF_RING version 7.0.0 from the ntop
linux system: 
CentOS release 6.3 (Final)
uname -r 
2.6.32-279.el6.x86_64

Network Interface p2p1: 

Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599

# ./pfsend -i p2p1 -w 1
Sending packets on p2p1
Using PF_RING v.7.0.0
pfring_set_tx_watermark() failed [rc=-7]
Dumping statistics on /proc/net/pf_ring/stats/19219-p2p1.2
TX rate: [current 359'067.48 pps/0.24 Gbps][average 359'067.48 pps/0.24 Gbps][total 359'070.00 pkts]
TX rate: [current 362'850.38 pps/0.24 Gbps][average 360'958.96 pps/0.24 Gbps][total 721'932.00 pkts]

**Comment by cardigliano** [comment]
@xyzheng0706 you get this failure because -w is not supported by the interface/driver you are using. I reworked the failure message into latest code.
