### ISSUE TITLE
Can not send packet with Intel Corporation 82599ES

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#382]
Hi @cardigliano 

I use PF_RING 7.3 and Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
I also use zsend pfsend to send packet follow:

> zsend -i zc:p1p1 -c 66 -r 3.0 -n -1 -l 600
pfsend -i p1p1 -r 1 -n 0 -f /root/allinone-03-09.pcap

it show this:

> Sending packets to zc:p1p1
Estimated CPU freq: 2394183000 Hz
Rate set to 3.00 Gbit/s, 64-byte packets, 4464285 pps
=========================
Absolute Stats: 32'768 pkts - 20'447'232 bytes
=========================
=========================
Absolute Stats: 32'768 pkts - 20'447'232 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================
=========================
Absolute Stats: 32'768 pkts - 20'447'232 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================
^CLeaving...
=========================
Absolute Stats: 32'768 pkts - 20'447'232 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 0.9 sec]
=========================
=========================
Absolute Stats: 32'769 pkts - 20'447'255 bytes
Actual Stats: 11'235.95 pps - 0.00 Gbps [23 bytes / 0.0 sec]
=========================

**Comment by cardigliano** [comment]
What is the output if you do not specify the rate?
zsend -i zc:p1p1 -c 66 -l 600

**Comment by laoyang103** [comment]
the same

Sending packets to zc:p1p1
Estimated CPU freq: 2108100000 Hz
=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
=========================

=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================

=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================

=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================

=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================

=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================

^CLeaving...
=========================
Absolute Stats: 33'025 pkts - 20'607'600 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 0.4 sec]
=========================

=========================
Absolute Stats: 33'026 pkts - 20'607'623 bytes
Actual Stats: 3'831.41 pps - 0.00 Gbps [23 bytes / 0.0 sec]
=========================

**Comment by cardigliano** [comment]
Please provide:
- ethtool p1p1
- cat /proc/net/pf_ring/dev/p1p1/info

**Comment by laoyang103** [comment]
> cat /proc/net/pf_ring/dev/p1p1/info
Name:         p1p1
Index:        8
Address:      90:E2:BA:88:8C:CC
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 32768
Num TX Slots: 32768
root@localhost:~# 

> ethtool p1p1
Settings for p1p1:
        Supported ports: [ FIBRE ]
        Supported link modes:   10000baseT/Full 
        Supported pause frame use: Symmetric
        Supports auto-negotiation: No
        Advertised link modes:  10000baseT/Full 
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: No
        Speed: Unknown!
        Duplex: Unknown! (255)
        Port: FIBRE
        PHYAD: 0
        Transceiver: external
        Auto-negotiation: off
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: no

**Comment by cardigliano** [comment]
Please note that the link is down, this should explain what you see.

**Comment by laoyang103** [comment]
OK, I see it thank you
