### ISSUE TITLE
Is it possible to build a project similar to NetVM using PF_Ring (ZC) APIs?

### ISSUE THREAD

**Issue by niks3089** [ntop/PF_RING#387]
Hi, 

I am researching for a project and I'm trying to build something similar to NetVM using PF Ring. 
Essentially what NetVM does is it uses KVM and Dpdk to run Virtual Network Functions (VNFs) and middle boxes to enable fast VNF chaining. Note that in this approach, the packets will not be consumed by the VM but instead will be forwarded to the next VNF in the service chain or dropped. 
NetVM uses Dpdk and poll mode. Simply put they are the client which uses the dpdk libraries and huge pages. The packet is DMA’ed into the shared memory and the their VM which has NetVM library keeps polling for this and will read/forward the packet pointers if it is interested in it. 

How feasible is it do something similar with PF Ring? Dpdk is too huge for this purpose and I find this suitable for my requirement. Can I do something similar? Can I integrate it with other open source systems for my research? Please let me know.

**Comment by cardigliano** [comment]
Hi @niks3089, did you read about KVM support in PF_RING ZC? It uses a similar approach as the one you described with DPDK, using shared memory for forwarding traffic between host and VMs in zero-copy. Please read http://www.ntop.org/guides/pf_ring/vm/kvm_zc.html

**Comment by niks3089** [comment]
Hi @cardigliano , thanks. Yes I did go through it. I am actually intending to run Unikernels which uses Kvm but not Qemu (It uses another minimalistic monitor). I had intended to modify PF Ring according to this requirement. I guess this is not feasible?

**Comment by cardigliano** [comment]
Hi @niks3089, currently KVM support in PF_RING ZC is based on QEMU components as you noticed, thus it seems this is not a viable solution for you..
