### ISSUE TITLE
pfring_open error [No such device] (pf_ring not loaded or interface eno1 is down ?)

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#389]
My OS is Ubuntu 16.04 LTS.
When i install the pf_ring by the GIT several days before, it works fine, The pf_ring vanilla and zc both work. But when I reboot the server. I type the command again, it told me that "pfring_open error [No such device] (pf_ring not loaded or interface eno1 is down ?)"

I am thinking to re-insert the pf_ring driver. So i type  "sudo insmod pf_ring.ko min_num_slots=8192 enable_tx_capture=0 quick_mode=1" agian.
it says: "ERROR: could not insert module pf_ring.ko: Invalid module format"

When I type " sudo rmmod pf_ring.ko " to first rmove it and insert again. but it says:
It says: rmmod: ERROR: Module pf_ring is not currently loaded.

When i run "systemctl restart pf_ring"

it says: "Failed to restart pf_ring.service: Unit pf_ring.service not found." It seems the pf_ring service disappeared. 

I have seen this issue also on another server, when I reinstall the pf_ring, problem disappear. But It is not a good way to solve the problem. Could you help me to slove it? thanks a lot.

**Comment by cardigliano** [comment]
Hi @FOSquare, please install from packages to use systemd to load pf_ring at boot time as described at http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html

**Comment by FOSquare** [comment]
Thanks, but I need to write some codes with pf_ring. with packages installation I think my codes will not work.....

**Comment by FOSquare** [comment]
I try the repository installtion, and do it as root following the suggestions. 
It works. Thanks a lot. Please let this open for two or three days. If it works stable, we can close it. thanks a lot.
