### ISSUE TITLE
Add port range support Traffic profile s

### ISSUE THREAD

**Issue by brianluers25809** [ntop/PF_RING#391]
Add support for port ranges in traffic profiling.  Appears the nBPF (the format ntop uses) is a different implementation and does not support port ranges at this time even though the nBPF standard does specify port range

portrange port1-port2
True if either the source or destination port of the packet is between port1 and port2.
Any of the above port or port range expressions can be prepended with the keywords, tcp or udp, as in:
tcp src portport

**Comment by cardigliano** [comment]
Hi @brianluers25809, which application/card are you using with nBPF?

**Comment by brianluers25809** [comment]
nTopNG

​​​​​
[cid:image005.jpg@01D43879.341A3CC0]

Brian Luers

Network Architect, Inteliquent

o: 312.348.8824 m: 919.410.0753   24-hr NOC: 866.388.7258

5917 Deep Spring Circle, Wake Forest NC  27587

www.inteliquent.com<http://www.inteliquent.com/> e: brian.luers@inteliquent.com

[cid:image002.png@01D175F9.F92DF460]<http://twitter.com/inteliquent>[Related image]<https://m.facebook.com/OnvoyLLC>[cid:image003.png@01D175F9.F92DF460]<https://www.linkedin.com/company/inteliquent>



The information contained in this message, including any accompanying documents, is confidential and is intended for the addressee(s) only.  The unauthorized use, disclosure, copying, or alteration of this message is strictly forbidden. Please consider the environment before printing this page.

**Comment by cardigliano** [comment]
@brianluers25809 this has been fixed, now you should be able to use:
[protocol] portrange <port1>-<port2>
New packages will be available soon, building right now.
