### ISSUE TITLE
pfsend -i zc:p2p2  send successfully but the receiver cannot receive

### ISSUE THREAD

**Issue by xyzheng0706** [ntop/PF_RING#395]
I download the PF_RING 7.2.0 stable version and use for send traffics.
when i use pfsend -i p2p2 , the traffic are sent successfully, the receiver side can receive right.
when i use pfsend -i zc:p2p2 , the traffic are sent successfully, but the receiver cannot receive any packets.
can you help to check what's the problem?
thanks very much.

[root@g10gen30 examples]# ethtool -i p2p2
driver: ixgbe
version: 5.3.7
firmware-version: 0x8000030d, 14.0.12
bus-info: 0000:42:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

[root@g10gen30 examples]# modinfo /usr/lib/ixgbe.ko 
filename:       /usr/lib/ixgbe.ko
version:        5.3.7
license:        GPL
description:    Intel(R) 10GbE PCI Express Linux Network Driver
author:         Intel Corporation, <linux.nics@intel.com>

[root@g10gen30 examples]# cat /proc/net/pf_ring/info 
PF_RING Version          : 7.2.0 (unknown)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

[root@g10gen30 examples]# cat /proc/net/pf_ring/dev/p2p2/info 
Name:         p2p2
Index:        80
Address:      A0:36:9F:1B:A4:FE
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 32768
Num TX Slots: 32768

[root@g10gen30 examples]# ./pfsend -i zc:p2p2 -v -n 20
Sending packets on zc:p2p2
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.2.0.180626
# license for p2p2 (MAC A0:36:9F:1B:A4:FE) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and          
# transmission limited to 5 minutes
#########################################################################
Using PF_RING v.7.2.0
Dumping statistics on /proc/net/pf_ring/stats/45474-p2p2.9
[0] pfring_send(60) returned 60
[1] pfring_send(60) returned 60
[2] pfring_send(60) returned 60
[3] pfring_send(60) returned 60
[4] pfring_send(60) returned 60
[5] pfring_send(60) returned 60
[6] pfring_send(60) returned 60
[7] pfring_send(60) returned 60
[8] pfring_send(60) returned 60
[9] pfring_send(60) returned 60
[10] pfring_send(60) returned 60
[11] pfring_send(60) returned 60
[12] pfring_send(60) returned 60
[13] pfring_send(60) returned 60
[14] pfring_send(60) returned 60
[15] pfring_send(60) returned 60
[16] pfring_send(60) returned 60
[17] pfring_send(60) returned 60
[18] pfring_send(60) returned 60
[19] pfring_send(60) returned 60
TX rate: [current 82.28 pps/0.00 Gbps][average 82.28 pps/0.00 Gbps][total 20.00 pkts]
Sent 20 packets

**Comment by cardigliano** [comment]
Hi @xyzheng0706, this is weird, the configuration looks good and this is the first time I see a similar issue. Could you try adding -F to pfsend? Thank you.

**Comment by xyzheng0706** [comment]
@cardigliano 
 when i use -F , the traffic seen from the interface still not increase.  it is wired when i not use zc: prefix, the TX packets increased normally,  if i add zc: prefix to send, the TX packets not increase.
when i run load_driver.sh, there is the warning 
"Warning: 512 hugepages available, 1024 requested"
do you think this warning has some impact for the result?

p2p2      Link encap:Ethernet  HWaddr A0:36:9F:1B:A4:FE  
          inet6 addr: fe80::a236:9fff:fe1b:a4fe/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9000  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 b)  TX bytes:9892 (9.6 KiB)
          Memory:d0f00000-d0f80000

**Comment by cardigliano** [comment]
@xyzheng0706 please ignore the output reported by tools reading stats from the kernel, as ZC is a kernel-bypass technology driving directly the network adapter without the kernel intervention.
As of hugepages, please ignore the warning as 512 hugepages are enough for pfsend (otherwise you get a failure running the application)

**Comment by xyzheng0706** [comment]
@cardigliano , that is to say, i can only check the sent correctly from the receiver?  i tried the same version in CentOS Linux release 7.3.1611 (Core)), and it seems the result is right. 
[root@geobladegen7 examples]# ./pfsend -i zc:p3p2
Sending packets on zc:p3p2
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.2.0.180626
# license for p3p2 (MAC A0:36:9F:36:20:3E) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and          
# transmission limited to 5 minutes
#########################################################################
Using PF_RING v.7.2.0
Dumping statistics on /proc/net/pf_ring/stats/38302-p3p2.15
TX rate: [current 11'309'419.59 pps/7.60 Gbps][average 11'309'419.59 pps/7.60 Gbps][total 11'309'544.00 pkts]
TX rate: [current 14'128'885.17 pps/9.49 Gbps][average 12'719'203.83 pps/8.55 Gbps][total 25'439'616.00 pkts]
TX rate: [current 14'135'840.02 pps/9.50 Gbps][average 13'191'414.79 pps/8.86 Gbps][total 39'576'078.00 pkts]
TX rate: [current 14'126'543.81 pps/9.49 Gbps][average 13'425'196.11 pps/9.02 Gbps][total 53'703'201.00 pkts]
TX rate: [current 14'123'579.93 pps/9.49 Gbps][average 13'564'872.43 pps/9.12 Gbps][total 67'827'360.00 pkts]
TX rate: [current 14'114'893.22 pps/9.49 Gbps][average 13'656'543.69 pps/9.18 Gbps][total 81'943'086.00 pkts]
TX rate: [current 14'114'896.37 pps/9.49 Gbps][average 13'722'022.77 pps/9.22 Gbps][total 96'058'674.00 pkts]
TX rate: [current 14'017'791.68 pps/9.42 Gbps][average 13'758'994.76 pps/9.25 Gbps][total 110'077'503.00 pkts]


and when i run the PF_RING in CentOS release 6.5 (Final), the result as below:

**Comment by xyzheng0706** [comment]
[root@g10gen30 examples]# ./pfsend -i zc:p2p1
Sending packets on zc:p2p1
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.2.0.180626
# license for p2p1 (MAC A0:36:9F:1B:A4:FC) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and          
# transmission limited to 5 minutes
#########################################################################
Using PF_RING v.7.2.0
Dumping statistics on /proc/net/pf_ring/stats/12360-p2p1.23
TX rate: [current 32'764.55 pps/0.02 Gbps][average 32'764.55 pps/0.02 Gbps][total 32'768.00 pkts]
TX rate: [current 0.00 pps/0.00 Gbps][average 16'382.76 pps/0.01 Gbps][total 32'768.00 pkts]
TX rate: [current 0.00 pps/0.00 Gbps][average 10'922.04 pps/0.01 Gbps][total 32'768.00 pkts]
TX rate: [current 0.00 pps/0.00 Gbps][average 8'191.60 pps/0.01 Gbps][total 32'768.00 pkts]
TX rate: [current 0.00 pps/0.00 Gbps][average 6'553.32 pps/0.00 Gbps][total 32'768.00 pkts]
TX rate: [current 0.00 pps/0.00 Gbps][average 5'461.12 pps/0.00 Gbps][total 32'768.00 pkts]

**Comment by xyzheng0706** [comment]
@cardigliano can you help to check if the PF_RING ZC mode should upgrade the linux to centOS 7 ?
when i send in centOS 7, the "ifconfig" result for interface p3p2 is increased as the pfsend traffic.
i am confuse about it.

**Comment by cardigliano** [comment]
@xyzheng0706 the ifconfig output depends on the actual drivers, as it works when the driver provides tx stats from the card counters, and it does not work then the driver provides stats computed in sw (as kernel is bypassed). In general it is recommended to check pf_ring stats only.
I see that your last trace is reporting 0 pps, it could be your link is down. Is this the case?

**Comment by xyzheng0706** [comment]
@cardigliano , i check the link through "ethtool p2p1" and the result is "Link detected: yes". i think the link is always up.  but the TX rate in first line is 32768pkts then down to 0.

TX rate: [current 32'764.55 pps/0.02 Gbps][average 32'764.55 pps/0.02 Gbps][total 32'768.00 pkts]
TX rate: [current 0.00 pps/0.00 Gbps][average 16'382.76 pps/0.01 Gbps][total 32'768.00 pkts]

**Comment by cardigliano** [comment]
@xyzheng0706 please note that 32K is the size of the TX ring, this means that the library enqueues 32K packets to the card and then it waits for those packets to be transmitted. This usually occurs when the link is down, however it seems this is not the case from what you said..

**Comment by xyzheng0706** [comment]
@cardigliano thanks for your explain. then i see, that is to say, no packets sent out from the card.

**Comment by cardigliano** [comment]
@xyzheng0706 are you able to provide ssh access to this system perhaps, to debug this issue?

**Comment by xyzheng0706** [comment]
dmesg log shows :

ixgbe 0000:42:00.0: p2p1: NIC Link is Up 10 Gbps, Flow Control: RX/TX
ADDRCONF(NETDEV_CHANGE): p2p1: link becomes ready
ixgbe 0000:42:00.1: p2p2: detected SFP+: 6
ixgbe 0000:42:00.1: p2p2: NIC Link is Up 10 Gbps, Flow Control: RX/TX
ADDRCONF(NETDEV_CHANGE): p2p2: link becomes ready
ixgbe 0000:42:00.0: p2p1: detected SFP+: 5
ixgbe 0000:42:00.0: p2p1: detected SFP+: 5
ixgbe 0000:42:00.0: p2p1: detected SFP+: 5
ixgbe 0000:42:00.0: p2p1: NIC Link is Up 10 Gbps, Flow Control: RX
ixgbe 0000:42:00.1: p2p2: detected SFP+: 6
ixgbe 0000:42:00.1: p2p2: NIC Link is Up 10 Gbps, Flow Control: RX
dmar: DRHD: handling fault status reg 2
dmar: DMAR:[DMA Read] Request device [42:00.0] fault addr ed0400000 
DMAR:[fault reason 06] PTE Read access is not set

I find another similar issue https://github.com/ntop/PF_RING/issues/56 , if they are same issue?

**Comment by cardigliano** [comment]
@xyzheng0706 it definitely seems to be related to dma memory, we need to investigate further in this direction

**Comment by xyzheng0706** [comment]
@cardigliano  
The original version of ixgbe in this CentOS 6.5 system is version: 3.15.1-k.

[root@g10gen30 MME_S1MME]# modinfo ixgbe
filename:       /lib/modules/2.6.32-431.el6.x86_64/kernel/drivers/net/ixgbe/ixgbe.ko
version:        3.15.1-k
license:        GPL
description:    Intel(R) 10 Gigabit PCI Express Network Driver
author:         Intel Corporation, <linux.nics@intel.com>

and the pfring driver ixgbe version is 5.3.7
[root@g10gen30 MME_S1MME]# modinfo /root/xzheng/PF_RING-7.2.0-stable/drivers/intel/ixgbe/ixgbe-5.3.7-zc/src/ixgbe.ko
filename:       /root/xzheng/PF_RING-7.2.0-stable/drivers/intel/ixgbe/ixgbe-5.3.7-zc/src/ixgbe.ko
version:        5.3.7
license:        GPL
description:    Intel(R) 10GbE PCI Express Linux Network Driver
author:         Intel Corporation, <linux.nics@intel.com>


[root@g10gen30 MME_S1MME]# ethtool -i p2p1
driver: ixgbe
version: 5.3.7
firmware-version: 0x8000030d, 14.0.12
bus-info: 0000:42:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes


Should I just upgrade the NVM? 
or should i upgrade both the card driver and NVM?

**Comment by cardigliano** [comment]
@xyzheng0706 are you aware of NVM updates available for your adapter? I am not sure it depends on the nvm version in this case, it could also be related to some Bios (e.g. iommu or shared memory features) setting. Please also try removing iommu in your grub settings if any.

**Comment by xyzheng0706** [comment]
@cardigliano , I removing the iommu in my grub settting , and the pfsend stats now seems normal. 
but i am still confused:  when i use PFRING 5.5.2 version before, the iommu is on, and i can use the DNA feature normally.  now i update the PFRING to 7.0.0/7.2.0 , why need to off the iommu? 
I am very appreciate for your response. thank you very very much.

[root@g10gen30 examples]# ./pfsend -i zc:p2p1
Sending packets on zc:p2p1
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.2.0.180626
# license for p2p1 (MAC A0:36:9F:1B:A4:FC) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and          
# transmission limited to 5 minutes
#########################################################################
Using PF_RING v.7.2.0
Dumping statistics on /proc/net/pf_ring/stats/6439-p2p1.1
TX rate: [current 12'050'199.24 pps/8.10 Gbps][average 12'050'199.24 pps/8.10 Gbps][total 12'050'380.00 pkts]
TX rate: [current 14'757'318.55 pps/9.92 Gbps][average 13'410'918.27 pps/9.01 Gbps][total 26'964'864.00 pkts]
TX rate: [current 14'881'016.85 pps/10.00 Gbps][average 13'899'223.06 pps/9.34 Gbps][total 41'846'238.00 pkts]

**Comment by cardigliano** [comment]
@xyzheng0706, I guess you were using DNA with your old PF_RING installation, in that case memory is allocated from the kernel, instead now it is using hugepages allocated in userspace, that could be the reason. Please try unmounting /dev/hugepages to force pfsend to use kernel memory.

**Comment by xyzheng0706** [comment]
@cardigliano you are right , umount /dev/hugepages also worked for the case.
