### ISSUE TITLE
ftflow Segmentation fault

### ISSUE THREAD

**Issue by marcopp2018** [ntop/PF_RING#397]
Hi,

  I'm trying to use the ftflow example programs, ftflow, ftflow_pcap.
when using with -7 get the following message:

Capturing from eth0 with nDPI support
Segmentation fault

Both nDPI and PF_RING were cloned and compiled from the latest version.

**Comment by cardigliano** [comment]
@marcopp2018 please update to latest code from github and recompile the userspace libraries/examples, I pushed a library update. Please let us know. Thank you.

**Comment by marcopp2018** [comment]
issue fixed
Tx!
