### ISSUE TITLE
Executing PF_Ring ZC as non-root

### ISSUE THREAD

**Issue by onursoyer** [ntop/PF_RING#400]
Hello,

I am unable to execute  PF_Ring ZC as non-root user. This problem is also reported in [here](#245 ) too. 

I already have tried `setcap 'cap_net_admin,cap_ipc_lock,cap_sys_admin=eip'` with no luck.

Is there any solution to fix this?

Thanks.

**Comment by cardigliano** [comment]
Please keep posting in #245. Thank you.
