### ISSUE TITLE
Load nDPI categories by host from file

### ISSUE THREAD

**Issue by marcopp2018** [ntop/PF_RING#401]
Hi,

   I couldn't find any documentation that describes the nDPI categories file structure for -c flag:

`-c <file>       Load nDPI categories by host from file
`
can you give an example how to write such a file?

Thanks.

**Comment by cardigliano** [comment]
Please look at the example referenced in ftflow -h:
https://github.com/ntop/nDPI/blob/dev/example/mining_hosts.txt
