### ISSUE TITLE
IPC send error

### ISSUE THREAD

**Issue by 55-AA** [ntop/PF_RING#402]
I start an IPC master with:

> #zbalance_ipc -c 99 -i Q,Q -n 1 -m 3 -r zc:eth0

then send packets with:

> #./zsend -i zc:99@0
> #./zsend -i zc:99@1

however, not any packet was sent, because the offset 0x14 field in struct pfring_zc_queue returned by pfring_zc_ipc_attach_queue() is 0.  The field should be max_pkt_len, so I force set it to 1536 as follow: 

> index 03666f2..fbac49c 100644
> --- a/userland/examples_zc/zsend.c
> +++ b/userland/examples_zc/zsend.c
> @@ -860,6 +860,7 @@ int main(int argc, char* argv[]) {
>                strerror(errno), cluster_id);
>        return -1;
>      }
> \+    *(u_int32_t *)((u_int64_t)zq + 0x14) = 1563;
>  
>      zp = pfring_zc_ipc_attach_buffer_pool(cluster_id, queue_id);
> 

After build, all packets can be sent successfully.
But I cannot found a exported function by libpfring_zc.so to modify that.

**Comment by cardigliano** [comment]
@55-AA it seems this is working for me using latest code from github, what pf_ring version are you using?

**Comment by 55-AA** [comment]
7.2.0@debian9.4 guest, host is vmware 10 with e1000e.

**Comment by cardigliano** [comment]
@55-AA 7.2 is working for me, could you make sure you update to latest 7.2 code and recompile everything? It looks like something is out of sync in the data structures.

**Comment by 55-AA** [comment]
I update to commit 9acd800(dev) and c93ef24(PF_RING 7.2.0 stable) , the iussus is fixed. but commit 7065ea1(PF_RING 7.2.0 release) is not.

**Comment by cardigliano** [comment]
@55-AA in essence latest revision is working, thank you for the update, we can close this.
