### ISSUE TITLE
License does not work

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#403]
Dear,
        You have kindly give me several licenses of zc pf_ring and n2disk for research. but now I find some of them does not work well on my servers. 
 ls /etc/pf_ring shows
 6CB3113C2154  hugepages.conf   pf_ring.conf   zc
6CB3113C2156  interfaces.conf  pf_ring.start

I create 2 licenses for both of my NIC. but when I use sudo pfcount -i zc:enp1s0f1
it shows
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.2.0.180626
# license for enp1s0f1 (MAC 6C:B3:11:3C:21:56) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and
# transmission limited to 5 minutes

For NIC enp1s0f1, the same problem for zc: pf_ring

And in another server, there is license issue for n2disk

timeout 2m sudo n2disk -i zc:enp1s0f0 -o /traces -b 512 -p 256 --disk-limit 50% -I -A /traces -u fyan -s 40
###################################################
# You do not seem to have a valid n2disk license.
# We're now in demo mode limited to 351 day(s) 05:33:36

I have the license file n2disk10g.license in the folder /etc.

What's might be the problem. The days before today. There seems no problem.

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare could you send me your licenses in a direct email please?

**Comment by FOSquare** [comment]
fine. could you kindly provide your email address? Thanks.

**Comment by cardigliano** [comment]
Please use cardigliano@ntop

**Comment by FOSquare** [comment]
already send to you email. Thanks a lot.
