### ISSUE TITLE
add sampling will prevent the dumping function in pfcount

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#404]
I want to do sampling in the pfcount and then dumpling the traffic on the file. However, When I add 

    case 'I':
      Sampling_Rate = atoi(optarg);         //Sampling rate
      break;
    }

  pfring_set_sampling_rate(pd, Sampling_Rate);

in the pfcount1.c and compile the pfcoun1.c. It will not dump the traffic when I use pfcount1 -i enp1s0f0  -I 10. the command line windows seems good. it can caputre the traffic.

However, when I use  pfcount1 -i enp1s0f0, it works fine.

How can I dump the traffic with a setting sampling rate?  Thanks a lot.

**Comment by FOSquare** [comment]
sorry, I mean when I use pfcount1 -i enp1s0f0 -I 10 -o test.pcap. 
No traffic is dumped. I do not even see the test.pacp file is created.

**Comment by cardigliano** [comment]
Could you provide some stats running pfcount with and without sampling rate for a few seconds? 
1. pfcount1 -i enp1s0f0 -I 10
2. pfcount1 -i enp1s0f0

**Comment by FOSquare** [comment]
1   pfcount1 -i enp1s0f0 -I 10

./pfcount1: invalid option -- 'I'
Using PF_RING v.7.2.0
Capturing from enp1s0f0 [mac: 6C:B3:11:3C:21:74][if_index: 4][speed: 0Mb/s]
# Device RX channels: 4
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/6515-enp1s0f0.20
=========================
Absolute Stats: [22'078 pkts total][0 pkts dropped][0.0% dropped]
[22'078 pkts rcvd][815'285'374 bytes rcvd]
=========================

=========================
Absolute Stats: [44'739 pkts total][0 pkts dropped][0.0% dropped]
[44'739 pkts rcvd][1'656'123'755 bytes rcvd][44'717.08 pkt/sec][13'242.50 Mbit/sec]
=========================
Actual Stats: [22'661 pkts rcvd][1'000.49 ms][22'649.90 pps][6.72 Gbps]
=========================

2  pfcount1 -i enp1s0f0

Using PF_RING v.7.2.0
Capturing from enp1s0f0 [mac: 6C:B3:11:3C:21:74][if_index: 4][speed: 0Mb/s]
# Device RX channels: 4
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/7226-enp1s0f0.22
=========================
Absolute Stats: [17'677 pkts total][0 pkts dropped][0.0% dropped]
[17'677 pkts rcvd][667'837'457 bytes rcvd]
=========================

=========================
Absolute Stats: [36'263 pkts total][0 pkts dropped][0.0% dropped]
[36'263 pkts rcvd][1'373'292'384 bytes rcvd][36'209.37 pkt/sec][10'970.09 Mbit/sec]
=========================
Actual Stats: [18'586 pkts rcvd][1'001.48 ms][18'558.51 pps][5.64 Gbps]


In the first case, invalid option -- 'I' seems to be the problem. Why is it invalid?

**Comment by cardigliano** [comment]
Please use your modified version including -I

**Comment by FOSquare** [comment]
yes, I use the modifed version pfcount1 to carry out th test. But when I add -I parameter, It will said 
invalid option -- 'I'

I already add 
case 'I':
  Sampling_Rate = atoi(optarg);         //Sampling rate
  break;
} in the pfcount1.

Just now, When I change while((c = getopt(argc,argv,"hi:c:C:d:H:l:Lv:ae:n:w:o:p:qb:rg:u:mtsSx:f:z:N:M")) != '?')  to while((c = getopt(argc,argv,"hi:c:C:d:H:l:Lv:ae:n:w:o:p:qb:rg:u:mtsSx:f:z:N:M:I")) != '?') 

Then I compile and run pfcount1 again. 
with pfcount1 -i enp1s0f0 -I 10
It says:
Segmentation fault (core dumped)

And pfcount1 -i enp1s0f0 works fine.

Why I just can not use this parameter as you did in the program? Thanks a lot.

**Comment by FOSquare** [comment]
I  comment the number of threads setting. 
 //case 'n':
    // num_threads = atoi(optarg);
    //  break;

And use parameter to act as sample rate. 
    case 'n':
      Sampling_Rate = atoi(optarg);   
      break;

Now sudo ./pfcount1 -i enp1s0f0 -n 10 -o testpcap4 works fine. I can see the dump traffic.

But I still do not know why the parameter I that I added does not work. 

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare you need to add a colon after I (e.g. "I:"), however we can close this issue.
