### ISSUE TITLE
zcount do not work at dummy0

### ISSUE THREAD

**Issue by 55-AA** [ntop/PF_RING#405]
7.2.0-stable-c93ef24  @ Debian 9.4
> #modprobe dummy numdummies=2
> #ifconfig dummy0 up
> #zsend -i dummy0 
> #zcount -i dummy0

The zcount cannot get packets, but pfsend can do.
What's the reason?

**Comment by cardigliano** [comment]
@55-AA please note that zcount captures rx packets only, while sending to dummy0 you have tx packets on the interface. If you want to use the dummy interface with zc in a similar way, you should send 'rx' packets with -i stack:dummy0

**Comment by 55-AA** [comment]
That's all right,Thanks for you.
