### ISSUE TITLE
run pf_ring zc and n2disk for a certain time?

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#407]
Can I specfic a certian period that pf_ring zc and n2disk can run? for example. run them for only 1 minutes.

Thanks.

**Comment by cardigliano** [comment]
Did you check the --stop-on-limit|-L option? It can be used to stop the packet capture when the max file len/duration/packets is reached (it dumps 1 file and exits). Please let us know if this works for you, or if you need something more flexible.
