### ISSUE TITLE
Need help on builtin ip/gre hash

### ISSUE THREAD

**Issue by jcmathews** [ntop/PF_RING#409]
Hi,

Could you please help me in understanding the builtin zc hash functions. Our intention is to use a five tuple hash(srcip,dstip,srcp,dstp,prot) in our zc application.
pfring_zc_builtin_ip_hash () -> Src Ip & Dst IP ?
pfring_zc_builtin_gre_hash() -> ??
pfring_zc_builtin_gtp_hash() -> ??
What all fields are eligible for the above hash functions?

Regards,
Jessel.

**Comment by cardigliano** [comment]
pfring_zc_builtin_ip_hash: IP-based (src and dst IP).
pfring_zc_builtin_gre_hash: Inner-IP-based packet hash in case of GRE packet, Outer-IP/Port-based packet hash otherwise.
pfring_zc_builtin_gtp_hash: GTP-C Seq-based packet hash in case of GTP-C, Inner-IP/Port-based packet hash in case of GTP-U, Outer-IP/Port-based packet hash otherwise.
Please note this is reported in the API documentation available at http://www.ntop.org/guides/pf_ring/api/pfring_zc.html

**Comment by jcmathews** [comment]
Thank you. But the documentation does not clearly mention about the fields used from l3/l4 for generating the hash by the builtin zc functions.

From your comment, i am assuming that the ip based hash uses both src & dst ip **(meaning 2 tuple)**. However for GRE hash function, i am assuming that if packet is qualified as GRE, then ip based hash will be generated**( i.e. using 2 tuple from inner packet)**, else if packet not qualified as GRE, then the generated hash is **4 tuple from outer packet src,dst IP and src,dst Port**. Could you please confirm this?
Our requirement is to generate a hash based on 5 tuple **(Src ip,Dst ip, Src port, Dst port, Protocol)**. Does any zc builtin hash function meet this requirement?

**Comment by cardigliano** [comment]
> From your comment, i am assuming that the ip based hash uses both src & dst ip (meaning 2 tuple). However for GRE hash function, i am assuming that if packet is qualified as GRE, then ip based hash will be generated**( i.e. using 2 tuple from inner packet)**, else if packet not qualified as GRE, then the generated hash is 4 tuple from outer packet src,dst IP and src,dst Port. Could you please confirm this?

Correct

> Our requirement is to generate a hash based on 5 tuple (Src ip,Dst ip, Src port, Dst port, Protocol). Does any zc builtin hash function meet this requirement?

This is not supported by the builtin hash functions currently available. Do you need this for the outer header or you need to handle some encapsulation (e.g. GRE)?

**Comment by jcmathews** [comment]
We are not looking on to any encapsulation. It is for normal IP packet, to generate a hash based on 5 tuple value.  Also in future, hash out of 7 tuple value. 
We were under the assumption that pf_ring might be having either a generic or 5 tuple based hash function.

**Comment by cardigliano** [comment]
@jcmathews PF_RING itself can generate a 5-tuple hash using pfring_parse_pkt(), ZC provides some builtin hash functions as sample hash'es (those listed above) as you can also provide your own hash function (calling pfring_parse_pkt() is also an option). This said it makes sense to add a 5-tuple optimized hash to the list of builtin ZC hash functions.

**Comment by jcmathews** [comment]
Thank you @cardigliano. It would be really helpful to have an optimized hash function under builtin zc.
while pfring_parse_pkt() might serve the purpose, but it might take a hit on performance.

**Comment by cardigliano** [comment]
Please check pfring_zc_builtin_5tuple_hash() in latest dev code

**Comment by jcmathews** [comment]
Thank you so much. Will check it.
