### ISSUE TITLE
bro: multiple entries with relase 7.x 

### ISSUE THREAD

**Issue by ryu80** [ntop/PF_RING#410]
Hello,
i have recently updated my bro and pf_ring installation with  bro-2.5.5  and pf_ring 7.2 ( compiled on debian stretch 4.9.0-3 ).
the compilation goes fine but once bro is running  i noted that every log entry was multplyed by 8, just as my lb_procs ( bro's node.cfg ) number.  i rolled back to the previous pf_ring 6.6.0 release and the issue is not present anymore .

**Comment by cardigliano** [comment]
@ryu80 please provide "more /proc/net/pf_ring/* | cat" while Bro is running

**Comment by ryu80** [comment]
here the ouput on a installation with 4 lb_procs

 more /proc/net/pf_ring/* | cat 
::::::::::::::
/proc/net/pf_ring/29808-ens192.6
::::::::::::::
Bound Device(s)    : ens192
Active                 : 1
Breed                  : Standard
Appl. Name             : <unknown>
Socket Mode            : RX+TX
Capture Direction      : RX+TX
Sampling Rate          : 1
Filtering Sampling Rate: 0
IP Defragment          : No
BPF Filtering          : Disabled
Sw Filt Hash Rules     : 0
Sw Filt WC Rules       : 0
Sw Filt Hash Match     : 0
Sw Filt Hash Miss      : 0
Sw Filt Hash Filtered  : 0
Hw Filt Rules          : 0
Poll Pkt Watermark     : 1
Num Poll Calls         : 2533735
Poll Watermark Timeout : 0
Channel Id Mask        : 0xFFFFFFFFFFFFFFFF
VLAN Id                : 65535
Slot Version           : 17 [7.3.0]
Min Num Slots          : 32768
Bucket Len             : 8192
Slot Len               : 8240 [bucket+header]
Tot Memory             : 270020608
Tot Packets            : 2355
Tot Pkt Lost           : 0
Tot Insert             : 2355
Tot Read               : 2355
Insert Offset          : 2346976
Remove Offset          : 2346976
Num Free Slots         : 32768
TX: Send Ok            : 0
TX: Send Errors        : 0
Reflect: Fwd Ok        : 0
Reflect: Fwd Errors    : 0
::::::::::::::
/proc/net/pf_ring/29809-ens192.8
::::::::::::::
Bound Device(s)    : ens192
Active                 : 1
Breed                  : Standard
Appl. Name             : <unknown>
Socket Mode            : RX+TX
Capture Direction      : RX+TX
Sampling Rate          : 1
Filtering Sampling Rate: 0
IP Defragment          : No
BPF Filtering          : Disabled
Sw Filt Hash Rules     : 0
Sw Filt WC Rules       : 0
Sw Filt Hash Match     : 0
Sw Filt Hash Miss      : 0
Sw Filt Hash Filtered  : 0
Hw Filt Rules          : 0
Poll Pkt Watermark     : 1
Num Poll Calls         : 2541582
Poll Watermark Timeout : 0
Channel Id Mask        : 0xFFFFFFFFFFFFFFFF
VLAN Id                : 65535
Slot Version           : 17 [7.3.0]
Min Num Slots          : 32768
Bucket Len             : 8192
Slot Len               : 8240 [bucket+header]
Tot Memory             : 270020608
Tot Packets            : 2355
Tot Pkt Lost           : 0
Tot Insert             : 2355
Tot Read               : 2355
Insert Offset          : 2346976
Remove Offset          : 2346976
Num Free Slots         : 32768
TX: Send Ok            : 0
TX: Send Errors        : 0
Reflect: Fwd Ok        : 0
Reflect: Fwd Errors    : 0
::::::::::::::
/proc/net/pf_ring/29815-ens192.7
::::::::::::::
Bound Device(s)    : ens192
Active                 : 1
Breed                  : Standard
Appl. Name             : <unknown>
Socket Mode            : RX+TX
Capture Direction      : RX+TX
Sampling Rate          : 1
Filtering Sampling Rate: 0
IP Defragment          : No
BPF Filtering          : Disabled
Sw Filt Hash Rules     : 0
Sw Filt WC Rules       : 0
Sw Filt Hash Match     : 0
Sw Filt Hash Miss      : 0
Sw Filt Hash Filtered  : 0
Hw Filt Rules          : 0
Poll Pkt Watermark     : 1
Num Poll Calls         : 2542501
Poll Watermark Timeout : 0
Channel Id Mask        : 0xFFFFFFFFFFFFFFFF
VLAN Id                : 65535
Slot Version           : 17 [7.3.0]
Min Num Slots          : 32768
Bucket Len             : 8192
Slot Len               : 8240 [bucket+header]
Tot Memory             : 270020608
Tot Packets            : 2355
Tot Pkt Lost           : 0
Tot Insert             : 2355
Tot Read               : 2355
Insert Offset          : 2346976
Remove Offset          : 2346976
Num Free Slots         : 32768
TX: Send Ok            : 0
TX: Send Errors        : 0
Reflect: Fwd Ok        : 0
Reflect: Fwd Errors    : 0
::::::::::::::
/proc/net/pf_ring/29820-ens192.5
::::::::::::::
Bound Device(s)    : ens192
Active                 : 1
Breed                  : Standard
Appl. Name             : <unknown>
Socket Mode            : RX+TX
Capture Direction      : RX+TX
Sampling Rate          : 1
Filtering Sampling Rate: 0
IP Defragment          : No
BPF Filtering          : Disabled
Sw Filt Hash Rules     : 0
Sw Filt WC Rules       : 0
Sw Filt Hash Match     : 0
Sw Filt Hash Miss      : 0
Sw Filt Hash Filtered  : 0
Hw Filt Rules          : 0
Poll Pkt Watermark     : 1
Num Poll Calls         : 2543799
Poll Watermark Timeout : 0
Channel Id Mask        : 0xFFFFFFFFFFFFFFFF
VLAN Id                : 65535
Slot Version           : 17 [7.3.0]
Min Num Slots          : 32768
Bucket Len             : 8192
Slot Len               : 8240 [bucket+header]
Tot Memory             : 270020608
Tot Packets            : 2355
Tot Pkt Lost           : 0
Tot Insert             : 2355
Tot Read               : 2355
Insert Offset          : 2346976
Remove Offset          : 2346976
Num Free Slots         : 32768
TX: Send Ok            : 0
TX: Send Errors        : 0
Reflect: Fwd Ok        : 0
Reflect: Fwd Errors    : 0

*** /proc/net/pf_ring/dev: directory ***

::::::::::::::
/proc/net/pf_ring/info
::::::::::::::
PF_RING Version          : 7.3.0 (dev:c03653cf434089b15d10c3af6703dac8990bb742)
Total rings              : 4

Standard (non ZC) Options
Ring slots               : 32768
Slot version             : 17
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

*** /proc/net/pf_ring/stats: directory ***

**Comment by cardigliano** [comment]
@ryu80 it seems that all instances are capturing from "ens192" and there is no "Cluster Id" set to split the traffic across the instances. We need to figure out why the behaviour changed after the update (if it depends on Bro or PF_RING). Btw, please provide your Bro configuration file too.

**Comment by ryu80** [comment]
do you mean node.cfg ?
if yes it is very simple

[logger]
type=logger
host=localhost
#
[manager]
type=manager
host=localhost
#
[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=ens192
lb_method=pf_ring
lb_procs=4
pin_cpus=0,1,2,3

**Comment by cardigliano** [comment]
As I said before it seems that Bro is not setting the a Cluster ID, not sure if thiw behaviour changed with the latest Bro version, please try forcing it appending this line to node.cfg:

env_vars=PCAP_PF_RING_CLUSTER_ID=99

**Comment by ryu80** [comment]
great it works.
i will try also to upgrade on my production enviroment .
thank you
