### ISSUE TITLE
pfring_zc_vm_register(/tmp/qmp0) error

### ISSUE THREAD

**Issue by sajishv** [ntop/PF_RING#411]
Hi, 

I am attempting ZC from host to VM with KVM/QEMU. 

**HOST OS: RHEL 7.2
GUEST OS: RHEL 7.2**

I started the VM as follows: 

**qemu-system-x86_64 \
-name myRHELVM \
-enable-kvm \
-cpu host \
-k en-us \
-drive file=zcvm-amd64.img,if=virtio \
-boot c \
-m 4096 \
-vnc 0.0.0.0:1 \
-netdev type=tap,id=guest0,script=if-up.sh,vhost=on -device virtio-net-pci,netdev=guest0,mac=DE:AD:BE:EF:FE:EA  \
-chardev socket,path=/tmp/qmp0,server,nowait,id=qmp0 \
-mon chardev=qmp0,mode=control \
$@**
 
Loaded all the required modules in the host and vm.
The monitor socket appears to be created on the host /tmp folder: 

**srwxr-xr-x 1 root root       0 Sep 20 19:20 qmp0**

However, when i try zsend command on the host it throws an error: 

**$sudo ./zsend -c 99 -Q  /tmp/qmp0
Sending packets to cluster 99 queue 0
Run your consumer application as follows:
        pfcount -i zc:99@0
pfring_zc_vm_register(/tmp/qmp0) error**

Request help in identifying the cause of this issue. 

Please let me know if you need any additional information. 

Thanks,
Sajish.

**Comment by cardigliano** [comment]
@sajishv do you see some error/warning message in the Qemu logs?

**Comment by sajishv** [comment]
Hi @cardigliano ,

Unfortunately adding -d and -D option to qemu command is not producing any log output. When i run the command, on the console I dont see any specific errors: 

**$ sudo ./vm-boot.sh zcvm-amd64.img
+ switch=br-ex
+ '[' -n tap0 ']'
+ ifconfig tap0 up 0.0.0.0 promisc
+ sleep 0.5s
+ ovs-vsctl add-port br-ex tap0
ovs-vsctl: cannot create a port named tap0 because a port named tap0 already exists on bridge br-ex
+ exit 0**
 
The script was modified a bit to take the image as argument and add the tap interface to a ovs bridge. 

Thanks,
Sajish.

**Comment by cardigliano** [comment]
@sajishv I will add more debug info to zsend/zbalance_ipc to see if we are able to get more details on the zc side. What is the Qemu version you are running on?

**Comment by sajishv** [comment]
Thanks @cardigliano , 

Qemu version: 

$ qemu-system-x86_64 --version
QEMU emulator version 2.9.0(qemu-kvm-ev-2.9.0-16.el7_4.14.1)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

Thanks,
Sajish.

**Comment by sajishv** [comment]
Hi @cardigliano , 

pfring_zc_vm_register is only returning -1. Unable to debug pfring_zc_vm_register. 

Would there be any permission or capabilties related issues? 

I am running zsend with sudo. Without sudo it gives a different error: 

$  ./zsend -c 99 -Q /tmp/qmp0
pfring_zc_create_cluster error [Socket operation on non-socket] Please check your hugetlb configuration
 
PS: We had not faced any of this issue when we tried with Ubuntu 16.4 earlier.. 

Thanks,
Sajish.

**Comment by cardigliano** [comment]
@sajishv please note that Ubuntu 16.4 is running an older version of Qemu (v.2.5), here you are running v.2.9, it could this error is due to changes to some components (e.g. ivshmem). I would expect some warning from Qemu, however since this is not the case I will add more debug info and let you know. Thank you.

**Comment by cardigliano** [comment]
@sajishv please update to latest dev code from github, recompile the library/examples, and run zsend with -D to get debug messages.

**Comment by sajishv** [comment]
Hi @cardigliano , 

Following is the output:

# sudo ./zsend -D -c 99 -Q /tmp/qmp0
[PF_RING-ZC][DEBUG] 33554432 bytes requested with id = 99
[PF_RING-ZC][DEBUG] 1008 2097152-byte pages available at /dev/hugepages
[PF_RING-ZC][DEBUG] 16 2097152-byte pages allocated with va = 0x2aaaaac00000 pa = [ 69212307456, 69210210304, 69216501760, 69214404608, 69220696064, 69218598912, 69224890368, 69222793216, 69229084672, 69226987520, 69233278976, 69231181824, 69237473280, 69235376128, 69241667584, 69239570432 ]
[PF_RING-ZC][DEBUG] Initialising memory segment
[PF_RING-ZC][DEBUG] Memory allocation completed successfully
Sending packets to cluster 99 queue 0
Run your consumer application as follows:
        pfcount -i zc:99@0
[PF_RING-ZC][DEBUG] Listening on socket /tmp/pfring-zc-kvm-shmem-sock-99
[PF_RING-ZC][DEBUG] Connecting to socket /tmp/qmp0
[PF_RING-ZC][DEBUG] QMP Message: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 9, "major": 2}, "package": "(qemu-kvm-ev-2.9.0-16.el7_4.14.1)"}, "capabilities": []}}
[PF_RING-ZC][DEBUG] QMP Sending Command { "execute": "qmp_capabilities" }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "device_del",  "arguments": {  "id" : "shmem-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "chardev-remove",  "arguments": {  "id" : "shmemsock-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "device_del",  "arguments": {  "id" : "vport-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "chardev-remove",  "arguments": {  "id" : "vportsock-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "device_add" ,  "arguments" : {  "driver": "virtio-serial"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "chardev-add",  "arguments" : {  "id" : "vportsock-99",  "backend" : {  "type" : "socket",  "data" : {  "addr" : {  "type" : "unix",  "data" : {  "path" : "/tmp/pfring-zc-kvm-vport-sock-99"  }  },  "server" : true,  "wait" : false  }  }  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "device_add" ,  "arguments": {  "driver" : "virtserialport",  "chardev" : "vportsock-99",  "name" : "pfring-zc-vport-99",  "id" : "vport-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "chardev-add",  "arguments" : {  "id" : "shmemsock-99",  "backend" : {  "type" : "socket",  "data" : {  "addr" : {  "type" : "unix",  "data" : {  "path" : "/tmp/pfring-zc-kvm-shmem-sock-99"  }  },  "server" : false,  "wait" : false  }  }  }  }
[PF_RING-ZC][DEBUG] SHM new connection
[PF_RING-ZC][DEBUG] SHM increasing vm slots
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "device_add" ,  "arguments": {  "driver" : "ivshmem",  "chardev" : "shmemsock-99",  "size" : "32m",  "ioeventfd" : "false",  "id" : "shmem-99"  }  }
[PF_RING-ZC][DEBUG] SHM Live_vms[0]
[PF_RING-ZC][DEBUG] SHM trying to send fds to new connection
[PF_RING-ZC][DEBUG] SHM Connected (count = 0).
[PF_RING-ZC][DEBUG] SHM Live_count is 1
[PF_RING-ZC][DEBUG] QMP Command response does not look like a success:
{"error": {"class": "GenericError", "desc": "Parameter 'driver' expects pluggable device type"}}
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "device_del",  "arguments": {  "id" : "shmem-99"  }  }
[PF_RING-ZC][DEBUG] QMP Command response does not look like a success:
{"error": {"class": "DeviceNotFound", "desc": "Device 'shmem-99' not found"}}
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "chardev-remove",  "arguments": {  "id" : "shmemsock-99"  }  }
[PF_RING-ZC][DEBUG] SHM disconnection
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "device_del",  "arguments": {  "id" : "vport-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "chardev-remove",  "arguments": {  "id" : "vportsock-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
pfring_zc_vm_register(/tmp/qmp0) error

**Comment by cardigliano** [comment]
@sajishv it seems it is failing due to the ivshmem driver, we need to modify the zc-kvm code to support latest Qemu versions. Please keep using ubuntu 16 in the meantime if this is an option, or compile an older Qemu version.

**Comment by sajishv** [comment]
Hi @cardigliano ,

With an older QEMU it is working: 

```
$qemu-system-x86_64 --version

(process:29220): GLib-WARNING **: gmem.c:483: custom memory allocation vtable not supported
QEMU emulator version 2.4.0, Copyright (c) 2003-2008 Fabrice Bellard
```

```
$ sudo ./zsend -D -c 99 -Q /tmp/qmp0
[PF_RING-ZC][DEBUG] 33554432 bytes requested with id = 99
[PF_RING-ZC][DEBUG] 1008 2097152-byte pages available at /dev/hugepages
[PF_RING-ZC][DEBUG] 16 2097152-byte pages allocated with va = 0x2aaaaac00000 pa = [ 69239570432, 69241667584, 69235376128, 69237473280, 69231181824, 69233278976, 69226987520, 69229084672, 69222793216, 69224890368, 69218598912, 69220696064, 69214404608, 69216501760, 69210210304, 69212307456 ]
[PF_RING-ZC][DEBUG] Initialising memory segment
[PF_RING-ZC][DEBUG] Memory allocation completed successfully
Sending packets to cluster 99 queue 0
Run your consumer application as follows:
        pfcount -i zc:99@0
[PF_RING-ZC][DEBUG] Listening on socket /tmp/pfring-zc-kvm-shmem-sock-99
[PF_RING-ZC][DEBUG] Connecting to socket /tmp/qmp0
[PF_RING-ZC][DEBUG] QMP Message: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 4, "major": 2}, "package": ""}, "capabilities": []}}
[PF_RING-ZC][DEBUG] QMP Sending Command { "execute": "qmp_capabilities" }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "device_del",  "arguments": {  "id" : "shmem-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "chardev-remove",  "arguments": {  "id" : "shmemsock-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "device_del",  "arguments": {  "id" : "vport-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute": "chardev-remove",  "arguments": {  "id" : "vportsock-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "device_add" ,  "arguments" : {  "driver": "virtio-serial"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "chardev-add",  "arguments" : {  "id" : "vportsock-99",  "backend" : {  "type" : "socket",  "data" : {  "addr" : {  "type" : "unix",  "data" : {  "path" : "/tmp/pfring-zc-kvm-vport-sock-99"  }  },  "server" : true,  "wait" : false  }  }  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "device_add" ,  "arguments": {  "driver" : "virtserialport",  "chardev" : "vportsock-99",  "name" : "pfring-zc-vport-99",  "id" : "vport-99"  }  }
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "chardev-add",  "arguments" : {  "id" : "shmemsock-99",  "backend" : {  "type" : "socket",  "data" : {  "addr" : {  "type" : "unix",  "data" : {  "path" : "/tmp/pfring-zc-kvm-shmem-sock-99"  }  },  "server" : false,  "wait" : false  }  }  }  }
[PF_RING-ZC][DEBUG] SHM new connection
[PF_RING-ZC][DEBUG] SHM increasing vm slots
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] QMP Sending Command  {  "execute" : "device_add" ,  "arguments": {  "driver" : "ivshmem",  "chardev" : "shmemsock-99",  "size" : "32m",  "ioeventfd" : "false",  "id" : "shmem-99"  }  }
[PF_RING-ZC][DEBUG] SHM Live_vms[0]
[PF_RING-ZC][DEBUG] SHM trying to send fds to new connection
[PF_RING-ZC][DEBUG] SHM Connected (count = 0).
[PF_RING-ZC][DEBUG] SHM Live_count is 1
[PF_RING-ZC][DEBUG] QMP Returned success
[PF_RING-ZC][DEBUG] VM initialized successfully
[PF_RING-ZC][DEBUG] Connecting to socket /tmp/pfring-zc-kvm-vport-sock-99
Estimated CPU freq: 3480900000 Hz
=========================
Absolute Stats: 8'190 pkts - 687'960 bytes
=========================

=========================
Absolute Stats: 8'190 pkts - 687'960 bytes
Actual Stats: 0.00 pps - 0.00 Gbps [0 bytes / 1.0 sec]
=========================
```

**Comment by sajishv** [comment]
> @sajishv it seems it is failing due to the ivshmem driver, we need to modify the zc-kvm code to support latest Qemu versions. Please keep using ubuntu 16 in the meantime if this is an option, or compile an older Qemu version.

Hi @cardigliano,

Thanks for looking into the issue so promptly. Please let me know if this is being planned to be updated in the near future.

**Comment by cardigliano** [comment]
@sajishv we will work on this asap, however this will take some time

**Comment by sajishv** [comment]
Thanks @cardigliano !
