### ISSUE TITLE
Question regarding PE340G2BPI71 Bypass Card Dual Port Fiber 40 Gigabit Ethernet PCI Express Bypass Server Adapter Intel® XL710 Based

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#413]
Hi,
Do you support PE340G2BPI71 Bypass Card
Dual Port Fiber 40 Gigabit Ethernet PCI Express Bypass Server Adapter Intel® XL710 Based from Silicom Connectivity Solution (https://www.silicom-usa.com/pr/server-adapters/networking-bypass-adapters/40-gigabit-ethernet-bypass-networking-server-adapters/pe340g2bpi71-server-adapter/)?

Thank you,
Steven

**Comment by cardigliano** [comment]
Hi Steven
yes XL710 is supported by our i40e-zc driver

**Comment by szarea** [comment]
thank you
