### ISSUE TITLE
Is IP fragmentation supported in PF_Ring ZC ?

### ISSUE THREAD

**Issue by jcmathews** [ntop/PF_RING#414]
Hi Alfredo,

a) Is IP Reassembly supported in PF_Ring ZC at driver level ?

b) Is there an application like zbalance for VM, where the traffic from host through cluster is being consumed and distributed to egress vNICs. I believe zbounce just work in terms of queues, but not to vNICS.

Expected Traffic flow
hostNIC-->VM(ivshmem)->vNIC's

Regards,
jcm.

**Comment by cardigliano** [comment]
@jcmathews, please see http://www.ntop.org/guides/pf_ring/vm/kvm_zc.html for VM support, I guess you need to use zbalance_ipc as in the example. IP reassembly is not natively supported by ZC.

**Comment by jcmathews** [comment]
We are running a zbalance_ipc master application, which is running on Host,.
In this context i would like zbalance_ipc run inside a VM too.
Does zbalance_ipc run inside a VM?

**Comment by cardigliano** [comment]
zbalance_ipc runs on the host, forwarding traffic to the VMs, please see http://www.ntop.org/guides/pf_ring/vm/kvm_zc.html

**Comment by jcmathews** [comment]
@cardigliano   Can software queue be equipped with de-fragmentation functionality?

**Comment by cardigliano** [comment]
@jcmathews defragmentation is not supported with ZC queues (PF_RING relies on kernel for that, supporting it in ZC means rewriting that component from scratch)

**Comment by jcmathews** [comment]
@cardigliano Thanks. Im not using ZC, but i was trying to use software queues. 
Say i have two S/W queues where one supports defragmentation and other without  defragmentation.

Just a thought, if pf_ring want to support ip reassembly. i was just seeing a possibility where the pf_ring module have a API interface to userland which can accept fragments. 
Once user pushes fragment via say pfring_reassemble(), the pf_ring module get the packet and create a dummy skb and push it to the  defrag_skb() in pf_ring.c
Is this a viable approach?

**Comment by cardigliano** [comment]
@jcmathews you can already push packets to the stack using the 'stack:' prefix in the interface name (e.g. pfring_open("stack:dummy0"), however it depends on the performance you need to achieve

**Comment by jcmathews** [comment]
@cardigliano Thank you.
q1=pfring_open("stack:dummy0", tx_only);
q2=pfring_open("stack:dummy0", qx_only);

q2 will be having a reassembled ip packet. Does it work in that way?

Performance is a concern, but i'm expecting my traffic to be composed of less than 5% fragmented traffic.

**Comment by cardigliano** [comment]
q2=pfring_open("dummy0", rx_only);

**Comment by jcmathews** [comment]
ok thanks. Will try it out
