### ISSUE TITLE
pf_ring zc loss packets

### ISSUE THREAD

**Issue by lightinbottle** [ntop/PF_RING#418]
I finish the installation according to the link http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html.
And when i capture packet on one port(ZC mode, use pfcout -i zc:p4p1), there are no packets dropped.
But when i capture packets both on two ports(both ZC mode, use pfcout -i zc:p4p1&p4p2), there are about 20% packts lossed on both port.
What should i do to solve the problem?

the related info are below:
os： centos7.5-1804
linux kernel version: 3.10.0-862.14.4.el7.x86_64
interface:  intel 82575
pf_ring version :  7.3.0.181012
pf_ring config:    
    min_num_slots=65534
    enable_tx_capture=0
    transparent_mode=2
igb-zc config:
    RSS=1,1
capture  traffic:  128 byte packets, 976.56kpps (1Gbps)

**Comment by cardigliano** [comment]
I guess pfcout -i zc:p4p1&p4p2 means "pfcount -i zc:p4p1" and "pfcount -i zc:p4p2", please try setting the cpu affinity (using different cores). Example:
pfcount -i zc:p4p1 -g 0
pfcount -i zc:p4p2 -g 1

**Comment by lightinbottle** [comment]
yes,  pfcout -i zc:p4p1&p4p2 means "pfcount -i zc:p4p1" and "pfcount -i zc:p4p2".
And the smp_affinity_list of the p4p1 is 13 ; the smp_affinity_list of the p4p2 is 11.
I try to capture packets with "pfcount -i zc:p4p1 -g 6" and  "pfcount -i zc:p4p2 -g 8".
And there are still about 15% packets lossed on both ports. 
The CPU utilization are all very low.
Should i adjust other things ?

**Comment by lightinbottle** [comment]
@cardigliano  And what the **difference between** "pfcount -i zc:p4p1 -g 6" and "zcount -i zc:p4p1 -g 6"?
I run the command "zcount -i zc:p4p1 -g 6" first. It works correctly. But then i run the command "zcount -i zc:p4p2 -g 9" , it reports error. 
The error info is "**pfring_zc_create_cluster error [Socket operation on non-socket] Please check that pf_ring.ko is loaded and hugetlb fs is mounted**" .
When i use the pfcount to capture these two ports it can work although packets loss.

**Comment by cardigliano** [comment]
zcount is creating a ZC cluster (it is based on the ZC API, which requires hugepages),
which requires a unique cluster ID, please set it with the -c option (a different ID for each instance).
Please also try adding -a to pfcount to use active wait. Please also check your PCIe configuration with "dmesg | grep Speed"

**Comment by lightinbottle** [comment]
@cardigliano Thank you for your suggestion.
However, when i use "pfcount -i zc:p4p1 -g 9 -a" and "pfcount -i zc:p4p2 -g 6 -a" ,the packets drop still happen.
The output info is:

[root@gp src] pfcount -i zc:p4p2 -g9 -a
Using PF_RING v.7.3.0
Capturing from zc:p4p2 [mac: 6C:B3:11:32:28:ED][if_index: 52][speed: 1000Mb/s]
Device RX channels: 1
Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/65016-p4p2.10
=========================
Absolute Stats: [507'696 pkts total][66'844 pkts dropped][13.2% dropped]
[440'852 pkts rcvd][96'987'440 bytes rcvd]
=========================
========================
Absolute Stats: [1'070'236 pkts total][178'168 pkts dropped][16.6% dropped]
[892'068 pkts rcvd][196'254'960 bytes rcvd][892'006.45 pkt/sec][1'569.93 Mbit/sec]
=========================
Actual Stats: [451'216 pkts rcvd][1'000.06 ms][451'184.86 pps][0.79 Gbps]
=========================

And i check the PCIe that linked with intel82575 configuration. The output info is:  

[root@gp ~]# lspci -n -d 8086:10a7 -vvv | grep --color  Width
		LnkCap:	Port #0, Speed 2.5GT/s, Width x4, ASPM L0s L1, Exit Latency L0s <4us, L1 <64us
		LnkSta:	Speed 2.5GT/s, Width x1, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
		LnkCap:	Port #0, Speed 2.5GT/s, Width x4, ASPM L0s L1, Exit Latency L0s <4us, L1 <64us
		LnkSta:	Speed 2.5GT/s, Width x1, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-

It is PCIe X1(250MB/s  2gbps ) .

**Comment by lightinbottle** [comment]
@cardigliano Hi. I buy two PF_RING 1Gb ZC License through ntop shop. And I have some questions:
1. I installed the PF-RING  with binary packages. (eg: yum install pfring...). Can i change the size of ring buffer pf_ring if i install it with this method. And what the default size of ring buffer ?
2.If i want  to use ZC mode with license , should i must to  install the pf_ring with binary packages ?
3 We want to capture packts(1Gbps,200 bytes packet) and write pcap file.  Does the PF_RING 1G ZC meet the requirement ?

**Comment by cardigliano** [comment]
Hi @lightinbottle, 
1. please read https://github.com/ntop/PF_RING/blob/dev/doc/get_started/packages_installation.rst
for learning more about the pf_ring package configuration. However if you are loading
a ZC driver with systemd/init.d, our script already initialize the card with the maximum
number of buffers based on the card model.
2. You can use both binary packages or source code (we recommend packages to be
able to support you in case of issues)
3. pf_ring allows you to capture at line-rate, however in order to continuously write traffic
to disk you need a specialized application like n2disk.
As of performance, it seems to be limited by the pcie slot you are using.
