### ISSUE TITLE
Two X710 for 80G using PF_RING ZC

### ISSUE THREAD

**Issue by brett90063** [ntop/PF_RING#419]
I try to use PF_RING zc and dual port X710 to receive 80G, but i saw Intel X710 datasheet says that  "The total supported supported by the X710/XXV710/XL710 is 40 Gb/s, even when connected via two 40 Gb/s connections."

Now i use two X710 NIC and PF_RING ZC to try receive 80G.
So here comes the question.
./zbalance_ipc -i zc:ens4f0,zc:ens8f0 -c 99 -n 1 -m 1 -g 0 -p
Is this the way to receive two different NIC flow by one process?
because everytime i use zbalance_ipc, it always drop packet and total highest speed is close to 40G.

**Comment by cardigliano** [comment]
@brett90063 please note that besides the maximum supported bandwidth reported in the datasheet, X710 has a small fifo per queue/interface (max len is 4K packets), thus it is not able to support high pps rates.. what is your peak pps rate?

**Comment by brett90063** [comment]
Hi there, and thanks for your reply.
Here is some situation.

1. 
When computer B use
./zbalance_ipc -i zc:ens4f0,zc:8fo -c 99 -n 1 -m 1 -g 0 -p
computer A respectively send 40G each NIC to computer B,
but each sending process always drop half packet when computer B recive
./pfsend -i zc:ens4f0 -f ~/mypacket -r 40 -c     (-c is to repeat sending this packet)
./pfsend -i zc:ens8f0 -f ~/mypacket -r 40 -c
each process sending about 3,157,900 pps/38.5 Gbps , so total send to computer B is 6,315,800 pps, but zbalance_ips only receive 3,157,900 pps.

Actual Stats: Recv 6'066'407.99 pps (309'817.68 drops) - Forwarded 1'721'415.31 pps (4'344'995.68 drops)

And i try to figure out what happen, i found that zbalance_ipc only receive half packet each send process.
btw, this forwarded is not acceptable(too low).

2. 
When i send 20G for each send process

Actual Stats: Recv 3'197'555.03 pps (0.00 drops) - Forwarded 3'197'555.03 pps (0.00 drops)

It will receive perfect 40G and didn't drop

So it make me so confuse. Why I am sending from different NIC, but zbalance_ipc can not receive 80G.

**Comment by cardigliano** [comment]
@brett90063 from your zbalance_ipc stats I see that zbalance is able to receive 6+Mpps, drops are actually on the consumer side ('Forwarded'). What application are you using to consume packets forwarded by zbalance_ipc?

**Comment by brett90063** [comment]
wow, that was surprise me
so it maybe the efficiency of pfcount is not supporting to 80G?
I use
pfcount -i zc:99@0 -c 99

**Comment by cardigliano** [comment]
Please run the commands below and report some output from both:
zbalance_ipc -i zc:ens4f0,zc:8fo -c 99 -n 1 -m 1 -q 131072 -g 0 -p
pfcount -i zc:99@0 -c 99 -g 1 -a

**Comment by brett90063** [comment]
When I send 2x40G:

zbalance_ipc -i zc:ens4f0,zc:ens8f0 -c 99 -n 1 -m 1 -q 131072 -g 0 -p 
--------------------------------------
Absolute Stats: Recv 67'914'915 pkts (13'826'615 drops) - Forwarded 20'387'327 pkts (47'527'581 drops)
   zc:ens4f0 RX 37724798 pkts Dropped 9545428 pkts (20.2 %)
   zc:ens8f0 RX 30190508 pkts Dropped 4281220 pkts (12.4 %)
   Q 0 RX 20256708 pkts Dropped 47528093 pkts (70.1 %)
Actual Stats: Recv 5'614'522.23 pps (695'786.05 drops) - Forwarded 1'245'867.87 pps (4'368'647.35 drops)
--------------------------------------

pfcount -i zc:99@0 -c 99 -g 1 -a
--------------------------------------
Absolute Stats: [65'076'184 pkts total][45'420'389 pkts dropped][69.8% dropped]
[19'655'795 pkts rcvd][29'955'431'580 bytes rcvd][701'959.98 pkt/sec][8'558.29 Mbit/sec]
--------------------------------------
Actual Stats: [1'242'996 pkts rcvd][1'000.06 ms][1'242'917.69 pps][15.15 Gbps]
--------------------------------------

When I send 2x20G:

zbalance_ipc -i zc:ens4f0,zc:ens8f0 -c 99 -n 1 -m 1 -q 131072 -g 0 -p 
--------------------------------------
Absolute Stats: Recv 117'555'807 pkts (219'502 drops) - Forwarded 117'555'823 pkts (0 drops)
   zc:ens4f0 RX 59965553 pkts Dropped 0 pkts (0.0 %)
   zc:ens8f0 RX 60775692 pkts Dropped 219502 pkts (0.4 %)   #(this dropped is because i didn't send at the same time, i use two terminal)
   Q 0 RX 120523776 pkts Dropped 86423 pkts (0.1 %)
Actual Stats: Recv 3'184'449.62 pps (0.00 drops) - Forwarded 3'098'260.82 pps (86'180.79 drops)
--------------------------------------

pfcount -i zc:99@0 -c 99 -g 1 -a
--------------------------------------
Absolute Stats: [114'270'720 pkts total][0 pkts dropped][0.0% dropped]
[114'270'720 pkts rcvd][174'148'577'280 bytes rcvd][2'929'887.96 pkt/sec][35'721.19 Mbit/sec]
--------------------------------------
Actual Stats: [3'184'396 pkts rcvd][1'000.03 ms][3'184'271.81 pps][38.82 Gbps]
--------------------------------------

**Comment by cardigliano** [comment]
@brett90063 it seems that adding pressure on zbalance_ipc increasing the ingress traffic, that also affects the pfcount performance. It happens when memory bandwidth becomes a bottleneck (that can happen at 80Gbit depending on the hw configuration). Could you provide hw specs? (CPU model, RAM  model and channels, etc.)

**Comment by brett90063** [comment]
@cardigliano Sorry for the late reply.
Both computer (send and receive) are using:
ubuntu 18.04
CPU: 2*E5-2620 (each 8 physical and 8 hyper )
MB: X10DRG-Q
RAM: 2*KVR24R17D8/16 ECC DDR4-2400 16G
NIC: 2*XL710-QDA2

CPU1 of NIC is ens4f0, and my /etc/default/grub affinity setting is isolcpus=0,1,2,3,4,5,6,7

**Comment by brett90063** [comment]
@cardigliano Sorry for my late reply.
Both computer (send and receive) are using:
ubuntu 18.04
CPU: 2 * E5-2620 V4
MB: X10DRG-Q
RAM: 2 * KVR24N17D8/16 ECC DDR4-2400 16G
NIC: 2 * XL710-QDA2

CPU1's NIC is ens4f0,ens4f1 ; CPU2's NIC is ens8f0,ens8f1
and my /etc/default/grub affinity setting is isolcpus=0,1,2,3,4,5,6,7

**Comment by brett90063** [comment]
@cardigliano Sorry for my late reply.
Both computer (send and receive) are using:
ubuntu 18.04
CPU: 2 * E5-2620 V4
MB: X10DRG-Q
RAM: 2 * KVR24N17D8/16 ECC DDR4-2400 16G
NIC: 2 * XL710-QDA2

CPU1's NIC is ens4f0,ens4f1 ; CPU2's NIC is ens8f0,ens8f1
and my /etc/default/grub affinity setting is isolcpus=0,1,2,3,4,5,6,7

**Comment by brett90063** [comment]
Sorry, github seems to be having problem.
I don't know why sometime i can see my last reply sometimes not.
As a precaution I comment again, sorry if u saw two times

Both computer (send and receive) are using:
ubuntu 18.04
CPU: 2 * E5-2620 V4
MB: X10DRG-Q
RAM: 2 * KVR24N17D8/16 ECC DDR4-2400 16G
NIC: 2 * XL710-QDA2

CPU1's NIC is ens4f0,ens4f1 ; CPU2's NIC is ens8f0,ens8f1
and my /etc/default/grub affinity setting is isolcpus=0,1,2,3,4,5,6,7

**Comment by cardigliano** [comment]
It also discarded my reply.. 
Please provide the output of “lstopo”

**Comment by cardigliano** [comment]
Please also provide the output of “lstopo”

**Comment by brett90063** [comment]
![lstopo](https://user-images.githubusercontent.com/11819638/47308612-a3eb9880-d664-11e8-9f65-3e448f541f6a.jpg)

**Comment by cardigliano** [comment]
@brett90063 I noticed that ens4f0 and ens8f0 are on different numa nodes, this is a problem for performance, are you able to move both cards to the same node?

**Comment by brett90063** [comment]
@cardigliano OMG...it works.
it can recieive about 75Gbps when I change ens8f(cpu2 slot) to ens10f(cpu1 slot).
Really really thank you sooooooooo much.
So  PCIE needs to took more time and efficacy to transform the data in different numa nodes?

BTW, i still have little problem here.
Is it normal that when i send 40G
./pfsend -i zc:ens4f0 -f ~/packet/mypacket -c(repeat send this packet) -r 40 -g 0
it only send up to 36, 37 even 38?
Is this limit is NIC cause? (when i send 10G, it still send 9.xG)

send 40G:
TX rate: [current 3'211'021.03 pps/39.15 Gbps][average 3'158'682.82 pps/38.51 Gbps][total 6'317'492.00 pkts]
TX rate: [current 3'211'019.88 pps/39.15 Gbps][average 3'176'128.61 pps/38.72 Gbps][total 9'528'605.00 pkts]
TX rate: [current 3'211'019.30 pps/39.15 Gbps][average 3'184'851.31 pps/38.83 Gbps][total 12'739'711.00 pkts]
TX rate: [current 3'211'012.09 pps/39.15 Gbps][average 3'190'083.48 pps/38.89 Gbps][total 15'950'813.00 pkts]
TX rate: [current 3'143'286.13 pps/38.32 Gbps][average 3'182'283.91 pps/38.80 Gbps][total 19'094'184.00 pkts]
TX rate: [current 3'152'618.82 pps/38.44 Gbps][average 3'178'045.96 pps/38.75 Gbps][total 22'246'951.00 pkts]
TX rate: [current 3'171'429.08 pps/38.67 Gbps][average 3'177'218.83 pps/38.74 Gbps][total 25'418'545.00 pkts]
TX rate: [current 3'174'820.55 pps/38.71 Gbps][average 3'176'952.35 pps/38.73 Gbps][total 28'593'537.00 pkts]
TX rate: [current 3'172'344.65 pps/38.68 Gbps][average 3'176'491.57 pps/38.73 Gbps][total 31'766'072.00 pkts]
TX rate: [current 3'173'979.38 pps/38.70 Gbps][average 3'176'263.18 pps/38.73 Gbps][total 34'940'245.00 pkts]
TX rate: [current 3'179'924.90 pps/38.77 Gbps][average 3'176'568.33 pps/38.73 Gbps][total 38'120'313.00 pkts]
TX rate: [current 3'181'341.20 pps/38.79 Gbps][average 3'176'935.47 pps/38.73 Gbps][total 41'301'791.00 pkts]
TX rate: [current 3'174'614.84 pps/38.70 Gbps][average 3'176'769.71 pps/38.73 Gbps][total 44'476'536.00 pkts]
TX rate: [current 3'177'468.48 pps/38.74 Gbps][average 3'176'816.30 pps/38.73 Gbps][total 47'654'157.00 pkts]

![pfsend](https://user-images.githubusercontent.com/11819638/47333350-2439ea00-d6b5-11e8-95fc-3be413d7d401.png)


It always have discount about 5% off.

**Comment by cardigliano** [comment]
@brett90063 nice to see that rx performance is good now. As of tx, I will check in our lab if we get the same bahaviour.

**Comment by cardigliano** [comment]
@brett90063 I noticed that you are using -r 40, please note that rate limiting in pfsend is based on the cpu clock that can be affected by fluctuations, please try removing -r 40. (pfsend is a sample application, it is not meant to be really accurate)

**Comment by brett90063** [comment]
remove -r 40:
TX rate: [current 3'209'181.79 pps/39.13 Gbps][average 3'175'593.93 pps/38.72 Gbps][total 34'932'975.00 pkts]
TX rate: [current 3'209'955.97 pps/39.14 Gbps][average 3'178'457.44 pps/38.75 Gbps][total 38'143'069.00 pkts]
TX rate: [current 3'206'956.89 pps/39.10 Gbps][average 3'180'649.71 pps/38.78 Gbps][total 41'350'167.00 pkts]
TX rate: [current 3'169'198.06 pps/38.64 Gbps][average 3'179'831.73 pps/38.77 Gbps][total 44'519'495.00 pkts]
TX rate: [current 3'173'120.30 pps/38.69 Gbps][average 3'179'384.30 pps/38.76 Gbps][total 47'692'793.00 pkts]

Sorry for my lack of knowledge about hardware.
My old server have x540, E5-2620 and it run pfsend can up to 10Gbps (my situation only run 9.x).
I need to rewrite pfsend for my new computer or maybe change my bios setting? or something i can do?

**Comment by cardigliano** [comment]
@brett90063 I guess you are running pfsend with -r 10 on this machine right? If this is the case, it could be it is just a matter of rate limiting accuracy (e.g. try with -r 11)

**Comment by brett90063** [comment]
@cardigliano ok thank you.
I will try to let it stable cuz I need to record the value when I do the experiment.

Sorry I have another question about zbalance_ipc.
Now I have three computer, all useing pf_ring zc.
As mention above, I need to let computer B as a IDS, so computer B needs to transfer the computer A's packet to computer C.

General situation is that A use pfsend, B use pfbridge, C use pfcount.
But i need zbalance_ipc to balance the queue and receive 80Gbps.

I try to use zbalance_ipc to open the queue and cluster, and then use pfbridge to transfer the packet.

computer A:
sudo ./pfsend -i zc:ens4f0 -f ~/packet/mypacket -c -g 0
sudo ./pfsend -i zc:ens10f0 -f ~/packet/mypacket -c -g 1

computer B:
sudo ./zbalance_ipc -i zc:ens4f0 ,zc:ens10f0 -n 2 -m 1 -a -p -c 99 -g 0
sudo ./pfbridge -a zc:99@0 -b zc:ens4f1 -p -g 1
sudo ./pfbridge -a zc:99@1 -b zc:ens10f1 -p -g 2

computer C:
sudo ./pfcount -i zc:ens4f1 -g 0
sudo ./pfcount -i zc:ens10f1 -g 1

When A send both 40Gbps, C only receive 9.xGbps.
B  zbalance_ipc one of the stat:

Absolute Stats: Recv 39'053'648 pkts (1'623'633 drops) - Forwarded 10'851'782 pkts (28'201'866 drops)
      zc:ens4f0 RX 18523512 pkts Dropped 1326436 pkts (6.7 %)
      zc:ens10f0 RX 20530973 pkts Dropped 297257 pkts (1.4 %)
      Q 0 RX 5432111 pkts Dropped 14087324 pkts (72.2 %)
      Q 1 RX 5403944 pkts Dropped 14115614 pkts (72.3 %)
Actual Stats: Recv 5'862'092.99 pps (51'791.47 drops) - Forwarded 1'505'168.55 pps (4'356'921.44 drops)

It limit is each queue about 10Gbps.
I think it's pfbridge doesn't match with zbalance_ipc? (sorry i haven't seen the code yet)

The second question is that pfbridge needs the parameter about -b (Egress).
That means my zbalance_ipc only can open two queue?
because each queue connect one NIC.
sudo ./pfbridge -a zc:99@0 -b **zc:ens4f1** -p -g 1
sudo ./pfbridge -a zc:99@1 -b **zc:ens10f1** -p -g 2
if I open the third queue, it maybe no place to send out? (I try two pfbridge connect one port, it says that 
Unable to enable ring :-( )

**Comment by cardigliano** [comment]
@brett90063 please note that pfbridge is not optimized to work in zero-copy mode, you can achieve the same with a single command (see -r) and work in zero-copy mode, example:

sudo ./zbalance_ipc -i zc:ens4f0,zc:ens10f0 -n 2 -m 1 -a -p -c 99 -g 0 -r 0:zc:ens4f1 -r 1:zc:ens10f1

**Comment by brett90063** [comment]
@cardigliano thank you, zbalance_ipc is really awesome.

Here are some question:
First question is that can zbalance_ipc bind the cpu core on each queue?
ex: -n 2
zbalance_ipc bind core 0
0 queue bind core 1
1 queue bind core 2

second question is that:
As mention above, computer B will be an IDS, so I need more and more queue to filter the packet (using pattern matching on GPU), in my experience with old server, each cpu core calculate ability is about 3Gbps.
I only have two NIC to egress queue, if i need to open 4 or more queue. How can i do?

**Comment by cardigliano** [comment]
1. zbalance_ipc is single-threaded, you can configure a single core
2. if you want to add more interfaces, you can do that with -n and -r, example: -n 4 -r 0:zc:eth1 -r 1:zc:eth2 -r 2:zc:eth3 -r 3:zc:eth4

**Comment by brett90063** [comment]
@cardigliano 
Thank you so much for answering so many questions.
I learned a lot, PF_RING is really great, thank you.

**Comment by cardigliano** [comment]
Thank you. Closing this issue.
