### ISSUE TITLE
can't load PF-RING_aware e1000e mic driver during install version 6.1.1

### ISSUE THREAD

**Issue by markc0303** [ntop/PF_RING#42]
Hi,

tried to install pf_ring w/ 2 Intel 82571EB giga nics on ubuntu 14.04 server.
following README.FRIST, i can successfully load pf_ring modules, but when i complie e1000e driver(in folder "/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src"), i got error when enter "make" command. error log below.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$ make
make -C /lib/modules/3.19.0-30-generic/build SUBDIRS=/home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src modules
make[1]: Entering directory `/usr/src/linux-headers-3.19.0-30-generic'
  CC [M]  /home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src/netdev.o
In file included from ./arch/x86/include/asm/apic.h:5:0,
                 from ./arch/x86/include/asm/smp.h:12,
                 from ./arch/x86/include/asm/mmzone_64.h:10,
                 from ./arch/x86/include/asm/mmzone.h:4,
                 from include/linux/mmzone.h:912,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src/netdev.c:25:
/home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src/netdev.c:8586:21: error: 'e1000e_pm_runtime_suspend' undeclared here (not in a function)
  SET_RUNTIME_PM_OPS(e1000e_pm_runtime_suspend, e1000e_pm_runtime_resume,
                     ^
include/linux/pm.h:347:21: note: in definition of macro 'SET_RUNTIME_PM_OPS'
  .runtime_suspend = suspend_fn, \
                     ^
/home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src/netdev.c:8586:48: error: 'e1000e_pm_runtime_resume' undeclared here (not in a function)
  SET_RUNTIME_PM_OPS(e1000e_pm_runtime_suspend, e1000e_pm_runtime_resume,
                                                ^
include/linux/pm.h:348:20: note: in definition of macro 'SET_RUNTIME_PM_OPS'
  .runtime_resume = resume_fn, \
                    ^
/home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src/netdev.c:8587:7: error: 'e1000e_pm_runtime_idle' undeclared here (not in a function)
       e1000e_pm_runtime_idle)
       ^
include/linux/pm.h:349:18: note: in definition of macro 'SET_RUNTIME_PM_OPS'
  .runtime_idle = idle_fn,
                  ^
make[2]: *** [/home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src/netdev.o] Error 1
make[1]: *** [_module_/home/mark/PF_RING/PF_RING/drivers/ZC/intel/e1000e/e1000e-3.0.4.1-zc/src] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.19.0-30-generic'
make: **\* [default] Error 2

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[verify status:]

mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$ ethtool -i eth1
driver: e1000e
version: 3.2.4.2-NAPI
firmware-version: 5.11-2
bus-info: 0000:0b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$ ethtool -i eth2
driver: e1000e
version: 3.2.4.2-NAPI
firmware-version: 5.11-2
bus-info: 0000:0b:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$
mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$
mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$
mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$ 

mark@PfRing-1:lsmod|grep pf
pf_ring               712704  0

mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$
mark@PfRing-1:~/PF_RING/PF_RING/drivers/PF_RING_aware/intel/e1000e/e1000e-3.0.4.1-zc/src$ cd /proc/net/pf_ring/
mark@PfRing-1:/proc/net/pf_ring$ ls
dev  info  plugins_info  stats
mark@PfRing-1:/proc/net/pf_ring$ more info
PF_RING Version          : 6.1.1 (dev:dc0e2f14547baf3ab5b29d2c10347a40d541e442)
Total rings              : 0

Standard (non DNA/ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
mark@PfRing-1:/proc/net/pf_ring$ cd dev
mark@PfRing-1:/proc/net/pf_ring/dev$ ls
eth0  eth1  eth2
mark@PfRing-1:/proc/net/pf_ring/dev$ cat eth1/info
Name:              eth1
Index:             9
Address:           00:26:55:DF:2C:8C
Polling Mode:      NAPI
Type:              Ethernet
Family:            Standard NIC
# Bound Sockets:   0

Max # TX Queues:   1
# Used RX Queues:  1

mark@PfRing-1:/proc/net/pf_ring/dev$ cat eth2/info
Name:              eth2
Index:             10
Address:           00:26:55:DF:2C:8D
Polling Mode:      NAPI
Type:              Ethernet
Family:            Standard NIC
# Bound Sockets:   0

Max # TX Queues:   1
# Used RX Queues:  1

can anyone kindly tell how to fix it?

Thanks
mark

**Comment by cardigliano** [comment]
Hi Mark
I just updated my Ubuntu 14.04 to latest available kernel which is 3.13.0.65.71 (where the driver compiles), 
while you have 3.19.0-30. However we will update the driver asap.

Alfredo

**Comment by cardigliano** [comment]
Hi Mark
there is a new e1000e driver in git (under testing), please let me know if it is working for you.

Thank you
Alfredo

**Comment by markc0303** [comment]
Hi Sir,

yes! i can load e1000e driver now.
thanks for great help!

BR,
Mark
