### ISSUE TITLE
when I kill zbalance_ipc system carsh

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#421]
Hi, I use pfring 7.3 in ubuntu-14.04.3, I often kill zbalance_ipc to restart all packet process, but today I kill it and restart, system carsh.
I see carsh log in screen and force restart machine,  I can not find carsh log /var/log all file.

**Comment by laoyang103** [comment]
@cardigliano 
https://github.com/laoyang103/acm-source/blob/master/20181019165912.jpg

**Comment by cardigliano** [comment]
@laoyang103 this looks like an old bug, are you using latest revision? Please update the drivers and make sure you are loading latest one.

**Comment by laoyang103** [comment]
this is my version, got it from http://packages.ntop.org, I just found pfring_7.3.0-2192_amd64.deb, are you means this diff?

> root@localhost:/data/kpi# dpkg -l | grep pf | awk '{print $2,$3}'
e1000e-zc-dkms 3.4.0.2.2056
fm10k-zc-dkms 0.23.5.2056
i40e-zc-dkms 2.4.6.2056
igb-zc-dkms 5.3.5.18.2056
ixgbe-zc-dkms 5.3.7.2056
libmpfr4:amd64 3.1.2-1
pfring 7.3.0-2056
pfring-dkms 7.3.0
pfring-drivers-zc-dkms 1.3

**Comment by cardigliano** [comment]
Please update to latest revision (2192)

**Comment by laoyang103** [comment]
OK I will test
