### ISSUE TITLE
Can I use zcount captrue NIC without "zc:"

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#422]
Hi, I use PF_RING-7.3, as we know zc only use for ixgbe igb e1000e driver NIC, now I want to use zc for more NIC, I test zcount -i eth0, the eth0 can be r8169 e1000 or an virtual machine NIC, I test in an virtual machine and it drop packet on a low traffic, where is my mistake or I only can use pf_ring or libpcap?

**Comment by cardigliano** [comment]
@laoyang103 you should be able to use zcount (ZC API) with any network card, however it does not provide performance improvements as it still uses standard drivers, you should get the same performance of pfcount (standard API)

**Comment by laoyang103** [comment]
OK, I know
