### ISSUE TITLE
ixgbe-zc build failure for kernel 3.10.0-957.el7.x86_64 (RHEL 7.6)

### ISSUE THREAD

**Issue by utilitynerd** [ntop/PF_RING#428]
ixgbe-zc fails to install on the newly released RedHat 7.6 (kernel 3.10.0-957.el7.x86_64).

Yum output:

Loading new ixgbe-zc-5.3.7.2232 DKMS files...
Building for 3.10.0-957.el7.x86_64
Building initial module for 3.10.0-957.el7.x86_64
Error! Bad return status for module build on kernel: 3.10.0-957.el7.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/make.log for more information.
warning: %post(ixgbe-zc-5.3.7.2232-dkms.noarch) scriptlet failed, exit status 10

make.log:

DKMS make.log for ixgbe-zc-5.3.7.2232 for kernel 3.10.0-957.el7.x86_64 (x86_64)
Wed Nov 14 16:24:04 PST 2018
make -C /lib/modules/3.10.0-957.el7.x86_64/build SUBDIRS=/var/lib/dkms/ixgbe-zc/5.3.7.2232/build modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-957.el7.x86_64'
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_main.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_common.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_api.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_param.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_lib.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_ethtool.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/kcompat.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_82598.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_82599.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_x540.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_x550.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_sriov.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_mbx.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_dcb.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_dcb_82598.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_dcb_82599.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_sysfs.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_procfs.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_phy.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_dcb_nl.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_fcoe.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_debugfs.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_ptp.o
In file included from /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_osdep.h:38:0,
                 from /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_type.h:66,
                 from /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_dcb.h:28,
                 from /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe.h:45,
                 from /var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_main.c:52:
/var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_main.c: In function ‘__ixgbe_setup_tc’:
/var/lib/dkms/ixgbe-zc/5.3.7.2232/build/kcompat.h:5767:31: error: ‘TC_SETUP_MQPRIO’ undeclared (first use in this function)
 #define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
                               ^
/var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_main.c:10313:7: note: in expansion of macro ‘TC_SETUP_QDISC_MQPRIO’
  case TC_SETUP_QDISC_MQPRIO:
       ^
/var/lib/dkms/ixgbe-zc/5.3.7.2232/build/kcompat.h:5767:31: note: each undeclared identifier is reported only once for each function it appears in
 #define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
                               ^
/var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_main.c:10313:7: note: in expansion of macro ‘TC_SETUP_QDISC_MQPRIO’
  case TC_SETUP_QDISC_MQPRIO:
       ^
make[2]: *** [/var/lib/dkms/ixgbe-zc/5.3.7.2232/build/ixgbe_main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/var/lib/dkms/ixgbe-zc/5.3.7.2232/build] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.el7.x86_64'
make: *** [default] Error 2

**Comment by cardigliano** [comment]
@utilitynerd we are working on this, a patch will be provided asap (7.6 is still beta), thank you for reporting.

**Comment by utilitynerd** [comment]
I understand new kernels / versions take time to support.  Thanks for tireless effort keeping this project going.

**Comment by jcmathews** [comment]
@cardigliano :
These below mentioned definitions aren't required for above mentioned kernel version as the definition itself is present in linux/netdevice.h  as
enum tc_setup_type {
        TC_SETUP_QDISC_MQPRIO,

Please confirm.

PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/kcompat.h://#define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
PF_RING/drivers/intel/fm10k/fm10k-0.23.5-zc/src/kcompat.h://#define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
PF_RING/drivers/intel/i40e/i40e-2.4.6-zc/src/kcompat.h://#define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
PF_RING/drivers/intel/igb/igb-5.3.5.18-zc/src/kcompat.h://#define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
PF_RING/drivers/intel/ixgbe/ixgbe-5.3.7-zc/src/kcompat.h://#define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO
PF_RING/drivers/intel/ixgbevf/ixgbevf-4.5.1-zc/src/kcompat.h://#define TC_SETUP_QDISC_MQPRIO TC_SETUP_MQPRIO

**Comment by cardigliano** [comment]
@jcmathews a driver update is available (on github, new packages will be available soon) to support 3.10.0-957.1.3.el7. 
As of the "disagrees about version of symbol" issues, are you manually loading the modules or using dkms? Did you rebuild pf_ring.ko?

**Comment by jcmathews** [comment]
Thanks, i sorted out the disagree problem. 
Yes, i commented out those and built pf_ring.
