### ISSUE TITLE
After commit: d31def0bd55e125799ce294fb9cfd720d87cb37d libpcap.so.1.6.2 does not correctly link to libpfring

### ISSUE THREAD

**Issue by utilitynerd** [ntop/PF_RING#43]
I apologize for my lack of C programming / build chain knowledge, but
I'm unable to successfully use the built libpcap.so.1.6.2 library,
included in the pf_ring source, after commit:
d31def0bd55e125799ce294fb9cfd720d87cb37d

In case it matters, my use case for pf_ring is having it load balance
network traffic, across many snort instances.  I'm running fully
updated RHEL 6.7, using an Intel 82599ES network card, and attempting
to configure pf_ring in zc mode.  This setup has been working for the
last several months.

Here is the relevant snippet of the script I'm using to build pf_ring
and it's components.

cd $BUILD_ROOT_DIR/pf_ring
cd kernel
echo -e "\n\nStarting Build of pf_ring kernerl \n\n" >>$BUILD_LOG
make clean >>$BUILD_LOG
make >>$BUILD_LOG
sudo make install >>$BUILD_LOG

cd ../userland/lib
echo -e "\n\nStarting Build of pf_ring userland/lib \n\n">>$BUILD_LOG
./configure >>$BUILD_LOG
make clean >>$BUILD_LOG
make >>$BUILD_LOG
sudo make install >>$BUILD_LOG

cd ../libpcap
echo -e "\n\nStarting Build of pf_ring userland/libpcap \n\n">>$BUILD_LOG
./configure >>$BUILD_LOG
make clean >>$BUILD_LOG
make >>$BUILD_LOG
sudo make install >>$BUILD_LOG

The rest of the script builds the ixgbe zero copy driver, the snort
daq, the pf_ring daq zero copy module, and finally snort itself.

Results when building with pf_ring commit:
217e3043f7956020f439f0a722b1204eadfc47b3

ldd /usr/local/lib/libpcap.so.1.6.2
        linux-vdso.so.1 =>  (0x00007ffd6f2a8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff0c4680000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ff0c4478000)
        libnl.so.1 => /lib64/libnl.so.1 (0x00007ff0c4225000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff0c3e91000)
        /lib64/ld-linux-x86-64.so.2 (0x000000381cc00000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff0c3c0d000)

snort runs / works as expected

Results when building with pf_ring commit:
d31def0bd55e125799ce294fb9cfd720d87cb37d

[root@fsb-07 ~]# ldd /usr/local/lib/libpcap.so.1.6.2
        linux-vdso.so.1 =>  (0x00007ffecb520000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa70d895000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fa70d68d000)
        libnl.so.1 => /lib64/libnl.so.1 (0x00007fa70d43a000)
        ../lib/libpfring.so => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007fa70d0a6000)
        /lib64/ld-linux-x86-64.so.2 (0x000000381cc00000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa70ce21000)

snort: snort: error while loading shared libraries:
../lib/libpfring.so: cannot open shared object file: No such file or
directory

**Comment by cardigliano** [comment]
Please try with latest commit.

Thank you
Alfredo

**Comment by utilitynerd** [comment]
Thank you for your reply.

I tried building (using the commands given above) with the latest commit and unfortunately run into the same error.

[root@fsb-07 ~]# ldd /usr/local/lib/libpcap.so.1.6.2
        linux-vdso.so.1 =>  (0x00007ffcf69e3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2adae9f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f2adac97000)
        libnl.so.1 => /lib64/libnl.so.1 (0x00007f2adaa44000)
        ../lib/libpfring.so => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007f2ada6b0000)
        /lib64/ld-linux-x86-64.so.2 (0x000000381cc00000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2ada42b000)

If it's helpful, I can post the full build script I'm using as well as the most recent build log.

**Comment by cardigliano** [comment]
Did you rebuild the daq with the instructions below after updating from git?
autoreconf -ivf
./configure
make
cp .libs/daq_pfring_zc.so /usr/local/lib/daq/

Alfredo

**Comment by utilitynerd** [comment]
I just preformed a full rebuild, including the commit from this morning, and everything is working beautifully.

I really appreciate all the hard work that goes into pf_ring and associated projects and am especially thankful for the time spent fixing my specific problem.  Keep up the amazing work!
