### ISSUE TITLE
[FT] pfring_ft_stats::flows (total or current ?) number of flows

### ISSUE THREAD

**Issue by mryamac** [ntop/PF_RING#436]
I simply run the ftflow.c in the example_ft folder.
Although  void pfring_ft_flow_free ( pfring_ft_flow * |flow  ) function is called, number of flows never decreases. pfring_ft_stats::flows constantly increases. I expect this number is the current number of flows

**Comment by cardigliano** [comment]
pfring_ft_stats::flows counts the total number of flows created, if you need the number of "current" active flows we need to add this to the stats.

**Comment by cardigliano** [comment]
Active flows stats are now available in pfring_ft_stats.active_flows (latest dev code)

**Comment by mryamac** [comment]
Thank you very much, it can be done using counter in the callbacks (new flow-expire flow); but this is the more programmatic way. Thanks a lot again
