### ISSUE TITLE
[FT] Is it possible to pass some custom data from custom nDPI to flow table

### ISSUE THREAD

**Issue by mryamac** [ntop/PF_RING#438]
Hello,
I want to detect custom protocol in the nDPI. Then If this protocol found, I need to pass some metadata from nDPI to flow table. If there is a pointer in the pfring_ft_flow_value, It would be beneficial. In my application, when flow expires, I will print flow information and this custom metadata. Is it possible or How can I achive this? Thanks all.

**Comment by cardigliano** [comment]
@mryamac how are you implementing support for this custom protocol? Are you going to write a new .c protocol dissector?

**Comment by mryamac** [comment]
yes I will write new.c file; but I need to create new function prototype for ft library. What I mean is that, For example, if I detect http protocol, I need to get host names

**Comment by mryamac** [comment]
Here is the way I think. I don't know exactly which functions are called in nDPI; but I have an idea. 

For example, I need to get hostnames for http connection.

-  In the nDPI part, If I detect the HTTP then I will allocate some memory to copy hostname

-  and this pointer is copied to the FT library. 

- Therefore when a flow expires, I can get the hostname. 

Finally, I can log the hostnames related to the session.

**Comment by lucaderi** [comment]
@mryamac As of today with nDPI we already detect the HTTP host name. Would you be happy to read this info?

**Comment by mryamac** [comment]
Thank you very much. I am very glad to see these quick updates. As you know there are lots of protocols, It is not possible to work with all of them. If you provide an interface to be able to process on layer 7 such as detecting hostname or some fields in the HTTP header, It would be nice for other developers trying to implement DPI applications.
