### ISSUE TITLE
[PF_RING FT] Static compilation problem with nDPI.

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#441]
My application uses PF_RING FT and nDPI.
I build both from latest 'dev' branch and link static libraries not dynamic.

Than on start of the application:

```
#########################################################################
# ERROR: You do not seem to have a valid PF_RING FT 7.3.0.181128 license [051E631C9208AB1B]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with flow processing limited to 5 minutes
#########################################################################
*** /usr/local/lib/libndpi.so not found or missing symbols ***
NTOP: pfring_ft_create_table error
```

Seems like there is always check for shared library.

**Comment by vitalivanov** [comment]
```
$ ldd test_app | grep -i ndpi
$ ldd test_app| grep -i ring
$
```

**Comment by vitalivanov** [comment]
@cardigliano @lucaderi please check

**Comment by cardigliano** [comment]
@vitalivanov PF_RING FT supports dynamic linking only at the moment, if this is not an option for you, we need to add a library able to link ndpi statically.

**Comment by vitalivanov** [comment]
@cardigliano you put static libraries too for both nDPI and PF_RING FT and the program links correctly during the build.
I think it's just some extra checks that you do in PF_RING FT.

For us static linking is what we want to go. Can you please check? It should be something trivial...

**Comment by cardigliano** [comment]
@vitalivanov dynamic linking is based on dlopen at the moment, that is why static linking is not working for you. Changing this is not trivial and requires some time.. Any reason you cannot use the shared library in the meanwhile?

**Comment by vitalivanov** [comment]
@cardigliano there is a reason why we need static libraries.
And you actually provide them now but they are not working. I would be great to have it fixed.
Thanks in advance...

**Comment by cardigliano** [comment]
@vitalivanov I pushed a library update, please check it

**Comment by vitalivanov** [comment]
Thanks. Verified. Working fine.

**Comment by cardigliano** [comment]
Thank you

**Comment by MykolaLiu** [comment]
Reproduced on latest sources.
@cardigliano @lucaderi please check

**Comment by cardigliano** [comment]
@MykolaLiu what did you reproduce exactly? Please provide your configuration/output. Thank you.

**Comment by vitalivanov** [comment]
@cardigliano we need to reopen this one. I do not think it worked ever. Just some artifact in form of .so file presence in the system made impression that it works

**Comment by cardigliano** [comment]
@vitalivanov please explain what is not working (I thought it was) and what you need. Thank you.

**Comment by MykolaLiu** [comment]
@cardigliano 
nDPI(commit 6c1d236a03f6c41f14d0d3c8a7627548fcd55779) is being used
Application is linked with libndpi.a/libpfring.a. Application does not required libndpi.so and libpfring.so according to ldd.

Application is compiled/started ok without any warning. But when pfring_ft_create_table is calling next error is raised : 
*** /usr/local/lib/libndpi.so not found or missing symbols ***

**Comment by cardigliano** [comment]
@MykolaLiu please note that by default FT uses dlopen to load nDPI, to avoid linking issues. I pushed a new configure option to disable dlopen, please update and run:
PF_RING/userland
./configure --disable-ft-dl
cd lib 
make

**Comment by MykolaLiu** [comment]
configure: WARNING: unrecognized options: --disable-ft-dl

@cardigliano

**Comment by vitalivanov** [comment]
@MykolaLiu it's added few minutes ago, let's try it now...

**Comment by MykolaLiu** [comment]
@vitalivanov 
Thank for reminding. Above mentioned error has been disappeared.
@cardigliano 
Even with ./configure --disable-ft-dl
Error with *** /usr/local/lib/libndpi.so not found or missing symbols *** is raised.

**Comment by cardigliano** [comment]
Can I see the output of this?
cd PF_RING/userland/lib
make

**Comment by vitalivanov** [comment]
@cardigliano once we got latest nDPI and PF_RING - it's OK.

Now we can close it.
Fixed by:

commit 0be0440053dc36853d46c1feba396dd7c46bf21b
Author: Alfredo Cardigliano <cardigliano@ntop.org>
Date:   Tue Mar 12 16:35:59 2019 +0100

    configure --disable-ft-dl
