### ISSUE TITLE
[PF_RING FT] API to install License.

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#442]
Can you please add API to install License after application starts in demo mode:
```
#########################################################################
# ERROR: You do not seem to have a valid PF_RING FT 7.3.0.181128 license [051E631C9208AB1B]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with flow processing limited to 5 minutes
#########################################################################
```
Like pfring_ft_set_license and if valid license is added demo mode would be disabled.

**Comment by vitalivanov** [comment]
@cardigliano @lucaderi

**Comment by cardigliano** [comment]
@vitalivanov I guess this is needed to "activate" this feature while the application is running. Since the license is usually stored under /etc, and the application could not have permissions to write there, what about adding an API to just "check again" the license, after installing it "manually"?

**Comment by vitalivanov** [comment]
@cardigliano yes, to activate when application is running.
Installing license manually is fine on PC. But if you think about appliances and access to them thru remote API/RPC/REST then it's much more convenient to have it handled by NTOP API.
I can try writing file to proper location but then NTOP part is changed. This should be done as part of API.
I do not see any challenges to implement this.

**Comment by cardigliano** [comment]
@vitalivanov the only challenge is with write permissions to /etc (this would not work for many applications dropping privileges for instance), that is why I was suggesting an external script (I meant this with "manual") for installing the license, and an API for reloading it in ZC, however we are open also to other options. Is your application always running as root?

**Comment by vitalivanov** [comment]
@cardigliano PF_RING FT is for applications based on DPDK. They all run under root.
I'm OK with any solution as long as you do not need to reboot your application to install and apply valid license.
I prefer API to take care of installation and validation. If you do not want /etc you can always check permissions and install to user directory only if he doesn't have rights for system wide access.

**Comment by cardigliano** [comment]
@vitalivanov latest dev code includes a new API pfring_ft_set_license. Please note that it now requires pfring_ft_create_table to be called after pfring_ft_set_license, does this work for you, or you need to create an ft object before setting the license?

**Comment by vitalivanov** [comment]
@cardigliano thanks for looiking into this.
You usually create ft object once on start and this approach with licenses would complecate application logic a lot.
If it’s possible i would prefer to have API to set license from any logical point.

**Comment by cardigliano** [comment]
@vitalivanov now the license check happens also after a ft object has been created
