### ISSUE TITLE
Connecting to a cluster interface from a normal user fails.

### ISSUE THREAD

**Issue by jhaprins** [ntop/PF_RING#443]
I have a zbalance_ipc cluster running that i want to use to capture traffic for a BRO/Snort combination. When I try to connect to the zc:10@0 interface using pfcount as a root user this works fine. When I try to do this as a regular user the user can't access the interface. 

Tried to follow http://www.ntop.org/guides/pf_ring/capabilities.html but that doesn't fix the issue.

-bash-4.2$ getcap /usr/bin/pfcount 
/usr/bin/pfcount = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+eip
-bash-4.2$ pfcount -i zc:10@0
pfring_open error [No such device] (pf_ring not loaded or interface zc:10@0 is down ?)
-bash-4.2$ logout
[root@idsprobe01 net]# pfcount -i zc:10@0
Using PF_RING v.7.3.0
Capturing from zc:10@0 [mac: unknown][if_index: -1][speed: 0Mb/s]
# Device RX channels: 1
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/23515-none.95

[root@idsprobe01 net]# mount |grep hugepages
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
none on /dev/hugepages type hugetlbfs (rw,relatime,seclabel,gid=994)
[root@idsprobe01 net]# cat /etc/group |grep 994
bro:x:994:

[root@idsprobe01 net]# su - bro
Last login: Wed Dec 12 14:57:56 CET 2018 on pts/0
-bash-4.2$ groups
bro sshaccess

**Comment by jhaprins** [comment]
A bro process started as the bro user has the following capabilities, but fails to open the zc:10 cluster interface.

[root@idsprobe01 etc]# ps auxww |grep bro |grep -v grep |grep -v su |grep -v bash |awk '{print "getpcaps "$2}' |sh
Capabilities for `8703': = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+ep
Capabilities for `8704': = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+ep
Capabilities for `8744': = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+ep
Capabilities for `8745': = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+ep
Capabilities for `8783': = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+ep
Capabilities for `8784': = cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin+ep

**Comment by jhaprins** [comment]
I might be on to something. The file /dev/hugepages/pfring_zc_10 is group root. The directory /dev/hugepages is group bro.
But the file is not group bro. The logs give permission denied on that file.
Changing the group of that file to bro and doing chmod g+w on that file fixes it.
Now I need to find why the gid option set in the hugepages.conf file doesn't fix this.

**Comment by jhaprins** [comment]
/etc/pf_ring/hugepages.conf:

node=0 hugepagenumber=1024 gid=994

**Comment by cardigliano** [comment]
@jhaprins I guess this happens because you are running zbalance_ipc as root, adding the capabilities also to that application and running it as user should fix it.

**Comment by jhaprins** [comment]
The pf_ring service defines the /dev/hugepages, but the cluster config indeed creates the file under /dev/hugepages. So the next question is, how to start the service as a user instead of root.

**Comment by cardigliano** [comment]
If you are using zbalance_ipc as service (e.g. systemd), it starts and initialize stuff as root, thus the only option at the moment is to change the file permission as you are doing now..

**Comment by cardigliano** [comment]
@jhaprins just to make sure, is this working when running zbalance_ipc in foreground as user directly (not as a service)?
