### ISSUE TITLE
kill process sequence

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#445]
Hi @cardigliano 

  run a zbalance_ipc with -n 2, and run two zcount_ipc with -i zc:99@0 and -i zc:99@1, when I want to kill all proces, do I need to follow a sequence, for example first kill zbalance_ipc then kill zcount_ipc or first kill zcount_ipc then kill zbalance_ipc

**Comment by cardigliano** [comment]
@laoyang103 the shutdown order is not important, as long as you kill all the applications before running a new cluster (running zbalance_ipc again) with the same ID

**Comment by laoyang103** [comment]
OK thank you very much
