### ISSUE TITLE
[PF RING FT] pfring_ft_license returns incorrect value

### ISSUE THREAD

**Issue by MykolaLiu** [ntop/PF_RING#450]
pfring_ft_license returns 1, when license is not set.
According to doxygen, 0 has to be returned instead.

/**
* Get license info.
* @param system_id A buffer (32 bytes long) where system id is returned. (out)
* @param license_expiration A pointer to a time_t where license expiration is returned. (out)
* @param maintenance_expiration A pointer to a time_t where maintenance expiration is returned. (out)
* @return 1 if a valid license is installed, 0 otherwise.
*/

@cardigliano @lucaderi Could you please take a look on this issue?

**Comment by cardigliano** [comment]
@MykolaLiu the return value has been fixed, thank you for reporting.

**Comment by vitalivanov** [comment]
@cardigliano This is still a problem

**Comment by cardigliano** [comment]
Uhm, what do you get with this command?
PF_RING/userland/examples_ft/ftflow -V

**Comment by vitalivanov** [comment]
It's from our application not from test app.
Let me know if you need help to see it.

**Comment by cardigliano** [comment]
Got it, I want to check if ftflow -V returns the expected value on your system (it is working fine on my system)

**Comment by vitalivanov** [comment]
@cardigliano 
I think it's because of version incopatibilities between nDPI and PF RING FT.
I use latest dev from both repositories.
When PF RING init starts i see the following:

```
[NDPI] INTERNAL ERROR missing protoName initialization for [protoId=0]: recovering
[NDPI] INTERNAL ERROR missing protoName initialization for [protoId=1]: recovering
[NDPI] INTERNAL ERROR missing protoName initialization for [protoId=2]: recovering
```

**Comment by cardigliano** [comment]
@vitalivanov I pushed a library update to make sure FT and nDPI are in sync, please update to latest dev branch

**Comment by cardigliano** [comment]
@vitalivanov is it working for you now?
