### ISSUE TITLE
zbalance_ipc fanout traffic in docker question

### ISSUE THREAD

**Issue by liuchuang** [ntop/PF_RING#452]
hi,
after read the docs about pf_ring/docker,now i can run zbalance_ipc``` -i eth2 -c 1 -n 2,2,2 ```in one docker forward host traffic,and run pfcount``` -i zc:1@0 ```receive traffic from zbalance in the same docker.

but how can i run pfcount in another docker receive the traffic from the first zbalance docker?i had test run docker with bind hugetlb and use --net=host --ipc=host,but still can not work.

error msg is:```pfring_open error [No such device] (pf_ring not loaded or interface zc:1@0 is down ?)```
my question is how to fanout host traffic to different dockers,thanks.

**Comment by cardigliano** [comment]
@liuchuang did you share /dev/hugepages also? Please note that ZC allocates shared memory from hugepages, thus all containers need to access the same hugetlbfs. Please read http://www.ntop.org/guides/pf_ring/containers/docker.html

**Comment by liuchuang** [comment]
@cardigliano , i had use share memory hugepages,my test details:
env:```host/docker centos7.5,pfring7.0.0```

docker1 cmd: ```docker run -it --name=zbalance --net=host --ipc=host --privileged --cap-add ipc_lock -v /dev/hugepages/:/dev/hugepages/ centos7.5_base bash```

docker2 cmd: ```docker run -it --name=pfcount --net=host --ipc=host --privileged --cap-add ipc_lock -v /dev/hugepages/:/dev/hugepages/ centos7.5_base bash```

in docker1: run ```./zbalance_ipc -i eth2 -c 2 -n 4,4 -m 1 -g 6 -p```(success)
in docker1: run ```./pfcount -i zc:2@0```(success)
in docker2: ```ls /dev/hugepages/pfring_zc_2```(exist)
in docker2:```cat /proc/net/pf_ring/1237203-eth2.464```
```
Bound Device(s)    : eth2
Active             : 1
Breed              : Standard
Appl. Name         : pfring-zc-2-eth2
Socket Mode        : RX only
Capture Direction  : RX only
Sampling Rate      : 1
IP Defragment      : No
BPF Filtering      : Disabled
Sw Filt Hash Rules : 0
Sw Filt WC Rules   : 0
Sw Filt Hash Match : 0
Sw Filt Hash Miss  : 0
Hw Filt Rules      : 0
Poll Pkt Watermark : 128
Num Poll Calls     : 0
Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
VLAN Id            : 65535
Slot Version       : 16 [7.0.0]
Min Num Slots      : 4098
Bucket Len         : 1600
Slot Len           : 1656 [bucket+header]
Tot Memory         : 6795264
Tot Packets        : 1
Tot Pkt Lost       : 0
Tot Insert         : 1
Tot Read           : 1
Insert Offset      : 384
Remove Offset      : 384
Num Free Slots     : 4098
Reflect: Fwd Ok    : 0
Reflect: Fwd Errors: 0
```
in docker2:run ```./pfcount -i zc:2@1```(failed)
error msg:```pfring_open error [No such device] (pf_ring not loaded or interface zc:2@1 is down ?)```

**Comment by liuchuang** [comment]
hi, @cardigliano , after read http://www.ntop.org/guides/pf_ring/containers/docker.html and checked all my run parameters, os env, I still can't fanout traffic between dockers.do you have any advice? 

I had test 3 cases:
case1:run zbalance_ipc in host,and run pfcount in docker(failed)
case2:run zbalance_ipc in docker,and run pfcount in host(success)
case3:run zbalance_ipc in docker1,and run pfcount in docker2(failed)

**Comment by cardigliano** [comment]
Sorry for coming back on this so late. zbalance_ipc in host and run pfcount in docker works smoothly following the instruction in the guide (on ubuntu 20)
