### ISSUE TITLE
Cannot build for Linux ≥ 4.16 with CONFIG_AX25 disabled

### ISSUE THREAD

**Issue by ikle** [ntop/PF_RING#454]
Try to build 7.4.0-stable for Linux 4.19.11, got:
```
.../kernel/pf_ring.c: In function 'ring_notifier':
.../kernel/pf_ring.c:8170:37: error: 'struct net_device' has no member named 'ax25_ptr'
.../kernel/pf_ring.c:8184:195: error: 'struct net_device' has no member named 'ax25_ptr'
```
The problem triggered by
```
commit 19ff13f2a411d99af67d8e51867d54b86e1bf017
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Feb 13 08:52:01 2018 -0800

    net: Make ax25_ptr depend on CONFIG_AX25

...
diff --git a/include/linux/netdevice.h b/include/linux/netdevice.h
...
+#if IS_ENABLED(CONFIG_AX25)
        void                    *ax25_ptr;
+#endif
```

**Comment by cardigliano** [comment]
Thank you for reporting, we will fix this asap (please keep using a supported kernel from Ubuntu LTS or Centos in the meanwhile).

**Comment by jonbackhaus** [comment]
I'm having a similar problem; system configuration and terminal dump below. 
`$ uname -a`
`Linux odroid 4.14.87-153 #1 SMP PREEMPT Tue Dec 11 11:33:18 -02 2018 armv7l armv7l armv7l GNU/Linux`

ODROID does something funny with the kernel, so I had to really work to get the libraries and source ready to compile. I symlinked `/lib/modules/4.14.87-153/` to the installed `/lib/modules/4.14.87-041487/` to get the build to even start. Here's the error: 

```
root@eb08c789f4d2:/opt/PF_RING/kernel# make
make -C /lib/modules/4.14.87-153/build SUBDIRS=/opt/PF_RING/kernel EXTRA_CFLAGS='-I/opt/PF_RING/kernel -DGIT_REV="\"dev:1ff5dfeec1f07d3a3091b79296bfc36b814bcdad\"" -no-pie -fno-pie' modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.87-041487-generic'
  CC [M]  /opt/PF_RING/kernel/pf_ring.o
In file included from /opt/PF_RING/kernel/pf_ring.c:117:0:
/opt/PF_RING/kernel/pf_ring.c: In function 'ring_setsockopt':
./include/generated/utsrelease.h:2:32: error: invalid digit "8" in octal constant
 #define UTS_UBUNTU_RELEASE_ABI 041487
                                ^
/opt/PF_RING/kernel/pf_ring.c:6468:57: note: in expansion of macro 'UTS_UBUNTU_RELEASE_ABI'
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,2,0) && UTS_UBUNTU_RELEASE_ABI >= 28) || \
                                                         ^~~~~~~~~~~~~~~~~~~~~~
./include/generated/utsrelease.h:2:32: error: invalid digit "8" in octal constant
 #define UTS_UBUNTU_RELEASE_ABI 041487
                                ^
/opt/PF_RING/kernel/pf_ring.c:6469:57: note: in expansion of macro 'UTS_UBUNTU_RELEASE_ABI'
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,4,0) && UTS_UBUNTU_RELEASE_ABI >= 22))) || \
                                                         ^~~~~~~~~~~~~~~~~~~~~~
./include/generated/utsrelease.h:2:32: error: invalid digit "8" in octal constant
 #define UTS_UBUNTU_RELEASE_ABI 041487
                                ^
/opt/PF_RING/kernel/pf_ring.c:6486:57: note: in expansion of macro 'UTS_UBUNTU_RELEASE_ABI'
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,2,0) && UTS_UBUNTU_RELEASE_ABI >= 28) || \
                                                         ^~~~~~~~~~~~~~~~~~~~~~
./include/generated/utsrelease.h:2:32: error: invalid digit "8" in octal constant
 #define UTS_UBUNTU_RELEASE_ABI 041487
                                ^
/opt/PF_RING/kernel/pf_ring.c:6487:57: note: in expansion of macro 'UTS_UBUNTU_RELEASE_ABI'
        (UBUNTU_VERSION_CODE == KERNEL_VERSION(4,4,0) && UTS_UBUNTU_RELEASE_ABI >= 22))) || \
                                                         ^~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:332: recipe for target '/opt/PF_RING/kernel/pf_ring.o' failed
make[2]: *** [/opt/PF_RING/kernel/pf_ring.o] Error 1
Makefile:1538: recipe for target '_module_/opt/PF_RING/kernel' failed
make[1]: *** [_module_/opt/PF_RING/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.87-041487-generic'
Makefile:64: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cardigliano** [comment]
This has been fixed, please check latest dev. Thank you.

**Comment by thinrope** [comment]
I just hit that on a different (Gentoo) system, trying to sort it out... Can you point me to the commit that fixed it? I read through the logs and some of the code, but couldn't find anything related.
Alternatively, is next release coming in the next few days (then I can wait and not bother)?

**Comment by cardigliano** [comment]
@thinrope this required quite a few changes, this is the initial commit, however other patches follows this one (latest is from March 1st)
https://github.com/ntop/PF_RING/commit/2aa76765ff367e9c9c49c7373f7e2f51fb10b399

**Comment by ikle** [comment]
> I just hit that on a different (Gentoo) system, trying to sort it out... Can you point me to the commit that fixed it? I read through the logs and some of the code, but couldn't find anything related.
> Alternatively, is next release coming in the next few days (then I can wait and not bother)?

I think, current resolution is "won't fix" without explaning the reason. And the reason is the need for a private pointer in the structure net_device, but PF_RING is not in the upstream and thus cannot have its own private pointer here. The ax25_ptr is used (illegally) as a workaround.

If you can, just delete guards from include/linux/netdevice.h around ax25_ptr in struct net_device definition or enable AX25 in configuration.

**Comment by cardigliano** [comment]
@ikle please note that latest dev code from github is using a different approach, ax25_ptr is no longer used, a new symbol (function) is exported to the kernel instead.
