### ISSUE TITLE
pfring_ft_set_no_filter(pfring_ft_table *table)

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#456]
Once you set filter by pfring_ft_set_filter_protocol_by_name there is no way to remove them and set different filters.

It would be very convenient to have API to restore filters to default(none) and set new filters.

**Comment by vitalivanov** [comment]
@cardigliano can you check this one?

**Comment by cardigliano** [comment]
@vitalivanov you can reset a specific protocol using PFRING_FT_ACTION_DEFAULT as action. I guess what you need is a call to reset all filters in one call right?

**Comment by vitalivanov** [comment]
@cardigliano yes

**Comment by cardigliano** [comment]
A new API call has been added to reset all filters, example:
pfring_ft_set_filter_all_protocols(ft, PFRING_FT_ACTION_DEFAULT);
