### ISSUE TITLE
`pfring` Debian package should not depend on dkms

### ISSUE THREAD

**Issue by praseodym** [ntop/PF_RING#458]
I'm using PF_RING inside a Docker container, which I want to keep as slim as possible. Because I assume the host machine on which the container is going to run will have PF_RING already set up, all I need is the userland libraries.

The `pfring` Debian package contains these libraries. However, it also depends on `dkms`, which pulls in `gcc` and other build tools that bloat the container size:
```
$ dpkg -I pfring_7.5.0-2378_amd64.deb
[--snip--]
 Package: pfring
 Version: 7.5.0-2378
 Architecture: amd64
 Maintainer: Luca Deri <deri@ntop.org>
 Installed-Size: 20419
 Depends: ndpi (= 2.7.0-1482), net-tools, kmod, dkms, ethtool
 Recommends: pfring-dkms (= 7.5.0)
 Section: free
 Priority: optional
 Description: PF_RING (http://www.ntop.org/pf_ring/) [dev:d9afeaab60b61b876579c05d23b554f8d01069db]
```
Only `pfring-dkms` needs `dkms`; it already has this dependency specified, so `dkms` can be safely removed as a dependency from `pfring`. `kmod` should be made a dependency of `pfring-dkms` instead of `pfring`. The dependencies `ndpi`, `net-tools` and `ethtool` seem better suited as recommended (or maybe suggested) ones, not actual hard dependencies.

**Comment by cardigliano** [comment]
@praseodym dkms dependency should be definitely moved to pfring-dkms, we will fix it. Thank you for reporting.

**Comment by cardigliano** [comment]
@praseodym the dkms dependency has been moved. kmod is still there as it pfring script included in pfring may need it for managing kernel modules (regardless of pfring-dkms). Anyway this should fix your main issue about all the dkms and gcc related dependencies.
