### ISSUE TITLE
Cannot build for raspberry (Userland dir error)

### ISSUE THREAD

**Issue by baadie** [ntop/PF_RING#459]
Trying to compile on a rapsberry pi 3. Any thoughts on how to fix the issue below?

cd kernel; make
make[1]: Entering directory '/root/PF_RING/kernel'
make -C /lib/modules/4.14.79-v7+/build SUBDIRS=/root/PF_RING/kernel EXTRA_CFLAGS='-I/root/PF_RING/kernel -DGIT_REV="\"dev:939bd825ad729e178e8c77a61830ef5689ea7ae5\"" -no-pie -fno-pie' modules
make[2]: Entering directory '/root/linux-36612d5d7a88672a3e7dd6cb458dbbbca0d75efe'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory '/root/linux-36612d5d7a88672a3e7dd6cb458dbbbca0d75efe'
make[1]: Leaving directory '/root/PF_RING/kernel'
cd userland; make
make[1]: Entering directory '/root/PF_RING/userland'
cd lib; make
make[2]: Entering directory '/root/PF_RING/userland/lib'
ar x ../nbpf/libnbpf.a
cp ../nbpf/nbpf.h .
=*= making library libpfring.a =*=
ar rs libpfring.a pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '`
ranlib libpfring.a
=*= making library libpfring.so =*=
gcc -Wl,-soname,libpfring.so.1 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl    -o libpfring.so
make[2]: Leaving directory '/root/PF_RING/userland/lib'
cd libpcap; make
make[2]: Entering directory '/root/PF_RING/userland/libpcap-1.8.1'
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
gcc -shared -Wl,-soname,libpcap.so.$MAJOR_VER  \
    -o libpcap.so.$VER pcap-linux.o pcap-usb-linux.o pcap-netfilter-linux.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o   ../lib/libpfring.a -lpthread -lrt   -lrt -ldl
make[2]: Leaving directory '/root/PF_RING/userland/libpcap-1.8.1'
cd examples; make
make[2]: Entering directory '/root/PF_RING/userland/examples'
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfcount.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfcount
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfcount_multichannel.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfcount_multichannel
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  preflect.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o preflect
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfflow_offload.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfflow_offload
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfbridge.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfbridge
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  alldevs.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o alldevs
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pcap2nspcap.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pcap2nspcap
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfcount_82599.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfcount_82599
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfsystest.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfsystest
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfsend.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfsend
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pflatency.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pflatency
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pftimeline.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pftimeline
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pcount.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pcount
gcc  -O2 -DHAVE_PF_RING -Wall -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfwrite.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfwrite
make[2]: Leaving directory '/root/PF_RING/userland/examples'
cd examples_zc; make
make[2]: Entering directory '/root/PF_RING/userland/examples_zc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/PF_RING/userland/examples_zc'
cd examples_ft; make
make[2]: Entering directory '/root/PF_RING/userland/examples_ft'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/PF_RING/userland/examples_ft'
cd wireshark/extcap; make
make[2]: Entering directory '/root/PF_RING/userland/wireshark/extcap'
gcc  -O2 -DHAVE_PF_RING -Wall -I../../../kernel -I../../lib -I../../libpcap -Ithird-party `../../lib/pfring_config --include` -D ENABLE_BPF  -O2  ntopdump.o ../../libpcap/libpcap.a   ../../lib/libpfring.a ../../libpcap/libpcap.a   ../../lib/libpfring.a `../../lib/pfring_config --libs` -lpthread  -lrt -ldl  -lrt -o ntopdump
make[2]: Leaving directory '/root/PF_RING/userland/wireshark/extcap'
make[1]: Leaving directory '/root/PF_RING/userland'
cd drivers; make
make[1]: Entering directory '/root/PF_RING/drivers'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/PF_RING/drivers'
root@raspberrypi:~/PF_RING# make install
cd userland; make install
make[1]: Entering directory '/root/PF_RING/userland'
cd lib; make
make[2]: Entering directory '/root/PF_RING/userland/lib'
ar x ../nbpf/libnbpf.a
cp ../nbpf/nbpf.h .
=*= making library libpfring.a =*=
ar rs libpfring.a pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '`
ranlib libpfring.a
=*= making library libpfring.so =*=
gcc -Wl,-soname,libpfring.so.1 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl    -o libpfring.so
make[2]: Leaving directory '/root/PF_RING/userland/lib'
cd libpcap; make
make[2]: Entering directory '/root/PF_RING/userland/libpcap-1.8.1'
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
gcc -shared -Wl,-soname,libpcap.so.$MAJOR_VER  \
    -o libpcap.so.$VER pcap-linux.o pcap-usb-linux.o pcap-netfilter-linux.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o   ../lib/libpfring.a -lpthread -lrt   -lrt -ldl
make[2]: Leaving directory '/root/PF_RING/userland/libpcap-1.8.1'
cd lib; make install
make[2]: Entering directory '/root/PF_RING/userland/lib'
ar x ../nbpf/libnbpf.a
cp ../nbpf/nbpf.h .
=*= making library libpfring.a =*=
ar rs libpfring.a pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '`
ranlib libpfring.a
mkdir -p /usr/local/include
cp pfring.h pfring_mod_sysdig.h    ../nbpf/nbpf.h /usr/local/include/
mkdir -p /usr/local/lib
cp libpfring.a /usr/local/lib/
=*= making library libpfring.so =*=
gcc -Wl,-soname,libpfring.so.1 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl    -o libpfring.so
mkdir -p /usr/local/lib
cp libpfring.so /usr/local/lib/
cd /usr/local/lib; ln -sf libpfring.so libpfring.so.7.5.0
cd /usr/local/lib; ln -sf libpfring.so libpfring.so.7
make[2]: Leaving directory '/root/PF_RING/userland/lib'
cd libpcap; make install
make[2]: Entering directory '/root/PF_RING/userland/libpcap-1.8.1'
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
gcc -shared -Wl,-soname,libpcap.so.$MAJOR_VER  \
    -o libpcap.so.$VER pcap-linux.o pcap-usb-linux.o pcap-netfilter-linux.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o   ../lib/libpfring.a -lpthread -lrt   -lrt -ldl
[ -d /usr/local/lib ] || \
    (mkdir -p /usr/local/lib; chmod 755 /usr/local/lib)
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
/usr/bin/install -c libpcap.so.$VER /usr/local/lib/libpcap.so.$VER; \
ln -sf libpcap.so.$VER /usr/local/lib/libpcap.so.$MAJOR_VER; \
ln -sf libpcap.so.$MAJOR_VER /usr/local/lib/libpcap.so
#
# Most platforms have separate suffixes for shared and
# archive libraries, so we install both.
#
[ -d /usr/local/lib ] || \
    (mkdir -p /usr/local/lib; chmod 755 /usr/local/lib)
/usr/bin/install -c -m 644 libpcap.a /usr/local/lib/libpcap.a
ranlib /usr/local/lib/libpcap.a
[ -d /usr/local/lib ] || \
    (mkdir -p /usr/local/lib; chmod 755 /usr/local/lib)
[ -d /usr/local/include ] || \
    (mkdir -p /usr/local/include; chmod 755 /usr/local/include)
[ -d /usr/local/include/pcap ] || \
    (mkdir -p /usr/local/include/pcap; chmod 755 /usr/local/include/pcap)
[ -d /usr/local/share/man/man1 ] || \
    (mkdir -p /usr/local/share/man/man1; chmod 755 /usr/local/share/man/man1)
[ -d /usr/local/share/man/man3 ] || \
    (mkdir -p /usr/local/share/man/man3; chmod 755 /usr/local/share/man/man3)
[ -d /usr/local/share/man/man5 ] || \
    (mkdir -p /usr/local/share/man/man5; chmod 755 /usr/local/share/man/man5)
[ -d /usr/local/share/man/man7 ] || \
    (mkdir -p /usr/local/share/man/man7; chmod 755 /usr/local/share/man/man7)
for i in pcap.h pcap-bpf.h pcap-namedb.h pcap/bpf.h pcap/bluetooth.h pcap/can_socketcan.h pcap/dlt.h pcap/export-defs.h pcap/ipnet.h pcap/namedb.h pcap/nflog.h pcap/pcap.h pcap/sll.h pcap/vlan.h pcap/usb.h; do \
	/usr/bin/install -c -m 644 ./$i \
	    /usr/local/include/$i; done
[ -d /usr/local/bin ] || \
    (mkdir -p /usr/local/bin; chmod 755 /usr/local/bin)
/usr/bin/install -c pcap-config /usr/local/bin/pcap-config
for i in pcap-config.1; do \
	/usr/bin/install -c -m 644 ./$i \
	    /usr/local/share/man/man1/$i; done
for i in pcap-savefile.manfile.in; do \
	/usr/bin/install -c -m 644 `echo $i | sed 's/.manfile.in/.manfile/'` \
	    /usr/local/share/man/man5/`echo $i | sed 's/.manfile.in/.5/'`; done
for i in pcap-filter.manmisc.in pcap-linktype.manmisc.in pcap-tstamp.manmisc.in; do \
	/usr/bin/install -c -m 644 `echo $i | sed 's/.manmisc.in/.manmisc/'` \
	    /usr/local/share/man/man7/`echo $i | sed 's/.manmisc.in/.7/'`; done
make[2]: Leaving directory '/root/PF_RING/userland/libpcap-1.8.1'
cd examples; make install
make[2]: Entering directory '/root/PF_RING/userland/examples'
mkdir -p /usr/bin
cp pfcount pfcount_multichannel preflect pfflow_offload pfbridge alldevs pcap2nspcap pfcount_82599 pfsystest pfsend pflatency pftimeline pcount pfwrite /usr/bin/
make[2]: Leaving directory '/root/PF_RING/userland/examples'
cd examples_zc; make install
make[2]: Entering directory '/root/PF_RING/userland/examples_zc'
mkdir -p /usr/bin
cp  /usr/bin/
cp: missing destination file operand after '/usr/bin/'
Try 'cp --help' for more information.
Makefile:89: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/root/PF_RING/userland/examples_zc'
Makefile:76: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/root/PF_RING/userland'
Makefile:7: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by cardigliano** [comment]
@baadie please update as I fixed this error (please note that ZC examples cannot be compiled/installed on raspberry)
