### ISSUE TITLE
Error with modprobe or insmod and pf_ring Kernelmodule

### ISSUE THREAD

**Issue by mhthdeg** [ntop/PF_RING#46]
Hello,

when I try to load the pf_ring.ko Kernelmodule I receive the following error.

```
root@linaro-nano:/lib/modules/3.18.0-00257-g034e7cb/kernel/net# ls
bridge  pf_ring
root@linaro-nano:/lib/modules/3.18.0-00257-g034e7cb/kernel/net# modprobe pf_ring
[ 1944.840226] pf_ring: version magic '3.18.0-00257-g034e7cb mod_unload ARMv5 p2v8 ' should be '3.18.0-00257-g034e7cb SMP mod_unload ARMv7 p2v8 '
modprobe: ERROR: could not insert 'pf_ring': Exec format error
```

I nearly tried everything to fix the version magic from kernel compilation side. Could it be a problem with the pf_ring Kernelmodule Makefile?

**Comment by lucaderi** [comment]
I think you have not compiled the PF_RING kernel module on the same machine where you are running (insmod) it. Please compile it on the same machine and it should work.
