### ISSUE TITLE
[PF RING FT] pfring_ft_set_license does not work properly

### ISSUE THREAD

**Issue by MykolaLiu** [ntop/PF_RING#460]
In case of absence the /etc/pf_ring directory, calling of pfring_ft_set_license with a proper key does not set license, even a directory /etc/pf_ring is not created.

@cardigliano @lucaderi Could you please take a look on this issue?

**Comment by cardigliano** [comment]
@MykolaLiu latest dev code should fix this (pfring_ft_set_license assumed that the directory was already there, which is not true unless you install from packages)
