### ISSUE TITLE
When trying to send an RST packet, a generic packet is also sent.

### ISSUE THREAD

**Issue by rudyeeee** [ntop/PF_RING#461]
```
// sample
while(!do_shutdown){
    if(pfring_zc_recv_pkt(queue, &b, 1)){
            data = pfring_zc_pkt_buff_data(b, queue);
            rc = parse_tcp_packet(data, &p);
            if ( rc != 0 ) { // not tcp
                continue;
            } 
            if( ntohs(p.tcphdr->dest) == 80  ){  
                // server -> client RST
                // reverse(s_mac<->d_mac, s_ip<->d_ip, s_port<->d_port & RST & re-compute checksum
                rc = create_block_packet(p, NULL, 1);
                b->len = rc;
                if( pfring_zc_send_pkt(outzq, &b, 1) < 0 ){
                    printf("pfring_zc_send_pkt error\n");
                }

                // client -> server RST
                // reverse(s_mac<->d_mac, s_ip<->d_ip, s_port<->d_port & RST & re-compute checksum
                rc = create_block_packet(p, NULL, 1);
                b->len = rc;
                if( pfring_zc_send_pkt(outzq, &b, 1) < 0 ){
                    printf("pfring_zc_send_pkt error\n");
                }
           }
    }
}
```

If the buffer is *HTTP*, the packet is reversed and changed to an RST packet, and `pfring_zc_send_pkt (outzq, & b, 1)` is used to transmit the packet.

Using tcpdump on the interface mapped to outzq, I see not only RST packets, but also regular packets coming into the queue.

![image](https://user-images.githubusercontent.com/15131409/52552314-16a29e80-2e23-11e9-9760-dd0be9e79171.png)

The interface only captures non-RST packets when it generates an RST packet. Why is this happening?

**Comment by cardigliano** [comment]
@derktam are you using standard or ZC drivers?

**Comment by rudyeeee** [comment]
@cardigliano I am using a standard driver.

**Comment by cardigliano** [comment]
@derktam did you try specifying the capture direction in tcpdump with -Q in|out|inout ?

**Comment by rudyeeee** [comment]
@cardigliano  OMG !. It is captured correctly in out mode. My mistake! Sorry.

![image](https://user-images.githubusercontent.com/15131409/52553402-b01f7f80-2e26-11e9-8506-f1c41ff70c17.png)

**Comment by cardigliano** [comment]
Glad it worked
