### ISSUE TITLE
Capture and Management using same drivers

### ISSUE THREAD

**Issue by micmoyles** [ntop/PF_RING#462]
Hi, 

I am trying to get to the bottom of an undesirable behaviour on some of our servers and have a question about how pf_ring treats interfaces. 

I noticed that when we stopped pf_ring, all the routes out of our management interface we removed. I specified our management interface in /etc/pf_ring/interfaces.conf but am no longer able to load zc drivers for my capture interface (because it uses the same i40e driver)

```
pf_ringctl[172243]: Skipping driver i40e: driver matches the management interface

cat /etc/pf_ring/interfaces.conf 
MANAGEMENT_INTERFACES="eno1"
CAPTURE_INTERFACES="eno2"

```

and here is my directory structure
```

root@----:/etc/pf_ring# tree 
.
├── A4BF014B5F09
├── hugepages.conf
├── interfaces.conf
├── override.conf
├── pf_ring.conf
├── pf_ring.start
└── zc
    ├── e1000e
    ├── fm10k
    ├── i40e
    │   ├── i40e.conf
    │   └── i40e.start
    └── ixgbe
```
eno1 and eno2 are physically separate. Is the inability to use zc drivers on my capture interface when the driver matches that of the management interface by design?

If not, can you suggest a way around this for me? 

Thanks for the help. I've already dug around open issues to see if this has been brought up before, apologies if I missed an existing ticket! 

Michael

**Comment by cardigliano** [comment]
Hi @micmoyles, as you noticed the pf_ring script does not (re)load a ZC driver if the same is in use by the management interface by default, this to avoid loosing the machine when you are connected from a remote location as reloading the driver could break the interface configuration. 
This said, you can still load a ZC driver in use by the management interface forcing it (as explained at http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html), as it will work as a standard driver unless you start capturing from the interface using the "zc:" prefix (in this case it gets disconnected from the Linux stack). You only need to make sure it gets the configuration back after reloading the driver.

**Comment by micmoyles** [comment]
@cardigliano  - thanks for the explanation. So if I understand correctly the driver will behave differently for each interface depending on whether or not I am capturing from it using the zc: prefix?

**Comment by cardigliano** [comment]
Correct, the interface will behave as ZC only when running an application with "zc:ethX" as interface name

**Comment by micmoyles** [comment]
Excellent, thanks a lot!
