### ISSUE TITLE
the feature “userspace ring” has been removed ?

### ISSUE THREAD

**Issue by hardboydu** [ntop/PF_RING#463]
I am maintaining an old system that uses features like "```pfcount -i usr1; pfsend -i userspace:usr1```", But using a new version, I found that this feature can't be used.

Is there any new feature that can replace this feature?

The version I am using is v5.6.2

**Comment by cardigliano** [comment]
@hardboydu there are 2 ways for achieving the same.

1. using ZC:

zsend -c 99
zcount_ipc -c 99 -i 0 (or pfcount -i zc:99@0)

2. using dummy interfaces and the stack module

modprobe dummy
ifconfig dummy0 up
pfsend -i stack:dummy0
pfcount -i dummy0
