### ISSUE TITLE
[PF_RING FT] pfring_ft_process alway returns PFRING_FT_ACTION_DEFAULT

### ISSUE THREAD

**Issue by MykolaLiu** [ntop/PF_RING#465]
Next scenario has been used to configure PF RING FT:
64 tables with following parameters are created:
 pfring_ft_create_table(PFRING_FT_TABLE_FLAGS_DPI 0, 0, 0);
For table #0 next configuration is applied:
 pfring_ft_set_filter_protocol_by_name(TABLE[0], "Skype", PFRING_FT_ACTION_FORWARD);
 pfring_ft_set_default_action(TABLE[0], PFRING_FT_ACTION_DISCARD);
 pfring_ft_set_flow_export_callback(TABLE[0], _ntop_process_flow, (void*)&id);

Packets from https://github.com/ntop/nDPI/blob/dev/tests/pcap/skype.pcap have been sent.
For all packets :
 pfring_ft_process(TABLE[0], ...) returns PFRING_FT_ACTION_DEFAULT.

How to enable debug mode. And how to figure out where problem is?

@cardigliano @lucaderi please check.

**Comment by cardigliano** [comment]
@MykolaLiu the same is working for me:

`# ./ftflow_pcap -i /home/blackout/skype.pcap -7 | grep FORWARD | wc -l`
`1036`

This is from a modified ftflow_pcap.c from github:

diff --git a/userland/examples_ft/ftflow_pcap.c b/userland/examples_ft/ftflow_pcap.c
index 9b2ea5e..37ce8f9 100644
--- a/userland/examples_ft/ftflow_pcap.c
+++ b/userland/examples_ft/ftflow_pcap.c
@@ -182,6 +182,9 @@ void process_packet(u_char *_deviceId, const struct pcap_pkthdr *h, const u_char
 
   action = pfring_ft_process(ft, p, (pfring_ft_pcap_pkthdr *) h, &ext_hdr);
 
+  if (action == PFRING_FT_ACTION_FORWARD)
+    printf("FORWARD\n");
+
   if (verbose) {
     char buffer[256];
     buffer[0] = '\0';
@@ -265,6 +268,9 @@ int main(int argc, char* argv[]) {
     return -1;
   }
 
+  pfring_ft_set_default_action(ft, PFRING_FT_ACTION_DISCARD);
+  pfring_ft_set_filter_protocol_by_name(ft, "Skype", PFRING_FT_ACTION_FORWARD);
+
   pfring_ft_set_flow_export_callback(ft, processFlow, NULL);
 
   if (categories_file) {`
