### ISSUE TITLE
100% packet drop on pfcount i40e

### ISSUE THREAD

**Issue by BilldePing** [ntop/PF_RING#466]
Using PF_RING 7.4.0-stable, I am encountering 100% packet drop using pfcount.

i40e load_driver insmods :
insmod ../../../../../kernel/pf_ring.ko min_num_slots=65534 enable_tx_capture=0 enable_ip_defrag=1
insmod ./i40e.ko num_rx_slots=65536 num_tx_slots=0

cat /proc/net/pf_ring/stats/20567-eth1.82 :
Duration: 0:00:00:43:020
Packets: 0
Dropped: 20222147
Bytes: 0

Any idea what could be the issue here ?
There are no flow director rules of any sort that should drop packets

Thanks

**Comment by cardigliano** [comment]
I guess you are capturing from the first queue only, please try setting RSS to 1:
 ethtool -L ethX combined 1

**Comment by BilldePing** [comment]
> I guess you are capturing from the first queue only, please try setting RSS to 1:
> ethtool -L ethX combined 1

Setting RSS=1 does not solve this issue.
Output of the command :
combined unmodified, ignoring.
no channel parameters changed.
current values: rx 0 tx 0 other 1 combined 1

**Comment by cardigliano** [comment]
Please provide the output of:
- cat /proc/net/pf_ring/dev/ethX/info
- pfcount -i zc:ethX (a few lines from the output)

**Comment by BilldePing** [comment]
cat /proc/net/pf_ring/dev/eth1/info
`Name: eth1
Index: 12
Address: XX:XX:XX:XX:XX:XX
Polling Mode: NAPI/ZC
Type: Ethernet
Family: Intel i40e
TX Queues: 1
RX Queues: 1
Num RX Slots: 512
Num TX Slots: 512`

pfcount -i zc:eth1
Using PF_RING v.7.4.0
Capturing from zc:eth1 [mac: XX:XX:XX:XX:XX:XX][if_index: 12][speed: 10000Mb/s]
#Device RX channels: 1
#Polling threads: 1
Dumping statistics on /proc/net/pf_ring/stats/29137-eth1.89
#=========================
Absolute Stats: [431'823 pkts total][431'823 pkts dropped][100.0% dropped]
[0 pkts rcvd][0 bytes rcvd]

**Comment by cardigliano** [comment]
@BilldePing this is actually strange, any chance you can provide access to this box for debugging this issue? Thank you.

**Comment by BilldePing** [comment]
I am afraid its an internal network.
This configuration is on a VM with a passthrough i40e NIC.
Anything else I can provide you with ?

**Comment by cardigliano** [comment]
Could you double check with ifconfig that the interface is in promiscuous mode while capturing?

**Comment by BilldePing** [comment]
I have now changed it to promiscuous mode (ifconfig eth1 promisc) but to no avail - pfcount still has 100% drop

**Comment by BilldePing** [comment]
also, I am not sure if it helps, but after rmmod i40e driver and modprobe i40e (default os driver), performing pfcount -i eth1 shows no packets at all

**Comment by cardigliano** [comment]
@BilldePing what OS / kernel version are you running here?

**Comment by BilldePing** [comment]
Ubuntu 18.04.1 LTS, kernel 4.15.0-43-generic

**Comment by BilldePing** [comment]
### [_****_](url)

**Comment by BilldePing** [comment]
Hi @cardigliano ,
Any idea on what can be done to solve this issue ?
Thank you very much

**Comment by cardigliano** [comment]
@BilldePing I need to reproduce it in order to figure out what's going on, I will try in our lab with the same setup (actually this is similar to one of the configurations we tested)

**Comment by BilldePing** [comment]
Hi @cardigliano , anything I can assist for the meantime ?
Thank you

**Comment by cardigliano** [comment]
@BilldePing sorry this is taking some time as the driver is working for me using a standard server configuration, I need to setup the exact same configuration to see if I am able to reproduce it. If you are also able to provide a pcap with your traffic, that would be even better as it could depend on traffic type. Thank you.

**Comment by BilldePing** [comment]
Hi @cardigliano ,
It turns out that this issue is related to ESX.
Rebooting the ESX solved the issue.
thank you
