### ISSUE TITLE
Fedora 29, Kernel version 5.0.3 Build From Source Error

### ISSUE THREAD

**Issue by routespf** [ntop/PF_RING#467]
Attempting to build pf_ring kernel driver from source on Fedora 29 running 5.0.3 kernel. I receive the following error message. Any help would be appreciated. Is this kernel version not supported yet?

`make -C /lib/modules/5.0.3-200.fc29.x86_64/build SUBDIRS=/root/PF_RING/kernel EXTRA_CFLAGS='-I/root/PF_RING/kernel -DGIT_REV="\"dev:a4c78335b2d3a95ce55264af1cd3126426f8ee87\"" -no-pie -fno-pie' modules
make[1]: Entering directory '/usr/src/kernels/5.0.3-200.fc29.x86_64'
Makefile:189: ================= WARNING ================
Makefile:190: 'SUBDIRS' will be removed after Linux 5.3
Makefile:191: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:192: ==========================================
  CC [M]  /root/PF_RING/kernel/pf_ring.o
/root/PF_RING/kernel/pf_ring.c: In function ‘set_netdev_promisc’:
/root/PF_RING/kernel/pf_ring.c:4946:5: error: too few arguments to function ‘dev_change_flags’
     dev_change_flags(netdev, if_flags);
     ^~~~~~~~~~~~~~~~
In file included from ./include/linux/rtnetlink.h:7,
                 from /root/PF_RING/kernel/pf_ring.c:84:
./include/linux/netdevice.h:3631:5: note: declared here
 int dev_change_flags(struct net_device *dev, unsigned int flags,
     ^~~~~~~~~~~~~~~~
/root/PF_RING/kernel/pf_ring.c: In function ‘unset_netdev_promisc’:
/root/PF_RING/kernel/pf_ring.c:4964:5: error: too few arguments to function ‘dev_change_flags’
     dev_change_flags(netdev, if_flags);
     ^~~~~~~~~~~~~~~~
In file included from ./include/linux/rtnetlink.h:7,
                 from /root/PF_RING/kernel/pf_ring.c:84:
./include/linux/netdevice.h:3631:5: note: declared here
 int dev_change_flags(struct net_device *dev, unsigned int flags,
     ^~~~~~~~~~~~~~~~
/root/PF_RING/kernel/pf_ring.c: In function ‘ring_notifier’:
/root/PF_RING/kernel/pf_ring.c:8102:7: error: duplicate case value
       case NETDEV_PRE_UP:           what = "NETDEV_PRE_UP"; break;
       ^~~~
/root/PF_RING/kernel/pf_ring.c:8101:7: note: previously used here
       case NETDEV_BONDING_FAILOVER: what = "NETDEV_BONDING_FAILOVER"; break;
       ^~~~
make[2]: *** [scripts/Makefile.build:283: /root/PF_RING/kernel/pf_ring.o] Error 1
make[1]: *** [Makefile:1557: _module_/root/PF_RING/kernel] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.0.3-200.fc29.x86_64'
make: *** [Makefile:64: all] Error 2`

**Comment by cardigliano** [comment]
@routespf we will add support for kernel 5.x asap.

**Comment by routespf** [comment]
@cardigliano Thanks for the heads up. I am willing to test any patches/commits for this the moment they are available.

**Comment by cardigliano** [comment]
@routespf I pushed compilation fixes for kernel 5.x, please check it out
