### ISSUE TITLE
Zcount dropping packets using multiple queues 

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#469]
[zcount_ens3_0.log](https://github.com/ntop/PF_RING/files/3057016/zcount_ens3_0.log)
[zcount_ens3_1.log](https://github.com/ntop/PF_RING/files/3057017/zcount_ens3_1.log)
[zsend_ens2_0.log](https://github.com/ntop/PF_RING/files/3057018/zsend_ens2_0.log)
[zsend_ens2_1.log](https://github.com/ntop/PF_RING/files/3057019/zsend_ens2_1.log)

pfring branch: 7.4.0-stable
Operating system: CentOS Linux release 7.4.1708 (Core)
Kernel: 3.10.0-693.5.2.el7.x86_64
 
I am testing 40 Gbps performance using pfring. The attached lstopo output shows my test server has 2 CPUs with 14 cores each as well as 4 Intel XL710 NICs with 2 each installed in NUMA node 0 (ens2 and ens3) and NUMA node 1 (ens5 and ens6). I have ens2 and ens3 connected using a loopback cable, and I am sending packets from ens2 using zsend and receiving on ens3 using zcount. I noticed that when I start using multiple RSS queues, zcount starts reporting dropped packets on queue 0. The other queues report 0 dropped packets.
 
I have attached the various test descriptions, commands used run the tests, and the zcount and zsend output. Here’s a summary of the test results:
 
I ran the drivers/intel/i40e/i40e-2.4.6-zc/src/load_driver.sh script to load the pf_ring and i40e kernel modules. I set the CPU affinity for zsend to 1 and zcount to 8. I was able to send and receive 14.5 Gbps using a single queue without any drops.

I changed the number of queues from 1 to 2 in load_driver.sh and reran the script. I started 2 instances of zcount on cores 8 and 9. I started 1 instance of zsend on core 1, waited 30 seconds, and started another instance of zsend on core 2. The output of zcount for queue 0 shows no drops for the first 30 seconds, then about 2.2 million packet drops per stats interval (5% of total packets generated by both zsend instances) once the second zsend instance starts.

I noticed that the load_driver.sh warned that the number of hugepages available was half the number requested. This was because my server has 2 NUMA nodes so I doubled HUGEPAGES_NUM from 1024 to 2048, reran the load_driver.sh script, and ran the previous test again with 2 queues. The behavior was the same where zcount for queue 0 reports packet drops once the second zsend starts.

I thought maybe zcount could not handle the amount of packets generated by zsend so I increased the number of queues to 8. I started 8 instances of zcount on cores 5-12 and 2 instances of zsend on cores 1 and 2 with a 30 second gap between starting. In the first 30 seconds, zcount for queue 0 reports 3 intervals where several thousand packets are dropped. Once the second zsend instance starts, 2 million packets are dropped every interval.

After doing some research online, there was a suggestion to use the -a option with zcount. I reran test 3 using the -a option and saw no difference in behavior.

I reran test 4 with the zcount -a option and saw no difference.

**Comment by cardigliano** [comment]
Hi @szarea, please note that all drops are accounted to queue 0, even if they actually come also from queue 1, as there is a single counter in the adapter. From your tests it is clear that there is some hw bottleneck (memory bandwidth? pcie slot?) that prevents you from capturing more than ~40Mpps, as you get the same number of drops regardless of the number of queues.
