### ISSUE TITLE
Demo time elapsed. How to track available time left?

### ISSUE THREAD

**Issue by MykolaLiu** [ntop/PF_RING#470]
Upon PF RINF FT demo period is expired, user receive  SIGTERM and following message
#########################################################################
 Demo time elapsed: please get a valid license
#########################################################################

Question is how to maintain available time, and how to prevent receiving SIGTERM.

@cardigliano @lucaderi  please check.

**Comment by cardigliano** [comment]
@MykolaLiu please note that there is an API call (pfring_ft_license) that can be used to check license validity and expiration. As of sigterm, this is part of our license component, and it is triggered in demo mode only.
http://www.ntop.org/guides/pf_ring/api/pfring_ft.html#_CPPv317pfring_ft_licensePcP6time_tP6time_t

**Comment by vitalivanov** [comment]
@cardigliano 
so, does it mean that in case no license is installed and we are in demo mode then pfring_ft_license will return time till trial time (~5mins) is expired?

what we want to have is to show trial period time to user and be able to send traffic and see filtering happening...
but once it expires we have a notification to user and filtering is not happening. we do not want to have signals that may cause application exit...

**Comment by cardigliano** [comment]
> so, does it mean that in case no license is installed and we are in demo mode then pfring_ft_license will return time till trial time (~5mins) is expired?

Correct

> but once it expires we have a notification to user and filtering is not happening. we do not want to have signals that may cause application exit...

We need to discuss this internally as this requires a change in licensing component

**Comment by MykolaLiu** [comment]
@cardigliano 
> > so, does it mean that in case no license is installed and we are in demo mode then pfring_ft_license will return time till trial time (~5mins) is expired?
> 
> Correct

In case of license absences, pfring_ft_license returns expiration and maintenance date to 0. 
Tested on the latest version of PF RING FT(95dedf7a68790f0aa2cfb7ad91479840fc65a898).

**Comment by cardigliano** [comment]
@MykolaLiu I pushed a library update to the dev branch, please check it
