### ISSUE TITLE
upgrades failing on stable ubuntu 18.04 packages. 

### ISSUE THREAD

**Issue by sciencetaco** [ntop/PF_RING#471]
After an apt-get update/upgrade, i get dependency breaks:

pfring-dkms depends on pfring (= 7.4.0-2490); however:
  Version of pfring on system is 7.4.0-2491.

 n2disk depends on pfring-dkms (= 7.4.0); however:
  Package pfring-dkms is not configured yet.

**Comment by cardigliano** [comment]
Uhm strange that you have 7.4.0-2491 installed, latest on repo is 7.4.0-2491,
I am pushing a repo refresh right now, please try again in 1h. Thank you.

**Comment by sciencetaco** [comment]
Repo refresh did the trick, thank you.
