### ISSUE TITLE
Custom licensing for library

### ISSUE THREAD

**Issue by pavel-odintsov** [ntop/PF_RING#473]
Hello!

I have question regarding toolkit license. I understand that PF_RING kernel module licensed under GPLv2 terms and library licensed under LGPLv2 terms.

But some parts of library are not very flexible and require changes in source code. I'm interested in this particular one https://github.com/ntop/PF_RING/blob/dev/userland/lib/pfring_utils.c 

Do you have any options to license this particular file with more permissive license to allow using slightly custom version of functions in this code in commercial software?

Thank you!

**Comment by cardigliano** [comment]
@pavel-odintsov is it some extension that you can push mainline, or you need to keep it "private" in your commercial software?

**Comment by pavel-odintsov** [comment]
Thank you for response! I just dropped email to you with our patches.

**Comment by cardigliano** [comment]
Discussed via mail, closing.
