### ISSUE TITLE
Kernel Module Installation failed

### ISSUE THREAD

**Issue by smtpsrvs** [ntop/PF_RING#474]
Hi,
Using Ubuntu 18.04 TLS
http://www.ntop.org/guides/pf_ring/get_started/git_installation.html
get this when I make

root@h04s23:~# cd PF_RING/kernel
root@h04s23:~/PF_RING/kernel# make
make -C /lib/modules/4.15.0-23-generic/build SUBDIRS=/root/PF_RING/kernel EXTRA_                                                             CFLAGS='-I/root/PF_RING/kernel -DGIT_REV="\"dev:17aa6aa4658576b9ae3e4dc2463a27ff                                                             9cdcd890\"" -no-pie -fno-pie' modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-23-generic'
  CC [M]  /root/PF_RING/kernel/pf_ring.o
In file included from ./include/linux/list.h:5:0,
                 from ./include/linux/module.h:9,
                 from /root/PF_RING/kernel/pf_ring.c:79:
./include/linux/types.h:17:9: error: unknown type name '__kernel_ino_t'
 typedef __kernel_ino_t  ino_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:18:9: error: unknown type name '__kernel_mode_t'
 typedef __kernel_mode_t  mode_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:21:9: error: unknown type name '__kernel_off_t'
 typedef __kernel_off_t  off_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:22:9: error: unknown type name '__kernel_pid_t'
 typedef __kernel_pid_t  pid_t;
         ^~~~~~~~~~~~~~
./include/linux/types.h:23:9: error: unknown type name '__kernel_daddr_t'
 typedef __kernel_daddr_t daddr_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:25:9: error: unknown type name '__kernel_suseconds_t'
 typedef __kernel_suseconds_t suseconds_t;
         ^~~~~~~~~~~~~~~~~~~~
./include/linux/types.h:26:9: error: unknown type name '__kernel_timer_t'
 typedef __kernel_timer_t timer_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:27:9: error: unknown type name '__kernel_clockid_t'
 typedef __kernel_clockid_t clockid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:32:9: error: unknown type name '__kernel_uid32_t'
 typedef __kernel_uid32_t uid_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:33:9: error: unknown type name '__kernel_gid32_t'
 typedef __kernel_gid32_t gid_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:34:9: error: unknown type name '__kernel_uid16_t'
 typedef __kernel_uid16_t        uid16_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:35:9: error: unknown type name '__kernel_gid16_t'
 typedef __kernel_gid16_t        gid16_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:41:9: error: unknown type name '__kernel_old_uid_t'
 typedef __kernel_old_uid_t old_uid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:42:9: error: unknown type name '__kernel_old_gid_t'
 typedef __kernel_old_gid_t old_gid_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:46:9: error: unknown type name '__kernel_loff_t'
 typedef __kernel_loff_t  loff_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:55:9: error: unknown type name '__kernel_size_t'
 typedef __kernel_size_t  size_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:60:9: error: unknown type name '__kernel_ssize_t'
 typedef __kernel_ssize_t ssize_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:65:9: error: unknown type name '__kernel_ptrdiff_t'
 typedef __kernel_ptrdiff_t ptrdiff_t;
         ^~~~~~~~~~~~~~~~~~
./include/linux/types.h:70:9: error: unknown type name '__kernel_time_t'
 typedef __kernel_time_t  time_t;
         ^~~~~~~~~~~~~~~
./include/linux/types.h:75:9: error: unknown type name '__kernel_clock_t'
 typedef __kernel_clock_t clock_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:80:9: error: unknown type name '__kernel_caddr_t'
 typedef __kernel_caddr_t caddr_t;
         ^~~~~~~~~~~~~~~~
./include/linux/types.h:199:2: error: unknown type name '__kernel_daddr_t'
  __kernel_daddr_t f_tfree;
  ^~~~~~~~~~~~~~~~
./include/linux/types.h:200:2: error: unknown type name '__kernel_ino_t'
  __kernel_ino_t  f_tinode;
  ^~~~~~~~~~~~~~
In file included from ./include/linux/list.h:9:0,
                 from ./include/linux/module.h:9,
                 from /root/PF_RING/kernel/pf_ring.c:79:
./include/linux/kernel.h:6:10: fatal error: stdarg.h: No such file or directory
 #include <stdarg.h>
          ^~~~~~~~~~
compilation terminated.
scripts/Makefile.build:339: recipe for target '/root/PF_RING/kernel/pf_ring.o' f                                                             ailed
make[2]: *** [/root/PF_RING/kernel/pf_ring.o] Error 1
Makefile:1552: recipe for target '_module_/root/PF_RING/kernel' failed
make[1]: *** [_module_/root/PF_RING/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-23-generic'
Makefile:64: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cardigliano** [comment]
@smtpsrvs I just compiled PF_RING on Ubuntu 18.04.2 LTS with latest kernel 4.15.0-47 and it is working smoothly. It seems there is some issue with the header files, did you install linux-headers-$(uname -r) ?

**Comment by smtpsrvs** [comment]
The drivers are installed, zmap under ipv6 is compiled, normal too. The ipv6 version supports PF_RING, but does not support the most efficient ZC mode.

**Comment by smtpsrvs** [comment]
> cmake -DWITH_PFRING=ON
> make

Building C object src/CMakeFiles/ztests.dir/recv.c.o
/root/zmap/src/recv.c: In function 'handle_packet':
/root/zmap/src/recv.c:95:3: warning: 'ipv6_hdr' may be used uninitialized in this function [-Wmaybe-uninitialized]
   fs_add_ipv6_fields(fs, ipv6_hdr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 20%] Building C object src/CMakeFiles/ztests.dir/send.c.o
In file included from /usr/local/include/pfring_zc.h:19:0,
                 from /root/zmap/src/socket.h:18,
                 from /root/zmap/src/send.h:13,
                 from /root/zmap/src/send.c:9:
/root/zmap/src/send.c:69:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before '.' token
 static struct in6_addr ipv6_src;
                        ^
/root/zmap/src/send.c: In function 'send_init':
/root/zmap/src/send.c:94:65: error: 'ip_src' undeclared (first use in this function); did you mean 'ipv4_src'?
   int ret = inet_pton(AF_INET6, (char *) zconf.ipv6_source_ip, &ipv6_src);
                                                                 ^
/root/zmap/src/send.c:94:65: note: each undeclared identifier is reported only once for each function it appears in
/root/zmap/src/send.c: In function 'send_run':
/root/zmap/src/send.c:292:2: warning: ISO C forbids nested functions [-Wpedantic]
  struct in6_addr ipv6_dst;
  ^~~~~~
In file included from /usr/local/include/pfring_zc.h:19:0,
                 from /root/zmap/src/socket.h:18,
                 from /root/zmap/src/send.h:13,
                 from /root/zmap/src/send.c:9:
/root/zmap/src/send.c:292:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '.' token
  struct in6_addr ipv6_dst;
                  ^
/root/zmap/src/send.c:292:18: error: expected expression before '.' token
/root/zmap/src/send.c:295:30: error: 'ip_dst' undeclared (first use in this function); did you mean 'ip6_dest'?
   ipv6_target_file_get_ipv6(&ipv6_dst);
                              ^
/root/zmap/src/send.c:386:43: error: 'ip_src' undeclared (first use in this function); did you mean 'ipv4_src'?
     ((struct in6_addr *) probe_data)[0] = ipv6_src;
                                           ^
src/CMakeFiles/ztests.dir/build.make:314: recipe for target 'src/CMakeFiles/ztests.dir/send.c.o' failed
make[2]: *** [src/CMakeFiles/ztests.dir/send.c.o] Error 1
CMakeFiles/Makefile2:151: recipe for target 'src/CMakeFiles/ztests.dir/all' failed
make[1]: *** [src/CMakeFiles/ztests.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cardigliano** [comment]
@smtpsrvs please report this to zmap as that's not our product..

**Comment by smtpsrvs** [comment]
ok tnx
