### ISSUE TITLE
pfring_zc_send_pkt multi thread

### ISSUE THREAD

**Issue by mryamac** [ntop/PF_RING#477]
Hello,
I am trying to write network balancer. So I created a balancer with multi threads. Balancer works fine and packets are distributed well between threads. I have just one interface to forward packets so all of these threads use the same pfring_queue as an output. Each thread calls pfring_zc_send_pkt function with the same queue. 
Here is the question, pfring_zc_send_pkt function is the thread safe? or not.

**Comment by cardigliano** [comment]
@mryamac all queues/devices are single-producer, thus you cannot pfring_zc_send_pkt on the same queue from multiple threads. If you need to send to the same interface, you should use RSS to open multiple queues.

**Comment by mryamac** [comment]
Hello again,
I m sorry for disturbing you, I couldn't understand from the documentation.
I have some problem with multiqueue. I changed RS values to RS=0,0,0,0,0,0 ...
Then I opened devices for each thread to get multiqueue for TX.
For example 
`pfring_zc_queue *thread0Queue=pfring_zc_open_device(cluster, "zc:ens2f0@0", tx_only, PF_RING_ZC_DEVICE_ASYMMETRIC_RSS )`
`pfring_zc_queue *thread1Queue=pfring_zc_open_device(cluster, "zc:ens2f0@1", tx_only, PF_RING_ZC_DEVICE_ASYMMETRIC_RSS )`
Then I got error for thread1Queue. It is a null pointer. What is wrong with this.

**Comment by cardigliano** [comment]
Please use RSS instead of RS

**Comment by mryamac** [comment]
That was RSS, I found my error. After calling insmod, I was calling load_driver.sh. That was the my mistake. Thanks all.
