### ISSUE TITLE
pfring-drivers-zc-dkms Fails Under Ubuntu 19.04

### ISSUE THREAD

**Issue by Kolano** [ntop/PF_RING#478]
Each of the pfring-drivers-zc-dkms sub-packages fails in various ways under Ubuntu 19.04 (I understand only LTS releases are officially supported)...

[e1000e-zc-dkms.0.crash.log](https://github.com/ntop/PF_RING/files/3155527/e1000e-zc-dkms.0.crash.log)
[i40e-zc-dkms.0.crash.log](https://github.com/ntop/PF_RING/files/3155528/i40e-zc-dkms.0.crash.log)
[igb-zc-dkms.0.crash.log](https://github.com/ntop/PF_RING/files/3155529/igb-zc-dkms.0.crash.log)
[ixgbe-zc-dkms.0.crash.log](https://github.com/ntop/PF_RING/files/3155530/ixgbe-zc-dkms.0.crash.log)

Most seem related to changes in ethtool. Similar issues also occur when installing from source.

**Comment by cardigliano** [comment]
@Kolano thank you for reporting, we officially support LTS only, we will check this asap.

**Comment by cardigliano** [comment]
@Kolano a new dev package pfring-drivers-zc-dkms with compilation fixes for kernel 5.x is out, however they've not been tested on Ubuntu 19 specifically, thus I would not exclude that there is still some issue with that Ubuntu version.

**Comment by Kolano** [comment]
Great to hear, I should hopefully be able to test this out next week.

**Comment by cardigliano** [comment]
@Kolano did you have a chance to check the drivers? Thank you.
