### ISSUE TITLE
pf_ring zc licence is invalid

### ISSUE THREAD

**Issue by tileker** [ntop/PF_RING#480]
Hello!
yesterday I have purchased a pf_ring zc licence for an ethernet port for testing how it works. I ran the instructions and applied the licence. it worked without any issue/ but after I had restarted the server and started ntopng it gave error: pfring_open error [No such device]
then I had followed the install instructions one more time and when I started ntopng it began to give error: 
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.5.0.190404
# license for ens1f0 (MAC 90:1B:0E:D2:60:9B) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and
# transmission limited to 5 minutes
#########################################################################
ntopng version: 3.7.190426 - Community Edition
built on CentOS Linux release 7.6.1810 (Core)
nDPI 2.5.0-1364-71b2c19

**Comment by cardigliano** [comment]
@tileker please drop an email to cardigliano at ntop org with your email/orderid and the content of /etc/pf_ring/. Thank you.

**Comment by tileker** [comment]
tileker@gmail.com
Order id xxxxxxxxxx


Sent from Mail for Windows 10

**Comment by cardigliano** [comment]
@tileker your license has been generated for 90:1B:0E:D2:60:9C, while you are using 90:1B:0E:D2:60:9B
