### ISSUE TITLE
Capture 1536 bytes?

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#483]
Hi, i use pf_ring to capture packet of iperf flow. 
The packet length is in the range of 1500 ~ 65536 Bytes. However, I can only capture 1536 bytes of each packet regardless of it's length. 

Is this the case? can we caputre and store the full packet?

I know that the maximum length of ethernet packet is 1518 bytes. How this value 1536 comes?
Thanks so much.

**Comment by cardigliano** [comment]
@FOSquare please note that the second parameter of pfring_open() is the max capture length, which is set by default in many applications (e.g. pfcount) to 1536 (to handle an MTU of 1500 + ethernet + vlan + qinq, and it's rounded up). This can be changed.

**Comment by FOSquare** [comment]
Thanks a lot.
