### ISSUE TITLE
DKMS building pf_ring with wrong kernel version upon kernel upgrade

### ISSUE THREAD

**Issue by Ortpor** [ntop/PF_RING#487]
Hi,

I am testing automatic rebuild of the PF_RING kernel module upon a kernel update with dkms and came upon the following problem:
After installing the new kernel with "apt install linux-generic linux-headers-generic linux-image-generic", the pf_ring module is build with the wrong kernel version (as in the current build version instead of the new kernel version).

After rebooting, the module is not loading and we can see that the vermagic parameter in modinfo give the wrong build number:
```
# modinfo pf_ring
filename:       /lib/modules/**4.15.0-52-generic**/updates/dkms/pf_ring.ko
alias:          net-pf-27
version:        7.2.0
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
srcversion:     D33469BAFC1075DF66DA343
depends:        
retpoline:      Y
name:           pf_ring
vermagic:       **4.15.0-39-generic** SMP mod_unload 
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)
parm:           force_ring_lock:Set to 1 to force ring locking (automatically enable with rss) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog, 2 for more verbosity (uint)
parm:           transparent_mode:(deprecated) (uint)
```
Tested on both Ubuntu 16.04 LTS and 18.04 LTS.

After digging a little I found that to use the right kernel version during a kernel upgrade I have to edit the dkms.conf file under "kernel" before installing the module and replace the line:
`MAKE[0]="make"`
with the following:
`MAKE[0]="make BUILD_KERNEL=${kernelver}"`

After this modification, the module is built with the new kernel as expected instead of the current one.

While the tests have been done with the 7.2.0 stable version, I have not seen any difference with the current version showing that the problem doesn't still exist.

Thanks

**Comment by cardigliano** [comment]
@Ortpor, the kernel module was supposed to be built for the new active kernel on reboot, it is strange it does not work for you. I will push this patch on the dev branch and test it. Thank you.

**Comment by cardigliano** [comment]
@Ortpor could you confirm that latest dev packages are working for you? Thank you.
