### ISSUE TITLE
MAX pps without ZC (Ixgbe)

### ISSUE THREAD

**Issue by missyoyo** [ntop/PF_RING#488]
Hello:
I have two test with intel X520 NIC:
1.pfsend -i zc:ens192 -l 64  -r 10 
   I get 10Mpps as expected.
   TX rate: [current 10'267'572.58 pps/7.23 Gbps][average 8'207'192.12 pps/5.78 Gbps][total 19'604'725.00 pkts]
2.pfsend -i ens192 -l 64  -r 10
  When without zc support, I only get only 0.4Mpps, is this pps very low?
  TX rate: [current 448'553.26 pps/0.32 Gbps][average 429'997.07 pps/0.30 Gbps][total 2'580'108.00 pkts
3. pfsend -i ens32 -l 64  -r 1
    ens32 is e1000 virtual interface run vmware.can get 0.28Mpps.
    TX rate: [current 288'777.18 pps/0.20 Gbps][average 271'099.31 pps/0.19 Gbps][total 5'545'233.00 pkts]
Q1:
I just wonder is 0.5Mpps is the max pps with ixgbe(with out ZC)?
Q2:
I have check document said "transparent_mode=2",does mode 2 need ZC support?
I have try "modprobe pf_ring transparent_mode=2 min_num_slots=65534"
but can not see different below:
cat /proc/net/pf_ring/info
PF_RING Version          : 7.5.0 (dev:08d3f9d75d1e1f1a832adcc6c0d31142a46a031b)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

Thank you for your help.

**Comment by cardigliano** [comment]
@missyoyo the TX performance with standard drivers depends on a few factors including the adapter model and the hw specs (cpu, etc.). Please note that settings like transparent_mode do not affect the TX performance as they are RX optimizations.
