### ISSUE TITLE
libnet pf_ring support?

### ISSUE THREAD

**Issue by missyoyo** [ntop/PF_RING#489]
Hello:
    I have my some app nedd pf_ring to improve performance, these app base on libpcap and libnet. I have check "PF_RING-aware Libpcap".
 Does libnet need "PF_RING-aware" and how can I get it?

**Comment by cardigliano** [comment]
@missyoyo afaik libnet does not capture traffic directly, you use it in combination with libpcap, thus you should be fine. Anyway, we do not have a pf_ring-aware libnet.
