### ISSUE TITLE
Add sending pcap file option to zsend

### ISSUE THREAD

**Issue by mpolonio** [ntop/PF_RING#49]
It would be great if zsend, like pfsend, could be configured to send a pcap file. I would prefer this file to be sent recursively or at least, be able to configure how many times it could be sent (with the possibility to be infinitely sent).

Thanks and best regards

PS: Sorry, I don't know how to tag/label this issue as an Enhancement or Feature Request or something similar

**Comment by mpolonio** [comment]
Does anybody find this feature interesting?

**Comment by cardigliano** [comment]
This will be added as soon as possible, since it is possible to use pfsend for the same task this is not high priority.

**Comment by rezaeimh7** [comment]
@cardigliano  pfsent sends all the packets in a pcap file at user defined rate. when all the packets sent, pfsend stops working. 
is it possible to set an option for pfsend to send all packets of a pcap file recursively?

**Comment by cardigliano** [comment]
@mr-mohsen did you try with "-n 0" ?

**Comment by rezaeimh7** [comment]
@cardigliano  got it. thanks
