### ISSUE TITLE
libpcap fails to open ZC RSS queues beyond the first 10

### ISSUE THREAD

**Issue by jasoncontrib** [ntop/PF_RING#492]
The PF_RING `libpcap` fails to open ZC RSS queues beyond the first 10 (queues 0-9). This only happens with applications that rely on the PF_RING libpcap implementation, such as `tcpdump`, whereas `pfcount` works fine on any of the RSS queues (in my system I have 36 RSS queues on an Intel XL710 adapter).

For example:

`PF_RING/userland/tcpdump/tcpdump -i zc:enp216s0f1@9` works fine and shows packets from queue 9 of 36 as expected.
`PF_RING/userland/tcpdump/tcpdump -i zc:enp216s0f1@10` fails with:
`tcpdump: zc:enp216s0f1@10: No such device exists (No such device exists)`

**Comment by cardigliano** [comment]
62b5007cb9b3ed174689b09b71133adbb6b6032b should fix this.

**Comment by jasoncontrib** [comment]
It indeed fixed it, thanks!
