### ISSUE TITLE
insmod i40e driver fails

### ISSUE THREAD

**Issue by BilldePing** [ntop/PF_RING#493]
nic is not visible in ip l and ifconfig -a.
./load_driver.sh fails with the following log (dmesg) :
load_driver.sh (123): drop_caches: 3
i40e: Intel(R) 40-10 Gigabit Ethernet Connection Network Driver - version 2.4.6
i40e: Copyright(c) 2013-2018 Intel Corporation.
i40e 03:00.0 Core and Global modules ready 0
i40e 03:00.0 PF reset polling failed to complete.
i40e 03:00:00.0: Intial pf_reset failed: -15
i40e 03:00:00.0: previous errors forcing module to load in debug mode

The environment is an Ubuntu 18.04 bionic, kernel 4.15.0-42
PF_RING version, 7.4.0-stable (I also tried with 7.2.0-stable but got the same result).

Any ideas ?

Thank you

**Comment by cardigliano** [comment]
@BilldePing it seems that a card reset is failing for some reason, is the same adapter working fine with vanilla drivers?

**Comment by BilldePing** [comment]
Hi,
I am afraid that vanilla driver is also not working for this port.
The other port (mapped in passthrough mode) is working with PF_RING driver as well as the vanilla.
Any idea on what can cause this ?
Thank you

**Comment by cardigliano** [comment]
@BilldePing to be honest no idea, it could also be related to a hw failure, but I am not sure

**Comment by cardigliano** [comment]
Closing as this seems not related to zc drivers
