### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ichintu** [ntop/PF_RING#496]
Hello, I am trying to install PF_RING 7.2.0 as well as latest git clone. I am running CentOS 7 on aarch64 (Cavium ThunderX). I am unable to configure the build environment. getting these 2 error messages:

> Error: unknown architecture `native'
> 
> Error: unrecognized option -march=native

Please see the output below from uname -a & uname -m

> [epadmin@node lib]$ uname -a
> Linux node.dev 4.14.0-115.8.1.el7a.aarch64 #1 SMP Wed Jun 5 15:01:21 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
> [epadmin@node lib]$ uname -m
> aarch64

Thank you for your help.

**Comment by cardigliano** [comment]
@ichintu it seems your gcc version does not support -march=native, please update to latest code from github and use ./configure --disable-archopt

**Comment by FOSquare** [comment]
I also find similar problem. After I install the header, and make wil result the follow errors. thanks.

my system is Ubuntu 16.04 with kernel of 4.13.0-36-generic

fyan@tue-server:~/PF_RING/kernel$ make
make -C /lib/modules/4.13.0-36-generic/build SUBDIRS=/home/fyan/PF_RING/kernel EXTRA_CFLAGS='-I/home/fyan/PF_RING/kernel -DGIT_REV="\"6.0.3-stable:9037b4abab21829263128740f4857d78110452d9\""' modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-36-generic'
  CC [M]  /home/fyan/PF_RING/kernel/pf_ring.o
/home/fyan/PF_RING/kernel/pf_ring.c: In function ‘set_skb_time’:
/home/fyan/PF_RING/kernel/pf_ring.c:2844:17: error: request for member ‘tv64’ in something not a structure or union
   if(skb->tstamp.tv64 == 0)
                 ^
/home/fyan/PF_RING/kernel/pf_ring.c: In function ‘buffer_ring_handler’:
/home/fyan/PF_RING/kernel/pf_ring.c:4796:13: error: request for member ‘tv64’ in something not a structure or union
   skb.tstamp.tv64 = 0;
             ^
/home/fyan/PF_RING/kernel/pf_ring.c: In function ‘ring_setsockopt’:
/home/fyan/PF_RING/kernel/pf_ring.c:7547:13: error: implicit declaration of function ‘__sk_attach_filter’ [-Werror=implicit-function-declaration]
       ret = __sk_attach_filter(&fprog, pfr->sk, sock_owned_by_user(pfr->sk));
             ^
/home/fyan/PF_RING/kernel/pf_ring.c:7567:11: error: implicit declaration of function ‘__sk_detach_filter’ [-Werror=implicit-function-declaration]
     ret = __sk_detach_filter(pfr->sk, sock_owned_by_user(pfr->sk));
           ^
cc1: some warnings being treated as errors
scripts/Makefile.build:315: recipe for target '/home/fyan/PF_RING/kernel/pf_ring.o' failed
make[2]: *** [/home/fyan/PF_RING/kernel/pf_ring.o] Error 1
Makefile:1550: recipe for target '_module_/home/fyan/PF_RING/kernel' failed
make[1]: *** [_module_/home/fyan/PF_RING/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-36-generic'
Makefile:38: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cardigliano** [comment]
@FOSquare what pf_ring version are you compiling? This does not seem to be the latest one..

**Comment by shreve** [comment]
For future Googlers:
I had these same issues, plus an additional
```
... /PF_RING/kernel/pf_ring.c:3946:38: error: implicit declaration of function ‘ACCESS_ONCE’; did you mean ‘READ_ONCE’? [-Werror=implicit-function-declaration]
       u_short num_cluster_elements = ACCESS_ONCE(cluster_ptr->cluster.num_cluster_elements);
                                      ^~~~~~~~~~~
                                      READ_ONCE
```
I was on `6.4.0-stable` with `$(uname -r) == 4.15.0-47-generic`. I moved up to `7.2.0-stable` and was able to compile just fine.
