### ISSUE TITLE
report order id is invalid when the license is generated.

### ISSUE THREAD

**Issue by shuaidonga** [ntop/PF_RING#498]
I bought a pfring zc license, but the report order id is invalid when the license is generated.
why?

**Comment by cardigliano** [comment]
@shuaidonga please send me an email (cardigliano at ntop.org) with the details (order id, email, etc)

**Comment by shuaidonga** [comment]
@cardigliano 
I send  to your mail,
![image](https://user-images.githubusercontent.com/16378509/62448826-46f84380-b79b-11e9-9dee-f77db8f2c2a2.png)
