### ISSUE TITLE
zeek with pf_ring zc multiple workers Unbalanced load

### ISSUE THREAD

**Issue by shuaidonga** [ntop/PF_RING#499]
After using zeek of pfring_zc, the amount of data processed by multiple work is too large, resulting in a huge difference in the amount of work cpu, resulting in a large CPU usage.
Here is the zeek configuration
![image](https://user-images.githubusercontent.com/16378509/62601105-34a91180-b923-11e9-87a8-d76e7600e80c.png)

The following is the usage of each cpu of the work node.
![image](https://user-images.githubusercontent.com/16378509/62601207-67530a00-b923-11e9-998c-11a345e81ef3.png)

**Comment by cardigliano** [comment]
What do you mean with "the amount of data processed by multiple work is too large"?

**Comment by shuaidonga** [comment]
Some CPU usage is too high and work is too busy. There are some cpu usages that are too low. Why is the network data load imbalanced?

**Comment by cardigliano** [comment]
Load balancing is based on RSS in this case, which is a hw hash. RSS supports up to 16 queues, other queues get no traffic, this is the reason. Another option is using a software hash with zbalance_ipc.

**Comment by wang-xuefei** [comment]
@shuaidonga How many PPS at flow?
