### ISSUE TITLE
Broken symlink to libpcap in Debian build

### ISSUE THREAD

**Issue by edeca** [ntop/PF_RING#5]
A line in the [Ubuntu Makefile](https://github.com/ntop/PF_RING/blob/dev/package/ubuntu/Makefile.in#L48) contains a hard coded reference to libpcap-1.1.1.

    cd $(PF_RING_HOME)/userland/libpcap; ./configure; make; cp libpcap* $(HERE)/debian/usr/local/lib/; cd $(HERE)/debian/usr/local/lib/; ln -sf libpcap.so.1.1.1 libpcap.so

At least in my build environment (Debian Wheezy) this isn't correct and I end up with a broken symlink:

    drwxr-xr-x root/root         0 2015-05-12 14:55 ./usr/local/lib/
    -rw-r--r-- root/root    607240 2015-05-12 14:55 ./usr/local/lib/libpcap.so.1.6.2
    lrwxrwxrwx root/root         0 2015-05-12 14:55 ./usr/local/lib/libpcap.so -> libpcap.so.1.1.1

**Comment by cardigliano** [comment]
Fixed

**Comment by edeca** [comment]
Fixed in 5381ecf6c64ab59adfee91296b88fd6f2f88f8e1 - thanks!
