### ISSUE TITLE
how can i use bro with pf_ring zc driver

### ISSUE THREAD

**Issue by husterzlc** [ntop/PF_RING#500]
hello!
i have bought a licence for pf_ring zc driver（1 Gbit PF_RING ZC Intel [Linux]）,and my NIC is igb.Now the pf_ring zc is installed successfully.But when i use bro with it,error occured.i just followed (http://www.ntop.org/guides/pf_ring/thirdparty/bro.html  ),but it says that zc:eno1@*(pcap_error:SIOCGIFHWADDR:no such denvice(pcap_activate)).

what can i do?
Now,i have found two problems：
1.How can i load the DNA NIC driver on each worker host?
2.mast i use the zbalance_ipc？ i can't understand the application's function correctly,can you help me?
thank you.

**Comment by cardigliano** [comment]
@husterzlc are you able to run "pfcount -i zc:eno1"? This is to figure out whether the ZC driver is up and running.

**Comment by husterzlc** [comment]
i just tested it using your instruction.YES,it works very well.

**Comment by husterzlc** [comment]
@cardigliano  i just tested it using your instruction.YES,it works very well.

**Comment by cardigliano** [comment]
Did you make sure that Zeek is linking the right library?

ldd /usr/local/bro/bin/bro | grep pcap
        libpcap.so.1 => /usr/local/lib/libpcap.so.1 (0x00007fa371e33000)

**Comment by husterzlc** [comment]
Yes,it shows that libpcap.so.1 => /usr/local/lib/libpcap.so.1 (0x00007efd877fc000)

**Comment by cardigliano** [comment]
Please provide your node.cfg

**Comment by husterzlc** [comment]
in /usr/local/lib,i found libpfring.so.7.1.0 and libpfring.so.7.5.0.I actually installed two versions,but does that affect it?
this is my node.cfg.
[logger]
type=logger
host=localhost

[manager]
type=manager
host=localhost
#
[proxy-1]
type=proxy
host=localhost
#
[worker-1]
type=worker
host=localhost
lb_method=pf_ring
lb_procs=10
pin_cpus=0,1,2,3,4,5,6,7,8,9
interface=zc:enp4s0f1

**Comment by cardigliano** [comment]
Your configuration looks fine. Please cleanup all libraries and install the one from pf_ring

**Comment by husterzlc** [comment]
how can i  cleanup all libraries and uninstall the old version of pfring.it's just how to uninstall pf_ring..please

**Comment by cardigliano** [comment]
It is important to start from a clean environment, thus please remove the pfring package if any, and rm /usr/local/lib/libpfring.* /usr/local/lib/libpcap.*
then reinstall pfring (did you install it from source code?)

**Comment by husterzlc** [comment]
Ok .Now it works.I removed the lib and reinstalled the pf_ring. Thanks a lot.

**Comment by cardigliano** [comment]
Great

**Comment by sohailanjum97** [comment]
Dear Cardigliano, I have sent you an email and looking forward to hearing from you soon.
