### ISSUE TITLE
The real time processing of the packet

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#501]
Hello. I could user pfcount to capture and store the packet. Is there any interface that I can directly own and process the packet?

For example, I want to know whether a new flow is arrive, then I need to store the port and IP of all the previous packts. then comprare the current IP and port arrived packet with the stored value.

Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare I guess you need to store all traffic on disk and at some point go back in time and retrieve traffic matching a specific flow. If that's your use case, you need n2disk for continuous recording..

**Comment by FOSquare** [comment]
thanks for your reply. this is not my case. I know I can store the packet to a pcap file for analysis.  This is off-line processing. i would like to achieve the on-line real time processing. Is there a interface for me to manipulate the packte on time?
For example, tcpflow can distinguish all the flows in the caputred packet. So it must carry out the packet processing when it caputre the packet. 
I do not find a function that can reture the packet point so that I can own the header of the packet. is there a function in pfring that I can invoke? 
All i need is to get the packet header at the same time when I caputure the traffic. i hope I made the story clear.

thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare if you are interested in assisted flow processing, you should probably look at PF_RING FT, please take a look at https://www.ntop.org/guides/pf_ring/ft.html
