### ISSUE TITLE
pfring fail to start

### ISSUE THREAD

**Issue by radyphan** [ntop/PF_RING#502]
Hello,

Anyone have this issue bellow :

root@alien:~# systemctl status pf_ring
â— pf_ring.service - PF_RING service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-08-08 11:18:58 PDT; 1min 9s ago
  Process: 39891 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StopPost" >> /var/log/ntop-systemd.log (code=exited, status
  Process: 38061 ExecStart=/usr/local/bin/pf_ringctl start (code=exited, status=99)
  Process: 38058 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPre" >> /var/log/ntop-systemd.log (code=exited, status
 Main PID: 38061 (code=exited, status=99)

Aug 08 11:18:55 alien pf_ringctl[38061]: Installing new pfring driver
Aug 08 11:18:58 alien pf_ringctl[38061]: ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/pfring-dkms.0.crash'
Aug 08 11:18:58 alien pf_ringctl[38061]: Error! Bad return status for module build on kernel: 5.0.0-23-generic (x86_64)
Aug 08 11:18:58 alien pf_ringctl[38061]: Consult /var/lib/dkms/pfring/7.4.0/build/make.log for more information.
Aug 08 11:18:58 alien pf_ringctl[38061]: modprobe: FATAL: Module pf_ring not found in directory /lib/modules/5.0.0-23-generic
Aug 08 11:18:58 alien pf_ringctl[38061]:  * Unable to load PF_RING. Exiting
Aug 08 11:18:58 alien pf_ringctl[38061]:    ...fail!
Aug 08 11:18:58 alien systemd[1]: pf_ring.service: Main process exited, code=exited, status=99/n/a
Aug 08 11:18:58 alien systemd[1]: pf_ring.service: Failed with result 'exit-code'.
Aug 08 11:18:58 alien systemd[1]: Failed to start PF_RING service.

root@alien:~# more /var/crash/pfring-dkms.0.crash
ProblemType: Package
DKMSBuildLog:
 DKMS make.log for pfring-7.4.0 for kernel 5.0.0-23-generic (x86_64)
 Sat Aug  3 06:09:38 PDT 2019
 make -C /lib/modules/5.0.0-23-generic/build SUBDIRS=/var/lib/dkms/pfring/7.4.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/7.4.0/bui
ld -DGIT_REV="\"7.4.0-stable:c5146860f7ecc00d765af9a7108602bf1b8b5c54\"" -no-pie -fno-pie' modules
 make[1]: Entering directory '/usr/src/linux-headers-5.0.0-23-generic'
 Makefile:223: ================= WARNING ================
 Makefile:224: 'SUBDIRS' will be removed after Linux 5.3
 Makefile:225: Please use 'M=' or 'KBUILD_EXTMOD' instead
 Makefile:226: ==========================================
   CC [M]  /var/lib/dkms/pfring/7.4.0/build/pf_ring.o
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c: In function â€˜set_netdev_promiscâ€™:
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c:4952:5: error: too few arguments to function â€˜dev_change_flagsâ€™
      dev_change_flags(netdev, if_flags);
      ^~~~~~~~~~~~~~~~
 In file included from ./include/linux/rtnetlink.h:7:0,
                  from /var/lib/dkms/pfring/7.4.0/build/pf_ring.c:84:
 ./include/linux/netdevice.h:3634:5: note: declared here
  int dev_change_flags(struct net_device *dev, unsigned int flags,
      ^~~~~~~~~~~~~~~~
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c: In function â€˜unset_netdev_promiscâ€™:
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c:4970:5: error: too few arguments to function â€˜dev_change_flagsâ€™
      dev_change_flags(netdev, if_flags);
      ^~~~~~~~~~~~~~~~
 In file included from ./include/linux/rtnetlink.h:7:0,
                  from /var/lib/dkms/pfring/7.4.0/build/pf_ring.c:84:
 ./include/linux/netdevice.h:3634:5: note: declared here
  int dev_change_flags(struct net_device *dev, unsigned int flags,
      ^~~~~~~~~~~~~~~~
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c: In function â€˜ring_notifierâ€™:
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c:8119:7: error: duplicate case value
        case NETDEV_PRE_UP:           what = "NETDEV_PRE_UP"; break;
        ^~~~
 /var/lib/dkms/pfring/7.4.0/build/pf_ring.c:8118:7: note: previously used here
        case NETDEV_BONDING_FAILOVER: what = "NETDEV_BONDING_FAILOVER"; break;
        ^~~~
 scripts/Makefile.build:291: recipe for target '/var/lib/dkms/pfring/7.4.0/build/pf_ring.o' failed
 make[2]: *** [/var/lib/dkms/pfring/7.4.0/build/pf_ring.o] Error 1
 Makefile:1606: recipe for target '_module_/var/lib/dkms/pfring/7.4.0/build' failed
 make[1]: *** [_module_/var/lib/dkms/pfring/7.4.0/build] Error 2
 make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-23-generic'
 Makefile:64: recipe for target 'all' failed
 make: *** [all] Error 2
DKMSKernelVersion: 5.0.0-23-generic
Date: Sat Aug  3 06:09:43 2019
DuplicateSignature: dkms:pfring-dkms:7.4.0:/var/lib/dkms/pfring/7.4.0/build/pf_ring.c:4952:5: error: too few arguments to function â€˜
dev_change_flagsâ€™
Package: pfring-dkms 7.4.0
PackageVersion: 7.4.0
SourcePackage: pfring-dkms
Title: pfring-dkms 7.4.0: pfring kernel module failed to build
root@alien:~# systemctl restart pf_ring
Job for pf_ring.service failed because the control process exited with error code.
See "systemctl status pf_ring.service" and "journalctl -xe" for details.
root@alien:~# systemctl status pf_ring
â— pf_ring.service - PF_RING service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-08-08 11:18:58 PDT; 1min 9s ago
  Process: 39891 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StopPost" >> /var/log/ntop-systemd.log (code=exited, status
  Process: 38061 ExecStart=/usr/local/bin/pf_ringctl start (code=exited, status=99)
  Process: 38058 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPre" >> /var/log/ntop-systemd.log (code=exited, status
 Main PID: 38061 (code=exited, status=99)

Please help if you have experience with this.

Thanks,
Rady

**Comment by cardigliano** [comment]
Hi @radyphan, what OS/version are you running?

**Comment by radyphan** [comment]
Hi Cadigliano,

I'm using Ubuntu 18.04. and running on Hyper-V (Window 10 Education).
Any clue regarding this issue please let me know.

Thank you,
Rady

**Comment by radyphan** [comment]
Here is more detail:
# uname -a
Linux alien 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# uname -r
5.0.0-23-generic

**Comment by radyphan** [comment]
# ethtool -i eth0 | grep driver
driver: hv_netvsc

**Comment by cardigliano** [comment]
@radyphan it seems you are not running the default kernel, which is what we support with ubuntu lts, anyway I will try to fix the errors you found.

**Comment by radyphan** [comment]
Hi,

Can you help me one more thing seem like my license not working please check in attach file:

![8-12-2019 10-10-27 AM](https://user-images.githubusercontent.com/47866186/62883712-95509980-bce9-11e9-9dc4-5c8e28f65b9b.png)
