### ISSUE TITLE
Some questions about PF_RING

### ISSUE THREAD

**Issue by hirrolot** [ntop/PF_RING#504]
I have several questions about PF_RING:
 1. What is difference between specifying `zc:device` in [`pfring_open`](https://www.ntop.org/guides/pf_ring/api/pfring.html?highlight=pfring_open#_CPPv311pfring_openPKc9u_int32_t9u_int32_t) (`pfring_open("zc:eth0", 1500, 0)`) and using PF_RING ZC API?
 2. What is difference between specifying `stack::device` in [`pfring_open`](https://www.ntop.org/guides/pf_ring/api/pfring.html?highlight=pfring_open#_CPPv311pfring_openPKc9u_int32_t9u_int32_t) instead of `zc:device`? Will the performance be better?
 3. Can [`__pfring`](https://www.ntop.org/guides/pf_ring/api/pfring.html?highlight=pfring#_CPPv36pfring) be accessed from multiple threads or I need a mutex?
 4. Are there any performance guidelines?
 5. What is the difference between PF_RING and standard Linux Packet Sockets?

**Comment by cardigliano** [comment]
> 1. What is difference between specifying `zc:device` in [`pfring_open`](https://www.ntop.org/guides/pf_ring/api/pfring.html?highlight=pfring_open#_CPPv311pfring_openPKc9u_int32_t9u_int32_t) (`pfring_open("zc:eth0", 1500, 0)`) and using PF_RING ZC API?

The PF_RING ZC API provides more flexibility for implementing zero-copy packet processing patterns like load-balancing to threads/processes, pipelining, or buffering. If your application just need to process one packet, and move to the next one, the legacy pfring_open is fine.

> 2. What is difference between specifying `stack::device` in [`pfring_open`](https://www.ntop.org/guides/pf_ring/api/pfring.html?highlight=pfring_open#_CPPv311pfring_openPKc9u_int32_t9u_int32_t) instead of `zc:device`? Will the performance be better?

The "stack:" module is used for injecting traffic to the linux stack (send traffic to, read traffic from), if you want to emulate a device for instance or sit in the middle. If you need to capture traffic coming from the wire on an interface you need "zc:". They are two different things, it's not a matter of performance.

> 3. Can [`__pfring`](https://www.ntop.org/guides/pf_ring/api/pfring.html?highlight=pfring#_CPPv36pfring) be accessed from multiple threads or I need a mutex?

Locking is required when reading from the same socket from multiple threads.

> 4. Are there any performance guidelines?
> 5. What is the difference between PF_RING and standard Linux Packet Sockets?

The performance boost provided by PF_RING depends on the configuration. Let's say that a standard packet socket (e.g. libpcap/AF_PACKET) is fine for processing ~1 Mpps with small packets, ZC is able to process more than 15 Mpps per core.

**Comment by hirrolot** [comment]
Thank you.
