### ISSUE TITLE
ixgbe-zc on Kubuntu 18.04 LTS

### ISSUE THREAD

**Issue by gvanroyen** [ntop/PF_RING#508]
Hello,

Seeing that PF_RING ZC is fully supported on Ubuntu Server LTS I installed the latest LTS desktop version (Kubuntu 18.04 LTS)
Installing PF_RING via precompiled packages is OK but installing ZC drivers is not.

Here is the issue : 

Réception de :1 **http://packages.ntop.org/apt-stable/18.04 all/ ixgbe-zc-dkms 5.3.7.2612 [338 kB]**
338 ko réceptionnés en 0s (1 791 ko/s)  
Sélection du paquet ixgbe-zc-dkms précédemment désélectionné.
(Lecture de la base de données... 244222 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../ixgbe-zc-dkms_5.3.7.2612_all.deb ...
Dépaquetage de ixgbe-zc-dkms (5.3.7.2612) ...
Paramétrage de ixgbe-zc-dkms (5.3.7.2612) ...
Loading new ixgbe-zc-5.3.7.2612 DKMS files...
**Building for 5.0.0-25-generic**
Building for architecture x86_64
Building initial module for 5.0.0-25-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/ixgbe-zc-dkms.0.crash'
**Error! Bad return status for module build on kernel: 5.0.0-25-generic (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.3.7.2612/build/make.log for more information.**

My kernel is :  **5.0.0-25-generic**

attached the make.log : 

[make.log](https://github.com/ntop/PF_RING/files/3559167/make.log)

Thank you for your help,

Guillaume

**Comment by cardigliano** [comment]
@gvanroyen please note that ZC supports latest Ubuntu *Server* LTS, the newest kernel is 4.15, which is what we officially support. However we will do our best to support your kernel too.

**Comment by gvanroyen** [comment]
Thank you for your quick answer, I thought all 18.04 LTS (server or desktop) were base on the same kernel, I'll try downgrading to 4.15 on my setup or i'll just go with 18.04 server. Do you know the exact kernel version supported at this time by ZC (did not find the info on 18.04 server description)

**Comment by gvanroyen** [comment]
Installed kernel 4.15.0-58-generic and headers on Kubuntu 18.04 LTS

Name: enp5s0f1             Driver: ixgbe      [Running ZC]   
Name: enp2s0               Driver: igb        [Supported by ZC]
Name: eno1                 Driver: e1000e     [Supported by ZC]
Name: enp5s0f0             Driver: ixgbe      [Running ZC]   
Name: enp23s0f0            Driver: ixgbe      [Running ZC]   
Name: enp23s0f1            Driver: ixgbe      [Running ZC] 

So far so good! Thanks for the help and thanks for the work you do

**Comment by cardigliano** [comment]
@gvanroyen I actually pushed patches to compile the drivers on kernel 5.x, I am testing them.

**Comment by cardigliano** [comment]
@gvanroyen new packages will be available soon, however please note that I pushed compilation fixes on the dev repo, if you want to use the stable packages you should keep using kernel 4.15

**Comment by gvanroyen** [comment]
Thank you verry mutch, i'll stick to 4.15 for my devs for now, as soon as i get something runing i will try on 5.x and let you know. GG to all all of you!

**Comment by cardigliano** [comment]
Closing as drivers now compile on 5.0.0-25
