### ISSUE TITLE
why kernel space to user space  took such of a long time use in PF_RING 6.1.1?

### ISSUE THREAD

**Issue by jarwin123** [ntop/PF_RING#51]
I add three  lines in  PF_RING/userland/examples/pfcount.c , 
    433a434,437

>   struct timeval t1;
>   gettimeofday(&t1,NULL);
> 
>   printf("%lld\n",(t1.tv_sec \* 1000000000 + t1.tv_usec \* 1000 - h->extended_hdr.timestamp_ns));

[root@localhost examples]# ./pfcount -i em2
Using PF_RING v.6.1.1
Capturing from em2 [44:A8:42:31:3B:28][ifIndex: 3]
# Device RX channels: 1
# Polling threads:    1

Dumping statistics on /proc/net/pf_ring/stats/36299-em2.2520
500340635
500355255
500360237
500366553
499201428
499202098
475305377
458176629
399656541
399653852
399657571
399661611
399064164
399056550
399062153
399065029
398885092
398891961
398896016
398900322
398301733
398299895
398303553
398145113
398147104
398151421
398159677
397150607
397151639
351792754
351794079
351808270
351815341
272232361
252847136
235235064
234910699
222151294
222153391
221939112
221941617
201571278
201570273
201575232
201581217
51274212
51275790
51280720
48558517
22264212
22267572
144075
150007
160231
170486
182779
174478
180512
187831
195027
200132
179247
186034
170355
177255
146370
153270
135375
#140321

Absolute Stats: [69 pkts rcvd][0 pkts dropped]
Total Pkts=69/Dropped=0.0 %
#69 pkts - 13'816 bytes

some pf_ring info :

 [root@localhost examples]# cat /proc/net/pf_ring/info 
PF_RING Version          : 6.1.1 (dev:686efccb01dc7eaab815d555a82d2e79232bd890)
Total rings              : 0

Standard (non DNA/ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

[root@localhost examples]# uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
  # ethtool -i em2

[root@localhost examples]# ethtool -i em2
driver: tg3
version: 3.137
firmware-version: FFV7.10.59 bc 5720-v1.36
bus-info: 0000:01:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

[root@localhost ~]# cat /etc/redhat-release 
Derived from Red Hat Enterprise Linux 7.1 (Source)

[root@localhost ~]# ifconfig em2
em2: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet 192.168.1.205  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::46a8:42ff:fe31:3b28  prefixlen 64  scopeid 0x20<link>
        ether 44:a8:42:31:3b:28  txqueuelen 1000  (Ethernet)
        RX packets 4290658658  bytes 2215627625127 (2.0 TiB)
        RX errors 1  dropped 412  overruns 0  frame 1
        TX packets 808995272  bytes 52018489641 (48.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 38  

[root@localhost ~]# ethtool -a em2
Pause parameters for em2:
Autonegotiate:  off
RX:             off
TX:             off

[root@localhost ~]# ethtool -k em2
Features for em2:
rx-checksumming: on
tx-checksumming: on
        tx-checksum-ipv4: on
        tx-checksum-ip-generic: off [fixed]
        tx-checksum-ipv6: on
        tx-checksum-fcoe-crc: off [fixed]
        tx-checksum-sctp: off [fixed]
scatter-gather: on
        tx-scatter-gather: on
        tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: on
        tx-tcp-segmentation: on
        tx-tcp-ecn-segmentation: on
        tx-tcp6-segmentation: on
udp-fragmentation-offload: off [fixed]
generic-segmentation-offload: on
generic-receive-offload: off
large-receive-offload: off [fixed]
rx-vlan-offload: on [fixed]
tx-vlan-offload: on [fixed]
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on
rx-vlan-filter: off [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-ipip-segmentation: off [fixed]
tx-sit-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-mpls-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: on
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
busy-poll: off [fixed]

**Comment by cardigliano** [comment]
@jarwin123 could you confirm this happens at initialisation only? This seems to be somehow expected because some packets get inserted into the ring at boot time while the capture thread is starting.

**Comment by jarwin123** [comment]
NO,it's always happened! when packets arrival rates increase,the latency decrease accordingly, 
it seems that the latency and packets arrival rates have the reciprocal relationship.
Test condition 1:
   code:
         wait_for_packet = 1;
         if((rc = pfring_recv(pd, &buffer_p, NO_ZC_BUFFER_LEN, &hdr, wait_for_packet));
result:
      if packets arrival rates  is less than 10 pps,the time latency is greater than 100 millseconds,
      if packets arrival rates  is more than 10K pps, the latency is about tens microseconds.
Test condition 2:
  code:
        wait_for_packet = 0;
         if((rc = pfring_recv(pd, &buffer_p, NO_ZC_BUFFER_LEN, &hdr, wait_for_packet));
result:
    the latency is not much changes.(but return value may be 0, and cpu utilization is %99.7);
    the latency is about tens microseconds;

**Comment by cardigliano** [comment]
Did you try with -a? It could be due to poll()

**Comment by jarwin123** [comment]
if use -a opt，but  reurn value may be 0, and cpu utilization is %99.7

**Comment by cardigliano** [comment]
This is expected, I would like to know if you still see latency.

**Comment by jarwin123** [comment]
yes，if try -a opt ，it has not latency！

**Comment by cardigliano** [comment]
Ok, then what you are eperiencing is due to the poll/watermark mechanism for improving throughput, paying in latency. For low-latency sensitive applications you should use active polling (-a).

**Comment by cardigliano** [comment]
Forgot to mention that you can decrease latency in passive polling mode setting a smaller poll timeout with pfring_set_poll_duration

**Comment by jarwin123** [comment]
for realtime application ,which value is used in pfring_set_poll_duration()?

**Comment by cardigliano** [comment]
1

**Comment by jarwin123** [comment]
thank you very much! by the way, 1 is nanosecond? 1 is millsecond?

**Comment by cardigliano** [comment]
poll works with msec

**Comment by jarwin123** [comment]
I test again,if use pfring_set_poll_duration, the latency is about 500 usec, not use it, the latency is about 10 usec

**Comment by jarwin123** [comment]
I modfiy userland/lib/pfring_mod.c  
int pfring_mod_poll(pfring *ring, u_int wait_duration) {
  if(wait_duration == 0)
    return(ring->is_pkt_available(ring));
  else {
     int rc;
    fd_set rfds;
    int max_fd;
    struct timeval tv;
    tv.tv_sec = 0;
    tv.tv_usec = wait_duration;

```
FD_ZERO(&rfds);
FD_SET(ring->fd,&rfds);
max_fd = ring->fd + 1; 
rc = select(max_fd, &rfds, NULL, NULL, &tv);
ring->num_poll_calls++;
return(rc);
```

  }

i test it,the latency is about 50 usec. what problems will cause?

**Comment by cardigliano** [comment]
It should work fine, but you changed the API from msec to usec, I cannot merge this patch.
