### ISSUE TITLE
The license of PF_RING FT?

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#510]
Do I must need a license for using of PF_RING FT? And what's the differences among ftflow.c, ftflow_pcap.c, ftflow_dpdk.c? thanks.

Below is the reminder asking the license....

# ERROR: You do not seem to have a valid PF_RING FT 7.2.0.180613 license [CB7860B5550460F1]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# We're now working in demo mode with packet capture and
# transmission limited to 5 minutes
#########################################################################
Using PF_RING v.7.2.0
Capturing from enp1s0f0 without (see -7) nDPI support

**Comment by FOSquare** [comment]
since PF_RING FT need license? can I have the pointer of the packet so that I can process the packet by myself? Thanks.

**Comment by cardigliano** [comment]
@FOSquare yes FT requires a license. The only difference among ftflow.c, ftflow_pcap.c, ftflow_dpdk.c is the capture library (pf_ring vs libpcap vs dpdk). The capture library is used to capture packets and provide them to the FT library, thus the answer to your latest question is yes, you have a pointer to the packet.

**Comment by FOSquare** [comment]
Can I get the pointer in the pf_ring and use it by myself? Cause I need license for FT, and I do not have one....

**Comment by cardigliano** [comment]
@FOSquare if you do not want to use FT, probably you are looking at the wrong example. Could you provide more info about what you are trying to do? Thank you.
