### ISSUE TITLE
packet points in PF_RING

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#511]
it was related to my last question. Can I get the pointer in the pf_ring and use it by myself? Cause I need license for FT, and I do not have one....

I just want to record the flows in my server, can I do it by myself in pf_ring? 

I have tens of servers to make the experiment, so if I can get the point in pf_ring, I can write several lines of code to achieve the similar function as FT achieved.

Thanks. How do you suggest me to use PF_RING???

**Comment by cardigliano** [comment]
@FOSquare please take a look at the examples in userland/examples (e.g. pfcount.c), those are packet-capture-only examples with no FT integration (you can do flow processing yourself).

**Comment by FOSquare** [comment]
yes, I know. And i check the pfcoutn.c , but I do not find the pointer of the packet. How can I get the packet point in pfcount.c? by which function or interface? Thanks a lot...

**Comment by cardigliano** [comment]
https://github.com/ntop/PF_RING/blob/dev/userland/examples/pcount.c#L254

**Comment by FOSquare** [comment]
Thanks a lot. I will look details in dummyProcesssPacket() function.
