### ISSUE TITLE
Zbalance works in demo mode when use myricom virtual interface

### ISSUE THREAD

**Issue by pak86** [ntop/PF_RING#512]
Hi,
if I try to run zbalance using Myricom virtual interface myri:3, obtain the following message

"We're now working in demo mode with packet capture and
transmission limited to 5 minutes"

**Comment by cardigliano** [comment]
@pak86 I pushed a fix for this to the dev packages (new packages will be available in ~30 min), please let us know if it works for you or report the pfcount output. Thank you.

**Comment by pak86** [comment]
I attach the output of pfcount:

SNF_FLAGS=0x2 pfcount -i myri:3

ERROR: Can't read snf device info for the specified device(s): Success

We're now working in demo mode with packet capture and
transmission limited to 5 minutes

Using PF_RING v.7.5.0
Capturing from myri:3 [mac: 00:00:00:00:00:00][if_index: 3][speed: 0Mb/s]
Device RX channels: 1
Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/5753-none.112

Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd]

**Comment by cardigliano** [comment]
@pak86 did you use latest version? Btw I pushed some more info too, please update to the latest one and provide me the output. Thank you.

**Comment by pak86** [comment]
@cardigliano yes, I'm using latest version.
Now, I have updated the packages and executed the command again.
You can watch the output below. Thank you.

SNF_FLAGS=0x2 pfcount -i myri:3

 ERROR: Can't read snf device info for the specified device(s): Success
 ERROR: Port 2 not found

 We're now working in demo mode with packet capture and
 transmission limited to 5 minutes

Using PF_RING v.7.5.0
Capturing from myri:3 [mac: 00:00:00:00:00:00][if_index: -1][speed: 0Mb/s]
Device RX channels: 1
Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/59876-none.393

Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd]

**Comment by cardigliano** [comment]
@pak86 please update again, it should work now.

**Comment by pak86** [comment]
@cardigliano I confirm, now it's working. Thank you very much :)
