### ISSUE TITLE
zc driver compile error.

### ISSUE THREAD

**Issue by south-devel** [ntop/PF_RING#513]
OS : CentOS Linux release 7.7.1908
kernel : 3.10.0-1062.el7.x86_64

When I try to make & load pf_ring zc driver from source(git) It cause error.
------------------------------------------
[root@localhost drivers]# cd /PF_RING/drivers
[root@localhost drivers]# make

cd intel; make
make[1]: Entering directory `/d/PF_RING/drivers/intel'
cd e1000e/e1000e-3.4.0.2-zc; make
make[2]: Entering directory `/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc'
cd src; make
make[3]: Entering directory `/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src'
cd ../../../../../kernel/; make
make[4]: Entering directory `/d/PF_RING/kernel'
make -C /lib/modules/3.10.0-1062.el7.x86_64/build SUBDIRS=/d/PF_RING/kernel EXTRA_CFLAGS='-I/d/PF_RING/kernel -DGIT_REV="\"dev:3ee6d70ee5b51ffed45ac61f3d3315e5a9bd1380\"" -fno-pie' modules
make[5]: Entering directory `/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[5]: Leaving directory `/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64'
make[4]: Leaving directory `/d/PF_RING/kernel'
cp ../../../../../kernel/Module.symvers .
make -C /lib/modules/3.10.0-1062.el7.x86_64/build O=/lib/modules/3.10.0-1062.1.1.el7.x86_64/build SUBDIRS=/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src modules
make[4]: Entering directory `/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64'
  CC [M]  /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.o
In file included from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000.h:42:0,
                 from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.c:48:
/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64/include/linux/ptp_clock_kernel.h:46:8: error: redefinition of ‘struct ptp_system_timestamp’
 struct ptp_system_timestamp {
        ^
In file included from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000.h:32:0,
                 from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.c:48:
/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/kcompat.h:6450:8: note: originally defined here
 struct ptp_system_timestamp {
        ^
In file included from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000.h:42:0,
                 from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.c:48:
/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64/include/linux/ptp_clock_kernel.h:242:20: error: conflicting types for ‘ptp_read_system_prets’
 static inline void ptp_read_system_prets(struct ptp_system_timestamp *sts)
                    ^
In file included from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000.h:32:0,
                 from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.c:48:
/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/kcompat.h:6456:1: note: previous definition of ‘ptp_read_system_prets’ was here
 ptp_read_system_prets(struct ptp_system_timestamp __always_unused *sts)
 ^
In file included from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000.h:42:0,
                 from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.c:48:
/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64/include/linux/ptp_clock_kernel.h:248:20: error: conflicting types for ‘ptp_read_system_postts’
 static inline void ptp_read_system_postts(struct ptp_system_timestamp *sts)
                    ^
In file included from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000.h:32:0,
                 from /d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.c:48:
/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/kcompat.h:6462:1: note: previous definition of ‘ptp_read_system_postts’ was here
 ptp_read_system_postts(struct ptp_system_timestamp __always_unused *sts)
 ^
make[6]: *** [/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.o] Error 1
make[5]: *** [_module_/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src] Error 2
make[4]: *** [sub-make] Error 2
make[4]: Leaving directory `/usr/src/kernels/3.10.0-1062.1.1.el7.x86_64'
make[3]: *** [default] Error 2
make[3]: Leaving directory `/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/d/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/d/PF_RING/drivers/intel'
make: *** [all] Error 2

And also packages from http://packages.ntop.org/centos/ also cause error.
---------------------------------------

[root@localhost drivers]# systemctl status pf_ring.service
● pf_ring.service - PF_RING service
   Loaded: loaded (/usr/lib/systemd/system/pf_ring.service; disabled; vendor preset: disabled)
   Active: active (exited) since Sun 2019-09-22 22:05:07 KST; 28min ago
  Process: 16829 ExecStartPost=/bin/sh -c if [ -x /etc/pf_ring/post ]; then /etc/pf_ring/post; fi (code=exited, status=0/SUCCESS)
  Process: 16824 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 16664 ExecStart=/usr/local/bin/pf_ringctl start (code=exited, status=0/SUCCESS)
  Process: 16661 ExecStartPre=/bin/sh -c if [ -x /etc/pf_ring/pre ]; then /etc/pf_ring/pre; fi (code=exited, status=0/SUCCESS)
  Process: 16655 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 16664 (code=exited, status=0/SUCCESS)

Sep 22 22:05:03 localhost.localdomain systemd[1]: Starting PF_RING service...
Sep 22 22:05:03 localhost.localdomain pf_ringctl[16664]: Starting PF_RING module: PF_RING already loaded.[  OK  ]
**Sep 22 22:05:03 localhost.localdomain pf_ringctl[16664]: modinfo: ERROR: Module igb-zc not found.
Sep 22 22:05:03 localhost.localdomain pf_ringctl[16664]: Driver igb-zc not available
Sep 22 22:05:03 localhost.localdomain pf_ringctl[16664]: /usr/local/bin/pf_ringctl: line 315: lspci: command not found**
Sep 22 22:05:07 localhost.localdomain pf_ringctl[16664]: [  OK  ]
Sep 22 22:05:07 localhost.localdomain systemd[1]: Started PF_RING service.

**Comment by cardigliano** [comment]
@nkh8212 we are working on supporting 7.7 which has been released a few days ago. Thank you for reporting.

**Comment by cardigliano** [comment]
@nkh8212 please update to latest dev code or packages, they should compile now on centos 7.7. Thank you.

**Comment by south-devel** [comment]
It works now.
Thank you for the quick response.
