### ISSUE TITLE
nDPI DPDK ft example linking problem

### ISSUE THREAD

**Issue by akiskourtis** [ntop/PF_RING#517]
I am trying to compile pfring and run the ft example with dpdk support.
I have cloned both pfring and ndpi from the latest repositories, but when I do the configure in the pfring userland folder i get the following error.

checking for ndpi_get_api_version in -lndpi... no
configure: WARNING: nDPI is required for L7 protocol detection with PF_RING FT, please install it from http://github.com/ntop/nDPI
checking nDPI support for nBPF - static linking... no

I have done the make && make install in nDPI, and PF_RING and nDPI are both on the same home folder.
Also the nDPI libraries are on /usr/local/lib

Could you lead me on what does it require to link the libraries?
Because from the nDPI integration page, the process seems pretty straight forward but I cannot link these 2.

Thank you!

**Comment by cardigliano** [comment]
@akiskourtis the configure script expects that the ndpi library is installed in a standard location.
AC_CHECK_LIB([ndpi], [ndpi_get_api_version], [LDFLAGS="${LDFLAGS} -lndpi"])
I am not sure why it does not detect the ndpi library from /usr/local/lib in your case. 
What OS are you running?

**Comment by akiskourtis** [comment]
I am running ubuntu 16.04.

I have tried both as a superuser and as a root.

In the second case i had all my folders in the root folder.

I also do an ldconfig after the make install of ndpi.

I have also tried and installed the package version of pfring with no problems. But then i cannot/dont know how to run the ftflow with the dpdk.

**Comment by akiskourtis** [comment]
From what I could find in the configure file, I get the error due to this

> if ac_fn_c_try_link "$LINENO"; then :
  ac_cv_lib_ndpi_ndpi_get_api_version=yes
else
  ac_cv_lib_ndpi_ndpi_get_api_version=no
fi
rm -f core conftest.err conftest.$ac_objext \
    conftest$ac_exeext conftest.$ac_ext
LIBS=$ac_check_lib_save_LIBS
fi
{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_ndpi_ndpi_get_api_version" >&5
$as_echo "$ac_cv_lib_ndpi_ndpi_get_api_version" >&6; }
if test "x$ac_cv_lib_ndpi_ndpi_get_api_version" = xyes; then :
  LDFLAGS="${LDFLAGS} -lndpi"
fi
if test "x$ac_cv_lib_ndpi_ndpi_get_api_version" = xyes; then
  NDPI_LIB=pkg-config --libs libndpi
  NDPI_INC=pkg-config --cflags libndpi | sed -e 's/\(-I^ \t*\)/\1\/libndpi/g'
  HAVE_NDPI="-D HAVE_NDPI"


It tries to call the ndpi_get_api_version, but fails.
I did a clean install, and then a make install on nDPI, is there something else needed?

I also noticed that the paths below:

`NDPI_HOME="../../nDPI"
  if test -f "../$NDPI_HOME/src/lib/libndpi.a"; then
    NDPI_LIB="../$NDPI_HOME/src/lib/libndpi.a"
    NDPI_INC="-I../$NDPI_HOME/src/include"
    HAVE_NDPI="-D HAVE_NDPI"`

don't quite work when I have nDPI in the home/usr/ dir, I need to remove the step back.
After I fix this I get :
checking nDPI support for nBPF - static linking... yes

but still no ft-nDPI yes.

**Comment by cardigliano** [comment]
@akiskourtis I pushed a patch for the configure script, please update to latest code and try again. Thank you.

**Comment by akiskourtis** [comment]
thank you! it configures with no errors now.

**Comment by feriel-ux** [comment]
How Can I link nDPI with DPDK ?

**Comment by cardigliano** [comment]
Sure, the ftflow_dpdk example is using FT, which is in turn loading nDPI at runtime using the shared library in the standard installation path.

**Comment by feriel-ux** [comment]
yes , but how nDPI will match with the DPDK ?

**Comment by cardigliano** [comment]
DPDK is used to capture traffic, packets are provided to FT, which is running the DPI engine on the payload. Did I answer to your question?

**Comment by feriel-ux** [comment]
to be honest , I need to know how the process will happen cz I don't know exactly what should I do first ?

**Comment by feriel-ux** [comment]
should I install the DPDK and the nDPI on the same machine ?

**Comment by cardigliano** [comment]
Yes, you need to install both

**Comment by feriel-ux** [comment]
Then what should do ? I consult which file to add the configuration to ensure the link ?

**Comment by cardigliano** [comment]
You just need to place the library in /usr/lib/libndpi.so.3.5.0 or set the NDPI_LIB_PATH env var (please make sure you use latest ndpi version)

**Comment by feriel-ux** [comment]
Okay thanks

**Comment by feriel-ux** [comment]
hello again , I have a lot of errors in the installation of DPDK http://fast.dpdk.org/rel/dpdk-16.11.1.tar.xz this version .. any help plz or any documentation ?

**Comment by cardigliano** [comment]
@feriel-ux we cannot provide support for installing dpdk sorry

**Comment by feriel-ux** [comment]
okay thanks

**Comment by feriel-ux** [comment]
hello , I need a help for the linking between ndpi over dpdk , I didn't now how to add the library and where .. and how can I be sure that my system run the ndpi over dpdk
