### ISSUE TITLE
how to set the BRO zc worker's number and pin cpus' number?some cpus can'not work now

### ISSUE THREAD

**Issue by husterzlc** [ntop/PF_RING#518]
Hello,i have some problems now when i use bro with zc pf_ring.Our server 's logitic cpu's number is 64,and memory is 256G.And my network interface is ixgbe.It's10Git.I have bought a licence for it.
But when i set the node.cfg,some problems occured.Below is my node.cfg:
[logger]
type=logger
host=localhost
[manager]
type=manager
host=localhost
[proxy-1]
type=proxy
host=localhost
[worker-1]
type=worker
host=localhost
lb_method=pf_ring
lb_procs=16
pin_cpus=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
interfaces=zc:enps0f0
[worker-2]
type=worker
host=localhost
lb_method-pf_ring
lb_procs=16
pin_cpus=16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
interfaces=zc:enps0f0

Only the worker1 workered.The worker2 didn't solve any packages at all.And when i set the 32 pin_cpus in the same worker, i got segment fault.
How to set the node's config? Please.

**Comment by cardigliano** [comment]
@husterzlc please note that:
1. in your configuration worker 1 and worker 2 are opening the same interface zc:enps0f0, this looks like a wrong configuration and it is not allowed with ZC (you cannot open the same interface multiple times as ZC is a kernel-bypass technology with the driver running in the userspace process).
2. each worker is already running multiple processes (lb_procs), I guess you do not need to define multiple workers
3. up to 16 RSS queues are supports with Intel (you should not define 32 processes)

**Comment by husterzlc** [comment]
Ok,thanks a lot.
Now i removed worker-2.And i tested it just now.The capture_loss sometimes is high,such as 20%.Our network's max flow is 2000Mb/s,and the internet card is 10Gbit.Its performance should be better.
How can i solve this?

**Comment by cardigliano** [comment]
It is likely this is due to Bro which is cpu intensive..

**Comment by husterzlc** [comment]
I just read https://www.mail-archive.com/ntop-misc@listgateway.unipi.it/msg05045.html.Its'capture loss is so slow.. Does NUMA affect?how to config it? 
Now the capture_loss is about 20% when the netflow is high.I can't bear it.
Do you have any experience to  make it better though the bottleneck is zeek?
thanks.

**Comment by cardigliano** [comment]
@husterzlc I can only recommend you to reduce the input filtering out traffic which is not interesting (please see for instance L7 filtering with FT at  https://www.ntop.org/guides/pf_ring/thirdparty/bro.html#pf-ring-ft-acceleration). For Zeek tuning please ask the zeek folks.
