### ISSUE TITLE
packets dropped by kernel is higher than packets received by filter when using pf_ring's tcpdump 

### ISSUE THREAD

**Issue by husterzlc** [ntop/PF_RING#519]
Hello.
pakets captured+packets dropped by kernel=packets received by filter
Is it ok?But my results are wrong.Below is one of my results:
71605 packets captured
71605 packets received by filter
1192059 packets dropped by kernel
How to explain this? Where does the packets dropped by kernel come from?
Thanks!

**Comment by cardigliano** [comment]
packets captured are those processed by tcpdump
packets received by filter are those captured by libpcap (they match those processed unless there is a bpf running in libpcap)
packets dropped by kernel are those lost by the kernel when the application cannot keep up with the ingress rate
