### ISSUE TITLE
Feature Request: provide user-space API for match/miss counters for filters

### ISSUE THREAD

**Issue by akadoorie** [ntop/PF_RING#52]
It looks to me quite basic for filtering I/S to provide simple user-space APIs to count the miss/match packets.
For more info, please refer to: http://www.gossamer-threads.com/lists/ntop/misc/40149

**Comment by cardigliano** [comment]
Stats are now available with commit 5668b55867437150c656eab74ba7ba7b433a650a, it also fixes a memory leak. Example:
hash_filtering_rule_stats rule_stats;
pfring_get_hash_filtering_rule_stats(ring, rule, &rule_stats, sizeof(rule_stats));
printf("match: %llu miss: %llu\n", rule_stats.match, rule_stats.miss);
