### ISSUE TITLE
Build failure in Linux: UTS_UBUNTU_RELEASE_ABI too large

### ISSUE THREAD

**Issue by JackBoosY** [ntop/PF_RING#522]
Hi Developers,
Recently I tried to add pfring to vcpkg([#8648](https://github.com/microsoft/vcpkg/pull/8648)), but I got some error here:
```
src/kcompat.h:824:2: error: #error UTS_UBUNTU_RELEASE_ABI is too large...
 #error UTS_UBUNTU_RELEASE_ABI is too large...
  ^~~~~
```

After reviewing the solution, I found the following link:
[[E1000-devel] Ubuntu Kernel Version on AWS EC2](https://sourceforge.net/p/e1000/mailman/message/35929970/)
[[Ntop-dev] Bug in pf_ring.c?](http://lists.ntop.org/pipermail/ntop-dev/2016-August/016526.html)

However, even if I made a patch to fix it, the changes will still be restored when building pf-ring.

How can I solve it? Anyone can help me?

Thanks.

**Comment by cardigliano** [comment]
@JackBoosY which driver is affected? What kernel version are you running? Can I see your patch? Thank you.

**Comment by JackBoosY** [comment]
@cardigliano Thanks for reply, here is my machine info:
> root@usr:/home/work/vcpkg# sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

patch: 
[fix-build.zip](https://github.com/ntop/PF_RING/files/3742752/fix-build.zip)

Step:
1. Download source code.
2. Apply this patch.
3. Build.

I should use driver `e1000e`.

**Comment by cardigliano** [comment]
What pf_ring version are you using? Latest dev source/package is compiling in our lab on Ubuntu 18. Can I see "uname -a"?

**Comment by JackBoosY** [comment]
@cardigliano 
> root@usr:/home/work/vcpkg# uname -a
Linux usr 5.0.0-1020-azure #21~18.04.1-Ubuntu SMP Fri Sep 13 14:10:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I use the commit ID 15c8a3fd01c419b888f379c69c53c90380835200 .

**Comment by cardigliano** [comment]
Got it, you are using an azure kernel. 
Did you check if latest Intel driver available at https://sourceforge.net/projects/e1000/files/e1000e%20stable/3.6.0/ is compiling smootly on the same kernel?

**Comment by JackBoosY** [comment]
@cardigliano  Can not compile this too, the same error:
>/home/work/e1000e-3.6.0/src/kcompat.h:824:2: error: #error UTS_UBUNTU_RELEASE_ABI is too large...
 #error UTS_UBUNTU_RELEASE_ABI is too large...

BTW, how can I modify `kcompat.h` without letting it roll back my changes?
If I fix this judgment correctly, I can build it smoothly.

**Comment by cardigliano** [comment]
Removing that check may lead to compilation of unexpected code paths, however you should be fine as long as the compiler is not complaining. Maybe we can just comment that line for now.

**Comment by cardigliano** [comment]
I pushed the patch, building new packages in 1h.

**Comment by JackBoosY** [comment]
@cardigliano Thanks!

**Comment by JackBoosY** [comment]
@cardigliano Sorry, other identical errors occurred:
```
/home/work/vcpkg/buildtrees/pfring/x64-linux-dbg/drivers/intel/igb/igb-5.3.5.18-zc/src/kcompat.h:824:2: error: #error UTS_UBUNTU_RELEASE_ABI is too large...
 #error UTS_UBUNTU_RELEASE_ABI is too large...
  ^~~~~
```

Can you comment out the `#error UTS_UBUNTU_RELEASE_ABI is too large...` in `kcompat.h` under all drivers?

Thanks.

**Comment by cardigliano** [comment]
@JackBoosY that check is now disabled on all drivers

**Comment by JackBoosY** [comment]
@cardigliano It works!
BTW, without `configure` or `configure.ac` in _SOURCE_PATH_, I cannot set the default install directory.
And, does this library support Windows?

**Comment by cardigliano** [comment]
@JackBoosY feel free to push patches to handle SOURCE_PATH if needed.
Please note that Windows is not supported by PF_RING.
