### ISSUE TITLE
Is it possible to run napatech and n2disk on different containers?

### ISSUE THREAD

**Issue by igorribeiroduarte** [ntop/PF_RING#526]
I have 2 containers, the first starts napatech and on the same container I have an application reading from nt streams. The other container is just a simple container running n2disk, but I need n2disk to read from napatech streams just like the application on the first container. Is there any thing I could do to expose napatech API for other containers so I could be able to read from nt streams from different containers?

**Comment by cardigliano** [comment]
@igorribeiroduarte what do you mean exactly with "the first starts napatech"? Is the first container running the Napatech service?
I assume from what you said that the first container is working, the second is not. Correct?

**Comment by igorribeiroduarte** [comment]
Exactly. The first container is running napatech service alongside with an application which reads from its streams

**Comment by cardigliano** [comment]
I sent a support request to Napatech, with a reference to this issue, asking what resources need to be shared between containers in order to make this work.

**Comment by cardigliano** [comment]
It seems that it is not possible to have one stream in one container and another one in a different container. A container can own the entire adapter, but it cannot be shared between containers.
Please note that there are other options, including capturing all traffic on the host with zbalance_ipc and attach to ZC streams, however this has some impact on performance.
