### ISSUE TITLE
PF_RING zc driver not work.

### ISSUE THREAD

**Issue by oksbsb** [ntop/PF_RING#527]
PF_RING did not work when testing zc driver.

`ubuntu 18.04`

build from git.  load_driver.sh works okay.

zc_driver load okay.

`
driver: i40e
version: 2.4.6
firmware-version: 3.33 0x80000e48 1.1719.0
expansion-rom-version:
bus-info: 0000:1a:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes`
`

`root@master:/dev/shm/build/scripts# /dev/shm/build/userland/usr/bin/zcount -D -i zc:eth1
pfring_zc_create_cluster error [Socket operation on non-socket] Please check that pf_ring.ko is loaded and hugetlb fs is mounted
`

dmesg says.
`[631766.683085] [PF_RING] ring_notifier veth8f21e48: interface index 39096 > max index 2048
[631766.714220] [PF_RING] ring_notifier veth67775e2: interface index 39097 > max index 2048
[631766.714242] [PF_RING] ring_notifier veth67775e2: interface index 39097 > max index 2048
[631766.714362] [PF_RING] ring_notifier veth67775e2: interface index 39097 > max index 2048
[631766.750210] [PF_RING] ring_notifier veth8f21e48: interface index 39096 > max index 2048
[631766.750233] [PF_RING] ring_notifier veth67775e2: interface index 39097 > max index 2048
[631768.230266] [PF_RING] ring_notifier eth4: interface index 38486 > max index 2048
[631768.230270] [PF_RING] ring_notifier eth4: interface index 38486 > max index 2048
[631768.230273] [PF_RING] ring_notifier eth4: interface index 38486 > max index 2048
[631768.230276] [PF_RING] ring_notifier eth5: interface index 38487 > max index 2048
[631768.230278] [PF_RING] ring_notifier eth5: interface index 38487 > max index 2048
[631768.230281] [PF_RING] ring_notifier eth5: interface index 38487 > max index 2048
[631768.230283] [PF_RING] ring_notifier eth0: interface index 38520 > max index 2048
[631768.230285] [PF_RING] ring_notifier eth0: interface index 38520 > max index 2048
[631768.230288] [PF_RING] ring_notifier eth0: interface index 38520 > max index 2048
[631768.230290] [PF_RING] ring_notifier eth1: interface index 38521 > max index 2048
[631768.230292] [PF_RING] ring_notifier eth1: interface index 38521 > max index 2048
[631768.230295] [PF_RING] ring_notifier eth1: interface index 38521 > max index 2048
[631768.230297] [PF_RING] ring_notifier eth2: interface index 38522 > max index 2048
[631768.230299] [PF_RING] ring_notifier eth2: interface index 38522 > max index 2048
[631768.230302] [PF_RING] ring_notifier eth2: interface index 38522 > max index 2048
[631768.230304] [PF_RING] ring_notifier eth3: interface index 38523 > max index 2048
[631768.230307] [PF_RING] ring_notifier eth3: interface index 38523 > max index 2048
[631768.230309] [PF_RING] ring_notifier eth3: interface index 38523 > max index 2048
[631768.230312] [PF_RING] ring_notifier vethf698c58: interface index 39093 > max index 2048
[631768.230314] [PF_RING] ring_notifier vethf698c58: interface index 39093 > max index 2048
[631768.230316] [PF_RING] ring_notifier vethf698c58: interface index 39093 > max index 2048
[631768.230322] [PF_RING] ring_notifier eth0: interface index 39092 > max index 2048
[631768.230324] [PF_RING] ring_notifier eth0: interface index 39092 > max index 2048
[631768.230327] [PF_RING] ring_notifier eth0: interface index 39092 > max index 2048`

`
root@master:/dev/shm/build/scripts# ls /proc/net/pf_ring/dev/ -al
total 0
dr-xr-xr-x 7 root root 0 Nov  7 18:34 .
dr-xr-xr-x 4 root root 0 Nov  7 18:34 ..
dr-xr-xr-x 2 root root 0 Nov  7 18:34 br-29495eec5491
dr-xr-xr-x 2 root root 0 Nov  7 18:34 docker0
dr-xr-xr-x 2 root root 0 Nov  7 18:34 lo
dr-xr-xr-x 2 root root 0 Nov  7 18:34 veth36b0bd2
dr-xr-xr-x 2 root root 0 Nov  7 18:34 vethda2b514
`

`
root@master:/dev/shm/build/scripts# ifconfig
br-29495eec5491: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:c6ff:fe3e:32c6  prefixlen 64  scopeid 0x20<link>
        ether 02:42:c6:3e:32:c6  txqueuelen 0  (Ethernet)
        RX packets 631856  bytes 43597847 (43.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1263872  bytes 161134398 (161.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:82ff:fe39:304f  prefixlen 64  scopeid 0x20<link>
        ether 02:42:82:39:30:4f  txqueuelen 0  (Ethernet)
        RX packets 956962  bytes 52741518 (52.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1361201  bytes 1849100232 (1.8 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.119.0.55  netmask 255.255.255.0  broadcast 10.119.0.255
        inet6 fe80::6e92:bfff:fe99:943e  prefixlen 64  scopeid 0x20<link>
        ether 6c:92:bf:99:94:3e  txqueuelen 1000  (Ethernet)
        RX packets 125285  bytes 62949537 (62.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 187517  bytes 23944008 (23.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::6e92:bfff:fe99:943f  prefixlen 64  scopeid 0x20<link>
        ether 6c:92:bf:99:94:3f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 35432 (35.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15  bytes 1146 (1.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 6c:92:bf:99:94:40  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth3: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 6c:92:bf:99:94:41  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth4: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 6c:92:bf:67:4a:92  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xc4800000-c5000000

eth5: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 6c:92:bf:67:4a:93  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xc4000000-c4800000

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 717912550  bytes 72387702346 (72.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 717912550  bytes 72387702346 (72.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth36b0bd2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::d4ad:70ff:fed2:ab5b  prefixlen 64  scopeid 0x20<link>
        ether d6:ad:70:d2:ab:5b  txqueuelen 0  (Ethernet)
        RX packets 631856  bytes 52443831 (52.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1264058  bytes 161147514 (161.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethd2a9559: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether ae:dd:14:57:9a:35  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethda2b514: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::90e2:5fff:fed6:85dd  prefixlen 64  scopeid 0x20<link>
        ether 92:e2:5f:d6:85:dd  txqueuelen 0  (Ethernet)
        RX packets 1931  bytes 119630 (119.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 23116  bytes 1062490 (1.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethff24905: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 92:c2:17:75:66:21  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by oksbsb** [comment]
it seems occur at:
`  if(dev->ifindex >= MAX_NUM_IFIDX) {
    printk("[PF_RING] %s %s: interface index %d > max index %d\n", __FUNCTION__,
           dev->name, dev->ifindex, MAX_NUM_IFIDX);
    return NOTIFY_DONE;
  }`

**Comment by cardigliano** [comment]
@oksbsb this is due to a limit in the ifindex value, it seems that your system generated too many interface indexes (are you running containers perhaps?), as a workaround please reboot the machine to reset the ifindex, we will fix this.

**Comment by oksbsb** [comment]
Yes. Docker has been installed in that machine, and it may (stop and ) start new instance every few minutes.
The max ifindex were 42945 yestoday, while it's 61603 at this time.
The max ifindex is okay (not bigger than 2048) after reboot.

`61603: veth5690e24@if61602: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default`

`42945: veth70e337b@if42944: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 6a:9d:a9:3a:93:85 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::689d:a9ff:fe3a:9385/64 scope link
       valid_lft forever preferred_lft forever`

**Comment by cardigliano** [comment]
Fixed with https://github.com/ntop/PF_RING/commit/2f7625710731042a3627a3e10e38405cacb69e78 and https://github.com/ntop/PF_RING/commit/07e6f6597a64d344ac6d7cb8d616f9fd9a632ede
