### ISSUE TITLE
Possible packet overwriting with ZC output queue

### ISSUE THREAD

**Issue by pauldurrant** [ntop/PF_RING#528]
I'm working in zc mode with the ixgbe driver, on code based on the zbounce sample, compiled and running on Ubuntu 16.04.

In addition to forwarding between the two external interfaces that are using the ixgbe driver, I'm also reading from an internal dummy interface called (unimaginatively) dummy0 created using

    ip line add dummy0 type dummy

and writing any packets read from that interface to one of the packets. All packet writing to an external interface is happening in a single thread.

I am reading from both interfaces using pfrint_zc_recv_pkt_burst(), passing a different array of ten packet handles depending on whether I'm reading from the real interface or the virtual interface. The twenty packet handle are allocated using the same clusterPtr in the main thread with pfring_zc_get_packet_handle(clusterPtr).

The virtual interface is opened using

    pfring_zc_open_device(clusterPtr, virtualInput.c_str(), rx_only, 0)

where virtualInput is "stack:dummy0"

From debugging, reading packets from the virtual interface seems to work correctly - I'm seeing all the packets I expect to see, and I'm logging details of data in the packet, so I'm sure the packets read are correct.

I then send the packets to the external interface one at a time (often I only receive one at a time anyway), using 

pfring_zc_send_pkt(realOutputQueue, &packetBuffer[loop], 0)

And when they've all been queued, I'm then calling pfring_zc_sync_queue() on the realOutputQueue.

But when I capture the output from the real interface using an external box, I'm not seeing all the packets I expect.

Quite often, there's a missing packet, and then there's two copies of the packet that should come after the missing packet. It very much looks like the data for one of the packets sent to the output has somehow been overwritten by the data in the subsequent packet, so two copies get sent. (The two packets in question are the same length.)

I have tried changing the flag in the send() to send immediately, which had no effect. 

I'm not seeing any problems with packets read from the other external interface and forwarded.

I can't see what I'm doing wrong. Any suggestions greatly appreciated.

**Comment by pauldurrant** [comment]
I forgot to mention - this is with pfring 7.4.0_stable

**Comment by cardigliano** [comment]
@pauldurrant this does not seem to be related to the flush/sync, it seems the same packet is somehow getting copied to 2 egress buffers. Could you provide some code snippet with the buffers management when you read and forward packets?

**Comment by pauldurrant** [comment]
Thanks for the quick response. To get some code I can post, I tried to get adapt zbounce very simply to reproduce the bug, but I was unable to get it to trigger. I'm now examining the differences between the adapted sample and my code. It may be that the problem is being caused by something to do with how I'm setting up and using dummy0 outside of pfring. 

However, please leave this issue open for now, and I'll report back when I have more info next week.

**Comment by pauldurrant** [comment]
I still haven't managed to get sample code to demonstrate the problem. And changes I've made to how my code works has now shown that the problem might lie elsewhere (the duplicate packets now seem not to have gone through my code at all.) Although since I still haven't got to the bottom of things, I can't be 100% sure.

However, I think it would be best to close this issue now. Once I finally find what's really going on, I'll open a new issue if it is pfring related.

**Comment by cardigliano** [comment]
Ok thank you for the update.
