### ISSUE TITLE
On update PFRing restarts before dkms available

### ISSUE THREAD

**Issue by DunkB5** [ntop/PF_RING#529]
Hi,
   When we do and apt-get update and pfring updates, the interface it's bound to vanishes and doesn't come back until we restart pfring again.  In syslog we see

 00:16:08 pf_ringctl[62188]: PF_RING kernel module not installed, please install pfring-dkms:

while in dpkg.log it looks like the pfring-dkms upgrade starts first but is half-configured / half-installed until after pfring is installed and doesn't finish until 5 seconds later, which is 5 seconds after the please install pfring-dkms message.

I see pfring Recommends pfring-dkms, should this be a Depends instead or a restart of pfring triggered after pfring-dkms completes it's install?

Thanks,
           Duncan

**Comment by cardigliano** [comment]
It actually makes sense to move driver loading to the dkms package, this is under testing.

**Comment by cardigliano** [comment]
@DunkB5 there is a new package already available with this change, it's currently under test. It would be nice if you have a chance to check if it's working for you. Thank you.

**Comment by DunkB5** [comment]
Morning,
             Thanks for the fast fix.  I've just installed 7.5.0-2746 via apt and the interface didn't disappear but we ran into other issues immediately and had to roll back. (Kernel module and huge pages)  I'll need to wait until our test server is configured and try this there instead.

I'll go with this is fixed (Interface was still there afterwards) but there's a different problem stopping us moving to 7.5 right now.

Cheers,
           Duncan

**Comment by cardigliano** [comment]
I assume this has been addressed, please reopen this issue in case.
