### ISSUE TITLE
wireshark gui hangs while capturing

### ISSUE THREAD

**Issue by fgerardi** [ntop/PF_RING#53]
Hi,
we have this issue with current linux distributions (i.e. debian jessie, centos 7).
That is wireshark gui totally hangs the moment you start a capture. Even though the capture seems to be running in the background you are forced to kill wireshark process otherwise you are stuck.
This issue is not occurring in case you start a capture via terminal programs like tcpdump or tshark.

The issue is identical on both linux distributions I have tried to replicate the situation: debian jessie and centos 7

I have installed pf_ring from git following the following procedure:

cd PF_RING/kernel
make
sudo make install
cd ../userland
make
cd lib
sudo make install
cd ../libpcap
sudo make install
cd ../tcpdump
./configure
make
sudo make install

After that I have compiled wireshark this way:

./configure --with-gtk2=yes --with-pcap=/usr/local/lib
make
sudo make install

I hope you can help

Bye,
Fabrizio

**Comment by fgerardi** [comment]
I just want to add a note: recently wireshark has been updated to the brand new 2.0 branch.
The issue reported is also occurring with this new wireshark version.

Kind regards,
Fabrizio

**Comment by yesbox** [comment]
I experience this issue (GUI hanging when starting the capture) when Wireshark compiled with pf_ring was run as root. The issue seems to trigged by having no filters, which Wireshark had none of by default when run as root. As a normal user there was a default filter that attempts to filter the users SSH session. If you have no filter as an unprivileged user Wireshark hangs as well.

When using a filter Wireshark doesn't hang anymore. Any filter will do it seems.

This can be reproduced with tshark as well, which doesn't just hang and shows a useful error message:

```
# tshark -i eth0
Capturing on 'eth0'
tshark: Unknown message from dumpcap, try to show it as a string: Warning: Kernel filter failed: Bad address

# tshark -i eth0 greater 0
loads of packets captured!
```

**Comment by cardigliano** [comment]
yesbox, what is the system you are running? Did you reproduce this using latest 6.3?

**Comment by fgerardi** [comment]
Hi. I don't run wireshark as root and the issue occurred both with or without filters.
But I have to say that seemed to be fixed with version 6.3 (still running tests but it is now working on debian jessie).

Bye

**Comment by cardigliano** [comment]
Thank you, please reopen the issue if you are able to reproduce it.

**Comment by yesbox** [comment]
Not entirely clear I'm afraid, I didn't set pf_ring up on there. It's RHEL 7.1 with pf_ring 6.2 or 6.3.
The system will be reinstalled regardless, is 6.3 recommended to run in production? I'll open a new issue if I find out more since we might just have shared the same symptoms.

**Comment by cardigliano** [comment]
yesbox, are you able to reproduce the issue on any of _latest_ 6.2 or 6.3?
6.2 is _the_ stable and recommended for production, 6.3 at the moment is stable enough.

**Comment by rathnaTech** [comment]
@fgerardi 
 please clearly explain 
how you would implement PF_RING with wireshark??
What was the purpose you have to do that ?

please reply as soon as possible. I will tell you the solution.

**Comment by fgerardi** [comment]
Hi, unfortunately the same issue is occurring again with pf_ring version 6.5...Also, the entire system is crashing (kernel panic) in case you click on wireshark menu "Capture/Interfaces"
Please reopen this issue...

**Comment by cardigliano** [comment]
Hi, in the past weeks we worked on a better Wireshark integration, and it seems to be working fine, please let us know if you still experience issues.

**Comment by fgerardi** [comment]
Hi, thanks for your effort indeed...wireshark now is not hanging while capturing.
But I still got kernel panic in case you open "Capture/interfaces" (gtk gui).

**Comment by cardigliano** [comment]
Could you report the kernel panic trace? Thank you.

**Comment by fgerardi** [comment]
Hi, I hope a "dirty" screenshot would be sufficient...
![wireshark_pfring_kernel_panic_11102016_1](https://cloud.githubusercontent.com/assets/15855390/19267693/748e8ffe-8fb0-11e6-8d14-fe7214cf3d7f.jpg)
