### ISSUE TITLE
Intel XXV710 support?

### ISSUE THREAD

**Issue by daniel-pebble** [ntop/PF_RING#530]
Hi, 

Does anyone know if PF_RING ZC supports Intel XXV710 25Gb cards?

Thanks,

Daniel

**Comment by cardigliano** [comment]
@daniel-pebble XXV710 should be supported by the i40e zc driver, however we do not have it in our lab at the moment, please let me know if you have a chance to test it. Thank you.

**Comment by daniel-pebble** [comment]
Thanks for confirming.  I'll order a card and will let you know how the testing goes. 
For reference this is the card I'll be using https://www.fs.com/uk/products/75603.html

**Comment by cardigliano** [comment]
Great, please keep up posted updating this issue. Thank you.

**Comment by daniel-pebble** [comment]
I can confirm pf_ring works with this card and indeed it uses the i40e driver!
Many thanks
