### ISSUE TITLE
PF_RING-DEV insmod ixgbe failed

### ISSUE THREAD

**Issue by liuchuang** [ntop/PF_RING#531]
hi,use PF_RING-DEV, after `make`

exe:
`insmod ./ixgbe/ixgbe-5.5.3-zc/src/ixgbe.ko`
error msg:
`insmod: error inserting './ixgbe/ixgbe-5.5.3-zc/src/ixgbe.ko': -1 Unknown symbol in module`
dmesg:
`ixgbe: Unknown symbol pf_ring_zc_dev_handler (err 0)`

if `insmod ixgbe` after `insmod pf_ring` is no error,can it be fix? sometimes i dont need pf_ring ko.
and in PF_RING-7.4.0 release this is no error,thanks.

**Comment by cardigliano** [comment]
@liuchuang you need pf_ring.ko to use the drivers we provide
