### ISSUE TITLE
Broken support for Redhat Kernel 4.X 

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#533]
A recent change added the following to pfring.c (in multiple locations):

```
#if(LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0))
    dev_change_flags(netdev, if_flags);
#else
    dev_change_flags(netdev, if_flags, NULL);
#endif
```
Causes the following compile errors (also seen during yum package installation of pfring-dkms):

> make -C /lib/modules/4.18.0-147.el8.x86_64/build SUBDIRS=/usr/src/PF_RING/kernel EXTRA_CFLAGS='-I/usr/src/PF_RING/kernel -DGIT_REV="\"dev:d3568ad199f894986c6df1255e062081c0dbe9c5\"" -no-pie -fno-pie' modules
> make[1]: Entering directory '/usr/src/kernels/4.18.0-147.el8.x86_64'
>   CC [M]  /usr/src/PF_RING/kernel/pf_ring.o
> /usr/src/PF_RING/kernel/pf_ring.c: In function ‘set_netdev_promisc’:
> /usr/src/PF_RING/kernel/pf_ring.c:5049:5: error: too few arguments to function ‘dev_change_flags’
>      dev_change_flags(netdev, if_flags);
>      ^~~~~~~~~~~~~~~~
> In file included from ./include/linux/rtnetlink.h:7,
>                  from /usr/src/PF_RING/kernel/pf_ring.c:84:
> ./include/linux/netdevice.h:3791:5: note: declared here
>  int dev_change_flags(struct net_device *dev, unsigned int flags,
>      ^~~~~~~~~~~~~~~~
> /usr/src/PF_RING/kernel/pf_ring.c: In function ‘unset_netdev_promisc’:
> /usr/src/PF_RING/kernel/pf_ring.c:5071:5: error: too few arguments to function ‘dev_change_flags’
>      dev_change_flags(netdev, if_flags);
>      ^~~~~~~~~~~~~~~~
> In file included from ./include/linux/rtnetlink.h:7,
>                  from /usr/src/PF_RING/kernel/pf_ring.c:84:
> ./include/linux/netdevice.h:3791:5: note: declared here
>  int dev_change_flags(struct net_device *dev, unsigned int flags,
>      ^~~~~~~~~~~~~~~~
> make[2]: *** [scripts/Makefile.build:319: /usr/src/PF_RING/kernel/pf_ring.o] Error 1
> make[1]: *** [Makefile:1547: _module_/usr/src/PF_RING/kernel] Error 2
> make[1]: Leaving directory '/usr/src/kernels/4.18.0-147.el8.x86_64'
> make: *** [Makefile:64: all] Error 2

Redhat 8.1 Kernel 4.18.0-147 also requires three arguments to dev_change_flags.

**Comment by cardigliano** [comment]
I am currently running Centos 8 with kernel 4.18.0-80 in our lab, it seems Centos has not been updated to 4.18.0-147 yet. I will try to add a check on the revision..

**Comment by cardigliano** [comment]
Are you running RH 8 or 8.1?

**Comment by cardigliano** [comment]
Please check if latest code works for you
https://github.com/ntop/PF_RING/commit/6bf11cb0db3d1828477cafe1446564447f2beef7

**Comment by Arislen** [comment]
> Are you running RH 8 or 8.1?

RH 8.1

**Comment by Arislen** [comment]
> Please check if latest code works for you
> [6bf11cb](https://github.com/ntop/PF_RING/commit/6bf11cb0db3d1828477cafe1446564447f2beef7)

Still no joy. A quick look at part of the change:

```
#if(LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0) || \
    (defined(REDHAT_PATCHED_KERNEL) && RHEL_MAJOR == 8 && RHEL_MINOR >= 1))
    dev_change_flags(netdev, if_flags);
#else
    dev_change_flags(netdev, if_flags, NULL);
#endif
```

The logic seems a little off. RedHat 8.1 needs the #else portion (three arguments). Something like this?

```
#if(LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0) && \
    !(defined(REDHAT_PATCHED_KERNEL) && RHEL_MAJOR == 8 && RHEL_MINOR >= 1))
    dev_change_flags(netdev, if_flags);
#else
    dev_change_flags(netdev, if_flags, NULL);
#endif



```

**Comment by cardigliano** [comment]
Correct. Sorry it was a blind fix, I fixed it right now.

**Comment by Arislen** [comment]
> Correct. Sorry it was a blind fix, I fixed it right now.

Looks good! Thanks!
