### ISSUE TITLE
ZeroCopy Drivers broken in RedHat 8.1

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#534]
Found another potential issue with PF_RING and RedHat 8.1:

This time I'm trying to install the latest 8 YUM package for the ZC Drivers. Most of the drivers display this error during the script execution portion of the yum package install:

> DKMS make.log for ixgbe-zc-5.5.3.2770 for kernel 4.18.0-147.0.3.el8_1.x86_64 (x86_64)
> Wed Dec  4 09:51:52 EST 2019
> cd /usr/src/pfring-7.5.0/; make
> make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> make[1]: Entering directory '/usr/src/pfring-7.5.0'
> make -C /lib/modules/4.18.0-147.0.3.el8_1.x86_64/build SUBDIRS=/usr/src/pfring-7.5.0 EXTRA_CFLAGS='-I/usr/src/pfring-7.5.0 -DGIT_REV="\"dev:d3568ad199f894986c6df1255e062081c0dbe9c5\"" -no-pie -fno-pie' modules
> make[2]: Entering directory '/usr/src/kernels/4.18.0-147.0.3.el8_1.x86_64'
>   Building modules, stage 2.
>   MODPOST 1 modules
> make[2]: Leaving directory '/usr/src/kernels/4.18.0-147.0.3.el8_1.x86_64'
> make[1]: Leaving directory '/usr/src/pfring-7.5.0'
> cp /usr/src/pfring-7.5.0/Module.symvers .
> make -C /lib/modules/4.18.0-147.0.3.el8_1.x86_64/build SUBDIRS=/var/lib/dkms/ixgbe-zc/5.5.3.2770/build modules
> make[1]: Entering directory '/usr/src/kernels/4.18.0-147.0.3.el8_1.x86_64'
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_main.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_common.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_api.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_param.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_lib.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_ethtool.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/kcompat.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_82598.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_82599.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_x540.o
>   CC [M]  /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_x550.o
> In file included from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_osdep.h:17,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_type.h:45,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_dcb.h:7,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe.h:24,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_main.c:31:
> /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/kcompat.h:6470:8: error: redefinition of ‘struct flow_match’
>  struct flow_match {
>         ^~~~~~~~~~
> In file included from ./include/net/pkt_cls.h:9,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/kcompat.h:6468,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_osdep.h:17,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_type.h:45,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_dcb.h:7,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe.h:24,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_main.c:31:
> ./include/net/flow_offload.h:6:8: note: originally defined here
>  struct flow_match {
>         ^~~~~~~~~~
> In file included from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_osdep.h:17,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_type.h:45,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_dcb.h:7,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe.h:24,
>                  from /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/ixgbe_main.c:31:
> /var/lib/dkms/ixgbe-zc/5.5.3.2770/build/kcompat.h:6476:8: error: redefinition of ‘struct flow_match_basic’
>  struct flow_match_basic {
>         ^~~~~~~~~~~~~~~~
> In file included from ./include/net/pkt_cls.h:9,
> (cut for brevity)

Looks like the kcompat.h is redefining structs that exists in the RedHat 8.1 kernel source. 

In kcompat.h: 

```
/*****************************************************************************/
#if (LINUX_VERSION_CODE < KERNEL_VERSION(5,1,0))

#ifdef HAVE_TC_SETUP_CLSFLOWER
#include <net/pkt_cls.h>

struct flow_match {
	struct flow_dissector	*dissector;
	void			*mask;
	void			*key;
};

struct flow_match_basic {
	struct flow_dissector_key_basic *key, *mask;
};

struct flow_match_control {
	struct flow_dissector_key_control *key, *mask;
};
(cut for brevity)
```

Looks like there needs to be another test because RedHat 8.1 (kernel version 4.18.X) is implementing changes from Linux Generic Kernel Source 5 and greater.

**Comment by cardigliano** [comment]
I will fix this as soon as I am able to access a Centos 8.1, if you are able to add a check in the meantime (and even send a PR) that would be great.

**Comment by Arislen** [comment]
I've made changes and tested it to fix this issue on my Redhat 8.1 system. Not familiar enough with GitHub to know the best way to get the changes to you for review however. I have a local Git branch that I made the changes to. 

Please advise on your preferred way to get the changes to you. I've attach a tarball here in the meantime.

The changes I made were adapted from the way DPDK fixed their Intel drivers for the particularities of the RedHat 8 kernel. 

[PFRING_ZC_FIXES.tar.gz](https://github.com/ntop/PF_RING/files/3932145/PFRING_ZC_FIXES.tar.gz)

**Comment by cardigliano** [comment]
Thank you! The tarball is also fine, however if you would like to be tracked as contributor to the project on github, you should send a pull request.

**Comment by cardigliano** [comment]
I pushed a few paches to build the drivers on Centos 8.1 (same kernel as RH 8.1)
