### ISSUE TITLE
Build error - kernel 5.4

### ISSUE THREAD

**Issue by fsamareanu** [ntop/PF_RING#535]
Hello,

DKMS module build fails with this error:

```
DKMS make.log for pfring-7.5.0 for kernel 5.4.0-xanmod0 (amd64)
Thu 05 Dec 2019 03:18:17 PM +04
make -C /lib/modules/5.4.0-xanmod0/build SUBDIRS=/var/lib/dkms/pfring/7.5.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/7.5.0/build -DGIT_REV="\"dev:6bf11cb0db3d1828477cafe1446564447f2beef7\"" -no-pie -fno-pie' modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-xanmod0'
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
make[1]: *** [arch/x86/Makefile:272: archscripts] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-xanmod0'
make: *** [Makefile:64: all] Error 2
```
Changing the make line to this fixes it:

        make -C /lib/modules/$(BUILD_KERNEL)/build M=${PWD} EXTRA_CFLAGS='${EXTRA_CFLAGS}' modules

**Comment by cardigliano** [comment]
I pushed this patch to latest 7.5. Thank you.

**Comment by fsamareanu** [comment]
Confirmed working now. Thank you :)

**Comment by heliolei** [comment]
Hello, I met the same problem, but please how to change the make line?
I did not find where I can change

**Comment by cardigliano** [comment]
@heliolei what pf_ring version are you using?

**Comment by evandrocoan** [comment]
> I pushed this patch to latest 7.5. Thank you.

@cardigliano Is this the commit fixing it? 
1. https://github.com/ntop/PF_RING/commit/a960f8093ac3026cbf7189dce83462b888863f3a - Compilation fix
1. https://github.com/ntop/PF_RING/commits/dev?after=2e5350540b1cd400f488cfd48d3807f1a124732f+419&branch=dev

**Comment by cardigliano** [comment]
yes

**Comment by EmilPi** [comment]
Hi,
https://manhattanproducts.us/products/manhattan-en-smart-card-reader-102049 - I downloaded driver for linux, extracted, run `make` or `sudo make` and I get
`
sed "s/RTSX_MK_TIME/`date +%y.%m.%d.%H.%M`/" timestamp.in > timestamp.h
cp -f ./define.release ./define.h
make -C /lib/modules/5.8.0-59-generic/build/ SUBDIRS=/home/emil/Desktop/rts_pstor modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-59-generic'
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
make[1]: *** [arch/x86/Makefile:214: archscripts] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-59-generic'
make: *** [Makefile:37: default] Error 2
`
