### ISSUE TITLE
Request Modifications to CENTOS/Redhat Repository Page

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#536]
When I'm installing from a minimal RedHat 8.1 install, the following NTOP packages require the make command to be installed but do not require it as a dependency:

pfring-dkms
pfring-drivers-zc-dkms (actually it probably is the drivers that this installs that require make to be specific)

Would like to have either the rpm's to be modified to require make or to include a blurb about the requirement on that http://packages.ntop.org/centos/ webpage.

Also, a bit more RedHat 8 centric but the install command:

dnf config-manager --set-enabled PowerTools

Is not applicable to RedHat OS's. The EPEL website states the following as the equivalent for RedHat systems (using the x86_64 architecture):

 subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms

Reference: https://fedoraproject.org/wiki/EPEL

**Comment by cardigliano** [comment]
The make dep has been added to the dkms package. As of the EPEL command, we provide instructions for CentOS only as that's what we officially support (we do not have RH in our lab).
