### ISSUE TITLE
Warning during installation

### ISSUE THREAD

**Issue by fsamareanu** [ntop/PF_RING#537]
Hello,

The following warning pops up on debian 10:

```
Unpacking pfring (7.5.0-2774) over (7.5.0-2774) ...
Removed /etc/systemd/system/multi-user.target.wants/pf_ring.service.
Invalid unit name "cluster@*" was escaped as "cluster@\x2a" (maybe you should use systemd-escape?)

```
It doesn't affect operation but it should be considered in order to comply to systemd standards.

Similar issue: https://github.com/ntop/ntopng/issues/2837

**Comment by cardigliano** [comment]
The same fix of ntop/ntopng#2837 has been applied, could you let us know if you still see the same on next update? Thank you.

**Comment by fsamareanu** [comment]
Nope, still the same as of today:

Get:1 http://packages.ntop.org/apt/buster x64/ pfring 7.5.0-2780 [1,911 kB]
Get:2 http://packages.ntop.org/apt/buster x64/ ndpi 3.1.0-2125 [574 kB]
Get:3 http://packages.ntop.org/apt/buster x64/ ntopng 3.9.191216-8360 [18.7 MB]
Get:4 http://packages.ntop.org/apt/buster all/ ntopng-data 3.9.191216 [22.7 MB]
Fetched 43.9 MB in 6s (6,992 kB/s)
Preconfiguring packages ...
(Reading database ... 160809 files and directories currently installed.)
Preparing to unpack .../pfring_7.5.0-2780_amd64.deb ...
Unpacking pfring (7.5.0-2780) over (7.5.0-2780) ...
Invalid unit name "cluster@*" was escaped as "cluster@\x2a" (maybe you should use systemd-escape?)

**Comment by fsamareanu** [comment]
Same issue in this one:

```
Unpacking pfring (7.5.0-2786) over (7.5.0-2780) ...
Invalid unit name "cluster@*" was escaped as "cluster@\x2a" (maybe you should use systemd-escape?)

```

**Comment by cardigliano** [comment]
I pushed one more fix, let's see with the next update

**Comment by fsamareanu** [comment]
Works now. Thank you!
