### ISSUE TITLE
[FT] Reload protos.txt during runtime (especially in zbalance_ipc)

### ISSUE THREAD

**Issue by upendrabh** [ntop/PF_RING#538]
Reload protos.txt during runtime especially in zbalance_ipc without restart. It should update the filter table with new ips/custom filters without traffic disruption.

**Comment by annp1987** [comment]
Hi @cardigliano
Would you mind to share status of this feature? Is it ready on current pf_ring ft lib?

**Comment by cardigliano** [comment]
The FT API now includes pfring_ft_load_ndpi_protocols, that can be used to reload custom nDPI protocols. This is called by zbalance_ipc at startup. (Feel free to send a PR if you can contribute adding support for runtime reloading in zbalance_ipc)

**Comment by cardigliano** [comment]
Implemented via PR
