### ISSUE TITLE
Problem with pf_ring ZC and Bro restrict_filter

### ISSUE THREAD

**Issue by ppalad** [ntop/PF_RING#540]
I noticed that pf_ring zc and Bro with some “restrict_filter” aren't filtering the specified host correctly.
I think that the problem is in the pf_ring ZC driver.
In order to isolate the problem, I did several tests. I tried both virtual (hypervisor used: VMware ESXi), and physical machines belong to the same VLAN. Maybe the problem could be related to the VLAN tag. I also tried to perform tests using tcpdump (with BPF filters as in Bro).  I suspect the issue could be in Pf_ring ZC driver.

Here is a list of the tests I did:

**snf0** refers to a interface that uses an Intel i40e driver
**zc:99** is a virtual interface made from pf_ring zc

**Test1:**
tcpdump -i snf0 host IP
Tcpdump captures the traffic of both virtual and physical machines, without issues.
 
**Test2:**
tcpdump -i zc:99 host IP
The test has failed. In detail it doesn't filter some virtual and physical machines.
 
**Test3:**
tcpdump -i zc:99 net IP_net/netmask
The test has failed. In detail it doesn't filter some virtual and physical machines.

Thank you.
Regards,
Pasquale

**Comment by cardigliano** [comment]
Test2 and Test3 (with your pcap) work for me, I can see the traffic matching the filter. Are you using the tcpdump distributed with pf_ring?
