### ISSUE TITLE
error with pfcount : pfring_open error [No such device] (pf_ring not loaded or interface zc:ens4f0 is down ?) 

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#541]
I was running pfcount with ZC but pfcount throws the below error. It works fine without ZC.

Version of pfringZC: PF_RING-ZC-ixgbe-7.5.0

#  /usr/bin/pfcount -i zc:ens4f0
pfring_open error [No such device] (pf_ring not loaded or interface zc:ens4f0 is down ?)

Details of interface and commands executed:
=====================================
ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::a236:9fff:fe3f:55b8  prefixlen 64  scopeid 0x20<link>
        ether a0:36:9f:3f:55:b8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 880 (880.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfbc00000-fbe00000  

# pf_ringcfg --list-interfaces
Name: eno1                 Driver: tg3                       
Name: eno2                 Driver: tg3                       
Name: eno3                 Driver: tg3                       
Name: eno4                 Driver: tg3                       
Name: ens4f0               Driver: ixgbe      [Running ZC]   
Name: virbr0-nic           Driver: tun                       
Name: virbr0               Driver: bridge                    
Name: ens4f1               Driver: ixgbe      [Running ZC]   

$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

$ free -g
              total        used        free      shared  buff/cache   available
Mem:            251           5         244           0           1         245
Swap:           119           0         119

**Comment by cardigliano** [comment]
Please provide the dmesg output. It seems the zc driver is loaded, thus this is due to some other failure.

**Comment by mdiqbalahmad** [comment]
dmesg output is at : https://gist.github.com/mdiqbalahmad/2683f49521a19a56f37750febdefaa6b

update:
the interface ens4f0 might show down at the end of dmesg, please ignore that as I had removed the cable before taking dmesg dump.

**Comment by cardigliano** [comment]
@mdiqbalahmad I do not see errors, what is strange is that the driver is loaded before the pf_ring module, are you loading them manually perhaps? Are you able to provide access to this system for debugging? Thank you.

**Comment by mdiqbalahmad** [comment]
yes we are loading driver and pf_ring manually. As the server contains IntelectualProperties, I can share it it over team viewer. Please let me know the time/timezone you can be available. How shall i share team viewer details?

**Comment by cardigliano** [comment]
Please try loading the driver *after* the pf_ring kernel module.

**Comment by mdiqbalahmad** [comment]
we have loaded the pf_ring first and then driver module as suggested.

commands/scripts used to load are as below:

ipprobe-pf_ring-zc-ixgbe-3.10.0-957.21.3.el7.x86_64-7.5.0.modules:
https://gist.github.com/mdiqbalahmad/b41b60210831b8875229253be7c1353a

createhugepages.sh:
https://gist.github.com/mdiqbalahmad/e0a101ded2202e5b7d84222989ee52d9

loadModulesixgbe.sh:
https://gist.github.com/mdiqbalahmad/97e09bb8996fe7b5daf268a934ee7518

when trying with zcount with interface "ens4f0" - this works but if we run using "zc:ens4f0: it doesnt
# /usr/bin/zcount -i zc:ens4f0
pfring_zc_open_device error [Socket operation on non-socket] Please check that zc:ens4f0 is up and not already used

Q: Is there a change in way of providing interface name for zc?

Dmesg: log
=============
[Mon Jan 6 15:14:27 2020] ixgbe 0000:21:00.1: removed PHC on ens4f1
[Mon Jan 6 15:14:28 2020] ixgbe 0000:21:00.0: removed PHC on ens4f0
[Mon Jan 6 15:16:47 2020] NET: Unregistered protocol family 27
[Mon Jan 6 15:16:47 2020] [PF_RING] Module unloaded
[Mon Jan 6 15:16:47 2020] [PF_RING] Welcome to PF_RING 7.5.0 ($Revision: unknown$)
(C) 2004-17 ntop.org
[Mon Jan 6 15:16:47 2020] LINUX_VERSION_CODE 00030A00
[Mon Jan 6 15:16:47 2020] [PF_RING] Min # ring slots 409600
[Mon Jan 6 15:16:47 2020] [PF_RING] Slot version 17
[Mon Jan 6 15:16:47 2020] [PF_RING] Capture TX No [RX only]
[Mon Jan 6 15:16:47 2020] [PF_RING] IP Defragment No
[Mon Jan 6 15:16:47 2020] NET: Registered protocol family 27
[Mon Jan 6 15:16:47 2020] [PF_RING] pf_ring initialized correctly
[Mon Jan 6 15:16:47 2020] Intel(R) 10GbE PCI Express Linux Network Driver - version 5.3.7
[Mon Jan 6 15:16:47 2020] Copyright(c) 1999 - 2018 Intel Corporation.
[Mon Jan 6 15:16:47 2020] ixgbe: Receive-Side Scaling (RSS) set to 4
[Mon Jan 6 15:16:47 2020] ixgbe: 0000:21:00.0: ixgbe_check_options: FCoE Offload feature enabled
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: irq 92 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: irq 93 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: irq 94 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: irq 95 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: irq 96 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: 32.000 Gb/s available PCIe bandwidth, limited by 5 GT/s x8 link at 0000:20:03.0 (capable of 63.008 Gb/s with 8 GT/s x8 link)
[Mon Jan 6 15:16:47 2020] [PF_RING] removing dev=ens4f0 ifindex=30 (2)
[Mon Jan 6 15:16:47 2020] IPv6: ADDRCONF(NETDEV_UP): ens4f0: link is not ready
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0 ens4f0: MAC: 3, PHY: 3, PBA No: G45270-003
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: a0:36:9f:3f:55:b8
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0 ens4f0: Enabled Features: RxQ: 4 TxQ: 4 FdirHash 
[Mon Jan 6 15:16:47 2020] pps pps0: new PPS source ptp4
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0: registered PHC device on ens4f0
[Mon Jan 6 15:16:47 2020] IPv6: ADDRCONF(NETDEV_UP): ens4f0: link is not ready
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.0 ens4f0: Intel(R) 10 Gigabit Network Connection
[Mon Jan 6 15:16:47 2020] ixgbe: Receive-Side Scaling (RSS) set to 4
[Mon Jan 6 15:16:47 2020] ixgbe: 0000:21:00.1: ixgbe_check_options: FCoE Offload feature enabled
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: irq 98 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: irq 99 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: irq 100 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: irq 101 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: irq 102 for MSI/MSI-X
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: 32.000 Gb/s available PCIe bandwidth, limited by 5 GT/s x8 link at 0000:20:03.0 (capable of 63.008 Gb/s with 8 GT/s x8 link)
[Mon Jan 6 15:16:47 2020] [PF_RING] removing dev=ens4f1 ifindex=31 (2)
[Mon Jan 6 15:16:47 2020] IPv6: ADDRCONF(NETDEV_UP): ens4f1: link is not ready
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1 ens4f1: MAC: 3, PHY: 3, PBA No: G45270-003
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: a0:36:9f:3f:55:ba
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1 ens4f1: Enabled Features: RxQ: 4 TxQ: 4 FdirHash 
[Mon Jan 6 15:16:47 2020] pps pps1: new PPS source ptp5
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1: registered PHC device on ens4f1
[Mon Jan 6 15:16:47 2020] IPv6: ADDRCONF(NETDEV_UP): ens4f1: link is not ready
[Mon Jan 6 15:16:47 2020] ixgbe 0000:21:00.1 ens4f1: Intel(R) 10 Gigabit Network Connection
[Mon Jan 6 15:16:50 2020] ixgbe 0000:21:00.1 ens4f1: NIC Link is Up 1 Gbps, Flow Control: RX/TX
[Mon Jan 6 15:16:50 2020] IPv6: ADDRCONF(NETDEV_CHANGE): ens4f1: link becomes ready
[Mon Jan 6 15:16:55 2020] ixgbe 0000:21:00.1 ens4f1: NIC Link is Up 1 Gbps, Flow Control: RX
[Mon Jan 6 15:24:55 2020] ixgbe 0000:21:00.0 ens4f0: NIC Link is Up 10 Gbps, Flow Control: RX
[Mon Jan 6 15:24:55 2020] IPv6: ADDRCONF(NETDEV_CHANGE): ens4f0: link becomes ready
[Mon Jan 6 15:32:46 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:32:49 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:34:34 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:35:02 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:38:05 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:38:09 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:38:17 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:38:43 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:39:33 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:40:15 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:42:53 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:43:25 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:43:42 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:43:51 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:46:42 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:48:34 2020] device ens4f0 left promiscuous mode
[Mon Jan 6 15:49:09 2020] device ens4f0 entered promiscuous mode
[Mon Jan 6 15:49:11 2020] device ens4f0 left promiscuous mode





We have seen huge pages getting created.
# grep HugePages_ /proc/meminfo
HugePages_Total:    1536
HugePages_Free:     1536
HugePages_Rsvd:        0
HugePages_Surp:        0

**Comment by cardigliano** [comment]
@mdiqbalahmad it seems the driver is loaded in the correct order now. Are you able to provide access to this box for debugging?

**Comment by mdiqbalahmad** [comment]
@cardigliano  how shall i share the teamviewer details securely?

**Comment by cardigliano** [comment]
Please drop an email to cardigliano at ntop

**Comment by w2n1ck** [comment]
its work? I have the same problem. What’s the solution? help me.

**Comment by stanley111111** [comment]
Did anyone solve that?
 
```
/usr/bin/zcount -i zc:enp6s0f0
pfring_zc_open_device error [Socket operation on non-socket] Please check that zc:enp6s0f0 is up and not already used
```

```
/sbin/ethtool -i enp6s0f0
driver: ixgbe
version: 5.1.0-k
firmware-version: 0x00012b2c
expansion-rom-version:
bus-info: 0000:06:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```

```
cat /proc/net/pf_ring/dev/enp6s0f0/info
Name:         enp6s0f0
Index:        4
Address:      00:1B:21:BC:76:96
Polling Mode: NAPI
Promisc:      Enabled
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  4
TX Queues:    40
RX Queues:    40
```
