### ISSUE TITLE
Stack-injected packets seem to loop 

### ISSUE THREAD

**Issue by atonkyra** [ntop/PF_RING#542]
First of all I'm not sure if this is a bug or is supposed to happen. I encountered the following (unexpected) scenario while trying to make a following test setup:

```
zc-device (RX only) =filter=> stack
```

However when testing with zbounce example script I get a "loop" where following seems to happen (`./zbounce -i zc:enp2s0 -o stack:enp2s0`):
```
                         ,-----------------
                        v                  \
zc-device => recv(zc:enp2s0) => send(stack:enp2s0)
```

So the original packet received from the ZC device seems to end up being received again after it is sent to stack.

So to reproduce, have interface (in my example, enp2s0) and run `./zbounce -i zc:enp2s0 -o stack:enp2s0` and after that send a packet to that interface and you should have reproduced the "loop".

**Comment by atonkyra** [comment]
Using e1000e driver so this might be a regression of #27

**Comment by cardigliano** [comment]
@atonkyra I pushed a fix for this, please update and let me know.

**Comment by atonkyra** [comment]
That fixed it. Thanks! Found 1 more issue and will make an issue out of it.
