### ISSUE TITLE
insmod i40e driver, ssh error

### ISSUE THREAD

**Issue by huangh901218** [ntop/PF_RING#544]
when insomd pfring i40e dirver, then  reboot, ssh error ssh_exchange_identification: read: Connection reset by peer
 i40e version 2.4.6
 centos os and kenel version 3.10.0-693.17.el7.x86_64

**Comment by cardigliano** [comment]
@huangh901218 if you just insmod the driver, then you reboot the machine, this should not affect ssh after reboot. Instead, I guess you are configuring the driver to be loaded by systemd, correct? Is the management interface using the same driver?

**Comment by huangh901218** [comment]
> @huangh901218 if you just insmod the driver, then you reboot the machine, this should not affect ssh after reboot. Instead, I guess you are configuring the driver to be loaded by systemd, correct? Is the management interface using the same driver?

yes,yes

**Comment by huangh901218** [comment]
The driver of the network card can be connected through SSH normally

**Comment by cardigliano** [comment]
Please make sure an IP address is set on the interface after reboot, as the standard driver is getting reloaded. You can use the "post" script as described at the bottom of https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html to configure the interface in case

**Comment by huangh901218** [comment]
I'm sure an IP address is set on the interface after reboot, when i use "ping" is  normally

**Comment by cardigliano** [comment]
This is strange, could you try restarting the ssh service after reloading the driver?
