### ISSUE TITLE
Alpine Linux 3.11 compatibility

### ISSUE THREAD

**Issue by atonkyra** [ntop/PF_RING#545]
Current PF_RING distribution uses `__strdup` in several of the shipped binaries. Would it be possible to use `strdup` directly? Alternatively would it be possible to provide binaries for musl userlands?

Musl in Alpine Linux 3.11 only exposes `strdup` symbol so any binaries trying to link to libpfring will fail because of the missing `__strdup` .

The problem can of course be hacked around by defining a custom `__strdup()` which uses `strdup()`.

**Comment by cardigliano** [comment]
@atonkyra our code is not explicitly using __strdup actually, it seems this due to compiler optimizations..

**Comment by Xumeiquer** [comment]
@atonkyra did you finally spot the issue? I am facing the same issue.

**Comment by XinRoom** [comment]
It seems to be introduced by files under `userland/lib/libs/`.
For example, the `check_fb_license` function in `libpfring_fiberblaze_x86_64.a` is used.
﻿Can try to use a custom `__strdup` function to link to solve the problem.
