### ISSUE TITLE
[disk2n.c:1925] ERROR: Unable to open PF_RING device zc:ens2f0 [globals.ro.snaplen=1536]

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#547]
Hi,

I had previous version of disk2n and pfring zc in rhel 7.2 which i removed to install recent version of disk2n and pfring zc. I see the below error while running the disk2n.

How do I fix it?

Installed packages
====================
pfring-dkms-7.4.0-2813.noarch
pfring-7.4.0-2813.x86_64
pfring-drivers-zc-dkms-1.2-0.noarch
n2disk-3.4.200120-5184.x86_64

=============== error while running disk2n ============================ 
24/Jan/2020 19:23:38 [disk2n.c:2603] WARNING: Please use chunk len of 1MB (-C 1024) when replaying .npcap compressed files
24/Jan/2020 19:23:38 [disk2n.c:2623] Reading data in 4096 KB chunks
24/Jan/2020 19:23:38 [disk2n.c:2624] Allocating 2048 MB buffer memory...
24/Jan/2020 19:23:38 [disk2n.c:2675] Memory allocated successfully
24/Jan/2020 19:23:38 [disk2n.c:1925] ERROR: Unable to open PF_RING device zc:ens2f0 [globals.ro.snaplen=1536]
24/Jan/2020 19:23:38 [disk2n.c:353] Waiting thread termination...
24/Jan/2020 19:23:38 [disk2n.c:2683] ERROR: Unable to initialize socket on zc:ens2f0

dmesg log
==========

[dmesg-disk2n.txt](https://github.com/ntop/PF_RING/files/4109104/dmesg-disk2n.txt)

# pf_ringcfg --list-interfaces
Name: enp3s0f0             Driver: bnx2                      
Name: enp4s0f0             Driver: bnx2                      
Name: enp3s0f1             Driver: bnx2                      
Name: enp4s0f1             Driver: bnx2                      
Name: ens2f0               Driver: ixgbe      [Supported by ZC]
Name: ens3f0               Driver: ixgbe      [Supported by ZC]
Name: virbr0-nic           Driver: tun                       
Name: virbr0               Driver: bridge                    
Name: ens2f1               Driver: ixgbe      [Supported by ZC]
Name: ens3f1               Driver: ixgbe      [Supported by ZC]

Command used to run disk2n
=========================
# /usr/local/bin/disk2n  -m playpcap.txt -i ens2f0 -I 420 -O -g -C 1024 -b 2048 -c 1 -w 2 -S 3 -v

**Comment by cardigliano** [comment]
Please note that pf_ringcfg is reporting that ixgbe interfaces are "Supported" but not "Running", did you try reconfiguring the ixgbe ZC driver?

**Comment by mdiqbalahmad** [comment]
No i did not reconfigured it. How do i reconfigure it?

I see below command to reconfigure it:
 pf_ringcfg --configure-driver ixgbe --rss-queues 1

What should be the optimum value for rss-queues  for using disk2n at 10Gbps?

**Comment by mdiqbalahmad** [comment]
I tried as below: but still ixgbe not showing as "Running"

Dmesg output is here:
-----------------------------------------
[dmesg-after-reconfigure.txt](https://github.com/ntop/PF_RING/files/4109698/dmesg-after-reconfigure.txt)

 pf_ringcfg --configure-driver ixgbe --rss-queues 1
[>] Configuring PF_RING
[>] Configuring hugepages
[>] Detecting interfaces using ixgbe
ens2f0
ens3f0
ens2f1
ens3f1
[>] Configuring ixgbe driver with 1 RSS queues
[>] Restarting PF_RING
[>] Configuration completed
[root@flyingrhel5 ~]# 
[root@flyingrhel5 ~]# pf_ringcfg --list-interfaces
Name: enp3s0f0             Driver: bnx2                      
Name: enp4s0f0             Driver: bnx2                      
Name: enp3s0f1             Driver: bnx2                      
Name: enp4s0f1             Driver: bnx2                      
Name: ens2f0               Driver: ixgbe      [Supported by ZC]
Name: ens3f0               Driver: ixgbe      [Supported by ZC]
Name: virbr0-nic           Driver: tun                       
Name: virbr0               Driver: bridge                    
Name: ens2f1               Driver: ixgbe      [Supported by ZC]
Name: ens3f1               Driver: ixgbe      [Supported by ZC]


Kernel version:
# uname -a
Linux flyingrhel5 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mdiqbalahmad** [comment]
I have a question:
when I install  "yum install pfring-drivers-zc-dkms" i seethe packages to be installed are as below

---> Package e1000e-zc.noarch 0:3.4.0.2.2813-dkms will be installed
---> Package i40e-zc.noarch 0:2.4.6.2813-dkms will be installed
---> Package igb-zc.noarch 0:5.3.5.18.2813-dkms will be installed
---> Package ixgbevf-zc.noarch 0:4.5.1.2813-dkms will be installed

It installs ixgbevf-zc drivers. What is the path where .ko module is installed? Do we need to use ixgbevf-zc or ixgbe drivers?

**Comment by cardigliano** [comment]
What you need is ixgbe (ixgbevf is for Virtual Functions). The .ko module is compiled during installation by dkms and installed in places like /lib/modules/<kernel version>/updates/dkms/ixgbe_zc.ko, please use "updatedb && locate ixgbe_zc.ko" to find it

**Comment by mdiqbalahmad** [comment]
Thanks,
I manually downloaded the ixgbe_zc package and installed it. After inserting this zc kernel module pfring_zc was working.
