### ISSUE TITLE
Info on Disk2n throughput

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#548]
Hi,

I need to understand the mechanism in which disk2n works, as I see the difference in throughput calculated over a interval of 1 minute at my application and the rate at which disk2n sends traffic(from pcaps).

I send traffic from disk2n at 2000Mbps and at my application when I calculate the throughput, taking 1 minute statistics. I see a difference of 160Mbps. There is no drops at the interface or at application as the count of packets sent by disk2n and received by my application are exactly same.

Is there any delay between reading/sending between consecutive pcaps in the list of pcaps?
Even if the delay is of few milliseconds, I need this information. I am doing bench-marking for my application.

To send traffic, I am using command:
/usr/local/bin/disk2n  -m /root//gentraffic-2000m.txt -i zc:ens3f0 -I 2720 -g -C 1024 -b 2048 -c 1 -w 2 -S 3 -v -O

gentraffic-2000m.txt  file has list of 123 pcaps(size 23MB) which runs in loop.

# head /root/dpi_data_bristal-lessurl/gentraffic-2000m.txt
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap
/root/gtp-session-pdu-100.pcap

-Iqbal

**Comment by cardigliano** [comment]
What is the number of packets sent in 1 minutes? I am trying to figure out if we can correlate that 160Mbps with the packet overhead on the wire (crc, ifg, etc).

**Comment by mdiqbalahmad** [comment]
Hi Alfredo,

Total packets sent/received per minute is close to 29411775

-Iqbal

**Comment by cardigliano** [comment]
With ~30Mppm (~500Kpps), if your application does not account 24 bytes per packet of overhead (crc, IFG, preamble), there is a difference of ~100 Mbps (24*8*500K), that *could* explain what you are seeing. Could you double check?
