### ISSUE TITLE
Bug Debian package in repository ntop

### ISSUE THREAD

**Issue by mahdi1001** [ntop/PF_RING#55]
2 notice in debian 8:
1- root@Linux:~# apt-cache show pfring
Package: pfring
Priority: optional
Section: free
Installed-Size: 6970
Maintainer: Luca Deri deri@ntop.org
Architecture: amd64
Version: 6.1.1-360
Depends: linux-image-3.16.0-4-amd64, linux-headers-3.16.0-4-amd64, pfring-dkms
Filename: x64/./pfring_6.1.1-360_amd64.deb
Size: 600214
MD5sum: 5ed5a5a3414b968b802529e3ee34cbb0
SHA1: fc6dd6f956b6b38bdbffe361513ae0cc6297fc5c
SHA256: a395bb0f711066bdbf6173a17908e752fd2bb8d1fc552506ae5eaa6f06b38579
SHA512: 2896254cc77ff6f2e8f530141328d81a0358226fae5a082773853d22f61f02981287e8b23b51fedf7c25bdc718f2bf8adf2a7ea8e4b5107b40dcd781bad49ec4
Description: PF_RING (http://www.ntop.org/pf_ring/)
Description-md5: d2bddd78fd0ccfc52efb0cdaee91b219

Question: why this path depends to linux-image-3.16.0-4-amd64, linux-headers-3.16.0-4-amd64??
in ubuntu olny depend to pfring-dkms and that's OK. but in debian if change debian kernel is problem with linux-image-3.16.0-4-amd64, linux-headers-3.16.0-4-amd64.

uname -a : 
Linux Linux 3.16.0-4+imq-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5.1 (2015-11-17) x86_64 GNU/Linux

2- I try to install pfring-drivers-zc-dkms :
                    root@Linux:~# apt-get install pfring-drivers-zc-dkms  
                    Reading package lists... Done
                    Building dependency tree  
                    Reading state information... Done
                    E: Unable to locate package pfring-drivers-zc-dkms

**Comment by mahdi1001** [comment]
No idea?

**Comment by lucaderi** [comment]
I have fixed it in the latest version

dpkg --show-deps pfring_6.3.0-378_amd64.deb
dpkg: error: unknown option --show-deps

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
deri@debian 205> dpkg -I pfring_6.3.0-378_amd64.deb
 new debian package, version 2.0.
 size 599334 bytes: control archive=1550 bytes.
       0 bytes,     0 lines      conffiles  
     309 bytes,     9 lines      control  
    1413 bytes,    23 lines      md5sums  
     470 bytes,    15 lines   \*  postinst             #!/bin/sh
     165 bytes,    10 lines   \*  postrm               #!/bin/sh
      20 bytes,     4 lines   \*  preinst              #!/bin/sh
      44 bytes,     4 lines   \*  prerm                #!/bin/sh
 Package: pfring
 Version: 6.3.0-378
 Architecture: amd64
 Maintainer: Luca Deri deri@ntop.org
 Installed-Size: 6970
 Depends: pfring-dkms (= 6.3.0)
 Section: free
 Priority: optional
 Description: PF_RING (http://www.ntop.org/pf_ring/) [dev:863a7342389117a897a754f6ab1c9e614630fd74 (Tue Dec 1 00:14:16 2015 +0100)]

**Comment by ghost** [comment]
Your pfring deb won't install because pfring-dkms is not installed,
and of course, pfring-dkms isn't in the repos,
and of course, I actually built pfring from the repos, and of course, your nprobe software doesn't see it's installed and in the kernel modules.

**Comment by cardigliano** [comment]
@ajzimme what repo are you using? Please provide the installation steps you followed.
