### ISSUE TITLE
Question about FT config

### ISSUE THREAD

**Issue by CyberTaoFlow** [ntop/PF_RING#550]
Hi I had a few questions and points I wanted to confirm.

1. I wanted to confirm that specifying a port in the ft conf is not supported?
like:

    tcp/902 = 128

instead a custom l7 app would need to be added to ndpi and then ndpi recompiled?  

2.  Also the case for unknown application is intended to be handled by 
  tcp = ###
  udp = ### 
  rather than 
  unknown = ###

3. The time based configuration is only available globally? ie:

   flow_idle_timeout = 30
   flow_lifetime_timeout = 120

Just to confirm the first (idle) is applied after activity ceases on a given flow while lifetime timeout will evict flows from the tracking table regardless of activity after the interval?

it would be cool if one could specify time or packet count based shunt rules.   

Another cool feature would be if you could somehow cleanly truncate the payloads  for a given flow beyond the l3 and l4 header which could still permit calculations like Producer Consumer Ratio (using ip len header) to work for shunted flows providing a kind of hybrid shunt.  Im calculating PCR values (with Zeek) using IP Len because of issues using seq numbers caused by the sequence space wrapping.

Perhaps packet checksums would be  rewritten when truncated or just not checked in the receiving application..... Or am I wrong in thinking the reason shunting is desirable is really the extra load around the uninteresting payload are while the l3 and l4 headers still provide useful connection metadata and would not be that much overhead.

**Comment by cardigliano** [comment]
> Hi I had a few questions and points I wanted to confirm.
> 
> 1. I wanted to confirm that specifying a port in the ft conf is not supported?
>    like:
>    tcp/902 = 128
> 
> instead a custom l7 app would need to be added to ndpi and then ndpi recompiled?

This is supported by defining custom L7 protocols (e.g. based on ip or hostname) using the standard nDPI protocols file (https://github.com/ntop/nDPI/blob/dev/example/protos.txt) and providing the file path to FT by setting the PF_RING_FT_PROTOCOLS environment variable. No need to recompile nDPI.

> 1. Also the case for unknown application is intended to be handled by
>    tcp = ###
>    udp = ###
>    rather than
>    unknown = ###

This should work already

> 2. The time based configuration is only available globally? ie:
>    flow_idle_timeout = 30
>    flow_lifetime_timeout = 120

Those are global settings.

> Just to confirm the first (idle) is applied after activity ceases on a given flow while lifetime timeout will evict flows from the tracking table regardless of activity after the interval?

Correct
 
> it would be cool if one could specify time or packet count based shunt rules.

Only the number of packets it supported now, please open a new ticket for this feature.

> Another cool feature would be if you could somehow cleanly truncate the payloads for a given flow beyond the l3 and l4 header which could still permit calculations like Producer Consumer Ratio (using ip len header) to work for shunted flows providing a kind of hybrid shunt. Im calculating PCR values (with Zeek) using IP Len because of issues using seq numbers caused by the sequence space wrapping.

Packet payload can be truncated by using the packet capture API (PF_RING), I am not sure I got what you need in FT exactly.
 
> Perhaps packet checksums would be rewritten when truncated or just not checked in the receiving application..... Or am I wrong in thinking the reason shunting is desirable is really the extra load around the uninteresting payload are while the l3 and l4 headers still provide useful connection metadata and would not be that much overhead.

I guess you mean slicing instead of shunting
