### ISSUE TITLE
Disk2n for Napatech card 40Gbps

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#551]
Hi,

We have 1.6 TB of pcaps and want to use disk2n to replay it using Napatech card at 40Gbps.

Does disk2n supports Napatech smart NIC?

If it does not supports then Which Intel NIC (With QSFP+ to connect to another Napatech card) do you recommend for sending 40Gbps traffic using disk2n?

What are the server configuration do you suggest for sending 40Gbps traffic using disk2n. 
Eg.How many SSD(Raid 0)? What IOPS?
     How much RAM?
    What license we need to take for pfring ZC and disk2n?

-Iqbal

**Comment by cardigliano** [comment]
@mdiqbalahmad disk2n supports all adapters supported by PF_RING, including Intel (XL710 at 40G) and Napatech. This said, the ability to transmit traffic from PCAP at 40G depends on the avg packet size as disk2n uses a single core for transmitting traffic, and can work well up to 10-20 Mpps depending on hw (cpu, memory bandwidth, etc). A 4-core 3Ghz CPU is enough, with enough memory modules to fill all CPU channels (e.g. 4x8GB is enough on a Xeon E5).
As of the storage configuration, if you have a storage which is fast enough to record 40Gbps, it is usually also able to replay at that rate (read speed is usually higher than write speed). If you are using SSDs you probably need ~10-16 disks (depending on the read speed), as you need a total of ~5GB/s.
As of the license, you need "PF_RING ZC" for "Intel" of "FPGA" according to the adapter, and "disk2n"
