### ISSUE TITLE
@mdiqbalahmad disk2n What partition to use SSD

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#552]
Hi,

We are going ahead with 6 SSD for 30Gbps traffic(average packet size id 570Bytes). Our question is: can we have these( 6 SSD x Raid0) as data partition or these SSD needs to be as "/" partition?

-Iqbal

@mdiqbalahmad disk2n supports all adapters supported by PF_RING, including Intel (XL710 at 40G) and Napatech. This said, the ability to transmit traffic from PCAP at 40G depends on the avg packet size as disk2n uses a single core for transmitting traffic, and can work well up to 10-20 Mpps depending on hw (cpu, memory bandwidth, etc). A 4-core 3Ghz CPU is enough, with enough memory modules to fill all CPU channels (e.g. 4x8GB is enough on a Xeon E5).
As of the storage configuration, if you have a storage which is fast enough to record 40Gbps, it is usually also able to replay at that rate (read speed is usually higher than write speed). If you are using SSDs you probably need ~10-16 disks (depending on the read speed), as you need a total of ~5GB/s.
As of the license, you need "PF_RING ZC" for "Intel" of "FPGA" according to the adapter, and "disk2n"

_Originally posted by @cardigliano in https://github.com/ntop/PF_RING/issues/551#issuecomment-581953121_

**Comment by cardigliano** [comment]
You can definitely use a data partition, that is the recommended configuration actually.
