### ISSUE TITLE
Commented out sed command in Makefile breaks igb dkms based build

### ISSUE THREAD

**Issue by mzpqnxow** [ntop/PF_RING#553]
Please see: https://github.com/ntop/PF_RING/blob/dev/drivers/intel/Makefile.dkms.igb.in

For some reason, the `sed` command is commented out in the `add` target:

```
	#sed -i -e 's|DRIVER_NAME=@IGB@|DRIVER_NAME=@IGB@_zc|g' /usr/src/@IGB@-zc-@IGB_VERSION@.@REVISION@/Makefile
```

This causes `make -f Makefile.dkms.igb.in` to fail because the `@IGB@` doesn't get replaced, causing various commands to search for files by name that still contain the literal `@IGB@`

When I uncomment the line, it properly replaces the literal with igb and then works as expected

Is this a mistake? Should it be uncommented? I don't see how it would work without it

**Comment by mzpqnxow** [comment]
I sent in #554 as a PR which fixes this for each Intel device .. curiously, this style (using sed to replace a fixed @<DEVICE>@ string) is present in all of the Makefiles except the Intel ones..

**Comment by cardigliano** [comment]
Closing this as #554 seems it is not required
