### ISSUE TITLE
Older versions of packages not available on apt-stable channel

### ISSUE THREAD

**Issue by tadams42** [ntop/PF_RING#556]
In my environment it is critical to pin dependencies for each release we make and test that release with exact versions of OS and packages we depened on.

We'd been relying on [apt-stable](http://packages.ntop.org/apt-stable/) chanel for `pfring` and `ndpi` packages and locked our dependencies to `pfring == 7.4.0` and `ndpi == 3.0.0`. 

With releases of new pfring and ndpi (`7.6.0` i `3.2.0`) our new builds fail, but also tests for older builds are no longer reproducible because we suddenly can't install `pfring == 7.4.0` and `ndpi == 3.0.0`: these packages no longer exist.

Is there any chance that [apt-stable](http://packages.ntop.org/apt-stable/) could maintain older versions of packages that are built there? 

This is standard practice for other Ubuntu PPA-s and also a standard practice for package repositories in general. 

No matter the standard practices, I hope I'd also shown specific use case that illustrates why would this matter. 

Also: repo doesn't have to keep older build versions, ie. we wouldn't need all older builds for ie. `7.4.0`, only the latest `7.4.0`, and so on.

thnx

**Comment by cardigliano** [comment]
@tadams42 we only keep latest stable and dev packages at the moment as we do nto support older versions, however I understand that keeping latest package for older releases would be helpful, we will discuss this internally. I am wondering if it makes more sense for you to keep an internal repository with the exact version/revision which has been tested with your application.

**Comment by tadams42** [comment]
@cardigliano, sorry for late reply... yes, it totally makes sense to have internal copy of dependencies. And we did: using mirror of [apt-stable](http://packages.ntop.org/apt-stable/) via [apt-mirror](https://github.com/apt-mirror/apt-mirror).

End result of mirroring is that when you pulled older versions out, they automatically disappeared from our mirrored repo too. Not the best way to do the deps backup on our side, I know :-D.

Anyway, I totally understand you not wanting to support older versions of software, but does that have to exclude providing binaries for older, unsupported versions?

Much appreciate you guys considering this request, and thanks for previous quick reply.

**Comment by tadams42** [comment]
@cardigliano I ended up switching to new version of pfring/ndpi anyway and also fixed my dependency freezing procedure.
