### ISSUE TITLE
Segmentation fault when enable PRINT_NDPI_INFO of ftflow_pcap

### ISSUE THREAD

**Issue by annp1987** [ntop/PF_RING#557]
I tried to enable PRINT_NDPI_INFO of ftflow_pcap, then I got segmentation fault.
I saw ndpi_flow2json encounter segmentation fault with HTTP.

**Comment by cardigliano** [comment]
@annp1987 this was due to some missing NULL string check in the exported metadata, I pushed a fix for this. Please update ndpi (if you are using packages, a new one will be available later today).

**Comment by annp1987** [comment]
@cardigliano : thank you for fixing it.
