### ISSUE TITLE
ndpi-dev package missing from apt-stable

### ISSUE THREAD

**Issue by tadams42** [ntop/PF_RING#558]
Was trying to do something like this:

```C
#include <ndpi/ndpi_api.h>

// ... 

struct ndpi_detection_module_struct *ndpi = pfring_ft_get_ndpi_handle(ft);
pfring_ft_flow_value *v = pfring_ft_flow_get_value(flow);
char* category_name = ndpi_category_get_name(ndpi, v->l7_protocol.category);

```

and it doesn't compile since I haven't got `ndpi/ndpi_api.h`... 

One way to get it is to install `ndpi-dev` which is only available from unstable repo. I would like to avoid that since I'm pulling other packages from `apt-stable`. Also, versions in stable and unstable differ, so that would be concern preventing me to mix those two sources.

**Comment by tadams42** [comment]
I ended up taking headers from nDPI source tree, `3.2-stable` branch, and embedding them into my own source tree. Would prefer having an external package to depend on, but it is not a deal breaker.

**Comment by cardigliano** [comment]
@tadams42 we will add the -dev package to the stable asap

**Comment by cardigliano** [comment]
Added to the stable
