### ISSUE TITLE
ifindex_map[] exhaustion

### ISSUE THREAD

**Issue by Nieuwejaar** [ntop/PF_RING#559]
If a device doesn't have an entry in `ifindex_map[]`,  `pf_ring.c:ring_notifier()` will attempt to allocate one every time it is called.  This is true even when the device is being unregistered.  When adding and removing a bridge, we will see something like:

```
[ 1300.881077] [PF_RING] foo: NETDEV_POST_INIT Type=1 IfIndex=1282 Ptr=d6e86000 Namespace=c0a24a80 Addr=000000000000
[ 1300.893204] [PF_RING] foo: NETDEV_REGISTER Type=1 IfIndex=1282 Ptr=d6e86000 Namespace=c0a24a80 Addr=000000000000
[ 1300.903774] [PF_RING] ring_notifier:8415 indirect mapped ifindex 1282 to 9
[ 1309.851714] [PF_RING] foo: NETDEV_UNREGISTER Type=1 IfIndex=1282 Ptr=d6e86000 Namespace=c0a24a80 Addr=000000000000
[ 1309.862044] [PF_RING] ring_notifier:8449 unmapped ifindex 1282 at 9
[ 1310.040959] [PF_RING] foo: NETDEV_UNREGISTER_FINAL Type=1 IfIndex=1282 Ptr=d6e86000 Namespace=c0a24a80 Addr=000000000000
[ 1310.124388] [PF_RING] ring_notifier:8415 indirect mapped ifindex 1282 to 9
```

Even though the bridge has been deleted, it is consuming a slot incorrectly allocated during `NETDEV_UNREGISTER_FINAL`.

The attached patch should fix the problem.

[ifindex.txt](https://github.com/ntop/PF_RING/files/4283177/ifindex.txt)

**Comment by cardigliano** [comment]
Fixed. Thank you
