### ISSUE TITLE
Pfcount seems to not be reading correctly from NIC queues

### ISSUE THREAD

**Issue by igorribeiroduarte** [ntop/PF_RING#563]
I'm trying to use pfcount to read from ixgbe queues on a machine with 8 queues and 56 logical cores, but when I run `pfcount -i INTERFACE@queue` the only queues which seems to be receiving traffic are queues 1 and 33, with both receiving a full copy of the traffic. All the other queues seems to be ignored by pfring.
But, when I check ethtool -S $INTERFACE I can see traffic in 8 queues, and no traffic on queue 33 at all, which seems to be right, since only 8 queues are configured.

My adapter Model: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (rev 01)
Output from /proc/net/pf_ring/dev/enp1s0f1/info:
``` interface info:
Name:         enp1s0f1
Index:        3
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  2
TX Queues:    8
RX Queues:    8 
```

**Comment by cardigliano** [comment]
@igorribeiroduarte please also specify the pf_ring version you are using (from /proc/net/pf_ring/info)

**Comment by cardigliano** [comment]
A couple of fixes and improvements have been pushed, a new nightly build will be available soon. Please test it and let us know. Thank you.

**Comment by igorribeiroduarte** [comment]
Thank you. My pfring version is `7.6.0-stable:166c80cf3ee6cb6614ef0e59f7a0c26c218176f6`

**Comment by igorribeiroduarte** [comment]
Everything's working fine now. Thank you.
