### ISSUE TITLE
if I need encrypt network packets can PD_RING Kernel help me in it? 

### ISSUE THREAD

**Issue by BugsBountyHunter** [ntop/PF_RING#564]

**Comment by cardigliano** [comment]
What kind of encryption do you need?
(PF_RING does not currently provide encryption)

**Comment by BugsBountyHunter** [comment]
I just try to create a network module to encrypt/decrypt network packet I was not interested in which any kind of encrypt I just need to prove the concept.

**Comment by cardigliano** [comment]
@DEV-A7med pf_ring is a kernel module for raw packet capture/transmission, attaching to the sniffing layer in the linux stack. It does not act as a bridge for the linux kernel, thus you cannot use it to for transparent encryption/decryption for traffic from/to the host.

**Comment by cardigliano** [comment]
Note: if you use kernel-bypass drivers (ZC), combined with the "stack" module, you can actually act as a bridge (with encryption/decryption in a zc-based userspace application)
