### ISSUE TITLE
SR-IOV setup with XL710 (intel 40G)

### ISSUE THREAD

**Issue by tsivakca67** [ntop/PF_RING#566]
We would want to receive packets in XL710 and distribute the packets based on ntuple to 
different VF’s. Then, We would want to use PF_RING and  i40evf module in the guest vm’s to further process the packets. Pls note that we do not want to steer the traffic based on mac or vlan to different VF’s.
Let me know the steps needed to achieve this.

**Comment by cardigliano** [comment]
@tsivakca67 please note that we do not have a i40evf ZC driver at the moment, you should keep using the vanilla i40e driver. You can still use the PF_RING kernel module (in the VM). As of steering to the VFs, there is no special instructions for PF_RING, you can keep using what is supported by the adapter with ethtool.

**Comment by tsivakca67** [comment]
Thank you for the information provided.
