### ISSUE TITLE
Configure disk2n to send traffic in Million Packets per second

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#567]
Hi,

Currently I am using disk2n to replay the pcaps. using below command

/usr/local/bin/disk2n -m /root/pcap-list.txt -i nt:0 -I 505 -C 65535 -b 20480 -U -c 1 -w 3 -S 5 -O -v

I need to send the traffic at 1.2 Mpps, instead of configuring the throughput. Is there any way to achieve this. I had a look at disk2n documentation and did not find any options for the same.

-Iqbal

**Comment by cardigliano** [comment]
Did you check the inter-packet-time option? You should be able to tune the rate changing this parameter:
[--inter-packet-time|-I] <nsec>

**Comment by mdiqbalahmad** [comment]
yes I used -I 505  as in below command. This is for time difference between packets in ns.
/usr/local/bin/disk2n -m /root/pcap-list.txt -i nt:0 -I 505 -C 65535 -b 20480 -U -c 1 -w 3 -S 5 -O -v

How do I configure Mpps?

**Comment by cardigliano** [comment]
By tuning the inter-packet time you should be also able to tune the rate (there is no option to directly specify the pps atm)

**Comment by mdiqbalahmad** [comment]
Thanks.
