### ISSUE TITLE
Pfcount is receiving all the traffic on queue 1, despite the fact that my traffic is divided into 6 queues

### ISSUE THREAD

**Issue by igorribeiroduarte** [ntop/PF_RING#568]
I'm having a problem with pf_ring after my kernel updated to 4.15.0-91 version.
My traffic is divided into 6 queues, configured using ethtool and the output from `ethtool -S $interface` shows that I have traffic in all the 6 queues. But when I try to use pfcount to process this traffic, everything seems to be going to queue 1

**My system info:**
pfring version: 7.6.0-stable:166c80cf3ee6cb6614ef0e59f7a0c26c218176f6
interface model: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2
pfcount command: `pfcount -i $INTERFACE@$QUEUE_ID`
Command used to check if there's traffic incoming in all the queues: `sudo ethtool -S $INTERFACE | grep rx_queue | less`
Command used to set number of queues: `sudo ethtool -X $INTERFACE equal 6`

**Comment by cardigliano** [comment]
@igorribeiroduarte please note that the pf_ring revision you are using is not the latest one, a patch for RSS has been pushed a few days ago (https://github.com/ntop/PF_RING/commit/0e07b27c0d593174584de79e273470366a91d307)
Please update and let us know. Thank you.

**Comment by igorribeiroduarte** [comment]
Sorry, I thought this was the last version.
It's working fine now. Thank you.

**Comment by cardigliano** [comment]
Great. Thank you.
