### ISSUE TITLE
pfring_zc_create_cluster arguments changed, breaking compatibility

### ISSUE THREAD

**Issue by andrewbeard** [ntop/PF_RING#569]
It seems like at some point the arguments to the pfring_zc_create_cluster function were modified, adding an additional flags parameter. This breaks existing applications (like zmap) that build against pf_ring ZC. In addition the API documentation does not seem to have been updated, showing only the old prototype:
https://www.ntop.org/guides/pf_ring_api/pfring__zc_8h.html#ae72b4662fcd2463633ddb6527b67ca3d

Could the documentation be updated and an inline compatibility stub that calls the function with flags set to default (0?) be added?

**Comment by cardigliano** [comment]
@andrewbeard please note that the API documentation has been moved to https://www.ntop.org/guides/pf_ring/api/ , we are going to remove the old documentation (the one in your like) now. Could you provide an example of how you would implement this compatibility stub? Thank you.

**Comment by andrewbeard** [comment]
Sorry, I realized after the fact the kind of function overloading I was think of can only be done in C++, not C. It does appear that this change has also made it to the 7.4.0-stable branch, breaking compatibility within the same stable release stream, though.

**Comment by cardigliano** [comment]
Yeah, unfortunately we cannot use overloading, and we also wanted to avoid duplicating the function complicating the API. We didn't think this was an headache for other projects (we updated the API in our projects). Too late to come back at this point..
