### ISSUE TITLE
Can't receive alert in suricata, without any errors 

### ISSUE THREAD

**Issue by ellenzhu** [ntop/PF_RING#571]
Hi,
I am using the lastest version of pf_ring zc. There are no errors when compiling and running zbalance_ipc, also suricata is running successfully. I can't see any alert in suricata, while I notice many alerts when using pfring with standard mode. 
I don't have an license, but it's free in 5 minutes. I think it should have alerts in the first 5 minutes.
ps:
3.10.0-693.21.1.el7.x86_64 is the kernel

**Comment by cardigliano** [comment]
Did you check statistics for received packets in Suricata? Is it processing the expected number of packets? Is it extracting traffic metadata, besides the fact that it is not exporting alerts? Please provide more details in order to figure where data is getting lost.

**Comment by ellenzhu** [comment]
Thanks. My problem is similar with issue[#573](https://github.com/ntop/PF_RING/issues/573)
