### ISSUE TITLE
pfring_zc_ipc_attach_queue error in vm

### ISSUE THREAD

**Issue by tsivakca67** [ntop/PF_RING#574]
Hi,
  I am executing the programs in examples_zc.
Step 1: Starting up guest and specifying the monitor socket as /tmp/qmp4
Step 2: Running the zpipeline_ipc program on the Host 
./zpipeline_ipc -i zc:psdeth0%0 -o zc:psdeth1%1 -c 100 -n 2 -f -Q /tmp/qmp4
Step 3: Run zcount_ipc on the guest machine
./zbounce_ipc -c 99 -i 0 -o 1 -g 3 -u
I am getting the following error at pfring_zc_ipc_attach_queue error
pfring_zc_ipc_attach_queue error [No buffer space available] Please check that cluster 99 is running

**Comment by tsivakca67** [comment]
Correcting the typo error:
Step 2: Running the zpipeline_ipc program on the Host
./zpipeline_ipc -i zc:psdeth0%0 -o zc:psdeth1%1 -c 100 -n 2 -f -Q /tmp/qmp4
Step 3: Run zbounce_ipc on the guest machine
./zbounce_ipc -c 100 -i 0 -o 1 -g 3 -u
Getting following error while running bounce_ipc
pfring_zc_ipc_attach_queue error [No buffer space available] Please check that cluster 100 is running

**Comment by tsivakca67** [comment]
Looks like the problem is in opening /dev/uio0. Shall update once I resolve that issue.

**Comment by cardigliano** [comment]
Did you check https://github.com/ntop/PF_RING/issues/416 ?
What QEMU version are you running?

**Comment by tsivakca67** [comment]
QEMU emulator version 2.4.0, Copyright (c) 2003-2008 Fabrice Bellard.
I am able to get this working now.
dmesg output indicates that there is no memory for the pci device to be mapped.
Restarted the guest program and fired up the host program again and now the /dev/uio0 is getting created and we are able to successfully get the packets in the guest machine.
However, I am seeing some issues when I increase the cluster memory (unable to map more than 178MB). As suggested in #416 let me upgrade my qemu to 2.5 and check

**Comment by cardigliano** [comment]
Ok thank you for the update

**Comment by tsivakca67** [comment]
I have upgraded qemu to 2.5 and checked out. I am observing the same behavior.
Here are the steps to reproduce the issue.
1. Start a guest_vm with monitor socket set to qmp1
2. On the guest execute modprobe uio and insmod uio_ivshmem.ko
3. Start zbalance_ipc program on the host ./zbalance_ipc -I eth0 -c 99 -n 4 -Q /path/qmp1
4. Run zcount_ipc -I 0 -u -c 99  on the guestvm
(This works fine)
The file size in /dev/hugepages is
-rwxr-xr-x 1 root root 268435456 Apr 22 21:55 pfring_zc_99

The following is not working
increase the number of consumer queues to 16 in step 3.
./zbalance_ipc -I eth0 -c 99 -n 16 -Q /path/qmp1
The file size of /dev/hugepages/pfring_zc_99 is 
-rwxr-xr-x 1 root root 536870912 Apr 22 21:58 pfring_zc_99
 
Now execute
"count_ipc -i 0 -u -c 99" on the guest vm
we get the following error
pfring_zc_ipc_attach_queue error [No buffer space available] Please check that cluster 99 is running 

The dmesg output from the guest machine also indicates that it is no space while doing pci enumeration
[  152.551862] pci 0000:00:06.0: BAR 2: no space for [mem size 0x20000000 64bit pref] (failed case: n=16)

[ 3123.282566] pci 0000:00:06.0: BAR 2: assigned [mem 0xd0000000-0xdfffffff 64bit pref]
(passed case: n=4)

Now how do we setup the guest vm's when the cluster memory size is greater than 4G?

**Comment by cardigliano** [comment]
@tsivakca67 thank you for all the details. With QEMU 2.4 it was working up to 178MB, is this limit increased to 4G with QEMU 2.5? What is the max size you are able to use? Thank you.

**Comment by tsivakca67** [comment]
Hi,
Able to map in memory more than 4G by passing pci=nocrs in the guest machine and able to receive and send packets from the guest.
Thanks,
Siva

**Comment by cardigliano** [comment]
Great! Thank you for the update. Can we close this?
