### ISSUE TITLE
Starting PF_RING module: modinfo: ERROR: Module ixgbe-zc not found

### ISSUE THREAD

**Issue by sysxtem** [ntop/PF_RING#575]
[root@localhost ~]# systemctl status pf_ring -l
● pf_ring.service - PF_RING service
   Loaded: loaded (/usr/lib/systemd/system/pf_ring.service; disabled; vendor preset: disabled)
   Active: active (exited) since 五 2020-04-17 14:03:05 CST; 5s ago
  Process: 6201 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 6116 ExecStop=/usr/local/bin/pf_ringctl stop (code=exited, status=0/SUCCESS)
  Process: 6531 ExecStartPost=/bin/sh -c if [ -x /etc/pf_ring/post ]; then /etc/pf_ring/post; fi (code=exited, status=0/SUCCESS)
  Process: 6525 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 6273 ExecStart=/usr/local/bin/pf_ringctl start (code=exited, status=0/SUCCESS)
  Process: 6269 ExecStartPre=/bin/sh -c if [ -x /etc/pf_ring/pre ]; then /etc/pf_ring/pre; fi (code=exited, status=0/SUCCESS)
  Process: 6241 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) pf_ring StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 6273 (code=exited, status=0/SUCCESS)

4月 17 14:03:01 localhost systemd[1]: Starting PF_RING service...
4月 17 14:03:02 localhost pf_ringctl[6273]: Starting PF_RING module: modinfo: ERROR: Module ixgbe-zc not found.
4月 17 14:03:02 localhost pf_ringctl[6273]: Driver ixgbe-zc not available
4月 17 14:03:02 localhost pf_ringctl[6273]: /usr/local/bin/pf_ringctl:行327: lspci: Command not found
4月 17 14:03:05 localhost pf_ringctl[6273]: [  yes  ]
4月 17 14:03:05 localhost systemd[1]: Started PF_RING service.

**Comment by cardigliano** [comment]
What OS are you running?) Please install lspci (a dependency has been added lately).
Did you follow the instructions at https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html to configure pf_ring? Wizard or manual?

**Comment by sysxtem** [comment]
CentOS 7

**Comment by cardigliano** [comment]
Please try with an update, and follow https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html , it should work, otherwise contact us again. Thank you.

**Comment by dreamhighhd** [comment]
[root@xs-network-dpi src]# journalctl -u pf_ring -f
-- Logs begin at Mon 2021-12-27 19:03:02 CST. --
Jan 19 12:35:13 xs-network-dpi pf_ringctl[24987]: [  OK  ]
Jan 19 12:35:13 xs-network-dpi systemd[1]: Started PF_RING service.
Jan 19 13:22:45 xs-network-dpi systemd[1]: Stopping PF_RING service...
Jan 19 13:22:46 xs-network-dpi pf_ringctl[11026]: Stopping PF_RING module: [  OK  ]
Jan 19 13:22:46 xs-network-dpi systemd[1]: Stopped PF_RING service.
Jan 19 13:22:46 xs-network-dpi systemd[1]: Starting PF_RING service...
Jan 19 13:22:46 xs-network-dpi pf_ringctl[11115]: Starting PF_RING module: modinfo: ERROR: Module ixgbe-zc not found.
Jan 19 13:22:46 xs-network-dpi pf_ringctl[11115]: Driver ixgbe-zc not available
Jan 19 13:22:49 xs-network-dpi pf_ringctl[11115]: [  OK  ]
Jan 19 13:22:49 xs-network-dpi systemd[1]: Started PF_RING service.

**Comment by dreamhighhd** [comment]
[root@xs-network-dpi src]# lsmod |grep pf_ring
pf_ring               722460  6 
[root@xs-network-dpi src]# lsmod |grep ixgbe
ixgbe                 333244  0 
mdio                   14073  1 ixgbe
dca                    15130  1 ixgbe
ptp                    19231  2 ixgbe,e1000e

**Comment by dreamhighhd** [comment]
[root@xs-network-dpi src]# cat /proc/net/pf_ring/dev/enp2s0f0/info 
Name:         enp2s0f0
Index:        16
Address:      00:1B:21:B1:65:7B
Polling Mode: NAPI
Promisc:      Enabled
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  3
TX Queues:    12
RX Queues:    12
You have new mail in /var/spool/mail/root

**Comment by dreamhighhd** [comment]
[root@xs-network-dpi src]# lspci | grep Ethernet 
02:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
02:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
06:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection
07:00.0 Ethernet controller: Intel Corporation 82574L Gigabit Network Connection

**Comment by cardigliano** [comment]
@dreamhighhd what OS are you running? What is the pfring version?

**Comment by dreamhighhd** [comment]
CentOS Linux release 7.9.2009 (Core)
[root@xs-network-dpi ~]# rpm -qa|grep pfring
pfring-dkms-8.0.0.7172-7172.noarch
pfring-drivers-zc-dkms-8.0.0-7172.noarch
pfring-8.0.0-7172.x86_64

**Comment by dreamhighhd** [comment]
Hello, I need the support of ntopng. I have about 5g image data received from nprobe and then pushed to ntopng. The image data contains the data of three VLANs. I distinguish services by creating sub interfaces and configuring corresponding VLANs for each interface, but now the platform data is inaccurate.

**Comment by dreamhighhd** [comment]
Is there any solution to optimize

**Comment by dreamhighhd** [comment]
pf_ The ring driver has been installed, but the effect is not as good as before. The data displayed on the ntopng platform is very small, and one interface for each VLAN cannot be displayed. I don't know if it's a configuration problem.

**Comment by cardigliano** [comment]
Are you loosing traffic on nProbe? Could you check the nProbe statistics for packet drops?

**Comment by dreamhighhd** [comment]
Flow comparison on network port:

                                                    VLAN123 VLAN234 VLAN345

Real traffic of service switch:    2.8G            1.4G         1.4G

Traffic received by the server:  2.7G            1.4G          1.4G

Ntopng displayed flow:              700M            1G         400M
