### ISSUE TITLE
Build failure on Debian Buster

### ISSUE THREAD

**Issue by zinosat** [ntop/PF_RING#576]
Hi,
I've tried to recompile the deb packages inside a simple container based on Debian Buster (https://pastebin.com/rfzh3ALj)

After cloning the repo, I do the following:

    cd package/debian
    ./configure
    make

the build fails with the following error:

DKMS: mkdeb completed.
Moving built files to /var/lib/dkms/fm10k-zc/0.23.5.2958/deb...mv: cannot stat '/tmp/dkms.XiJiJE/fm10k-zc-dkms_0.23.5.2958_amd64.deb': No such file or directory
(bad exit status: 1)
Cleaning up temporary files...
cp /var/lib/dkms/fm10k-zc/*/deb/*.deb .
cp: cannot stat '/var/lib/dkms/fm10k-zc/*/deb/*.deb': No such file or directory
make[1]: *** [Makefile:37: dkms-deb] Error 1
make[1]: Leaving directory '/home/zino/pf_ring/drivers/intel'
make: *** [Makefile:25: pre-zc] Error 2

complete log can be found here: https://pastebin.com/CdB24tEC

I've searched the web and found https://github.com/al177/esp8089/issues/32 which suggests a patch against dkms which fixes the issue. I haven't had the time to see if the Debian BTS for dkms is aware of this or provides a proper patch.

Anyway, once I apply the fix I get another failure, due to pfring.h not beign found while compiling userland/snort/pfring-daq-module which looks the same as https://lists.gt.net/ntop/misc/44970

checking for sfbpf_compile in -lsfbpf... yes
checking for redisCommand in -lhiredis... no
checking pfring.h usability... no
checking pfring.h presence... no
checking for pfring.h... no
configure: error: Could not find pfring.h!
make[1]: Entering directory '/home/zino/pf_ring/userland/snort/pfring-daq-module'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/zino/pf_ring/userland/snort/pfring-daq-module'
cp: cannot stat '/home/zino/pf_ring/package/ubuntu/../..//userland/snort/pfring-daq-module/.libs/daq_pfring.la': No such file or directory
cp: cannot stat '/home/zino/pf_ring/package/ubuntu/../..//userland/snort/pfring-daq-module/.libs/daq_pfring.so': No such file or directory

**Comment by cardigliano** [comment]
I confirm you need the dkms patch. That's s known bug.
As of the pfring.h error, this seems to be working for me, please make sure you have the PF_RING folder in your home (otherwise you need to pass the path to the snort daq configure, which is not supproted via package makefile)

**Comment by zinosat** [comment]
Hi Alfredo,
the source folder is already in my home folder.

it turns out that the problem was the name of the folder "pf_ring" instead of uppercase "PF_RING".
I spent some time trying to find out the issue: manually building inside "userland/lib" and then building the packages, _sometimes_, fixed the problem.

Thank you,
Davide

**Comment by cardigliano** [comment]
Thank you for the update
