### ISSUE TITLE
 During the 5 minute damo, the packet was suddenly not captured when capturing the packet

### ISSUE THREAD

**Issue by wangly2020** [ntop/PF_RING#580]
The VF function of pf_ring 7.6.0 in the vxlan environment.
Within 5 minutes, I use pfcount in zc mode to capture packets, and suddenly no data packets, only ARP packets. 
pfcount -i zc:ens5 -o test.pcap  
I use pfcount in normal mode to capture packets, It's OK.
[test.pcap.zip](https://github.com/ntop/PF_RING/files/4522816/test.pcap.zip)

**Comment by cardigliano** [comment]
@wangly2020 how are you steering traffic to the VF? Are you capturing traffic to/from the VM itself perhaps (the interface has an IP)? If you are able to capture ARP packets, it seems ZC capture itself is working, however please keep in mind that the network stack id disconnected as ZC is a kernel-bypass technology. Please provide more details. Thank you.

**Comment by wangly2020** [comment]
Yes, an IP address is configured on the collection interface.  After deleting the IP address, PF_RING packet capture is normal.
