### ISSUE TITLE
pfring_get_filtering_rule_stats() not implemented?

### ISSUE THREAD

**Issue by rjo** [ntop/PF_RING#583]
I'm brand new to pfring development and have been testing the examples. I found that pfring_get_filtering_rule_stats() always returns -1 and when I dug down I found that the function is actually not implemented as can be see in the [kernel implementation of ring_getsockopt()](https://github.com/ntop/PF_RING/blob/525ee03cd510d38a3446f66524c3d792a02442a8/kernel/pf_ring.c#L7664)

https://github.com/ntop/PF_RING/blob/525ee03cd510d38a3446f66524c3d792a02442a8/kernel/pf_ring.c#L7664

Since the examples go to the effort to demonstrate use of that function I wonder if I'm missing something.

Is there something I'm not understanding?

**Comment by cardigliano** [comment]
@rjo it seems this feature has never been implemented, if you want to contribute you are welcome!

**Comment by rjo** [comment]
thanks @cardigliano ... I might take a stab at that when I feel competent enough to do so!

**Comment by teoring** [comment]
I understand it's still not implemented and there is no way to find out whether any traffic hits the filter rule?
