### ISSUE TITLE
Does GRO impact the maximum packet length seen by pfring_recv()

### ISSUE THREAD

**Issue by rjo** [ntop/PF_RING#584]
I have network where GRO is enabled and we see packets greater than the length of a jumbo frame.  In the pfcount.c example I see the packet buffer being statically sized at 9000, which makes sense for a jumbo frame.

Would a pfring application ever see GRO influenced packets that exceeded the size of a jumbo frame?

**Comment by cardigliano** [comment]
@rjo PF_RING expects a snaplen to be configured as you've seen to limit the max packet size to capture. That is also used to determine the kernel buffer size. Besides this, we recommend to turn GRO off in the adapter (our service script does that already) as a traffic analysis application expects to see packets as they are on the wire.

**Comment by rjo** [comment]
great, thanks @cardigliano
