### ISSUE TITLE
Installation fails on Centos/Redhat 8 for ZC Intel Drivers

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#585]
Running:
Red Hat Enterprise Linux release 8.2 (Ootpa)
Kernel (latest):
Linux 4.18.0-193.el8.x86_64 x86_64

Error (installing from http://packages.ntop.org/centos/8/)

Loading new ixgbe-zc-5.5.3.2973 DKMS files...
Building for 4.18.0-193.el8.x86_64
Building initial module for 4.18.0-193.el8.x86_64
Error! Bad return status for module build on kernel: 4.18.0-193.el8.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.2973/build/make.log for more information.
warning: %post(ixgbe-zc-5.5.3.2973-dkms.noarch) scriptlet failed, exit status 10

Output of /var/lib/dkms/ixgbe-zc/5.5.3.2973/build/make.log:
[make.log](https://github.com/ntop/PF_RING/files/4603832/make.log)

Edit:

I downgraded this system to RedHat 8.1 (and it's kernel version  4.18.0-147.el8.x86_64) and the ZC driver is installing without errors again. So some change with 8.2 and it's kernel seems to be the culprit.

**Comment by cardigliano** [comment]
HI @Arislen, we officially support CentOS (8.1) which is currently running kernel 4.18.0-147, it seems that RH 8.2 is not running the same kernel, thus please wait a bit before updating.
