### ISSUE TITLE
Jumbo support in pfring zc on rhel 7

### ISSUE THREAD

**Issue by mdiqbalahmad** [ntop/PF_RING#590]
Hi,
Does pfring zc 7.6 supports jumbo frame for NIC
10Gb 2-port 560SPF+ Adaptor?

We use it On RHEL. What would be the process to enable jumboframe on pfring zc?

-Iqbal

**Comment by cardigliano** [comment]
This should be based on Intel X520, yes this is supported (we officially support CentOS, RH should also work)

**Comment by mdiqbalahmad** [comment]
Is there any extra config to enable jumbo frame in zc? Or it is taken care automatically?

**Comment by cardigliano** [comment]
The driver reads the MTU on the interface

**Comment by mdiqbalahmad** [comment]
Thanks

**Comment by mdiqbalahmad** [comment]
Is jumbo frame also supported in  pfring zc 7.5?

-Iqbal

**Comment by cardigliano** [comment]
Yes, however 7.5 is no longer supported, we recommend moving to 7.6 (stable) or 7.7 (dev)

**Comment by mdiqbalahmad** [comment]
Hi Alfredo,

As per this link:
https://support.hpe.com/hpesc/public/docDisplay?cc=ec&docId=emr_na-c03499286&lang=es-ec

HP Ethernet 10Gb 2-port 560SFP+ adapter is based on  Intel 82599 controller.

Can you please confirm that this NIC is certified by ntop for ZC 7.5.

-Iqbal

**Comment by cardigliano** [comment]
Yes, 82599 is supported
