### ISSUE TITLE
pfring-7.6.0 zc take up large memory

### ISSUE THREAD

**Issue by Onotoko** [ntop/PF_RING#591]
Hi there,
I faced the same problem with pfring_zc (7.6.0) when it takes up large memory but I don't know where is it.

![Image Pasted at 2020-5-27 15-29](https://user-images.githubusercontent.com/38826492/83002548-62d51a80-a037-11ea-83d7-c41650dca8ae.png)

I found a person had a same issue with me on https://www.reddit.com/r/linuxquestions/comments/f7iz9h/pfring_sh_make_taking_up_large_amounts_of_memory/

My question is: Does anyone know how can I fix it?

Thanks

**Comment by cardigliano** [comment]
@Onotoko what OS are you running? Did this happen during an installation or update?

**Comment by Onotoko** [comment]
@cardigliano,
I am using Centos 7
It happens after I updated  the kernel.

**Comment by cardigliano** [comment]
I was not able to find what is triggering this so far. Please provide the output of:

- yum list installed | grep pfring
- dkms status

Btw, how did you temporarily fix it? Did you kill those processes?

**Comment by Onotoko** [comment]
Hi @cardigliano,

![image](https://user-images.githubusercontent.com/38826492/83472848-61ca4000-a4b2-11ea-9b97-332e793082b1.png)

> how did you temporarily fix it

-> I have run to kill those processes many times, but after I killed it, it restarts again

**Comment by cardigliano** [comment]
@Onotoko any chance I can connect to this system and take a look?

**Comment by Onotoko** [comment]
@cardigliano, sorry you cannot connect to the system.

Any suggestion, I can check for you, btw It only happens after I installed it about 2-3 months

**Comment by cardigliano** [comment]
@Onotoko I have a few questions then:
- is /usr/src/pfring-7.6.0 empty?
- do you have other /usr/src/pfring-* folders? (did you migrate from other versions?)
- did you try removing the pfring-dkms package, deleting /usr/src/pfring-*, and reinstalling the package? What is strange is that it seems the package is already built and installed in dkms

**Comment by Onotoko** [comment]
Hi @cardigliano,

> is /usr/src/pfring-7.6.0 empty?

Yes

> do you have other /usr/src/pfring-* folders? (did you migrate from other versions?)

No

> did you try removing the pfring-dkms package, deleting /usr/src/pfring-*, and reinstalling the package

No

**Comment by cardigliano** [comment]
Please try with the last step, to figure out how to reproduce it

**Comment by Onotoko** [comment]
@cardigliano,

Because of this issue, I cannot fix it, so I removed all pfring-zc and dkms. So now I cannot reproduce it for you.

**Comment by Onotoko** [comment]
if you read the article https://www.reddit.com/r/linuxquestions/comments/f7iz9h/pfring_sh_make_taking_up_large_amounts_of_memory/, it may help you more idea about it

**Comment by oanhsaitec** [comment]
It was resolved. Thanks for your supporting

**Comment by Onotoko** [comment]
It was resolved. Thanks for your supporting
