### ISSUE TITLE
could not insert module /etc/pf_ring/kernel/3.10.0-957.10.1.el7.x86_64/i40e.ko: File exists

### ISSUE THREAD

**Issue by kothuri88** [ntop/PF_RING#592]
Hi,

I am trying to setup PF_ring and PF_ringZC

I see following error /var/log/messages after the server reboot 

Jun  1 11:38:16 [localhost] yum[7103]: Installed: PF_RING-ZC-i40e-3.10.0-957.10.1.el7.x86_64-7.5.0-1.el7.x86_64
Jun  1 11:38:39 [localhost] yum[7135]: Installed: PF_RING-3.10.0-957.10.1.el7.x86_64-7.5.0-3.el7.x86_64
Jun  1 11:42:05 [localhost] journal: [PF_RING] Cannot load module
Jun  1 11:42:05 [localhost] kernel: pf_ring: loading out-of-tree module taints kernel.
Jun  1 11:42:05 [localhost] kernel: pf_ring: module verification failed: signature and/or required key missing - tainting kernel
Jun  1 11:42:05 [localhost] kernel: [PF_RING] Welcome to PF_RING 7.5.0 ($Revision: unknown$)#012(C) 2004-17 ntop.org
Jun  1 11:42:05 [localhost] kernel: [PF_RING] Min # ring slots 409600
Jun  1 11:42:05 [localhost] kernel: [PF_RING] Slot version     17
Jun  1 11:42:05 [localhost] kernel: [PF_RING] Capture TX       No [RX only]
Jun  1 11:42:05 [localhost] kernel: [PF_RING] IP Defragment    Yes
Jun  1 11:42:05 [localhost] kernel: [PF_RING] pf_ring initialized correctly
Jun  1 11:42:06 [localhost] kernel: [PF_RING] Module unloaded
Jun  1 11:42:06 [localhost] kernel: [PF_RING] Welcome to PF_RING 7.5.0 ($Revision: unknown$)#012(C) 2004-17 ntop.org
Jun  1 11:42:06 [localhost] kernel: [PF_RING] Min # ring slots 409600
Jun  1 11:42:06 [localhost] kernel: [PF_RING] Slot version     17
Jun  1 11:42:06 [localhost] kernel: [PF_RING] Capture TX       No [RX only]
Jun  1 11:42:06 [localhost] kernel: [PF_RING] IP Defragment    Yes
Jun  1 11:42:06 [localhost] kernel: [PF_RING] pf_ring initialized correctly
Jun  1 11:42:06 [localhost] kernel: [PF_RING] removing dev=ens3f0 ifindex=3 (2)
Jun  1 11:42:06 [localhost] kernel: [PF_RING] removing dev=ens5f1 ifindex=9 (2)
Jun  1 11:42:06 [localhost] kernel: [PF_RING] removing dev=eno5 ifindex=6 (2)
Jun  1 11:42:06 [localhost] kernel: [PF_RING] removing dev=eno8 ifindex=16 (2)
Jun  1 11:42:07 [localhost] kernel: [PF_RING] removing dev=eno7 ifindex=14 (2)
Jun  1 11:42:07 [localhost] kernel: [PF_RING] removing dev=eno6 ifindex=12 (2)
Jun  1 11:42:07 [localhost] kernel: [PF_RING] removing dev=ens1f0 ifindex=13 (2)
Jun  1 11:42:07 [localhost] kernel: [PF_RING] removing dev=ens1f1 ifindex=15 (2)
Jun  1 11:42:07 [localhost] kernel: [PF_RING] removing dev=ens4f1 ifindex=18 (2)
Jun  1 11:42:07 [localhost] kernel: [PF_RING] removing dev=ens4f0 ifindex=17 (2)
Jun  1 11:42:07 [localhost] rhel-loadmodules: insmod: ERROR: could not insert module /etc/pf_ring/kernel/3.10.0-957.10.1.el7.x86_64/i40e.ko: File exists

it works well, if I manually remove and load the module, I can see bothNAPI/ZC, however after reboot only NAPI remains.

Name:         ens1f0
Index:        13
Address:      48:DF:37:A5:A0:10
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    4
RX Queues:    4

lsmod|grep i40e
i40e                  354807  0
ptp                    19231  3 igb,tg3,i40e

lsmod|grep -i pf
pf_ring              1246952  0

OS: RHEL 7.6 [3.10.0-957.10.1.el7.x86_64]

Thanks,
KK

**Comment by cardigliano** [comment]
Just to make sure: did you configure the i40e package according to the user's guide? 
Is the "insmod: ERROR: could not insert module" error triggered by the pfring systemd script? The script should unload i40e and dependencies before loading the module, and it should load i40e_zc actually.

**Comment by kothuri88** [comment]
Yes, the loading of module has the first line to remove and reconfigured :

Here  is the content of the script:

## This is to load i40e driver

#!/bin/bash -
# Auto-created in rpm installation, do no modify.

rmmod i40e
rmmod pf_ring

bash /etc/sysconfig/modules/ipprobe-pf_ring-3.10.0-957.10.1.el7.x86_64-7.5.0.modules

modprobe ptp
modprobe vxlan
modprobe configfs

insmod /etc/pf_ring/kernel/3.10.0-957.10.1.el7.x86_64/i40e.ko RSS=4,4,4,4

bash /etc/pf_ring/kernel/3.10.0-957.10.1.el7.x86_64/createhugepages.sh
bash /etc/pf_ring/kernel/3.10.0-957.10.1.el7.x86_64/loadModules_i40e.sh

**Comment by cardigliano** [comment]
Please try with modprobe -r i40e to make sure you unload all dependencies, however it is recommended to use our scripts as described at https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html

**Comment by kothuri88** [comment]
It works after I parsed modprobe -r i40e in the module script.  A much cleaner approach. 
Thank you.
