### ISSUE TITLE
Add revision to pfring-drivers-zc-dkms package

### ISSUE THREAD

**Issue by alessio-pascolini** [ntop/PF_RING#595]
I used to mirror the apt-stable repository of ntop in order to have a local one. 
After last sync I discovered that the package pfring-drivers-zc-dkms has not been updated, but its hash is changed in file Packages.
This happens because mirroring software has checked the version of package and has not downloaded it again.
This involves in hash mismatch when I try to install package with apt-get in ubuntu machine using my local repository.
Usually it is not allowed to re-upload package with same version on standard ubuntu or debian repository, so many mirroring tools don't check hash but only version of package.
Do you confirm that on each release you rebuild and re-upload all packages even if the version of some of them is not changed?
Could you change that behavior, please?

**Comment by cardigliano** [comment]
@alessio-pascolini I confirm that we rebuild and re-upload all packages on each release. It seems the problem is that the revision is not part of the version for the pfring-drivers-zc-dkms package. We will try to fix this. Are you able to use a workaround for this?

**Comment by alessio-pascolini** [comment]
I could remove and sync all packages every time I want to update my mirror repository, so that it's possible to ensure the hashes inside the file Packages match the real hashes of deb files.
