### ISSUE TITLE
Pass filter_func argument to pfring_zc_run_xxx()

### ISSUE THREAD

**Issue by EaseTheWorld** [ntop/PF_RING#599]
I look at zbalance_ipc.c code and come to a suggestion.
In current code, every distribution_func has to call packet_filter() which seems quite redundant
and even worse, when built-in distribution func is used,(if time_pulse is 0 with mode 2, distribution_func is NULL), you can't implement filtering.
So my suggestion is...
pfring_zc_run_xxx() accepts filter_func as well as distribution_func then
in the worker, call filter_func before distribution_func just like each dist func does now.

**Comment by EaseTheWorld** [comment]
or passing "bpf filter expression" is also possible.
then worker can choose hardware bpf or software bpf.

**Comment by cardigliano** [comment]
It would definitely be nice to have the filtering function as callback. I will mark this ticket as enhancement.

**Comment by EaseTheWorld** [comment]
pfring_zc_set_bpf_filter is fixed now(230d9ab), which makes this feature less attractive.
I don't mind you close the issue.

**Comment by cardigliano** [comment]
Implemented
