### ISSUE TITLE
Add bpf update in runtime to zbalance_ipc

### ISSUE THREAD

**Issue by EaseTheWorld** [ntop/PF_RING#600]
For current zbalance_ipc, bpf filter is given as argument so it can't be updated
unless restarting zbalance_ipc and related consumer applications.
But usually consumer application is a daemon and should keep running.

To improve this, pass a text file(ex. expression.bpf) and when modifying the file, send SIGUSR1 to zbalance_ipc process so it can apply the updated filter.

Some design note.
- setting filter should be in distributor thread for concurrency between bpf read/write.
- need to remove the previous filter before setting new one, which means remove&set should be in same distributor thread to prevent allowing unmatched packet between remove and set
- When updating filter, some delay in distribution is allowed because of file io.
- share '-f' flag so argument could be '-f expression' or '-f file.bpf' to prevent using both.

**Comment by cardigliano** [comment]
@EaseTheWorld since you already implemented this, please feel free to send a pull request to move the patch upstream. Thank you.

**Comment by EaseTheWorld** [comment]
I got a problem when I move the remove/set filtering code to packet_filtering_func.
After I update the filter which does not match at all, packet_filtering_func is not called any more.
so I can't update the filter. kind of race condition.

To solve this, maybe bpf check should be done after filtering_func priority?
If this change is too risky, I will find another way.(not using bpf at all and only use filtering_func, maybe slower though)

**Comment by cardigliano** [comment]
bpf cannot be done after filtering_func, what you can do, is to update the bpf filter both in the filtering function and in the idle callback in case of no packet

**Comment by EaseTheWorld** [comment]
It sounds alright. Then how about update filter only in idle_func?
In my test, idle_func is even called in wire-speed(10G) input.
because updating filter can be waited few ms.

**Comment by cardigliano** [comment]
That's also fine

**Comment by EaseTheWorld** [comment]
Yes, doing in idle_func seems to work, and simplifes the logic as well.
filtering_func is for per-packet/per-queue job(because it passes packet/queue),  but updating filter is not.
