### ISSUE TITLE
Question about Transparent Mode

### ISSUE THREAD

**Issue by gerald-dotcom** [ntop/PF_RING#604]
I'm in process building my own firewall that re-write packets and strip out some of data that aid attackers. 
Now, I selected PF-RING due to simplicity I found in your documentations.

I kinda get what Queues do but with  Transparent Mode 0 it makes quite hard to build mental model around them. 

Since, Transparent Mode 0 share packets to both Kernel and Userspace, How could one send out packets when the packet already shared with Kernel? Can't be there Race condition occur in this case? 

My current assumption is that this will cause double transmission thus duplicate packets.

Please correct me if I am wrong.

**Comment by cardigliano** [comment]
Hi @gerald-dotcom, please note that transparent mode is no longer supported (deprecated), if you need to run as mitm with respect to the host machine, one option is using ZC drivers to detach the interface and the "stack" pfring module to inject to the kernel. If you are running as mitm for other hosts, you should not worry about the kernel and just receive from an interface and send to the other.
