### ISSUE TITLE
Ubuntu 20.04 Build  error

### ISSUE THREAD

**Issue by Michael971022** [ntop/PF_RING#607]
When I build 7.6.0 on ubuntu 20.04(focal) 
the error show below, is this same as the issue [Build error - kernel 5.4 #535](https://github.com/ntop/PF_RING/issues/535)

![pf](https://user-images.githubusercontent.com/65302905/86870934-e2acd500-c10b-11ea-88b3-0e6d65e2e414.jpg)

**Comment by cardigliano** [comment]
@Michael971022 the same is working for me, pfring 7.6 on the same kernel. However I applied some minor changes to the Makefile if you want to give it a try.

`ubuntu20:~/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc$ make
cd src; make
make[1]: Entering directory '/home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src'
# PF_RING
cd ../../../../../kernel/; make
make[2]: Entering directory '/home/nbox/PF_RING/kernel'
make -C /lib/modules/5.4.0-40-generic/build M=/home/nbox/PF_RING/kernel EXTRA_CFLAGS='-I/home/nbox/PF_RING/kernel -DGIT_REV="\"7.6.0-stable:bb096286377c88f07c576317ce735bc624a4396e\"" -no-pie -fno-pie' modules
make[3]: Entering directory '/usr/src/linux-headers-5.4.0-40-generic'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory '/usr/src/linux-headers-5.4.0-40-generic'
make[2]: Leaving directory '/home/nbox/PF_RING/kernel'
cp ../../../../../kernel/Module.symvers .
make[2]: Entering directory '/usr/src/linux-headers-5.4.0-40-generic'
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/netdev.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/ethtool.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/ich8lan.o
uname -a  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/mac.o

  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/nvm.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/phy.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/manage.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/80003es2lan.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/82571.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/param.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/ptp.o
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/kcompat.o
  LD [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000e.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000e.mod.o
  LD [M]  /home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src/e1000e.ko
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-40-generic'
make[1]: Leaving directory '/home/nbox/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc/src'
ubuntu20:~/PF_RING/drivers/intel/e1000e/e1000e-3.4.0.2-zc$ uname -a
Linux ubuntu20 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Michael971022** [comment]
Thank you for help
Where can I download the minor Makefile?
I think the following reasons may cause the situation, but I'm not sure
(1)Install snort 3.0.1 before PF_RING install
(2)install in VM environment the NIC may not fit the driver

I'm still trying to find out the problem,if there are results, I will update.
Thanks again!!

**Comment by cardigliano** [comment]
You can download latest changes with a git update (I see you are using the source code). Alternatively you can also checkout the "dev" code to see if it works. I do not think snort or the VM itself affects this.

**Comment by Michael971022** [comment]
I try again with new VM environment with following step
>git clone https://github.com/ntop/PF_RING.git
>cd PF_RING/kernel && make
>insmod pf_ring.ko min_num_slots=65536 enable_tx_capture=0
>cd PF_RING/drivers/intel  && make

New error occurred
![0709](https://user-images.githubusercontent.com/65302905/87024090-3f42e980-c20b-11ea-947c-a3500583c7f9.jpg)

**Comment by cardigliano** [comment]
I just pushed a fix for this, please update

**Comment by Michael971022** [comment]
It work, thank a lot! 
when I go i40e folder(same as others) for load_driver.sh , it show 'ifconfig' not found
This is because this package is not installed by default Ubuntu 20.04
I replace it with 'ip link set NIC up' and everything go well

**Comment by cardigliano** [comment]
Glad to see it's working now
