### ISSUE TITLE
pf_ring shunt / filter not working 

### ISSUE THREAD

**Issue by MichaelOks** [ntop/PF_RING#608]
Hello,
I am using ftflow.c example with ndpi option and added the following:

_pfring_ft_set_flow_packet_callback(ft, **callbackFunction**, NULL);_
_pfring_ft_set_shunt_protocol_by_name ( ft , "SSH", 10);_

During runtime, I see that pfring_ft_process return value for SSH packets is changing from "PFRING_FT_ACTION_DEFAULT" to "PFRING_FT_ACTION_DISCARD", with is ok. But new SSH packets (from the same flow) are still keep coming to pfring_recv(..) and **callbackFunction**(..) is called for each discarded ssh packet too.

Tried to filter too, but it not filtering packets, just changing the return value of pfring_ft_process(..)
_pfring_ft_set_filter_protocol_by_name ( ft , "SSH", PFRING_FT_ACTION_DISCARD);_

It seemed that after pfring_ft set flow as "discard", packets not filtered in kernel and keep coming to userspace.

[Packet][**discard**] [00:00:00:00:00:00 -> 00:00:00:00:00:00] [IPv4][127.0.0.1:39510 -> 127.0.0.1:22] [l3_proto=TCP][hash=4261452404][tos=16][tcp_seq_num=1999007278] [caplen=66][len=66][eth_offset=0][l3_offset=14][l4_offset=34][payload_offset=66]

Thank you.
Michael

**Comment by cardigliano** [comment]
@MichaelOks please note that FT runs in userspace, thus packets are marked and filtered in userspace. You should use the return value of pfring_ft_process as verdict to discard the packet explicitly, or you can configure PF_RING_FT_CONF  as explained at https://www.ntop.org/guides/pf_ring/ft.html#ids-acceleration to hide this behind the pf_ring API. In any case filtering happens in userspace (we are working on offload support to use specialized hw adapters for that, but it's still not available, unless you set a filter explicitly).
