### ISSUE TITLE
tcpdump not capturing outgoing packets on interface

### ISSUE THREAD

**Issue by kothuri88** [ntop/PF_RING#609]
Hi ,

I see this strange thing of tcpdump not capturing outgoing packets with server enabled with PF_ring . Below is some info :

Using the native tcpdump shipped with RHEL

tcpdump version 4.9.2
libpcap version 1.8.1
OpenSSL 1.0.2k-fips  26 Jan 2017

Name:         ens1f0
Index:        3
Address:      48:DF:37:A5:71:90
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel i40e
TX Queues:    4
RX Queues:    4
Num RX Slots: 4096
Num TX Slots: 512

Please let me know if any information is needed. 

Thanks,
Karthik

**Comment by cardigliano** [comment]
@kothuri88 I see that you have a ZC driver loaded. Are you running tcpdump in ZC mode? What is the command line you are using?

**Comment by kothuri88** [comment]
No. I m using the plan native tcpdump command

tcpdump -i any port 162

**Comment by cardigliano** [comment]
Could you try unloading the ZC driver to check if you have the same behaviour?

**Comment by kothuri88** [comment]
I removed the module using following 

rmmod pf_ring 

and I see tcpdump is well capturing the outgoing packets. 

Thanks,
karthik

**Comment by cardigliano** [comment]
@kothuri88 I meant unloading just the ZC driver, while using the pf_ring module for capturing traffic. I want to figure out if it depends on ZC.

**Comment by kothuri88** [comment]
Sorry. Could you please guide as to how can be unload only ZC. Because, under lsmod I see pf_ring and i40e only

**Comment by cardigliano** [comment]
If you configured the package, please move the content of /etc/pf_ring/zc/i40e/ and restart the service (systemctl restart pf_ring)

**Comment by kothuri88** [comment]
unloaded ZC. still don't see outgoing packets .

Name:         ens1f0
Index:        11
Address:      48:DF:37:A5:71:90
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    4
RX Queues:    4

**Comment by cardigliano** [comment]
Please provide cat /proc/net/pf_ring/info

**Comment by kothuri88** [comment]
rs01:~$ cat /proc/net/pf_ring/info
PF_RING Version          : 7.5.0 (unknown)
Total rings              : 3

Standard (non ZC) Options
Ring slots               : 409600
Slot version             : 17
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Standard

**Comment by cardigliano** [comment]
Please pay attention to "Capture TX : No [RX only]", did you configure enable_tx_capture=0 perhaps?

**Comment by kothuri88** [comment]
Thank you. I think I lost thought on this. I enabled it and I can see packets on tcpdump. I will check with my team.  
Thanks a ton, once again.
