### ISSUE TITLE
zbalance was droping packets the ports whose numa nuode is -1.

### ISSUE THREAD

**Issue by bth-kumar** [ntop/PF_RING#611]
I have putted X720 card to cisco server for testing ... 

cat /sys/class/net/enps0f0/device/numa_node      was showing -1. and after certain interval it was dropping packets... event the bandwitdh was 800Mbps..

**Comment by cardigliano** [comment]
Do you mean X710 or X520? Could you provide the output of lstopo?

**Comment by cardigliano** [comment]
Looks like duplicate of #612
