### ISSUE TITLE
zeek:multiple entries with PF_RING-7.6.0

### ISSUE THREAD

**Issue by shuaidonga** [ntop/PF_RING#613]
I'm currently using zeek-3.1.5 and pf_ring 7.6.0 (compiled on CentOS Linux release 7.8.2003). Run zeek every log is multiplied by 10. It is the same as my lb_procs (zeek node.cfg) number.

The following is pf_ring information when zeek is running

root@EM-GJJ8D53: /opt# more /proc/net/pf_ring/* |cat

*** /proc/net/pf_ring/dev: directory ***

::::::::::::::
/proc/net/pf_ring/info
::::::::::::::
PF_RING Version          : 7.6.0 (unknown)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

*** /proc/net/pf_ring/stats: directory ***

The following is zeek's node.cfg configuration information
[logger]
type=logger
host=localhost

[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=com6
lb_method=pf_ring
lb_procs=10
pin_cpus=2,3,4,5,6,7,8,9,10,11
env_vars=PCAP_PF_RING_CLUSTER_ID=99

**Comment by cardigliano** [comment]
It looks like clustering is not spreading the load and all procs (you configured 10) are receiving a copy of the traffic.
What kind of interface is com6?

**Comment by shuaidonga** [comment]
@cardigliano 
ethtool -i com6
driver: ixgbe
version: 5.1.0-k-rh7.7
firmware-version: 0x8000095d, 19.5.12
expansion-rom-version: 
bus-info: 0000:3b:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

**Comment by cardigliano** [comment]
Please make sure that the cluster is set correctly in the pfring socket with the command below. You should see "Cluster Id : 99" for all sockets (one per zeek process).

cat /proc/net/pf_ring/<socket> | grep "Cluster Id"

**Comment by shuaidonga** [comment]
The following is zeek's zeekctl.cfg configuration information
```
## Global ZeekControl configuration file.

###############################################
# Mail Options
env_vars=PCAP_PF_RING_CLUSTER_ID=99
#env_vars=PCAP_PF_RING_CLUSTER_ID=99
PFRINGClusterID=99

# Recipient address for all emails sent out by Zeek and ZeekControl.
MailTo = root@localhost

```

**Comment by cardigliano** [comment]
Please make sure the conf is applied by checking the actual cluster ID in the socket as I suggested:
cat /proc/net/pf_ring/ | grep "Cluster Id"

**Comment by shuaidonga** [comment]
![image](https://user-images.githubusercontent.com/16378509/89171155-562eee80-d5b3-11ea-9d39-1873c134ecdc.png)

**Comment by AspirePig** [comment]
How was this problem solved
