### ISSUE TITLE
Application hangs in pfring_mod_poll() 

### ISSUE THREAD

**Issue by teoring** [ntop/PF_RING#614]
I have a multi threading application that polls for packets from the interface. At some point all threads stops inside of the pfring_mod_poll() even though the traffic is still there. This reproduces once per week, the application stop receiving packets and do not recover.

I know that it is impossible to fully investigate this issue without all the logs and information but I hope you might have seen such behavior before and might have a guess why it might occur.

My polling loop is simple:
        while( mIsStarted )
        {
                pfring_poll( aVars.pfringP(), 100 );
                 ....
        }

I also apply following configuration:

pfring_open( .., PF_RING_PROMISC | PF_RING_LONG_HEADER )
pfring_set_cluster( cluster_per_flow_5_tuple )
pfring_enable_ring() for every thread that invoks prfing_poll()

![image](https://user-images.githubusercontent.com/12891023/89391297-4e349300-d708-11ea-9121-73efaa4c7074.png)
![image](https://user-images.githubusercontent.com/12891023/89390830-9901db00-d707-11ea-9035-d8775403b4ea.png)

**Comment by cardigliano** [comment]
@teoring what is the interface model? I guess you are using standard drivers (I see you are setting a kernel cluster). 
What pf_ring version are you using?

**Comment by teoring** [comment]
We are using Intel I350 NIC with standard drivers ( Ubuntu 16.04.06 ). PF_RING v7.2.0.

**Comment by cardigliano** [comment]
Are you able to provide the content of /proc/net/pf_ring/<socket> when this happens?

**Comment by teoring** [comment]
I would collect this information and report it here once available.

**Comment by teoring** [comment]
While I am still collecting information from /proc/net/pf_ring I want to apologize and correct myself. The server we are using is Dell R640 and the NIC is actually Broadcom 5719 Quad Port 1GbE B ASE-T Adapter, PCIe Low Profile.

**Comment by cardigliano** [comment]
Ok np, you are running Ubuntu 16 right? Let's wait for the /proc stats to figure out what's going on, please collect them when the issue happens (better if a couple of snapshots with a delay of a few seconds to see how counters increase)

**Comment by teoring** [comment]
Hello again,

I have collected information that was requested. 
The management interface is CM57416 NetXtreme-E Dual-Media 10G RDMA Ethernet Controller (mgmt).
![image](https://user-images.githubusercontent.com/12891023/89761929-b95adc80-daef-11ea-8e04-53897cf8826f.png)

There is traffic on the interface for sure:
![image](https://user-images.githubusercontent.com/12891023/89761982-d099ca00-daef-11ea-92d7-d3d8ee57f75a.png)


Here is the entire directory structure from /proc/net/pf_ring taken a few seconds apart, 4x. It is attached
[pfring_info.zip](https://github.com/ntop/PF_RING/files/5049578/pfring_info.zip)

**Comment by cardigliano** [comment]
@teoring it seems there is no traffic hitting the pf_ring kernel module, the problem is not the poll itself. 
A few more requests:
- Could you provide the output of "ifconfig" while running the application?
- Did you check with a single interface?
- Did you check without setting the cluster?

**Comment by teoring** [comment]
@cardigliano Thanks for giving the look on logs. I can't disable clustering as it is hard coded into the application. I understand that 'ifconfig' output has to be collected when this situation occurs?

**Comment by teoring** [comment]
Here is ipconfig collected few times in a row.
[ifconfig2.txt](https://github.com/ntop/PF_RING/files/5073364/ifconfig2.txt)
[ifconfig1.txt](https://github.com/ntop/PF_RING/files/5073365/ifconfig1.txt)

**Comment by teoring** [comment]
@cardigliano do you think this kind of condition can be caused by the application using PFRING itself? Can any kind of undefined behavior result in PFRING kernel module not getting any traffic?

**Comment by cardigliano** [comment]
Looking at ifconfig everything looks good, packets are coming and the interface is in promiscuous mode. Are you capturing traffic with multiple threads from the same socket perhaps? This could lead to corruptions in the receive ring.

**Comment by teoring** [comment]
Could you elaborate on topic of sniffing the traffic from the same socket with multiple threads? I am not sure I understood. Does that mean I can't invoke pfring_recv on the same ring from the different threads without synchronization?

**Comment by cardigliano** [comment]
@teoring correct, if you want to call pfring_recv from multiple threads, you should add the PF_RING_REENTRANT flag to pfring_open, however this leads to performance degradation. If you traffic rate is high, you should consider using technologies like RSS, and spawn one thread per RSS queue.

**Comment by teoring** [comment]
@cardigliano Thanks, I appreciate your support. Just one question, I understand in case I am calling pfring_open ( opening the same interfaces from different threads ) for each thread ( having pfring handle per thread ) I don't have to synchronize the access to pfring_recv?

**Comment by cardigliano** [comment]
If you open the same interface from multiple thread, no syncronization is required, however you should use clustering (see pfcount -c) or RSS otherwise all threads will receive the same traffic.

**Comment by teoring** [comment]
Got it, that is what I am doing. My problem must be in some other place.
