### ISSUE TITLE
Intel 9560(2x2 AC) net card's driver

### ISSUE THREAD

**Issue by lemorn** [ntop/PF_RING#615]
Hello! I'm using the Intel 9560(2x2 AC) net card and i didn't find the corresponding driver in guides https://www.ntop.org/guides/pf_ring/zc.html. Which driver shoud i use?

I also want to use the masscan on ubuntu based on vmware to scan a Internet space, can pf_ring be used on vmware?

**Comment by cardigliano** [comment]
@lemorn it looks like Intel 9560 is a Wireless chipset, this is not supported by ZC.. please use standard drivers.
PF_RING can run on VMWare.
