### ISSUE TITLE
pfring 6.2.0-411 rpm doesn't provide libpfring.so

### ISSUE THREAD

**Issue by wonder** [ntop/PF_RING#62]
I have a rpm package that was compiled having pfring  as requirements and it generated a so dependency for libpfring.so.

This rpm package cannot be installed because pfring 6.2.0-411 rpm doesn't provide libpfring.so.
It's working fine with  6.0.3-218.

Running provides for 6.0.3
 rpm -q --provides pfring
daq_pfring.so()(64bit)  
daq_pfring_zc.so()(64bit)  
libpcap.so.1()(64bit)  
libpfring.so()(64bit)  
libsfbpf.so.0()(64bit)  
libtool(/usr/local/lib/daq/daq_pfring.la)  
libtool(/usr/local/lib/daq/daq_pfring_zc.la)  
pfring = 6.0.3-218
pfring(x86-64) = 6.0.3-218

Running provides on 6.2.
 rpm -q --provides pfring
pfring = 6.2.0-411
pfring(x86-64) = 6.2.0-411

**Comment by lucaderi** [comment]
@wonder 
It works for me. Please check again and let us know.

> diff pfring.spec.in_stable ~/network/PF_RING/package/rpm/pfring.spec.in
> 
> rpm -qpl ./pfring-6.2.0-411.x86_64.rpm|grep libpfring.so
> warning: ./pfring-6.2.0-411.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 7921df34: NOKEY
> /usr/local/lib/libpfring.so

**Comment by wonder** [comment]
@lucaderi I didn't say that the rpm doesn't have the libpfring.so  file in the package.
What I said is that the rpm doesn't provide anymore the dependency of libpfring.so.

If in a spec I have that my application depends on pfring, automatically the rpm builder is detecting that it needs libfring.so. So if 6.2.0 doesn't have it, I am unable to install the newer version of pfring (if my rpm is installed) or even to install my rpm package.

Please notice the difference that rpm -q --provides pfring returns on 6.0.3 vs 6.2.0.

**Comment by wonder** [comment]
to be more clear, it's a soname dependency error because the rpm package doesn't provide it.
rpm has dependencies (package names as dependencies)  and soname dependencies.(dependecies as soname) and pfring 6.2 doesn't provide the sonames dependencies.

**Comment by lucaderi** [comment]
@wonder Can you please check if the patch works for you?

**Comment by wonder** [comment]
@lucaderi unfortunally, I'm not able to build pfring starting from the spec that is available in git.
Can you upload a rpm for pfring in order to test it?

**Comment by lucaderi** [comment]
That's in git is the only one we have. Why do you want to build it? We do package it on http://packages.ntop.org

**Comment by wonder** [comment]
@lucaderi I wanted to test your patch and since I didn't find any new rpm on stable I was thinking that was the best approach.

**Comment by cardigliano** [comment]
Please test the dev package on http://packages.ntop.org if possible, if it works well we will backport the fix to the stable. Thank you.

**Comment by wonder** [comment]
still doesn't work

  Requires: libpfring.so()(64bit)
           Removing: pfring-6.0.3-218.x86_64 (@ntop)
               libpfring.so()(64bit)
           Updated By: pfring-6.3.0-437.x86_64 (/pfring-6.3.0-437.x86_64)
               Not found
 You could try using --skip-broken to work around the problem

I believe it requires other format.
 rpm -q --provides pfring
daq_pfring_zc.so  
daq_pfring.so  
libpfring.so  
pfring = 6.3.0-437
pfring(x86-64) = 6.3.0-437

vs
rpm -q --provides pfring
daq_pfring.so()(64bit)  
daq_pfring_zc.so()(64bit)  
libpcap.so.1()(64bit)  
libpfring.so()(64bit)  
libsfbpf.so.0()(64bit)  
libtool(/usr/local/lib/daq/daq_pfring.la)  
libtool(/usr/local/lib/daq/daq_pfring_zc.la)  
pfring = 6.0.3-218
pfring(x86-64) = 6.0.3-218

**Comment by lucaderi** [comment]
@wonder Can you please set as dependency on your package the pfring package? In the meantime I will see what I can do for fixing the dependencies.
