### ISSUE TITLE
Auto-Negotiation:"Not Available after using fm10 driver in fm10420 adapter  

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#620]
![image](https://user-images.githubusercontent.com/44804599/90228600-18e71e00-de49-11ea-9185-069b45ddbc58.png)

**Comment by cardigliano** [comment]
@MaoPann this feature comes from the standard intel driver, is it working with the original driver available at
https://sourceforge.net/projects/e1000/files/fm10k%20stable/0.27.1/ ?

**Comment by MaoPann** [comment]
I don't understand what you mean

**Comment by cardigliano** [comment]
ZC drivers are standard Intel drivers with some patches and optimizations. The auto-negotiation feature comes from the original driver which is available at https://sourceforge.net/projects/e1000/files/fm10k%20stable/0.27.1/ 
I expect to see the same behavior using that driver, thus I suggested you to test that.
