### ISSUE TITLE
What nbroker does. Do I need nbroker to use FM10 Adapter》

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#621]

**Comment by cardigliano** [comment]
You need nbroker or a tool from the card manufacturer for setting the internal (hw) bridge.

**Comment by MaoPann** [comment]
How to etting the internal (hw) bridge? Can the FM10 Adapter  run Normal operation,such as pfring ZC.

**Comment by cardigliano** [comment]
You need to set the internal bridge to enable normal operation, please see https://www.ntop.org/guides/pf_ring/nbroker/index.html
