### ISSUE TITLE
how to use pfring ZC on the fm10420 Adapter?

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#623]
Can you give me a tutorial on using pfring ZC on the fm10420 Adapter? There is no detailed introduction to using the fm10420 adapter in the user manual. Or tell me what's different from other adapters. Because I encountered some problems with the fm10420 adapter, such as no ZMQ when loading the driver. This problem was not encountered when I used other adapters.

**Comment by cardigliano** [comment]
Besides configuring the switch (see the other discussion/issue) all you need to do is to configure the ZC driver as described at https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html
