### ISSUE TITLE
Only run the nbrokered can i use the fm10420 normal operations？

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#624]
If i run the nbrokered can i use the fm10420 normal operations？such as pfring ZC,

**Comment by cardigliano** [comment]
I already answered to this question, fm10420 can be used with ZC as a standard adapter, however you need to configure the internal adapter switch using nbroker or the manufacturer tool to set the adapter in "standard nic" mode.
When you run nbroker, the adapter is configured as standard nic by default, please read https://www.ntop.org/guides/pf_ring/nbroker/index.html
