### ISSUE TITLE
nbrokerd error 

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#626]
17/Aug/2020 10:32:38 [daemon.c:1197] Welcome to nbrokerd
---0     19---17/Aug/2020 10:32:38 [daemon.c:103] [ZMQ] Listening at tcp://127.0.0.1:5555
17/Aug/2020 10:32:38 [daemon.c:1095] RRC initialization..
17/Aug/2020 10:32:38 [rrc.c:1036] - Initialisation. Please wait
Loading /etc/rrc/fm_platform_attributes.cfg
WARNING:events:fmPlatformHostDrvOpen:2093:uio0 is pep0 but mgmt pep is set to 2
Connect to host driver using /dev/uio0
Found netdev ens4 (derived from uio device /dev/uio0)
WARNING:events:ValidateMgmtPep:1956:ens4 is pep0 but mgmt pep is set to 2
ERROR:events:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:events:InitSwitchPcaDevice:3639:Error to init PCA mux
FATAL:events:fmHandleSwitchInserted:4306:Switch Inserted Event Handler: fmPlatformSwitchInserted returned error 230(I2C access error) for switch 0
ERROR:nbrokerd:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:nbrokerd:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:nbrokerd:SwitchI2cWriteRead:1364:I2C error accessing device 0x20 via switch 0: I2C access error
ERROR:nbrokerd:fmPlatformLibGetPortXcvrState:4678:Failed to read PCA IO regs (hwResourceId 0)
ERROR:nbrokerd:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:nbrokerd:fmPlatformLibGetPortXcvrState:4657:Failed to select xcvr bus (hwResourceId 1)
ERROR:nbrokerd:fm10000PostBootSwitch:5634:Sw#0: RX DMA Disabled. Expect pep 2 RXQCTL[0].enable=1 but is 0. RXQCTL=0x0
ERROR:nbrokerd:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:nbrokerd:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x20 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4678:Failed to read PCA IO regs (hwResourceId 0)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4657:Failed to select xcvr bus (hwResourceId 1)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x20 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4678:Failed to read PCA IO regs (hwResourceId 0)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4657:Failed to select xcvr bus (hwResourceId 1)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x20 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4678:Failed to read PCA IO regs (hwResourceId 0)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4657:Failed to select xcvr bus (hwResourceId 1)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x20 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4678:Failed to read PCA IO regs (hwResourceId 0)
ERROR:Mgmt Thread:SwitchI2cWriteRead:1364:I2C error accessing device 0x70 via switch 0: I2C access error
ERROR:Mgmt Thread:fmPlatformLibGetPortXcvrState:4657:Failed to select xcvr bus (hwResourceId 1)
17/Aug/2020 10:32:46 [daemon.c:1023] Terminating... [signal: 2]
17/Aug/2020 10:32:46 [rrc.c:1482] Interface ens4 is on PCIe slot 0/25/0
17/Aug/2020 10:32:46 [daemon.c:1103] RRC successfully initialized. Accepting commands

**Comment by cardigliano** [comment]
@MaoPann what is the card manufacturer? Silicom? Did they provide you the correct fm_platform_attributes.cfg file? They should also provide a tool for setting the switch (rdif in case of Silicom) that you can use to configure the adapter as standard nic when you do not need the flexibility provided by nbroker.

**Comment by MaoPann** [comment]
i use the fm_platform_attributes.cfg in pfring /usrland/nbroker/rrclib/etc/rrc/fm_platform_attributes.cfg

**Comment by MaoPann** [comment]
FM10420 adapter

**Comment by MaoPann** [comment]
I  want to  use nbroker to set the fm10420 adapter in ''standard nic' mode.but some error occurd as above。

**Comment by MaoPann** [comment]
I want to use nbroker to set the fm10420 adapter to use Pfring ZC.but some error occurd as above。

**Comment by cardigliano** [comment]
@MaoPann the correct fm_platform_attributes.cfg file depends on the adapter and cables you are using, please ask the manufacturer to provide the correct file, and I suggest to use the manufacturer tool to make sure everything is working. After that you can use nbroker to configure the switch.

**Comment by MaoPann** [comment]
The user guide indicate the fm10420 adaper is available,Why does this happen? My  adaper is fiber.
![image](https://user-images.githubusercontent.com/44804599/90424546-dfd0d700-e0f0-11ea-8602-539cb96ea24d.png)

**Comment by MaoPann** [comment]
Have you ever test the fm10420 adapter wtih fm_platform_attributes.cfg in /etc/rcc?

**Comment by cardigliano** [comment]
Sure, but as I said the configuration file also changes according to the cable model. Please ask the manufacturer to provide the correct one.

**Comment by MaoPann** [comment]
The name of the document provided by the manufacturer is also fm_ platform_ attributes.cfg?Because usually there are many configuration file.Can you give me a specific define.

**Comment by MaoPann** [comment]
Can you tell me the specific model of FM10420 Ethernet adapter that you have tested，or give me a website？

**Comment by cardigliano** [comment]
@MaoPann the configuration file name is the same, you should replace it with the correct one. What is your adapter model/manufacturer? This is what we have in our lab https://www.silicom-usa.com/pr/server-adapters/networking-adapters/100-gigabit-ethernet-networking-server-adapters/pe3100g2dqir_server_adapter/

**Comment by MaoPann** [comment]
thanks!!!!!!!! FM10420QDA2 network adapter
