### ISSUE TITLE
Move my NIC 

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#628]
If I activate my NIC with ZC license on one device, now I move the NIC to another device, can I activate my NIC again with the original license.

**Comment by cardigliano** [comment]
@MaoPann the license is based on the MAC address, thus you can move it on another machine (as long as the license is not expired)

**Comment by MaoPann** [comment]
Just activate my NIC again with the original license?

**Comment by cardigliano** [comment]
Just copy the license on the new machine
