### ISSUE TITLE
Multiple applications capture from same zc interface?

### ISSUE THREAD

**Issue by EaseTheWorld** [ntop/PF_RING#629]
application 1 : zbalance_ipc -i zc:ethX -c 1 -n 4 -m 2 -f bpf1
application 2 : zbalance_ipc -i zc:ethX -c 2 -n 4 -m 2 -f bpf2
When I'm running application 1, I want to start/stop application 2 and others.
Is this possible with "**zc:ethX**"? or I have to use "**ethX**" instead?

If latter, do I still need ZC license?
zbalance_ipc is not complaining about license when input is not ZC.
but I'm not sure because zbalance_ipc still uses zc_api like cluster.

assume traffic is under 1Gbps.

**Comment by cardigliano** [comment]
You cannot open the same ZC device multiple times, as the application takes exclusive control over the interface.
If you use a standard interface, no license is required. If you have less than 1g, that should work.

**Comment by EaseTheWorld** [comment]
Thank you for clear response.
