### ISSUE TITLE
Hugepages cleanup at startup

### ISSUE THREAD

**Issue by lucaderi** [ntop/PF_RING#63]
When a PF_RING ZC based application starts up it might create a file under the huge pages mount directory (e.g. when a new cluster is created). However it is likely that such application will change user (e.g. from root to nobody) thus at shutdown such file cannot be deleted. If the application is restarted as is, the file is deleted (overwritten) at startup, but if not restarted or restarted with different parameter, the file stays. This way the space is filled up and thus new applications cannot start.
In order to avoid this, PF_RING ZC at startup must scan the huge pages mount, use fuser() to identify non-used files, and delete them, in order to reclaim unused space.

**Comment by cardigliano** [comment]
Implemented
