### ISSUE TITLE
what does wait_for_packet means 

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#630]
what does wait_for_packet means in the pfring_zc_recv_pkt()?

**Comment by cardigliano** [comment]
That is used for blocking recv (set wait_for_packet = 1 for blocking, 0 for non blocking)

**Comment by MaoPann** [comment]
what  is Pulse-time thread for inter-packet time check mean?

**Comment by cardigliano** [comment]
What is the application you are talking about? The pulse-thread is usually used to compute time with low overhead and mid-high precision.
