### ISSUE TITLE
load balancing

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#632]
1.Can you elaborate on the meaning of - M parameter, especially fan - out.
![image](https://user-images.githubusercontent.com/44804599/91140245-27072b00-e6e2-11ea-97e2-f9ed3bb29be6.png)
2.If I use zbalance_ipc, can I achieve 100Gbit to receive packets.
3.Which load balancing method can receive data at 100Gbit.

**Comment by cardigliano** [comment]
@MaoPann -m specifies which distribution function you want to use to assign packets to consumer queues. A few examples: 
- Round-Robin  assigns packets in equal portions and in circular order
- IP hash assigns packets to queues based on the src/dst IP addresses (same IPs always go to the same queue)
- Fan-out delivers all packets to all queues
The traffic rate in Gbit you are able to handle mainly depends on the PPS rate. Unlikely you will be able to handle 100Gbit unless you have jumbo packets. RSS (hardware distribution) is recommended at 100 Gbit.
