### ISSUE TITLE
Ping cannot be used after ixgbe driver is loaded

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#634]

**Comment by cardigliano** [comment]
ixgbe ZC is a kernel-bypass drivers, that means the interface is detached from the kernel when you run the packet capture, thus this is expected.

**Comment by MaoPann** [comment]
Can I send packets

**Comment by cardigliano** [comment]
The application opening the "zc:ethX" interface takes full control over the interface. This means you can send packets using that interface (not through the kernel)
