### ISSUE TITLE
Can zcout receive packets in a contiguous memory space?

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#637]

**Comment by cardigliano** [comment]
zcount and all ZC-based applications receive packets in individual buffers. If you need a contiguous buffer with packets you need to copy them.

**Comment by MaoPann** [comment]
I want to copy the cache directly

**Comment by MaoPann** [comment]
I want to copy the cache directly. What should I do?

**Comment by MaoPann** [comment]
Copying one packet at a time is too slow. We want to copy the packets in the cache when the cache is full
