### ISSUE TITLE
libpcap issue:  Bad address

### ISSUE THREAD

**Issue by sanyaden** [ntop/PF_RING#64]
Hello,
After installing PF_RING 6.3.0 on ubuntu 14.04 and compilling libpcap 1.6.2
faced with such issue:
root@test-lbs:~# dumpcap -i eth0
Capturing on 'eth0'
Warning: Kernel filter failed: Bad address
File: /tmp/wireshark_pcapng_eth0_20160114100407_wlPZDH
Packets captured: 187248
Packets received/dropped on interface 'eth0': 187248/0 (pcap:0/dumpcap:0/flushed:0/ps_ifdrop:0) (100.0%)
root@test-lbs:~# tshark -i eth0
Running as user "root" and group "root". This could be dangerous.
Capturing on 'eth0'

^Ctshark: Unknown message from dumpcap, try to show it as a string: Warning: Kernel filter failed: Bad address

0 packets captured

But when starting tshark or dumpcap with any capture filter, for example:
dumpcap -i eth0 -f 'ip'
there is no such issue.
I guess issue related to libpcap and fixed in 1.7.2 version (from changelog):
Thursday Feb. 12, 2015 guy@alum.mit.edu/mcr@sandelman.ca
  Summary for 1.7.2 libpcap release
    Support for filtering Geneve encapsulated packets.
    Generalize encapsulation handling, fixing some bugs.
    Don't add null addresses to address lists.

Could You be so kind to add newer version of libpcap into PF_RING 6.3.0 to fix this issue?

Thanks in advance!

**Comment by sanyaden** [comment]
Dear Colleagues,

did You investigated this issue or added fix into ?

Thanks!

**Comment by cardigliano** [comment]
Warning fixed, please update to latest code.

**Comment by sanyaden** [comment]
Dear Colleagues,
faced with the same issue after upgrading to pfring 6.4.1

**Comment by cardigliano** [comment]
Fixed
