### ISSUE TITLE
Tagged traffic stops working when using  "enable_ip_defrag=1"

### ISSUE THREAD

**Issue by zinosat** [ntop/PF_RING#642]
I have a system (Linux 4.14.79-rt29-yocto-preempt-rt) with 4 network interfaces and an application using various rings spanning on multiple interfaces and mainly dealing with UDP traffic:

 - one ring involves all interfaces "enp8s0f0,enp8s0f1,enp8s0f2,enp8s0f3"
 - one ring on "enp8s0f0,enp8s0f1"
 - one ring on "enp8s0f2,enp8s0f3"

pf_ring module is loaded with "enable_ip_defrag=1" option.
Everything works as expected.

We have introduced a vlan interface ("enp8s0f2.10") to handle management SNMP traffic, but the traffic on this interface, stops working as soon as the PF_RING-based application is run; in particular, as soon as pfring_open("enp8s0f0,enp8s0f1,enp8s0f2,enp8s0f3") executes.

To reproduce the problem, I ping a device from enp8s0f2.10 and ping stops working when running the application as explained.

If I load pf_ring module without "enable_ip_defrag=1" and run the test again, ping runs smoothly even after running our application.

The problem was tested with the following versions of PF_RING:

PF_RING 7.6.0 ($Revision: 7.6.0-stable:26892dd68d2fce2dd93ac5a3e6e169ddc563f203$)
PF_RING 7.7.0 ($Revision: dev:76fd2a9802b0bddd6e34ee1eec7a7cb1e7e38053$)

Thank you in advance for your help,

regards,
Davide

**Comment by cardigliano** [comment]
@zinosat please check latest pf_ring kernel module available on github (dev) or update 7.7 later today from the repo and let me know.

**Comment by zinosat** [comment]
@cardigliano I've just run a test with your latest fixes: it works.

thanx alot!

Davide
