### ISSUE TITLE
tcpdump with pf_ring capture twice for every packet from lo interface

### ISSUE THREAD

**Issue by strgrb** [ntop/PF_RING#648]
My environment:
- PF_RING: 7.6.0
- os: CentOS-7.6
- kernel: 3.10.0-975 and 3.10.0-1127

I can get correct result using normal tcpdump, and using tcpdump in pf_ring, I capture same packet twice, for every packet.

**Comment by cardigliano** [comment]
@strgrb this happens because pf_ring captures both packets sent and received by the interface. This can be avoided by loading the pf_ring kernel module with enable_tx_capture=0, or setting the capture direction in the application (e.g. "pfcount -i lo -e 1" or "tcpdump -i lo -Q in")

**Comment by strgrb** [comment]
@cardigliano I use "tcpdump -i lo dst port ", this works fine for other interface, and tcpdump without pf_ring works with this option, but not works with lo interface. 
 I've tried enable_tx_capture=0, and that works fine for me. Thank you very much.

**Comment by cardigliano** [comment]
you can also use "tcpdump -i lo -Q in" without reloading the kernel module, in case you have other applications that require tx traffic
