### ISSUE TITLE
Compiling error. Debian 7. Kernel 3.2.0-4 

### ISSUE THREAD

**Issue by lexesv** [ntop/PF_RING#65]
Hello!

OS: Linux 3.2.0-4-rt-amd64 #1 SMP PREEMPT RT Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

I get errors when compiling PF_RING:

webmaster@shost:/build/pf_ring/PF_RING-6.2.0/kernel$ make
make -C /lib/modules/3.2.0-4-rt-amd64/build SUBDIRS=/build/pf_ring/PF_RING-6.2.0/kernel EXTRA_CFLAGS='-I/build/pf_ring/PF_RING-6.2.0/kernel -DGIT_REV="\"6.2.0-stable:6e64d978b8877c61b68da1ec3f9e2bde80ca8892\""' modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
  CC [M]  /build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.o
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c: In function ‘init_ring_readers’:
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c:288:5: error: expected expression before ‘{’ token
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c: In function ‘init_lockless_list’:
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c:520:5: error: expected expression before ‘{’ token
make[4]: *** [/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.o] Error 1
make[3]: *** [_module_/build/pf_ring/PF_RING-6.2.0/kernel] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.2.0-4-rt-amd64'
make: **\* [all] Error 2

I tried other versions, anyway compilation errors.

Please help.

**Comment by cardigliano** [comment]
6.2.0 is compiling on my Debian 7

**Comment by cardigliano** [comment]
PF_RING 6.2.0 is compiling on my Debian 7.
Linux debianvm 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u4 x86_64 GNU/Linux

**Comment by lexesv** [comment]
The problem was in the realtime (3.2.0-4-rt-amd64) kernel.
In normal kernel compilation is successful.
Is it possible to do in the future support of RT kernels?
Thanks.
