### ISSUE TITLE
Support for enic driver

### ISSUE THREAD

**Issue by mzac** [ntop/PF_RING#652]
Is it possible to get support for the Cisco enic driver?

```
root@ntop:~# pf_ringcfg --list-interfaces | grep enic
Name: ens192               Driver: enic
Name: ens256               Driver: enic

root@ntop:~# lspci | grep -i cisco
0b:00.0 Ethernet controller: Cisco Systems Inc VIC Ethernet NIC (rev a2)
1b:00.0 Ethernet controller: Cisco Systems Inc VIC Ethernet NIC (rev a2)
```

**Comment by cardigliano** [comment]
@mzac enic adapters can be used with standard drivers (there is no accelerated ZC driver available for those interfaces, and there is no plan to add support for that at the moment as this is the first request we get)
