### ISSUE TITLE
PF_RING zero copy go implementation does not return control to calling function

### ISSUE THREAD

**Issue by wontoniii** [ntop/PF_RING#653]
Hello, I am developing an application in Go using PF_RING's zero copy driver (licensed). We have been having some issues with the ZeroCopyReadPacketData function as it never returns control to the caller function. We see that the driver is working, i.e. pfcount work without problems with the zc interfaces (zc:ifname@0), as well as showing stats (using the built in function https://github.com/google/gopacket/blob/master/pfring/pfring.go#L346). But we have no luck in getting ZeroCopyReadPacketData to work. The same exact code, minus using ZeroCopyReadPacketData, works like a charm.

Thank you very much for you help!

**Comment by cardigliano** [comment]
@wontoniii the Go wrapper is not maintained by us, sorry..
