### ISSUE TITLE
pcap_breakloop() can't stop pcap_loop() if no input traffic.

### ISSUE THREAD

**Issue by EaseTheWorld** [ntop/PF_RING#654]
Environment
  RHEL 7.4
  pfring-aware libpcap 1.8.1 installed from PF_RING-dev-7dd96c4.
  running zbalance_ipc -i ens4f1 -c 100 -n 4 -m 2
  no input traffic in ens4f1.

I made a basic counter with libpcap.

  - pcap_open_live -> pcap_loop with packet handler(=counter) -> pcap_close
  - SIGINT handler calls pcap_breakloop

and run ./basic_counter zc:100@0

When there is no input traffic, Ctrl+C can't stop pcap_loop().
It is same whether using original libpcap.so or pf-ring aware libpcap.so.

I had to signal SIGKILL to kill the counter but then zc:100@0 was not closed safely
so I restarted zbalance_ipc again to use zc:100@0 again.

**Comment by cardigliano** [comment]
@EaseTheWorld I pushed a patch that should fix this, please update from github or wait the next dev builds and let us know.

**Comment by EaseTheWorld** [comment]
Did you reproduce the issue?
I might made mistake or something.

I can't reproduce the issue with old(7dd96c4) and new(87584c0) version.
old libpcap & old zbalance_ipc -> no issue
old libpcap & new zbalance_ipc -> no issue
new libpcap & old zbalance_ipc -> no issue
new libpcap & new zbalance_ipc -> no issue

I tested like both
LD_LIBRARY_PATH=PF_RING-dev-7dd96c4/userland/libpcap ./basic_counter zc:100@0
LD_LIBRARY_PATH=PF_RING-dev-87584c0/userland/libpcap ./basic_counter zc:100@0
and press ctrl+c which stops normally.

What case is 87584c0(71e27ba actually) affecting...?

**Comment by cardigliano** [comment]
71e27ba is fixing the breakloop which was likely to fix your issue, however if everything is working now we are fine I guess
