### ISSUE TITLE
Is the open source code complete.

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#655]
Is the open source code complete.include ntopng，ndpi，nprobe，PF_ring.
For example, does the downloaded open source code include different versions of ntopng? As long as the corresponding license is purchased, can the corresponding version of each tool be used through the source code?

**Comment by MaoPann** [comment]
and n2disk,nDPI,n2n.all products

**Comment by MaoPann** [comment]
If you don't develop all the source code.Whether the source code can be provided after purchasing the license.

**Comment by cardigliano** [comment]
@MaoPann ntopng Community, nDPI, n2n, PF_RING (and some other) are open source and you can find the code on github. For commercial products like n2disk or ntopng Enterprise (extensions to the Community) we do not provide the source code, the license does not include it.
