### ISSUE TITLE
libpcap timeout is ignored.

### ISSUE THREAD

**Issue by EaseTheWorld** [ntop/PF_RING#656]
Environment
RHEL 7.4
pfring-aware libpcap 1.8.1 installed from PF_RING-dev-7dd96c4.
running zbalance_ipc -i ens4f1 -c 100 -n 4 -m 2
no input traffic in ens4f1.

I found another libpcap issue that timeout is ignored.

test pseudo code is like below.
pcap_open_live("zc:100@0", 65536, 1, NULL)  -> while(running) pcap_next_ex() -> pcap_close
SIGINT handler just set running = 0 (not using pcap_breakloop because timeout is 1ms)
pcap_next_ex is supposed to return immediately but it hangs forever which means timeout is not applied.

real code about pcap handle setting is in https://github.com/LibtraceTeam/libtrace/blob/master/lib/format_pcap.c#L281

**Comment by cardigliano** [comment]
Fixed in pf_ring 7.7 (dev). A new stable will be released in a few days.
