### ISSUE TITLE
Add support for Arista/Metamako Metwatch trailer

### ISSUE THREAD

**Issue by dimitrijepetrovic** [ntop/PF_RING#658]
Arista 7130 devices have a way of providing ultra accurate timestamps to sub-ns level. 
The clock stability is much higher than Arista switch timestamps and the trailer is considerably simpler, i.e. no need for key frames.

The trailer description is as follows:
https://www.arista.com/assets/data/pdf/Whitepapers/Overview_Arista_Timestamps.pdf

**Comment by cardigliano** [comment]
Timestamp support has been implemented. Device ID and Port ID need to be added to the packet header.

**Comment by cardigliano** [comment]
port_id and device_id have been added to the extended header
