### ISSUE TITLE
PF_RING ZC Rate?!

### ISSUE THREAD

**Issue by mahdi1001** [ntop/PF_RING#66]
Hi 
We create 10Gb/s traffic with 64 byte packet size and send it.
In other machine receive data with pf_ring_zc .
 ./zpipeline -i zc:eth2 -c 99 -g 2:3.
But 5.7 Gb/s received.  
Absolute Stats: 17'165'841 pkts - 1'441'930'644 bytes
Actual Stats: 8'581'651.19 pps - 5.77 Gbps
###### 
# ./zpipeline_ipc -i "zc:eth10;0" -o "zc:eth12;0" -n 1 -c 11

Absolute Stats: Recv 17'069'204 pkts [Drop 13'410'270 pkts] Processed Q0 17'069'056 pkts AVG 17'069'056 pkts [Drop 5 pkts]
Actual Stats: Recv 8'530'331.63 pps Processed AVG 8'530'227.64 pps
###### 

this result is correct?!!!
You said with zero copy received "line rate" .
Please help me. what is wrong?
 Is it possible received 10Gb/s with 64 byte packet size ???

**Comment by cardigliano** [comment]
Hi
please check with pfcount or zcount the ingress rate, 
I think there is a bug in zpipeline_ipc but let's check with pfcount as first step, then we figure out what's happening with zpipeline_ipc

**Comment by mahdi1001** [comment]
Hi Alfredo
I used zcount but I received 5.7Gbps . Also with zsend send 8.92 Gbps, 13.3 Mpps !!!

top:
  PID      USER      PR   NI      VIRT       RES      SHR S         # *\* %CPU *\*    %MEM       TIME+ COMMAND  
 8052      root         20    0     149456     2904     1860 S           # *_40.6  *_         0.0            0:08.98 zcount     

# ./zcount -i zc:eth10 -c 11 -g 2

Absolute Stats: 16'983'700 pkts (12'783'302 drops) - 1'426'630'800 bytes

# Actual Stats: 8'490'406.92 pps (6'390'612.79 drops) - 5.71 Gbps

# ./zcount -i zc:eth10 -c 11 -g 4  -S 8

Absolute Stats: 18'820'901 pkts (14'026'381 drops) - 1'580'955'684 bytes
Thresholds: 18805913 pkts <1.500usec 14953 pkts >2.500usec

# Actual Stats: 8'527'083.67 pps (6'354'434.60 drops) - 5.73 Gbps

############################################ 

# ./zsend -i zc:eth12 -c 11 

Absolute Stats: 66'382'422 pkts - 5'576'123'448 bytes

# Actual Stats: 13'271'845.13 pps - 8.92 Gbps

######################################

cat /proc/net/pf_ring/info 
PF_RING Version          : 6.2.0 (unknown)
Total rings              : 0

Standard (non DNA/ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Quick
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

cat /proc/net/pf_ring/dev/eth10/info 
Name:              eth10
Index:             13
Address:           00:10:F3:3D:AF:8A
Polling Mode:      NAPI/ZC
Type:              Ethernet
Family:            Intel ixgbe 82599
Max # TX Queues:   1

# Used RX Queues:  1

Num RX Slots:      8192
Num TX Slots:      8192

root@debian:/PF_RING-6.2.0-stable/userland/examples_zc# ethtool eth10
Settings for eth10:
    Supported ports: [ FIBRE ]
    Supported link modes:   10000baseT/Full 
    Supported pause frame use: No
    Supports auto-negotiation: No
    Advertised link modes:  10000baseT/Full 
    Advertised pause frame use: Symmetric
    Advertised auto-negotiation: No
    Speed: 10000Mb/s
    Duplex: Full
    Port: FIBRE
    PHYAD: 0
    Transceiver: external
    Auto-negotiation: off
    Supports Wake-on: d
    Wake-on: d
    Current message level: 0x00000007 (7)
                   drv probe link
    Link detected: yes

root@debian:/PF_RING-6.2.0-stable/userland/examples_zc# ethtool -i eth10
driver: ixgbe_ZC
version: 4.1.5
firmware-version: 0x800000cb
bus-info: 0000:08:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

what is the problem?!!

**Comment by cardigliano** [comment]
It seems the application is not able to capture all the traffic, probably due to hw limitations. What is the 1. cpu model (please provide /proc/cpuinfo), 2. memory (please provide dmidecode), PCIe version and number of lanes in the slot you are using(dmesg grep 0000:08:00.0)?
Are you ending traffic from the same machine? If yes, could you try sending from another machine to save memory bandwidth?

**Comment by mahdi1001** [comment]
Intel® Xeon® Processor X5690 (12M Cache, 3.46 GHz, 6.40 GT/s Intel® QPI)
Ram 32G DDR3
ixgbe 0000:08:00.0
ixgbe 0000:08:00.1

```
       *-network:0
            description: Ethernet interface
            product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
            vendor: Intel Corporation
            physical id: 0
            bus info: pci@0000:08:00.0
            logical name: eth10
            version: 01
            serial: 00:10:f3:3d:af:8a
            size: 10Gbit/s
            width: 64 bits
            clock: 33MHz
            capabilities: pm msi msix pciexpress vpd cap_list ethernet physical fibre
            configuration: autonegotiation=off broadcast=yes driver=ixgbe driverversion=4.1.5 duplex=full firmware=0x800000cb latency=0 link=no multicast=yes port=fibre promiscuous=yes speed=10Gbit/s
            resources: irq:16 memory:fbe20000-fbe3ffff ioport:e020(size=32) memory:fbe44000-fbe47fff
       *-network:1
            description: Ethernet interface
            product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
            vendor: Intel Corporation
            physical id: 0.1
            bus info: pci@0000:08:00.1
            logical name: eth11
            version: 01
            serial: 00:10:f3:3d:af:8b
            size: 10Gbit/s
            width: 64 bits
            clock: 33MHz
            capabilities: pm msi msix pciexpress vpd cap_list ethernet physical fibre
            configuration: autonegotiation=off broadcast=yes driver=ixgbe driverversion=4.1.5 duplex=full firmware=0x800000cb latency=0 link=no multicast=yes port=fibre promiscuous=yes speed=10Gbit/s
            resources: irq:17 memory:fbe00000-fbe1ffff ioport:e000(size=32) memory:fbe40000-fbe43ff
```

Machine A send to B, and B just receive traffic.
A->B
A Send 8.9 G and B Receive 5.6 G

**Comment by cardigliano** [comment]
This CPU is a bit old, however it should be fast enough to capture 10G, please provide:
1. dmidecode | grep "Speed|Locator”
2. dmesg | grep 0000:08:00.0 | grep "PCI|GT/s"

Alfredo

**Comment by mahdi1001** [comment]
```
Max Speed: 4000 MHz
Current Speed: 2660 MHz
Speed: Unknown
Speed: Unknown
Max Speed: 4000 MHz
Current Speed: Unknown
Locator: A1_DIMM0
Bank Locator: A1_Node0_Channel0_Dimm0
Speed: Unknown
Locator: A1_DIMM1
Bank Locator: A1_Node0_Channel0_Dimm1
Speed: Unknown
Locator: A1_DIMM2
Bank Locator: A1_Node0_Channel1_Dimm0
Speed: Unknown
Locator: A1_DIMM3
Bank Locator: A1_Node0_Channel1_Dimm1
Speed: Unknown
Locator: A1_DIMM4
Bank Locator: A1_Node0_Channel2_Dimm0
Speed: Unknown
Locator: A1_DIMM5
Bank Locator: A1_Node0_Channel2_Dimm1
Speed: Unknown
Locator: A2_DIMM0
Bank Locator: A2_Node1_Channel0_Dimm0
Speed: 1333 MHz
Locator: A2_DIMM1
Bank Locator: A2_Node1_Channel0_Dimm1
Speed: Unknown
Locator: A2_DIMM2
Bank Locator: A2_Node1_Channel1_Dimm0
Speed: 1333 MHz
Locator: A2_DIMM3
Bank Locator: A2_Node1_Channel1_Dimm1
Speed: Unknown
Locator: A2_DIMM4
Bank Locator: A2_Node1_Channel2_Dimm0
Speed: 1333 MHz
Locator: A2_DIMM5
Bank Locator: A2_Node1_Channel2_Dimm1
Speed: Unknown
```

[    0.810231] pci 0000:08:00.0: Signaling PME through PCIe PME interrupt
[    5.739307] ixgbe 0000:08:00.0: PCI Express bandwidth of 16GT/s available
[    5.739308] ixgbe 0000:08:00.0: (Speed:2.5GT/s, Width: x8, Encoding Loss:20%)

**Comment by cardigliano** [comment]
It seems you have a numa system, please also provide the output of lstopo

**Comment by mahdi1001** [comment]
What's the "lstopo"?!!

**Comment by cardigliano** [comment]
http://manpages.ubuntu.com/manpages/quantal/man1/lstopo.1.html

**Comment by mahdi1001** [comment]
Excuse me ! My Cpu in this machine is X5650.
cat /proc/cpuinfo

processor   : 11
vendor_id   : GenuineIntel
cpu family  : 6
model       : 44
model name  : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping    : 2
microcode   : 0xc
cpu MHz     : 2666.845
cache size  : 12288 KB
physical id : 1
siblings    : 12
core id     : 10
cpu cores   : 6
apicid      : 53
initial apicid  : 53
fpu     : yes
fpu_exception   : yes
cpuid level : 11
wp      : yes

lstopo
 Machine (32GB)
 Socket L#0 + L3 L#0 (12MB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#6)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#1)
      PU L#3 (P#7)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#2)
      PU L#5 (P#8)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#3)
      PU L#7 (P#9)
    L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
      PU L#8 (P#4)
      PU L#9 (P#10)
    L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
      PU L#10 (P#5)
      PU L#11 (P#11)
  HostBridge L#0
    PCIBridge
      PCI 8086:10fb
        Net L#0 "eth10"
      PCI 8086:10fb
        Net L#1 "eth11"

**Comment by cardigliano** [comment]
A1_Node0_Channel0_Dimm0

**Comment by cardigliano** [comment]
Please try moving the memory banks to match the following slots in dmidecode:

Bank Locator: A1_Node0_Channel0_Dimm0
Bank Locator: A1_Node0_Channel1_Dimm0
Bank Locator: A1_Node0_Channel2_Dimm0

This is what you have now:
Bank Locator: A2_Node1_Channel0_Dimm0
Speed: 1333 MHz
Bank Locator: A2_Node1_Channel1_Dimm0
Speed: 1333 MHz
Bank Locator: A2_Node1_Channel2_Dimm0
Speed: 1333 MHz

**Comment by mahdi1001** [comment]
I have 1 CPU, and don't chanege A2_Node1 to A1_Node0.
For this change must be move CPU to other slot and all RAMs move to other slots.
Are u sure ?
Also System boot if slot1 CPU exist.

**Comment by cardigliano** [comment]
If you are sure about the hw setup, keep using the same configuration. It looks strange (at least from dmidecode) you are using the second node only, usually you are allowed to use the first node only or both nodes. However from the ZC performance it seems this system has some hw limitation affecting memory bandwidth.
