### ISSUE TITLE
Problem with UDP fragmented packets in the 1473-1497 bytes range

### ISSUE THREAD

**Issue by zinosat** [ntop/PF_RING#660]
I'm working on a pf_ring application and noticed a problem with fragmented packets whose length is in the range [1473-1497] bytes: pfring reports the wrong packet size when packets fall in that range.
Our custom protocol, has a 12bytes transport header:

 - 8bytes contain a timestamp
 - 4bytes contain the length of the following payload

The application checks that the length written in the header matches the actual payload length: if not, packet is discarded.

The check is performed comparing the 4bytes in the transport header with:

 hdr.caplen - (hdr.extended_hdr.parsed_pkt.offset.payload_offset + 12)

[frag.zip](https://github.com/ntop/PF_RING/files/5322119/frag.zip)

I'm attaching a few packets forged to reproduce the problem.

pf_ring module is loaded with "enable_ip_defrag=1": 
I've reproduced the problem both with 7.6.0 (7555836c28e49173df2ebb1cde89f08b940af604) and recent dev (aba31bfc147fca3bd8b214b5087681f7077bd713)

thank you for the support,
Davide

**Comment by cardigliano** [comment]
@zinosat please check my fix

**Comment by zinosat** [comment]
@cardigliano works great, thank you!
