### ISSUE TITLE
[BPF, split, API] Add the possibility to easily split traffic with BPF filters

### ISSUE THREAD

**Issue by gianogli** [ntop/PF_RING#661]
Hi,
I need to split the traffic on different queues by using BPF filters consistently.
I read the ZC APIs but I haven't find any function to do that in a easily way without using a lot CPU (yes, I know, BPF filters are CPU expensive, but some optimization could be useful).

Now we have a zc interface (zc:0@0) used as input queue for a zbalance_ipc process that mirror (fan-out) the traffic on 2 zc queues (zc:1@0, zc:1@1). On zc:1@0 we need the filtered zc:0@0 traffic while on zc:1@1 we need what remains. To do that we are applying 2 filters to these queues:

1) "(udp and (host 192.168.1.1 and host 8.8.8.8) or (host 192.168.1.2 and host 1.1.1.1)  or (host 192.168.1.10 and host 8.4.4.8))"
2) "not (udp and (host 192.168.1.1 and host 8.8.8.8) or (host 192.168.1.2 and host 1.1.1.1)  or (host 192.168.1.10 and host 8.4.4.8))"

As you can see the filter 2) is only the 1) denied.

This approach use a lot of CPU because we have to filter the same traffic 2 times with 2 different BPF filters. I think you can improve this behavior by implementing an API that just split the traffic in 2 queues . When a packet arrive to the filter, in fact, you have to check it only one time: if the packet matches the filter you can route it to queue1 (in our case  zc:1@0), if not to queue2 (zc:1@1). 
What do you think? Could you implement this useful API function? Is there another way to implement this behavior (without new API functions) that I haven't discovered until now? :-)

Thanks...

**Comment by cardigliano** [comment]
@gianogli what you need is to evaluate the bpf filter in the distribution function (see distr_func which is provided to pfring_zc_run_balancer_v2 in zbalance_ipc.c) and set the queue according to the verdict

**Comment by gianogli** [comment]
Ok, I understood.
Have I to directly use the bpf api functions from libpcap? (pcap/bpf.h)
Thanks

**Comment by cardigliano** [comment]
Yes (look at userspace_bpf in pfring.c for an example)
