### ISSUE TITLE
7.8.0-stable on what nDPI it's based on?

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#668]
I tried with latest stable nDPI 3.2-stable and got:

*** ndpi library version mismatch (expected 3514 found 6732) ***

@lucaderi @cardigliano

**Comment by cardigliano** [comment]
I will push an update right now, and I will include the major version in the warning

**Comment by vitalivanov** [comment]
please. it would be good to have a table of mapping pfring to ndpi...

**Comment by cardigliano** [comment]
I pushed an update both for stable and dev. It should print a more comprensive error now.

**Comment by vitalivanov** [comment]
*** ndpi library version mismatch, expected API rev.3514 (3.4.0) found rev.1397 (3.4.0) ***

This is with the latest ndpi 3.4-stable and PF_RING 7.8.0-stable.

What are the revs difference?

**Comment by cardigliano** [comment]
Are you compiling from source code? Did you run autogen before recompiling?

**Comment by vitalivanov** [comment]
Yes, full rebuild from source code for both.
Here is my current output:

*** ndpi library version mismatch, expected API rev.3514 (3.4.0) found rev.2501 (3.4.0) ***

Rev is different from the previous one.

Please check this....

**Comment by cardigliano** [comment]
Just to make sure: did you pull latest 3.4 commit?

**Comment by vitalivanov** [comment]
I use 3.4-stable branch and latest commit inside

**Comment by cardigliano** [comment]
@vitalivanov did you install it? The API revision should be 3514

**Comment by vitalivanov** [comment]
What is api revision? Where to check it in code?

Our build is in docker for target OS. And we do not install but just link as static libs.
So, it's not a problem of what is installed w/ what you build

**Comment by cardigliano** [comment]
Please check NDPI_API_VERSION in src/include/ndpi_api.h (generated from ndpi_api.h.in)

**Comment by vitalivanov** [comment]
https://github.com/ntop/nDPI/pull/1045

**Comment by cardigliano** [comment]
Thank you for the patch, it has been merged
