### ISSUE TITLE
[pf_ring_ft] license format is changed.

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#670]
@cardigliano 
Old license was like:
```
7.5.0.190227
3D9873D19206AAF2
Maintenance for this license will expire on Tue, 31 Mar 2020 02:00:00 +0200
A4C226F49102DC2EFBE8C64451F20C1A1585612800849B1C2F
```

New format is like:
```
7.8.0.201027
3D9873D19206AAF2
Maintenance for this license will expire on Fri, 08 Jan 2021 16:09:55 +0100
JX+m3qejSXIgntb3fAv35+JII4y9Hla348Q9xP/eHwPTiZodPhqADLzs1dieipCnPb7AB1Nm/+h02AKTw0vE9i30oqw6GkgP0i0SKNnPDO74BKnDjSRnQA2EIjQRdK3N60xrppXYCaf8fieSGqfCO/GAy1teBcSeejnMv+2CpD2JO27UazWDOH7AsZckJgeYf43tQV1/wRE5Xt6qDehwadx5c+7k4rYQNX2N2JEJWKbJvQzlCMhm/1MYlE68SSAxqG3fXdzGpj8oePQqgwQ4iQCVgOCq/sx0zjhbA5RJUDaDG42WBgHJe/8iQLo5c3MaQc8lALf0KmYoQsOGqd4CJQ==
```

Why did you change it?
All old licenses are not valid anymore?

**Comment by cardigliano** [comment]
@vitalivanov we changed the license format, however the old format should still work for licenses under maintenance. Are you experiencing any issue?

**Comment by vitalivanov** [comment]
@cardigliano license A4C226F49102DC2EFBE8C64451F20C1A1585612800849B1C2F was used on one of my servers.
It's not valid anymore, but I'm not sure if it's just expired or because of some failures?
Can you check your records for this license?

**Comment by cardigliano** [comment]
Yes the maintenance for A4C226F49102DC2EFBE8C64451F20C1A1585612800849B1C2F expired on March 31

**Comment by vitalivanov** [comment]
OK, thanks. I will let you know if any other problems...

**Comment by vitalivanov** [comment]
But this is maintenance... is license still supposed to be valid after maintenance period?
So, we buy a license for 2-3 months in other case? I suppose it should be valid for years...

**Comment by cardigliano** [comment]
The license is permanent if you do not update the software, otherwise the validity is 1y. Please see https://www.ntop.org/support/faq/are-licenses-permanent-what-about-maintenance/
