### ISSUE TITLE
zeek:multiple entries with PF_RING-7.6.0 and 7.8.0

### ISSUE THREAD

**Issue by AspirePig** [ntop/PF_RING#673]
I am currently using ZEEK 3.0.6. When I configure 10 cores for the NIC, my log also records 10 of the same records
Only gigabit network card will appear this situation, 10 Gigabit network card does not repeat
My configuration is as follows：
cat node.cfg
```
[logger]
type=logger
host=localhost

[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=enp134s0f0
lb_method=pf_ring
lb_procs=10
pin_cpus=1,2,3,4,5,22,23,24,25,26
```

cat zeekctl.cfg 
```
## Global ZeekControl configuration file.
###############################################
# Mail Options
# Recipient address for all emails sent out by Zeek and ZeekControl.
MailTo = root@localhost
env_vars=PCAP_PF_RING_CLUSTER_ID=99
PFRINGClusterID=99
```
When I execute the following command, the data is not filtered out
```
# cat /proc/net/pf_ring/* | grep 99
```

This problem appeared after 7.5.0

**Comment by cardigliano** [comment]
@AspirePig please update to latest github code and let me know if something changes
