### ISSUE TITLE
PFRing ZC compatibility with Emulex card (driver be2net)

### ISSUE THREAD

**Issue by jatin152** [ntop/PF_RING#676]
Hi 

Does PFRing ZC support below NIC card? 
If not, is there any scope for developing a compatible ZC driver for this card?

Product: OneConnect NIC (Skyhawk)
vendor: Emulex Corporation
driver=be2net

Regards,
Jatin

**Comment by cardigliano** [comment]
@jatin152 this adapter is not supported, and there is no plan for that in the short term.
