### ISSUE TITLE
Change NIC mtu in zc

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#679]
@cardigliano 

Hi cardigliano, I want to recv big packet which frame.len > 1800, set with

> ifconfig p5p2 mtu 2000

use follow can not recv any packet 

> zcount -i zc:p5p2 

,but without zc can recv all, 

> zcount -i p5p2 

does zc have a param to set recv mtu ?

**Comment by cardigliano** [comment]
Setting the interface MTU should be enough, what is the adapter model?
