### ISSUE TITLE
Triple vlan tags not reconstructed correctly

### ISSUE THREAD

**Issue by tturner** [ntop/PF_RING#680]
Hi,

For traffic tagged with 3 layers of vlans, the code in kernel/pf_ring.c:parse_pkt() doesn't reconstruct the outer vlan tag so it is inaccessible to code using pf_ring.

Apparently for inbound vlan-tagged data, the outer layer is stripped by the kernel even if you disable this from being accelerated in the network driver.

There is code in the kernel/pf_ring.c:parse_pkt() function which is intended to catch this and shuffles the vlans in the parsed packets and copies the stripped vlan tag back into place. Unfortunately the if statement for deciding when to do this is flawed.

It basically only runs the recovery if there is no vlan_id or no qinq_vlan_id field in the parsed header. For triple tagged packets, both of these fields are present as they are the 2 inner vlans.

I tested this by commenting out this test and it does restore the outer layer, however it has then overwritten the innermost tag. For code that uses these headers this is probably therefore not quite the desired fix. I am also not sure if it shuffles the rest of the header correctly.

This is the line I'm referring to:
https://github.com/ntop/PF_RING/blob/af6f3232bb17d059d83b93c6f36a568b8ba551c6/kernel/pf_ring.c#L2568

I wonder if the real fix needs to be in parse_raw_pkt() as there is clearly code for handling further nesting, but the reconstruction of the kernel parsed vlan tag is not being done at that point..

https://github.com/ntop/PF_RING/blob/af6f3232bb17d059d83b93c6f36a568b8ba551c6/kernel/pf_ring.c#L2141

**Comment by tturner** [comment]
On reflection I thought I should add some more info on my testing of this to make this as easy as possible to reproduce:
Debian 10 Buster 
Kernel 4.19

Network interface types tested:
* veth (easy way to test rx traffic on a single box):
ip link add send_here type veth peer name receive_here

* physical (what I had available on my test laptop): realtek 8152-based USB

I have run this on all interfaces involved to attempt to disable hw accelerated vlan stripping:
ethtool -K rxvlan off txvlan off

I understand that the physical interface I used is not technically listed as supported but the veth type is the kind of thing that could be used by containers so I think that probably should be made to work correctly.

Here is a snippet to use scapy to add/generate multiple layers of vlan:
```
e = Ether()
for vid in [10,20,30]:
    e = e/Dot1Q(vlan=vid)
# Add IP layer after this
```

My methodology:
Prep:
tcpdump and pfcount on the send interface
tcpdump and pfcount on the receive interface

Test:
scapy send on the send interface with 3 layers of vlan 10,20,30

Observe:
tcpdump (send): vlan 10, vlan 20, vlan 30
pfcount (send): vlan 10, qinq-vlan 20 (it doesn't display third layer)
tcpdump (receive): vlan 10, vlan 20, vlan 30
pfcount (receive): vlan 20, qinq-vlan 30 (1st layer missing)

Also, I observe that the reported caplen/len in pfcount on the receive interface is 4 bytes shorter than the reported length by tcpdump on both interfaces and than the reported caplen/len by pfcount on the send interface.

If I repeat the tests with scapy only sending 2 layers of vlan (or 1 layer), the send and receive observations match each other and so are correct.


The more I look a the code, the more confused I get about why the patch I made (commenting out the if at 2568) fixed things. The oddest bit for me is that I don't get how it fixes vlan in the raw bytes too. I am not particularly familiar with the pfring source code though - I only started looking at it when I encountered this issue.

**Comment by cardigliano** [comment]
@tturner I pushed a fix for this, please let me know if it works for you (sorry for the delay)

**Comment by tturner** [comment]
Hi @cardigliano yes I can confirm that this works for me (primarily interested in not losing the raw data) - both in pfcount and also in my own code. 

I am not using the derived headers so I can't comment on whether it does the right thing there (or whether anyone using those headers cares).

Thanks very much for fixing this.

Regards,

Tom

**Comment by cardigliano** [comment]
Thank you
