### ISSUE TITLE
PF_RING 7.8.0 likely macro conflict with boost/date_time/v1.71

### ISSUE THREAD

**Issue by linuzlover** [ntop/PF_RING#681]
Hi, 

I am including PF_RING into my application.
In userland/lib/pfring.h I see the following macro definition:

```
/* ********************************* */

#ifndef likely
#define likely(x)       __builtin_expect((x),1)
#endif

#ifndef unlikely
#define unlikely(x)     __builtin_expect((x),0)
#endif

/* ********************************* */


```
This macro conflicts with the following header file in boost library v 1.71 where a static _likely_ function is defined:

`boost/date_time/special_values_parser.hpp`

Unfortunately, a compilation error arises when both these header files are used.

It seems to me that _likely_ macro function is used only internally within pf_ring library. Is it possible to move this macro into an internal only header file?

Thanks,
AP

**Comment by cardigliano** [comment]
In the meantime, could you #undef after including the header?

**Comment by linuzlover** [comment]
Yes, you are right. 
Undefining the macro works like a charm.

Thank you
