### ISSUE TITLE
[pf_ring_ft] pfring_ft_license() returns valid license, but expiration and maintenance are zeros

### ISSUE THREAD

**Issue by f0rget-the-sad** [ntop/PF_RING#685]
@cardigliano
```
"version": "7.8.0.201027"
"systemid": "A732E0E7B208AA9A"
License Key : a2PM2w5o+RtbR09Jl5cUJGpVUBghblr/r8ispmrvXd+AghvCdFa+eL27EvH0F3e9yD3S25sCzASz45qkgMs3soNOZsrX9ReF3WuJn9wBvU94rk9k966vqapgvwZWPliQglDgPGSdnRBqFFIq4DwjFSDqAXIzgovpt5hmZ18TDNsv1eQjbcsAxmMOZXXZF8qJVjeYsy503EggaZpcjSd8czBQmcOWZnr7b+YduEGqEq7gymfhEiL8m6l/mStIFaf5GRQxpTiWioUUQiyARRgqdebZOUizd9au7sCAoM5WMg0TNHGopHBOikbtqmR8cJvca6GLxO0s1xLbNRlek+UR1A==
```

Just want to clarify what  expiration and maintenance zero values means in terms of license type, because in [this example ](https://github.com/ntop/PF_RING/blob/dev/userland/examples_ft/ftflow.c) we print "license type: permanent" only if maintenance are greater then zero, else we print nothing about it's type.
So if both time values are zero and license is valid, is license type still permanent?

Also this license should still have maintenance time, is it really expired or it's bug in `pfring_ft_license`?

**Comment by cardigliano** [comment]
@f0rget I pushed a patch to print the below in case of expired maintenance:
License Type:  Permanent License
Maintenance:   Expired

**Comment by vitalivanov** [comment]
thanks
we will cherry pick it into our current tree
