### ISSUE TITLE
[pf_ring_ft] license length issue on old library versions...

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#686]
@cardigliano 

To follow up on:
https://github.com/ntop/PF_RING/issues/670

New license length is not a problem for new releases for us as we changed the length.
But old releases has defined length of license and it's less then 512. So, If we generate new license for old version of our SW based on older PF RING - we are in trouble and license won't be valid.

Are there any chances to get previous version of license length in case of older PF RING FT?

**Comment by cardigliano** [comment]
@vitalivanov what (old) version (including date) of FT are you referring to?
Also, the length of a license should be less than 512, even with new licenses, could you show me an example? (please provide the orderid in a private mail)

**Comment by vitalivanov** [comment]
@cardigliano 

Sorry for confusion. I somehow selected 512 as a number ...

Here is the example.

Version : 7.5.0.191118
Maintenance for this license will expire on Thu, 21 Jan 2021 16:43:03 +0100
System id: A73AC7A8B208AA9A

License is:
Du0mH7lSWyjHuh/WQqeqgWEbTQ7KiNy6sPbWnZpf+uSsZ+o0FE/LNkjVqeU5vmWkK3cH9bC4AWcGJDW6PS2oHJMV0mvMPbw/inMz3fF0vRSEogF1WUpeRAnrdP3F8lHKlGeg5V9/NYL73OHD7d68O6ABpWjZImOKkwUch1KWKqgwNdJnK1gHy4IibB03xGCAD+1b1zPvs7q63aM/ZqssJihzDm/YN9FlgQYaa02zSioii2wWvlx0Ms1ACCz+Z1ocyvZXbVgBH8JTOFDywGLNWY1CCG8Utr4G5GdXfHZJZrvzhQaHrGOKumAANJdMq5YVz8fPvXrl4Cx6y9W2aS+41A==

```
$ echo "Du0mH7lSWyjHuh/WQqeqgWEbTQ7KiNy6sPbWnZpf+uSsZ+o0FE/LNkjVqeU5vmWkK3cH9bC4AWcGJDW6PS2oHJMV0mvMPbw/inMz3fF0vRSEogF1WUpeRAnrdP3F8lHKlGeg5V9/NYL73OHD7d68O6ABpWjZImOKkwUch1KWKqgwNdJnK1gHy4IibB03xGCAD+1b1zPvs7q63aM/ZqssJihzDm/YN9FlgQYaa02zSioii2wWvlx0Ms1ACCz+Z1ocyvZXbVgBH8JTOFDywGLNWY1CCG8Utr4G5GdXfHZJZrvzhQaHrGOKumAANJdMq5YVz8fPvXrl4Cx6y9W2aS+41A==" | wc -c
345
```
So, new license is 345 characters long.

Old licenses were ~51 characters:
```
$ echo "B7A5F0AF34C95A6428E4404DE8B2F4301585612800B7191E3B" | wc -c
51
```

You know that we use pf_ring as a library. So, in our SW that is using the pf_ring_ft library we are taking license from user input and string is limited per old license format.

So, when we try to load new string to old SW - we can not do that.

Can we have license generator page to produce old style licenses for old pf_ring_ft versions?

**Comment by cardigliano** [comment]
@vitalivanov I am afraid this is not possible, we moved all our license system to this new format, and even if we provide you an old style license, a software update would break them as they are no longer supported.

**Comment by vitalivanov** [comment]
It leads us to the point that our old SW versions based on pf_ring_ft - we can not generate a license for them anymore.
and if customers wants to active ntop functionality - we need to ask to upgrade our SW to the latest with new license style support.
That's generally bad handling of library and support for companies that use it.

I'm not sure what other options we have...

**Comment by cardigliano** [comment]
@vitalivanov please also note that the software version the customer is running is no longer supported anyway as it is too old..
