### ISSUE TITLE
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.

### ISSUE THREAD

**Issue by gianogli** [ntop/PF_RING#691]
I tried to build the sources with the command `make -j16 all` but I see a lot of `make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.` messages:
```# make -j16 all
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/local/src/pfring/kernel'
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/local/src/pfring/drivers'
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/local/src/pfring/userland'
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/local/src/pfring/userland/tcpdump-4.9.3'
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/local/src/pfring/userland/libpcap-1.9.1'
[...]
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/local/src/pfring/userland/lib'
[...]
```
It seems that is not possible use the option -jN to specify the number of jobs to run simultaneously.

To solve this "issue" I found this [article](https://stackoverflow.com/questions/60702726/warning-jobserver-unavailable-using-j1-add-to-parent-make-rule).

I made some tests and this warning message disappears (and -j16 option works) by changing the command `make` with `$(MAKE)` into all the `Makefile`.

Could you verify this behavior and change all the `Makefile` accordingly?

Thanks... :-)

**Comment by cardigliano** [comment]
Fixed. Thank you.
