### ISSUE TITLE
problem building Mellanox module

### ISSUE THREAD

**Issue by michael-clarke** [ntop/PF_RING#695]
When I try to build the Mellanox module the following error is seen.

`$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ibv_open_device in -libverbs... yes
checking Mellanox support... yes
configure: creating ./config.status
config.status: creating Makefile

$ make
rm -f ./.depend
gcc  -O2  -Wall -fPIC -I../../../kernel -I../../nbpf -I../../lib -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -MM pfring_mod_mlx.c>>./.depend;
gcc  -O2  -Wall -fPIC -I../../../kernel -I../../nbpf -I../../lib -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -c pfring_mod_mlx.c -o pfring_mod_mlx.o
pfring_mod_mlx.c: In function ‘pfring_mlx_enable_ring’:
pfring_mod_mlx.c:490:10: error: ‘pfring’ {aka ‘struct __pfring’} has no member named ‘mtu_len’
   if(ring->mtu_len == 0) ring->mtu_len = 1536;
          ^~
pfring_mod_mlx.c:490:30: error: ‘pfring’ {aka ‘struct __pfring’} has no member named ‘mtu_len’
   if(ring->mtu_len == 0) ring->mtu_len = 1536;
                              ^~
pfring_mod_mlx.c:493:39: error: ‘pfring’ {aka ‘struct __pfring’} has no member named ‘mtu_len’
   if(mlx_configure_qp(&mlx->ring, ring->mtu_len, mlx->num_entries, mlx->port_num)) {
                                       ^~
pfring_mod_mlx.c:504:34: error: ‘pfring’ {aka ‘struct __pfring’} has no member named ‘mtu_len’
   if(mlx_recv_post_wqes(mlx, ring->mtu_len))
                                  ^~
make: *** [Makefile:46: pfring_mod_mlx.o] Error 1`

**Comment by cardigliano** [comment]
@michael-clarke please note this module is deprecated. If you want to revamp it, feel free to send a PR.
