### ISSUE TITLE
pfring_open error [No such device] (pf_ring not loaded or interface eth4 is down ?)

### ISSUE THREAD

**Issue by w2n1ck** [ntop/PF_RING#696]
[root@sh1-arch-1 examples]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

[root@sh1-arch-1 examples]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 14:18:77:6d:ff:ee brd ff:ff:ff:ff:ff:ff
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 14:18:77:6d:ff:ef brd ff:ff:ff:ff:ff:ff
4: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 14:18:77:6d:ff:f0 brd ff:ff:ff:ff:ff:ff
5: eth3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 14:18:77:6d:ff:f1 brd ff:ff:ff:ff:ff:ff
8: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether fa:f7:eb:9c:81:5b brd ff:ff:ff:ff:ff:ff
9: bond4: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9c:74:1a:77:50:13 brd ff:ff:ff:ff:ff:ff
    inet 10.3.1.252/24 brd 10.3.1.255 scope global bond4
       valid_lft forever preferred_lft forever
12: eth4: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond4 state UP group default qlen 1000
    link/ether 9c:74:1a:77:50:13 brd ff:ff:ff:ff:ff:ff
13: eth5: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond4 state UP group default qlen 1000
    link/ether 9c:74:1a:77:50:13 brd ff:ff:ff:ff:ff:ff

[root@sh1-arch-1 examples]# dmesg | grep Ethernet
[    3.353406] tg3 0000:01:00.0 eth0: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[    3.381535] tg3 0000:01:00.1 eth1: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[    3.402510] tg3 0000:02:00.0 eth2: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[    3.422403] tg3 0000:02:00.1 eth3: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[   17.019039] Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

[root@sh1-arch-1 examples]# lsmod |grep bonding
bonding               152979  0

[root@sh1-arch-1 examples]# modinfo bonding
filename:       /lib/modules/3.10.0-1127.el7.x86_64/kernel/drivers/net/bonding/bonding.ko.xz
author:         Thomas Davis, tadavis@lbl.gov and many others
description:    Ethernet Channel Bonding Driver, v3.7.1
version:        3.7.1

[root@sh1-arch-1 examples]# pf_ringcfg --list-interfaces
Name: bond0                Driver: bonding
Name: eth0                 Driver: tg3
Name: eth1                 Driver: tg3
Name: eth2                 Driver: tg3
Name: eth3                 Driver: tg3
Name: eth4                 Driver: ixgbe      [Running ZC]
Name: eth5                 Driver: ixgbe      [Running ZC]
Name: bond4                Driver: bonding

[root@sh1-arch-1 examples]# modinfo pf_ring
filename:       /lib/modules/3.10.0-1127.el7.x86_64/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
version:        7.9.0
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
retpoline:      Y
rhelversion:    7.8
srcversion:     519C96188C7A6461934C1A1

==============================================================

BUT i run
[root@sh1-arch-1 examples]# pfcount -i eth4
[PF_RING] Wrong RING version: kernel is 18, libpfring was compiled with 16
pfring_open error [No such device] (pf_ring not loaded or interface eth4 is down ?)
[root@sh1-arch-1 examples]# pfcount -i bond4
[PF_RING] Wrong RING version: kernel is 18, libpfring was compiled with 16
pfring_open error [No such device] (pf_ring not loaded or interface bond4 is down ?)

[root@sh1-arch-1 examples]# sudo pfcount -i zc:eth4
pfring_open error [No such device] (pf_ring not loaded or interface zc:eth4 is down ?)

what happend? what can i do?  
Please help me.

**Comment by cardigliano** [comment]
@w2n1ck please note you are using an old application (pfcount) version, with the latest pf_ring kernel module. Please update also the application.

**Comment by w2n1ck** [comment]
Yes, thank you！by the way, my NIC driver is using bonding, how do I configure this to enable PF?

**Comment by cardigliano** [comment]
There is no special configuration required to capture from a bond interface with pf_ring, just load the module
