### ISSUE TITLE
zeek polling mechanism and pfring compatibility

### ISSUE THREAD

**Issue by alessio-pascolini** [ntop/PF_RING#699]
From documentation:

> Latest recommended Zeek version is 3.0.7, newest Zeek release are using a packet polling mechanism which is not compatible with PF_RING ZC SPSC queues and some devices.

Could you give more details about that? 
What are the devices involved?

Thanks

**Comment by cardigliano** [comment]
@alessio-pascolini it seems they fixed this in 4.0, please read https://github.com/zeek/zeek/issues/1063
