### ISSUE TITLE
How to setup pfring ft to handle 500k active flows?

### ISSUE THREAD

**Issue by annp1987** [ntop/PF_RING#701]
Hello,

Currently, I'm build a application base on zc + pfring ft, Here is work flows: traffic-->zbalance_ipc--> 8 queues, 8 pfring_ft threads will consume packet from 8 queues. As the document said, pfring ft able to handle 500k active flows. However, i tested on my application, it seems pfring_ft able to handle 1000 active flows. Do you need any special setup for zc or pfring_ft to able to handle 500k active flows?

**Comment by cardigliano** [comment]
How did you found that pfring_ft can handle 1000 active flows? Please provide more details about your tests and results. Thank you.

**Comment by annp1987** [comment]
Thank you quick replied, 
Here is my test resutl: https://nowtransfer.de/ead2ebfb8c21
I used zsend cmd to send traffic like that zsend -i zc:enp6s0f0 -g 0 -r 10 -b 1000.
I tested with driver: ixgbe

**Comment by annp1987** [comment]
Hi @cardigliano,
We can achieve our target by rewrite the program. So I would like to close this issue.
Thank you.
