### ISSUE TITLE
AF_XDP: packet reading stops on 40g network card

### ISSUE THREAD

**Issue by MeneTelk0** [ntop/PF_RING#702]
Hello,

While configuring the reading of input packets using the `AF_XDP` module in `PF_RING`, I encountered a problem for which I have not yet been able to find the correct solution.

The problem is as follows - as soon as I load `pfcount` (`pfcount -i xdp:enp71s0f1@0`) with lots of traffic and try to use `pfcount` for some additional tasks (for example, printing some statistics to stdout), then after receiving a small number of packets `pfcount` stops counting input traffic. Moreover, the `pfcount` process itself does not end, but in the output statistics, the number of received packets does not increase.

### Test bench

The test bench I'm doing research for consists of two `Ubuntu` 18.04 (with 5.4.0 kernel) servers with Intel `XL710` NICs (i40e drivers), directly connected with a cable.

On one machine, I run: `pfsend -i zc:enp71s0f1 -n 0 -r 1000`

On the other: `pfcount -i xdp:enp71s0f1@0`

### Steps to reproduce
In `PF_RING/userland/lib/pfring_mod_af_xdp.c`, in function `pf_xdp_refill_queue`, right after loop `for (i = 0; i < reserve_size; i++)` you can add the following `printf` :

```c++
for (i = 0; i < reserve_size; i++) {
……
}
printf("\n Provided queues %d %d head: %d tail: %d \n", provided, reserve_size, umem->buff_q->head, umem->buff_q->tail);
```

Next, you need to run `make` in `PF_RING/userland/` and you are ready to go.

Run `pfcount -i xdp:enp71s0f1@0` and (probably, on the another machine, because it uses ZC) run `pfsend -i zc:enp71s0f1 -n 0 -r 1000` (send rate is approx 13.50 Gbps)
After a while, you’ll be able to see in the console output of the pfcount the following lines:

```
.......

 Provided queues 32 32 head: 93 tail: 4095

 Provided queues 32 32 head: 94 tail: 31

 Provided queues 32 32 head: 95 tail: 63

 Provided queues 32 32 head: 96 tail: 95

 Provided queues 1 32 head: 97 tail: 96

 Provided queues 1 32 head: 98 tail: 97

 Provided queues 1 32 head: 99 tail: 98

 Provided queues 1 32 head: 100 tail: 99

 Provided queues 1 32 head: 101 tail: 100

 Provided queues 1 32 head: 102 tail: 101

 Provided queues 1 32 head: 103 tail: 102

.......
```

After receiving approx 30 lines starting with **Provided queues 1** the receiving process stops and the counter doesn’t increment the number of received packets (while the sending process is still generating traffic):
```
.......

Provided queues 1 32 head: 129 tail: 128

 Provided queues 1 32 head: 130 tail: 129
=========================
Absolute Stats: [4'220 pkts total][0 pkts dropped][0.0% dropped]
[4'220 pkts rcvd][354'480 bytes rcvd][843.72 pkt/sec][0.57 Mbit/sec]
=========================
Actual Stats: [4'220 pkts rcvd][1'000.15 ms][4'219.35 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [4'220 pkts total][0 pkts dropped][0.0% dropped]
[4'220 pkts rcvd][354'480 bytes rcvd][703.13 pkt/sec][0.47 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.06 ms][0.00 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [4'220 pkts total][0 pkts dropped][0.0% dropped]
[4'220 pkts rcvd][354'480 bytes rcvd][602.70 pkt/sec][0.41 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.06 ms][0.00 pps][0.00 Gbps]
=========================

.......
```

If you will reduce sending rate of `pfsend` to smth around 1Gbps and restart `pfcount`, then everything will be OK. `pfcount` will be able to count input packets. But increasing rate to 10+ Gbps leads `pfcount` counters to stop.

### What may cause this problem:

As mentioned in `PF_RING/userland/lib/pfring_mod_af_xdp.c`, in function `pf_xdp_refill_queue` there is a problem with dequeuing of `buff_q`:
```c++
 /* FIXX what if we fail dequeueing reserve_size buffers reserved with xsk_ring_prod__reserve? */
```
As can be seen in the output above, the `buff_q` tail chases the `buff_q` head and at some point, they meet and we can’t do proper dequeuing.

Afterwards, on receive in `pfring_mod_af_xdp_recv_multi` function,`xsk_ring_cons__peek` always returns 0. And therefore, `pfring_mod_af_xdp_recv_multi` always returns 0.

### My ~~kludgy~~ fix for this problem:

In `PF_RING/userland/lib/pfring_mod_af_xdp.c`, in function `pf_xdp_refill_queue`

Instead of:
```c++
  if (pf_xdp_buff_q_dequeue(umem->buff_q, &addr) != 0)
   break;
```

I made:
```c++
  if (pf_xdp_buff_q_dequeue(umem->buff_q, &addr) != 0){
   provided = reserve_size;
   break;
  } 
```
When we are not able to make a proper dequeue, we just set the provided queues to the value of the `reserve_size`.
With this kludge, `pfcount` won’t stop receiving packages even on a very high load from `pfsend`. But the problem with `buff_q` tail chasing the head still occurs (if you’ll set the debugging for it), but doesn't affect the performance of `pfcount` and appears rarely.

**Comment by cardigliano** [comment]
@MeneTelk0 the AF XDP support has been reworked and improved, please check it now

**Comment by MeneTelk0** [comment]
Hello @cardigliano 

While testing your new AF_XDP implementation, I encountered some strange behaviour. 

### Both on Ubuntu 18.04 and 20.04:

When I don't use your custom zc i40e drivers, I get the following:
````
sudo ./pfcount -i xdp:enp71s0f1@0
pfring_zc_create_cluster error [No buffer space available]
pfring_open error [No buffer space available] (pf_ring not loaded or interface xdp:enp71s0f1@0 is down ?)
````
When I am setting up ZC drivers - pfcount starts working but doesn't receive any packets. So all the counters are stopped at 0.

Afterwards, if I remove your driver and set the default one, then pfcount starts working correctly. The performance of pfcount is the same as can be reached with the AF_XDP reader example from [xdp-tutorial/advanced03-AF_XDP](https://github.com/xdp-project/xdp-tutorial/tree/master/advanced03-AF_XDP).

### Only on Ubuntu 18.04:

When I load your ZC drivers and trying to run pfcount AF_XDP option, my system crashes. The only thing that helps is to reboot the PC manually. On Ubuntu 20.04 the system doesn't crash.

Btw, I noticed this problem before your updates too. Unfortunately, I hadn't tested it on Ubuntu 20.04. 

 ## Kinda suggested solution

Maybe it will be Ok to remove the following `ifdef` from `pfring_mod_af_xdp.c`:
````
#ifdef HAVE_PF_RING_ZC
````
Especially if without ZC drivers everything runs normally.

**Comment by cardigliano** [comment]
Hi @MeneTelk0, please note XDP support is disabled in our ZC drivers, please use vanilla drivers unless you need to use ZC.
The ifdef HAVE_PF_RING_ZC cannot be removed as the XDP module uses the ZC library memory manager for allocating packet buffers and work in zero-copy.

**Comment by MeneTelk0** [comment]
Thank you. Maybe information about the incompatibility of ZC drivers and AF_XDP should be listed in your docs. Or should be checked and warned somehow when trying to run RX with AF_XDP and ZC drivers loaded. Or both ;)

But still, the previously stated problem, when I can't use pfcount with the AF_XDP interface, persists. I'm not able to run it right after boot before doing the manipulations with the loading and unloading of ZC drivers.

**Comment by MeneTelk0** [comment]
So, running hugepages configuration from `load_driver.sh` fixes the problem:

````
HUGEPAGES_NUM=1024
HUGEPAGES_PATH=/dev/hugepages
sync && echo 3 > /proc/sys/vm/drop_caches
echo $HUGEPAGES_NUM > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
if [ `cat /proc/mounts | grep hugetlbfs | grep $HUGEPAGES_PATH | wc -l` -eq 0 ]; then
	if [ ! -d $HUGEPAGES_PATH ]; then
		mkdir $HUGEPAGES_PATH
	fi
	mount -t hugetlbfs nodev $HUGEPAGES_PATH
fi
HUGEPAGES_AVAIL=$(grep HugePages_Total /sys/devices/system/node/node0/meminfo | cut -d ':' -f 2|sed 's/ //g')
if [ $HUGEPAGES_AVAIL -ne $HUGEPAGES_NUM ]; then 
	printf "Warning: %s hugepages available, %s requested\n" "$HUGEPAGES_AVAIL" "$HUGEPAGES_NUM"
fi
````
I think this should also be stated somewhere. Because by default, solutions from the same [xdp-tutorial](https://github.com/xdp-project/xdp-tutorial) don't require hugepages configuration.

**Comment by cardigliano** [comment]
Thank you. I updated the doc. We can close this.
