### ISSUE TITLE
Loop : recv and send 

### ISSUE THREAD

**Issue by HumanToApe** [ntop/PF_RING#703]
hey, I'm a newbie with pf_ring and i would love some #help.
I'm trying to code a Man In The Middle (It's only in goal to pentest some tool).
So i tried  with the exemple pfbridge with  rx_and_tx direction and send_and_recv_mode for both of my device.
Then in the while, i did :

```
if(pfring_rcv(a_ring,&buffer,0,&hdr,1)>0)
{
int rc;
rc=pfring_send(b_ring,(char*) buffer,hdr.caplen,1);
}
if(pfring_rcv(b_ring,&buffer,0,&hdr,1)>0)
{
int rc;
rc=pfring_send(a_ring,(char*) buffer,hdr.caplen,1);
}
```

And then i tried to send 5 tcp packets on my eth1.
so, what happened:

A BIG LOOP!
During execution,I think my code send already sended packets and received packets on both device or something like that.
I'm using PF_RING 7.0 and can't change for the moment.

Best regards.
PS: sorry for my english and my pseudo.

**Comment by cardigliano** [comment]
@HumanToApe are you setting the capture direction to rx only? Otherwise you capture also transmitted packets, going in a loop

**Comment by HumanToApe** [comment]
@cardigliano i did it with rx_and_tx_direction and send_and_recv_mode then it was going in a loop.
So i tried to set in rx_only ( and send_and_recv_mode  ) as you said but it seems to work only in one direction... 

`pfring_set_direction(a_ring, rx_and_tx_direction);
pfring_socket_mode(a_ring, send_and_recv_mode);
pfring_set_direction(b_ring, rx_and_tx_direction);
pfring_socket_mode(b_ring, send_and_recv_mode);
`
my goal is to code the same thing than pfbridge.c with 2 interfaces but in both direction.
I need to be able to send and recv on the same interface without going in a loop :$

**Comment by HumanToApe** [comment]
So, i fixed it !
First thing, I updated my PF_RING to be able to use PF_RING_DISCARD_INJECTED_PKTS as a flag.
Then I used rx_only_direction and send_and_recv_mode as paremeters.
And finally , in my loop i used pfring_recv() with the last argument to 0 to avoid to be stuck until a packet is received.
 It would be great to add an example of MITM with PF_RING.

**Comment by cardigliano** [comment]
Great. It would be great if you want to contribute to the project sending a PR with an example. Thank you.
