### ISSUE TITLE
installing ntop but having these issues, using ubuntu 20 .04.1 LTS

### ISSUE THREAD

**Issue by adeelkhan-ak** [ntop/PF_RING#704]
Errors were encountered while processing:
 i40e-zc-dkms
 igb-zc-dkms
 fm10k-zc-dkms
 e1000e-zc-dkms
 pfring-drivers-zc-dkms
 ixgbe-zc-dkms

**Comment by cardigliano** [comment]
@adeelkhan-ak are you using stable or dev packages?

**Comment by adeelkhan-ak** [comment]
stable and  i removed all these packages and its working fine 
command  : sudo apt-get remove <pkg-name>

**Comment by cardigliano** [comment]
Please close the issue if it's working for you
