### ISSUE TITLE
Make fails when making e1000e driver

### ISSUE THREAD

**Issue by pico-martin** [ntop/PF_RING#705]
make fails when making the first Intel driver 
ERROR: modpost: "pf_ring_skb_ring_handler" [/home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/e1000e.ko] undefined!

- I've tried to make i40e separately but it also fails in a similar manner:
[pfring_make.txt](https://github.com/ntop/PF_RING/files/6295139/pfring_make.txt)

**Comment by cardigliano** [comment]
What OS are you running?

**Comment by pico-martin** [comment]
Ubuntu 20.04, kernel 5.8.0-48-generic

**Comment by pico-martin** [comment]
root@1hu-server:/home/martin/pcaps# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by cardigliano** [comment]
@pico-martin the same seems to be working for me, however Ubuntu 20 LTS should have a 5.4 kernel, while you have 5.8 which is not currently supported. Did you install an Ubuntu Server LTS?

**Comment by pico-martin** [comment]
I installed Ubuntu 20.04.2 LTS which has the 5.8 kernel - I checked the repo beforehand and saw comments for kernel 5.9 so thought it would be ok. I will step back to Ubuntu 20.04.1 LTS, kernel 5.4 and try again - thanks

**Comment by pico-martin** [comment]
I installed Ubuntu 20.04.1 LTS and get the same problem: here are my steps:
1. install Ubuntu 200.04.1
2. install git
3. git clone https://github.com/ntop/PF_RING.git
4. cd PF_RING; install recommended apps from README.FIRST
apt-get install build-essential bison flex linux-headers-$(uname -r) libnuma-dev libnl-genl-3-dev
5. make or sudo make
I get the same failure at the same point:
make[5]: Entering directory '/home/martin/PF_RING/kernel'
make -C /lib/modules/5.8.0-48-generic/build M=/home/martin/PF_RING/kernel EXTRA_CFLAGS='-I/home/martin/PF_RING/kernel -DGIT_REV="\"dev:d5e557b5f9d99297b3a3c7cbb724ff38519d78f8\"" -no-pie -fno-pie -Wno-implicit-fallthrough' modules
make[6]: Entering directory '/usr/src/linux-headers-5.8.0-48-generic'
make[6]: Leaving directory '/usr/src/linux-headers-5.8.0-48-generic'
make[5]: Leaving directory '/home/martin/PF_RING/kernel'
cp ../../../../../kernel/Module.symvers .
*** The target kernel has CONFIG_MODULE_SIG_ALL enabled, but
*** the signing key cannot be found. Module signing has been
*** disabled for this build.
make[5]: Entering directory '/usr/src/linux-headers-5.8.0-48-generic'
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/ethtool.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/ich8lan.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/mac.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/nvm.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/phy.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/manage.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/80003es2lan.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/82571.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/param.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/ptp.o
  CC [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/kcompat.o
  LD [M]  /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/e1000e.o
WARNING: Symbol version dump "../../../../../kernel/Module.symvers" is missing.
         Modules may not have dependencies or modversions.
  MODPOST /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/Module.symvers
ERROR: modpost: "pf_ring_skb_ring_handler" [/home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/e1000e.ko] undefined!
ERROR: modpost: "pf_ring_zc_dev_handler" [/home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/e1000e.ko] undefined!
make[6]: *** [scripts/Makefile.modpost:111: /home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/Module.symvers] Error 1
make[6]: *** Deleting file '/home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src/Module.symvers'
make[5]: *** [Makefile:1696: modules] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-5.8.0-48-generic'
make[4]: *** [Makefile:84: default] Error 2
make[4]: Leaving directory '/home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc/src'
make[3]: *** [Makefile:4: all] Error 2
make[3]: Leaving directory '/home/martin/PF_RING/drivers/intel/e1000e/e1000e-3.8.7-zc'
make[2]: *** [Makefile:10: all] Error 2
make[2]: Leaving directory '/home/martin/PF_RING/drivers/intel'
make[1]: *** [Makefile:3: all] Error 2
make[1]: Leaving directory '/home/martin/PF_RING/drivers'
make: *** [Makefile:4: all] Error 2
[make_issue.txt](https://github.com/ntop/PF_RING/files/6296674/make_issue.txt)

**Comment by pico-martin** [comment]
sorry forget that - I see that my kernel is still updating to 5.8. I will try again.

**Comment by cardigliano** [comment]
This is strange: my Ubuntu 20.04.2 LTS (updated now) is actually running 5.4.0-70-generic, I will dig into this

**Comment by cardigliano** [comment]
It seems Ubuntu since 20.04.2 is autodetecting wether the HWE kernel (5.8) can be installed and doing that automatically. I think we should add support for it.

**Comment by pico-martin** [comment]
Ok, managed to revert to 5.4 by:
1. sudo apt remove linux-{image,headers}-generic-hwe-20.04
2. sudo apt install linux-generic
3. reboot and select 5.4 image
After this the PF_RING make works without a hitch.
you can close this issue now unless you want to maintain it as a 5.8 upgrade issue.
Thx for your help

**Comment by cardigliano** [comment]
Please keep this open as we need to support 5.8 at this point. Thank you.

**Comment by cardigliano** [comment]
Compilation on 5.8 has been fixed
