### ISSUE TITLE
Techniques for receiving rx/tx traffic bifurcated across two interfaces

### ISSUE THREAD

**Issue by rjo** [ntop/PF_RING#706]
I'm writing an application using ZC and I need to use an optical tap to monitor some traffic since my switch mirror drops packets at high rates. The optical tap splits the transmit and receive such that I need to use two interfaces, one for the rx and one for tx traffic.

I'm new to this kind of packet processing and I have not found any documentation that clearly describes the best techniques for ordering traffic like this.  How would you take packets from two interfaces that represent one aggregate flow (meaning the total flow passing through a switch port) such that the application processed them in the order they actually occurred?

My apologies if this has been answered elsewhere. I find the PF_Ring docs kinda scattered and have not seen anything that addresses this situation.

**Comment by cardigliano** [comment]
If you are using standard drivers, pf_ring supports traffic aggregation using comma-separated interface names (e.g. "eth1,eth2"), otherwise you need to open each interface separately and poll them in a round robin fashion. There is no guarantee about packet order as that would require hw support to mark the packets (e.g. nsec ts)

**Comment by rjo** [comment]
Would ixgbe be considered a standard driver?

**Comment by rjo** [comment]
And when you say there is no guarantee about packet order, does that apply to both the traffic aggregation and opening multiple interfaces with round robin polling?

**Comment by cardigliano** [comment]
Yes both

**Comment by rjo** [comment]
@cardigliano does pf_ring have any support for ordering if your interfaces support ieee 1588?

Is there a way I can reach you directly through ntop.org?
