### ISSUE TITLE
PF_RING with DPDK support

### ISSUE THREAD

**Issue by m-peko** [ntop/PF_RING#708]
Hi there,

First of all, thank you for your work.

I would like to know if PF_RING would work with DPDK library?

My assumption is that DPDK library would need to inject packets into PF_RING ZC framework. Then, PF_RING ZC does the load balancing of the packets. I would like to balance load depending on the protocol (Diameter, GTP-C, etc.). And finally PF_RING ZC provides packets to consumers.

Is it possible to have multiple consumers to the single ring? Or in case of a packet cluster, can multiple consumers read from the same member of a cluster? How does this work? Does packet stay in the queue until consumer gets it?

Is it possible to achieve this? Which example describes my case the best?

Thanks and best regards

**Comment by cardigliano** [comment]
> I would like to know if PF_RING would work with DPDK library?
> My assumption is that DPDK library would need to inject packets into PF_RING ZC framework. Then, PF_RING ZC does the load balancing of the packets. I would like to balance load depending on the protocol (Diameter, GTP-C, etc.). And finally PF_RING ZC provides packets to consumers.

You can combine the framework, but this requires a copy when moving a packet from one framework to the other as they have different memory management. I am wondering why you need to combine both.

> Is it possible to have multiple consumers to the single ring? Or in case of a packet cluster, can multiple consumers read from the same member of a cluster?

This requires locking, or multiple rings. Rings are single-consumer.

> How does this work? Does packet stay in the queue until consumer gets it?

Correct.

**Comment by m-peko** [comment]
@cardigliano thanks on your answers. I have more questions because it looks promising to me to replace DPDK with PF_RING now.

1. Regarding Napatech, is it possible to let Napatech do the filtering of the packets?
2. Furthermore, can we create multiple PF_RINGs to read packets from the same interface? Or does the one PF_RING take ownership of an interface while reading from it and none other application can use that interface?
3. If I have dozen of PF_RINGs that are reading packets from the same interface, would it cause a performance drop?

Thank you very much!

**Comment by cardigliano** [comment]
> 1. Regarding Napatech, is it possible to let Napatech do the filtering of the packets?

Yes, you can use the Napatech NTPL to program the adapter, or BPF filters through the PF_RING API (they are converted to NTPL, depending on the filter)

> 2. Furthermore, can we create multiple PF_RINGs to read packets from the same interface? Or does the one PF_RING take ownership of an interface while reading from it and none other application can use that interface?

This depends on the adapter. With Napatech you can create multiple streams (e.g. with load balancing) and attach with pf_ring as described in the user's guide.

> 3. If I have dozen of PF_RINGs that are reading packets from the same interface, would it cause a performance drop?

It depends, on the adapter, on the configuration (load balancing vs fan out), the number of CPU cores, cache and memory bandwidth, and other factors.

**Comment by m-peko** [comment]
Hey @cardigliano, thanks for the answers.

One thing I didn't get, can I have 2 or more PF_RINGs for the same physical interface (pcap, Intel or Napatech)?

**Comment by cardigliano** [comment]
PCAP: Yes
Intel with ZC: You can have one socket per interface or RSS queue
Napatech: You can have one socket per port, or you should use streams

**Comment by m-peko** [comment]
Thank you very much for your quick answers!
