### ISSUE TITLE
16 extra bytes in ZC-aware driver

### ISSUE THREAD

**Issue by Dvbcontrol-Daniel** [ntop/PF_RING#71]
Hi Alfredo,

Sorry to bother you again, but I have another problem. Now I'm using the ZC-aware drivers, and get the correct headers in my application. Thanks again for this. But now, when I get the packetData using "pfring_zc_pkt_buff_data", I get 16 extra leading bytes.

When I use the "old" drivers, I get the pointer to the data. With the ZC-aware drivers I have to shift the pointer 16 bytes, and have to shorten the caplen and len with 16. Something tells me my alterations cannot be the correct method to handle the data. What am I doing wrong? Is there a compiler-flag I oversee, when compiling the drivers?

Kind regards,
Daniël

**Comment by cardigliano** [comment]
Hi Daniel
could you provide more details about the 16-bytes offset? Are you getting 16 extra bytes before the ethernet header? Could you provide an example?

Alfredo

**Comment by Dvbcontrol-Daniel** [comment]
Hi Alfredo,

Thank you for helping. I do get 16 extra bytes before the 
ethernet-header. I suppose most helpful is attachment 
"networkCapture.pcap-received".

In my code, I have the following snippet, with which I produced the 
pcap-examples:

bool CNetworkManager::processCapturedPacket(pfring_zc_pkt_buff \* 
pkt_buffer, pfring_zc_queue *zqueue, int workerId)
{
         int offset = 0;
         struct pfring_pkthdr theader;

```
     theader.ts.tv_sec = pkt_buffer->ts.tv_sec;
     theader.ts.tv_usec = pkt_buffer->ts.tv_nsec/1000;
     theader.caplen = pkt_buffer->len - offset;
     theader.len = pkt_buffer->len - offset;

     pfring_pkthdr* header = &theader;

     const u_char* sourcePkt = (const 
```

u_char*)pfring_zc_pkt_buff_data(pkt_buffer, zqueue);

```
     return processPacketData( (const unsigned char*) sourcePkt + 
```

offset, header );
}

bool CNetworkManager::processPacketData( const u_char \* pkt_data, struct 
pfring_pkthdr \* header, int pWorkerId)
{
     if (!captureIsRunning())
     {
         winner.exchange(false);
         return;
     }

```
 while (winner.exchange(true) && captureIsRunning())
     usleep(1);    //Wacht tot de vorige thread de "winner" vrij geeft

 struct pcap_pkthdr_rob rec_hdr;
 rec_hdr.ts.tv_sec = header->ts.tv_sec;
 rec_hdr.ts.tv_usec = header->ts.tv_usec;
 rec_hdr.caplen = header->caplen;
 rec_hdr.len = header->len;

 fwrite(&rec_hdr, 1, sizeof (pcap_pkthdr_rob), m_FileStream);
 fwrite(pkt_data, 1, header->len, m_FileStream);
 fflush(m_FileStream);

 winner.exchange(false);        //Geef de "winner" vrij
```

}

In the default driver, the offset has to be 0 (as expected), in the 
zc-aware driver it has to be 16. I think "pfring_zc_pkt_buff_data" gives 
too much data...

In the attachments 2 wireshark-dumps. A networkCapture as expected (with 
the offset of 16) and a networkCapture with ZC-drivers and the offset 
set to 0 (networkCapture-received).

Do you need any additional information?

Kind regards,
Daniël

Op 01-Feb-16 om 18:59 schreef Alfredo Cardigliano:

> Hi Daniel
> could you provide more details about the 16-bytes offset? Are you 
> getting 16 extra bytes before the ethernet header? Could you provide 
> an example?
> 
> Alfredo
> 
> > On 01 Feb 2016, at 17:03, Dvbcontrol-Daniel

**Comment by Dvbcontrol-Daniel** [comment]
Hi Alfredo,

Possibly I have found something... When opening the device, I enabled 
PF_RING_ZC_DEVICE_HW_TIMESTAMP. But when I remove that from my code, the 
extra bytes are gone. Could this be the cause?

Is it true the flag "PF_RING_ZC_DEVICE_HW_TIMESTAMP" adds an additional 
16 bytes before the data?

Kind regards,
Daniël

Op 01-Feb-16 om 18:59 schreef Alfredo Cardigliano:

> Hi Daniel
> could you provide more details about the 16-bytes offset? Are you 
> getting 16 extra bytes before the ethernet header? Could you provide 
> an example?
> 
> Alfredo
> 
> > On 01 Feb 2016, at 17:03, Dvbcontrol-Daniel

**Comment by Dvbcontrol-Daniel** [comment]
A few examples from a recent printout, using the PF_RING_ZC_DEVICE_HW_TIMESTAMP:

00 00 00 00 00 00 00 00 88 1E 0D 15 41 00 00 00 01 00 5E 45 49 02 00 06 F4 61 D0 87 08 00 45 10 
00 00 00 00 00 00 00 00 70 91 0D 15 41 00 00 00 01 00 5E 0A 0A 01 00 13 B4 01 92 EA 08 00 45 00 
00 00 00 00 00 00 00 00 10 D3 0D 15 41 00 00 00 01 00 5E 45 48 08 00 06 F4 61 D0 89 08 00 45 00 
00 00 00 00 00 00 00 00 50 A3 0E 15 41 00 00 00 01 00 5E 45 48 01 00 06 F4 61 D0 89 08 00 45 00 
00 00 00 00 00 00 00 00 78 CE 0E 15 41 00 00 00 01 00 5E 45 46 09 00 06 F4 33 A8 02 08 00 45 08 

A few examples from a recent printout, using the PF_RING_ZC_DEVICE_SW_TIMESTAMP, and is the output I expected:
01 00 5E 45 49 02 00 06 F4 61 D0 87 08 00 45 10 05 40 BB DD 40 00 FF 11 AD 85 C0 A8 14 49 EF 45 
01 00 5E 45 48 08 00 06 F4 61 D0 89 08 00 45 00 05 40 E3 55 40 00 FF 11 87 18 C0 A8 14 48 EF 45 
01 00 5E 02 00 03 00 13 B4 00 64 9D 08 00 45 00 05 40 00 00 40 00 07 11 AA F5 C0 A8 14 0A EF 02 
01 00 5E 0A 0A 01 00 13 B4 01 92 EA 08 00 45 00 05 40 33 AB 40 00 07 11 6D 43 C0 A8 14 0B EF 0A
01 00 5E 02 00 04 00 13 B4 00 64 9D 08 00 45 00 05 40 00 01 40 00 07 11 AA F3 C0 A8 14 0A EF 02

Kind regards,
Daniël

**Comment by cardigliano** [comment]
Hi Daniël
what is the adapter model you are using?

**Comment by Dvbcontrol-Daniel** [comment]
Hi,
We use a SuperMicro motherboard with integrated Intel® i350-AM2 Dual port GbE LAN.
Regards,
Daniël

**Comment by cardigliano** [comment]
Well, the additional bytes you see is the hw timestamp which is (not yet) handled by ZC on that card model, we will add support for it, in the meanwhile please remove the PF_RING_ZC_DEVICE_HW_TIMESTAMP flag.

**Comment by Dvbcontrol-Daniel** [comment]
Ok, thank you for your reply! Hope the HW Timestamp will be supported soon. Keep up the good work! Thank you so far!
Regards,
Daniël

**Comment by cardigliano** [comment]
hw timestamp is now handled and removed from packet header

**Comment by Dvbcontrol-Daniel** [comment]
Excellent! Thanks!

Op 16-Feb-16 om 17:32 schreef Alfredo Cardigliano:
