### ISSUE TITLE
flag PF_RING_ZC_DEVICE_HW_TIMESTAMP is already available？

### ISSUE THREAD

**Issue by liuchuang** [ntop/PF_RING#712]
Env：`ixgbe/82599/x520/pf_ring7.4 release`

pfring_zc_open_device with the `PF_RING_ZC_DEVICE_HW_TIMESTAMP` flag
Test case:
(1)`./zfifo -i zc:eth4,zc:eth5 -c 10 -r 1 -g 2`
(2)`./zfifo -i eth4,eth5 -c 10 -r 1 -g 2`

test in examples_zc/zfifo,when case 1 use zc mode,the pfring_zc_pkt_buff->ts.tv_sec is 0
but case 2 use no zc mode,the pfring_zc_pkt_buff->ts.tv_sec is not 0.
any suggestions use HW timestamp in zc mode?
Thanks.

**Comment by cardigliano** [comment]
@liuchuang ixgbe adapters do not support hw timestamps, please check https://www.ntop.org/guides/pf_ring/modules/index.html
What you see in non-zc mode is the timestamp from the kernel (software)
