### ISSUE TITLE
Hardware recomendation to push 100Gbps traffic using disk2n

### ISSUE THREAD

**Issue by jatin152** [ntop/PF_RING#718]
We have 1.6 TB of pcaps and want to use disk2n to replay it using Napatech card at 100Gbps.

What is the recommened server configuration do you suggest for sending 100Gbps traffic using disk2n, considering average packet size of 400 bytes.

Eg.
How many SSD(Raid 0)? What IOPS?
How much RAM?

Thanks

**Comment by cardigliano** [comment]
@jatin152 said that I do not have numbers about the expected replay speed at 100Gb with disk2n, please note that:
1. the controller itself can have performance limitations regardless of the number of disks (in my experience the max *write* throughput on many controllers is ~40-45 Gbps for instance)
2. it is likely you need to use multiple "streams" using multiple disks (raid volumesor NVMes)
