### ISSUE TITLE
AF_XDP multi-process support

### ISSUE THREAD

**Issue by moshegbl** [ntop/PF_RING#719]
Would like to be able to run multiple process concurrently on top of AF_XDP multiple queues.

For example:
“sudo nprobe -i xdp:eth1@0” and “sudo nprobe -i xdp:eth1@1” simultaneously.

At the moment, when running pfcount on xdp:eth1@0 and xdp:eth1@1 simultaneously, the first pfcount drops to 0 bps.

**Comment by cardigliano** [comment]
@moshegbl the AF_XDP support has been improved and this seems to be working now, please check it and reopen this issue in case you experience the same issue

**Comment by moshegbl** [comment]
Update: now can successfully run pfcount on multiple xdp queues.
Still can **not** run **nProbe** on xdp:eth1@0.
nProbe says: "device not found"
