### ISSUE TITLE
Does pfring-ZC support cards HPE-655639-B21 and  655639-B21 

### ISSUE THREAD

**Issue by jatin152** [ntop/PF_RING#720]
Hi Team, 

Can you please confirm whether Pfring ZC is supported for the below cards? 
If yes, Which driver we will need to install For same?

The following 560FLB and 560M are based on Intel 82599 Ethernet Controller  

HPE Ethernet 10Gb 2-port 560M 
Adapter                              665246-B21

HPE Ethernet 10Gb 2-port 560FLB 
Adapter                          655639-B21

**Comment by cardigliano** [comment]
Yes, it seems they are both based on Intel 82599 (ixgbe)
