### ISSUE TITLE
disk2n utility exiting with error code

### ISSUE THREAD

**Issue by jatin152** [ntop/PF_RING#721]
Hi,

I am using disk2n to play some pcap file on a napatech FPGA card. However the utility exits with below error.
Please advise how to resolve this. 
As far as I remember disk2n works without configuring hugepages.

[root@loadtestsrv2 ~]# /usr/local/bin/disk2n -m /tmp/filelist.txt -i nt:0 -I 550 -C 1024 -b 20480 -U -c 15 -w 16 -S 17 -O -v
24/May/2021 11:22:32 [disk2n.c:2353] /data_r10/singtel-pcaps/snoop_eth7-2014-12-19--12-37-08.pcap addded to list
24/May/2021 11:22:32 [disk2n.c:2597] Welcome to disk2n v.3.4.200220 (r5185) [CPU 406F]
24/May/2021 11:22:32 [disk2n.c:2623] Reading data in 1024 KB chunks
24/May/2021 11:22:32 [disk2n.c:2624] Allocating 20480 MB buffer memory...
 *** error retrieving hugepages info ***
24/May/2021 11:22:32 [disk2n.c:2646] ERROR: Hugepages not available, did you configure them? Using standard allocation..
24/May/2021 11:22:32 [disk2n.c:2662] ERROR: Unable to allocate requested memory [pagesize: 4096][buffer_len: 1048576]
24/May/2021 11:22:32 [disk2n.c:353] Waiting thread termination...

[root@loadtestsrv2 tmp]# cat /proc/net/pf_ring/info
PF_RING Version          : 7.5.0 (unknown)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 409600
Slot version             : 17
Capture TX               : No [RX only]
IP Defragment            : No
Socket Mode              : Standard

**Comment by cardigliano** [comment]
It seems you need to reserve hugepages, please read https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html (or for more info also read https://www.ntop.org/guides/pf_ring/hugepages.html)
or just remove -U which is not mandatory
