### ISSUE TITLE
zc driver compile error

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#723]
OS:
Linux x86 

#uname -r 
3.10.62-ltsi-NGTOSv2.1.0

#cd pf_ring/driver/intel
#make

cc1: some warnings being treated as errors
make[4]: *** [/home/ngos/new-pfring/PF_RING-dev/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.o] Error 1
make[3]: *** [_module_/home/ngos/new-pfring/PF_RING-dev/drivers/intel/e1000e/e1000e-3.8.7-zc/src] Error 2
make[3]: Leaving directory `/usr/src/linux-3.10.62'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/home/ngos/new-pfring/PF_RING-dev/drivers/intel/e1000e/e1000e-3.8.7-zc/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/ngos/new-pfring/PF_RING-dev/drivers/intel/e1000e/e1000e-3.8.7-zc'
make: *** [all] Error 2
root@TopSecSystem:~/new-pfring/PF_RING-dev/drivers/intel\>

**Comment by cardigliano** [comment]
@MaoPann what OS distribution and version are you running exactly? This does not look like a supported kernel..

**Comment by MaoPann** [comment]
#uname -a
Linux TopSecSystem 3.10.62-ltsi-NGTOSv2.1.0 #1 SMP PREEMPT Fri Oct 26 14:53:50 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

yes it's a company's private operating system

**Comment by MaoPann** [comment]
@cardiglianoHi， Can pfring ZC be used in this environment?

**Comment by cardigliano** [comment]
It can be used but there is some compilation error that should be fixed. Please note we officially support Ubuntu LTS/Debian/CentOS, if you are interested in supporting other kernels please contact us by mail and we will estimate the effort.
