### ISSUE TITLE
Generate packet and send by pfring_zc_send_pkt

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#725]
Hello!
I want to generate a new packet and send it with pfring_zc_send_pkt
How to do it?

I can get the actual packet data (pfring_zc_pkt_buff_data) from buffer received from pfring_zc_recv_pkt and then modify it and send.

But how fill pfring_zc_pkt_buff received from cluster (pfring_zc_get_packet_handle) with my generated data? Where copy data? How set length?
Do I need to fill fields (pfring_zc_pkt_buff):
u_int16_t flags
u_int32_t hash
pfring_zc_timespec ts
so I can send it?

**Comment by cardigliano** [comment]
You can use pfring_zc_get_packet_handle() or pfring_zc_get_packet_handle_from_pool() to get a fresh buffer that can be used to forge packets and send them. Please check PF_RING/userland/examples_zc for sample code using those functions. You need to fill the buffer data (pfring_zc_pkt_buff_data) and length (buffer->len).

**Comment by andyarus** [comment]
```
u_char* pfring_zc_pkt_buff_data	(
    pfring_zc_pkt_buff *pkt_handle,
    pfring_zc_queue    *queue 
)		
Returns the pointer to the actual packet data.

Parameters
pkt_handle	The buffer handle.
queue	The queue from which the packet is arrived or destined.
```

Which queue to use for fresh buffer from pfring_zc_get_packet_handle() or pfring_zc_get_packet_handle_from_pool()?

**Comment by cardigliano** [comment]
You can provide any queue/pool in the cluster, it's just used to get a reference to the correct cluster (and memory)

**Comment by andyarus** [comment]
Thank you very much for your help!
