### ISSUE TITLE
pfcount -v 1 -L Does not list expiration time on Silicom FPGA

### ISSUE THREAD

**Issue by srfn8kd** [ntop/PF_RING#726]
Hello!

I am using the latest versions of pf_ring and it turns out pfcount -v 1 -L indicates validity and does not return the expiration date for the license; it also shows the status as down although the card is up and everything is working properly

FPGA Version: FPGA type: 4e, model: 17, version: 2.10.65.0

pfcount -v 1 -L
fbcard:0:a00    unknown fiberblaze      FB2CG@KU15P-2.0043      0000:00:02.0    0       Down    Valid   0
fbcard:0:a01    unknown fiberblaze      FB2CG@KU15P-2.0043      0000:00:02.0    0       Down    Valid   0

This is the same across 3 servers, one running CentOS 8 - the other two running RHEL 7.9

I want to make sure that the licenses are actually valid before I update the packages as I got caught before with an expired license and there is no method to downgrade once upgraded.

Thanks!

**Comment by cardigliano** [comment]
@srfn8kd could you provide the content of your /etc/pf_ring in a direct email to cardigliano at ntop.org? Thank you.

**Comment by cardigliano** [comment]
This was due to a mistake in the license files.
