### ISSUE TITLE
Illegal instruction in pfring_open ( 7.8.0-stable )

### ISSUE THREAD

**Issue by teoring** [ntop/PF_RING#728]
Hello,

I have compiled PFRING from sources ( 7.8.0-stable branch ) on the following environment:

Architecture:  x64_86
OS               :  Ubuntu 20.04.2 LTS
Core:           :  5.8.0-53-generic
CPU            :

> Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       4
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Stepping:                        0
CPU MHz:                         2095.078
BogoMIPS:                        4190.15
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        4 MiB
L3 cache:                        110 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 
                                 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear flush_l1d arch_capabilities

I also generated debian packages using sources in the repository. 
Everything was working just fine on my environment but when I have installed software on a new environment I have faced an "Illegal instruction" error.

Architecture, OS, kernel version is the same on a new environment, CPU is different:
![image](https://user-images.githubusercontent.com/12891023/122952151-1fee8f00-d37e-11eb-96ff-3cef2445a1c0.png)

This is a stack and last instruction:
![image](https://user-images.githubusercontent.com/12891023/122952330-43b1d500-d37e-11eb-9771-c199f09c4fad.png)

Is it possible that this issue is caused by missing  --disable-archopt flag for configure?

**Comment by cardigliano** [comment]
This happens when compiling the library on a CPU with a different instruction set, it is likely --disable-archopt would fix this.

**Comment by teoring** [comment]
I will verify this today and close the ticket afterwards.

**Comment by teoring** [comment]
This indeed the result of missing --disable-archopt ( native march ). Its very strange you are enabling this by default.
