### ISSUE TITLE
zbalance_DC_ipc stopped with Seg-fault when pass the packet

### ISSUE THREAD

**Issue by byungyong-hwang** [ntop/PF_RING#729]
Hi, 

I want to make customized packet filter.
zbalance_DC_ipc is looks good , but problem happen.
if I change filtering_func return 1; for pass all packets, segment-fault happen.
My modificatoin is here.

https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance_DC_ipc.c#L288
int64_t filtering_func(pf~~~~~~~~~~~~~~~~~~~~~~~~~~~) {
  return 1;  /* for pass all packets! */
}

**Comment by byungyong-hwang** [comment]
test pcap is from https://wiki.wireshark.org/SampleCaptures 

RTP_L16_monaural_sample.pcapng  file

**Comment by cardigliano** [comment]
@byungyong-hwang please note filtering_func should return the queue id. If you have only 1 queue it should always return 0 to pass all packets. Can I see your command line?

**Comment by byungyong-hwang** [comment]
Thank you for your fast answer.

I found filter_func same with distibution function in zbalance_ipc.c . 
This is my mistakes.
