### ISSUE TITLE
Need Help/Clarification on built-in IP-based Hash function

### ISSUE THREAD

**Issue by diwenx** [ntop/PF_RING#730]
From the [documentation](https://www.ntop.org/guides/pf_ring/api/pfring_zc.html#_CPPv425pfring_zc_builtin_ip_hashP18pfring_zc_pkt_buffP15pfring_zc_queue) it says 

> Computes an IP-based packet hash. Hash input: <src ip, dst ip>

Does this mean that any packets with the same two tuple (two ips) in whatever order will be hashed into the same group? Or does it mean that packet<src=a, dst=b> and packet<src=b, dst=a> can be mapped to different groups?
If it is the latter, is there any built-in hash function that maps both directions of a given flow to the same group? 

Thank you!

**Comment by cardigliano** [comment]
> Does this mean that any packets with the same two tuple (two ips) in whatever order will be hashed into the same group? 

Correct
