### ISSUE TITLE
ZC Drivers fail to Compile on RHEL 8.4

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#732]
/etc/redhat-release:

Red Hat Enterprise Linux release 8.4 (Ootpa)

Kernel Version:

 4.18.0-305.7.1.el8_4.x86_64 #1 SMP Mon Jun 14 17:25:42 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

All Drivers Failed to Compile.

Attached:

[dnf-command.log](https://github.com/ntop/PF_RING/files/6742858/dnf-command.log)
[e1000e-zc.log](https://github.com/ntop/PF_RING/files/6742860/e1000e-zc.log)
[i40e-zc.log](https://github.com/ntop/PF_RING/files/6742862/i40e-zc.log)
[igb-zc.log](https://github.com/ntop/PF_RING/files/6742863/igb-zc.log)
[ixgbe-zc.log](https://github.com/ntop/PF_RING/files/6742867/ixgbe-zc.log)
[ixgbevf-zc.log](https://github.com/ntop/PF_RING/files/6742869/ixgbevf-zc.log)

NTOP Versions installed: (from nightly):

pfring-7.9.0-6685.x86_64
pfring-drivers-zc-dkms-7.9.0-6685.noarch
pfring-dkms-7.9.0.6685-6685.noarch
n2disk-3.7.210630-5318.x86_64

**Comment by cardigliano** [comment]
I confirm a patch is required in order to compile on latest centos 8 kernel. I will work on this asap.

**Comment by cardigliano** [comment]
@Arislen the drivers should now compile on latest 8.4 kernel, please check it and let me know. Edit: please wait the next software update from nightly builds.

**Comment by Arislen** [comment]
Back from the US Holiday weekend. Will test the drivers tomorrow..

**Comment by Arislen** [comment]
Drivers now compile on RHEL 8.4. Thanks for your help.

**Comment by cardigliano** [comment]
Thank you
