### ISSUE TITLE
Bad return status for module build on kernel: 3.10.0-957.el7.x86_64(x86_64)

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#733]
when I use pfring zc on centos 7.9, compile error,
![image](https://user-images.githubusercontent.com/44804599/124557035-9bb30600-de6b-11eb-9e7b-cc3ba93d09bf.png)

![image](https://user-images.githubusercontent.com/44804599/124556748-3ced8c80-de6b-11eb-9bd2-13120bc3450b.png)

**Comment by cardigliano** [comment]
@MaoPann please provide the generated log file as reported in the warning (make.log)

**Comment by MaoPann** [comment]
how to get the make.log

**Comment by MaoPann** [comment]
we use pf_ringcfg to compile

**Comment by MaoPann** [comment]
The problem was solved after the software was updated
