### ISSUE TITLE
nProbe and AF_XDP

### ISSUE THREAD

**Issue by moshegbl** [ntop/PF_RING#734]
When trying to run nProbe on XDP interface queue, nprobe does not recognize the network device.

Steps to reproduce:
When running "nprobe -i xdp:ens1f0@0", getting "No such device exists".

**Comment by cardigliano** [comment]
@moshegbl what OS are you running here?

**Comment by cardigliano** [comment]
@moshegbl this is working for me on Ubuntu 20 (kernel 5.8.0) using latest nProbe dev (tested with 9.5.210709). Please make sure you are running latest version, which is compiled with XDP support.
