### ISSUE TITLE
high load average

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#735]
Memory: 16G 
Number of threads: 4
Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz ：1

pfring: 7.8
Our traffic is about 200Mbps

When I run our application with pfring zc, there is a High load average.The system is very slow to respond, for example, if I run an ls command, it takes a long time to respond.
If zc: is not added, the load is still close to 3, but the fluency of the system is improved, and the echo speed of command execution is improved.

![image](https://user-images.githubusercontent.com/44804599/125401233-7aab6180-e3e5-11eb-82e4-eb139b673aff.png)

**Comment by MaoPann** [comment]
If zc: is not added, the load is still close to 3, but the fluency of the system is improved, and the echo speed of command execution is improved.

**Comment by MaoPann** [comment]
@cardigliano

**Comment by cardigliano** [comment]
@MaoPann do you see the same load running pfcount -i zc:<interface> ?
Please provide cat /proc/net/pf_ring/dev/<interface>/info

**Comment by MaoPann** [comment]
![image](https://user-images.githubusercontent.com/44804599/125413981-085324d1-7ed5-4246-8d66-7ffda18049e4.png)

**Comment by MaoPann** [comment]
Here are the results of running zcount only.

![image](https://user-images.githubusercontent.com/44804599/125594173-67755db7-e9f7-486c-ad18-911f5bc96564.png)

**Comment by MaoPann** [comment]
@cardigliano

**Comment by cardigliano** [comment]
@MaoPann it seems the load with zcount is quite low (6% of a core), please investigate on what is causing that load in your application
