### ISSUE TITLE
ZC batch sending function. 

### ISSUE THREAD

**Issue by fattaholmanan** [ntop/PF_RING#736]
Hi, 
I was being confused regarding the sending burst API in the zc mode. In particular regarding the return value for `pfring_zc_send_pkt_burst`, it's mentioned that this function returns:

> The number of packets successfully sent, a negative value in case of error. Note: packets sent can be less than num_packets in case there is not enough room in the TX queue or in case of BPF filters.

Considering a scenario in which I try to send 12 packets, but the function returns 8; how would it be possible to find out which packets have been sent and which haven't? Is it like the first 8 packets? Is it random? 

I tried to see the example `zsend`, but over there also this issue is left for future.

Tnx,

**Comment by cardigliano** [comment]
The first 8 packets are sent in that case.
