### ISSUE TITLE
Regarding how Pf_ring works with dpdk

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/PF_RING#738]
I want to develop an environment of nDPI+DPDK. I am using two NICs XL710 and trying to achieve receiving throughput of 40gbps.
I have tried only nDPI with DPDK but it seems will not work because as per my understanding if I try to run the ./ndpiReader.dpdk command to read the packets on an interface it only achieves 5Gbps as that interface is no more in Kernel and bounded with igb_uio driver. It also shows a message that it can't find the device. Please tell me if I am doing something wrong here.
So I turn to pf_ring ft and I want to know will ftflow_dpdk will do in reference to dpdk. Please help or give some suggestions.
I also tried to transmit the packages from one CPU with XL710 NIC using pfsend and try to capture on another CPU with NIC XL710 using ./ndpiReader but the throughput was only 25Gbps. How can I make it achievable to the maximum of 40Gbps?
I am working on Ubuntu 20.04.2

**Comment by cardigliano** [comment]
I suggest to use ftflow_dpdk from https://github.com/ntop/PF_RING/tree/dev/userland/examples_ft 
There is a README.dpdk in the same folder for configuring the environment.
You can also scale with the performance running RSS in case one core is not enough.

**Comment by utkarsh0902311047** [comment]
How to run RSS ? I tried looking on internet but couldn't find the steps.
Please share the steps.

**Comment by utkarsh0902311047** [comment]
> I suggest to use ftflow_dpdk from https://github.com/ntop/PF_RING/tree/dev/userland/examples_ft
> There is a README.dpdk in the same folder for configuring the environment.
> You can also scale with the performance running RSS in case one core is not enough.

I tried the command : ./ftflow_dpdk -l 1-8 -n 16 --vdev=net_pcap0,iface=ens9f0
I have changed my NIC to 100Gbps on both the systems. I am succesfully able to generate 100gbps of traffic and when I run the above command I could only see the throughput of 7gbps. What should I do? Please help
![Screenshot from 2021-07-23 23-31-41](https://user-images.githubusercontent.com/78134056/126805633-54bb2f6b-4e2b-487f-80b3-b7579292a080.png)
![Screenshot from 2021-07-23 23-31-47](https://user-images.githubusercontent.com/78134056/126805652-80417681-2180-48fc-bdc5-0edb609c9e1a.png)

**Comment by cardigliano** [comment]
@utkarsh0902311047 please note you are using pcap capture, please follow the dpdk documentation to use native acceleration based on your adapter model
