### ISSUE TITLE
PF_RING version mismatch (expected v.7.8.0 found v.7.9.0)

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#739]
hello ，
Before I installed pfring 7.9 to run our own application, now I want to change to version 7.8. However, I encountered the following problems. I have used Yum to uninstall pfring 7.9 and install version 7.8. But my application still prompts to use version 7.9, the program does not report an error, but it will automatically exit after a period of time.
![image](https://user-images.githubusercontent.com/44804599/126471574-2095bddf-c4cc-4910-b277-27f2dcc94a1d.png)

**Comment by cardigliano** [comment]
You still have the 7.9 kernek module loaded, please try with a systemctl restart pf_ring, or a system reboot
