### ISSUE TITLE
Error While loading the ice driver

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/PF_RING#740]
root@aewin:~/PF_RING/drivers/intel/ice/ice-1.3.2-zc/src# ./load_driver.sh 
Configuring enx7635bdf085bf
Cannot change rx-vlan-offload
Cannot get device pause settings: Operation not supported
Cannot get device pause settings: Operation not supported
ls: cannot access '/sys/class/net/enx7635bdf085bf/device/msi_irqs': No such file or directory
Error: Could not find interrupts for enx7635bdf085bf
IFACE CORE MASK -> FILE
=======================
Configuring ens9f0
rx unmodified, ignoring
no pause parameters changed, aborting
tx unmodified, ignoring
no pause parameters changed, aborting
IFACE CORE MASK -> FILE
=======================
ens9f0 0 1 -> /proc/irq/31/smp_affinity
Configuring ens9f1
rx unmodified, ignoring
no pause parameters changed, aborting
tx unmodified, ignoring
no pause parameters changed, aborting
IFACE CORE MASK -> FILE
=======================
ens9f1 0 1 -> /proc/irq/101/smp_affinity
Warning: 120 hugepages available, 1024 requested

How to solve it
Please help.

**Comment by cardigliano** [comment]
Please provide cat /proc/meminfo

**Comment by utkarsh0902311047** [comment]
MemTotal:       263778656 kB
MemFree:        126331512 kB
MemAvailable:   125748196 kB
Buffers:           16704 kB
Cached:           823844 kB
SwapCached:            0 kB
Active:          1446332 kB
Inactive:         496028 kB
Active(anon):    1102204 kB
Inactive(anon):    38804 kB
Active(file):     344128 kB
Inactive(file):   457224 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2097148 kB
SwapFree:        2097148 kB
Dirty:              1880 kB
Writeback:             0 kB
AnonPages:       1102532 kB
Mapped:           402560 kB
Shmem:             39140 kB
KReclaimable:     187788 kB
Slab:             580656 kB
SReclaimable:     187788 kB
SUnreclaim:       392868 kB
KernelStack:       25552 kB
PageTables:        16928 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    66877612 kB
Committed_AS:    5282248 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      273236 kB
VmallocChunk:          0 kB
Percpu:            64000 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:     124
HugePages_Free:      123
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB
Hugetlb:        134217728 kB
DirectMap4k:      652292 kB
DirectMap2M:     8429568 kB
DirectMap1G:    261095424 kB

**Comment by cardigliano** [comment]
The system actually has plenty of memory available, not sure why the hugepages allocation is not able to allocate all the requested pages. Please read https://www.ntop.org/guides/pf_ring/hugepages.html and try reserving pages manually following the guide.

**Comment by utkarsh0902311047** [comment]
But is this the problem of hugepages? 
How about the other messages appearing like Cannot get device pause settings or cannot access '/sys/class/net/enx7635bdf085bf/device/msi_irqs': No such file or directory or while configuring the ports it says ignoring aborting.

**Comment by cardigliano** [comment]
I guess you can ignore those errors. I will take a look anyway.

**Comment by utkarsh0902311047** [comment]
ok thank you so much. 
Please do you have some suggestions for me for my case #738 or can I mail you or something ?

**Comment by utkarsh0902311047** [comment]
> I guess you can ignore those errors. I will take a look anyway.

root@aewin:~/PF_RING/drivers/intel/ice/ice-1.3.2-zc/src# ./load_driver.sh 
Configuring enx029cf3a0cfa3
Cannot change rx-vlan-offload
Cannot get device pause settings: Operation not supported
Cannot get device pause settings: Operation not supported
ls: cannot access '/sys/class/net/enx029cf3a0cfa3/device/msi_irqs': No such file or directory
Error: Could not find interrupts for enx029cf3a0cfa3
IFACE CORE MASK -> FILE
=======================
Configuring ens5f0
rx unmodified, ignoring
no pause parameters changed, aborting
tx unmodified, ignoring
no pause parameters changed, aborting
IFACE CORE MASK -> FILE
=======================
ens5f0 0 1 -> /proc/irq/44/smp_affinity
Configuring ens5f1
rx unmodified, ignoring
no pause parameters changed, aborting
tx unmodified, ignoring
no pause parameters changed, aborting
IFACE CORE MASK -> FILE
=======================
ens5f1 0 1 -> /proc/irq/114/smp_affinity
Warning: 121 hugepages available, 1024 requested


root@aewin:~/PF_RING/userland/examples# ./pfcount -i zc:ens5f0
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.9.0.210714
# license for ens5f0 (MAC 00:0D:48:56:07:A8) [Intel 100 Gbit ice family]
# ERROR: Missing license file
# ERROR: Please get one at http://shop.ntop.org/
#########################################################################
# PF_RING ZC running in demo mode (packet capture and transmission
# limited to 5 minutes)
#########################################################################
Using PF_RING v.7.9.0
Capturing from zc:ens5f0 [mac: 00:0D:48:56:07:A8][if_index: 9][speed: 10000Mb/s]
# Device RX channels: 1
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/12861-ens5f0.2
=========================
Absolute Stats: [8'950'547 pkts total][8'950'547 pkts dropped][100.0% dropped]
[0 pkts rcvd][0 bytes rcvd]
=========================

=========================
Absolute Stats: [20'922'933 pkts total][20'922'933 pkts dropped][100.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.06 ms][0.00 pps][0.00 Gbps]
=========================

On trying the ./pfcount -i zc:ens5f0, I get 100% packets dropped. Why? Is it because of some driver issue?

**Comment by utkarsh0902311047** [comment]
root@aewin:~/PF_RING# echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages 
root@aewin:~/PF_RING# echo 1024 > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages 
root@aewin:~/PF_RING# cd drivers/intel/ice/ice-1.3.2-zc/src/
root@aewin:~/PF_RING/drivers/intel/ice/ice-1.3.2-zc/src# ./load_driver.sh 
Configuring enx029cf3a0cfa3
Cannot change rx-vlan-offload
Cannot get device pause settings: Operation not supported
Cannot get device pause settings: Operation not supported
ls: cannot access '/sys/class/net/enx029cf3a0cfa3/device/msi_irqs': No such file or directory
Error: Could not find interrupts for enx029cf3a0cfa3
IFACE CORE MASK -> FILE
=======================
Configuring ens5f0
rx unmodified, ignoring
no pause parameters changed, aborting
tx unmodified, ignoring
no pause parameters changed, aborting
IFACE CORE MASK -> FILE
=======================
ens5f0 0 1 -> /proc/irq/44/smp_affinity
Configuring ens5f1
rx unmodified, ignoring
no pause parameters changed, aborting
tx unmodified, ignoring
no pause parameters changed, aborting
IFACE CORE MASK -> FILE
=======================
ens5f1 0 1 -> /proc/irq/114/smp_affinity
Warning: 121 hugepages available, 1024 requested

I run the above commands for assigning hugepages but why it still says only 121 hugepages available?

**Comment by cardigliano** [comment]
Please try with this:

- reboot the system
- issue the below commands:
echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
mount -t hugetlbfs nodev /dev/hugepages
- provide cat /proc/meminfo

**Comment by utkarsh0902311047** [comment]
![Screenshot from 2021-07-27 13-45-48](https://user-images.githubusercontent.com/78134056/127102043-35de22e8-8aa7-4416-8b2f-0433b31881a4.png)
 
Also in case #738 you mentioned "please note you are using pcap capture, please follow the dpdk documentation to use native acceleration based on your adapter model". What do you mean by this statement I didn't get? I am using 100G NIC by Intel E810. Please also tell me how to enable RSS?

Thank you

**Comment by cardigliano** [comment]
If you are using pf_ring drivers, please read https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html for instructions to configure RSS. If you are using DPDK, please check the official dpdk documentation.

**Comment by cardigliano** [comment]
As of the issue reserving hugepages, what you are experiencing looks weird, any chance I can ssh and take a look?

**Comment by utkarsh0902311047** [comment]
> As of the issue reserving hugepages, what you are experiencing looks weird, any chance I can ssh and take a look?

Sure, what should I provide you?

**Comment by utkarsh0902311047** [comment]
> If you are using pf_ring drivers, please read https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html for instructions to configure RSS. If you are using DPDK, please check the official dpdk documentation.

I was following PF_RING install guide through git.

But is there something wrong with this command I am running "./ftflow_dpdk -l 1-8 -n 16 --vdev=net_pcap0,iface=ens9f0".
Why the throughput is only 7Gbps?

**Comment by cardigliano** [comment]
> > As of the issue reserving hugepages, what you are experiencing looks weird, any chance I can ssh and take a look?
> 
> Sure, what should I provide you?

Please send a direct email to cardigliano at ntop.org to provide ssh credentials

**Comment by cardigliano** [comment]
The hugepages issue here was due to the hugepage size configuration in grub: 1G hugepages are enabled, but ZC requires 2MB hugepages, thus the script was trying to allocate 1024, getting just 125 (which is the RAM size)
