### ISSUE TITLE
Checking variable twice in same line

### ISSUE THREAD

**Issue by cvonhamm** [ntop/PF_RING#741]
https://github.com/ntop/PF_RING/blob/ea15e45d9dd51ebf237c3b6133080fb370fba33b/userland/examples_zc/zbalance_ipc.c#L1351
No purpose to check (ext_q == NULL) twice in same line. Believe the second check should be checking if pool is NULL.

**Comment by cardigliano** [comment]
Fixed in b9e78ece875ea34677b00999a052d22ae05727d4. Thank you.
