### ISSUE TITLE
ZeroCopy License Not Valid

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#742]
Summary: 

Upgrading the version of PF_RING to the latest results in a Zero Copy license error.

Repository: https://packages.ntop.org/centos/

OS: Red Hat Enterprise Linux release 8.2 (Ootpa)
Kernel: 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Fri Oct 16 13:38:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

NTOP Versions:

pfring-7.9.0-6760.x86_64
pfring-dkms-7.9.0.6760-6760.noarch
n2disk-3.7.210727-5320.x86_64
ixgbe-zc-5.5.3.6760-dkms.noarch

Error Messages:

count -i zc:ens1f0 -M
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.9.0.210723
# license for ens1f0 (MAC 90:E2:BA:E7:DD:10) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: License mismatch error
# ERROR: Please get one at http://shop.ntop.org/
#########################################################################
# PF_RING ZC running in demo mode (packet capture and transmission
# limited to 5 minutes)
#########################################################################
Invalid license

zcount -i zc:ens1f0 -C
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.9.0.210723
# license for ens1f0 (MAC 90:E2:BA:E7:DD:10) [Intel 10 Gbit ixgbe 82599-based]
# ERROR: License mismatch error
# ERROR: Please get one at http://shop.ntop.org/
#########################################################################
# PF_RING ZC running in demo mode (packet capture and transmission
# limited to 5 minutes)
#########################################################################
Invalid license

The same license worked on a previous version of PF_RING. I installed these versions to check after experiencing the error:

NTOP Versions:

pfring-dkms-7.9.0.6708-6708.noarch
pfring-7.9.0-6708.x86_64
n2disk-3.7.210707-5318.x86_64
ixgbe-zc-5.5.3.6708-dkms.noarch

License Output:

zcount -i zc:ens1f0 -M
1631714039 Wed Sep 15 09:53:59 2021
zcount -i zc:ens1f0 -C
License Ok

Our N2DISK license bought at the same time was not affected:

n2disk --check-license
License Ok
n2disk --check-maintenance
1631714008 Wed Sep 15 09:53:28 2021

**Comment by cardigliano** [comment]
@Arislen could you update to the latest (today's) version?

**Comment by Arislen** [comment]
Looks like the latest fixed it:

Versions:
pfring-7.9.0-6766.x86_64
pfring-dkms-7.9.0.6766-6766.noarch
ixgbe-zc-5.5.3.6766-dkms.noarch
n2disk-3.7.210728-5320.x86_64

License Check:
zcount -i zc:ens1f0 -M
1631714039 Wed Sep 15 09:53:59 2021
 zcount -i zc:ens1f0 -C
License Ok

Thanks for your help.

**Comment by cardigliano** [comment]
Thank you
