### ISSUE TITLE
Unable to achieve 100Gbps TX throughput by PF_RING

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/PF_RING#743]
I am using INTEL E810 NIC of 100G for generating the data at 100gbps throughput using PF_RING.
This is the command I am writing : ./pfsend -f /home/aewin/trex_2.9/trex-core-master/scripts/avl/packet_capture1.pcap -n 0 -i zc:ens5f0 -l 1500
admin:///root/packet_capture1.zip
I have attached the pcap file I am using and the maximum throughput I can achieve is 38Gbps. 
Please help

**Comment by cardigliano** [comment]
@utkarsh0902311047 I suggest to use multiple RSS queues as it is unlikely a single thread/core would be able to generate full 100Gbps. Please also check "dmesg | grep pcie" or similar to check if you are using all the PCIe lanes supported by the adapter.

**Comment by utkarsh0902311047** [comment]
Does this mean running all the following commands and then go to PF_RING/userland/examples and then run the ./pfsend command?? 
apt-get install pfring-dkms pfring-drivers-zc-dkms
sudo touch /etc/pf_ring/pf_ring.conf
echo "node=0 hugepagenumber=1024" | sudo tee /etc/pf_ring/hugepages.conf
sudo mkdir -p /etc/pf_ring/zc/ice
echo "RSS=1,1" | sudo tee /etc/pf_ring/zc/icee/ice.conf
sudo touch /etc/pf_ring/zc/ice/ice.start
sudo systemctl restart pf_ring

Following is the output of the command dmesg | grep pcie
Can you tell me what should I check on this?
![Screenshot from 2021-08-02 15-11-13](https://user-images.githubusercontent.com/78134056/127819025-19950359-8441-42f5-986c-001650249618.png)

**Comment by cardigliano** [comment]
dmesg | grep -i pcie

**Comment by cardigliano** [comment]
1. Replace RSS=1,1 with RSS=4,4
2. sudo systemctl restart pf_ring
3. Run one pfsend instance per queue:
pfsend ... -i zc:ens5f0@0
pfsend ... -i zc:ens5f0@1
pfsend ... -i zc:ens5f0@2
pfsend ... -i zc:ens5f0@3

**Comment by utkarsh0902311047** [comment]
![Screenshot from 2021-08-02 15-27-10](https://user-images.githubusercontent.com/78134056/127820962-5a6ed878-b968-43a4-89a7-92713a831c8c.png)

**Comment by utkarsh0902311047** [comment]
2058  touch /etc/pf_ring/pf_ring.conf
 2059  echo "node=1 hugepagenumber=1024" | tee /etc/pf_ring/hugepages.conf
 2060  mkdir -p /etc/pf_ring/zc/ice
 2061  echo "RSS=4,4" | tee /etc/pf_ring/zc/ice/ice.conf
 2062  touch /etc/pf_ring/zc/ice/ice.start
 2063  systemctl restart pf_ring
 2064  cd PF_RING/userland/examples
 2065  ./pfsend -f try1.pcap -n 0 -i zc:ens5f0@0 -l 1500

I run the above commands and still getting only 35Gbps TX throughput
![Screenshot from 2021-08-02 16-10-44](https://user-images.githubusercontent.com/78134056/127827120-f5aa7f54-0921-405a-a5dd-c6db5c732c46.png)

Also, I tried for queue 1, how to resolve this error?
./pfsend -f try1.pcap -n 0 -i zc:ens5f0@1 -l 1500
Sending packets on zc:ens5f0@1
pfring_open error [Operation not permitted] (pf_ring not loaded or interface zc:ens5f0@1 is down ?)

**Comment by cardigliano** [comment]
"Operation not permitted" are you running as root?

**Comment by utkarsh0902311047** [comment]
yes I am running as root. Usually when this kind of error appears I will go to ./drivers/intel/ice/ice-1.3.2-zc/./load_driver.sh. But it's working with 0 queue.

**Comment by cardigliano** [comment]
Please provide cat /proc/net/pf_ring/dev/ens5f0/info

**Comment by utkarsh0902311047** [comment]
Here it is
![Screenshot from 2021-08-04 19-53-21](https://user-images.githubusercontent.com/78134056/128176250-ddfd8ed4-b528-4cda-999b-2b92aa0421fa.png)

**Comment by cardigliano** [comment]
@utkarsh0902311047 it seems the ZC driver is not loaded actually. Any chance I can ssh and take a look?

**Comment by utkarsh0902311047** [comment]
I have mailed you.
I also repeat the configuration steps but I still get the same output for the cat /proc/net/pf_ring/dev/ens5f0/info as I showed above

**Comment by cardigliano** [comment]
This has been addressed with a driver update. Using RSS was able to generate 100Gbps.
