### ISSUE TITLE
incompatible type for argument 2 of ‘devlink_port_attrs_set’

### ISSUE THREAD

**Issue by RaD-Andrew** [ntop/PF_RING#744]
Hi All,

I'm currently trying to build a ZIP snapshot of the 7.8.0-stable branch (taken on Monday 2nd August) on RHEL 8.4 (4.18.0-305.7.1.el8_4.x86_64), and I see this and other errors:-

In file included from /root/PF_RING-7.8.0-stable/drivers/intel/i40e/i40e-2.13.10-zc/src/i40e.h:33,
                 from /root/PF_RING-7.8.0-stable/drivers/intel/i40e/i40e-2.13.10-zc/src/i40e_main.c:8:
/root/PF_RING-7.8.0-stable/drivers/intel/i40e/i40e-2.13.10-zc/src/kcompat.h: In function ‘_kc_devlink_port_attrs_set’:
/root/PF_RING-7.8.0-stable/drivers/intel/i40e/i40e-2.13.10-zc/src/kcompat.h:7321:44: error: incompatible type for argument 2 of ‘devlink_port_attrs_set’
  devlink_port_attrs_set(devlink_port, attrs->flavour,

These errors are occurring across the Intel drivers suite, although it's the i40e driver that we're primarily interested in.

The kernel and userland modules build just fine.

I'm using a tip of the 7.8.0-stable branch, and not the 7.8.0 release itself, because the latter complains about the missing 'linux/pci-aspm.h' file.  The kcompat.h file seems to base the present/not-present decision around a kernel version of >= 5, and if I understand correctly this has been fixed in one of the subsequent commits.

Any thoughts on the above error would be welcome.

**Comment by cardigliano** [comment]
@RaD-Andrew please note that the latest kernels are supported in the dev version (7.9). It seems that your kernel is not supported by the stable yet (7.8).

**Comment by RaD-Andrew** [comment]
Ah OK - apologies - I've missed that somehow.  I'll get a snapshot of the dev branch and will have a play.

**Comment by cardigliano** [comment]
@RaD-Andrew please let me know if it works. Thank you!

**Comment by RaD-Andrew** [comment]
Will do.  I'll leave this ticket open for now then.

**Comment by RaD-Andrew** [comment]
Morning Alfredo,

I can confirm that the dev branch snapshot taken yesterday does indeed build under RHEL8.4 / kernel 4.18.

However, we're now into build problems with our own code, and I can see that the at least one PFR function signature seems to have changed relative to 7.8.

Do you have an approximate timeframe for an official 7.9 release?  Your answer may influence what we do next :)

**Comment by cardigliano** [comment]
@RaD-Andrew what is the function signature which is creating issues? I will try to push a new stable for the next weeks, but there is not exact date yet.

**Comment by RaD-Andrew** [comment]
Sorry for the delay - got distracted with something else.

It's pfring_zc_create_cluster().
A,

EDIT
That's the only one causing a compile issue, but linking isn't picking up any pfring_zc_xxx() functions.  Looking into that now.

**Comment by cardigliano** [comment]
What is the signature (with all parameters) your "legacy" code is using?

**Comment by RaD-Andrew** [comment]
Our 7.4.0 code is missing the last argument - the 'flags' argument.  I'll read up about that later; looking into linking currently.

**Comment by cardigliano** [comment]
@RaD-Andrew we pushed a new stable (8.0) this week. However at this point we cannot revert the pfring_zc_create_cluster signature, please update the code to use the flags option.

**Comment by RaD-Andrew** [comment]
Thanks Alfredo – I’ll have a play.
A.

@RaD-Andrew<https://github.com/RaD-Andrew> we pushed a new stable (8.0) this week. However at this point we cannot revert the pfring_zc_create_cluster signature, please update the code to use the flags option.
This email and any files transmitted with it are confidential and contain information which may be privileged or confidential and are intended solely to be for the use of the individual(s) or entity to which they are addressed. If you are not the intended recipient be aware that any disclosure, copying, distribution or use of the contents of this information is strictly prohibited and may be illegal. If you have received this email in error, please notify us by telephone or email immediately and delete it from your system. Activity and use of our email system is monitored to secure its effective operation and for other lawful business purposes. Communications using this system will also be monitored and may be recorded to secure effective operation and for other lawful business purposes. Internet emails are not necessarily secure. We do not accept responsibility for changes made to this message after it was sent. You are advised to scan this message for viruses and we cannot accept liability for any loss or damage which may be caused as a result of any computer virus.

This email is sent by a bet365 group entity. The bet365 group includes the following entities: Hillside (Shared Services 2018) Limited (registration no. 11638014), bet365 Group Limited (registration no. 4241161), Hillside (Technology) Limited (registration no. 8273456), Hillside (Media Services) Limited (registration no. 9171710), Hillside (Trader Services) Limited (registration no. 9171598) each registered in England and Wales with a registered office address at bet365 House, Media Way, Stoke-on-Trent, ST1 5SZ, United Kingdom; Hillside (UK Sports) ENC (registration no. P1892) and Hillside (UK Gaming) ENC (registration no. P1888) each registered in Malta with a registered office address at Office 1/2373, Level G, Quantum House, 75 Abate Rigord Street, Ta’ Xbiex, XBX 1120, Malta; Hillside (Sports) GP Limited (registration no. 111829) and Hillside (Gaming) GP Limited (registered no. 111830) each registered in Gibraltar with a registered office address at Unit 1.1, First Floor, Waterport Place, 2 Europort Avenue, Gibraltar; Hillside (Sports) LP (registration no. 118), Hillside (International Sports) LP (registration no. 119), Hillside (Gaming) LP (registration no. 120) and Hillside (International Gaming) LP (registration no. 121) each registered in Gibraltar with a principal place of business at Unit 1.1, First Floor, Waterport Place, 2 Europort Avenue, Gibraltar; Hillside España Leisure S.A (CIF no. A86340270) registered in Spain with a registered office address at C/ Conde de Aranda nº20, 2º, 28001 Madrid, Spain; Hillside (Australia New Media) Pty Limited (registration no. 148 920 665) registered in Australia with a registered office address at Level 27, 100 Mount Street, North Sydney, NSW 2060, Australia; Hillside (New Media Malta) Plc, (registration no c.66039), Hillside (Sports) ENC, (registration no. P1811) and Hillside (Gaming) ENC (registration no. P1812) registered in Malta with a registered office address at Office 1/2373, Level G, Quantum House, 75 Abate Rigord Street, Ta’ Xbiex XBX 1120, Malta and Hillside (New Media Cyprus) Limited, (registration no. HE 361612) registered in Cyprus with a registered office address at Omrania Centre, 313, 28th October Avenue, 3105 Limassol, Cyprus. Hillside (New Jersey) LLC with a registered office address at Suite 200, Two Greentree Center, 9000 Lincoln Drive East, Marlton, New Jersey, 08053, United States. Lucky Stream Limited, a limited liability company organised under the laws of Malta, with company number C53884 and having its registered office address at Office 1/2373, Level G, Quantum House, 75 Abate Rigord Street, Ta’ Xbiex, XBX 1120, Malta. For residents of Mexico, this email is sent on behalf of Ganador Azteca, S.A.P.I. de C.V., a Mexican corporation of variable capital incorporated under the laws of Mexico, with address at Periférico Sur 4121, Fuentes del Pedregal, Tlalpan, 14140, Mexico City, Mexico. For residents of Russia, this email is sent on behalf of Golden Bet LLC, a betting company, which operates under licence No. 32 of the Federal Tax Service of the Russian Federation, issued on 5th July 2018, with address at 2nd Kozhukhovsky proezd 29, k2, str 16, floor 6, space I, room 20b, Moscow, 115432 Golden Bet LLC.

**Comment by RaD-Andrew** [comment]
Thanks Alfredo - I'll have a play.
