### ISSUE TITLE
dpkg error: " dpkg: error processing package ice-zc-dkms (--configure):

### ISSUE THREAD

**Issue by utkarsh0902311047** [ntop/PF_RING#746]
Hi,
Since last week I am trying to update and upgrade Ubuntu 20.04 and I keep getting errors for dpkg.
I have attached the snapshot of the errors.

Please help
![Screenshot from 2021-08-10 13-17-20](https://user-images.githubusercontent.com/78134056/128822040-3e852629-f31d-4a3c-b41f-f4e200a7e1fb.png)

**Comment by cardigliano** [comment]
@utkarsh0902311047 are you running Ubuntu server LTS with the default kernel? I see you are running kernel 5.11, it should be 5.8 (this is what Ubuntu 20 is running in our lab)

**Comment by utkarsh0902311047** [comment]
I am using Ubuntu Desktop 20.04.2 LTS
So it won't work on Kernel 5.11? 
Which kernel should I install from the image attached?
![kernel_version](https://user-images.githubusercontent.com/78134056/128827531-43acc67b-3500-4391-b44e-b05908f3efa6.png)

**Comment by cardigliano** [comment]
I suggest to install 5.8 which is what is supposed to run on Ubuntu 20

**Comment by utkarsh0902311047** [comment]
I have now set kernel 5.8 but still get the same errors.
![Screenshot from 2021-08-10 18-00-11](https://user-images.githubusercontent.com/78134056/128847919-cb21fcf9-c9be-44f4-b6ae-ff560eb18872.png)

**Comment by cardigliano** [comment]
Could you provide one of the generated log files? (e.g. /var/lib/dkms/ixgbe-zc/5.5.3.6804/build/make.log)

**Comment by utkarsh0902311047** [comment]
Here it is
[make.log](https://github.com/ntop/PF_RING/files/6963038/make.log)

**Comment by utkarsh0902311047** [comment]
Please give any suggestions what should I try?

**Comment by cardigliano** [comment]
It seems to be due to the kernel version, you are running a 5.8.0-050800-generic, the Ubuntu kernel version should look like 5.8.0-48-generic

**Comment by utkarsh0902311047** [comment]
Ok now when I set the kernel to 5.8.0-63-generic, it gets updated properly. Thank you for helping with updating.
Now when I use the pf_ringcfg --configure-driver ice --rss-queues 4, cat /proc/net/pf_ring/dev/ens5f1/info shows zc driver but TX and RX queues still show 1. They should show 4 right?
![Screenshot from 2021-08-12 22-07-40](https://user-images.githubusercontent.com/78134056/129211484-48faa35f-b621-45af-8a19-25bb477d19e7.png)

**Comment by cardigliano** [comment]
What pf_ring version are you using? 
Please provide cat /etc/pf_ring/zc/ice/ice.conf
Please try with a reboot to make sure pf_ring is reloaded.

**Comment by utkarsh0902311047** [comment]
![Screenshot from 2021-08-12 22-16-52](https://user-images.githubusercontent.com/78134056/129213739-9e034f7a-e424-4c8c-bb8f-d5a919f93bcc.png)
PF_RING version 8.1.0. It automatically gets updated to 8.1.0 when I run apt-get update && apt-get upgrade

**Comment by cardigliano** [comment]
Please try with a reboot to make sure pf_ring is reloaded.
After that please provide cat /proc/net/pf_ring/dev/ens5f1/info again.

**Comment by utkarsh0902311047** [comment]
After reboot this is the output of the command cat /proc/net/pf_ring/dev/ens5f1/info 
![Screenshot from 2021-08-13 16-13-46](https://user-images.githubusercontent.com/78134056/129326134-d374581e-3fb1-4a42-b52d-22f613d89fb6.png)

**Comment by cardigliano** [comment]
The ice driver is not getting loaded, it looks like a misconfiguration, please provide:

tree /etc/pf_ring
cat /proc/net/pf_ring/info

**Comment by utkarsh0902311047** [comment]
here it is
![Screenshot from 2021-08-13 16-37-35](https://user-images.githubusercontent.com/78134056/129329476-eba202c2-1927-4821-b141-995c12b4e873.png)

**Comment by cardigliano** [comment]
Uhm you said "updated to 8.1.0", but 8.0.0 is loaded, please cleanup the environment

**Comment by cardigliano** [comment]
and make sure ice-zc-dkms is installed

**Comment by utkarsh0902311047** [comment]
> Uhm you said "updated to 8.1.0", but 8.0.0 is loaded, please cleanup the environment

First I was trying with development builds which installs pfring 8.1.0
Since it was not giving satisfactory results I tried stable build.

Yes, this command I have already executed "apt-get install pfring-drivers-zc-dkms ".
Should I install development builds?

**Comment by cardigliano** [comment]
Please do a "systemctl restart pf_ring" and provide me the output of "systemctl status pf_ring"

**Comment by utkarsh0902311047** [comment]
It seems ice-zc driver not installed properly. But there was no error while installing. What should I do about it?
![pf_ring_error1](https://user-images.githubusercontent.com/78134056/129433107-2a2cafb4-def9-4b21-9066-5d62d0cdc47d.png)

**Comment by cardigliano** [comment]
Please make sure the ice-zc-dkms package is installed.

apt-get update
apt-get install ice-zc-dkms

**Comment by utkarsh0902311047** [comment]
I update and then apt-get install ice-zc-dkms says E: Unable to locate package ice-zc-dkms
![Screenshot from 2021-08-16 16-12-01](https://user-images.githubusercontent.com/78134056/129532561-b2124ec7-bac9-40a3-bcb1-6797343df3a0.png)

**Comment by cardigliano** [comment]
@utkarsh0902311047 it seems there is some misconfiguration, the ixe-zc-dkms package is actually available for Ubuntu 20 as you can see at https://packages.ntop.org/apt/20.04/all/ (it is working for me). Please try reconfiguring the repository.

**Comment by utkarsh0902311047** [comment]
When I run this command "apt install ./apt-ntop.deb", I get the following message in the end. Should I ignore it?
N: Download is performed unsandboxed as root as file '/root/apt-ntop.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

**Comment by utkarsh0902311047** [comment]
I have again download the repository from development build. The pf_ring version is now 7.9.0. The ice driver is installed. 
But the queues it shows is still 1.
I have attached a snapshot of the commands 
 cat /proc/net/pf_ring/dev/ens5f1/info
cat /etc/pf_ring/zc/ice/ice.conf
cat /proc/net/pf_ring/info
![Screenshot from 2021-08-18 14-08-10](https://user-images.githubusercontent.com/78134056/129847364-76e99975-fdcb-464e-a9cf-9e3515051bc1.png)

**Comment by cardigliano** [comment]
@utkarsh0902311047 please note the pf_ring version in the dev/nightly build repository is 8.1, this means there is some misconfiguration. If you installed latest packages, it is likely the pf_ring module has not been reloaded (or it has not been reinstalled by dkms, or there is some old pf_ring.ko module installed). First of all I would try with a system reboot. If the problem is still there, I would try playing with the dkms command to rebuild the pf_ring module.

**Comment by utkarsh0902311047** [comment]
Ok done. Now what should I do to get the queues equal to 4?
![Screenshot from 2021-08-18 15-09-09](https://user-images.githubusercontent.com/78134056/129853843-654daac5-1b11-4eca-95ee-d1b105c05c83.png)

**Comment by cardigliano** [comment]
Set RSS=4,4 in /etc/pf_ring/zc/ice/ice.conf, then restart the pfring service with systemctl restart pf_ring

**Comment by utkarsh0902311047** [comment]
I already tried that. But still it shows queues 1.

**Comment by cardigliano** [comment]
@utkarsh0902311047 are you still unable to set RSS? Could you provide ssh access?

**Comment by utkarsh0902311047** [comment]
Yes, I am still unable to set the TX and RX queues 4. 
I have injured my leg so I am not able to go to the lab this week.
Is it possible to give you ssh access next week?

**Comment by cardigliano** [comment]
Sure, feel free to come back on this as soon as you recover from the injury. Drop an email to cardigliano at ntop.org with the credentials.
