### ISSUE TITLE
100% packet drop on pfcount ice

### ISSUE THREAD

**Issue by ShijunGao** [ntop/PF_RING#748]
Hello, bros!
I have problems with GIT version of PF_RING. I am encountering 100% packet drop using pfcount.

check pf_ring info 
![image](https://user-images.githubusercontent.com/20250923/129541171-7e062e2a-c94c-458a-91eb-2eda8b1a3842.png)

![image](https://user-images.githubusercontent.com/20250923/129538040-7fb80de4-01ea-4153-924f-f09db31d8817.png)

run `./pfcount -i zc:eth2`

![image](https://user-images.githubusercontent.com/20250923/129540149-b09c4ec8-0176-45ad-80f8-1b2e2b485853.png)

run `cat /proc/net/pf_ring/dev/eth2/info`

![image](https://user-images.githubusercontent.com/20250923/129540926-864e5f8b-0462-4a50-a5c5-d25a2d7c734c.png)

**Comment by cardigliano** [comment]
@ShijunGao could you try updating to the latest version (8.1) first of all, to make sure we are using/looking at the same code? Thank you.

**Comment by ShijunGao** [comment]
> @ShijunGao could you try updating to the latest version (8.1) first of all, to make sure we are using/looking at the same code? Thank you.

Hi，
Now update to the latest version (8.1) from git, the problem is still here.
![image](https://user-images.githubusercontent.com/20250923/129655880-928c28d8-2c19-4a36-ae07-c1fa37defb73.png)
Using PF_RING v.8.1.0
Capturing from zc:eth2 [mac:xxxxx][if_index: 7][speed: 10000Mb/s]
# Device RX channels: 1
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/2831-eth2.1
=========================
Absolute Stats: [7'003'339 pkts total][7'003'339 pkts dropped][100.0% dropped]
[0 pkts rcvd][0 bytes rcvd]
=========================

=========================
Absolute Stats: [14'224'208 pkts total][14'224'208 pkts dropped][100.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.22 ms][0.00 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [21'466'247 pkts total][21'466'247 pkts dropped][100.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.10 ms][0.00 pps][0.00 Gbps]

**Comment by cardigliano** [comment]
@ShijunGao please provide the output of dmesg (please upload a txt file)

**Comment by ShijunGao** [comment]
[dmesg.txt](https://github.com/ntop/PF_RING/files/7004131/dmesg.txt)


> @ShijunGao please provide the output of dmesg (please upload a txt file)
thx

**Comment by cardigliano** [comment]
@ShijunGao everything looks fine from dmesg, any chance you can provide ssh access to debug this? Please drop an email to cardigliano at ntop.org

**Comment by ShijunGao** [comment]
> @ShijunGao everything looks fine from dmesg, any chance you can provide ssh access to debug this? Please drop an email to cardigliano at ntop.org

Thank you ! I don't know why,btw it workers now!

**Comment by wangfeng22** [comment]
> > @ShijunGao everything looks fine from dmesg, any chance you can provide ssh access to debug this? Please drop an email to cardigliano at ntop.org
> 
> Thank you ! I don't know why,btw it workers now!

@ShijunGao  I encountered the same problem. Do you know why now?
