### ISSUE TITLE
Source code zc

### ISSUE THREAD

**Issue by mahdi1001** [ntop/PF_RING#75]
Hi
I need some source code from libpfring_zc, for example 
u_char \* pfring_zc_pkt_buff_data( pfring_zc_pkt_buff *pkt_handle,  pfring_zc_queue *queue);.

Is impossible give me this function source code?

**Comment by cardigliano** [comment]
The ZC library is distributed in binary format, why do you need the pfring_zc_pkt_buff_data source code?

Alfredo

**Comment by mahdi1001** [comment]
I need convert pkt to other struct.

**Comment by cardigliano** [comment]
Isn’t a cast enough?

my_struct *pkt = (my_struct *) pfring_zc_pkt_buff_data(pkt_handle, queue);

Alfredo

**Comment by mahdi1001** [comment]
I know it, but it is not work.

**Comment by Vehere-VIPL** [comment]
Hi,

How can I get Capture Device Name (like eth0 or p6p1 etc) per packet with PF_RING+ZC?

**Comment by cardigliano** [comment]
@vhere-ccu are you capturing from multiple interfaces? What API are you using?
