### ISSUE TITLE
modprobe pf_ring 6.4.1 error on 3.16.0-6-amd64 Debian

### ISSUE THREAD

**Issue by andyarus** [ntop/PF_RING#751]
Hello!
I get error on Debian 3.16.0-6-amd64

**sudo modprobe pf_ring
modprobe: ERROR: could not insert 'pf_ring': Unknown symbol in module, or unknown parameter (see dmesg)
dmesg:
pf_ring: Unknown symbol sk_detach_filter (err 0)**

On Debian 3.16.0-4-amd64 all work fine

**sudo modinfo pf_ring && sudo cat /proc/net/pf_ring/info**
filename:       /lib/modules/3.16.0-4-amd64/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
depends:
vermagic:       3.16.0-4-amd64 SMP mod_unload modversions
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           transparent_mode:(deprecated) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)
PF_RING Version          : 6.4.1 (6.4.1-stable:db7bbc5160303d6f3a1985248455ac03a0a3298d)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

**Comment by andyarus** [comment]
It look like
[https://www.mail-archive.com/ntop-misc@listgateway.unipi.it/msg06379.html](url)
Could you please also make a patch for PF RING 6.4.1?

**Comment by cardigliano** [comment]
@andyarus we no longer support 6.4 which is quite old (latest stable is 8.0), feel free to send a PR

**Comment by andyarus** [comment]
Ok thanks
