### ISSUE TITLE
run ftflow_dpdk  application in fwd mode

### ISSUE THREAD

**Issue by anust** [ntop/PF_RING#757]
from the example code it is clear that its being written for forward mode, but it is not forwarding any packets and showing a huge packet loss when tested with t-rex.

command 

`sudo ./build/ftflow_dpdk  -- -p 0,1 -F -7`

**Comment by cardigliano** [comment]
@anust correct, the -F option enables packet forwarding between ports, however it may be it is not really optimized, a code review is required for performance tests. Please feel free to send a PR if you wish.

**Comment by anust** [comment]
@cardigliano Plz tell how to print per packer dpi result , instead of cumulative results at then end of the application.

**Comment by cardigliano** [comment]
Please see pfring_ft_set_flow_packet_callback (called when a packet and its flow have been processed, for each packet) and pfring_ft_set_l7_detected_callback (called when a packet and its flow have been processed and the l7 protocol has been just detected)
