### ISSUE TITLE
ZC startup error

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#759]
------------------------------------------

[root@SPAN src]# pf_ringcfg --configure-driver i40e --rss-queues  10 --force 
[>] Configuring PF_RING
[>] Configuring hugepages
[>] Detecting interfaces using i40e
ens2f3
ens2f1
ens1f1
eno1
ens2f2
eno2
ens2f0
ens1f0
[>] Configuring i40e driver with 10 RSS queues
[>] Restarting PF_RING
[>] Configuration completed
------------------------------------------------------------

-------------------------------------------------------------

[root@SPAN src]# cento -i zc:ens1f1@[0-9]  -5 192.168.14.72:9995 -D 0
09/Sep/2021 11:19:55 [cento.cpp:1697] Welcome to nProbe cento v.1.14.210908
09/Sep/2021 11:19:55 [cento.cpp:1698] Copyright 2015-21 - ntop
09/Sep/2021 11:19:55 [cento.cpp:1701] SystemId: L563F0554B208AA8F--U563F0554A7940483--OL
09/Sep/2021 11:19:55 [cento.cpp:1704] Permanent nProbe cento L license found [/etc/cento.license]
09/Sep/2021 11:19:55 [cento.cpp:1720] Built on CentOS Linux release 8.3.2011
09/Sep/2021 11:19:55 [cento.cpp:1721] Available CPU Cores: 48
09/Sep/2021 11:19:55 [cento.cpp:1722] Max flow duration set to 120 sec (-t)
09/Sep/2021 11:19:55 [cento.cpp:1723] Max flow idleness set to 30 sec (-d)
09/Sep/2021 11:19:55 [cento.cpp:1724] Flow hash size set to 512000 buckets (-w)
09/Sep/2021 11:19:55 [cento.cpp:1725] Hashes will have up to 1024000 buckets (-W)
09/Sep/2021 11:19:58 [cento.cpp:2008] Initialized global ZC cluster 10
0**9/Sep/2021 11:19:58 [ZCInterface.cpp:33] ERROR: pfring_zc_open_device error [Socket operation on non-socket] Please check that zc:ens1f1@0 is up and not already used
09/Sep/2021 11:19:58 [cento.cpp:2069] WARNING: Unable to open zc:ens1f1@0 (is pf_ring module loaded, and HugePages configured?)**
[root@SPAN src]# 

-------------------------------------------------------------

**Comment by cardigliano** [comment]
Are you able to run pfcount on the same interface? pfcount -i zc:ens1f1@0
Did you check that there is no other application using the same interface?

**Comment by MaoPann** [comment]
@cardigliano 

I comfirm other application using the same interface,Because I reboot frist.I don't think ZC driver starts normally.

I also try install use git , report same error as above,and i find this.
![image](https://user-images.githubusercontent.com/44804599/132646482-8866b12b-ef93-4a1b-8b2c-e19ac051e139.png)

**Comment by cardigliano** [comment]
Did you check the pf_ring service log (systemctl status pf_ring) after reboot to check for failures loading the driver?
Alternatively, if you use the load script, could you try removing the i40iw iWarp module with rmmod i40iw before loading the zc driver?

**Comment by MaoPann** [comment]
I tried rmmod i40iw but failed. Can you use TeamViewer to view the problem remotely? This problem comes from a customer who bought cento and pfring ZC not long ago. They are now experiencing this problem in installation and use.

**Comment by cardigliano** [comment]
Please drop an email to cardigliano at ntop.org, we will schedule a debug session

**Comment by cardigliano** [comment]
Fixed
