### ISSUE TITLE
ZC driver compilation fail

### ISSUE THREAD

**Issue by ppeska** [ntop/PF_RING#76]
Hi, I´ve recently purchased PF_RING ZC serial. After installation of pf_ring-6.3.0 I tried to compile ZC drivers included but with this error message : 

cd intel; make
make[1]: Entering directory `/PF_RING-6.0.3/drivers/ZC/intel'
cd igb/igb-5.2.5-zc/src; make
make[2]: Entering directory`/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src'
make -C /lib/modules/3.10.0-327.3.1.el7.x86_64/build SUBDIRS=/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-327.3.1.el7.x86_64'
  CC [M]  /PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.o
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c: In function ‘igb_ndo_bridge_getlink’:
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c:2567:2: error: too few arguments to function ‘ndo_dflt_bridge_getlink’
  return ndo_dflt_bridge_getlink(skb, pid, seq, dev, mode);
  ^
In file included from include/net/dst.h:13:0,
                 from include/net/sock.h:68,
                 from include/linux/tcp.h:23,
                 from /PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c:33:
include/linux/rtnetlink.h:87:12: note: declared here
 extern int ndo_dflt_bridge_getlink(struct sk_buff *skb, u32 pid, u32 seq,
            ^
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c: In function ‘igb_xmit_frame_ring’:
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c:5849:2: error: implicit declaration of function ‘vlan_tx_tag_present’ [-Werror=implicit-function-declaration]
  if (vlan_tx_tag_present(skb)) {
  ^
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c:5851:3: error: implicit declaration of function ‘vlan_tx_tag_get’ [-Werror=implicit-function-declaration]
   tx_flags |= (vlan_tx_tag_get(skb) << IGB_TX_FLAGS_VLAN_SHIFT);
   ^
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c: In function ‘igb_ndo_get_vf_config’:
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c:9962:5: error: ‘struct ifla_vf_info’ has no member named ‘tx_rate’
  ivi->tx_rate = adapter->vf_data[vf].tx_rate;
     ^
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c: In function ‘igb_ndo_bridge_getlink’:
/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.c:2568:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
cc1: some warnings being treated as errors
make[4]: *** [/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src/igb_main.o] Error 1
make[3]: *** [_module_/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src] Error 2
make[3]: Leaving directory`/usr/src/kernels/3.10.0-327.3.1.el7.x86_64'
make[2]: **\* [default] Error 2
make[2]: Leaving directory `/PF_RING-6.0.3/drivers/ZC/intel/igb/igb-5.2.5-zc/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/PF_RING-6.0.3/drivers/ZC/intel'
make: **\* [all] Error 2

Thanks for prompt help !

**Comment by cardigliano** [comment]
Please use latest drivers available on github

**Comment by ppeska** [comment]
Thank you, but after the installation of the latest drivers - I have still the same problem ! Bad kerenel version ?

**Comment by cardigliano** [comment]
I was able to reproduce after updating my centos7 kernel, fix in ced442a9fbc33afc65eace9ff6c74bce64ef2697
Please test it and let us know. Thank you.
