### ISSUE TITLE
Packet received with pfring_recv and pcap_next_ex doesn't have the same payload

### ISSUE THREAD

**Issue by teoring** [ntop/PF_RING#764]
Hello,

I am using PFRING 7.8.0 from 7.8.0-stable branch commit f0df19b.
Ubuntu 20.04.3 LTS host, x86_64 arch.
Libpcap from the PFRING repo, v1.9.1, compiled together with pfring.

We are parsing the same packet in two ways. In the first case, we just get it from the interface with pfring_recv and packet is already parsed. In the second case we are getting the packet from PCAP with pcap_next_ex call and then call pfring_parse_pkt. In 7.8.0 we are getting a different packet payload in both cases. 

In PFRING 7.2.0 the behavior of pfring_recv and pcap_next_ex was consistent. We were receiving a packet data with header, by getting hdr.extended_hdr.parsed_pkt.offset.l3_offset + ipHdr->ip_hl * 4 offset we were able to reach ERSPAN header, where  ERSPAN Protocol Type always had swapped bytes so we just invoked ntohs to get a correct value.

In 7.8.0 with pfring we receive a packet that in ERSPAN header contains correct ERSPAN Protocol Type 0x88be instead of reversed, but pcap_next_ex still provides 0xbe88 ( swapped ).

This might not be an issue but I though since libpcap comes in a bundle, you might wanted to have a consistent behavior ( if this is an issue indeed and not my mistake ).

**Comment by cardigliano** [comment]
@teoring sorry for late reply, please provide a PCAP with a packet that we can use to reproduce this.

**Comment by teoring** [comment]
@cardigliano Unfortunately, I can't share the PCAP due to policies. I am okay to close this ticket.

**Comment by cardigliano** [comment]
Ok, please reopen if you can still reproduce and provide more info to help us debug it
