### ISSUE TITLE
pfring_set_cluster regression in comparison to PFRING 7.2.0

### ISSUE THREAD

**Issue by teoring** [ntop/PF_RING#765]
Hello,

I am using PFRING 7.8.0 from 7.8.0-stable branch commit f0df19b.
Ubuntu 20.04.3 LTS host, x86_64 arch.

I have this powerful server where I was running my application with 69 worker threads using PFRING 7.2.0. Every worker thread was calling pfring_set_cluster for load balancing.

> silentdefense@artem-72:~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          72
On-line CPU(s) list:             0-71
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       72
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Stepping:                        0
CPU MHz:                         2095.078
BogoMIPS:                        4190.15
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       2.3 MiB
L1i cache:                       2.3 MiB
L2 cache:                        72 MiB
L3 cache:                        2 GiB
NUMA node0 CPU(s):               0-35
NUMA node1 CPU(s):               36-71
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_ti
                                 mer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear flush_l1d arch_capabilities

After update to PFRING 7.8.0 I am only able to spawn 64 worker threads maximum. pfring_set_cluster returns < 0 on worker #65.
Is that expected?

**Comment by cardigliano** [comment]
Tested on pf_ring 8.x with 70 cluster consumers
