### ISSUE TITLE
nprobe Cento (Licensed) pfring_zc_open_driver error with Ubuntu 18.04 kernel 5.4.0-89-generic

### ISSUE THREAD

**Issue by sohailanjum97** [ntop/PF_RING#768]
I am using the nProbe Cento Licensed version which requires a pf_ring ZC driver. I have installed and followed the instruction from the official website 
https://packages.ntop.org/apt/ 
and be specific for ZC drivers using this command.
apt-get install pfring-drivers-zc-dkms

my RSS 4,4.  I have set the huge pages: 
There are some screenshots for your reference.
OS:  Ubuntu 18.04.5 LTS (Kernel 5.4.0-89-generic)

Hugepages Setting:
![Screenshot from 2021-11-04 16-50-31](https://user-images.githubusercontent.com/48083468/140294970-5212cdbf-9957-4641-9dd3-d717e6a10669.png)

Unable to locate Driver:
![Screenshot from 2021-11-04 17-04-06](https://user-images.githubusercontent.com/48083468/140295030-e36dc899-e1cf-4ae4-b0a3-20770170e333.png)

Tree
![Screenshot from 2021-11-04 17-59-13](https://user-images.githubusercontent.com/48083468/140295092-7986aac2-c9c2-4246-9807-0f6259321d3f.png)

Info

![Screenshot from 2021-11-04 17-59-51](https://user-images.githubusercontent.com/48083468/140295127-1ab5a04c-7c16-4179-92c4-ca956c371ae8.png)

Cento output

![Screenshot from 2021-11-04 18-00-17](https://user-images.githubusercontent.com/48083468/140295183-f5615580-7a17-43de-8b3c-980437513455.png)

**Comment by cardigliano** [comment]
Please provide cat /proc/net/pf_ring/dev/enp24s0f0/info

**Comment by sohailanjum97** [comment]
Please see the 2nd last screenshot. Info is available there.

**Comment by cardigliano** [comment]
Ok I see that, it seems the driver has not been actually loaded, weird. Any chance you can provide ssh (or other) access to this system for debugging? (drop an email to cardigliano at ntop.org in case)

**Comment by sohailanjum97** [comment]
Sent email. Please check wether it’s in the inbox or spam may be.

**Comment by sohailanjum97** [comment]
Facing another issue now.
![54D31BE4-A762-4CE9-A3E1-B28CE61B0BB3](https://user-images.githubusercontent.com/48083468/140482480-89780c35-628e-4c03-8417-8ccebd4f3238.jpeg)

**Comment by cardigliano** [comment]
@sohailanjum97 this is expected as the driver is not loaded, I will fix the driver in your system

**Comment by sohailanjum97** [comment]
Ok
