### ISSUE TITLE
Reopen Crashed/Killed ZC application

### ISSUE THREAD

**Issue by bth-kumar** [ntop/PF_RING#769]
Hi,

Is there any way (linux cmds) to restart the zc application if it is crashed/killed just before. Every time I used to unload and reload the modules.
I generally get two types of error: -
1. Port is already open
2. No hugepage available.

**Comment by cardigliano** [comment]
@bth-kumar there should be no need to reload the modules, when you get something like "port is already open" please make sure there is no application running on the same ZC cluster.
