### ISSUE TITLE
PF_RING-6.2.0 ZC mode  memory Always increase ,and final  hang

### ISSUE THREAD

**Issue by huangsheng-dafo** [ntop/PF_RING#77]
[root@localhost hs]# uname -a
Linux localhost.localdomain 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux
# [root@localhost hs]# ./zcount -i zc:eth1 -c 11
# Absolute Stats: 14 pkts (0 drops) - 1'208 bytes

[root@localhost ~]# free
             total       used       free     shared    buffers     cached
Mem:      32854280   14462000   18392280          0      15396     512704
-/+ buffers/cache:   13933900   18920380
Swap:     35094520          0   35094520

**Comment by cardigliano** [comment]
Could you provide more details? Does memory utilisation increases on every application start, or while the application is running? Could you provide more details about memory utilisation (e.g. /proc/meminfo) over time? 
Thank you.

**Comment by huangsheng-dafo** [comment]
the application is running When capturing traffic..
[root@localhost ~]# more /proc/meminfo 
MemTotal:       32854280 kB
MemFree:        17778348 kB
Buffers:           19220 kB
Cached:           538612 kB
SwapCached:            0 kB
Active:           538452 kB
Inactive:          83876 kB
Active(anon):      65012 kB
Inactive(anon):     1044 kB
Active(file):     473440 kB
Inactive(file):    82832 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      35094520 kB
SwapFree:       35094520 kB
Dirty:                44 kB
Writeback:             0 kB
AnonPages:         64792 kB
Mapped:            41116 kB
Shmem:              1276 kB
Slab:           11967864 kB
SReclaimable:      24228 kB
SUnreclaim:     11943636 kB
KernelStack:        2824 kB
PageTables:        11748 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    50473084 kB
Committed_AS:     491468 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      350444 kB
VmallocChunk:   34340880896 kB
HardwareCorrupted:     0 kB
AnonHugePages:     10240 kB
HugePages_Total:    1024
HugePages_Free:      960
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:        6144 kB
DirectMap2M:     2082816 kB
DirectMap1G:    31457280 kB

**Comment by cardigliano** [comment]
Please provide memory utilisation _over time_: please start zcount and take a snapshot of /proc/meminfo (or any other useful stats), then after some time when memory utilisation is increased significantly, take another shapshot. Thank you.

**Comment by huangsheng-dafo** [comment]
Operating system is Centos6.2 x86_64, and PF_RING Version is 6.2.0,
[root@localhost src]# more /proc/net/pf_ring/info 
PF_RING Version          : 6.2.0 (6.2.0-stable:xxxxxx)
Total rings              : 3

Standard (non DNA/ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

Before start ./zcount -i zc:eth1 -c 11, Memory utilization is as follows

[root@localhost ~]# more /proc/meminfo
MemTotal:       32854280 kB
MemFree:        30177780 kB
Buffers:            9064 kB
Cached:            46452 kB
SwapCached:            0 kB
Active:            79560 kB
Inactive:          38868 kB
Active(anon):      63164 kB
Inactive(anon):      940 kB
Active(file):      16396 kB
Inactive(file):    37928 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      35094520 kB
SwapFree:       35094520 kB
Dirty:                36 kB
Writeback:             0 kB
AnonPages:         62968 kB
Mapped:            34220 kB
Shmem:              1148 kB
Slab:              78092 kB
SReclaimable:      10032 kB
SUnreclaim:        68060 kB
KernelStack:        2824 kB
PageTables:        11600 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    50473084 kB
Committed_AS:     475816 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      343848 kB
VmallocChunk:   34340932512 kB
HardwareCorrupted:     0 kB
AnonHugePages:     12288 kB
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:        6144 kB
DirectMap2M:     2082816 kB
DirectMap1G:    31457280 kB

Running ./zcount -i zc:eth1 -c 11, At the same time to download large files,
Memory utilization always increase, 10 minutes later, Memory utilization is as follows:

[root@localhost ~]# more /proc/meminfo 
MemTotal:       32854280 kB
MemFree:        27814872 kB
Buffers:           10660 kB
Cached:           140732 kB
SwapCached:            0 kB
Active:           163076 kB
Inactive:          52852 kB
Active(anon):      65004 kB
Inactive(anon):      940 kB
Active(file):      98072 kB
Inactive(file):    51912 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      35094520 kB
SwapFree:       35094520 kB
Dirty:              1296 kB
Writeback:             0 kB
AnonPages:         64824 kB
Mapped:            40948 kB
Shmem:              1148 kB
Slab:            2337704 kB
SReclaimable:      12696 kB
SUnreclaim:      2325008 kB
KernelStack:        2824 kB
PageTables:        11664 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    50473084 kB
Committed_AS:     488268 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      350444 kB
VmallocChunk:   34340919608 kB
HardwareCorrupted:     0 kB
AnonHugePages:     12288 kB
HugePages_Total:    1024
HugePages_Free:      960
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:        6144 kB
DirectMap2M:     2082816 kB
DirectMap1G:    31457280 kB

# ./zcount -i zc:eth1 -c 11

Absolute Stats: 1'297'633 pkts (0 drops) - 1'147'031'892 bytes

# Actual Stats: 20.00 pps (0.00 drops) - 0.00 Gbps

**Comment by cardigliano** [comment]
Some more questions:
1. what is the driver model? ethtool -i eth1
2. what does it mean exactly "at the same time to download large files"?
Thank you

**Comment by huangsheng-dafo** [comment]
[root@localhost ~]# ethtool -i eth1
driver: e1000e
version: 3.2.7.1-NAPI
firmware-version: 2.1-3
bus-info: 0000:07:00.0

The more data packets are captured, the more memory is used. 
To download large files is to quickly consume memory.

**Comment by cardigliano** [comment]
f30cacf1c01e4fdc1225415416bec169ed79d211 fixes a memory leak, please update, from github or packages (available in 1h), and let us know.
Thank you for reporting!
