### ISSUE TITLE
Failed to send data repeatedly

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#771]
For some special reasons, we need to send some packets repeatedly.

As shown in the figure below, I intend to send the same data packet repeatedly using the for loop for many times. The sender program shows that all data packets are sent successfully, but our receiver can only receive the first data sent repeatedly.
![image](https://user-images.githubusercontent.com/44804599/141727361-042eec76-eb8c-44fa-b00a-2101fe3b4552.png)

**Comment by MaoPann** [comment]
Supplementary note, we use ZC driver

**Comment by cardigliano** [comment]
I am not sure I got his, please rephrase. You said "I intend to send the same data packet repeatedly " and "our receiver can only receive the first data sent repeatedly", thus sounds expected.

**Comment by MaoPann** [comment]
I mean, for example, we want to repeatedly send packet AAA 10 times, and the sending program shows that it has been successfully sent 10 times, but in fact, we only receive AAA  once at the receiving end, and we expect to receive AAA  10 times at the receiving end.

**Comment by cardigliano** [comment]
Please note that when you send the packet, the g_postZpbSend is replaced with a fresh buffer, thus you need to forge the packet again in the new data pointer referenced by g_postZpbSend

**Comment by MaoPann** [comment]
fixed, thanks,
