### ISSUE TITLE
Why PF_RING ZC license  needed to send traffic on Napatech port using disk2n?

### ISSUE THREAD

**Issue by gautamch13** [ntop/PF_RING#772]
Hi Team, 

We trying to use disk2n on napatech port and we have procured the license for disk2n.
 But we are not able to understand why would PF_RING zc license will be required in this case? 
Can you help us so that we can use it without ZC license .

#disk2n -f pcef-gtp-sessions.pcap -i nt:0 -I 30 -C 65535 -b 20480 -c 12 -w 13 -S 14 -v

########################################################################## 
ERROR: You do not seem to have a valid PF_RING-Napatech 8.0.0.210811# license for port 0 (S/N 840-0045-03-20-0000-261008 / MAC 00.0D.E9.08.00.7B)# ERROR: Please get one at http://shop.ntop.org/.########################################################################## We're now working in demo mode with packet capture and# transmission limited to 5 minutes #########################################################################

Regards,
Gautam

**Comment by cardigliano** [comment]
@gautamch13 please note that Napatech requires a ZC license, please see on shop.ntop.org the "PF_RING ZC license (per adapter) for .. Napatech" item
