### ISSUE TITLE
i40e 2.13.10 unstable under high network load

### ISSUE THREAD

**Issue by jeremyerb** [ntop/PF_RING#774]
Intel pulled the 2.13.10 due to unstable problems under high network load

RedHat reference:
https://access.redhat.com/solutions/6104421

Intel:
https://downloadmirror.intel.com/30190/eng/635390-TA-256.pdf

We are currently experiencing this problem with the PF_RING i40e 2.13.10 driver.

**Comment by cardigliano** [comment]
Thank you @jeremyerb , we will port ZC to the latest i40e asap

**Comment by cardigliano** [comment]
New driver i40e-zc v. 2.17.4 available (20333f7e4bc12a095367ae1eca88c29f46ed92b2 565ddbe45040e96f7e4d072e6ba4a36e0517def6)
