### ISSUE TITLE
ZeroCopy Drivers will not install on RedHat 8.5

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#775]
OS: Red Hat Enterprise Linux release 8.5 (Ootpa)
Kernel: 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

System has the most up2date RHEL patches.

NTOP Versions Installed (from: https://packages.ntop.org/ Nightly Build Repository)

pfring-drivers-zc-dkms-8.1.0-7117.noarch
pfring-dkms-8.1.0.7117-7117.noarch
n2disk-3.7.211204-5344.x86_64
pfring-drivers-zc-dkms-8.1.0-7117.noarch
ixgbevf-zc-4.5.1.7117-dkms.noarch
i40e-zc-2.13.10.7117-dkms.noarch
igb-zc-5.3.5.18.7117-dkms.noarch
ixgbe-zc-5.5.3.7117-dkms.noarch
e1000e-zc-3.8.7.7117-dkms.noarch

All the ZC drivers have failed to compile/install.

I’ve included the dnf command output and all the make.log files from the drivers.

Thanks for your help.

[dnf-zc-output-06DEC2021.txt](https://github.com/ntop/PF_RING/files/7669114/dnf-zc-output-06DEC2021.txt)
[e1000e-zc.log](https://github.com/ntop/PF_RING/files/7669117/e1000e-zc.log)
[i40e-zc.log](https://github.com/ntop/PF_RING/files/7669118/i40e-zc.log)
[igb-zc.log](https://github.com/ntop/PF_RING/files/7669120/igb-zc.log)
[ixgbevf-zc.log](https://github.com/ntop/PF_RING/files/7669121/ixgbevf-zc.log)
[ixgbe-zc.log](https://github.com/ntop/PF_RING/files/7669122/ixgbe-zc.log)

**Comment by cardigliano** [comment]
A driver update is now available with compilation fixes for latest RH 8.5 kernels

**Comment by Arislen** [comment]
Thanks for the quick response.

Installed the latest ZC divers with no issues.
