### ISSUE TITLE
Compile error + lib module:4.18.0-193.28.1.el7.aarch64 + CentOS Linux release 7.9.2009

### ISSUE THREAD

**Issue by MrzMrzMr** [ntop/PF_RING#777]
[root@localhost PF_RING-8.0.0-stable]# uname -a
Linux localhost.localdomain 4.18.0-193.28.1.el7.aarch64 #1 SMP Wed Oct 21 16:25:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
[root@localhost PF_RING-8.0.0-stable]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (AltArch)
[root@localhost PF_RING-8.0.0-stable]# 

[root@localhost PF_RING-8.0.0-stable]# pwd
/root/xxxxx/PF_RING-8.0.0-stable
[root@localhost PF_RING-8.0.0-stable]# make
cd kernel; make
make[1]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/kernel'
make -C /lib/modules/4.18.0-193.28.1.el7.aarch64/build M=/root/xxxxx/PF_RING-8.0.0-stable/kernel EXTRA_CFLAGS='-I/root/xxxxx/PF_RING-8.0.0-stable/kernel  -fno-pie -Wno-implicit-fallthrough' modules
make[2]: Entering directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
make[1]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/kernel'
cd userland; ./configure; make
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking linux/net_tstamp.h usability... yes
checking linux/net_tstamp.h presence... yes
checking for linux/net_tstamp.h... yes
checking librdi.h usability... no
checking librdi.h presence... no
checking for librdi.h... no
Assembler messages:
Error: unknown architecture `native'

Error: unrecognized option -march=native
checking for clock_gettime in -lrt... yes
checking for nl_handle_alloc in -lnl... no
checking for dlopen, dlsym in -ldl... yes
checking for nl_socket_alloc in -lnl-3... no
checking PF_RING AF_XDP support... no
configure: creating ./config.status
config.status: creating lib/Makefile
config.status: creating lib/pfring_config
config.status: creating examples/Makefile
config.status: creating examples_zc/Makefile
config.status: creating examples_ft/Makefile
config.status: creating c++/Makefile
config.status: creating nbpf/Makefile
config.status: creating wireshark/extcap/Makefile
config.status: creating lib/config.h
config.status: lib/config.h is unchanged
make[1]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland'
cd lib; make
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/lib'
ar x ../nbpf/libnbpf.a
cp ../nbpf/nbpf.h .
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring.c -o pfring.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_mod.c -o pfring_mod.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_utils.c -o pfring_utils.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_mod_stack.c -o pfring_mod_stack.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_hw_filtering.c -o pfring_hw_filtering.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_hw_timestamp.c -o pfring_hw_timestamp.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_mod_sysdig.c -o pfring_mod_sysdig.o
gcc -O2  -Wall -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP     -c pfring_mod_pcap.c -o pfring_mod_pcap.o
=*= making library libpfring.a =*=
ar rs libpfring.a pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o pfring_mod_pcap.o            `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '`
ranlib libpfring.a
=*= making library libpfring.so =*=
gcc -Wl,-soname,libpfring.so.8 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o pfring_mod_pcap.o            `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl     -o libpfring.so.8.0.0
=*= making library libpfring_min.so =*=
gcc -Wl,-soname,libpfring_min.so.8 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o pfring_mod_pcap.o           `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl     -o libpfring_min.so.8.0.0
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/lib'
cd libpcap; make
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/libpcap-1.9.1'
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
gcc -std=gnu99  -shared -Wl,-soname,libpcap.so.$MAJOR_VER \
    -o libpcap.so.$VER pcap-linux.o pcap-usb-linux.o pcap-netfilter-linux.o fad-getad.o pcap.o gencode.o optimize.o nametoaddr.o etherent.o fmtutils.o savefile.o sf-pcap.o sf-pcapng.o pcap-common.o bpf_image.o bpf_filter.o bpf_dump.o  scanner.o grammar.o strlcat.o strlcpy.o  ../lib/libpfring.a -lpthread  -lrt -ldl    -lrt -ldl 
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/libpcap-1.9.1'
cd examples; make
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/examples'
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfcount.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfcount
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfcount_multichannel.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfcount_multichannel
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  preflect.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o preflect
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfflow_offload.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfflow_offload
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfbridge.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfbridge
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  alldevs.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o alldevs
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pcap2nspcap.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pcap2nspcap
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfcount_82599.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfcount_82599
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfsystest.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfsystest
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfsend.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfsend
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pflatency.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pflatency
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pftimeline.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pftimeline
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pcount.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pcount
gcc  -O2  -DHAVE_PF_RING -Wall -Wno-unused-function -Wno-format-truncation -Wno-address-of-packed-member -I../../kernel -I../lib -I../libpcap -Ithird-party `../lib/pfring_config --include` -D ENABLE_BPF    -O2  pfwrite.o ../libpcap/libpcap.a   ../lib/libpfring.a ../libpcap/libpcap.a   ../lib/libpfring.a `../lib/pfring_config --libs` `../libpcap/pcap-config --additional-libs --static` -lpthread  -lrt -ldl  -lrt -o pfwrite
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/examples'
cd examples_zc; make
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/examples_zc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/examples_zc'
cd examples_ft; make
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/examples_ft'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/examples_ft'
cd wireshark/extcap; make
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/wireshark/extcap'
gcc  -O2  -O2 -DHAVE_PF_RING -Wall -I../../../kernel -I../../lib -I../../libpcap -Ithird-party `../../lib/pfring_config --include` -D ENABLE_BPF  -O2  ntopdump.o ../../libpcap/libpcap.a   ../../lib/libpfring.a ../../libpcap/libpcap.a   ../../lib/libpfring.a `../../lib/pfring_config --libs` -lpthread  -lrt -ldl  -lrt -o ntopdump
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland/wireshark/extcap'
make[1]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/userland'
cd drivers; make
make[1]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers'
cd intel; ./configure; make
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Makefile.dkms.e1000e
config.status: creating Makefile.dkms.igb
config.status: creating Makefile.dkms.ixgbe
config.status: creating Makefile.dkms.ixgbevf
config.status: creating Makefile.dkms.i40e
config.status: creating Makefile.dkms.fm10k
config.status: creating Makefile.dkms.ice
config.status: creating dkms.conf.e1000e
config.status: creating dkms.conf.igb
config.status: creating dkms.conf.ixgbe
config.status: creating dkms.conf.ixgbevf
config.status: creating dkms.conf.i40e
config.status: creating dkms.conf.fm10k
config.status: creating dkms.conf.ice
config.status: creating pfring-drivers-zc-dkms/DEBIAN/control
config.status: creating pfring-zc-rpm.spec
make[2]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel'
cd e1000e/e1000e-3.8.7-zc; make
make[3]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc'
cd src; make
make[4]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src'
# PF_RING
cd /root/xxxxx/PF_RING-8.0.0-stable/kernel/; make
make[5]: Entering directory `/root/xxxxx/PF_RING-8.0.0-stable/kernel'
make -C /lib/modules/4.18.0-193.28.1.el7.aarch64/build M=/root/xxxxx/PF_RING-8.0.0-stable/kernel EXTRA_CFLAGS='-I/root/xxxxx/PF_RING-8.0.0-stable/kernel  -fno-pie -Wno-implicit-fallthrough' modules
make[6]: Entering directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
  Building modules, stage 2.
  MODPOST 1 modules
make[6]: Leaving directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
make[5]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/kernel'
cp /root/xxxxx/PF_RING-8.0.0-stable/kernel/Module.symvers .
*** The target kernel has CONFIG_MODULE_SIG_ALL enabled, but
*** the signing key cannot be found. Module signing has been
*** disabled for this build.
**make[5]: Entering directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'**
  CC [M]  /root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/ptp.o
/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/ptp.c:14:21: fatal error: asm/tsc.h: No such file or directory
 #include <asm/tsc.h>
                     ^
compilation terminated.
make[6]: *** [/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/ptp.o] Error 1
make[5]: *** [_module_/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src] Error 2
make[5]: Leaving directory `/usr/src/kernels/4.18.0-193.28.1.el7.aarch64'
make[4]: *** [default] Error 2
make[4]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers/intel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/xxxxx/PF_RING-8.0.0-stable/drivers'
make: *** [all] Error 2
[root@localhost PF_RING-8.0.0-stable]#

**Comment by cardigliano** [comment]
@MrzMrzMr could you check whether 8.1 compiles in your environment?

**Comment by MrzMrzMr** [comment]
@cardigliano Which command should I use to check?

**Comment by cardigliano** [comment]
Same commands, using the latest code (git clone https://github.com/ntop/PF_RING.git)

**Comment by MrzMrzMr** [comment]
Same result

**Comment by MrzMrzMr** [comment]
I wanted to add --DNO_PTP_SUPPORT in \ pf_ring-8.0.0-stable\drivers\ Intel\e1000e-e1000e-3.8.7-zc\SRC\common.mk, but it didn't work


“EXTRA_CFLAGS += -DNO_PTP_SUPPORT”



---------------------------------------------------------------------------------
PF_RING-8.0.0-stable\drivers\intel\e1000e\e1000e-3.8.7-zc\src\Makefile

# customized kernelbuild function
#
# ${1} is the kernel build target
# ${2} may contain extra rules to pass to kernelbuild macro
#
# We customize the kernelbuild target in order to provide our hack to disable
# CONFIG_PTP_1588_CLOCK support should -DNO_PTP_SUPPORT be defined in the extra
# cflags given on the command line.
devkernelbuild = $(call kernelbuild,$(if $(filter -DNO_PTP_SUPPORT,${EXTRA_CFLAGS}),CONFIG_PTP_1588_CLOCK=n) ${2},${1})
---------------------------------------------------------------------

**Comment by MrzMrzMr** [comment]
-------------------------
#ifdef CONFIG_PTP_1588_CLOCK
#include <linux/clocksource.h>
#include <linux/ktime.h>
#include <asm/tsc.h>
#endif
....
-------------------

the CONFIG_PTP_1588_CLOCK works only on x86 platform, not work on ARM platform ,  right?

****

**Comment by cardigliano** [comment]
@MrzMrzMr I didn't realize you are running on arm, please note Intel only is supported by ZC drivers, please skip the drivers compilation

**Comment by MrzMrzMr** [comment]
@cardigliano  The CPU architecture is ARM, right?

[root@localhost PF_RING-8.0.0-stable]# uname -a
Linux localhost.localdomain 4.18.0-193.28.1.el7.aarch64 #1 SMP Wed Oct 21 16:25:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
[root@localhost PF_RING-8.0.0-stable]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (AltArch)

**Comment by MrzMrzMr** [comment]
@cardigliano 
https://elixir.bootlin.com/linux/v4.8/ident/convert_art_to_tsc, 
According to this link,  the tsc. h exists only in arch/x86 directory, no other.

**Comment by cardigliano** [comment]
Yes, as I said please skip the drivers compilation on this architecture

**Comment by MrzMrzMr** [comment]
> ## #ifdef CONFIG_PTP_1588_CLOCK
> #include <linux/clocksource.h>
> #include <linux/ktime.h>
> #include <asm/tsc.h>
> #endif
> ....
> the CONFIG_PTP_1588_CLOCK works only on x86 platform, not work on ARM platform , right?



@cardigliano
