### ISSUE TITLE
Mellanox missing from pf_ringcfg --list-zc-drivers

### ISSUE THREAD

**Issue by TheHinsh** [ntop/PF_RING#779]
Hello, I'm working with a Mellanox ConnectX-6 Dx card and tring to get the PF_RING ZC drivers working. I've followed the config instructions here:
https://www.ntop.org/pf_ring/introducing-pf_ring-zc-support-for-mellanox-adapters/

Installing the Mellanox drivers included in `MLNX_OFED_LINUX-5.5-1.0.3.2-rhel7.9-x86_64.tgz` and updated PF_RING using the latest git hash from the `dev` branch.

``` bash
# cat /proc/net/pf_ring/info
PF_RING Version          : 8.1.0 (dev:8bc8a39cbcfbe529116b19ec55073e2ab600d030)

# lspci | grep Mellanox
17:00.0 Ethernet controller: Mellanox Technologies MT2892 Family [ConnectX-6 Dx]
17:00.1 Ethernet controller: Mellanox Technologies MT2892 Family [ConnectX-6 Dx]
```

However, pf_ringcfg --list-zc-drivers does not list mlx as an option.
```bash
# pf_ringcfg --list-zc-drivers
e1000e
igb
ixgbe
ixgbevf
i40e
fm10k
ice
```

Further, pf_ringcfg --list-interfaces, shows the mlx interface is not supporte by ZC. 
```bash
# pf_ringcfg --list-interfaces
Name: enp51s0f0            Driver: igb        RSS:     8    [Supported by ZC]
Name: enp89s0f0            Driver: ixgbe      RSS:     63   [Supported by ZC]
Name: enp51s0f3            Driver: igb        RSS:     8    [Supported by ZC]
Name: enp89s0f1            Driver: ixgbe      RSS:     63   [Supported by ZC]
Name: enp23s0f1            Driver: mlx5_core  RSS:     63
Name: enp90s0f1            Driver: igb        RSS:     8    [Supported by ZC]
Name: enp51s0f1            Driver: igb        RSS:     8    [Supported by ZC]
Name: enp23s0f0            Driver: mlx5_core  RSS:     1
Name: enp51s0f2            Driver: igb        RSS:     8    [Supported by ZC]
Name: enp90s0f0            Driver: igb        RSS:     8    [Supported by ZC]
```
Any tips or pointers on how to get this going correctly?

**Comment by TheHinsh** [comment]
We are trying t monitor network traffic that fluctuates between 5 gbps and around 30 gbps.  The command  `pfcount -i enp23s0f0` reports up to about 10 gbps (when we are seeing 30 gpbs on the line).  Using `pfcount -i mlx:mlx5_0` we are seeing the full 30 gbps.

However, when we attempt to monitor that traffic using tcpdump or zeek, almost all packets are reported as dropped by each tool when configured to use `mlx:mlx5_0`.

**Comment by cardigliano** [comment]
@TheHinsh I pushed a couple of fixes for pf_ringcfg, it should report more information now (next build). However it seems that the capture is working for you now.
As of the dropped traffic with zeek or tcpdump, that depends on the application itself which adds a lot of overhead leading to packet loss.
