### ISSUE TITLE
pf_ ring usage problem

### ISSUE THREAD

**Issue by dreamhighhd** [ntop/PF_RING#783]
Can you provide a copy of PF_ Ring, combined with nprobe and ntopng, is facing the large traffic network environment.

The problems I now encounter:

1. Since the third-party single-mode module used for 10 Gigabit network card is the network card identified by default, the network card identified by the following methods

```
rmmod ixgbe
modprobe ixgbe allow_ unsupported_ sfp=1,1
```

2. Install PF_ After ring, due to the adjustment of network card driver, it is incompatible with the third-party network card module. It is successfully identified in the following ways

```
rmmod ixgbe_ zc
modprobe ixgbe_ zc allow_ unsupported_ sfp=1,1
```

3、pf_ Ring and ntopng usage problems (it's uncertain whether it's a configuration problem, it can't solve the problem of inaccurate display of my traffic, and ntopng can't automatically create sub interfaces for VLAN)
![image](https://user-images.githubusercontent.com/40293011/152928336-19c9a45a-cacd-4141-95c4-3159f6276bc0.png)

![image](https://user-images.githubusercontent.com/40293011/152928033-09cd9875-4e1a-464e-804f-457734b79c32.png)

**Comment by dreamhighhd** [comment]
The pfcount test seems to work properly
![image](https://user-images.githubusercontent.com/40293011/152931523-e17b5886-e363-4abf-8201-d65806d582e3.png)

`pfcount -i zc:enp2s0f0`

**Comment by dreamhighhd** [comment]
@jnicholls @thus @sfd @TheHippo   The pfcount test seems to work properly

**Comment by dreamhighhd** [comment]
8255 chip network card
![image](https://user-images.githubusercontent.com/40293011/152932295-c90cc549-4315-4650-986f-b4a91240635a.png)

**Comment by dreamhighhd** [comment]
The real traffic of network card image is about 5-6GB, and the traffic may be greater in the later stage

**Comment by dreamhighhd** [comment]
present situation：
Flow comparison on network port:

                                                VLAN123 VLAN234 VLAN345
Real traffic of service switch: 2.8G 1.4G 1.4G

Traffic received by the server: 2.7G 1.4G 1.4G

Ntopng displayed flow: 700M 1G 400M




The ntopng agent reported that it was unable to handle the problem and asked to increase PF_ Ring to see if it can be solved. At this stage, the support is poor, and the problem has not been solved after several months of communication. I hope the manufacturer can solve the problem more closely.

**Comment by dreamhighhd** [comment]
@cardigliano

**Comment by cardigliano** [comment]
@dreamhighhd is this still an open issue? Could you update on the current status?
