### ISSUE TITLE
*** ndpi library version mismatch, expected API rev.5710 (4.2.0) found rev.5716 (4.2.0-3465-258fedbc) ***

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#785]
Latest ndpi from git tree 4.2.0-stable.
Latest PF ring ft from git tree 8.0.0-stable.

There is really something wrong in makefiles and how you track revisions.

@cardigliano

**Comment by vitalivanov** [comment]
any comments?

**Comment by cardigliano** [comment]
I just pushed a FT update on github for 8.0 branch

**Comment by vitalivanov** [comment]
@cardigliano 
it did not help.
Latest versions that i built from github:

nDPI v.4.2.0-3465-258fedbc
PF_RING FT v.8.0.0.220307

The error that I get now is:

*** ndpi library version mismatch, expected API rev.5951 (4.3.0) found rev.5716 (4.2.0-3465-258fedbc) ***

Why does it expect 4.3.0 now as ndpi latest is 4.2???

**Comment by cardigliano** [comment]
@vitalivanov I pushed a new update, please check it

**Comment by vitalivanov** [comment]
@cardigliano it's ok now. thanks.

**Comment by nhatlequang102** [comment]
I am getting the same error for the latest version
