### ISSUE TITLE
pf_ring receives data for a period of time and then the received data becomes 0

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/PF_RING#789]
When using zcount to receive data, the data is accepted normally at the beginning of the period, but after some time the data will become zero
Then if you restart the computer and then turn it on again it will get stuck, enter commands sudo ./zcount -i zc： and then have the following problem：
pfring_zc_create_cluster error [Socket operation on non-socket] Please check that pf_ring.ko is loaded and hugetlb fs is mounted
When viewing the huge the following appears：
Node 0 AnonHugePages:              0KB
Node 0 ShmemHugePages:          0KB
Node 0 FileHugePages:                0KB
Node 0 HugePages_total:          1024
Node 0 HugePages_Free:            871
Node 0 HugePages_Surp:               0
How can I solve this problem?
thanks

**Comment by cardigliano** [comment]
@hdsjahuen a few questions:
- how many packets are you capturing before seeing 0 data?
- what driver and adapter model are you using?
- what CPU are you using?
- are you able to reproduce the same with pfcount?

**Comment by hdsjahuen** [comment]
Captured differently each time
The NIC is an Intel xl710
The cpu is also Intel
The previous version of ubuntu was 19.04 and the pf_ring version was 7.6.
After the update, ubuntu is 20.04 and pf_ring is 7.8

**Comment by hdsjahuen** [comment]
pfcount is not running
pfring_open error [no such device] (pf_ring not loaded or interface RadarNetcardRdar is down?)

**Comment by cardigliano** [comment]
@hdsjahuen 7.8 is no longer supported, please check pf_ring 8.x (8.0 stable or 8.1 dev)
