### ISSUE TITLE
Ubuntu-22.04 support

### ISSUE THREAD

**Issue by jurjenwestra78** [ntop/PF_RING#793]
When will ubuntu-22.04 be supported?

I see here

[https://packages.ntop.org/apt/]()

that packages available for all (recent) ubuntu LTS releases, so I assume there are plans to support 22.04 as well. 

For what it's worth: I tried compiling myself but did not succeed, even after a bit of hacking. I'm assuming this is due to the kernel version. On my box (server, not completely up-to-date):

```
$ uname -r
5.15.0-18-generic
```

We really need `pf_ring`, so support is really appreciated!

**Comment by cardigliano** [comment]
@jurjenwestra78 we are working on that, it will be supported asap!

**Comment by jurjenwestra78** [comment]
Thanks!

**Comment by cardigliano** [comment]
Ubuntu 22 is supported now

**Comment by jurjenwestra78** [comment]
That's good news, we will try it soon.

Thanks!
