### ISSUE TITLE
X722 is supported? i40e driver is failed.

### ISSUE THREAD

**Issue by haroldfeng** [ntop/PF_RING#794]
Card type: Intel Corporation Ethernet Connection X722 for 10GbE SFP+

[root@localhost src]# ./load_driver.sh
insmod: ERROR: colud not insert module ./i40e.ko: Invalid parameters
Warning: 512 huge pages available, 1024 requested

**Comment by cardigliano** [comment]
@FengShaoCong X722 should work with the i40e driver, we did not that that exact chipset version as we do nto have it in our lab, however there are users using it. The issue you are experiencing does not seem to be related to the chipset, it's a driver issue. What OS and kernel are you running?

**Comment by haroldfeng** [comment]
> el

The OS is CentOS Linux release 7.9.2009 (Core).
The kernel is 3.10.0-1160.el7.x86_64.

**Comment by cardigliano** [comment]
What pf_ring version are you running?

**Comment by haroldfeng** [comment]
[root@localhost ~]# modinfo pf_ring
filename:       /lib/modules/3.10.0-1160.el7.x86_64/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
version:        8.1.0
description:    Packet capture acceleration and analysis
author:         ntop.org

**Comment by haroldfeng** [comment]
@[cardigliano](https://github.com/cardigliano)
Excuse me. When I make i40e kernel, it shows that:

The target kernel has CONFIG_MODULE_SIG_ALL enabled , but the signing key cannot be found. Module signing has been disable for this build.

**Comment by cardigliano** [comment]
Could you provide the last part of the dmesg output when trying to load the driver, to check what is triggering the "Invalid parameters" error?
Also, please make sure you are not running the kernel in secure boot mode, which allows signed modules only to be loaded.

**Comment by haroldfeng** [comment]
@cardigliano Thank you very much. I havs disabled secure boot, and the error have sloved.

[  791.895807] pf_ring: loading out-of-tree module taints kernel.
[  791.897315] pf_ring: module verification failed: signature and/or required key missing - tainting kernel

**But it still have the error. The dmesg  is as flows:**

[ 2750.775034] NET: Unregistered protocol family 27
[ 2750.775041] [PF_RING] Module unloaded
[ 2750.784772] [PF_RING] Welcome to PF_RING 8.1.0 ($Revision: dev:99a5af412d88f8f88eb39fb0a959ecea204b8dc1$)
(C) 2004-22 ntop.org
[ 2750.784781] LINUX_VERSION_CODE 00030A00
[ 2750.784784] [PF_RING] Min # ring slots 4096
[ 2750.784787] [PF_RING] Slot version     20
[ 2750.784790] [PF_RING] Capture TX       Yes [RX+TX]
[ 2750.784792] [PF_RING] IP Defragment    No
[ 2750.784809] NET: Registered protocol family 27
[ 2750.785174] [PF_RING] pf_ring initialized correctly
[ 2751.372359] i40e: disagrees about version of symbol pci_disable_pcie_error_reporting
[ 2751.372367] i40e: Unknown symbol pci_disable_pcie_error_reporting (err -22)
[ 2751.372579] i40e: disagrees about version of symbol pci_cleanup_aer_uncorrect_error_status
[ 2751.372584] i40e: Unknown symbol pci_cleanup_aer_uncorrect_error_status (err -22)
[ 2751.372885] i40e: disagrees about version of symbol pci_enable_pcie_error_reporting
[ 2751.372890] i40e: Unknown symbol pci_enable_pcie_error_reporting (err -22)
[ 2752.680630] load_driver.sh (10066): drop_caches: 3

**Comment by cardigliano** [comment]
@FengShaoCong I see there is a version mismatch for some symbols, could you try reinstalling the driver to force a recompilation? Please try removing the driver, checking the dkms tool to make sure it is not installed, and reinstalling the driver.

**Comment by haroldfeng** [comment]
I truly appreciate your help. I have solved the error, which is inconsistent version about  `/usr/src/kernels/` and `/lib/modules/`.
