### ISSUE TITLE
ice-zc compilation error on kernel 5.13.0

### ISSUE THREAD

**Issue by mcgillowen** [ntop/PF_RING#796]
Unable to install PF_RING ZC ice-zc-1.3.2.7366 on Ubuntu 20.04.1 with kernel 5.13.0-28-generic with the following compilation error.

```
/var/lib/dkms/ice-zc/1.3.2.7366/build/kcompat.h:297:46: errror: 'cpu_online_map' undeclared (first use in this function); did you mean 'cpu_online_mask'?
| #define cpu_online(cpuid) test_bit((cpu_id), &cpu_online_map)
```

**Comment by cardigliano** [comment]
I pushed a driver update to support latest kernels, please check the next package update
