### ISSUE TITLE
Hardware conditions for using pf_ring zc

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/PF_RING#797]
whether CPU hardware is required to support DMA and Cache consistency.

And
Can pf_ring zc run on ARM64 hardware platforms？
Are there any relevant success stories?
thanks

**Comment by cardigliano** [comment]
@hdsjahuen ZC drivers are supported on Intel CPUs (AMD is also working, we do not support it officially as we do not have AMD hw but there are users using it)
