### ISSUE TITLE
Does pfring_zc_builtin_ip_hash support ipv6?

### ISSUE THREAD

**Issue by liuchuang** [ntop/PF_RING#798]
I use `pfring_zc_builtin_ip_hash` for fanout packet,
I tested in release 7.4 that it does not support ipv6, it only hashes according to the first 4 bytes of the ip field of the ip header. Are there other functions that support ipv6? thanks.

**Comment by cardigliano** [comment]
@liuchuang pfring_zc_builtin_ip_hash should actually provide an hash computed on all 16 bytes of the IP field in case of IPv6
