### ISSUE TITLE
checking PF_RING AF_XDP support... no

### ISSUE THREAD

**Issue by HackedBaked** [ntop/PF_RING#799]
System
- Ubuntu 20.04
- Kernel: 5.11.0-49-generic
- CPU intel x710
- nic driver i40e 
- libelf-dev already installed
- Using latest code from the github, since this post was made.
- My kernel has `CONFIG_XDP_SOCKETS=y` configured

Trying to compile PF_RING with AF_XDP, but running `./configure` keeps showing 

```
checking PF_RING AF_XDP support... no
```

For the heck of it I tried running pfcount with xdp syntax `sudo ./pfcount -i xdp:eth0@0`, but this did not work.
I read through instructions here: https://www.ntop.org/guides/pf_ring/modules/af_xdp.html, clearly states that it should be enabled by default. 

I made sure all Prerequisites were in place, however its not clear how I can check `libbpf with latest AF_XDP support installed from <kernel source>/tools/lib/bpf`, so not sure if this is met. Here is a grep on my libbpf header file

```
# cat /usr/include/bpf/libbpf.h | grep -i xdp
bpf_program__attach_xdp(struct bpf_program *prog, int ifindex);
LIBBPF_API int bpf_program__set_xdp(struct bpf_program *prog);
LIBBPF_API bool bpf_program__is_xdp(const struct bpf_program *prog);
struct xdp_link_info {
struct bpf_xdp_set_link_opts {
#define bpf_xdp_set_link_opts__last_field old_fd
LIBBPF_API int bpf_set_link_xdp_fd(int ifindex, int fd, __u32 flags);
LIBBPF_API int bpf_set_link_xdp_fd_opts(int ifindex, int fd, __u32 flags,
                                        const struct bpf_xdp_set_link_opts *opts);
LIBBPF_API int bpf_get_link_xdp_id(int ifindex, __u32 *prog_id, __u32 flags);
LIBBPF_API int bpf_get_link_xdp_info(int ifindex, struct xdp_link_info *info,
```

Why does pf_ring configure refuses to enable af_xdp? 

EDIT:

Getting closer, looks like just because I have bpf headers loaded in my kernel, `configure` is looking for these files specifically found in line 4027

`if test -f /usr/local/include/bpf/xsk.h && test -f /usr/src/linux-headers-$BUILD_KERNEL/include/uapi/linux/if_xdp.h; then`

**Comment by HackedBaked** [comment]
I figured it out. the problem was xsk.h and if_xdp.h were not in the paths that configure was looking for. I was hesitant to integrate and update libbpf as other developers use these modules for xdp research on our host. Once I compiled the linux library bpf tools and installed the correct headers, it worked.

**Comment by cardigliano** [comment]
@HackedBaked what was the default path in your system?

**Comment by mzpqnxow** [comment]
Is there a reason this has to check /usr/local as opposed to using the same directory as the `if_xdp.h` header? I ran into this recently and fixed the two issues- would be nice if they were both in a single place
