### ISSUE TITLE
ftflow -7 will not work

### ISSUE THREAD

**Issue by HackedBaked** [ntop/PF_RING#800]
trying to run the following:

```
./ftflow -i xdp:eth0@0 -7
```

This results in the following error:

```
$ sudo ./ftflow -i xdp:eth0@0 -7
#########################################################################
# ERROR: You do not seem to have a valid PF_RING FT 8.1.0.220331 license [L560B1792F208AA8F--U560B1792A7930D83--OL]
# ERROR: Please get one at http://shop.ntop.org/.
#########################################################################
# PF_RING FT running in demo mode (flow processing limited to 5 minutes)
#########################################################################
*** ndpi_detection_get_sizeof_ndpi_id_struct not found, please install latest ndpi library ***
*** /usr/lib/libndpi.so.4.3.0 not found or missing symbols ***
pfring_ft_create_table error
```

What I have tried:
- I have tried compiling and installing nDPI from latest source.
    - I tried following the nDPI `README.md`, `README.nDPI` and `INSTALL` instructions
    - `./configure` `./make` and `./make install` ran without errors.
- Confirmed that /usr/lib/libndpi.so.4.3.0 exists.
- ftflow works fine without -7
- Tried running as sudo. No luck.

Questions:
- re: "ndpi_detection_get_sizeof_ndpi_id_struct not found, please install latest ndpi library", this is not clear, ndpi is installed, why does this error appear?
- re: "/usr/lib/libndpi.so.4.3.0 not found or missing symbols", like I said, this file exists from latest build. Looking for clarification on how to troubleshoot this error.

Can someone help?

**Comment by cardigliano** [comment]
Please check latest PF_RING code/lib from github

**Comment by HackedBaked** [comment]
Sorry for the delay in response, finally got back around to testing this. 
I did a pull on the latest dev branch, and installed again. 
This worked, -7 no longer gives me errors. Thanks!
