### ISSUE TITLE
X710 with i40e 2.17.4 drop packets under high network load

### ISSUE THREAD

**Issue by guoyc1** [ntop/PF_RING#801]
I use Intel X710 with i40e-2.17.4-zc driver on kernel 5.10.0, but when the transmission speed is high, packets drop sometimes.
However, when I use Intel 82599ES with ixgbe-5.5.3-zc driver, packets will not drop.
Is it somehow related to RSS? I enable RSS both of them, and it works successfully with i40e-2.17.4-zc when the transmission speed is not high.

**Comment by cardigliano** [comment]
i40e adapters have small packet buffers with respect to ixgbe (4K vs 32K packets), that could explain the packet loss depending on packet rate and the application..

**Comment by guoyc1** [comment]
Thank you for replying.
I tried to modify `i40e.h` and `load_driver.sh` to get a bigger buffer, but it looked useless. 
what else can I do?

**Comment by cardigliano** [comment]
The buffer is set already to the max supported by the adapter. You need to play with RSS and application tuning. What application are you running?

**Comment by guoyc1** [comment]
Thank you for your answer.
I'm running my own application, which uses `pfring_enable_rss_rehash` to enable RSS and uses `pfring_recv` to receive packets.
Today I tried to modify my RSS rules. Sometimes I can Improve its performance, depending on the rules of hardware filters and the parameters of application of sending packets.
Then I found that when I added rules about dst_port, they didn't take effect, which worked at ixgbe device. However, the rules about dst_ip can work at i40e device.
Is all i40e adapters have small buffers? If yes, I should attempt to modify RSS and my application to get the best performance.

**Comment by cardigliano** [comment]
Please note that rss rehashing does not affect ZC mode. You should configure RSS queues when loading the driver, and open zc:eth1@0, zc:eth1@1, and so on using multiple threads/processes. 
And yes, all i40e adapters have the same max buffer size. Hardware filters are not supported. 
I recommend Mellanox adapters if you need hw filters intensively.
