### ISSUE TITLE
 ice-zc-1.3.2.7393 compilation error on CentOS 8 (4.18.0-383)

### ISSUE THREAD

**Issue by deeonis-ru** [ntop/PF_RING#803]
There is a compilation error during installation ice-zc driver from the nightly builds repo.

`In file included from ./include/net/udp.h:34,
                 from ./include/net/udp_tunnel.h:6,
                 from /var/lib/dkms/ice-zc/1.3.2.7393/build/ice.h:96,
                 from /var/lib/dkms/ice-zc/1.3.2.7393/build/ice_main.c:8:
./include/linux/indirect_call_wrapper.h:27: warning: "INDIRECT_CALLABLE_DECLARE" redefined
 #define INDIRECT_CALLABLE_DECLARE(f) f

In file included from /var/lib/dkms/ice-zc/1.3.2.7393/build/ice.h:7,
                 from /var/lib/dkms/ice-zc/1.3.2.7393/build/ice_main.c:8:
/var/lib/dkms/ice-zc/1.3.2.7393/build/kcompat.h:3116: note: this is the location of the previous definition
 #define INDIRECT_CALLABLE_DECLARE(x) x
`
Full make.log is in attachment
[make.log](https://github.com/ntop/PF_RING/files/8554285/make.log)

**Comment by cardigliano** [comment]
@deeonis-ru I pushed a new ice driver version, please check it
