### ISSUE TITLE
pfring_open error [Address family not supported by protocol]

### ISSUE THREAD

**Issue by z-zayn** [ntop/PF_RING#806]
A few days ago, I used pfring_open() to work normally, but today I found that the program could not run, and the following error was reported using pf_count, what happened?

pfring_open error [Address family not supported by protocol] (pf_ring not loaded or interface wlo1 is down ?)

**Comment by cardigliano** [comment]
Please provide "cat /proc/net/pf_ring/info"

**Comment by z-zayn** [comment]
> Please provide "cat /proc/net/pf_ring/info"

No output at all，
I find My kernel was updated yesterday and I'm having version Magic problems, what can I do with this problem？

**Comment by cardigliano** [comment]
@z-zayn what kernel are you running? (uname -a)
can I see this "magic" error?

**Comment by z-zayn** [comment]
@cardigliano 
I use dmesg and it outputs:
pf_ring: version magic '5.15.32-1-rt39-MANJARO SMP preempt_rt mod_unload ' should be '5.15.36-1-rt41-MANJARO SMP preempt_rt mod_unload '

**Comment by cardigliano** [comment]
@z-zayn it seems the pf_ring.ko module has not been recompiled for the current kernel, I suggest trying restarting the service with systemctl restart pf_ring (this should force a recompilation) or use the dkms tool manually or reinstall the package as last resort.

**Comment by z-zayn** [comment]
@cardigliano 
I try to use systemctl restart pf_ring in console and it outputs:
Failed to restart pf_ring.service: Unit pf_ring.service not found.

And at first, I try to reinstall the PF_RING,but when I followed the "Installing from GIT" again,I can't insmod ./pf_ring.ko :insmod: ERROR: could not insert module pf_ring.ko: Invalid module format

Then, I found this problem:pf_ring: version magic '5.15.32-1-rt39-MANJARO SMP preempt_rt mod_unload ' should be '5.15.36-1-rt41-MANJARO SMP preempt_rt mod_unload '

**Comment by cardigliano** [comment]
Do you get compilation errors while compiling from git?

**Comment by z-zayn** [comment]
@cardigliano 
I reinstall the PF_RING ,but after that my pcap_next_ex() is not work correctly.Seems Libpcap has some problems, I reinstall PF_RING again but "pcap_next_ex()"'s problem  still:
when I use the Pcap_next_ex(),it can't go into the loop, but when i close my program in clion, the results come out in clion's consle, I have no idea about what happened.
So I reinstall libpcap, it works. But I want to use libpcap+PF_RING,so I follow the "cd PF_RING/userland/lib
./configure && make
sudo make install
cd ../libpcap
./configure && make
sudo make install"
when i finished, my Libpcap can't work correctly again.

**Comment by z-zayn** [comment]
I solve this question by reinstall from git. And libpcap issue is my program's fault and i fixed it
