### ISSUE TITLE
PF_RING compilation error on kernel 5.17.0

### ISSUE THREAD

**Issue by BasedUser** [ntop/PF_RING#807]
Hello. I get an error trying to compile PF_RING's kernel module, it seems to error on this one line using a definition for kernels <3.10. I can't really provide any more specifics to this...

[stdout+stderr](https://github.com/ntop/PF_RING/files/8741657/stdout.txt)

**Comment by xgerligand** [comment]
Hello.
It seems with Linux kernel >= 5.17.0 , function PDE_DATA(). is replaced by pde_data().
So I added these lines in PF_RING/kernel/pf_ring.c
   140 #if(LINUX_VERSION_CODE >= KERNEL_VERSION(5,17,0))
   141 #define PDE_DATA(a) pde_data(a)
   142 #endif
and now compilation is ok for my 5.17.9-vanilla kernel.
May be it exists a best solution...

**Comment by cardigliano** [comment]
What linux distribution/version are you running?

**Comment by cardigliano** [comment]
I pushed a path in 4e4480b88fe345e26951fa3ce4860f479685b91c (thank you @xgerligand)

**Comment by xgerligand** [comment]
Hello.
This is the last funtoo distribution Release 1.4 (funtoo.org).

**Comment by BasedUser** [comment]
I am running debian testing for this build.

> So I added these lines in PF_RING/kernel/pf_ring.c

This fixes the issue! Thanks
