### ISSUE TITLE
AMD servers crashing after some time while using pfring

### ISSUE THREAD

**Issue by vehere-ccu1** [ntop/PF_RING#808]
Hi,
I am using AMD Dell server and following the instruction for AMD processors, but still it is crashing after some time. I am using zbalance_ipc tool with zcount. It runs for sometime then it crashes.

I am using PF version 8.0.0 as well as I also tried in 8.1.0. When server starts, it showing pci error but same server is working properly with iperf tool.

![1](https://user-images.githubusercontent.com/33222750/169676852-02dc4672-27e7-4b0e-9479-ce8e82221aa5.PNG)

![1](https://user-images.githubusercontent.com/33222750/169676795-f2618af8-20f3-4e71-901e-b56384435ef8.PNG)

**Comment by vehere-ccu1** [comment]
iperf tool without pfring modules is working fine, if I run iperf with pfring modules then also it is crashing after some time.

**Comment by cardigliano** [comment]
@vehere-ccu1 are you running ZC drivers? Which model?

**Comment by vehere-ccu1** [comment]
PFRING-8.0.0
i40e 2.13.10-zc Using x710 card

**Comment by vehere-ccu1** [comment]
yes

**Comment by vehere-ccu1** [comment]
Even with 2.17.4 i40e facing page error: -
<img width="528" alt="HTest" src="https://user-images.githubusercontent.com/33222750/170811758-ae7b14cd-844b-4490-afac-256a52be74fe.PNG">

**Comment by vehere-ccu1** [comment]
Same thing happening on Intel based server also but the frequency is very less means 1 time/month, but with AMD server it is so frequent.
<img width="382" alt="Info-PF" src="https://user-images.githubusercontent.com/33222750/170811868-9b731a6c-46ef-438f-9bc4-07b3c2dd9eb3.PNG">

**Comment by cardigliano** [comment]
@vehere-ccu1 I did some code analysis, and I need to know when this happens: does this happen when closing the application/socket perhaps?

**Comment by vehere-ccu1** [comment]
No it is happening anytime after Ioading the pf modules & driver even if I am not running the zc applications on it, and I want to confirm you that this is happening with the i40e_2.13.10-zc driver, I am running the test with i40e_2.17.4 from last 72 hrs and the server is running well. The above crash log was for 2.13.10 version. Have you find such thing with i40e-2.13.10? Is it the issue with Intel release?

**Comment by vehere-ccu1** [comment]
But for Intel-Dell-server same driver (2.13.10) is working fine from last 15 days.

**Comment by cardigliano** [comment]
Weird. It should not happen while running the application. Please let me know if you can reproduce it with 2.17

**Comment by vehere-ccu1** [comment]
No, with 2.17 system is running well since last Friday.

**Comment by vehere-ccu1** [comment]
I have not tested 2.17 before that.
