### ISSUE TITLE
Compile errors after removed e1000e driver sources

### ISSUE THREAD

**Issue by gianogli** [ntop/PF_RING#811]
Hi,
I can't compile anymore all the sources running "make all" command after you removed the e1000e driver sources from the pf_ring with this commit: https://github.com/ntop/PF_RING/commit/292ea26c4189b02381eb604ac813c6732fc02f36

I think you have to re-add the e1000e driver sources or you have to modify the Makefile files... :-)

Could you verify?

Thanks...

**Comment by cardigliano** [comment]
@gianogli it seems it got lost when backporting patches for supporting latest kernels, I pushed it back. Thank you.
