### ISSUE TITLE
ZeroCopy Driver will not install on RedHat 8.6

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#812]
OS: Red Hat Enterprise Linux release 8.6 (Ootpa)
Kernel: 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

System has the most up2date RHEL patches.

NTOP Versions Installed (from: https://packages.ntop.org/ Nightly Build Repository)

pfring-8.1.0-7513.x86_64
pfring-dkms-8.1.0.7513-7513.noarch
n2disk-3.7.220601-5368.x86_64
e1000e-zc-3.8.7.7513-dkms.noarch

The e1000e-zc driver failed to compile. 

(Note: We also installed these drivers without issue)
ixgbe-zc-5.5.3.7513-dkms.noarch
i40e-zc-2.17.4.7513-dkms.noarch

Output from "dnf install" command:

```
  Installing       : e1000e-zc-3.8.7.7513-dkms.noarch                                                                                                                                      3/3
  Running scriptlet: e1000e-zc-3.8.7.7513-dkms.noarch                                                                                                                                      3/3
Loading new e1000e-zc-3.8.7.7513 DKMS files...
Building for 4.18.0-372.9.1.el8.x86_64
Building initial module for 4.18.0-372.9.1.el8.x86_64
Error! Bad return status for module build on kernel: 4.18.0-372.9.1.el8.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.8.7.7513/build/make.log for more information.
warning: %post(e1000e-zc-3.8.7.7513-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc
  Verifying        : e1000e-zc-3.8.7.7513-dkms.noarch                                                                                                                                      1/3
  Verifying        : i40e-zc-2.17.4.7513-dkms.noarch                                                                                                                                       2/3
  Verifying        : ixgbe-zc-5.5.3.7513-dkms.noarch                                                                                                                                       3/3
Installed products updated.

Installed:
  e1000e-zc-3.8.7.7513-dkms.noarch                                i40e-zc-2.17.4.7513-dkms.noarch                                ixgbe-zc-5.5.3.7513-dkms.noarch

Complete!
```

I’ve included the make.log file from the driver compile.

Thanks for your help.

[make.log](https://github.com/ntop/PF_RING/files/8831620/make.log)

**Comment by cardigliano** [comment]
Are you still able to reproduce this with latest drivers from pfring 8.3?

**Comment by Arislen** [comment]
Correct. Tested again with:

pfring-8.3.0-7646.x86_64
pfring-dkms-8.3.0.7646-7646.noarch
n2disk-3.7.220714-5373.x86_64
e1000e-zc-3.8.7.7646-dkms.noarch

This e1000-zc driver still fails with the same error.
