### ISSUE TITLE
Packet capture stops on Intel e810

### ISSUE THREAD

**Issue by TIE1996** [ntop/PF_RING#814]
### Problem description

When running pfcount in ZC mode it reports a huge number of dropped packages.
-> Received package count is exactly as high as the Number of RX Slots

`Absolute Stats: [51'447 pkts total][47'351 pkts dropped][92.0% dropped]`
`[4'096 pkts rcvd][344'064 bytes rcvd][682.58 pkt/sec][0.46 Mbit/sec]`
`Actual Stats: [0 pkts rcvd][1'000.13 ms][0.00 pps][0.00 Gbps]`

Output from cat /proc/net/pf_ring/dev/ens2f0/info:
Name:         ens2f0
Index:        40
Address:      <MAC_ADDR>
Polling Mode: NAPI/ZC
Promisc:      Disabled
Type:         Ethernet
Family:       Intel ice
TX Queues:    1
RX Queues:    1
Num RX Slots: 4096
Num TX Slots: 4096
RX Slot Size: 1536
TX Slot Size: 1536

### System Info
Network Card: Intel e810-xxvda4
Network Card Driver: ice
OS: RHEL 8.4
Kernel: 4.18.0
CPU: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
PF_Ring Version: 8.0.0

Any tips which could lead to this behaviour? To me it seems like the RX Buffer does not get emptied.

**Comment by cardigliano** [comment]
@TIE1996 it seems the library stops capturing after the first round when dequeuing from the receive queue as you noticed, I will do some internal check, are you able to provide ssh access to the box if required perhaps? Are you able to run a test also with the latest dev (8.1) in the meantime?

**Comment by TIE1996** [comment]
@cardigliano thank you for your fast reply.
Theoretically I could provide you with SSH access to the box, however this would require quite a bit of work, I would be happy if its not necessary. 
I just tried it with the latest dev and the result is exactly the same as in the original problem description.

**Comment by TIE1996** [comment]
Hi @cardigliano , how is your analysis going? 
Please let me know if you need SSH access to the machine, in that case I would set up our Server for you.

**Comment by cardigliano** [comment]
@TIE1996 that would speed up this debugging (send a direct email to cardigliano at ntop.org in case)

**Comment by Tms2207** [comment]
@cardigliano just sent you SSH access details.

**Comment by cardigliano** [comment]
Fixed (main fix 57710ab88f7ca7af13c0d49e3ddeaab46de7ee66)
