### ISSUE TITLE
Integration with suricata fails

### ISSUE THREAD

**Issue by cybersecurity99** [ntop/PF_RING#815]
Hi

I am trying
cento-ids -i enp0s3 --v9 127.0.0.1:1234 --balanced-egress-queues 1

suricata --pfring-int=zc:10@0 -c /etc/suricata/suricata.yaml --runmode=workers
This command runs but getting warning no such device (zc:10@0)
but when suricata stops it show stats like pkts : xyz for zc:10@0

Also when I am using
ntopng -i tcp://127.0.0.1:1234c

I am not getting any traffic on this interface ://127.0.0.1:1234 on ntopng website gui

What I am missing here , unable to find 
Asked this many times in community support no response

Thanks.

**Comment by cardigliano** [comment]
@cybersecurity99 please note that you should send flows using ZMQ to ntopng, in your command line you configured cento to send Netflow V9. Please read https://www.ntop.org/guides/cento/usecases.html#integration-with-ntopng

**Comment by cybersecurity99** [comment]
> @cybersecurity99 please note that you should send flows using ZMQ to ntopng, in your command line you configured cento to send Netflow V9. Please read https://www.ntop.org/guides/cento/usecases.html#integration-with-ntopng

@cardigliano Hi
I changed my command to this
cento-ids -i enp0s3 --zmq tcp://127.0.0.1:1234 --balanced-egress-queues 1

Still no traffic in ntopng ( ntopng -i tcp://*:1234c)

**Comment by cardigliano** [comment]
Please provide a screenshot of the Interface page (with stats) in ntopng

**Comment by cybersecurity99** [comment]
> Please provide a screenshot of the Interface page (with stats) in ntopng

![ntop1](https://user-images.githubusercontent.com/101694567/172801423-e6d3aa0b-9166-4154-a9b8-3676bf323d1a.png)

**Comment by cardigliano** [comment]
Please go to the Interface page from the left sidebar

**Comment by cybersecurity99** [comment]
![ntop3](https://user-images.githubusercontent.com/101694567/172815504-c4252fe8-f2c9-40d9-9386-8e15e9375d78.png)
![ntop4](https://user-images.githubusercontent.com/101694567/172815537-4eda00c9-8886-4bfa-9ddd-565ec8147dc1.jpg)

**Comment by cardigliano** [comment]
Please provide:
cento --version
ntopng --version

**Comment by cybersecurity99** [comment]
> Please provide: cento --version ntopng --version

root@ashok-VirtualBox:/home/ashok# ntopng --version
Version:	5.3.220608 [Enterprise/Professional build]
GIT rev:	dev:c5823a24961d4cf899eeffc5bb1bd779d315f1bc:20220608
Pro rev:	r5084
Built on:	Ubuntu 20.04.4 LTS
System Id:	L399F37350D0706F9--U399F3735DE4F8A77--OL
Platform:	x86_64
Edition:	Enterprise L (Bundle)
License Type:	Time-Limited [Empty license file]
Validity:	Until Thu Jun  9 15:34:13 2022
root@ashok-VirtualBox:/home/ashok# cento --version
v.1.17.220608
Built OS:      Ubuntu 20.04.4 LTS
System Id:     L399F37350D0706F9--U399F3735DE4F8A77--OL
GIT rev:       dev:8d19ce1f340cdf80ba72ac8e46637f39281ae571:20220608
License:       Invalid license

**Comment by cardigliano** [comment]
@cybersecurity99 the same commands are working for me, please note that you should wait a couple of minutes to get the flow in ntopng according to the cento configuration, you can control this with:

[--lifetime-timeout|-t] <sec>           | Set maximum flow duration (sec). Default: 120
[--idle-timeout|-d] <sec>               | Set maximum flow idleness (sec). Default: 60
