### ISSUE TITLE
pf_ringcfg --configure-driver not applying ZC driver

### ISSUE THREAD

**Issue by stanley111111** [ntop/PF_RING#818]
Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

root@ubuntu:~# cat /proc/net/pf_ring/dev/enp6s0f0/info
```
Name:         enp6s0f0
Index:        4
Address:      00:1B:21:BC:76:96
Polling Mode: NAPI
Promisc:      Disabled
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    40
RX Queues:    40
```

root@ubuntu:~# lsmod | grep ring
`pf_ring               196608  0`

root@ubuntu:~# pf_ringcfg --configure-driver ixgbe --rss-queues 1

```
[>] Configuring PF_RING
[>] Configuring hugepages
[>] Detecting interfaces using ixgbe
enp6s0f1
enp6s0f0
[>] Configuring ixgbe driver with 1 RSS queues
[>] Restarting PF_RING
[>] Configuration completed
```

root@ubuntu:~#  sudo pf_ringcfg --list-interfaces
```
Name: enp6s0f1             Driver: ixgbe      RSS:     40   [Supported by ZC]
Name: eno1                    Driver: igb         RSS:     8    [Supported by ZC]
Name: docker0               Driver: bridge    RSS:     1
Name: eno2                    Driver: igb         RSS:     8    [Supported by ZC]
Name: enp6s0f0             Driver: ixgbe      RSS:     40   [Supported by ZC]
```

It says supported but it doesn't change after running the command? Do I need a license for it or I have done something wrong?!

Best Regards =)

**Comment by cardigliano** [comment]
Is your management interface also using ixgbe perhaps? In that case you need to force it (--force) as the driver will be reloaded and you may loose connectivity

**Comment by stanley111111** [comment]
Wow, thanks for the quick response just used the **--force** option, and indeed I lost connection.  And came back after 2 minutes and _worked_!!!

sudo pf_ringcfg --list-interfaces
```
Name: enp6s0f1             Driver: ixgbe      RSS:     1    [Running ZC] <-----
Name: eno1                 Driver: igb        RSS:     8    [Supported by ZC]
Name: docker0              Driver: bridge     RSS:     1
Name: eno2                 Driver: igb        RSS:     8    [Supported by ZC]
Name: enp6s0f0             Driver: ixgbe      RSS:     1    [Running ZC] <-----
```

For anyone playing around I also had the nightly build by mistake and just replaced with the stable version (lsmod rmmod)

cat /proc/net/pf_ring/info
```PF_RING Version          : 8.1.0 (dev:cabd2381e3bb623b5b22e670e9612b622fa94d49)
Total rings              : 2

Standard (non ZC) Options
Ring slots               : 65536
Slot version             : 20
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
```

```cat /proc/net/pf_ring/info
PF_RING Version          : 8.0.0 (unknown)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 65536
Slot version             : 18
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0
```

Not sure if I am supposed to open a new issue for this but here goes nothing:


Where do I add the ZC 10gbe license that I am going to buy into the software? For some reason the speed dropped from 
~2.7mpps to ~1.2mpps!!! same exact command ```zmap -p80 -T9 -i enp6s0f0 -B 11G | grep Kb ``` Am I supposed to use zc: next to the enp6s0f0 cause when I did that I got this

 ```zmap -G 00:1b:21:bc:76:96 -p 80 -i zc:enp6s0f0 -o output.csv -T9 -B 11G```
```[FATAL] get-iface-ip: ioctl failure: No such device``` ```and without the zc command I get lower speed than before```


Thanks a lot for your time appreciate it =)

**Comment by cardigliano** [comment]
You definitely need to use the zc: prefix to run zero-copy mode. It seems zmap does not handle it correctly (it should not fail on ioctl). Without zc: you get lower performance as you are running the standard mode and driver is now configured with 1 RSS queue.

**Comment by stanley111111** [comment]
Oh okay makes sense, should I use RSS 2? Even masscan acts weird

```masscan 0.0.0.0/0 -p80 --rate=10000000 --exclude 255.255.255.255 -oJ test.json --pfring```

```No pfring adapter available. Please install pfring or run masscan without the --pfring option. adapter[enp6s0f0].init: failed```

root@ubuntu:~#  masscan --iflist
```
 0  enp6s0f0    (No description available)
 1  eno1        (No description available)
 2  enp6s0f1    (No description available)
 3  eno2        (No description available)
 4  lo  (No description available)
 5  any         (Pseudo-device that captures on all interfaces)
 6  docker0     (No description available)
 7  nflog       (Linux netfilter log (NFLOG) interface)
 8  nfqueue     (Linux netfilter queue (NFQUEUE) interface)
```

**Comment by stanley111111** [comment]
root@ubuntu:~# modinfo pf_ring
```
filename:       /lib/modules/5.4.0-120-generic/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
version:        8.0.0
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
srcversion:     39A03DB35F34BABB24A42CB
depends:
retpoline:      Y
name:           pf_ring
vermagic:       5.4.0-120-generic SMP mod_unload modversions
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)
parm:           force_ring_lock:Set to 1 to force ring locking (automatically enable with rss) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog, 2 for more verbosity (uint)
parm:           transparent_mode:(deprecated) (uint)
```

root@ubuntu:~# lsmod | grep pf_ring
```pf_ring               724992  7 ixgbe_zc```

root@ubuntu:~# masscan --pfring -p80,8000-8100 10.0.0.0/8 --rate=10000
```No pfring adapter available. Please install pfring or run masscan without the --pfring option. adapter[enp6s0f0].init: failed```

P.S defined gateway and router ip and same outcome


root@ubuntu:~# zmap -p80 -T9 -i zc:enp6s0f0 -B 11G | grep Kb
```[FATAL] get-iface-ip: ioctl failure: No such device```


root@ubuntu:~# pf_ringcfg --list-interfaces
```Name: docker0              Driver: bridge     RSS:     1
Name: eno2                 Driver: igb        RSS:     8    [Supported by ZC]
Name: eno1                 Driver: igb        RSS:     8    [Supported by ZC]
Name: enp6s0f0             Driver: ixgbe      RSS:     1    [Running ZC]
Name: enp6s0f1             Driver: ixgbe      RSS:     1    [Running ZC]
```

**Comment by cardigliano** [comment]
@stanley111111 I am not aware of what masscan does to detect pfring, please contact the masscan community (please provide a reference here)

**Comment by mzpqnxow** [comment]
> root@ubuntu:~# modinfo pf_ring
> 
> ```
> 
> filename:       /lib/modules/5.4.0-120-generic/kernel/net/pf_ring/pf_ring.ko
> 
> alias:          net-pf-27
> 
> version:        8.0.0
> 
> description:    Packet capture acceleration and analysis
> 
> author:         ntop.org
> 
> license:        GPL
> 
> srcversion:     39A03DB35F34BABB24A42CB
> 
> depends:
> 
> retpoline:      Y
> 
> name:           pf_ring
> 
> vermagic:       5.4.0-120-generic SMP mod_unload modversions
> 
> parm:           min_num_slots:Min number of ring slots (uint)
> 
> parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
> 
> parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
> 
> parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
> 
> parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
> 
> parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)
> 
> parm:           force_ring_lock:Set to 1 to force ring locking (automatically enable with rss) (uint)
> 
> parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog, 2 for more verbosity (uint)
> 
> parm:           transparent_mode:(deprecated) (uint)
> 
> ```
> 
> 
> 
> root@ubuntu:~# lsmod | grep pf_ring
> 
> ```pf_ring               724992  7 ixgbe_zc```
> 
> 
> 
> root@ubuntu:~# masscan --pfring -p80,8000-8100 10.0.0.0/8 --rate=10000
> 
> ```No pfring adapter available. Please install pfring or run masscan without the --pfring option. adapter[enp6s0f0].init: failed```
> 
> 
> 
> P.S defined gateway and router ip and same outcome
> 
> 
> 
> 
> 
> root@ubuntu:~# zmap -p80 -T9 -i zc:enp6s0f0 -B 11G | grep Kb
> 
> ```[FATAL] get-iface-ip: ioctl failure: No such device```
> 
> 
> 
> 
> 
> root@ubuntu:~# pf_ringcfg --list-interfaces
> 
> ```Name: docker0              Driver: bridge     RSS:     1
> 
> Name: eno2                 Driver: igb        RSS:     8    [Supported by ZC]
> 
> Name: eno1                 Driver: igb        RSS:     8    [Supported by ZC]
> 
> Name: enp6s0f0             Driver: ixgbe      RSS:     1    [Running ZC]
> 
> Name: enp6s0f1             Driver: ixgbe      RSS:     1    [Running ZC]
> 
> ```
> 
> 

FWIW, I once encountered the ioctl error when my userspace package and kernel module had a grossly mismatched version

Building both (including the PF_RING libpcap shared library) from source fixed the issue

**Comment by ArmanSabzevari** [comment]
@cardigliano could you please tell me how to verify if PFring  ZC in cluster mode is working correctly? the only way i know to check is "pfcount -i zc:eth0" but it returned error. 

the only worker we have for zeek:
[worker-1]
type=worker
host=127.0.0.1
interface=zc:99
lb_method=pf_ring
lb_procs=14
pin_cpus=5,7,9,11,13,15,17,19,21,23,25,27,29,31


cat info:
PF_RING Version          : 8.8.0 (unknown)
Total rings              : 30

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 21
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

pfcount -i zc:enp94s0f0
Using PF_RING v.8.8.0.240805 kernel module v.8.8.0
Dumping statistics on /proc/net/pf_ring/stats/45585-enp94s0f0.41
Unable to enable ring :-(

sudo pfcount -i zc:99
pfring_open error [Resource temporarily unavailable] (pf_ring not loaded or interface zc:99 is down ?)

**Comment by cardigliano** [comment]
Do you have any other application capturing from zc:99 (including zeek) while running pfcount -i zc:99 ? Access to the queue is exclusive.

**Comment by ArmanSabzevari** [comment]
@cardigliano Thank you for your reply. The environment is a fresh installation of OS(ubuntu 22), PFring, and Zeek. I stopped Zeek and pfring load balancer services(I stopped all apps that may use zc:99). Now using "pfcount -i zc:enp94s0f0" does not return error but "pfcount -i zc:99" output is the same

**Comment by cardigliano** [comment]
Please provide the command and output for zbalance_ipc

**Comment by ArmanSabzevari** [comment]
So, I started Zeek and pfring loadbalancer.
while everything works but I do not know if this is ZC log or Vanilla the situation is like this:
zbalance_ipc -i zc:enp94s0f0 -c 99 -n 14 -m 1 -g 3 -d -l /var/log/zbalance.log
 Cat  /var/log/zbalance.log
 16/Sep/2024 15:09:53 [zbalance_ipc.c:1568] Starting balancer with 14 consumer queues..
16/Sep/2024 15:09:53 [zbalance_ipc.c:1580] Run your application instances as follows:
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@0
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@1
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@2
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@3
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@4
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@5
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@6
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@7
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@8
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@9
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@10
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@11
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@12
16/Sep/2024 15:09:53 [zbalance_ipc.c:1586]      pfcount -i zc:99@13
16/Sep/2024 15:09:53 [zbalance_ipc.c:1630] Running balancer #0 on core 3...

**Comment by ArmanSabzevari** [comment]
if i stop zeek, then pfcount -i zc:99 has the correct output.... I think everything works now. do you confirm that it is a correct way to check if ZC work correctly?

**Comment by cardigliano** [comment]
Yes that's the expected behaviour

**Comment by ArmanSabzevari** [comment]
thank you very much @cardigliano
