### ISSUE TITLE
pf_ring zc 6.2.0 Cannot capture XP win data package?

### ISSUE THREAD

**Issue by huangsheng-dafo** [ntop/PF_RING#82]
I will WinXP installed in the virtual machine, 
Virtual machine using bridge mode,
the link network in the virtual machine, ZC PF_RING 
mode can not be captured in the WinXP virtual 
machine data packets，

---
## The client environment is as follows

VM Information is as follows:
VMware Workstation 12 Pro
12.0.0 build-2985596

OS is WinXp SP2

---
## Server environment is as follows

OS is Centos6.2 x64

PF_RING Information is as follows:
PF_RING Version          : 6.2.0 (unknown)
Total rings              : 2

Standard (non DNA/ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Total plugins            : 0
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

Network card driver information is as follows:
[root@localhost ~]# ethtool -i eth1
driver: e1000e
version: 3.2.7.1-NAPI
firmware-version: 2.1-3

**Comment by cardigliano** [comment]
The topology is not clear, please rephrase, thank you.
