### ISSUE TITLE
Should I be able to use pfring_zc on a VF?

### ISSUE THREAD

**Issue by jasonnrich** [ntop/PF_RING#820]
I'm trying to virtualize what used to be some older bare metal machines.   I've got an ESXI host (703uD) with SRIOV enabled on my x710 nics.

My VM comes up (ubuntu 20), see's his interfaces (iavf driver), but I cannot seem to compile/install PFRING in such a way that it recognizes a valid interface.  I've tried installing both the i40e and ice drivers, but no valid interface is found (which seems correct since its really a VF using iavf).   Should I be able to do this?
root@ubuntu20-sriov:~/PF_RING# uname -a
Linux ubuntu20-sriov 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu20-sriov:~/PF_RING# /root/PF_RING/package/usr/bin/pf_ringcfg --list-zc-drivers
e1000e
igb
ixgbe
ixgbevf
i40e
fm10k
ice
mlx5_core

root@ubuntu20-sriov:~/PF_RING# /root/PF_RING/package/usr/bin/pf_ringcfg --configure-driver ice --rss-queues 1
<SNIP>
[>] Configuring PF_RING
[>] Configuring hugepages
[>] Detecting interfaces using i40e
No i40e interface found

**Comment by cardigliano** [comment]
@jasonnrich VFs for i40e are not currently supported. Only ixgbe VFs are supported. The only option you have to use ZC with X710 on a VM is to use the PCI passthrough (IO Direct)

**Comment by jasonnrich** [comment]
Understood, tested and works.  Thanks.  Is support for the i40e VFs on a future roadmap?

**Comment by cardigliano** [comment]
There is no plan, however I created an feature request at https://github.com/ntop/PF_RING/issues/823
