### ISSUE TITLE
Why does pcap_compile not optimize

### ISSUE THREAD

**Issue by sdir** [ntop/PF_RING#826]
https://github.com/ntop/PF_RING/blob/88585ea7b5e50592aba0df6db6678bd2d920b090/userland/lib/pfring_mod.c#L981

Turning on optimization can use pfring_set_bpf_filter to write more complex settings

```c
rc = pcap_compile(p, &filter, filter_buffer, 1, 0); 
```

**Comment by cardigliano** [comment]
Optimization enabled now, there was no reason to keep it turned off afaik
