### ISSUE TITLE
kernel Make Error

### ISSUE THREAD

**Issue by psdjc** [ntop/PF_RING#827]
CentOS Stream release 9

Linux test 5.14.0-134.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 21 12:57:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> make -C /lib/modules/5.14.0-134.el9.x86_64/build M=/usr/local/src/PF_RING/kernel EXTRA_CFLAGS='-I/usr/local/src/PF_RING/kernel -DGIT_REV="\"dev:36293f89224f382fb7090aef8562cc78c8eb6f61\"" -no-pie -fno-pie -Wno-implicit-fallthrough' modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-134.el9.x86_64'
  CC [M]  /usr/local/src/PF_RING/kernel/pf_ring.o
/usr/local/src/PF_RING/kernel/pf_ring.c: In function ‘ring_proc_open’:
/usr/local/src/PF_RING/kernel/pf_ring.c:1082:48: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DATA’? [-Werror=implicit-function-declaration]
 1082 |   return single_open(file, ring_proc_get_info, PDE_DATA(inode));
      |                                                ^~~~~~~~
      |                                                NODE_DATA
/usr/local/src/PF_RING/kernel/pf_ring.c:1082:48: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Wint-conversion]
 1082 |   return single_open(file, ring_proc_get_info, PDE_DATA(inode));
      |                                                ^~~~~~~~~~~~~~~
      |                                                |
      |                                                int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:181,
                 from ./include/linux/netdevice.h:37,
                 from ./include/linux/rtnetlink.h:7,
                 from /usr/local/src/PF_RING/kernel/pf_ring.c:84:
./include/linux/seq_file.h:151:68: note: expected ‘void *’ but argument is of type ‘int’
  151 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/usr/local/src/PF_RING/kernel/pf_ring.c: In function ‘ring_proc_virtual_filtering_open’:
/usr/local/src/PF_RING/kernel/pf_ring.c:4570:70: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Wint-conversion]
 4570 |   return single_open(file, ring_proc_virtual_filtering_dev_get_info, PDE_DATA(inode));
      |                                                                      ^~~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:181,
                 from ./include/linux/netdevice.h:37,
                 from ./include/linux/rtnetlink.h:7,
                 from /usr/local/src/PF_RING/kernel/pf_ring.c:84:
./include/linux/seq_file.h:151:68: note: expected ‘void *’ but argument is of type ‘int’
  151 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/usr/local/src/PF_RING/kernel/pf_ring.c: In function ‘pf_ring_inject_packet_to_stack’:
/usr/local/src/PF_RING/kernel/pf_ring.c:5833:9: error: implicit declaration of function ‘netif_rx_ni’; did you mean ‘netif_rx’? [-Werror=implicit-function-declaration]
 5833 |   err = netif_rx_ni(skb);
      |         ^~~~~~~~~~~
      |         netif_rx
/usr/local/src/PF_RING/kernel/pf_ring.c: In function ‘ring_proc_stats_open’:
/usr/local/src/PF_RING/kernel/pf_ring.c:6687:50: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Wint-conversion]
 6687 |   return single_open(file, ring_proc_stats_read, PDE_DATA(inode));
      |                                                  ^~~~~~~~~~~~~~~
      |                                                  |
      |                                                  int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:181,
                 from ./include/linux/netdevice.h:37,
                 from ./include/linux/rtnetlink.h:7,
                 from /usr/local/src/PF_RING/kernel/pf_ring.c:84:
./include/linux/seq_file.h:151:68: note: expected ‘void *’ but argument is of type ‘int’
  151 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
/usr/local/src/PF_RING/kernel/pf_ring.c: In function ‘ring_proc_dev_open’:
/usr/local/src/PF_RING/kernel/pf_ring.c:8314:52: warning: passing argument 3 of ‘single_open’ makes pointer from integer without a cast [-Wint-conversion]
 8314 |   return single_open(file, ring_proc_dev_get_info, PDE_DATA(inode));
      |                                                    ^~~~~~~~~~~~~~~
      |                                                    |
      |                                                    int
In file included from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:181,
                 from ./include/linux/netdevice.h:37,
                 from ./include/linux/rtnetlink.h:7,
                 from /usr/local/src/PF_RING/kernel/pf_ring.c:84:
./include/linux/seq_file.h:151:68: note: expected ‘void *’ but argument is of type ‘int’
  151 | int single_open(struct file *, int (*)(struct seq_file *, void *), void *);
      |                                                                    ^~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:271: /usr/local/src/PF_RING/kernel/pf_ring.o] Error 1
make[1]: *** [Makefile:1887: /usr/local/src/PF_RING/kernel] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-134.el9.x86_64'
make: *** [Makefile:67: all] Error 2

**Comment by cardigliano** [comment]
@psdjc what PF_RING version / branch are you compiling?

**Comment by psdjc** [comment]
Version 8.2

**Comment by cardigliano** [comment]
Please check the dev branch on github

**Comment by psdjc** [comment]
I compile after running
git clone https://github.com/ntop/PF_RING.git
