### ISSUE TITLE
Packet Encapsulation in PF_RING ZC applications

### ISSUE THREAD

**Issue by akiskourtis** [ntop/PF_RING#83]
Hello,

First of all thank you for all your great work.
I am using the zbounce application with kernel-driver interfaces, and I would like to know if it is possible to encapsulate the packets, before sending them out.
As I have understood the packets in the zero-copy applications are stored in pfring_zc_pkt_buff, as I have tested I can modify the fields, however I have not managed to increase its size, or add additional headers, as I cannot modify packet data in this struct.
Is this possible in the zero-copy applications?

Thank you,

Akis

**Comment by lucaderi** [comment]
If you want to encapsulate packets you cannot use zero-copy as you need to modify the payload and recomputed checksum etc. So you can capture in zero copy but you need to do some memory management for preparing the new packet, then cannot then be sent in ZC as the original packet was modified in memory. ZC memory is allocated at the MTU, so you have room for your extra data.

**Comment by akiskourtis** [comment]
Thank you for your response, I can see it more clearly now. I will maybe use a different transmitting path, but for the matter concerned I am covered. Thank you.
