### ISSUE TITLE
BPF filter for VLAN doesn't work after update from 6.6.0 to 7.8.0

### ISSUE THREAD

**Issue by teoring** [ntop/PF_RING#832]
We noticed strange change in the behavior of BPF filter. After the PFRING update we noticed that negative offsets doesn't seem to work anymore.

This is the filter we use to filter on specific VLANs:

` '(ether[-4088:4] = 3 and (ether[-4048:1] = 1 and (ether[-4052:1] = 712 or ether[-4052:1] = 713 or ether[-4052:1] = 714 or ether[-4052:1] = 715 or ether[-4052:1] = 717)))'
`
Where "3" in 'ether[-4088:4] = 3' represents an interface index.

On PFRING 6.6.0 ( kernel 4.4.232-11.el7.x86_64, CentOS 7 ) this filter was working. We had libpcap v1.5.3.

```
[root@ct-1759 ~]# tcpdump --version
tcpdump version 4.9.2
libpcap version 1.5.3
OpenSSL 1.0.2k-fips  26 Jan 2017
```

This tcpdump of simple filter on previous version:
![image](https://user-images.githubusercontent.com/12891023/188623998-969d7846-63e2-47ba-892e-1a80c7201fcd.png)

On PFRING 7.8.0

```
root@xx-u20:~/Development/zzzz$ sudo tcpdump --version
tcpdump version 4.9.3-fs1
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.0.2g-fips  1 Mar 2016
```

This tcpdump of simple filter on new version:
![image](https://user-images.githubusercontent.com/12891023/188624284-c1925936-30eb-4c57-9f75-5d0ecc404300.png)

Any idea why we see this change?

**Comment by cardigliano** [comment]
@teoring this seems related to some change in the latest libpcap version, I will take a loop asap. Thank you for reporting with useful details.

**Comment by cardigliano** [comment]
@teoring it seems that the behavior of the bpf compiler changed (also 1.7.x was producing the same bytecode of 1.5.x). Could you open an issue at https://github.com/the-tcpdump-group/libpcap/issues ? Thank you.

**Comment by teoring** [comment]
Thanks for checking! We can close this issue and I will open a new one on libpcap repo.
