### ISSUE TITLE
PF_ring version certification for RHEL 9 kernel

### ISSUE THREAD

**Issue by Yasminkundur** [ntop/PF_RING#833]
Hi,

we want to know what is the pf_ring version supported for RHEL9 kernel version "5.14.0-70.17.1.el9_0.x86_64"
we are certifying our applications where we used pf_ring driver. following are the results.

Pf_ring 8.x version on kernel "5.14.0-70.17.1.el9_0.x86_64" (RHEL9)
git clone https://github.com/ntop/PF_RING.git
Kernel Module Installation
cd PF_RING/kernel
make
sudo make install

Running PF_RING
cd PF_RING/kernel
sudo insmod pf_ring.ko min_num_slots=65536 enable_tx_capture=0
Drivers
cd PF_RING/drivers/intel
make
cd ixgbe/ixgbe-*-zc/src
sudo ./load_driver.sh

output:

[root@localhost ~]# lsmod | grep pf_ring
pf_ring               208896  1 ixgbe

whereas pf_ring 7.x on kernel "5.14.0-70.17.1.el9_0.x86_64" (RHEL9) fails
[Pf_ring failure.txt](https://github.com/ntop/PF_RING/files/9563232/Pf_ring.failure.txt)
t

Any quick response is appreciated.

**Comment by cardigliano** [comment]
Please use pf_ring 8.3 (dev branch) on RH9

**Comment by Yasminkundur** [comment]
@cardigliano 
 What about pf_ring 7.x version?? 
Why we are facing the issue while building??
 Will it not work on RHEL9?? Is Yes will it work on RHEL8?

**Comment by cardigliano** [comment]
PF_RING 7.x is no longer supported sorry
