### ISSUE TITLE
ixgbe-zc-dkms does not install on docker

### ISSUE THREAD

**Issue by jurjenwestra78** [ntop/PF_RING#835]
For automated testing purposes we are trying to install `ixgbe-zc-dkms` from the repo on a `ubuntu-20` docker container that runs on a `ubuntu-18` host. It fails (see below). 

Basically, the installer is confused which kernel is active (not unreasonably so). Of course, `uname` returns the _actual_ kernel:
```
root@922237a4b5d6:/# uname -a
Linux 922237a4b5d6 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
but it says `Building for 5.4.0-126-generic`. I can "fix" the install issues by replacing `uname` by a little shell script that returns the right info for `ubuntu-20` before `apt install`ing `ixgbe-zc-dkms`:
```bash
#!/bin/bash
echo "5.4.0-125-generic"
```

Note:
* `pfring` installs fine.
* The version in the script was copied from a real `ubuntu-20` machine; the version is slightly different than what was mentioned by the installer.
* I read https://www.ntop.org/guides/pf_ring/vm_support/docker.html

## Questions
Questions I have:
1. Is there a better / correct way to install `ixgbe-zc-dkms` on docker like this?
2. Will this actually _work_?

Currently, we do not deploy with docker, but we see certain advantages so we may explore it in the future. We _are_ testing on docker containers, but we use a simulation mode that does not actually use any network traffic, so that's ok.

Thanks in advance!

## Install output
```
root@922237a4b5d6:/# apt-get -y install ixgbe-zc-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ixgbe-zc-dkms is already the newest version (5.5.3.7827).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up ixgbe-zc-dkms (5.5.3.7827) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Removing old ixgbe-zc-5.5.3.7827 DKMS files...

------------------------------
Deleting module version: 5.5.3.7827
completely from the DKMS tree.
------------------------------
Done.
Loading new ixgbe-zc-5.5.3.7827 DKMS files...
It is likely that 4.15.0-175-generic belongs to a chroot's host
Building for 5.4.0-126-generic
Building for architecture x86_64
Building initial module for 5.4.0-126-generic
Error! Bad return status for module build on kernel: 5.4.0-126-generic (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.7827/build/make.log for more information.
dpkg: error processing package ixgbe-zc-dkms (--configure):
 installed ixgbe-zc-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 ixgbe-zc-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by cardigliano** [comment]
@jurjenwestra78 please note that kernel modules should be installed/loaded on the host system as a container is a userspace "jail" thing..

**Comment by jurjenwestra78** [comment]
@cardigliano 
My understanding of kernel modules is very limited, so your help is appreciated. Please help me understand:

1. Having `ixgbe-zc-dkms` as a dependency makes no sense if you're installing on docker. This dependency should be installed+loaded on the host system. Right?
2. Would things "just work" if we have the `pfring` and `ixgbe-zc-dkms` packages on the host system and only install `pfring` in the docker container?
3. Would things "just work" if we have a `ubuntu-X` container running on a `ubuntu-X` host with  the `pfring` and `ixgbe-zc-dkms` packages installed on both?

**Comment by cardigliano** [comment]
> 1. Having `ixgbe-zc-dkms` as a dependency makes no sense if you're installing on docker. This dependency should be installed+loaded on the host system. Right?

Correct

> 2. Would things "just work" if we have the `pfring-dkms` and `ixgbe-zc-dkms` packages on the host system and only install `pfring` in the docker container?

Yes

> 3. Would things "just work" if we have a `ubuntu-X` container running on a `ubuntu-X` host with  the `pfring` and `ixgbe-zc-dkms` packages installed on both?

Yes but as I said you cannot install ixgbe-zc-dkms in the container

**Comment by jurjenwestra78** [comment]
Thanks, I think I know enough for now!
