### ISSUE TITLE
PF_RING Package Dropped 

### ISSUE THREAD

**Issue by frkn4129** [ntop/PF_RING#839]
I am receiving 5 Gigabit network traffic and I would like to process this traffic without data loss. I have tried to process this data with pf_ring in the Go programming language.
I have processed the network traffic with Go pf_ring on the nic card. While processing the data I also captured the traffic with tcpdump. Afterwhile I compared the differences between pf_ring and tcpdump. There were missing data at pf_ring pcap. So I have made some tests and I saw that while processing the network traffic with pf_ring, on average %70 data losses occuring. When I stopped the process at pf_ring data loss dropped to %0. Processing the network traffic even printing causes data loss.
I think this problem occurs due to the pf_ring ring buffer size. How can I increase the ring buffer size? If the cause is different how can I prevent the data loss?

**Comment by frkn4129** [comment]
**case 1**  0 drop 
![image](https://user-images.githubusercontent.com/89160550/200583514-fcc33120-a6de-4c40-9f24-010909bf49ab.png)

![image](https://user-images.githubusercontent.com/89160550/200583462-f702f4ff-c602-4df4-992c-2ccf96b02f20.png)

case 2
![image](https://user-images.githubusercontent.com/89160550/200583285-d069356b-1c28-4216-a456-74ef2ca0b051.png)

**Comment by cardigliano** [comment]
@frkn4129 at high packet rate the application should be really fast in processing packets as there are not much cpu cycles available, thus it is expected to loose packets if you use things like system calls or prints. Even the go wrapper itself introduces some overhead. You can try increasing the buffer size tuning min_num_slots as documented at https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html but that would help just in case of spikes, not with sustained traffic.

**Comment by frkn4129** [comment]
@cardigliano  Can you suggest a different method in sustainable traffic?

**Comment by cardigliano** [comment]
@frkn4129 if the performance drop depends on the Go wrapper and application, there is nothing we can do on the capture side. I suggest to check the performance with pfcount (which using the native C API) and compare it with the go application.
