### ISSUE TITLE
pcap_set_direction failed

### ISSUE THREAD

**Issue by oovoo** [ntop/PF_RING#84]
When I try tcpdump (tcpdump -nni zc:p2p2) I am getting following error:
tcpdump: zc:p2p2: pcap_set_direction failed:

Installed versions:
tcpdump-4.0.0-5.20090921gitdf3cb4.2.el6.x86_64
libpcap-1.4.0-4.20130826git2dbcaa1.el6.x86_64

We are using CentOS 6.7

**Comment by cardigliano** [comment]
Did you link tcpdump across our pfring-aware libpcap?

**Comment by oovoo** [comment]
Hi,
We compiled tcpdump with your libpcap and now it seems to work.

Thanks.
