### ISSUE TITLE
pfring_recv bug

### ISSUE THREAD

**Issue by jiongge** [ntop/PF_RING#841]
**in pfring.c and function**

int pfring_recv(pfring *ring, u_char** buffer, u_int buffer_len,
		struct pfring_pkthdr *hdr,
		u_int8_t wait_for_incoming_packet) 

#if defined(ENABLE_BPF) || defined(HAVE_PF_RING_FT)
recv_next:
#endif

    rc = ring->recv(ring, buffer, buffer_len, hdr, wait_for_incoming_packet);

    if (unlikely(rc > 0 && ring->flags & (
          PF_RING_IXIA_TIMESTAMP | 
          PF_RING_VSS_APCON_TIMESTAMP |
          PF_RING_METAWATCH_TIMESTAMP |
          PF_RING_ARISTA_TIMESTAMP))) {
      if(ring->ixia_timestamp_enabled)
        pfring_handle_ixia_hw_timestamp(*buffer, hdr);
      else if(ring->vss_apcon_timestamp_enabled)
        pfring_handle_vss_apcon_hw_timestamp(*buffer, hdr);
      else if(ring->flags & PF_RING_ARISTA_TIMESTAMP)
        pfring_handle_metawatch_hw_timestamp(*buffer, hdr);
      else if(ring->flags & PF_RING_ARISTA_TIMESTAMP) {
        if (pfring_handle_arista_hw_timestamp(*buffer, hdr) == 1)
          goto recv_next;
      }
    }

questions:
1."goto recv_next"  is not between in #if and #endif 
2."if(ring->flags & PF_RING_ARISTA_TIMESTAMP)" is same as the next if

**Comment by cardigliano** [comment]
Fixed, thank you
