### ISSUE TITLE
how to setup a cluster through muti-thread

### ISSUE THREAD

**Issue by frank-s-liu** [ntop/PF_RING#842]
it seems no API is provided in libpcap, and it seems libpcap using environment variable likes PCAP_PF_RING_CLUSTER_ID to loadbalance traffic.
are there some descriptions in document?

**Comment by cardigliano** [comment]
@frank-s-liu they are not documented unfortunately, we will add the doc asap

**Comment by frank-s-liu** [comment]
thanks

**Comment by cardigliano** [comment]
Initial doc: https://github.com/ntop/PF_RING/blob/dev/doc/api/libpcap.rst
