### ISSUE TITLE
ZeroCopy Drivers will not install on RedHat 8.7

### ISSUE THREAD

**Issue by Arislen** [ntop/PF_RING#843]
OS: Red Hat Enterprise Linux release 8.7 (Ootpa)
Kernel: 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

System has the most up2date RHEL patches.

NTOP Versions Installed (from: https://packages.ntop.org/ Nightly Build Repository)

pfring-dkms-8.3.0.8003-8003.noarch
pfring-8.3.0-8003.x86_64
n2disk-3.7.221208-5384.x86_64
e1000e-zc-3.8.7.8003-dkms.noarch
ixgbe-zc-5.5.3.8003-dkms.noarch
i40e-zc-2.17.4.8003-dkms.noarch

All three ZC drivers failed to compile.

Output from "dnf install" command:

```
Running transaction
  Preparing        :                                                                                                              1/1
  Installing       : ixgbe-zc-5.5.3.8003-dkms.noarch                                                                              1/3
  Running scriptlet: ixgbe-zc-5.5.3.8003-dkms.noarch                                                                              1/3
Loading new ixgbe-zc-5.5.3.8003 DKMS files...
Building for 4.18.0-425.3.1.el8.x86_64
Building initial module for 4.18.0-425.3.1.el8.x86_64
Error! Bad return status for module build on kernel: 4.18.0-425.3.1.el8.x86_64 (x86_64)
Consult /var/lib/dkms/ixgbe-zc/5.5.3.8003/build/make.log for more information.
warning: %post(ixgbe-zc-5.5.3.8003-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package ixgbe-zc
  Installing       : i40e-zc-2.17.4.8003-dkms.noarch                                                                              2/3
  Running scriptlet: i40e-zc-2.17.4.8003-dkms.noarch                                                                              2/3
Loading new i40e-zc-2.17.4.8003 DKMS files...
Building for 4.18.0-425.3.1.el8.x86_64
Building initial module for 4.18.0-425.3.1.el8.x86_64
Error! Bad return status for module build on kernel: 4.18.0-425.3.1.el8.x86_64 (x86_64)
Consult /var/lib/dkms/i40e-zc/2.17.4.8003/build/make.log for more information.
warning: %post(i40e-zc-2.17.4.8003-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package i40e-zc
  Installing       : e1000e-zc-3.8.7.8003-dkms.noarch                                                                             3/3
  Running scriptlet: e1000e-zc-3.8.7.8003-dkms.noarch                                                                             3/3
Loading new e1000e-zc-3.8.7.8003 DKMS files...
Building for 4.18.0-425.3.1.el8.x86_64
Building initial module for 4.18.0-425.3.1.el8.x86_64
Error! Bad return status for module build on kernel: 4.18.0-425.3.1.el8.x86_64 (x86_64)
Consult /var/lib/dkms/e1000e-zc/3.8.7.8003/build/make.log for more information.
warning: %post(e1000e-zc-3.8.7.8003-dkms.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package e1000e-zc
```

I’ve included the make.log files from the driver compilse.

Thanks for your help.

[e1000e-zc-make.log](https://github.com/ntop/PF_RING/files/10185628/e1000e-zc-make.log)
[i40e-make.log](https://github.com/ntop/PF_RING/files/10185630/i40e-make.log)
[ixgbe-make.log](https://github.com/ntop/PF_RING/files/10185631/ixgbe-make.log)

**Comment by novaksam** [comment]
Yeah I had the some thing on Rocky linux; digging in it was something to do with different method definitions getting picked up. I was able to fix it manually, and rerun DKMS build/install, but I forget the exact changes.

**Comment by cardigliano** [comment]
I pushed a driver update on the dev branch that should fix compilation on Rocky 8.7

**Comment by Arislen** [comment]
> I pushed a driver update on the dev branch that should fix compilation on Rocky 8.7

Looks like the ZC driver updates didn't make it to https://packages.ntop.org/centos/8/noarch/Packages/

![image](https://user-images.githubusercontent.com/58514010/207046340-15dec46c-5792-483e-998c-a094e51b9033.png)

**Comment by cardigliano** [comment]
Please check again

<img width="657" alt="Screen Shot 2022-12-12 at 14 16 59" src="https://user-images.githubusercontent.com/7548711/207054489-22e602d8-e678-41d0-9ff0-ae566a3b4e92.png">

**Comment by Arislen** [comment]
Got the drivers. Testing now.

**Comment by Arislen** [comment]
Tested the new ZeroCopy drivers and they now compile. Thanks for your assist.
