### ISSUE TITLE
ixgbe_zc not support recv_burst

### ISSUE THREAD

**Issue by tiger-mango** [ntop/PF_RING#846]
system: centos7  
version: pf_ring 8.2  ZC mode
NIC: intel 82599ES
traffic: 20Gbps，8 Rss rx queue
desc: pfring_recv_burst return PF_RING_ERROR_NOT_SUPPORTED
Will support later? Because using pfring_recv, the perf top indicates that ring_is_not_empty is hot.

**Comment by cardigliano** [comment]
Please consider using the ZC API to receive traffic in batch on 82599 (see pfring_zc_recv_pkt_burst)
