### ISSUE TITLE
Arista HW Nanosecond Time Stamping Support

### ISSUE THREAD

**Issue by JeremyAshton** [ntop/PF_RING#85]
The arista switches support precision time stamping similar to IXIA devices.

https://www.arista.com/assets/data/pdf/7150S_Q&A.pdf
https://eos.arista.com/timestamping-deep-dive-frequent-questions-and-tips-on-integration/
https://eos.arista.com/timestamping-on-the-7150-series/

There are some reference pcap files at:
https://github.com/arista-eosext/PCAPDecoder/blob/master/pcaps/test-1.pcap
https://github.com/arista-eosext/PCAPDecoder/blob/master/pcaps/test-2.pcap

I would love to see this format be supported as well.

**Comment by cardigliano** [comment]
Arista 7150 and Arista 7130 MetaWatch support has been introduced time ago
