### ISSUE TITLE
i40e null pointer turns kernel read mode.

### ISSUE THREAD

**Issue by vehere-ccu1** [ntop/PF_RING#856]
Using PF_RING 8.2 on debian 11, whenever unloading OS driver and loading PF driver i40e, it stuck, and I am not able to run commads like sudo, systemctl etc.
![dmesg](https://user-images.githubusercontent.com/33222750/216548528-a475ab1f-df0d-4220-a5fc-5bf51147d51c.png)

**Comment by cardigliano** [comment]
Please update to latest stable (8.4) and let us know if it is still affected

**Comment by vehere-ccu1** [comment]
Sure

**Comment by vehere-ccu1** [comment]
Same output for PF-8.4.0: -

[Fri Feb  3 15:16:54 2023] NFSD: Using UMH upcall client tracking operations.
[Fri Feb  3 15:16:54 2023] NFSD: starting 90-second grace period (net f0000098)
[Fri Feb  3 15:17:12 2023] i40e 0000:81:00.3: i40e_ptp_stop: removed PHC on ens4f3
[Fri Feb  3 15:17:13 2023] i40e 0000:81:00.2: i40e_ptp_stop: removed PHC on ens4f2
[Fri Feb  3 15:17:14 2023] i40e 0000:81:00.1: i40e_ptp_stop: removed PHC on ens4f1
[Fri Feb  3 15:17:15 2023] i40e 0000:81:00.0: i40e_ptp_stop: removed PHC on ens4f0
[Fri Feb  3 15:17:16 2023] i40e 0000:63:00.1: i40e_ptp_stop: removed PHC on eno34
[Fri Feb  3 15:17:18 2023] i40e 0000:63:00.0: i40e_ptp_stop: removed PHC on eno33
[Fri Feb  3 15:17:19 2023] NET: Unregistered protocol family 27
[Fri Feb  3 15:17:19 2023] [PF_RING] Module unloaded
[Fri Feb  3 15:17:21 2023] [PF_RING] Welcome to PF_RING 8.4.0 ($Revision: unknown$)
                           (C) 2004-22 ntop
[Fri Feb  3 15:17:21 2023] LINUX_VERSION_CODE 00050A7F
[Fri Feb  3 15:17:21 2023] [PF_RING] Min # ring slots 4096
[Fri Feb  3 15:17:21 2023] [PF_RING] Slot version     20
[Fri Feb  3 15:17:21 2023] [PF_RING] Capture TX       Yes [RX+TX]
[Fri Feb  3 15:17:21 2023] [PF_RING] IP Defragment    No
[Fri Feb  3 15:17:21 2023] NET: Registered protocol family 27
[Fri Feb  3 15:17:21 2023] [PF_RING] pf_ring initialized correctly
[Fri Feb  3 15:17:21 2023] i40e: Intel(R) 40-10 Gigabit Ethernet Connection Network Driver - version 2.17.4
[Fri Feb  3 15:17:21 2023] i40e: Copyright(c) 2013 - 2021 Intel Corporation.
[Fri Feb  3 15:17:21 2023] i40e 63:00.0 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:21 2023] i40e 63:00.0 Core and Global modules ready 0
[Fri Feb  3 15:17:21 2023] i40e 63:00.0 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.0: fw 9.80.70867 api 1.15 nvm 9.00 0x8000cfe5 21.5.9
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.0: MAC address: 68:05:ca:d3:73:8c
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.0: qs_avail=768 FD SB=1 lan_qs=32 lan_tc0=32 vf=64*4 vmdq=8*1, remaining=471
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.0: Enabling symmetric hash (HSYM)
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.0: PCI-Express: Speed 8.0GT/s Width x8
[Fri Feb  3 15:17:21 2023] [PF_RING-ZC] i40e_up_complete: attach eth0 [pf start=1100065275904 len=16777216][cache_line_size=64][MSIX enabled]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@0 [rx-ring=000000000eb10152][tx-ring=00000000d98c6a81]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@1 [rx-ring=00000000a28424da][tx-ring=00000000dd05997c]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@2 [rx-ring=000000009f677098][tx-ring=00000000ede712ae]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@3 [rx-ring=0000000040d783f2][tx-ring=000000004786b023]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@4 [rx-ring=0000000026131392][tx-ring=00000000d8aec08a]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@5 [rx-ring=00000000bda9c8ad][tx-ring=00000000fe4976a4]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@6 [rx-ring=000000007ef94ee3][tx-ring=00000000b8acd14a]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@7 [rx-ring=000000003bf8ede9][tx-ring=00000000f53bf8a3]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@8 [rx-ring=00000000b0f87ade][tx-ring=000000009db709f5]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@9 [rx-ring=000000006b2aac9a][tx-ring=000000004f040fc1]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@10 [rx-ring=00000000db96aef2][tx-ring=00000000ca330e3a]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@11 [rx-ring=000000007336cb56][tx-ring=00000000bb7967b4]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@12 [rx-ring=00000000bef0be60][tx-ring=000000005b17a010]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@13 [rx-ring=00000000b6a1df02][tx-ring=000000004b4c7636]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@14 [rx-ring=00000000b48ba436][tx-ring=000000009e042a88]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@15 [rx-ring=0000000075b92d5d][tx-ring=00000000b5ff4ee9]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@16 [rx-ring=00000000425f84c5][tx-ring=00000000f763c0e3]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@17 [rx-ring=0000000000715d24][tx-ring=00000000de4cedc7]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@18 [rx-ring=00000000a2358bfe][tx-ring=000000001367d81d]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@19 [rx-ring=00000000ddb7da6e][tx-ring=00000000babbf9fa]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@20 [rx-ring=000000001530a45c][tx-ring=000000003c124abb]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@21 [rx-ring=0000000093dd6b9f][tx-ring=000000000db1454f]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@22 [rx-ring=000000009b2fdc3b][tx-ring=00000000949f3f41]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@23 [rx-ring=00000000916663a5][tx-ring=0000000016faffc8]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@24 [rx-ring=0000000077a3b292][tx-ring=00000000d7115008]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@25 [rx-ring=00000000a50d1013][tx-ring=0000000071f8da93]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@26 [rx-ring=00000000c0d7cc7e][tx-ring=00000000bf253b58]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@27 [rx-ring=00000000e2f5abd5][tx-ring=0000000070abdeb6]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@28 [rx-ring=000000006e64e7a6][tx-ring=000000009277710d]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@29 [rx-ring=0000000054463f6c][tx-ring=0000000024d2654f]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@30 [rx-ring=00000000e4794157][tx-ring=0000000028e3abeb]
[Fri Feb  3 15:17:21 2023] [PF_RING] Registering ZC device eth0@31 [rx-ring=000000009f40bc46][tx-ring=00000000dd3d88b9]
[Fri Feb  3 15:17:21 2023] 8021q: adding VLAN 0 to HW filter on device eth0
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.0: Features: PF-id[0] VFs: 64 VSIs: 66 QP: 32 RSS FD_ATR FD_SB NTUPLE CloudF VxLAN Geneve NVGRE PTP VEPA
[Fri Feb  3 15:17:21 2023] i40e 63:00.1 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:21 2023] i40e 63:00.1 Core and Global modules ready 0
[Fri Feb  3 15:17:21 2023] i40e 63:00.1 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:21 2023] i40e 0000:63:00.1: fw 9.80.70867 api 1.15 nvm 9.00 0x8000cfe5 21.5.9
[Fri Feb  3 15:17:22 2023] i40e 0000:63:00.1: MAC address: 68:05:ca:d3:73:8d
[Fri Feb  3 15:17:22 2023] i40e 0000:63:00.1: qs_avail=768 FD SB=1 lan_qs=32 lan_tc0=32 vf=64*4 vmdq=8*1, remaining=471
[Fri Feb  3 15:17:22 2023] i40e 0000:63:00.1: Enabling symmetric hash (HSYM)
[Fri Feb  3 15:17:22 2023] i40e 0000:63:00.1: PCI-Express: Speed 8.0GT/s Width x8
[Fri Feb  3 15:17:22 2023] i40e 0000:63:00.1: Features: PF-id[1] VFs: 64 VSIs: 66 QP: 32 RSS FD_ATR FD_SB NTUPLE CloudF VxLAN Geneve NVGRE PTP VEPA
[Fri Feb  3 15:17:22 2023] i40e 81:00.0 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:22 2023] i40e 81:00.0 Core and Global modules ready 0
[Fri Feb  3 15:17:22 2023] [PF_RING-ZC] i40e_up_complete: attach eth1 [pf start=1100082053120 len=16777216][cache_line_size=64][MSIX enabled]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@0 [rx-ring=0000000041f5c017][tx-ring=000000008e11da14]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@1 [rx-ring=00000000dedac7c9][tx-ring=00000000fddc94d0]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@2 [rx-ring=000000008321cd20][tx-ring=000000001acbafc6]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@3 [rx-ring=0000000092b86cc5][tx-ring=000000007764af0e]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@4 [rx-ring=0000000020e73eed][tx-ring=00000000efe59f1a]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@5 [rx-ring=00000000f1b21d81][tx-ring=000000003683f0f5]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@6 [rx-ring=0000000044860da6][tx-ring=000000003fe628c3]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@7 [rx-ring=00000000bc75f92d][tx-ring=00000000c66cb424]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@8 [rx-ring=00000000f22f9687][tx-ring=000000003466174b]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@9 [rx-ring=000000008d131c5f][tx-ring=000000003d19fa7d]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@10 [rx-ring=00000000bba0d36c][tx-ring=000000000fa014a7]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@11 [rx-ring=00000000497e28a5][tx-ring=00000000f847bbe5]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@12 [rx-ring=0000000098f7cccb][tx-ring=00000000bd3711f0]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@13 [rx-ring=00000000e03a0a79][tx-ring=0000000042e7f70b]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@14 [rx-ring=00000000fd9a84e9][tx-ring=000000009ab13140]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@15 [rx-ring=000000004c4655e3][tx-ring=0000000010072106]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@16 [rx-ring=00000000284d9d7a][tx-ring=0000000025d455f5]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@17 [rx-ring=0000000004ffaebe][tx-ring=00000000815d7cdb]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@18 [rx-ring=00000000a9563fa1][tx-ring=00000000d1b35096]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@19 [rx-ring=000000009aaf1e3f][tx-ring=0000000054815671]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@20 [rx-ring=00000000db931c99][tx-ring=00000000e27c5d24]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@21 [rx-ring=00000000db4205b2][tx-ring=000000005f85ba33]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@22 [rx-ring=00000000f3dfa047][tx-ring=000000004e6c5189]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@23 [rx-ring=00000000a0370943][tx-ring=0000000015958d39]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@24 [rx-ring=0000000056d89c72][tx-ring=00000000360414f7]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@25 [rx-ring=00000000d1f282ff][tx-ring=0000000077cb8712]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@26 [rx-ring=00000000458afb3b][tx-ring=000000001cd7ea0d]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@27 [rx-ring=00000000b4b2ae0f][tx-ring=0000000012afbcaf]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@28 [rx-ring=000000008711a93a][tx-ring=0000000041aa012b]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@29 [rx-ring=000000005232bc65][tx-ring=000000007f58f06e]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@30 [rx-ring=000000008211e63f][tx-ring=000000004e875591]
[Fri Feb  3 15:17:22 2023] [PF_RING] Registering ZC device eth1@31 [rx-ring=00000000b26b83cb][tx-ring=0000000075f8f6f9]
[Fri Feb  3 15:17:22 2023] 8021q: adding VLAN 0 to HW filter on device eth1
[Fri Feb  3 15:17:22 2023] i40e 81:00.0 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.0: fw 8.5.67516 api 1.15 nvm 8.50 0x8000b6bb 1.3082.0
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.0: MAC address: 40:a6:b7:36:37:28
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.0: qs_avail=384 FD SB=1 lan_qs=32 lan_tc0=32 vf=32*4 vmdq=8*1, remaining=215
[Fri Feb  3 15:17:22 2023] BUG: kernel NULL pointer dereference, address: 0000000000000010
[Fri Feb  3 15:17:22 2023] #PF: supervisor read access in kernel mode
[Fri Feb  3 15:17:22 2023] #PF: error_code(0x0000) - not-present page
[Fri Feb  3 15:17:22 2023] PGD 0 P4D 0
[Fri Feb  3 15:17:22 2023] Oops: 0000 [#1] SMP NOPTI
[Fri Feb  3 15:17:22 2023] CPU: 16 PID: 849 Comm: connmand Tainted: G           OE     5.10.0-16-amd64 #1 Debian 5.10.127-2
[Fri Feb  3 15:17:22 2023] Hardware name: Dell Inc. PowerEdge R7525/0YHMCJ, BIOS 2.9.3 08/05/2022
[Fri Feb  3 15:17:22 2023] RIP: 0010:i40e_setup_tx_descriptors+0x7/0xb0 [i40e]
[Fri Feb  3 15:17:22 2023] Code: 4c 89 e0 41 5c c3 83 c1 01 48 c1 e0 05 eb da ba 01 00 00 00 e8 aa fc ff ff 4c 89 e0 41 5c c3 0f 1f 40 00 0f 1f 44 00 00 55 53 <48> 8b 6f 10 48 85 ed 0f 84 95 00 00 00 48 83 7f 28 00 48 89 fb 75
[Fri Feb  3 15:17:22 2023] RSP: 0018:ffffb758075c7bd8 EFLAGS: 00010246
[Fri Feb  3 15:17:22 2023] RAX: ffff92ad02084200 RBX: ffff92a74297d000 RCX: 0000000000000000
[Fri Feb  3 15:17:22 2023] RDX: 000000000000000c RSI: 0000000006000000 RDI: 0000000000000000
[Fri Feb  3 15:17:22 2023] RBP: 0000000000000000 R08: 0000000000000218 R09: ffff92ac16e4c620
[Fri Feb  3 15:17:22 2023] R10: ffffb758075c7c60 R11: 0000000000000100 R12: ffff92a74297d000
[Fri Feb  3 15:17:22 2023] R13: 0000000000000000 R14: 0000000000000001 R15: 0000000000000000
[Fri Feb  3 15:17:22 2023] FS:  00007f0763cbb9c0(0000) GS:ffff92afff800000(0000) knlGS:0000000000000000
[Fri Feb  3 15:17:22 2023] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[Fri Feb  3 15:17:22 2023] CR2: 0000000000000010 CR3: 0000001084ba6000 CR4: 0000000000350ee0
[Fri Feb  3 15:17:22 2023] Call Trace:
[Fri Feb  3 15:17:22 2023]  ? i40e_vsi_setup_tx_resources+0x26/0x90 [i40e]
[Fri Feb  3 15:17:22 2023]  ? i40e_vsi_open+0x32/0x2d0 [i40e]
[Fri Feb  3 15:17:22 2023]  ? i40e_open+0x6b/0x120 [i40e]
[Fri Feb  3 15:17:22 2023]  ? __dev_open+0xea/0x1a0
[Fri Feb  3 15:17:22 2023]  ? __dev_change_flags+0x1da/0x250
[Fri Feb  3 15:17:22 2023]  ? dev_change_flags+0x21/0x60
[Fri Feb  3 15:17:22 2023]  ? devinet_ioctl+0x641/0x810
[Fri Feb  3 15:17:22 2023]  ? tomoyo_path_number_perm+0x66/0x1d0
[Fri Feb  3 15:17:22 2023]  ? inet_ioctl+0x18c/0x1d0
[Fri Feb  3 15:17:22 2023]  ? sock_do_ioctl+0x38/0x130
[Fri Feb  3 15:17:22 2023]  ? sock_ioctl+0x240/0x3b0
[Fri Feb  3 15:17:22 2023]  ? __x64_sys_ioctl+0x83/0xb0
[Fri Feb  3 15:17:22 2023]  ? do_syscall_64+0x33/0x80
[Fri Feb  3 15:17:22 2023]  ? entry_SYSCALL_64_after_hwframe+0x44/0xa9
[Fri Feb  3 15:17:22 2023] Modules linked in: i40e(OE+) pf_ring(OE) nfsd auth_rpcgss nfs_acl lockd grace md4 sha512_ssse3 sha512_generic cmac nls_utf8 cifs libarc4 dns_resolver fscache libdes joydev amd64_edac_mod edac_mce_amd amd_energy kvm_amd kvm irqbypass ghash_clmulni_intel rapl pcspkr dell_smbios dcdbas dell_wmi_descriptor wmi_bmof 8021q garp stp mrp llc bluetooth iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 jitterentropy_rng nf_defrag_ipv4 drbg iptable_mangle aes_generic aesni_intel crypto_simd cryptd glue_helper ansi_cprng ecdh_generic rfkill ecc iptable_filter libaes binfmt_misc ccp sg rng_core sp5100_tco watchdog k10temp ipmi_ssif acpi_ipmi ipmi_si ipmi_devintf ipmi_msghandler acpi_power_meter evdev acpi_cpufreq sunrpc fuse configfs ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c crc32c_generic raid1 raid0 multipath linear md_mod hid_generic usbhid hid sd_mod t10_pi crc_t10dif crct10dif_generic
[Fri Feb  3 15:17:22 2023]  mgag200 i2c_algo_bit drm_kms_helper ahci cec libahci xhci_pci crct10dif_pclmul crct10dif_common libata xhci_hcd crc32_pclmul crc32c_intel tg3 drm megaraid_sas libphy usbcore scsi_mod ptp pps_core i2c_piix4 usb_common wmi button [last unloaded: pf_ring]
[Fri Feb  3 15:17:22 2023] CR2: 0000000000000010
[Fri Feb  3 15:17:22 2023] ---[ end trace e2cfdefc69a54984 ]---
[Fri Feb  3 15:17:22 2023] RIP: 0010:i40e_setup_tx_descriptors+0x7/0xb0 [i40e]
[Fri Feb  3 15:17:22 2023] Code: 4c 89 e0 41 5c c3 83 c1 01 48 c1 e0 05 eb da ba 01 00 00 00 e8 aa fc ff ff 4c 89 e0 41 5c c3 0f 1f 40 00 0f 1f 44 00 00 55 53 <48> 8b 6f 10 48 85 ed 0f 84 95 00 00 00 48 83 7f 28 00 48 89 fb 75
[Fri Feb  3 15:17:22 2023] RSP: 0018:ffffb758075c7bd8 EFLAGS: 00010246
[Fri Feb  3 15:17:22 2023] RAX: ffff92ad02084200 RBX: ffff92a74297d000 RCX: 0000000000000000
[Fri Feb  3 15:17:22 2023] RDX: 000000000000000c RSI: 0000000006000000 RDI: 0000000000000000
[Fri Feb  3 15:17:22 2023] RBP: 0000000000000000 R08: 0000000000000218 R09: ffff92ac16e4c620
[Fri Feb  3 15:17:22 2023] R10: ffffb758075c7c60 R11: 0000000000000100 R12: ffff92a74297d000
[Fri Feb  3 15:17:22 2023] R13: 0000000000000000 R14: 0000000000000001 R15: 0000000000000000
[Fri Feb  3 15:17:22 2023] FS:  00007f0763cbb9c0(0000) GS:ffff92afff800000(0000) knlGS:0000000000000000
[Fri Feb  3 15:17:22 2023] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[Fri Feb  3 15:17:22 2023] CR2: 0000000000000010 CR3: 0000001084ba6000 CR4: 0000000000350ee0
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.0: Enabling symmetric hash (HSYM)
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.0: PCI-Express: Speed 8.0GT/s Width x8
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.0: Features: PF-id[0] VFs: 32 VSIs: 34 QP: 32 RSS FD_ATR FD_SB NTUPLE CloudF VxLAN Geneve NVGRE PTP VEPA
[Fri Feb  3 15:17:22 2023] i40e 81:00.1 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:22 2023] i40e 81:00.1 Core and Global modules ready 0
[Fri Feb  3 15:17:22 2023] i40e 81:00.1 i40e_set_mac_type found mac: 1, returns: 0
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.1: fw 8.5.67516 api 1.15 nvm 8.50 0x8000b6bb 1.3082.0
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.1: MAC address: 40:a6:b7:36:37:29
[Fri Feb  3 15:17:22 2023] i40e 0000:81:00.1: qs_avail=384 FD SB=1 lan_qs=32 lan_tc0=32 vf=32*4 vmdq=8*1, remaining=215
![PF_8_4](https://user-images.githubusercontent.com/33222750/216569790-498f5b6a-471c-458f-929f-23a9f61f528f.PNG)

**Comment by vehere-ccu1** [comment]
Seems firmware issue.
