### ISSUE TITLE
undefined symbol: pcap_open_dead        (./libpfring.so.8.2.0)

### ISSUE THREAD

**Issue by Refraction0602** [ntop/PF_RING#858]
Hi, Team

root@localhost:/home/capture/PF_RING-8.2.0/userland/lib# ./configure && make
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking linux/net_tstamp.h usability... yes
checking linux/net_tstamp.h presence... yes
checking for linux/net_tstamp.h... yes
checking librdi.h usability... no
checking librdi.h presence... no
checking for librdi.h... no
checking for clock_gettime in -lrt... yes
checking for nl_handle_alloc in -lnl... no
checking for dlopen, dlsym in -ldl... yes
checking for nl_socket_alloc in -lnl-3... no
checking PF_RING AF_XDP support... no
configure: creating ./config.status
config.status: creating lib/Makefile
config.status: creating lib/pfring_config
config.status: creating examples/Makefile
config.status: creating examples_zc/Makefile
config.status: creating examples_ft/Makefile
config.status: creating c++/Makefile
config.status: creating nbpf/Makefile
config.status: creating wireshark/extcap/Makefile
config.status: creating lib/config.h
make -C ../nbpf
make[1]: Entering directory '/home/capture/PF_RING-8.2.0/userland/nbpf'
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o nbpf_mod_rdif.o nbpf_mod_rdif.c
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o rules.o rules.c
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o tree_match.o tree_match.c
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o parser.o parser.c
bison -d grammar.y
lex scanner.l
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o lex.yy.o lex.yy.c
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o grammar.tab.o grammar.tab.c
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o nbpf_mod_fiberblaze.o nbpf_mod_fiberblaze.c
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -c -o nbpf_mod_napatech.o nbpf_mod_napatech.c
ar rs libnbpf.a nbpf_mod_rdif.o rules.o tree_match.o parser.o lex.yy.o grammar.tab.o nbpf_mod_fiberblaze.o nbpf_mod_napatech.o
ar: creating libnbpf.a
ranlib libnbpf.a
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -g nbpftest.c -o nbpftest  libnbpf.a `../lib/pfring_config --libs` -lpthread -lm 
make[1]: Leaving directory '/home/capture/PF_RING-8.2.0/userland/nbpf'
ar x ../nbpf/libnbpf.a
cp ../nbpf/nbpf.h .
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring.c -o pfring.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_mod.c -o pfring_mod.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_utils.c -o pfring_utils.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_mod_stack.c -o pfring_mod_stack.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_hw_filtering.c -o pfring_hw_filtering.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_hw_timestamp.c -o pfring_hw_timestamp.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_mod_sysdig.c -o pfring_mod_sysdig.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_mod_pcap.c -o pfring_mod_pcap.o
gcc -O2  -Wall -Wno-stringop-truncation -Wno-address-of-packed-member -fPIC -I../../kernel -I../libpcap-1.9.1         -D ENABLE_BPF -D ENABLE_HW_TIMESTAMP      -c pfring_device.c -o pfring_device.o
=*= making library libpfring.a =*=
ar rs libpfring.a pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o pfring_mod_pcap.o pfring_device.o             `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '`
ar: creating libpfring.a
ranlib libpfring.a
=*= making library libpfring.so =*=
gcc -Wl,-soname,libpfring.so.8 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o pfring_mod_pcap.o pfring_device.o             `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl     -o libpfring.so.8.2.0
=*= making library libpfring_min.so =*=
gcc -Wl,-soname,libpfring_min.so.8 -g -shared pfring.o pfring_mod.o pfring_utils.o pfring_mod_stack.o pfring_hw_filtering.o pfring_hw_timestamp.o pfring_mod_sysdig.o pfring_mod_pcap.o pfring_device.o            `ar t ../nbpf/libnbpf.a | grep -F .o | tr '\n' ' '` -lpthread  -lrt -ldl     -o libpfring_min.so.8.2.0

**Compile successfully, but there are some issues with libpfring.so:**
root@localhost:/home/capture/PF_RING-8.2.0/userland/lib# ldd -r libpfring.so.8.2.0 
        linux-vdso.so.1 (0x0000ffff8668a000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff865e7000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffff865d2000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff86479000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff8665f000)
undefined symbol: pcap_compile_nopcap   (./libpfring.so.8.2.0)
undefined symbol: pcap_setfilter        (./libpfring.so.8.2.0)
undefined symbol: pcap_next     (./libpfring.so.8.2.0)
undefined symbol: pcap_get_selectable_fd        (./libpfring.so.8.2.0)
undefined symbol: pcap_close    (./libpfring.so.8.2.0)
undefined symbol: pcap_stats    (./libpfring.so.8.2.0)
undefined symbol: pcap_open_dead        (./libpfring.so.8.2.0)
undefined symbol: pcap_next_ex  (./libpfring.so.8.2.0)
undefined symbol: pcap_open_offline     (./libpfring.so.8.2.0)
undefined symbol: pcap_compile  (./libpfring.so.8.2.0)
undefined symbol: pcap_freecode (./libpfring.so.8.2.0)
undefined symbol: pcap_open_live        (./libpfring.so.8.2.0)
undefined symbol: bpf_filter    (./libpfring.so.8.2.0)

Can you give me some advice？Thanks.

**Comment by cardigliano** [comment]
I suggest to move to latest stable (8.4) and check if the issue is still reproducible

**Comment by Refraction0602** [comment]
@cardigliano Thanks for your advice. 

**But there are still the same problems:**
root@localhost:/home/capture/PF_RING-8.4.0/userland/lib# ldd -r libpfring.so.8.4.0 
        linux-vdso.so.1 (0x0000ffffbeb47000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffbeaa4000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffbea8f000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffbe936000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffbeb1c000)
undefined symbol: pcap_compile_nopcap   (./libpfring.so.8.4.0)
undefined symbol: pcap_setfilter        (./libpfring.so.8.4.0)
undefined symbol: pcap_next     (./libpfring.so.8.4.0)
undefined symbol: pcap_get_selectable_fd        (./libpfring.so.8.4.0)
undefined symbol: pcap_close    (./libpfring.so.8.4.0)
undefined symbol: pcap_stats    (./libpfring.so.8.4.0)
undefined symbol: pcap_open_dead        (./libpfring.so.8.4.0)
undefined symbol: pcap_next_ex  (./libpfring.so.8.4.0)
undefined symbol: pcap_open_offline     (./libpfring.so.8.4.0)
undefined symbol: pcap_compile  (./libpfring.so.8.4.0)
undefined symbol: pcap_freecode (./libpfring.so.8.4.0)
undefined symbol: pcap_open_live        (./libpfring.so.8.4.0)
undefined symbol: bpf_filter    (./libpfring.so.8.4.0)

Do I need to do anything before compiling？

**Comment by cardigliano** [comment]
Did you try to compile an application (e.g. the examples), linking pf_ring and libpcap?

**Comment by Refraction0602** [comment]
> Did you try to compile an application (e.g. the examples), linking pf_ring and libpcap?

Yes, I've tried.
An error occurs when the **pfring_set_bpf_filter()** is called

target/debug/pfring_test: symbol lookup error: /usr/local/lib/libpfring.so: undefined symbol: pcap_open_dead

**Comment by cardigliano** [comment]
Are you able to compile and run pfcount in examples? Example:

~/PF_RING/userland/examples$ sudo ./pfcount -i eno1 -f "port 80"

**Comment by Refraction0602** [comment]
@cardigliano Now I know the reason, I only linked pf_ring, not include libpcap. The problem is solved when both are linked.
