### ISSUE TITLE
Cannot install on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by ns-vpanfilov** [ntop/PF_RING#859]
Getting an error message when installing on Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1011-aws x86_64)

```
=======================================
sudo apt-get -y install pfring-dkms
=======================================
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pfring-dkms : Depends: pfring (= 8.5.0-8132) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

=======================================
sudo apt-get -y install pfring
=======================================
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pfring : Depends: ndpi (= 4.7.0-4121) but 4.7.0-4122 is to be installed
          Recommends: pfring-dkms (= 8.5.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by ns-vpanfilov** [comment]
I think the issue is with hard-coded versions in https://packages.ntop.org/apt/20.04/x64/Packages

It has conflicting entries in different places: 
```
Depends: ndpi (= 4.7.0-4121), net-tools, kmod, ethtool, pciutils
Depends: ndpi (= 4.7.0-4122)
```

**Comment by Alestor** [comment]
Similar issue on Debian 11:

```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
apt install pfring
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pfring : Depends: ndpi (= 4.7.0-4122) but 4.6.0-4122 is to be installed
          Recommends: pfring-dkms (= 8.4.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by cardigliano** [comment]
@ns-vpanfilov could you retry now? (dev packages)
@Alestor we are checking the stable branch

**Comment by iangandon** [comment]
Same issue for CENTOS (found during an attempted NTOP upgrade):


 ` yum install pfring
Last metadata expiration check: 0:10:26 ago on Tue 14 Feb 2023 11:09:28 GMT.
Package pfring-7.8.0-3334.x86_64 is already installed.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64`

**Comment by atbohmer** [comment]
Same issue for RH 8.7, installed flawless yesterday but today an update fails:
...
 Problem 1: conflicting requests
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64
 Problem 2: package pfring-dkms-8.4.0.8133-8133.noarch requires pfring = 8.4.0-8133, but none of the providers can be installed
  - conflicting requests
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64
 Problem 3: package ntopng-5.6.230214-19544.x86_64 requires pfring = 8.4.0-8133, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64
 Problem 4: package nprobe-10.2.230214-7987.x86_64 requires pfring = 8.4.0-8133, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64
 Problem 5: package n2disk-3.6.230214-5278.x86_64 requires pfring = 8.4.0-8133, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64
 Problem 6: package cento-1.18.230214-775.x86_64 requires pfring = 8.4.0-8133, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides ndpi = 4.7.0-4122 needed by pfring-8.4.0-8133.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by atbohmer** [comment]
Seems just released pfring 8.4.0-8135 solves it!

**Comment by cardigliano** [comment]
Great. As soon as @ns-vpanfilov confirm this we can close the issue.

**Comment by ns-vpanfilov** [comment]
confirmed it is working now
