### ISSUE TITLE
when use pfsend with -b or -t will destroy the original pcap

### ISSUE THREAD

**Issue by powerxly** [ntop/PF_RING#860]
pf_ring version:  8.2.0
When I use pfsend -b or pfsend -t, these two command will change the right Protocol Type to a wrong Protocol Type.
my commond：
`pfsend -i zc:ens192 -n 200 -b -f test1.pcap
`
before using pfsend -b or pfsend -t:
Protocol Type addr (0x6558)
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/17894031/218948455-5373818c-c491-4563-94b0-94234b1fdab6.png">

after using pfsend -b or pfsend -t:
Protocol Type addr (0x5865)
<img width="2474" alt="image" src="https://user-images.githubusercontent.com/17894031/218948231-2e7a3ce1-6ff1-4e40-aebb-8bfc6579bae1.png">

**Comment by cardigliano** [comment]
@powerxly this is strange as the PCAP is read through libpcap and this should be read only. We will investigate.

**Comment by cardigliano** [comment]
@powerxly this looks weird as pfsend should not modify the PCAP file in any case. It reads it through the libpcap API, and I also run some test to make sure this does not happen. I suggest anyway to update to latest dev or stable and try to reproduce it again. Thank you.
