### ISSUE TITLE
wrong statistic on zc interface

### ISSUE THREAD

**Issue by jolysoul127** [ntop/PF_RING#863]
Dear
pfcount has wrong traffic statistics on ZC interface, hope someone can help me. Thank you so much.
The problem :
1. Run pfcount on intel 10 Gb interface ( x710 chipset), the input traffic about  2 Gbps : 
`sudo ./pfcount -i zc:enp12s0f2`
Although this is a **10 Gb** interface (intel x710 chipset), pfcount statistics traffic up to **35 Gbps** and packets drop about 40%.
2. If running on a non-zc interface, the statistics are normal, the traffic is correct and there is no packet drop:
`sudo ./pfcount -i enp12s0f2`

System information :
AMD 5950x
64 GB RAM
OS Ubuntu 22.04
NIC: 4x10 Gbps intel x710 (driver i40e)
PF_RING Version : 8.5.0
![image](https://user-images.githubusercontent.com/7579502/222306671-3ab14684-27f5-4f59-a909-c02d03072691.png)

**Comment by cardigliano** [comment]
@jolysoul127 this is strange, definitely not a known bug. Any chance you can provide access to the machine to debug this? Please drop an email to cardigliano at ntop.org in case. Thank you.

**Comment by jolysoul127** [comment]
@cardigliano First of all, thank you for your support.
Due to the IP restriction policy, it is not possible to directly access to the faulty machine. 
But you can remote into my PC via Anydesk or Teamviewer to control the faulty machine.
Which remote desktop software do you prefer to use? Anydesk or Teamviewer?
Thank you

**Comment by jolysoul127** [comment]
@cardigliano 
you're absolutely right. The cause of the error is not turning off the IOMMU with the AMD CPU.
Thank you so much
