### ISSUE TITLE
ixgbe-5.5.3-zc： remove -DDISABLE_PACKET_SPLIT  will get bad package

### ISSUE THREAD

**Issue by jiongge** [ntop/PF_RING#868]
If I remove -DDISABLE_PACKET_SPLIT from /drivers/intel/ixgbe/ixgbe-5.5.3-zc/src/makefile,  CFLAGS_EXTRA += -DHAVE_PF_RING -DIXGBE_NO_HW_RSC -DDISABLE_PACKET_SPLIT ${DEBUG_CFLAGS} , The packet content received in the background of the packet sent by RING 8.4.0 is incomplete or different from the sent packet content. Because I want to use XDP at the same time, i have to remove -DDISABLE_PACKET_SPLIT to use XDP

**Comment by cardigliano** [comment]
The -DDISABLE_PACKET_SPLIT is mandatory for using ZC drivers due to design choices in the zero-copy drivers.
