### ISSUE TITLE
PF 8.4 showing drops after 10 days since zbalance_ips starts 

### ISSUE THREAD

**Issue by vehere-ccu1** [ntop/PF_RING#875]
I have a server with 2 x 16 cores, where 2 x 2P Intel 100G 810-C cards and 5 x 4P X710  Intel cards. Multiple instance of balancer is running. Total ingress bandwidth is 220 Gbps received from 100G ports and forwarded/distributed through 20 egress ports (10G).
First 10 days there is zero drop but after 10 days I can see regular rx - drops even, I cant see changes in CPU usage.
LB's are bind with CPU 4,5,6,7,8,9 (Numa=0) and 20,21,22,23,24,25 (Numa=1).

![LB1-Setup](https://github.com/ntop/PF_RING/assets/33222750/ffc5ecd5-0a20-4d41-83a9-f3c58ce9a768)
![LB-1_CPU](https://github.com/ntop/PF_RING/assets/33222750/30e08654-0f6a-454b-9390-5ce7a10f5236)

**Comment by cardigliano** [comment]
@vehere-ccu1 at what stage of this "pipeline" is the system dropping traffic? Is it at the interface level, or application queues level? Could you provide some zbalance output to check this? (There is a -p option in zbalance_ipc to provide per-queue statistics)

**Comment by vehere-ccu1** [comment]
Drop is at Rx level (Interface).

**Comment by cardigliano** [comment]
Could you report some stats (bps/pps of ingress traffic vs drop rate)?

**Comment by vehere-ccu1** [comment]
![LB-Drop_stats](https://github.com/ntop/PF_RING/assets/33222750/e69938df-9b34-45e0-a2f4-8ea6c5232e15)

**Comment by vehere-ccu1** [comment]
It was due to another process, how was consuming all the physical memory. Thanks!
