### ISSUE TITLE
 ERROR: Unable to open PF_RING device any: Address family not supported by protocol [snaplen=1536]

### ISSUE THREAD

**Issue by red2thebones** [ntop/PF_RING#882]
I'm encountering this error on a fresh install - Ubuntu 22.04, kernel version 5.19. 
I have tried installing/reinstalling pfring-dkms and the rest of the packages, which all completed without any errors, but when I try to restart pf-ring, I get the error: "Failed to restart pf-ring.service: Unit pf-ring.service not found." and also when I do  sudo cat /proc/net/pf_ring/info , I get: "cat: /proc/net/pf_ring/info: No such file or directory"
Any pointers would be much appreciated. Thank  you.

**Comment by cardigliano** [comment]
@red2thebones please note the service name is pf_ring, not pf-ring
