### ISSUE TITLE
zbalance showing 1/2th bandwidth at rx even the rx drop is zero.

### ISSUE THREAD

**Issue by vehere-ccu1** [ntop/PF_RING#885]
Hi,

Ingress bandwidth is coming from CUBRO, I have other tools which is showing proper bandwidth but when I am trying to check the bandwidth at server with bzalance it is showing less rx bandwidth with zero drops.

I am using PF 8.4 with Intel 100G QSFP28 LR4, CPU usage and other this are normal.

**Comment by cardigliano** [comment]
Could you try with pfcount on the same interface and report the output of both pfcount and zbalance?

**Comment by vehere-ccu1** [comment]
Cubro is updating ethernet type 0x0800 for IPv6 packets in order to remove MPLS levels from the packets. The packets are being received by X520 but not 810C intel cards. Is there any way to to receive such packets in 810-C 100G/10G cards?
