### ISSUE TITLE
Compil to debian 11 kernel 5.10.0-26-amd64

### ISSUE THREAD

**Issue by channelsss** [ntop/PF_RING#889]
Hello,
I have an error after apt install ixgbe-zc-5.19.6.854 : 

root@wanfilter1:~$ pf_ringcfg --configure-driver ixgbe --rss-queues 1
[>] Installing PF_RING.ko
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                         
Hit:4 https://packages.ntop.org/apt/bookworm x64/ InRelease                                           
Hit:5 https://packages.ntop.org/apt/bookworm all/ InRelease
Hit:6 https://www.andrisoft.com/files/debian11 bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-compiler-gcc-12-x86 linux-headers-6.1.0-13-amd64 linux-headers-6.1.0-13-common linux-kbuild-6.1
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  dctrl-tools dkms linux-headers-amd64 sbsigntool sudo
Suggested packages:
  debtags menu
The following NEW packages will be installed:
  dctrl-tools dkms linux-headers-amd64 pfring-dkms sbsigntool sudo
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,376 kB of archives.
After this operation, 6,232 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian bullseye/main amd64 dctrl-tools amd64 2.24-3+b1 [104 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 dkms all 2.8.4-3 [78.2 kB] 
Get:3 http://deb.debian.org/debian bullseye/main amd64 linux-headers-amd64 amd64 5.10.197-1 [1,176 B]
Get:4 http://deb.debian.org/debian bullseye/main amd64 sbsigntool amd64 0.9.2-2 [63.5 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 sudo amd64 1.9.5p2-3+deb11u1 [1,061 kB]
Get:6 https://packages.ntop.org/apt/bookworm all/ pfring-dkms 8.7.0.8548 [68.4 kB]
Fetched 1,376 kB in 0s (7,025 kB/s)    
Selecting previously unselected package dctrl-tools.
(Reading database ... 82144 files and directories currently installed.)
Preparing to unpack .../0-dctrl-tools_2.24-3+b1_amd64.deb ...
Unpacking dctrl-tools (2.24-3+b1) ...
Selecting previously unselected package dkms.
Preparing to unpack .../1-dkms_2.8.4-3_all.deb ...
Unpacking dkms (2.8.4-3) ...
Selecting previously unselected package linux-headers-amd64.
Preparing to unpack .../2-linux-headers-amd64_5.10.197-1_amd64.deb ...
Unpacking linux-headers-amd64 (5.10.197-1) ...
Selecting previously unselected package sbsigntool.
Preparing to unpack .../3-sbsigntool_0.9.2-2_amd64.deb ...
Unpacking sbsigntool (0.9.2-2) ...
Selecting previously unselected package pfring-dkms.
Preparing to unpack .../4-pfring-dkms_8.7.0.8548_all.deb ...
Unpacking pfring-dkms (8.7.0.8548) ...
Selecting previously unselected package sudo.
Preparing to unpack .../5-sudo_1.9.5p2-3+deb11u1_amd64.deb ...
Unpacking sudo (1.9.5p2-3+deb11u1) ...
Setting up linux-headers-amd64 (5.10.197-1) ...
Setting up sudo (1.9.5p2-3+deb11u1) ...
Setting up sbsigntool (0.9.2-2) ...
Setting up dctrl-tools (2.24-3+b1) ...
Setting up dkms (2.8.4-3) ...
Setting up pfring-dkms (8.7.0.8548) ...
Loading new pfring-8.7.0.8548 DKMS files...
Building for 5.10.0-26-amd64
Building for architecture amd64
Building initial module for 5.10.0-26-amd64
Done.

pf_ring.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.0-26-amd64/updates/dkms/

depmod...

DKMS: install completed.
Created symlink /etc/systemd/system/multi-user.target.wants/pf_ring.service → /etc/systemd/system/pf_ring.service.
cluster is a disabled or a static unit not running, not starting it.
Processing triggers for man-db (2.11.2-2) ...
[>] Installing ixgbe Zero-Copy driver
Continue (y/n)?y
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease                              
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                                        
Hit:4 https://packages.ntop.org/apt/bookworm x64/ InRelease               
Hit:5 https://packages.ntop.org/apt/bookworm all/ InRelease
Hit:6 https://www.andrisoft.com/files/debian11 bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pfring-dkms is already the newest version (8.7.0.8548).
The following packages were automatically installed and are no longer required:
  linux-compiler-gcc-12-x86 linux-headers-6.1.0-13-amd64 linux-headers-6.1.0-13-common linux-kbuild-6.1
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  ixgbe-zc-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 397 kB of archives.
After this operation, 2,374 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.ntop.org/apt/bookworm all/ ixgbe-zc-dkms 5.19.6.8548 [397 kB]
Fetched 397 kB in 0s (1,792 kB/s)     
Selecting previously unselected package ixgbe-zc-dkms.
(Reading database ... 82423 files and directories currently installed.)
Preparing to unpack .../ixgbe-zc-dkms_5.19.6.8548_all.deb ...
Unpacking ixgbe-zc-dkms (5.19.6.8548) ...
Setting up ixgbe-zc-dkms (5.19.6.8548) ...
Loading new ixgbe-zc-5.19.6.8548 DKMS files...
Building for 5.10.0-26-amd64
Building for architecture amd64
Building initial module for 5.10.0-26-amd64
Error! Bad return status for module build on kernel: 5.10.0-26-amd64 (amd64)
Consult /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/make.log for more information.
dpkg: error processing package ixgbe-zc-dkms (--configure):
 installed ixgbe-zc-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 ixgbe-zc-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
[>] Configuring PF_RING
[>] Configuring hugepages
[>] Detecting interfaces using ixgbe
enp5s0
[>] Configuring ixgbe driver with 1 RSS queues
[>] Restarting PF_RING
[>] Configuration completed

root@wanfilter1:    cat /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/make.log
DKMS make.log for ixgbe-zc-5.19.6.8548 for kernel 5.10.0-26-amd64 (amd64)
Sun Oct  8 02:01:50 PM CEST 2023
cd /usr/src/pfring-8.7.0.8548/; make
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/pfring-8.7.0.8548'
make -C /lib/modules/5.10.0-26-amd64/build M=/usr/src/pfring-8.7.0.8548 EXTRA_CFLAGS='-I/usr/src/pfring-8.7.0.8548 -DGIT_REV="\"dev:657fc352fc8753674fdbea4aea8a58ec8982c6d2\"" -no-pie -fno-pie -Wno-implicit-fallthrough' modules
make[2]: Entering directory '/usr/src/linux-headers-5.10.0-26-amd64'
  CC [M]  /usr/src/pfring-8.7.0.8548/pf_ring.o
  MODPOST /usr/src/pfring-8.7.0.8548/Module.symvers
  CC [M]  /usr/src/pfring-8.7.0.8548/pf_ring.mod.o
  LD [M]  /usr/src/pfring-8.7.0.8548/pf_ring.ko
make[2]: Leaving directory '/usr/src/linux-headers-5.10.0-26-amd64'
make[1]: Leaving directory '/usr/src/pfring-8.7.0.8548'
cp /usr/src/pfring-8.7.0.8548/Module.symvers .
make -C /lib/modules/5.10.0-26-amd64/build M=/var/lib/dkms/ixgbe-zc/5.19.6.8548/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-26-amd64'
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_main.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_api.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_common.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_dcb.o
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_main.c: In function ‘ixgbe_configure_dcb’:
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_main.c:6427:4: error: implicit declaration of function ‘netif_set_tso_max_size’; did you mean ‘netif_set_gso_max_size’? [-Werror=implicit-function-declaration]
 6427 |    netif_set_tso_max_size(netdev, 65536);
      |    ^~~~~~~~~~~~~~~~~~~~~~
      |    netif_set_gso_max_size
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_dcb_82598.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_dcb_82599.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_lib.o
  CC [M]  /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_mbx.o
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.c:1755:14: warning: ‘struct kernel_ethtool_ringparam’ declared inside parameter list will not be visible outside of this definition or declaration
 1755 |       struct kernel_ethtool_ringparam __always_unused *ker,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.c:1778:14: warning: ‘struct kernel_ethtool_ringparam’ declared inside parameter list will not be visible outside of this definition or declaration
 1778 |       struct kernel_ethtool_ringparam __always_unused *ker,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_lib.c: In function ‘ixgbe_alloc_q_vector’:
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_lib.c:953:2: error: too few arguments to function ‘netif_napi_add’
  953 |  netif_napi_add(adapter->netdev, &q_vector->napi, ixgbe_poll);
      |  ^~~~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-26-common/include/net/inet_sock.h:19,
                 from /usr/src/linux-headers-5.10.0-26-common/include/net/ip.h:28,
                 from /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe.h:7,
                 from /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_lib.c:4:
/usr/src/linux-headers-5.10.0-26-common/include/linux/netdevice.h:2407:6: note: declared here
 2407 | void netif_napi_add(struct net_device *dev, struct napi_struct *napi,
      |      ^~~~~~~~~~~~~~
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.c:4951:20: error: initialization of ‘void (*)(struct net_device *, struct ethtool_ringparam *)’ from incompatible pointer type ‘void (*)(struct net_device *, struct ethtool_ringparam *, struct kernel_ethtool_ringparam *, struct netlink_ext_ack *)’ [-Werror=incompatible-pointer-types]
 4951 |  .get_ringparam  = ixgbe_get_ringparam,
      |                    ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.c:4951:20: note: (near initialization for ‘ixgbe_ethtool_ops.get_ringparam’)
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.c:4952:20: error: initialization of ‘int (*)(struct net_device *, struct ethtool_ringparam *)’ from incompatible pointer type ‘int (*)(struct net_device *, struct ethtool_ringparam *, struct kernel_ethtool_ringparam *, struct netlink_ext_ack *)’ [-Werror=incompatible-pointer-types]
 4952 |  .set_ringparam  = ixgbe_set_ringparam,
      |                    ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.c:4952:20: note: (near initialization for ‘ixgbe_ethtool_ops.set_ringparam’)
make[3]: *** [/usr/src/linux-headers-5.10.0-26-common/scripts/Makefile.build:291: /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_lib.o] Error 1
make[3]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.10.0-26-common/scripts/Makefile.build:291: /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_ethtool.o] Error 1
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.10.0-26-common/scripts/Makefile.build:291: /var/lib/dkms/ixgbe-zc/5.19.6.8548/build/ixgbe_main.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-26-common/Makefile:1856: /var/lib/dkms/ixgbe-zc/5.19.6.8548/build] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-26-common/Makefile:192: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-26-amd64'
make: *** [Makefile:43: all] Error 2
root@wanfilter1:~$

**Comment by cardigliano** [comment]
It seems ixgbe is compiling in our lab on the same OS (debian 11) and kernel version (5.10.0-26), I suggest to check the very latest update, otherwise we need to figure out what is making the difference.

**Comment by cardigliano** [comment]
I double checked also on another system, I confirm latest ixgbe driver (and after yesterday's update also all other drivers) is compiling on debian 11 with kernel 5.10.0-26
