### ISSUE TITLE
LibPcap-1.6.2-Ring Does Not Support VLAN Tag Filters

### ISSUE THREAD

**Issue by jwilczek** [ntop/PF_RING#89]
We are using tcpdump to facilitate a filtered network capture.  The running tcpdump instance is exposed to vlan tagged traffic.  In testing, we found that tcpdump (really libpcap) was not properly filtering vlan traffic (see [https://github.com/the-tcpdump-group/libpcap/issues/390](url)).

This issue was fixed in libpcap 1.7.0 and on (see [https://github.com/the-tcpdump-group/libpcap/pull/391](url)).

When testing with this version of libpcap we were noticing about a 5% packet drop during business hours.  As such, we thought we would look into PF_RING.  However, PF_RING appears to be using and older version of libpcap (libpcap-1.6.2-ring?).  In looking at the commit that addresses the vlan filtering issue (see [https://github.com/the-tcpdump-group/libpcap/commit/d8e39a9c306fe393a54029ca28693a63ab487e82](url)), it doesn't appear that the required code changes are that complex.

I would like to see these changes added to PF_RING, but I'm not sure how difficult this would be to do.  For example, is libpcap-1.6.2-ring the same as libpcap-1.6.2.  If so, then I think this would be a pretty easy fix.  If not, then I'm not sure where to start.

**Comment by cardigliano** [comment]
I backported the patch in our libpcap, please let us know if it is working for you, reopen the issue otherwise.

**Comment by cbboggs** [comment]
@cardigliano - Thanks, the patch worked!  vlan filtering now works properly when capturing from the interface, now with 0 packet loss thanks to pf_ring :)  

However, vlan filtering no longer works when staying in userland (i.e. when feeding tcpdump a pcap with -r).  Not sure why that would happen..   This isn't a major issue for me at the moment, as I have other non-pf_ring aware versions of tcpdump that work fine for this purpose, but thought I would let you know.  Appreciate the help!
