### ISSUE TITLE
PF-8.2.0 - ZC: Dell & HPE servers goes in hang state with variation in ingress traffic.

### ISSUE THREAD

**Issue by vehere-ccu1** [ntop/PF_RING#893]
We are using Debian 11 (5.10.0-16-amd64) in all the servers, and all of them has latest firmware,  PF-8.2.0 - ZC: Dell & HPE servers goes in hang state with variation in ingress traffic. We are using X710 & 4P 810 C. This is not happenings frequently but it happens while changing in the ingress traffic (Not physical cables). The ingress links are coming from Packet-brokers.

**Comment by cardigliano** [comment]
@vehere-ccu1 please note latest PF_RING stable version is 8.6.1, including new drivers, are you able to check it?

**Comment by vehere-ccu1** [comment]
Sure. thanks for quick reply. Hope, zc license for 8.2.0 will also work for 8.6.1.

**Comment by vehere-ccu1** [comment]
![image](https://github.com/ntop/PF_RING/assets/33222750/349fa36b-6f25-4800-925d-ba958fafabe0)

**Comment by vehere-ccu1** [comment]
8.6.1 giving compilation error.

**Comment by cardigliano** [comment]
@vehere-ccu1 it seems latest debian 11 has a more recent kernel, could you try updating it?

**Comment by vehere-ccu1** [comment]
Faced: ice driver load issue with PF-8.6.1 in kernel- 5.10.0-16-amd64

<img width="440" alt="image" src="https://github.com/ntop/PF_RING/assets/33222750/c47a2160-1c10-4e5a-9533-686a5889f32b">

**Comment by cardigliano** [comment]
@vehere-ccu1 we can support latest kernel only, please update (you should get 5.10.0-26)

**Comment by cardigliano** [comment]
Anyway please try loading the gnss module before loading the driver:

modprobe gnss

**Comment by vehere-ccu1** [comment]
With 8.6.0 & 8.6.1 it seems stable.

**Comment by cardigliano** [comment]
Thank you
