### ISSUE TITLE
i40e-zc (X710) crash with Suricata and Zeek on Rocky Linux 8.8

### ISSUE THREAD

**Issue by cardigliano** [ntop/PF_RING#895]
Kernel: 4.18.0-477.27.1.el8_8.x86_64

Running in demo mode - it crashes in a few minutes

dmesg:

[ 3133.392393] i40e 0000:5f:00.0 ens2f0: changing MTU from 1500 to 9000
[ 3133.446121] [PF_RING-ZC] i40e_down: detach ens2f0
[ 3133.446123] [PF_RING-ZC] i40e_down: detaching ens2f0 while in use
[ 3133.446124] [PF_RING] Removing ZC device ens2f0@0 [rx-ring=000000004ed26f41][tx-ring=00000000733c8e97]
[ 3133.446128] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446130] [PF_RING] Removing ZC device ens2f0@1 [rx-ring=00000000fa5dccba][tx-ring=0000000015cb25ee]
[ 3133.446131] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446131] [PF_RING] Removing ZC device ens2f0@2 [rx-ring=000000006978de49][tx-ring=00000000978b55af]
[ 3133.446132] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446133] [PF_RING] Removing ZC device ens2f0@3 [rx-ring=00000000d17d2f1c][tx-ring=000000000e667b82]
[ 3133.446134] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446135] [PF_RING] Removing ZC device ens2f0@4 [rx-ring=000000009a68d790][tx-ring=000000009a8fa747]
[ 3133.446136] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446137] [PF_RING] Removing ZC device ens2f0@5 [rx-ring=000000004b627413][tx-ring=00000000286dee29]
[ 3133.446138] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446139] [PF_RING] Removing ZC device ens2f0@6 [rx-ring=0000000058de7e62][tx-ring=00000000d71f538f]
[ 3133.446140] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.446141] [PF_RING] Removing ZC device ens2f0@7 [rx-ring=000000002e9010a1][tx-ring=0000000041702090]
[ 3133.446142] [PF_RING] Unloading ZC driver while the device is in use from userspace!!
[ 3133.449559] [PF_RING-ZC] i40e_up_complete: attach ens2f0 [pf start=3120562176 len=16777216][cache_line_size=64][MSIX enabled]
[ 3133.449562] [PF_RING] Registering ZC device ens2f0@0 [rx-ring=000000004ed26f41][tx-ring=00000000733c8e97] [ 3133.449568] [PF_RING] Registering ZC device ens2f0@1 [rx-ring=00000000fa5dccba][tx-ring=0000000015cb25ee] [ 3133.449569] [PF_RING] Registering ZC device ens2f0@2 [rx-ring=000000006978de49][tx-ring=00000000978b55af] [ 3133.449571] [PF_RING] Registering ZC device ens2f0@3 [rx-ring=00000000d17d2f1c][tx-ring=000000000e667b82] [ 3133.449573] [PF_RING] Registering ZC device ens2f0@4 [rx-ring=000000009a68d790][tx-ring=000000009a8fa747] [ 3133.449575] [PF_RING] Registering ZC device ens2f0@5 [rx-ring=000000004b627413][tx-ring=00000000286dee29] [ 3133.449577] [PF_RING] Registering ZC device ens2f0@6 [rx-ring=0000000058de7e62][tx-ring=00000000d71f538f] [ 3133.449579] [PF_RING] Registering ZC device ens2f0@7 [rx-ring=000000002e9010a1][tx-ring=0000000041702090] [ 3133.460063] list_del corruption. prev->next should be ffffac0b4e1cbca8, but was ffff9362c52d1350
[ 3133.460181] ------------[ cut here ]------------
[ 3133.460183] kernel BUG at lib/list_debug.c:53!
[ 3133.460195] list_del corruption. prev->next should be ffffac0b4e10bca8, but was ffff9362c52d7750
[ 3133.460235] invalid opcode: 0000 [#1] SMP NOPTI
[ 3133.460336] ------------[ cut here ]------------
[ 3133.460368] CPU: 87 PID: 5160 Comm: W#01-zc:e..f0@4 Kdump: loaded Tainted: G
4.18.0-477.27.1.el8_8.x86_64 #1
[ 3133.460413] kernel BUG at lib/list_debug.c:53!
[ 3133.460531] Hardware name: XIT XZ, BIOS 2.16.1 08/17/2022
[ 3133.460576] RIP: 0010:__list_del_entry_valid.cold.1+0x34/0x48
IOE    --------- -  -

[ 3133.460597] Code: 7f d3 a1 e8 da cb c7 ff 0f 0b 48 c7 c7 88 80 d3 a1 e8 cc cb c7 ff 0f 0b 48 89 f2 48 89 fe 48 c7
c7 48 80 d3 a1 e8 b8 cb c7 ff <0f> 0b 48 89 fe 48 c7 c7 10
[ 3133.460644] RSP: 0018:ffffac0b4e1cba98 EFLAGS: 00010046
[ 3133.460660] RAX: 0000000000000054 RBX: ffffac0b4e1cbc90
[ 3133.460680] RDX: 0000000000000000 RSI: ffff93a17fade698
[ 3133.460699] RBP: ffff9362c52d1348 R08: 0000000000000000
[ 3133.460717] R10: 0000000000000001 R11: ffffac0b4e1cb8b8
[ 3133.460736] R13: ffffac0b4e1cbc80 R14: 0000000000000001
[ 3133.460755] FS: 00007ff433b0a700(0000) GS:ffff93a17fac0000(0000) knlGS:0000000000000000 [ 3133.460775] CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3133.460791] CR2: 00007ff428722408 CR3: 00000020f4d46003 CR4: [ 3133.460810] DR0: 0000000000000000 DR1: 0000000000000000 DR2: [ 3133.460829] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: [ 3133.460848] PKRU: 55555554
[ 3133.460857] Call Trace:
[ 3133.460867] remove_wait_queue+0x20/0x60
[ 3133.460885] poll_freewait+0x3d/0xa0
[ 3133.460898] do_sys_poll+0x316/0x570
[ 3133.460910] ? update_load_avg+0x7e/0x710
[ 3133.460925] ? prep_new_page+0x92/0x100
[ 3133.460940] ? get_page_from_freelist+0x1128/0x1370
[ 3133.460956] ? __switch_to+0x10c/0x450
[ 3133.460969] ? compat_poll_select_copy_remaining+0x150/0x150 [ 3133.460986] ? _cond_resched+0x15/0x30
[ 3133.461000] ? __alloc_pages_nodemask+0x166/0x330
[ 3133.461016] ? __mod_memcg_lruvec_state+0x4a/0xc0
[ 3133.461033] ? __mod_lruvec_page_state+0x5e/0x80
[ 3133.461046] ? page_add_new_anon_rmap+0x4b/0xe0
[ 3133.461063] ? handle_pte_fault+0x484/0x880
[ 3133.461075] ? seccomp_run_filters+0x77/0x130
[ 3133.461090] ? __handle_mm_fault+0x453/0x6c0
[ 3133.461103] ? __seccomp_filter+0x3e/0x4b0
[ 3133.461119] ? __audit_syscall_entry+0xf2/0x140
[ 3133.461133] ? ktime_get_ts64+0x50/0xf0
[ 3133.461147] __x64_sys_poll+0xa0/0x130
[ 3133.461160] do_syscall_64+0x5b/0x1b0
[ 3133.461467] entry_SYSCALL_64_after_hwframe+0x61/0xc6
[ 3133.461689] RIP: 0033:0x7ff449a82251
00000000007706e0
0000000000000000
0000000000000400
80 d3 a1 e8 a7 cb c7 ff 0f 0b 90 48 85
RCX: 0000000000000000
RDI: ffff93a17fade698
R09: c0000000ffff7fff
R12: 0000000000000282
R15: ffffac0b4e1cbb64

[ 3133.461833] Code: 00 41 54 41 89 d4 55 48 89 f5 53 48 89 fb 48 83 ec 10 e8 82 ff ef ff 44 89 e2 48 89 ee 48 89 df 41 89 c0 b8 07 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 31 44 89 c7 89 44 24 0c e8 bb ff ef ff 8b 44
[ 3133.462144] RSP: 002b:00007ff433b098b0 EFLAGS: 00000293 ORIG_RAX: 0000000000000007
[ 3133.462297] RAX: ffffffffffffffda RBX: 00007ff433b098e8 RCX: 00007ff449a82251
[ 3133.462450] RDX: 0000000000000033 RSI: 0000000000000001 RDI: 00007ff433b098e8
[ 3133.462599] RBP: 0000000000000001 R08: 0000000000000000 R09: 00000000fffffffe
[ 3133.462745] R10: 00005637edd879a0 R11: 0000000000000293 R12: 0000000000000033
[ 3133.462893] list_del corruption. prev->next should be ffffac0b4e1fbca8, but was ffff9362c52d5b50 [ 3133.462910] R13: 00007ff433b09a28 R14: 00007ff433b09930 R15: 00007ff433b09a50
[ 3133.462912] Modules linked in:
[ 3133.463097] ------------[ cut here ]------------
[ 3133.463263] i40e_zc(OE)
[ 3133.463422] kernel BUG at lib/list_debug.c:53!
[ 3133.463582] nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct vxlan ip6_udp_tunnel nf_tables_set udp_tunnel uio pf_ring(OE) nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables libcrc32c nfnetlink intel_rapl_msr intel_rapl_common intel_uncore_frequency intel_uncore_frequency_common isst_if_common skx_edac nfit libnvdimm x86_pkg_temp_thermal intel_powerclamp coretemp ipmi_ssif kvm_intel kvm irqbypass dell_smbios crct10dif_pclmul crc32_pclmul iTCO_wdt dell_wmi_descriptor wmi_bmof iTCO_vendor_support ghash_clmulni_intel rapl intel_cstate intel_uncore acpi_ipmi mei_me pcspkr joydev mei i2c_i801 lpc_ich ipmi_si wmi ipmi_devintf ipmi_msghandler acpi_power_meter vfat fat ext4 mbcache jbd2 sr_mod cdrom sd_mod t10_pi sg mgag200 drm_shmem_helper drm_kms_helper syscopyarea sysfillrect sysimgblt ahci fb_sys_fops libahci drm megaraid_sas igb libata crc32c_intel dca i2c_algo_bit dm_mirror dm_region_hash dm_log
[ 3133.463942] dm_mod [last unloaded: i40e]

**Comment by fandigunawan** [comment]
Your questions on Discord:

1. Does it happen after 5 minutes or before?
>> It happended before 5 minutes.
2. Did you change the MTU to 9000?
>> I did not change the MTU when application running. Did PF_RING change MTU when application running using ZC? I suspected that there are other thing interfiring e.g. NetworkManager if PF_RING set MTU automatically.

**Comment by cardigliano** [comment]
@fandigunawan did you try updating and checking latest driver revision?

**Comment by fandigunawan** [comment]
Hi @cardigliano I have updated to 8.6.1-8656 and it is okay.

**Comment by cardigliano** [comment]
Thank you
