### ISSUE TITLE
pf_ringcfg with Broadcom NIC on ROCKY 9.3 NOT WORKING

### ISSUE THREAD

**Issue by jrp999** [ntop/PF_RING#899]
I followed this guide and install PF_RING on ROCKY 9.3:

`https://packages.ntop.org/centos-stable/`

I do not have a license for ZC and did not add that package.

I then referenced this guide to get PF_RING working:

`https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html`

these are the interfaces on the system I am working on:

```
# pf_ringcfg --list-interfaces
Name: enp1s0               Driver: tg3        RSS:     1    [Linux Driver] 
Name: enp2s0               Driver: tg3        RSS:     1    [Linux Driver] 
Name: eno1                 Driver: e1000e     RSS:     1    [Supported by ZC]
```

```
01:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5751 Gigabit Ethernet PCI Express (rev 21)
02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5751 Gigabit Ethernet PCI Express (rev 21)

```

eno1 is the management interface whereas the other 2 interfaces are my capture ports

When I try to configure one of my capture ports I get this error:

```
# pf_ringcfg --configure-driver tg3 --rss-queues 1
Please provide a supported driver with --configure-driver <name> (please check --list-zc-drivers)
```

This article indicates that tg3 (Broadcomm) should work with the Linux Driver:

`https://github.com/ntop/PF_RING/issues/110`

Can someone please assist me in getting PF_RING configured on my system?

Thanx!

**Comment by cardigliano** [comment]
@jrp999 please note in case of Broadcom (as well as all adapters not supported by ZC) there is no need to use the pf_ringcfg script to configure the adapter. Just use it with -i enp2s0
