### ISSUE TITLE
PF_RING and shaping

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#90]
Is PF_RING compatible with htb or any other shaping discipline?
Is any way to shaping (or policing) outgoing traffic sent by program who uses a zero copy driver?

**Comment by cardigliano** [comment]
Hi
we use traffic shaping with pf_ring in some applications (e.g. ntopng), thus it is definitely feasible,
we are thinking to add shaping support to ZC queues in the roadmap, I guess this is a +1 for you.

Alfredo

**Comment by Skryabind** [comment]
Adding shaping support to ZC queues would be great. 
Must I realize a shaping in my app manually, or there are any libraries/modules for it?

**Comment by cardigliano** [comment]
There are a few libraries on internet, our components are not publicly available atm, we will add ZC support soon so that you can use it.

Alfredo

**Comment by Skryabind** [comment]
Thank you.
