### ISSUE TITLE
PF_RING 8.6.1 with ixgbe device no long can set the size of receive and transmit queues

### ISSUE THREAD

**Issue by pieter-winter** [ntop/PF_RING#900]
We noticed that after updating to 8.6.1 of PF_RING (from an older 7.6 I believe) the ethtool -G for setting the number of receive and transmit queues did no longer work for the ixgbe device.

The 8.6.1 version of PF_RING contains 5.19.6 version of the ixgbe driver. In the ixgbe.h file drivers/intel/ixgbe/ixgbe-5.19.6-zc/src/ixgbe.h the IXGBE_MAX_NUM_DESCRIPTORS is set to 4096. In an earlier version of the driver this "seems" to have been called IXGBE_MAX_TXD and this was (when PF_RING is used) increased to 32768

It seems there is a relation. My question is: is this observation an omission in the driver modification for PF_RING, or is this as expected but not removed properly. I noticed that the "driver specific" load_device script still uses 32768. The pfring_ctl tries to set the size to the maximum (which odd enough is set to 8192 but cannot be changed to anything else).

**Comment by cardigliano** [comment]
Fixed in 631b4488ca89f4810701010c12a8da5a0e7e59d4
Thank you for reporting
