### ISSUE TITLE
pfring_zc_send_pkt_multi seems to always return 0 when the pfring_zc_pkt_buff->len = 0

### ISSUE THREAD

**Issue by bas-k** [ntop/PF_RING#903]
When you want to use the `pfring_zc_multi_queue` only for transferring information in the `pfring_zc_pkt_buff->user` data which means the `pfring_zc_pkt_buff->len = 0`, the `pfring_zc_send_pkt_multi `will always **return 0**, but the packet is actually added to the multi queue. Using `pfring_zc_pkt_buff->len = 1` the returned value is correct. 

This issue did not exist in the 7.6.0 version and was introduced in the 7.8.0 version and still exists in the 8.6.1 version of PF_RING.

**Comment by cardigliano** [comment]
I pushed a new library to the dev branch (8.7) with a fix for this, please check if it works in your case. Thank you.

**Comment by bas-k** [comment]
Thanks for the support. I've done a test with the dev branch and all seems to work ok again. Thank you
