### ISSUE TITLE
Drivers compile fails with several "implicit-function-declaration" errors on kernel 6.6.8

### ISSUE THREAD

**Issue by dlk3** [ntop/PF_RING#904]
I am trying to compile PF_RING on Fedora 39, which has kernel 6.6.9.  I get three implicit_function_declaration errors in e1000e-3.8.7-zc/src/netdev.c, for "e1000e_hwtstamp_get", "pci_enable_pcie_error_reporting", and "pci_disable_pcie_error_reporting’.   I found "e100e_hwtstamp_get" function in the netdev.c on [Torvalds' Linux Github repo](https://github.com/torvalds/linux/blob/master/drivers/net/ethernet/intel/e1000e/netdev.c).  I couldn't find the other function definitionss anywhere.

From reading other bug reports here I suspect that the answer will be that you don't support the 6.6.9 kernel yet.  Still, I thought I should pass this along.  I have attached a full log of my PF_RING make, FWIW:  [make.log](https://github.com/ntop/PF_RING/files/13936056/make.log)

**Comment by cardigliano** [comment]
@dlk3 as you noticed this kernel is not officially supported, however we do our best to support all the kernels. Thank you for reporting.

**Comment by incapdns** [comment]
@cardigliano Which is the latest kernel supported ?

**Comment by cardigliano** [comment]
@incapdns we officially support latest kernels shipped with Ubuntu LTS, Rocky Linux, Debian

**Comment by cardigliano** [comment]
Kernel up to 6.8 (ubuntu 24) is now supported
