### ISSUE TITLE
pfring_recv doesn't receive only big UDP packets

### ISSUE THREAD

**Issue by rmbq** [ntop/PF_RING#905]
Hi!
I'm using vanilla pf_ring 8.7 @ e499765ba985e377c828265d6a67640032f3f477
In my application i open a ring with 6 interfaces as device_name.
Every interface receive:
- 11 62KB packets every 350milliseconds. So 66 62K packets on the ring every 350mS.
- few smaller packets, something like 10 80B and 10 250B

After 15 seconds `pfring_recv` stops receiveing 62KB packets but keeps receiveing smaller packets. Rarely some 62KB pkt is received.
If I disconnect from 2 of 6 interfaces, `pfring_recv` returns to work normally.
In stats (/proc/net/pf_ring/) the isn't any dropped packet on the ring.

i tried with no luck to:
- put `options pf_ring min_num_slots=65534` `options pf_ring force_ring_lock=1` in `/etc/modprobe.d/pf_ring.conf`.
- reduce the size to 30KB, doubling the number

Here is an example of packets received by 1 interface: [62kPackets.zip](https://github.com/ntop/PF_RING/files/13953152/62kPackets.zip)

Do you have any suggestion?
Thanks

**Comment by rmbq** [comment]
more info:
i use "enable_ip_defrag=1"
reducing the size from 62k to 5k (same amount of total data) seems to help a lot. more packets are received and CPU consumption is decreased by ~20%

**Comment by cardigliano** [comment]
This definitely seems to be related to defragmentation (pf_ring leverages on the kernel support for this), this would explain why you do not see packet loss. We need to dig further into this to see what the linux stack is doing in this case.

**Comment by rmbq** [comment]
i use kernel 4.14.79
Is there any way i can help?

**Comment by rmbq** [comment]
seems like increasing `ipfrag_high_thresh `and `ipfrag_low_thresh` helped a lot
