### ISSUE TITLE
Cannot install ixgbe zero copy drivers

### ISSUE THREAD

**Issue by DerRealKeyser** [ntop/PF_RING#909]
When attempting to configure ixgbe zero copy drivers on Ubuntu 22.04.3 with latest Ntop 6.0 stable (ntopng Enterprise L v.6.0.240110 rev.22572 (Ubuntu 22.04.3 LTS) ) the drivers refuse to install with a dependency error on pfring-dkms:
A full apt-get upgrade has completed just before the attempt, and everything is updated.

[>] Installing ixgbe Zero-Copy driver
Continue (y/n)?y
Hit:1 http://dk.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://dk.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://dk.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.ntop.org/apt-stable/22.04 x64/ InRelease
Hit:6 https://packages.ntop.org/apt-stable/22.04 all/ InRelease
Hit:7 https://packages.clickhouse.com/deb stable InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pfring-dkms is already the newest version (8.6.1.8845).
pfring-dkms set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ixgbe-zc-dkms : Depends: pfring-dkms (= 8.6.1.8820) but 8.6.1.8845 is to be installed
E: Unable to correct problems, you have held broken packages.
[>] Configuring PF_RING
[>] Configuring hugepages
[>] Detecting interfaces using ixgbe
ens1f0
ens1f1
[>] Configuring ixgbe driver with 4 RSS queues
[>] Restarting PF_RING
[>] Configuration completed

**Comment by cardigliano** [comment]
This should've been addressed, please try with apt clean all, update, upgrade

**Comment by DerRealKeyser** [comment]
Hmmm, then I get an update showing some updates have been held back - including ntopng and ntopng-data.
If I try to include those in the upgrade with --with-new-pkgs I get a:

The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: pfring (= 8.6.1-8820) but 8.6.1-8845 is to be installed
E: Broken packages

So it seems I have a "to new" pfring installed or? How do I resolve that? I'm not too experienced in the world of Linux.

**Comment by DerRealKeyser** [comment]
Seems the never pfring and dependencies comes from the Ubuntu distribution and was installed earlier on an apt upgrade.
How is it that repo has a newer pfring than what your stable build on Ntopng has/uses? 
Shouldn't a dependency of the installed ntopng has prevented it from upgrading pfring?

host# sudo apt show -a pfring

Package: pfring
Version: 8.6.1-8845
Status: install ok installed
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 37.5 MB
Depends: ndpi (= 4.8.0-4608), net-tools, kmod, ethtool, pciutils, libelf1, libbpf0, libhiredis0.14
Recommends: pfring-dkms (= 8.6.1.8845)
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
Description: PF_RING (http://www.ntop.org/pf_ring/) [8.6.1-stable:6e316372e30b4c33a14e91b7c3ad511f69b36d91]

Package: pfring
Version: 8.6.1-8820
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 37.5 MB
Depends: ndpi (= 4.8.0-4573), net-tools, kmod, ethtool, pciutils, libelf1, libbpf0, libhiredis0.14
Recommends: pfring-dkms (= 8.6.1.8820)
Download-Size: 4,698 kB
APT-Sources: https://packages.ntop.org/apt-stable/22.04 x64/ Packages
Description: PF_RING (http://www.ntop.org/pf_ring/) [8.6.1-stable:0d1022bde1646f86cdad51337f28729926d427bd]

**Comment by DerRealKeyser** [comment]
Seems its because the current installed NtopNG package (a week old) requires a newer pfring than the latest NtopNG:

host$ sudo apt show -a ntopng

Package: ntopng
Version: 6.0.240117-22602
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 47.6 MB
Depends: ntopng-data (= 6.0.240117), pfring (= 8.6.1-8820), libsqlite3-0, libexpat1, redis-server, librrd8, logrotate, libcurl4, libpcap0.8, libldap-2.5-0, libhiredis0.14, libssl3, libmysqlclient21, librdkafka1, lsb-release, tar, ethtool, libcap2, libcap2-bin, libzstd1, libmaxminddb0, libradcli4, libjson-c5, libsnmp40, udev, whiptail, libmariadb3, libelf1, nmap, libbpf0, debconf, libnuma1, libzmq5, libnetfilter-queue1, ntop-license (= 1.0)
Conflicts: nedge
Replaces: ntop
Download-Size: 9,066 kB
APT-Sources: https://packages.ntop.org/apt-stable/22.04 x64/ Packages
Description: Web-based traffic monitoring.

Package: ntopng
Version: 6.0.240110-22572
Status: install ok installed
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 47.6 MB
Depends: ntopng-data (= 6.0.240110), pfring (= 8.6.1-8845), libsqlite3-0, libexpat1, redis-server, librrd8, logrotate, libcurl4, libpcap0.8, libldap-2.5-0, libhiredis0.14, libssl3, libmysqlclient21, librdkafka1, lsb-release, tar, ethtool, libcap2, libcap2-bin, libzstd1, libmaxminddb0, libradcli4, libjson-c5, libsnmp40, udev, whiptail, libmariadb3, libelf1, nmap, libbpf0, debconf, libnuma1, libzmq5, libnetfilter-queue1, ntop-license (= 1.0)
Conflicts: nedge
Replaces: ntop
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Web-based traffic monitoring.

**Comment by cardigliano** [comment]
It looks like this was caused by a broken ntopng package, I suggest to remove that package and start over

**Comment by DerRealKeyser** [comment]
A complete removal of Ntopng and a autoremove of dependent packages solved the issue.
