### ISSUE TITLE
set_affinity CPU usage goes high in zc at 6 Gbps

### ISSUE THREAD

**Issue by vehere-ccu1** [ntop/PF_RING#914]
At 6 Gbps the CPU(used in load_driver.sh set_affinity ) usage goes up to 70%. As you mentioned ZC does not use IRQ then why is the kernel using the CPU. Once CPU utilization cross 80 % the packet drop can be seen. Happening for all intel ZC cards with all PF version (8.6.0, 8.6.1 and older). How can I solve this? For now I am using multiple RSS and assigning the RSS TxRx to different CPU.

**Comment by cardigliano** [comment]
Which driver are you using?
