### ISSUE TITLE
No forum/community to find help?

### ISSUE THREAD

**Issue by DerRealKeyser** [ntop/PF_RING#919]
Sorry to post this here, but is there no forum/community for ntop/pfring/nprobe available any more?
The discord invite doesn’t work, and there no discoverable discord on that topic. Google can’t find me anything usable in terms of help/support.

Currently testing Ntopng on a raspberry pi (rasbian os Arm64), but there seems to be no pf_ring on that platform, and Ntopng doesn’t have it as a dependecy. Would be nice to eek out the last bit of capture performance by having pf_ring on that platform.

**Comment by cardigliano** [comment]
@DerRealKeyser a new discord link to join the community will be available at https://www.ntop.org/faq/howto-join-public-ntop-discussions/ later today
As of pi systems, as you noticed ntopng is using standard pcap capture on those systems, as they are low-speed systems and pfring (or zc) acceleration does not really make the difference.
