### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by dylanjamesdev** [ntop/PF_RING#922]
Trying to install ntopng and it hangs on this every time. Debian 12.

root@kanc-cr10:/home/sysop# sudo apt-get install nprobe ntopng -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nprobe is already the newest version (10.5.240314-8268).
ntopng is already the newest version (6.1.240314-23075).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up pfring-dkms (8.7.0.8958) ...
Removing old pfring-8.7.0.8958 DKMS files...
Deleting module pfring-8.7.0.8958 completely from the DKMS tree.
Loading new pfring-8.7.0.8958 DKMS files...
Building for 6.1.0-18-amd64
Building for architecture amd64
Building initial module for 6.1.0-18-amd64
Done.

pf_ring.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.1.0-18-amd64/updates/dkms/
depmod...

**Comment by cardigliano** [comment]
Does it hangs forever? Could you check "ps aux" in another terminal to see what command is actually running?
