### ISSUE TITLE
igb-zc make failed

### ISSUE THREAD

**Issue by ws-weisb** [ntop/PF_RING#926]
on 3.10.0-229 error
![image](https://github.com/ntop/PF_RING/assets/107823574/645763b5-19d2-4e52-ae81-1aed98f5bc29)
![image](https://github.com/ntop/PF_RING/assets/107823574/78ce9b29-f1d9-4b17-9a35-984378062296)
`NETIF_F_HW_TC` seems to be provided starting from the 4.16 kernel. What else can I do besides upgrading the kernel?

If there is any documentation on the minimum required kernel version for that, I couldn't find it, so I asked here, tks. 

> 3.10.0-951.21 work!

**Comment by cardigliano** [comment]
@life1988 what OS version are you running?

**Comment by ws-weisb** [comment]
> @life1988 what OS version are you running?

![image](https://github.com/ntop/PF_RING/assets/107823574/d1a8cb1e-149c-4d89-b4ff-0e9dda905df4)
![image](https://github.com/ntop/PF_RING/assets/107823574/a553598b-c470-438e-9b55-ef4fbb160e7d)

maybe this distribution version not patch newest kernel update not like 957, so closed @cardigliano

**Comment by cardigliano** [comment]
Correct, please update the OS

**Comment by ws-weisb** [comment]
> Correct, please update the OS

thk
