### ISSUE TITLE
incorrect ipv6 formate  lead to a  kernel crash

### ISSUE THREAD

**Issue by liuhandsome110** [ntop/PF_RING#928]
Recently during project testing, it was discovered that pfring led to a kernel crash. The issue was identified as being caused by IPv6 packets, and we hope the community can provide assistance to resolve this problem.

tips:
    kernel version: Linux TDA-7.localdomain 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
    pfring version:8.0.0.6892
    crash info:
![image](https://github.com/ntop/PF_RING/assets/25005137/f56be761-9ccd-457b-bedd-638b86fa78ef)
                                                                                                                                                                                   
![image](https://github.com/ntop/PF_RING/assets/25005137/38df781a-4594-4a5b-9046-18df0a9f5aba)
[
[Uploading ipv6_error.zip…]()
](url)

**Comment by cardigliano** [comment]
@liuhandsome110 I realised you are running pfring 8.0, could you try with the latest 8.7 (or at least latest stable 8.6.1)?

**Comment by liuhandsome110** [comment]
@cardigliano I’ve seen the latest code, and this part hasn’t been modified.

**Comment by cardigliano** [comment]
Could you provide a small pcap with a packet able to reproduce this please?
