### ISSUE TITLE
How to switch off debug messages?

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#93]
I have many messages in my syslog like 
May  5 13:10:24 dpi-kamensk kernel: [79770.080807] [PF_RING] eth2 driver -> pf_ring [len=1500]
although debug is not set:

```
# cat /sys/module/e1000e/parameters/enable_debug
0
```

How to turn off debug messages?
PF_RING Version          : 6.3.0 (dev:5bd5c7925b5fb1f526915468297861b09f831904)
Driver loaded by standard load_driver.sh file.

**Comment by cardigliano** [comment]
It should not happen with enable_debug = 0, however I removed the message now.
