### ISSUE TITLE
Can't RX Network traffic is stable on ZC PF_Ring

### ISSUE THREAD

**Issue by 35596035** [ntop/PF_RING#930]
I modify pf_ring,ko.xz min_num_slots=X ，I try any number but RX network traffic is still unstable，if pf_ring have ZC ，modify min_num_slots=X is useful? 
Are there other parameters that can be adjusted?

**Comment by cardigliano** [comment]
min_num_slots is ignored by ZC drivers as kernel is bypassed. The adapter is already configure with the max number of (hw) slots available. What do you mean by "stable"?

**Comment by 35596035** [comment]
Assuming Device A is responsible for sending packets to Device B, under conditions with no interference from other network packets, the TX speed displayed on Device A remains stable, averaging around 700 Mbps.

However, on Device B, where I have enabled PF_RING version 8.6.1 with Zero Copy (ZC) functionality, and where B is receiving packets exclusively from A without interference from other network packets, the observed RX speed on Device B is indeed unstable. Despite B using 16 CPUs to handle packet reception, and with monitoring conducted using bwm-ng on the network card RX and TX, the device is using an i40e network adapter.

**Comment by cardigliano** [comment]
Could you run pfcount on device B, single RSS queue, and provide the statistics generated by pfcount? (run it for a few seconds)

**Comment by cardigliano** [comment]
Closed for inactivity
