### ISSUE TITLE
A Question to "i40e" Driver

### ISSUE THREAD

**Issue by altoliaw** [ntop/PF_RING#931]
To support large packet flows, I clone the PF-RING project with version 8.6.1 from the repository on GitHub, and then install the two drivers of PF-RING, namely “ixgbe” and “i40e”, for simulations to ensure that PF-RING can work on the RHEL 8.7 accurately. However, the “i40e” results confuse me when using the commands, ifconfig and tcpdump from `userland/tcpdump-4.99.1` in the PF-RING repository. To distinguish the difference between the interfaces with “ixgbe” and “i40e”, all simulations have followed the settings as below.

In the beginning, as shown in the following results, the default “ixgbe” driver (from RHEL) works well and the number of the packets is displayed correctly in the RX of the eno2.

```bash
root@ph127144 ~ $ ifconfig
eno2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.152.132  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::baca:3aff:fe61:f762  prefixlen 64  scopeid 0x20<link>
        ether b8:ca:3a:61:f7:62  txqueuelen 1000  (Ethernet)
        RX packets 153086  bytes 11766381 (11.2 MiB)
        RX errors 0  dropped 3238  overruns 0  frame 0
        TX packets 50  bytes 4948 (4.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

After installing the given “ixgbe” driver from PF-RING, the eno2 also works fine and the results are similar to the ones above. In addition, the verification with the command, `tcpdump`, which is provided by the PF-RING project (`userland/tcpdump-4.99.1`), can list all packet information when packets are transferred from the other device.

As for the “i40e” driver, the default driver works fine and shows the number of packets; however, there are no packets in RX when installing the “i40e” driver provided by PF-RING. The results are displayed as follows.

```bash
root@ph127144 ~ $ ifconfig
ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 3c:fd:fe:d8:38:31  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1857980758  bytes 1309653408942 (1.1 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

What aspects might I have overlooked in “i40e”?

**Comment by cardigliano** [comment]
@altoliaw are you running the ZC drivers or the standard drivers? Could you provide full information about the steps you are following and the configuration? Thank you.

**Comment by altoliaw** [comment]
Sorry for the late reply. 

After several simulations, I found the reason regarding when the situation above occurs. That is, the two different devices where both devices are installed PF-RING are sending packets to the other one and receiving arrived packets simultaneously. For example, given two devices, A and B, my co-worker transfers packets from A to B and I transfer packets in the opposite direction at the same time. As a result, both devices fail to receive any packets and the number of received packets (RX) is zero.

Although the situation can be explained logically, the situation mentioned previously will occur in the real world. Is this situation normal? Are there any suggestions or mechanisms to avoid the above-mentioned situation?

**Comment by cardigliano** [comment]
@altoliaw please note the adapter cannot be opened twice (from two different processes at the same time) when using zero-copy drivers, this might explain what you see.
