### ISSUE TITLE
kernel module makefile side effets removing linux-headers files

### ISSUE THREAD

**Issue by noraj** [ntop/PF_RING#934]
It seems the `clean` command in this makefile may generate side-effects.

https://github.com/ntop/PF_RING/blob/8cda9fc2ee0a3eb34493ac28f42d274d685c44b3/kernel/Makefile#L77

Refs.

- https://bbs.archlinux.org/viewtopic.php?pid=2172370
- https://github.com/BlackArch/blackarch/issues/4144

I'm not sure but isn't `*#` dangerous? It successfully removes files named like `a#`. But isn't there some case where it will be interpreted as `*` followed by a comment, where other files could end up being deleted? Then `*\#` sounds a bit safer.

My guess may be wrong but pf_ring module seems to remove some files from `linux-headers`.

**Comment by cardigliano** [comment]
Removed in eb42f8795516c096ca2f93f1b0747d31bbedb15d as it does not seem useful, yet unsafe
