### ISSUE TITLE
ice-zc driver error in Rocky Linux 9.2 & 9.3 under XCP-ng 8.2 (Xen)

### ISSUE THREAD

**Issue by fandigunawan** [ntop/PF_RING#935]
Hi I would like to report issues that I found while using Zero Copy ice device (E810).
Informations:
- Virtualization: XCP-NG 8,2
- Guest OS: Rocky Linux 9.2 and 9.3
- Device: Intel E810
- PF_RING version: pfring-8.6.1-9112

I found Zero Copy working if I used X710 (i40e-zc) under XCP-NG 8.2 and Rocky Linux 9.3 with different server.
It is also working just fine if we are not using XCP-NG (no virtualization) under the same machine.

Please find the attached dmesg log of ice-zc and i40e-zc for comparison.
[ice-zc under Rocky Linux 9.3](https://github.com/ntop/PF_RING/files/15371518/dmesg_log_nok_rl93_ice.log)
[i40e-zc under Rocky Linux 9.3](https://github.com/ntop/PF_RING/files/15371520/dmesg_log_ok_rl93_i40e.log)

**Comment by fandigunawan** [comment]
Found solution by extending Xen IRQs size from default 64 due to1024. It is due to E810 requests bigger IRQs.
```
/opt/xensource/libexec/xen-cmdline --set-xen "extra_guest_irqs=1024"
```

Please mark this issue as resolved.

**Comment by cardigliano** [comment]
The user found a solution by extending Xen IRQs size from default 64 due to 1024 as this was due to E810 requesting more IRQs.

/opt/xensource/libexec/xen-cmdline --set-xen "extra_guest_irqs=1024"

**Comment by fandigunawan** [comment]
Found solution by extending Xen IRQs size from default 64 due to1024. It is due to E810 requests bigger IRQs.
```
/opt/xensource/libexec/xen-cmdline --set-xen "extra_guest_irqs=1024"
```
Please mark this issue as resolved.
