### ISSUE TITLE
Issues of Packet Loss and Drivers' Dependency

### ISSUE THREAD

**Issue by altoliaw** [ntop/PF_RING#936]
To increase NIC packet reception and reduce packet loss, I have migrated our application from using PF-RING to PF-RING ZC with RSS over the past few weeks. The migration has been generally successful, except for some issues with packet loss. In PF-RING ZC, packet loss information is not available in `/proc/net/pf_ring/ens2f1`. To obtain real-time packet loss information, I attempted to monitor the application using `pfcount`. Unfortunately, an error occurred because the application occupied the interface `zc:ens2f1@0`, preventing `pfcount` from enabling the ring on the same interface.

Is there a way to obtain real-time packet loss information from an application using PF-RING ZC with RSS?

Additionally, I have encountered issues with the `ixgbe` and `i40e` drivers. When the `i40e` driver is loaded using the `modprobe` command, pf_ring is automatically loaded as a dependency. However, this automatic loading does not occur with the `ixgbe` driver, as shown in the following figure. This inconsistency is puzzling.
Is this behavior normal, and if not, what could be causing this inconsistency?

![messageImage_1716273224583](https://github.com/ntop/PF_RING/assets/6938753/787cafad-574f-47bc-a8fd-a0f7cc51aa68)

**Comment by cardigliano** [comment]
@altoliaw I suggest using the systemd service to load the driver as explained in the user's guide, that will automatically load all the dependencies, or use the pf_ringcfg script which is also creating the configuration

**Comment by cardigliano** [comment]
Details are being discussed by email (closing)
