### ISSUE TITLE
kernel module makefile side effets removing linux-headers files

### ISSUE THREAD

**Issue by nvzeppelin** [ntop/PF_RING#937]
follow up to #934 
wasn't fixed in upstream due to issue lying in the line above the modified one.
The issue is due use of no longer working args as described in pull request #925

**Comment by cardigliano** [comment]
I am not sure I got this, please send a PR or provide a patch to make it clear. Thank you.

**Comment by nvzeppelin** [comment]
> I am not sure I got this, please send a PR or provide a patch to make it clear. Thank you.

#925 is a pr

**Comment by cardigliano** [comment]
PR accepted, thank you
