### ISSUE TITLE
Add the libpcap include files to the pfring RPM

### ISSUE THREAD

**Issue by mvi57** [ntop/PF_RING#938]
The libpcap library is in the pfring RPM but the include files that go with the library are not there, which makes it hard to compile programs that will use the library.  Please add the pcap include files to the RPM.

**Comment by cardigliano** [comment]
The libpcap library distributed with the pfring package is meant to be used by applications already built and compiled for libpcap. For compiling the application we suggest to use the header files already available in the mainstream package (libpcap-dev / libpcap-devel).
