### ISSUE TITLE
PF_RING ARM64 support

### ISSUE THREAD

**Issue by DerRealKeyser** [ntop/PF_RING#944]
I’m missing pf_ring on ARM64 architecture machines in the repositories. 
I can tell for your own text and website that pf_ring has once existed for ARM, but why is that no longer the case?

It would be great to be able to squeeze a some more throughput out of nProbe/NtopNG on Raspberry Pi. 

Any reason ARM architecture was dropped?

**Comment by cardigliano** [comment]
@DerRealKeyser we actually never released official packages for pfring on ARM, however there are users cloning and compiling it from github. nprobe and ntopng packages actually do not have the pfring support enabled on rPI, in any case I would not expect a major performance improvement on that device.

**Comment by DerRealKeyser** [comment]
> @DerRealKeyser we actually never released official packages for pfring on ARM, however there are users cloning and compiling it from github. nprobe and ntopng packages actually do not have the pfring support enabled on rPI, in any case I would not expect a major performance improvement on that device.

Ohh, I'm sorry to hear that :-( 
May I ask why you decided not to support pfring in NtopNG/nProbe on Raspberry pi - or deploy a official arm build? 
Not only is the Pi a great training platform, but the Pi5 with a pfRing enabled nProbe could be the GREATEST little Gigabit wirespeed probe to deploy around the network (POE powered, so, plug and play - no extra wires). 
With pfRing I'm quite certain a Pi5 could do full Gigabit probing with nDPI and ZMQ it back to NtopNG via its WiFi interface or a USB ethernet port..

**Comment by lucaderi** [comment]
You can compile PF_RING from source: it will work. At the moment we support pnly nVidia BlueFiled that is ARM64
