### ISSUE TITLE
Is it allowed to use linux/pf_ring.h header file on terms of LGPLv2.1?

### ISSUE THREAD

**Issue by TuliMyrskyTaivas** [ntop/PF_RING#946]
There is pf_ring.h header file which is a part of the kernel module (GPLv2) included by the user space library (LGPLv2.1) to access the socket API (data structures).

Does this allow me, as a developer of non-GPLv2 project, to use this file on terms of LGPLv2.1 license since the entire user space library libpfring is licensed under LGPLv2.1 license?

**Comment by cardigliano** [comment]
Yes, as already replied by mail
