### ISSUE TITLE
Question related to ftflow.c

### ISSUE THREAD

**Issue by jsb9945** [ntop/PF_RING#949]
Hello!

I've been greatly helped by the open source you provided.

I'm trying to print out packet metadata in real time using ftflow.c file now, and I'd appreciate it if you could check if my method is wrong.

I'm trying to run the processFlow function inside the packet_consumer function. But I think I should use the flow data, but I don't know where to get it.

I would appreciate it if you could let me know if there is another way to output metadata in real time.

Thank you.

**Comment by cardigliano** [comment]
ftflow should be used as example for processing packets and extract flow metadata, please take a look at pfcount for packet parsing.
