### ISSUE TITLE
Why and when I should use a pfring_zc_sync_queue?

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#95]
What is purpose of pfring_zc_sync_queue() function? When I need to use this?
Sorry, I don't found this in the source code.

**Comment by cardigliano** [comment]
pfring_zc_sync_queue should be used to flush all buffers in a queue when calling pfring_zc_send_pkt() with flush_packet = 0
(calling pfring_zc_send_pkt() with flush_packet = 1 for every packet reduces the queue performance)

Alfredo

**Comment by Skryabind** [comment]
Thanks a lot!
