### ISSUE TITLE
Stable packages for Ubuntu 24.04

### ISSUE THREAD

**Issue by rojer** [ntop/PF_RING#950]
Ubuntu 24.04 is the new LTS release is out but stable ntop packages for it are not available.
https://packages.ntop.org/apt/24.04/x64/Packages is ok
https://packages.ntop.org/apt-stable/24.04/x64/Packages is empty

**Comment by rojer** [comment]
cc @jurjenwestra78 who previously helped with [22.04 support](https://github.com/ntop/PF_RING/issues/793).

**Comment by cardigliano** [comment]
This will be released today!

**Comment by rojer** [comment]
today is 5 days later and still no stable packages

**Comment by cardigliano** [comment]
@rojer we released the new stable for pf_ring last week actually, however we are still in the process of updating the repository for the 24 as we are also releasing the other products, sorry for the delay

https://www.ntop.org/pf_ring/released-pf_ring-8-8-flow-table-offload-and-nvidia-bluefield-support/

**Comment by cardigliano** [comment]
Repo released a few days ago
