### ISSUE TITLE
PF_Ring or PF_ring ZC support on non RHEL linux distributions

### ISSUE THREAD

**Issue by Yasminkundur** [ntop/PF_RING#954]
Hi Team,

Can you please confirm do we have support for non RHEL Linux distribution like Alma, Rocky and Oracle Linux for PF_RING and PF_RING ZC flavors?

This is in order to have alternate OS when compared to RHEL OS.

**Comment by cardigliano** [comment]
Rocky Linux is officially supported, however it should be compatible also with the other RH based distributions as the kernel is the same
