### ISSUE TITLE
Does PF_RING support Oracle OS 9.4?

### ISSUE THREAD

**Issue by xyzheng0706** [ntop/PF_RING#958]
Could you help to check if PF_RING suppport oracle 9.4?
When I build PF_RING 8.8.0 stable version in oracle 9.4, the "uname -r" shows 5.15.0-209.161.7.2.el9uek.x86_64
and when build drivers,  e1000e have below errors, also ice have many errors.

  CC [M]  PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.o
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c: In function ‘e1000e_set_interrupt_capability’:
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:2433:35: error: this statement may fall through [-Werror=implicit-fallthrough=]
 2433 |                 adapter->int_mode = E1000E_INT_MODE_MSI;
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:2435:9: note: here
 2435 |         case E1000E_INT_MODE_MSI:
      |         ^~~~
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c: In function ‘e1000e_reset’:
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:4964:20: error: this statement may fall through [-Werror=implicit-fallthrough=]
 4964 |                 if (adapter->netdev->mtu > ETH_DATA_LEN) {
      |                    ^
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:4972:9: note: here
 4972 |         default:
      |         ^~~~~~~
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c: In function ‘e1000_setup_rctl’:
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:3693:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
 3693 |                         psrctl |= PAGE_SIZE << E1000_PSRCTL_BSIZE3_SHIFT;
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:3695:17: note: here
 3695 |                 case 2:
      |                 ^~~~
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:3696:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
 3696 |                         psrctl |= PAGE_SIZE << E1000_PSRCTL_BSIZE2_SHIFT;
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:3698:17: note: here
 3698 |                 case 1:
      |                 ^~~~
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c: In function ‘__e1000e_disable_aspm’:
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:8065:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
 8065 |                 aspm_dis_mask |= PCI_EXP_LNKCTL_ASPM_L0S;
PF_RING-8.8.0-stable/drivers/intel/e1000e/e1000e-3.8.7-zc/src/netdev.c:8067:9: note: here
 8067 |         case PCIE_LINK_STATE_L1:
      |         ^~~~
cc1: all warnings being treated as errors

Thanks very much

**Comment by cardigliano** [comment]
We do our best to support most of the kernels, however Oracle OS is not one of the distribution we officially support sorry

**Comment by xyzheng0706** [comment]
Thank you @cardigliano
