### ISSUE TITLE
Make VLAN ID optional field in PF_RING FT key

### ISSUE THREAD

**Issue by ronygut** [ntop/PF_RING#959]
Make VLAN ID optional field in PF_RING FT key.
In some situation we will not want to use VLAN ID as part of the flow key.
The request is to allow this field to be an optional field in the FT key.

**Comment by cardigliano** [comment]
pfring_ft_create_table now supports a new PFRING_FT_IGNORE_VLAN flag

**Comment by ronygut** [comment]
Thanks for the new feature!

I have 2 questions though:

1. We just purchased a license for PF_RING FT version 8.7.0.240730 (a week ago) , do we need to purchase new license to use the new VLAN IGNORE flag?

2. How do make sure before pulling new PF RING FT from gisthub that the version is the same as nDPI?
In the past we had a problem with mismatch versions that was fixed by you. Is it possible to see in advance that there is a mismatch in github with PF_RING FT and nDPI?

**Comment by cardigliano** [comment]
The license includes 1 year updates, thus you can safely upgrade.
The latest FT lib is in sync with the latest nDPI.

**Comment by ronygut** [comment]
Thanks for the answer!
Another quick question, a session can potentially have 2 different VLAN ID for client and server. (Different network segments)
Currently I only see one field for VLAN ID in flow key.
How do you support this situation?

**Comment by cardigliano** [comment]
This is not supported, a single (first) vlan id is currently stored in the flow key (which is ignored with the PFRING_FT_IGNORE_VLAN flag)

**Comment by cardigliano** [comment]
Note that you can use the users metadata to add additional info

**Comment by ronygut** [comment]
@cardigliano 
The VLAN ID in the flow is the outer VLAN if we have multiple VLAN encapsulated, or the inner one?

**Comment by cardigliano** [comment]
In case of nested vlans, the flow contains the inner one

**Comment by ronygut** [comment]
@cardigliano , does PF_RING FT ignore IP fragmented packet? e.g. if a packet with fragmentation offset is sent to pfring_ft_process is it ignored and  pfring_ft_set_flow_packet_callback is not called?

I want to also process fragmented IP packets and reassemble them.

do you reassemble fragmented IP packets?

**Comment by cardigliano** [comment]
@ronygut FT actually implements a cache to handle fragmented traffic

**Comment by ronygut** [comment]
@cardigliano , so FT handles fragmented IP packets and aggregate the fragments transparently?
Do I need to enable something for that, or it is done automatically?

**Comment by cardigliano** [comment]
Yes, as long as it is possible to aggregate fragments (they need to be close in time etc.) they are transparently accounted

**Comment by ronygut** [comment]
@cardigliano , when using FT , if I have a connection on port 80, does the NDPI classifier will classify the connection as HTTP only if it see HTTP data or it can also classify it as HTTP protocol if no HTTP data found, but because the connection is on known HTTP port, in this case port 80?
What I mean is if I have connection on port 80 and there is no HTTP data, will the NDPI classifier classify this as HTTP because it is on know HTTP port 80 or as Unknown?

**Comment by cardigliano** [comment]
Replied on the ndpi repo, let's keep discussing there about this

**Comment by ronygut** [comment]
@cardigliano , I downloaded the latest stable pf_ring-8.8.-stable and I don't find the VLAN ignore feature.
I'm getting PFRING_FT_IGNORE_VLAN undefined symbol.
In which version of PF_RING was it added?
I only see it in the dev branch.
In order to use it I need to build the dev branch?
Which NDPI version should I take? the dev or 4.10 stable branch?

**Comment by cardigliano** [comment]
PFRING_FT_IGNORE_VLAN has been introduced in PF_RING 8.9 (dev branch)

**Comment by ronygut** [comment]
@cardigliano , and which NDPI branch should I use with it so it will be compatible?

**Comment by cardigliano** [comment]
Latest dev branch also for nDPI

**Comment by ronygut** [comment]
@cardigliano 
I'm getting *** ndpi library version mismatch, expected API rev.11589 (4.11.0) found rev.11599 (4.11.0-4972-ccbbcdf) ***

**Comment by cardigliano** [comment]
Please try updating from github or wait for the next build later today

**Comment by ronygut** [comment]
@cardigliano Update NDPI or PF_RING from github?

**Comment by cardigliano** [comment]
They both need to be at the latest version to be aligned

**Comment by ronygut** [comment]
@cardigliano 
I downloaded both an hour ago, both from dev branch and I got the mismatch error.
did you update both?

**Comment by cardigliano** [comment]
I pushed a pfring update a few minutes ago
