### ISSUE TITLE
Does pf_ring support iptables TEE rule?

### ISSUE THREAD

**Issue by Ferozmd7** [ntop/PF_RING#960]
Need to configure IPTables rule to copy incoming traffic to another gateway/interface.

Requirement is application should run with PF_Ring and mirror the Incoming and Outgoing GTP control packets to external application for monitoring

Does it bypasses netfilter?

This is our rule:
sudo iptables -t mangle -A PREROUTING -i eth0  -p udp --dport 2123 -j TEE --gateway 192.168.100.101

**Comment by cardigliano** [comment]
PF_RING captures traffic on the interface, before (or after) iptables comes into play

**Comment by Ferozmd7** [comment]
> PF_RING captures traffic on the interface, before (or after) iptables comes into play

Could you explain the process flow and how it will work? Please simplify the explanation for me.

**Comment by cardigliano** [comment]
Please take a look at this picture which is self explanatory, the "sniffer process" captures packets close to the adapter, before iptables/netfilter receives traffic.
![Packet-capture-in-Linux-Kernel ppm](https://github.com/user-attachments/assets/68bf5fa7-8066-44e9-9794-3d64fa5cb4e1)
