### ISSUE TITLE
Pfring-dkms 8.4 install broken on kernel >=5.15.0-117

### ISSUE THREAD

**Issue by bigF93** [ntop/PF_RING#961]
Hi,
In my project we are using pfring 8.4.
A recent update of the kernel broke the dkms package build.
We noticed that the commit https://github.com/ntop/PF_RING/commit/c71ea0d4b1334e05bdad021fe64775cebcf6778f
fixes the issue, but I just wanted to ask you, do you see any problems in backporting that commit internally from 8.8 to 8.4?

thank you very much,
Cheers

**Comment by cardigliano** [comment]
@mfornaroli you can backport the patch or just get the new driver from the latest code
