### ISSUE TITLE
PFring ZC: what must be the put of (pfcount -i zc:"name of interface") in a cluster mode? 

### ISSUE THREAD

**Issue by ArmanSabzevari** [ntop/PF_RING#963]
How we can say ZC is being applied correctly? I see that conn.log file is growing. I see that "pf_ringcfg --list-interfaces" returned all interfaces are running ZC but I have just 1 license for 1 interface. So, I think "pf_ringcfg --list-interfaces" can not tell me if currently what I see in conn.log is extracted by ZC pfring and it could be just pfring vanilla.
 
the only worker we have for zeek:
[worker-1]
type=worker
host=127.0.0.1
interface=zc:99
lb_method=pf_ring
lb_procs=14
pin_cpus=5,7,9,11,13,15,17,19,21,23,25,27,29,31

cat info:
PF_RING Version : 8.8.0 (unknown)
Total rings : 30

Standard (non ZC) Options
Ring slots : 4096
Slot version : 21
Capture TX : Yes [RX+TX]
IP Defragment : No
Socket Mode : Standard
Cluster Fragment Queue : 0
Cluster Fragment Discard : 0

pfcount -i zc:enp94s0f0
Using PF_RING v.8.8.0.240805 kernel module v.8.8.0
Dumping statistics on /proc/net/pf_ring/stats/45585-enp94s0f0.41
Unable to enable ring :-(

sudo pfcount -i zc:99
pfring_open error [Resource temporarily unavailable] (pf_ring not loaded or interface zc:99 is down ?)

**Comment by cardigliano** [comment]
pf_ringcfg --list-interfaces is reporting as "Running" those interfaces who have the ZC driver actually loaded, regardless of the license. pfcount -i zc:enp94s0f0 should run as long as there is no other application using enp94s0f0. pfcount -i zc:99 should run as long as you have a zc cluster with ID 99 (e.g. zbalance_ipc).
