### ISSUE TITLE
Opening zc device with PF_RING_ZC_DEVICE_HW_TIMESTAMP distorts PTP clock

### ISSUE THREAD

**Issue by TIE1996** [ntop/PF_RING#966]
I've seen a strange behaviour when using phc2sys to synchronize the PTP clock of the network card to system time and then opening a PF_Ring application that uses hardware timestamps. I'm running the synchronisation using
`/usr/sbin/phc2sys -O 0 -l 6 -s CLOCK_REALTIME -c enps0f0 -m`
and see that the clock is synced down to several nanoseconds.
When I now open a different terminal and use zcount with HW timestamps
`sudo zcount -i enps0f0  -X`
I can see, that PTP clock jumped forward:
```
phc2sys[4059.699]: enps0f0   sys offset         0 s2 freq  +97414 delay   3662
phc2sys[4060.699]: enps0f0  sys offset       -27 s2 freq  +97387 delay   3656
phc2sys[4061.699]: clockcheck: clock jumped forward or running faster than expected!
phc2sys[4061.699]: enps0f0  sys offset 1039723456473 s0 freq  +97387 delay   3502
phc2sys[4062.700]: enps0f0  sys offset 1039723456415 s2 freq  +97348 delay   3698
phc2sys[4063.700]: enps0f0  sys offset 1039723456469 s2 freq +62499999 delay   3666
```

Running the same code without the -X option does not lead to this issue, which leads me to believe that the issue stems from the flag named in the title.

**Comment by cardigliano** [comment]
What is the adapter model? Thank you

**Comment by TIE1996** [comment]
Hi thank you for the quick reply, I'm using the Intel I350 and the Intel E810.

**Comment by cardigliano** [comment]
And are you experiencing the same behaviour with both i350 and E810?

**Comment by TIE1996** [comment]
Hi, I just ran a quick test. The problem only occurs with the Intel I350 card.

**Comment by cardigliano** [comment]
I pushed a patch to avoid syncing the hw clock with an option (the library was syncing the adapter time to the system time, creating the issue, but we want to keep this as default for backward compatibility). There is a new -U option in zcount to disable this. Please update and add -U to your command line.

**Comment by TIE1996** [comment]
Hi, the patch worked. Thank you!
I'm closing the issue now.

**Comment by cardigliano** [comment]
Great, thank you
