### ISSUE TITLE
When using PF_RING FT how does NDPI classifier works when there are 2 protocols in the PCAP file

### ISSUE THREAD

**Issue by ronygut** [ntop/PF_RING#971]
I have a sample PCAP file that contains RDP and TLS in it. (Attached) (Rename .txt to .pcap)
[rdp.pcap.txt](https://github.com/user-attachments/files/18006845/rdp.pcap.txt)
When running ftflow_pcap on it, it is detected as TLS.
The PCAP contains also RDP.
Is it possible to get both TLS and RDP from NDPI?
Your help is appreciated.
Thanks,
Rony.

**Comment by cardigliano** [comment]
I suggest to analyse the pcap with ndpiReader, part of nDPI. If you see the same issue, please open a ticket in the nDPI repo.
