### ISSUE TITLE
Optimization for running PF_RING FT with 100Gbit/second

### ISSUE THREAD

**Issue by ronygut** [ntop/PF_RING#972]
@cardigliano
We got the Intel E810 card and we are performing test to check performance.
What is the optimized insmod command for the ice driver to be used with 100Gbit/sec traffic?
e.g. MQ, and RSS parameters?
What should be the huge pages size ?
Any other information you can provide would be much appreciated.
Thanks,
Rony.

**Comment by ronygut** [comment]
@cardigliano , can you please help regarding this issue?
Thanks,
Rony.

**Comment by cardigliano** [comment]
If you are using our systemd service or load script, no need of special settings, besides the number of RSS queues if the application can leverage on multiqueue capture. The supported hugepage size by ZC is 2MB.

**Comment by ronygut** [comment]
@cardigliano 
I'm building PF_RING from source. I'm not using systemd.
I'm using load_driver script and I need your recommendation for the parameter for insmod command with ice.ko driver.
RSS parameter and MQ parameter.
Our application can support multi queue capture.
How much huge pages did you use, 2048, 4096?
What is the recommended number for RSS and MQ for high load, like 25Gbit/second of traffic.
What did you se when you run your performance tests for ~100Gbit/second?

**Comment by cardigliano** [comment]
The number of hugepages depends on the application/configuration (number of queues, queue size, etc), however if the number of hugepages is too low, the application would not run at all (and you need to increase it).
At 25Gbps even 1/2 RSS queues are enough, this depends on the application performance. At 100 Gbps we usually use 16 queues (e.g. in nProbe Cento).

**Comment by ronygut** [comment]
@cardigliano 
Regarding RSS, do you mean for 25Gbps :
insmode ./ice.ko RSS=2,2,2,2
and in case of 100Gbps:
insmode ./ice.ko RSS=16,16,16,16

We have a machine with 1 processor that contains 24 cores , total including hipper threading, 48 cores.

**Comment by ronygut** [comment]
@cardigliano 
I wanted to also check:
./zbalance_ipc -i zc:ens192 -c 2 -n 4 -m 1
it opened 4 queues:
09/Dec/2024 10:39:20 [zbalance_ipc.c:1586]      pfcount -i zc:2@0
09/Dec/2024 10:39:20 [zbalance_ipc.c:1586]      pfcount -i zc:2@1
09/Dec/2024 10:39:20 [zbalance_ipc.c:1586]      pfcount -i zc:2@2
09/Dec/2024 10:39:20 [zbalance_ipc.c:1586]      pfcount -i zc:2@3

I tried to open from my app one of the queues for example zc:2@0 and it gave me the following error:
Could not open device zc:2@0 , error: Socket operation on non-socket

If I open the device myself without zbalance_ipc, e.g.  zc:ens192, everything works fine.
What could be the problem that I can't open the device that zbalance_ipc created , but can open the main device zc:ens192 (without running zbalance_ipc )
