### ISSUE TITLE
How to set Intel e810 with ICE driver to work with 2 tuple or 4 tuple TCP/UDP hashing  with RSS enabled using PF_RING script

### ISSUE THREAD

**Issue by ronygut** [ntop/PF_RING#974]
How to set Intel e810 with ICE driver to work with 2 tuple or 4 tuple TCP/UDP hashing  with RSS enabled using PF_RING script.
Can you supply examples to add to the load driver script?

**Comment by ronygut** [comment]
Running 
sudo ethtool -N ens192 rx-flow-hash tcp4 sd
sudo ethtool -N ens192 rx-flow-hash udp4 sd
and then checking with ethtool -x ens192 gives:

RSS hash function:
    toeplitz: on
    xor: off
    crc32: off

running ethtool -n 
36 RX rings available
Total 0 rules

**Comment by cardigliano** [comment]
@ronygut the way you are configuring rss should work (it worked in our lab)

2-tuple
sudo ethtool -N ens192 rx-flow-hash tcp4 sd
sudo ethtool -N ens192 rx-flow-hash udp4 sd

4-tuple
sudo ethtool -N ens192 rx-flow-hash tcp4 sdfn
sudo ethtool -N ens192 rx-flow-hash udp4 sdfn

**Comment by ronygut** [comment]
@cardigliano 
Which output do you get after running those commands?

when I ran
ethtool -x ens192 

I still get:
toeplitz: on
xor: off
crc32: off

also ethtool -n ens192 gives:
36 RX rings available
Total 0 rules

Is it OK? 

shouldn't it give this output instead after running the hash commands for 2 tuple , and not the output that I get?
RSS hash function:
    tcp4: sd
    udp4: sd
