### ISSUE TITLE
Sources for userland/lib/libs absent.

### ISSUE THREAD

**Issue by rdpmc** [ntop/PF_RING#99]
Hello!
Why sources for userland/lib/libs are absent in source tree?
I need full sources of project.

**Comment by cardigliano** [comment]
The source code is available at https://github.com/ntop/PF_RING/tree/dev/userland/lib. Commercial ZC extensions are not released in source at the moment. What are you looking for with source? Is there anything we need to add to satisfy your needs?

**Comment by rdpmc** [comment]
It's a license question/problem for my project. Can I build some minimalistic version of PF_RING lib not using this commercial extensions and use it for Suricata for example? I just want to get traffic fast in pf-ring mode. May be is it possible no to use some or all of these exentions in libs? 
Thanks for fast response.

**Comment by cardigliano** [comment]
Yes, just remove the binary libraries form the libs folder and re-configure/make

**Comment by rdpmc** [comment]
Thank you very much, it's built ok. My final question - what does this binary extention gives in addition to simple pf_ring? this DNA support  or smth else?

**Comment by cardigliano** [comment]
ZC support (new generation DNA) and support for FPGA cards including Napatech and Myricom.
